Wrims-engine: wrimsv2.components.IntDouble Class Reference
wrimsv2.components.IntDouble Class Reference
Public Member Functions
IntDouble ()
IntDouble (Number value, boolean isInt)
IntDouble (Number value, boolean isInt, String name, int index)
IntDouble copyOf ()
Number getData ()
int getIndex ()
String getName ()
boolean isInt ()
void setData (Number value)
void setIndex (int index)
void setInt (boolean isInt)
void setName (String argName)
Private Attributes
String argName =""
Number data
int index
boolean isInteger
Detailed Description
Definition at line 5 of file IntDouble.java.
Constructor & Destructor Documentation
IntDouble() [1/3]
wrimsv2.components.IntDouble.IntDouble ()
Definition at line 11 of file IntDouble.java.
Referenced by copyOf().
IntDouble() [2/3]
wrimsv2.components.IntDouble.IntDouble (Number value, boolean isInt)
Definition at line 14 of file IntDouble.java.
References argName, data, isInt(), and isInteger.
IntDouble() [3/3]
wrimsv2.components.IntDouble.IntDouble (Number value, boolean isInt, String name, int index)
Definition at line 20 of file IntDouble.java.
References argName, data, index, isInt(), and isInteger.
Member Function Documentation
copyOf()
IntDouble wrimsv2.components.IntDouble.copyOf ()
Definition at line 43 of file IntDouble.java.
References IntDouble(), data, and isInteger.
Referenced by wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), and wrimsv2.commondata.wresldata.ModelDataSet.processSvar().
getData()
Number wrimsv2.components.IntDouble.getData ()
Definition at line 27 of file IntDouble.java.
References data.
Referenced by wrimsv2.evaluator.ValueEvaluation.abs(), wrimsv2.evaluator.Evaluation.absOperation(), wrimsv2.evaluator.Evaluation.acos(), wrimsv2.evaluator.ValueEvaluation.acos(), wrimsv2.evaluator.Evaluation.acot(), wrimsv2.evaluator.ValueEvaluation.acot(), wrimsv2.evaluator.Evaluation.add(), wrimsv2.evaluator.ValueEvaluation.add(), wrimsv2.evaluator.Evaluation.addOperation(), wrimsv2.evaluator.Evaluation.argFunction(), wrimsv2.evaluator.Evaluation.asin(), wrimsv2.evaluator.ValueEvaluation.asin(), wrimsv2.evaluator.AssignPastCycleVariable.assignAlias(), wrimsv2.evaluator.AssignPastCycleVariable.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.evaluator.AssignPastCycleVariable.assignSvar(), wrimsv2.evaluator.Evaluation.assignWhereStatement(), wrimsv2.evaluator.Evaluation.atan(), wrimsv2.evaluator.ValueEvaluation.atan(), wrimsv2.tools.RCCComparison.compareConstraint(), wrimsv2.evaluator.Evaluation.cos(), wrimsv2.evaluator.ValueEvaluation.cos(), wrimsv2.evaluator.Evaluation.cot(), wrimsv2.evaluator.ValueEvaluation.cot(), wrimsv2.evaluator.Evaluation.divide(), wrimsv2.evaluator.ValueEvaluation.divide(), wrimsv2.evaluator.Evaluation.divideOperation(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exp(), wrimsv2.evaluator.Evaluation.expOperation(), wrimsv2.components.DebugInterface.getAllControlGoalName(), wrimsv2.components.DebugInterface.getAllGoalFile(), wrimsv2.components.DebugInterface.getAllGoalString(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.commondata.wresldata.TimeArray.getTimeArraySize(), wrimsv2.evaluator.WeightEval.getTimeArraySize(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.ValueEvaluation.getTimeSeries(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.intFunc(), wrimsv2.evaluator.Evaluation.intOperation(), wrimsv2.evaluator.ValueEvaluation.log(), wrimsv2.evaluator.ValueEvaluation.log10(), wrimsv2.evaluator.Evaluation.log10Operation(), wrimsv2.evaluator.Evaluation.logOperation(), wrimsv2.evaluator.ValueEvaluation.max(), wrimsv2.evaluator.Evaluation.maxOperation(), wrimsv2.evaluator.ValueEvaluation.min(), wrimsv2.evaluator.Evaluation.minOperation(), wrimsv2.evaluator.ValueEvaluation.mod(), wrimsv2.evaluator.Evaluation.modOperation(), wrimsv2.evaluator.Evaluation.mult(), wrimsv2.evaluator.ValueEvaluation.mult(), wrimsv2.evaluator.Evaluation.multiplyOperation(), wrimsv2.solver.Gurobi.GurobiSolver.Output(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pow(), wrimsv2.evaluator.Evaluation.powOperation(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.evaluator.ValueEvaluation.realFunc(), wrimsv2.evaluator.Evaluation.realOperation(), wrimsv2.evaluator.Evaluation.relationStatement(), wrimsv2.evaluator.ValueEvaluation.relationStatement(), wrimsv2.evaluator.ValueEvaluation.round(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), wrimsv2.solver.CbcSolver.setConstraintsSkip(), wrimsv2.evaluator.Evaluation.sin(), wrimsv2.evaluator.ValueEvaluation.sin(), wrimsv2.evaluator.Evaluation.substract(), wrimsv2.evaluator.ValueEvaluation.substract(), wrimsv2.evaluator.Evaluation.substractOperation(), wrimsv2.evaluator.Evaluation.tan(), wrimsv2.evaluator.ValueEvaluation.tan(), wrimsv2.evaluator.Evaluation.term_IDENT(), wrimsv2.evaluator.ValueEvaluation.term_IDENT(), wrimsv2.evaluator.Evaluation.term_SVAR(), wrimsv2.evaluator.ValueEvaluation.term_SVAR(), wrimsv2.evaluator.Evaluation.trunk_timeArray(), wrimsv2.evaluator.ValueEvaluation.trunk_timeArray(), wrimsv2.evaluator.Evaluation.unary(), and wrimsv2.hdf5.HDF5Util.writeCycleDynamicSv().
getIndex()
int wrimsv2.components.IntDouble.getIndex ()
Definition at line 61 of file IntDouble.java.
References index.
getName()
String wrimsv2.components.IntDouble.getName ()
Definition at line 53 of file IntDouble.java.
References argName.
isInt()
boolean wrimsv2.components.IntDouble.isInt ()
Definition at line 35 of file IntDouble.java.
References isInteger.
Referenced by IntDouble(), IntDouble(), wrimsv2.evaluator.ValueEvaluation.abs(), wrimsv2.evaluator.Evaluation.absOperation(), wrimsv2.evaluator.ValueEvaluation.add(), wrimsv2.evaluator.Evaluation.addOperation(), wrimsv2.evaluator.ValueEvaluation.divide(), wrimsv2.evaluator.Evaluation.divideOperation(), wrimsv2.evaluator.ValueEvaluation.exp(), wrimsv2.evaluator.Evaluation.expOperation(), wrimsv2.commondata.wresldata.TimeArray.getTimeArraySize(), wrimsv2.evaluator.WeightEval.getTimeArraySize(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.intFunc(), wrimsv2.evaluator.Evaluation.intOperation(), wrimsv2.evaluator.ValueEvaluation.log(), wrimsv2.evaluator.ValueEvaluation.log10(), wrimsv2.evaluator.Evaluation.log10Operation(), wrimsv2.evaluator.Evaluation.logOperation(), wrimsv2.evaluator.ValueEvaluation.max(), wrimsv2.evaluator.Evaluation.maxOperation(), wrimsv2.evaluator.ValueEvaluation.min(), wrimsv2.evaluator.Evaluation.minOperation(), wrimsv2.evaluator.ValueEvaluation.mod(), wrimsv2.evaluator.Evaluation.modOperation(), wrimsv2.evaluator.ValueEvaluation.mult(), wrimsv2.evaluator.Evaluation.multiplyOperation(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pow(), wrimsv2.evaluator.Evaluation.powOperation(), wrimsv2.evaluator.ValueEvaluation.realFunc(), wrimsv2.evaluator.Evaluation.realOperation(), setInt(), wrimsv2.evaluator.ValueEvaluation.substract(), wrimsv2.evaluator.Evaluation.substractOperation(), wrimsv2.evaluator.Evaluation.term_IDENT(), wrimsv2.evaluator.ValueEvaluation.term_IDENT(), wrimsv2.evaluator.Evaluation.term_SVAR(), wrimsv2.evaluator.ValueEvaluation.term_SVAR(), wrimsv2.evaluator.Evaluation.trunk_timeArray(), wrimsv2.evaluator.ValueEvaluation.trunk_timeArray(), and wrimsv2.evaluator.Evaluation.unary().
setData()
void wrimsv2.components.IntDouble.setData (Number value)
Definition at line 31 of file IntDouble.java.
References data.
Referenced by wrimsv2.evaluator.Evaluation.unary().
setIndex()
void wrimsv2.components.IntDouble.setIndex (int index)
Definition at line 65 of file IntDouble.java.
References index.
Referenced by wrimsv2.evaluator.Evaluation.trunk_timeArray(), and wrimsv2.evaluator.ValueEvaluation.trunk_timeArray().
setInt()
void wrimsv2.components.IntDouble.setInt (boolean isInt)
Definition at line 39 of file IntDouble.java.
References isInt(), and isInteger.
setName()
void wrimsv2.components.IntDouble.setName (String argName)
Definition at line 57 of file IntDouble.java.
References argName.
Member Data Documentation
argName
String wrimsv2.components.IntDouble.argName ="" private
Definition at line 8 of file IntDouble.java.
Referenced by IntDouble(), IntDouble(), getName(), and setName().
data
Number wrimsv2.components.IntDouble.data private
Definition at line 6 of file IntDouble.java.
Referenced by IntDouble(), IntDouble(), copyOf(), getData(), and setData().
index
int wrimsv2.components.IntDouble.index private
Definition at line 9 of file IntDouble.java.
Referenced by IntDouble(), getIndex(), and setIndex().
isInteger
boolean wrimsv2.components.IntDouble.isInteger private
Definition at line 7 of file IntDouble.java.
Referenced by IntDouble(), IntDouble(), copyOf(), isInt(), and setInt().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/IntDouble.java