Wrims-engine: wrimsv2.external.GenerateCompileFiles Class Reference
wrimsv2.external.GenerateCompileFiles Class Reference
Static Public Member Functions
static void afterCall_2DArray (PrintWriter out, String vt, String vn)
static void afterCallScalar (PrintWriter out, String vt, String vn)
static void generateBatchFile ()
static void generateCFile (String functionName)
static void generateFiles ()
static void generateJavaFile (String functionName)
static boolean isNameFormatRight (String name)
static void main (String args[])
static void preCall_2DArray (PrintWriter out, String vt, String vn)
static String removeLeadingTailingSpace (String text)
static void reportErrors ()
static boolean setDllFunction (String fileName)
static void setWorkingDirectory (String fileFullPath)
Static Public Attributes
static HashMap< String, String > dllDlls = new HashMap<String, String>()
static HashMap< String, String[]> dllFunctions =new HashMap<String, String[]>()
static ArrayList< String > error =new ArrayList<String>()
static HashMap< String, String > functionTypes =new HashMap<String, String>()
static HashMap< String, String[]> functionVariableNames = new HashMap<String, String[]> ()
static HashMap< String, String[]> functionVariableTypes = new HashMap<String, String[]> ()
static boolean setPath =false
static String workingDir
Static Private Attributes
static String currentDirectory
static ArrayList< String > functionArray =new ArrayList<String>()
Detailed Description
Definition at line 22 of file GenerateCompileFiles.java.
Member Function Documentation
afterCall_2DArray()
void wrimsv2.external.GenerateCompileFiles.afterCall_2DArray (PrintWriter out, String vt, String vn) static
Definition at line 708 of file GenerateCompileFiles.java.
Referenced by generateCFile().
afterCallScalar()
void wrimsv2.external.GenerateCompileFiles.afterCallScalar (PrintWriter out, String vt, String vn) static
Definition at line 760 of file GenerateCompileFiles.java.
Referenced by generateCFile().
generateBatchFile()
void wrimsv2.external.GenerateCompileFiles.generateBatchFile () static
Definition at line 34 of file GenerateCompileFiles.java.
References currentDirectory, dllDlls, dllFunctions, error, functionVariableNames, setPath, and workingDir.
Referenced by generateFiles().
generateCFile()
void wrimsv2.external.GenerateCompileFiles.generateCFile (String functionName) static
Definition at line 259 of file GenerateCompileFiles.java.
References afterCall_2DArray(), afterCallScalar(), error, functionTypes, functionVariableNames, functionVariableTypes, preCall_2DArray(), and workingDir.
Referenced by generateFiles().
generateFiles()
void wrimsv2.external.GenerateCompileFiles.generateFiles () static
Definition at line 635 of file GenerateCompileFiles.java.
References functionVariableNames, generateBatchFile(), generateCFile(), generateJavaFile(), and workingDir.
Referenced by main().
generateJavaFile()
void wrimsv2.external.GenerateCompileFiles.generateJavaFile (String functionName) static
Definition at line 75 of file GenerateCompileFiles.java.
References error, functionTypes, functionVariableNames, functionVariableTypes, and workingDir.
Referenced by generateFiles().
isNameFormatRight()
boolean wrimsv2.external.GenerateCompileFiles.isNameFormatRight (String name) static
Definition at line 626 of file GenerateCompileFiles.java.
Referenced by setDllFunction().
main()
void wrimsv2.external.GenerateCompileFiles.main (String args[]) static
Definition at line 783 of file GenerateCompileFiles.java.
References currentDirectory, generateFiles(), reportErrors(), setDllFunction(), setPath, and setWorkingDirectory().
preCall_2DArray()
void wrimsv2.external.GenerateCompileFiles.preCall_2DArray (PrintWriter out, String vt, String vn) static
Definition at line 664 of file GenerateCompileFiles.java.
Referenced by generateCFile().
removeLeadingTailingSpace()
String wrimsv2.external.GenerateCompileFiles.removeLeadingTailingSpace (String text) static
Definition at line 620 of file GenerateCompileFiles.java.
Referenced by setDllFunction().
reportErrors()
void wrimsv2.external.GenerateCompileFiles.reportErrors () static
Definition at line 649 of file GenerateCompileFiles.java.
References error, and workingDir.
Referenced by main().
setDllFunction()
boolean wrimsv2.external.GenerateCompileFiles.setDllFunction (String fileName) static
Definition at line 467 of file GenerateCompileFiles.java.
References dllDlls, dllFunctions, error, functionArray, functionTypes, functionVariableNames, functionVariableTypes, isNameFormatRight(), and removeLeadingTailingSpace().
Referenced by main().
setWorkingDirectory()
void wrimsv2.external.GenerateCompileFiles.setWorkingDirectory (String fileFullPath) static
Definition at line 778 of file GenerateCompileFiles.java.
References workingDir.
Referenced by main().
Member Data Documentation
currentDirectory
String wrimsv2.external.GenerateCompileFiles.currentDirectory static private
Definition at line 32 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), and main().
dllDlls
HashMap<String, String> wrimsv2.external.GenerateCompileFiles.dllDlls = new HashMap<String, String>() static
Definition at line 24 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), and setDllFunction().
dllFunctions
HashMap<String, String[]> wrimsv2.external.GenerateCompileFiles.dllFunctions =new HashMap<String, String[]>() static
Definition at line 23 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), and setDllFunction().
error
ArrayList<String> wrimsv2.external.GenerateCompileFiles.error =new ArrayList<String>() static
Definition at line 29 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), generateCFile(), generateJavaFile(), reportErrors(), and setDllFunction().
functionArray
ArrayList<String> wrimsv2.external.GenerateCompileFiles.functionArray =new ArrayList<String>() static private
Definition at line 28 of file GenerateCompileFiles.java.
Referenced by setDllFunction().
functionTypes
HashMap<String, String> wrimsv2.external.GenerateCompileFiles.functionTypes =new HashMap<String, String>() static
Definition at line 25 of file GenerateCompileFiles.java.
Referenced by generateCFile(), generateJavaFile(), and setDllFunction().
functionVariableNames
HashMap<String, String[]> wrimsv2.external.GenerateCompileFiles.functionVariableNames = new HashMap<String, String[]> () static
Definition at line 26 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), generateCFile(), generateFiles(), generateJavaFile(), and setDllFunction().
functionVariableTypes
HashMap<String, String[]> wrimsv2.external.GenerateCompileFiles.functionVariableTypes = new HashMap<String, String[]> () static
Definition at line 27 of file GenerateCompileFiles.java.
Referenced by generateCFile(), generateJavaFile(), and setDllFunction().
setPath
boolean wrimsv2.external.GenerateCompileFiles.setPath =false static
Definition at line 31 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), and main().
workingDir
String wrimsv2.external.GenerateCompileFiles.workingDir static
Definition at line 30 of file GenerateCompileFiles.java.
Referenced by generateBatchFile(), generateCFile(), generateFiles(), generateJavaFile(), reportErrors(), and setWorkingDirectory().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/GenerateCompileFiles.java