Wrims-engine: wrimsv2.evaluator.DssOperation Class Reference
wrimsv2.evaluator.DssOperation Class Reference
Static Public Member Functions
static String createPath (String apart, String bpart, String cpart, String dpart, String epart, String fpart)
static String entryNameTS (String name, String timeStep)
static HecTimeSeries getDataForInitial (String apart, String bpart, String cpart, String dpart, String epart, String fpart)
static synchronized HecTimeSeries getDataForSvar (String apart, String bpart, String cpart, String dpart, String epart, String fpart, int svFileIndex, String filename)
static boolean getDVAliasInitTimeseries (String name)
static boolean getSVInitTimeseries (String name)
static boolean getSVTimeseries (String name, String file, String timeStep, int svFileIndex)
static String getTSName (String entryNameTS)
static boolean isToWrite (String name, String kind)
static String regularExp (String part)
static int savedTimeStep (String timeStep, int year, int month, int day)
static void saveDvarCycleData (HecDss dss, String fileName)
static void saveDvarData (HecDss dss, String fileName)
static void saveDVInitialData (HecDss dss, String fileName)
static void saveInitialData (HecDss dss, String fileName)
static void saveSvarTSData (HecDss dss, String fileName)
static void saveSVInitialData (HecDss dss, String fileName)
static void shiftData ()
static void shiftDvAliasCycleData (Date prevMemDate, Date memStartDate, Date outputDate)
static void shiftDvAliasData (Date prevMemDate, Date memStartDate, Date outputDate)
static void writeDVAliasCycleDataToDSS ()
static void writeDVAliasToDSS ()
static void writeInitDvarAliasToDSS ()
Static Private Attributes
static int savedEndDailyTimestep
static int savedEndMonthlyTimestep
static int savedStartDailyTimestep
static int savedStartMonthlyTimestep
static int totalSavedDailyTimestep
static int totalSavedMonthlyTimestep
Detailed Description
Definition at line 27 of file DssOperation.java.
Member Function Documentation
createPath()
String wrimsv2.evaluator.DssOperation.createPath (String apart, String bpart, String cpart, String dpart, String epart, String fpart) static
Definition at line 272 of file DssOperation.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and getSVTimeseries().
entryNameTS()
String wrimsv2.evaluator.DssOperation.entryNameTS (String name, String timeStep) static
Definition at line 490 of file DssOperation.java.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), wrimsv2.hdf5.HDF5Reader.assignTimeseries(), wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.components.DebugInterface.getCycleValueDetail(), getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), getTSName(), wrimsv2.components.DebugInterface.modifyTimeSeries(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.sql.DssToSQLDatabase.readDssData(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), wrimsv2.components.PreRunModel.readTimeseries(), wrimsv2.debug.ReLoadSVDss.readTimeseries(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), wrimsv2.evaluator.ValueEvaluation.svarTimeSeries(), and wrimsv2.components.ControllerDebug.updateVarMonitor().
getDataForInitial()
HecTimeSeries wrimsv2.evaluator.DssOperation.getDataForInitial (String apart, String bpart, String cpart, String dpart, String epart, String fpart) static
Definition at line 309 of file DssOperation.java.
References wrimsv2.components.ControlData.cacheInit, wrimsv2.components.FilePaths.fullInitFilePath, and wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getNominalPathname().
getDataForSvar()
synchronized HecTimeSeries wrimsv2.evaluator.DssOperation.getDataForSvar (String apart, String bpart, String cpart, String dpart, String epart, String fpart, int svFileIndex, String filename) static
Definition at line 277 of file DssOperation.java.
References wrimsv2.components.ControlData.cacheSvar, wrimsv2.components.ControlData.cacheSvar2, and wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getNominalPathname().
getDVAliasInitTimeseries()
boolean wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries (String name) static
Definition at line 210 of file DssOperation.java.
References wrimsv2.components.ControlData.cacheInit, createPath(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, entryNameTS(), wrimsv2.components.ControlData.initPartF, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.partE, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), wrimsv2.evaluator.DssDataSet.setUnits(), wrimsv2.commondata.wresldata.Alias.units, and wrimsv2.commondata.wresldata.Dvar.units.
Referenced by wrimsv2.evaluator.Evaluation.getDVAliasInitTimeseries(), and wrimsv2.evaluator.ValueEvaluation.getDVAliasInitTimeseries().
getSVInitTimeseries()
boolean wrimsv2.evaluator.DssOperation.getSVInitTimeseries (String name) static
Definition at line 121 of file DssOperation.java.
References wrimsv2.components.ControlData.cacheInit, wrimsv2.commondata.wresldata.Timeseries.convertToUnits, createPath(), wrimsv2.components.ControlData.currTsMap, wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.commondata.wresldata.Timeseries.dssBPart, entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.ControlData.initPartF, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.partE, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.evaluator.DssDataSet.setConvertToUnits(), wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), wrimsv2.evaluator.DssDataSet.setUnits(), wrimsv2.evaluator.DataTimeSeries.svInit, wrimsv2.evaluator.Evaluation.tafcfs(), wrimsv2.components.ControlData.timeStep, and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by wrimsv2.evaluator.Evaluation.getSVInitTimeseries(), and wrimsv2.evaluator.ValueEvaluation.getSVInitTimeseries().
getSVTimeseries()
boolean wrimsv2.evaluator.DssOperation.getSVTimeseries (String name, String file, String timeStep, int svFileIndex) static
Definition at line 36 of file DssOperation.java.
References wrimsv2.components.ControlData.allTsMap, wrimsv2.components.ControlData.cacheSvar, wrimsv2.components.ControlData.cacheSvar2, wrimsv2.commondata.wresldata.Timeseries.convertToUnits, createPath(), wrimsv2.commondata.wresldata.Timeseries.dssBPart, entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.generateStudyStartIndex(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.partE, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.evaluator.DssDataSet.setConvertToUnits(), wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setFromDssFile(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), wrimsv2.evaluator.DssDataSet.setUnits(), wrimsv2.components.ControlData.svDvPartF, wrimsv2.evaluator.DataTimeSeries.svTS, wrimsv2.evaluator.Evaluation.tafcfs(), wrimsv2.components.ControlData.timeStep, and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by wrimsv2.components.PreRunModel.readTimeseries(), and wrimsv2.debug.ReLoadSVDss.readTimeseries().
getTSName()
String wrimsv2.evaluator.DssOperation.getTSName (String entryNameTS) static
Definition at line 494 of file DssOperation.java.
References entryNameTS().
Referenced by wrimsv2.sql.MySQLCWriter.formPathName(), wrimsv2.sql.MySQLRWriterAlt.formVariableName(), wrimsv2.sql.SQLServerRWriterAlt.formVariableName(), wrimsv2.evaluator.CsvOperation.ouputCSV(), saveDvarCycleData(), saveDvarData(), saveDVInitialData(), saveInitialData(), saveSvarTSData(), writeDVAliasCycleDataToDSS(), writeDVAliasToDSS(), and writeInitDvarAliasToDSS().
isToWrite()
boolean wrimsv2.evaluator.DssOperation.isToWrite (String name, String kind) static
Definition at line 963 of file DssOperation.java.
References isToWrite(), and wrimsv2.components.ControlData.ovPartBC.
Referenced by isToWrite(), saveDvarCycleData(), saveDvarData(), writeDVAliasCycleDataToDSS(), writeDVAliasToDSS(), and writeInitDvarAliasToDSS().
regularExp()
String wrimsv2.evaluator.DssOperation.regularExp (String part) static
Definition at line 206 of file DssOperation.java.
savedTimeStep()
int wrimsv2.evaluator.DssOperation.savedTimeStep (String timeStep, int year, int month, int day) static
Definition at line 880 of file DssOperation.java.
References wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by saveDvarCycleData(), and saveDvarData().
saveDvarCycleData()
void wrimsv2.evaluator.DssOperation.saveDvarCycleData (HecDss dss, String fileName) static
Definition at line 732 of file DssOperation.java.
References wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.cycleDataStartDay, wrimsv2.components.ControlData.cycleDataStartMonth, wrimsv2.components.ControlData.cycleDataStartYear, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSetFixLength.getUnits(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.tools.General.isSelectedCycleOutput(), isToWrite(), wrimsv2.components.ControlData.memStartDay, wrimsv2.components.ControlData.memStartMonth, wrimsv2.components.ControlData.memStartYear, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.ovOption, wrimsv2.components.ControlData.partA, savedEndDailyTimestep, savedEndMonthlyTimestep, savedStartDailyTimestep, savedStartMonthlyTimestep, savedTimeStep(), wrimsv2.components.ControlData.svDvPartF, totalSavedDailyTimestep, and totalSavedMonthlyTimestep.
Referenced by saveDvarData().
saveDvarData()
void wrimsv2.evaluator.DssOperation.saveDvarData (HecDss dss, String fileName) static
Definition at line 663 of file DssOperation.java.
References wrimsv2.evaluator.TimeOperation.addOneDay(), wrimsv2.evaluator.TimeOperation.addOneMonth(), wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSetFixLength.getUnits(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, isToWrite(), wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.ovOption, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.prevOutputDate, savedEndDailyTimestep, savedEndMonthlyTimestep, savedTimeStep(), saveDvarCycleData(), and wrimsv2.components.ControlData.svDvPartF.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), and wrimsv2.components.DebugInterface.saveDvDss().
saveDVInitialData()
void wrimsv2.evaluator.DssOperation.saveDVInitialData (HecDss dss, String fileName) static
Definition at line 539 of file DssOperation.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getKind(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSet.getUnits(), wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by wrimsv2.components.DebugInterface.saveInitDss().
saveInitialData()
void wrimsv2.evaluator.DssOperation.saveInitialData (HecDss dss, String fileName) static
Definition at line 499 of file DssOperation.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getKind(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSet.getUnits(), wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), and wrimsv2.components.DebugInterface.saveDvDss().
saveSvarTSData()
void wrimsv2.evaluator.DssOperation.saveSvarTSData (HecDss dss, String fileName) static
Definition at line 797 of file DssOperation.java.
References wrimsv2.components.ControlData.allTsMap, wrimsv2.commondata.wresldata.Timeseries.convertToUnits, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getKind(), wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSet.getUnits(), wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.svDvPartF, wrimsv2.evaluator.DataTimeSeries.svTS, wrimsv2.evaluator.Evaluation.tafcfs(), and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by wrimsv2.components.DebugInterface.saveSvDss().
saveSVInitialData()
void wrimsv2.evaluator.DssOperation.saveSVInitialData (HecDss dss, String fileName) static
Definition at line 580 of file DssOperation.java.
References wrimsv2.components.ControlData.allTsMap, wrimsv2.commondata.wresldata.Timeseries.convertToUnits, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getKind(), wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), wrimsv2.evaluator.DssDataSet.getUnits(), wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.partA, wrimsv2.evaluator.DataTimeSeries.svInit, wrimsv2.evaluator.Evaluation.tafcfs(), and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by wrimsv2.components.DebugInterface.saveInitDss().
shiftData()
void wrimsv2.evaluator.DssOperation.shiftData () static
Definition at line 898 of file DssOperation.java.
References wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputYear, wrimsv2.components.ControlData.prevMemDate, shiftDvAliasCycleData(), and shiftDvAliasData().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
shiftDvAliasCycleData()
void wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData (Date prevMemDate, Date memStartDate, Date outputDate) static
Definition at line 929 of file DssOperation.java.
References wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.tools.General.isSelectedCycleOutput(), and wrimsv2.evaluator.DssDataSetFixLength.setStartTime().
Referenced by shiftData().
shiftDvAliasData()
void wrimsv2.evaluator.DssOperation.shiftDvAliasData (Date prevMemDate, Date memStartDate, Date outputDate) static
Definition at line 904 of file DssOperation.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), and wrimsv2.evaluator.DssDataSetFixLength.setStartTime().
Referenced by shiftData().
writeDVAliasCycleDataToDSS()
void wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS () static
Definition at line 428 of file DssOperation.java.
References wrimsv2.evaluator.TimeOperation.addOneDay(), wrimsv2.evaluator.TimeOperation.addOneMonth(), wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.components.ControlData.dvDss, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSetFixLength.getUnits(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.tools.General.isSelectedCycleOutput(), isToWrite(), wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.ovOption, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.prevOutputDate, and wrimsv2.components.ControlData.svDvPartF.
Referenced by writeDVAliasToDSS().
writeDVAliasToDSS()
void wrimsv2.evaluator.DssOperation.writeDVAliasToDSS () static
Definition at line 368 of file DssOperation.java.
References wrimsv2.evaluator.TimeOperation.addOneDay(), wrimsv2.evaluator.TimeOperation.addOneMonth(), wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.components.ControlData.dvDss, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSetFixLength.getUnits(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, isToWrite(), wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.ovOption, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.prevOutputDate, wrimsv2.components.ControlData.svDvPartF, wrimsv2.components.ControlData.t_writeDss, and writeDVAliasCycleDataToDSS().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.components.Controller.writeOutputDssEveryTenYears(), wrimsv2.components.ControllerBatch.writeOutputDssEveryTenYears(), wrimsv2.components.ControllerDebug.writeOutputDssEveryTenYears(), and wrimsv2.components.ControllerSG.writeOutputDssEveryTenYears().
writeInitDvarAliasToDSS()
void wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS () static
Definition at line 327 of file DssOperation.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.components.ControlData.dvDss, wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getKind(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), getTSName(), wrimsv2.evaluator.DssDataSet.getUnits(), isToWrite(), wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.ovOption, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
Member Data Documentation
savedEndDailyTimestep
int wrimsv2.evaluator.DssOperation.savedEndDailyTimestep static private
Definition at line 33 of file DssOperation.java.
Referenced by saveDvarCycleData(), and saveDvarData().
savedEndMonthlyTimestep
int wrimsv2.evaluator.DssOperation.savedEndMonthlyTimestep static private
Definition at line 30 of file DssOperation.java.
Referenced by saveDvarCycleData(), and saveDvarData().
savedStartDailyTimestep
int wrimsv2.evaluator.DssOperation.savedStartDailyTimestep static private
Definition at line 32 of file DssOperation.java.
Referenced by saveDvarCycleData().
savedStartMonthlyTimestep
int wrimsv2.evaluator.DssOperation.savedStartMonthlyTimestep static private
Definition at line 29 of file DssOperation.java.
Referenced by saveDvarCycleData().
totalSavedDailyTimestep
int wrimsv2.evaluator.DssOperation.totalSavedDailyTimestep static private
Definition at line 34 of file DssOperation.java.
Referenced by saveDvarCycleData().
totalSavedMonthlyTimestep
int wrimsv2.evaluator.DssOperation.totalSavedMonthlyTimestep static private
Definition at line 31 of file DssOperation.java.
Referenced by saveDvarCycleData().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/DssOperation.java