Wrims-engine: wrimsv2.evaluator.CsvOperation Class Reference
wrimsv2.evaluator.CsvOperation Class Reference
Public Member Functions
double convertValue (double value, String units, String convertToUnits, Date date, String timestep)
double factorCfsToTaf (Date date, String timestep)
double factorTafToCfs (Date date, String timestep)
String formDateData (Date date)
String formKindName (String name)
String formUnitsName (String units)
String formVariableName (String name)
void ouputCSV (String csvLocalPath, int scenarioIndex)
void procOVFile ()
Private Attributes
Map< String, String > ovPartBC =new HashMap<String, String>()
String slackPrefix ="slack__"
String surplusPrefix ="surplus__"
Detailed Description
Definition at line 20 of file CsvOperation.java.
Member Function Documentation
convertValue()
double wrimsv2.evaluator.CsvOperation.convertValue (double value, String units, String convertToUnits, Date date, String timestep)
Definition at line 295 of file CsvOperation.java.
References factorCfsToTaf(), and factorTafToCfs().
Referenced by ouputCSV().
factorCfsToTaf()
double wrimsv2.evaluator.CsvOperation.factorCfsToTaf (Date date, String timestep)
Definition at line 316 of file CsvOperation.java.
References wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by convertValue().
factorTafToCfs()
double wrimsv2.evaluator.CsvOperation.factorTafToCfs (Date date, String timestep)
Definition at line 305 of file CsvOperation.java.
References wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by convertValue().
formDateData()
String wrimsv2.evaluator.CsvOperation.formDateData (Date date)
Definition at line 342 of file CsvOperation.java.
References wrimsv2.evaluator.TimeOperation.dayName(), and wrimsv2.evaluator.TimeOperation.monthNameNumeric().
Referenced by ouputCSV().
formKindName()
String wrimsv2.evaluator.CsvOperation.formKindName (String name)
Definition at line 337 of file CsvOperation.java.
Referenced by ouputCSV().
formUnitsName()
String wrimsv2.evaluator.CsvOperation.formUnitsName (String units)
Definition at line 327 of file CsvOperation.java.
Referenced by ouputCSV().
formVariableName()
String wrimsv2.evaluator.CsvOperation.formVariableName (String name)
Definition at line 332 of file CsvOperation.java.
Referenced by ouputCSV().
ouputCSV()
void wrimsv2.evaluator.CsvOperation.ouputCSV (String csvLocalPath, int scenarioIndex)
Definition at line 26 of file CsvOperation.java.
References wrimsv2.evaluator.TimeOperation.addOneDay(), wrimsv2.evaluator.TimeOperation.addOneMonth(), wrimsv2.evaluator.TimeOperation.backOneDay(), wrimsv2.evaluator.TimeOperation.backOneMonth(), convertValue(), wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, formDateData(), formKindName(), formUnitsName(), formVariableName(), wrimsv2.evaluator.DssDataSet.getConvertToUnits(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSet.getKind(), wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.evaluator.DssOperation.getTSName(), wrimsv2.evaluator.DssDataSet.getUnits(), wrimsv2.evaluator.DssDataSetFixLength.getUnits(), wrimsv2.components.ControlData.isSimOutput, wrimsv2.components.ControlData.ovOption, ovPartBC, wrimsv2.components.ControlData.partA, procOVFile(), slackPrefix, surplusPrefix, wrimsv2.components.ControlData.svDvPartF, wrimsv2.evaluator.DataTimeSeries.svInit, wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.components.ControlData.writeInitToDVOutput.
Referenced by wrimsv2.sql.DssToSQLDatabase.convertData(), wrimsv2.sql.MySQLRWriter.createCSV(), wrimsv2.sql.SQLServerRWriter.createCSV(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
procOVFile()
void wrimsv2.evaluator.CsvOperation.procOVFile ()
Definition at line 259 of file CsvOperation.java.
References wrimsv2.components.ControlData.ovFile, wrimsv2.components.ControlData.ovOption, and ovPartBC.
Referenced by ouputCSV().
Member Data Documentation
ovPartBC
Map<String, String> wrimsv2.evaluator.CsvOperation.ovPartBC =new HashMap<String, String>() private
Definition at line 24 of file CsvOperation.java.
Referenced by ouputCSV(), and procOVFile().
slackPrefix
String wrimsv2.evaluator.CsvOperation.slackPrefix ="slack__" private
Definition at line 22 of file CsvOperation.java.
Referenced by ouputCSV().
surplusPrefix
String wrimsv2.evaluator.CsvOperation.surplusPrefix ="surplus__" private
Definition at line 23 of file CsvOperation.java.
Referenced by ouputCSV().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/CsvOperation.java