Wrims-engine: wrimsv2.wreslplus.elements.Procedures Class Reference
wrimsv2.wreslplus.elements.Procedures Class Reference
Static Public Member Functions
static void analyzeVarNeededFromCycle (StudyTemp s)
static void classifyDependants (SequenceTemp seqObj, ArrayList< String > parameterList)
static void classifyDependants (StudyTemp s)
static void collectTimeStep (StudyTemp st)
static void convertAliasToGoal (SequenceTemp seqObj)
static void convertAliasToGoal (StudyTemp s)
static boolean copyModelVarMapToSequenceVarMap (ModelTemp mt, SequenceTemp seq)
static boolean copyModelVarMapToSequenceVarMap (StudyTemp st)
static void createSpaceInVarCycleValueMap (StudyTemp s)
static void findAllOffSpring (StudyTemp st)
static void findFileGroupOrder (StudyTemp st)
static void findKidMap (StudyTemp st)
static int findWarmStart (int preStop, int nCyc)
static int findWarmStart (int preStop, int nCyc, StudyDataSet sd)
static int findWarmStop (int start, int nCyc)
static int findWarmStop (int start, int nCyc, StudyDataSet sd)
static void postProcessIncFileList (StudyTemp st)
static void postProcessVarListinIncFile (StudyTemp st)
static void processDependants (ModelTemp mObj)
static void processDependants (StudyTemp s)
Private Member Functions
Procedures ()
Detailed Description
Definition at line 18 of file Procedures.java.
Constructor & Destructor Documentation
Procedures()
wrimsv2.wreslplus.elements.Procedures.Procedures () private
Definition at line 20 of file Procedures.java.
Member Function Documentation
analyzeVarNeededFromCycle()
void wrimsv2.wreslplus.elements.Procedures.analyzeVarNeededFromCycle (StudyTemp s) static
Definition at line 813 of file Procedures.java.
References wrimsv2.wreslplus.elements.SequenceTemp.aliasUsedByLaterCycle, wrimsv2.wreslplus.elements.SequenceTemp.asIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.dvarUsedByLaterCycle, wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslplus.elements.SequenceTemp.dvList_fromAlias, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.SequenceTemp.neededCycleVarMap, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.SequenceTemp.svarUsedByLaterCycle, wrimsv2.wreslplus.elements.SequenceTemp.svIncFileList_post, and wrimsv2.wreslplus.elements.SequenceTemp.varUsedByLaterCycle.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
classifyDependants() [1/2]
void wrimsv2.wreslplus.elements.Procedures.classifyDependants (SequenceTemp seqObj, ArrayList< String > parameterList) static
Definition at line 671 of file Procedures.java.
References wrimsv2.wreslplus.elements.SequenceTemp.asMap, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.AliasTemp.dependants_alias, wrimsv2.wreslplus.elements.GoalTemp.dependants_alias, wrimsv2.wreslplus.elements.SvarTemp.dependants_alias, wrimsv2.wreslplus.elements.AliasTemp.dependants_dvar, wrimsv2.wreslplus.elements.GoalTemp.dependants_dvar, wrimsv2.wreslplus.elements.SvarTemp.dependants_dvar, wrimsv2.wreslplus.elements.GoalTemp.dependants_external, wrimsv2.wreslplus.elements.SvarTemp.dependants_external, wrimsv2.wreslplus.elements.AliasTemp.dependants_parameter, wrimsv2.wreslplus.elements.GoalTemp.dependants_parameter, wrimsv2.wreslplus.elements.SvarTemp.dependants_parameter, wrimsv2.wreslplus.elements.AliasTemp.dependants_svar, wrimsv2.wreslplus.elements.GoalTemp.dependants_svar, wrimsv2.wreslplus.elements.SvarTemp.dependants_svar, wrimsv2.wreslplus.elements.AliasTemp.dependants_timeseries, wrimsv2.wreslplus.elements.GoalTemp.dependants_timeseries, wrimsv2.wreslplus.elements.SvarTemp.dependants_timeseries, wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslplus.elements.SequenceTemp.exList, wrimsv2.wreslplus.elements.SequenceTemp.exMap, wrimsv2.wreslplus.elements.SequenceTemp.glMap, wrimsv2.wreslplus.elements.SequenceTemp.svMap, and wrimsv2.wreslplus.elements.SequenceTemp.tsList.
classifyDependants() [2/2]
void wrimsv2.wreslplus.elements.Procedures.classifyDependants (StudyTemp s) static
Definition at line 660 of file Procedures.java.
References classifyDependants(), wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and classifyDependants().
collectTimeStep()
void wrimsv2.wreslplus.elements.Procedures.collectTimeStep (StudyTemp st) static
Definition at line 893 of file Procedures.java.
References wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.StudyTemp.seqTimeStepList, wrimsv2.wreslplus.elements.StudyTemp.timeseriesTimeStepMap, wrimsv2.wreslplus.elements.SequenceTemp.timeStep, wrimsv2.wreslplus.elements.SequenceTemp.tsList, and wrimsv2.commondata.wresldata.Param.undefined.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
convertAliasToGoal() [1/2]
void wrimsv2.wreslplus.elements.Procedures.convertAliasToGoal (SequenceTemp seqObj) static
Definition at line 287 of file Procedures.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslplus.elements.SequenceTemp.asIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.asList, wrimsv2.wreslplus.elements.SequenceTemp.asMap, wrimsv2.wreslplus.elements.GoalTemp.caseCondition, wrimsv2.wreslplus.elements.GoalTemp.caseExpression, wrimsv2.wreslplus.elements.GoalTemp.caseName, wrimsv2.wreslplus.elements.AliasTemp.condition, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.SequenceTemp.dvList_fromAlias, wrimsv2.wreslplus.elements.SequenceTemp.dvMap, wrimsv2.wreslplus.elements.AliasTemp.expression, wrimsv2.wreslplus.elements.AliasTemp.fromWresl, wrimsv2.wreslplus.elements.SequenceTemp.glList_fromAlias, wrimsv2.wreslplus.elements.SequenceTemp.glMap, wrimsv2.wreslplus.elements.AliasTemp.id, wrimsv2.wreslplus.elements.GoalTemp.id, wrimsv2.wreslplus.elements.GoalTemp.isFromAlias, wrimsv2.wreslplus.elements.AliasTemp.kind, wrimsv2.wreslplus.elements.AliasTemp.line, wrimsv2.wreslplus.elements.DvarTemp.line, wrimsv2.wreslplus.elements.GoalTemp.line, wrimsv2.commondata.wresldata.Param.lower_unbounded, wrimsv2.wreslplus.elements.AliasTemp.noSolver, wrimsv2.wreslplus.elements.AliasTemp.timeArraySize, wrimsv2.wreslplus.elements.AliasTemp.units, and wrimsv2.commondata.wresldata.Param.upper_unbounded.
convertAliasToGoal() [2/2]
void wrimsv2.wreslplus.elements.Procedures.convertAliasToGoal (StudyTemp s) static
Definition at line 274 of file Procedures.java.
References convertAliasToGoal(), wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and convertAliasToGoal().
copyModelVarMapToSequenceVarMap() [1/2]
boolean wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap (ModelTemp mt, SequenceTemp seq) static
Definition at line 205 of file Procedures.java.
References wrimsv2.wreslplus.elements.ModelTemp.asList, wrimsv2.wreslplus.elements.SequenceTemp.asList, wrimsv2.wreslplus.elements.ModelTemp.asMap, wrimsv2.wreslplus.elements.SequenceTemp.asMap, wrimsv2.wreslplus.elements.ModelTemp.deviationSlackSurplus_toleranceMap, wrimsv2.wreslplus.elements.SequenceTemp.deviationSlackSurplus_toleranceMap, wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslplus.elements.ModelTemp.dvList_deviationSlackSurplus, wrimsv2.wreslplus.elements.SequenceTemp.dvList_deviationSlackSurplus, wrimsv2.wreslplus.elements.ModelTemp.dvMap, wrimsv2.wreslplus.elements.SequenceTemp.dvMap, wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.wreslplus.elements.ModelTemp.exList, wrimsv2.wreslplus.elements.SequenceTemp.exList, wrimsv2.wreslplus.elements.ModelTemp.exMap, wrimsv2.wreslplus.elements.SequenceTemp.exMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.findDuplicatesIgnoreCase(), wrimsv2.wreslplus.elements.GoalTemp.fromWresl, wrimsv2.wreslplus.elements.ModelTemp.gl2List, wrimsv2.wreslplus.elements.SequenceTemp.gl2List, wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.SequenceTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.wreslplus.elements.SequenceTemp.glMap, wrimsv2.wreslplus.elements.ModelTemp.groupWeightMap, wrimsv2.wreslplus.elements.SequenceTemp.groupWeightMap, wrimsv2.wreslplus.elements.GoalTemp.line, wrimsv2.wreslplus.elements.ModelTemp.neededCycleVarMap, wrimsv2.wreslplus.elements.SequenceTemp.neededCycleVarMap, wrimsv2.wreslplus.elements.ModelTemp.ssList_hasCase, wrimsv2.wreslplus.elements.SequenceTemp.ssList_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssList_noCase, wrimsv2.wreslplus.elements.SequenceTemp.ssList_noCase, wrimsv2.wreslplus.elements.ModelTemp.ssMap_hasCase, wrimsv2.wreslplus.elements.SequenceTemp.ssMap_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssMap_noCase, wrimsv2.wreslplus.elements.SequenceTemp.ssMap_noCase, wrimsv2.wreslplus.elements.ModelTemp.ssWeightMap_hasCase, wrimsv2.wreslplus.elements.SequenceTemp.ssWeightMap_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssWeightMap_noCase, wrimsv2.wreslplus.elements.SequenceTemp.ssWeightMap_noCase, wrimsv2.wreslplus.elements.ModelTemp.svMap, wrimsv2.wreslplus.elements.SequenceTemp.svMap, wrimsv2.wreslplus.elements.ModelTemp.tsList, wrimsv2.wreslplus.elements.SequenceTemp.tsList, wrimsv2.wreslplus.elements.ModelTemp.tsMap, wrimsv2.wreslplus.elements.SequenceTemp.tsMap, wrimsv2.wreslplus.elements.ModelTemp.wTableObjList, wrimsv2.wreslplus.elements.SequenceTemp.wTableObjList, wrimsv2.wreslplus.elements.SequenceTemp.wvList, and wrimsv2.wreslplus.elements.ModelTemp.wvList_post.
copyModelVarMapToSequenceVarMap() [2/2]
boolean wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap (StudyTemp st) static
Definition at line 70 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, wrimsv2.wreslplus.elements.ModelTemp.asIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.asList, wrimsv2.wreslplus.elements.SequenceTemp.asMap, copyModelVarMapToSequenceVarMap(), wrimsv2.wreslplus.elements.ModelTemp.dvIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslplus.elements.SequenceTemp.dvMap, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.wreslplus.elements.ModelTemp.exIncFileList_post, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.findDuplicatesIgnoreCase(), wrimsv2.wreslplus.elements.AliasTemp.fromWresl, wrimsv2.wreslplus.elements.DvarTemp.fromWresl, wrimsv2.wreslplus.elements.GoalTemp.fromWresl, wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.TimeseriesTemp.fromWresl, wrimsv2.wreslplus.elements.ModelTemp.glIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.glList, wrimsv2.wreslplus.elements.SequenceTemp.glMap, wrimsv2.wreslplus.elements.ModelTemp.incFileAbsPathList_post, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.AliasTemp.line, wrimsv2.wreslplus.elements.DvarTemp.line, wrimsv2.wreslplus.elements.GoalTemp.line, wrimsv2.wreslplus.elements.SvarTemp.line, wrimsv2.wreslplus.elements.TimeseriesTemp.line, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.ModelTemp.svIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.svIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.svMap, wrimsv2.wreslplus.elements.SequenceTemp.tsList, and wrimsv2.wreslplus.elements.SequenceTemp.tsMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and copyModelVarMapToSequenceVarMap().
createSpaceInVarCycleValueMap()
void wrimsv2.wreslplus.elements.Procedures.createSpaceInVarCycleValueMap (StudyTemp s) static
Definition at line 866 of file Procedures.java.
References wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.StudyTemp.varCycleValueMap, and wrimsv2.wreslplus.elements.SequenceTemp.varUsedByLaterCycle.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findAllOffSpring()
void wrimsv2.wreslplus.elements.Procedures.findAllOffSpring (StudyTemp st) static
Definition at line 465 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap, wrimsv2.wreslplus.elements.Tools.findAllOffspring(), and wrimsv2.wreslplus.elements.StudyTemp.kidMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findFileGroupOrder()
void wrimsv2.wreslplus.elements.Procedures.findFileGroupOrder (StudyTemp st) static
Definition at line 478 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap, wrimsv2.wreslplus.elements.StudyTemp.fileGroupOrder, wrimsv2.wreslplus.elements.Tools.findFileHierarchy(), wrimsv2.wreslplus.elements.StudyTemp.noKid, and wrimsv2.wreslplus.elements.StudyTemp.relativePath.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findKidMap()
void wrimsv2.wreslplus.elements.Procedures.findKidMap (StudyTemp st) static
Definition at line 444 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.StudyTemp.kidMap, and wrimsv2.wreslplus.elements.StudyTemp.noKid.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findWarmStart() [1/2]
int wrimsv2.wreslplus.elements.Procedures.findWarmStart (int preStop, int nCyc) static
Definition at line 929 of file Procedures.java.
References wrimsv2.commondata.wresldata.Param.cbcMinIntNumber, wrimsv2.components.ControlData.currStudyDataSet, and wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap.
Referenced by wrimsv2.tools.Warmstart.collectIntegerDV_1(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), and wrimsv2.tools.Warmstart.collectIntegerDV_3().
findWarmStart() [2/2]
int wrimsv2.wreslplus.elements.Procedures.findWarmStart (int preStop, int nCyc, StudyDataSet sd) static
Definition at line 940 of file Procedures.java.
References wrimsv2.commondata.wresldata.Param.cbcMinIntNumber, and wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap.
findWarmStop() [1/2]
int wrimsv2.wreslplus.elements.Procedures.findWarmStop (int start, int nCyc) static
Definition at line 950 of file Procedures.java.
References wrimsv2.components.ControlData.currStudyDataSet, and wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap.
Referenced by wrimsv2.tools.Warmstart.collectIntegerDV_1(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), and wrimsv2.tools.Warmstart.collectIntegerDV_3().
findWarmStop() [2/2]
int wrimsv2.wreslplus.elements.Procedures.findWarmStop (int start, int nCyc, StudyDataSet sd) static
Definition at line 959 of file Procedures.java.
References wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap.
postProcessIncFileList()
void wrimsv2.wreslplus.elements.Procedures.postProcessIncFileList (StudyTemp st) static
Definition at line 383 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap, wrimsv2.wreslplus.elements.StudyTemp.fileGroupOrder, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.ModelTemp.incFileAbsPathList_post, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, and wrimsv2.wreslplus.elements.StudyTemp.modelMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
postProcessVarListinIncFile()
void wrimsv2.wreslplus.elements.Procedures.postProcessVarListinIncFile (StudyTemp st) static
Definition at line 495 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap, wrimsv2.wreslplus.elements.ModelTemp.asIncFileList_post, wrimsv2.wreslplus.elements.ModelTemp.dvIncFileList_post, wrimsv2.wreslplus.elements.ModelTemp.exIncFileList_post, wrimsv2.wreslplus.elements.StudyTemp.fileGroupOrder, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.ModelTemp.glIncFileList_post, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.ModelTemp.ssList_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssList_noCase, and wrimsv2.wreslplus.elements.ModelTemp.svIncFileList_post.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
processDependants() [1/2]
void wrimsv2.wreslplus.elements.Procedures.processDependants (ModelTemp mObj) static
Definition at line 43 of file Procedures.java.
References wrimsv2.wreslplus.elements.ModelTemp.asMap, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.commondata.wresldata.Param.reservedSet, and wrimsv2.wreslplus.elements.ModelTemp.svMap.
processDependants() [2/2]
void wrimsv2.wreslplus.elements.Procedures.processDependants (StudyTemp s) static
Definition at line 23 of file Procedures.java.
References wrimsv2.wreslplus.elements.StudyTemp.incModelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, and processDependants().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile(), and processDependants().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/Procedures.java