Wrims-engine: wrimsv2.wreslplus.elements.procedures.ProcIncFile Class Reference
wrimsv2.wreslplus.elements.procedures.ProcIncFile Class Reference
Static Public Member Functions
static void processPath (ModelTemp m)
static void processPath (ModelTemp m, StudyTemp s)
static void processPath (StudyTemp s)
Private Member Functions
ProcIncFile ()
Detailed Description
Definition at line 14 of file ProcIncFile.java.
Constructor & Destructor Documentation
ProcIncFile()
wrimsv2.wreslplus.elements.procedures.ProcIncFile.ProcIncFile () private
Definition at line 16 of file ProcIncFile.java.
Member Function Documentation
processPath() [1/3]
void wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath (ModelTemp m) static
Definition at line 78 of file ProcIncFile.java.
References wrimsv2.wreslplus.elements.IncFileTemp.absPath, wrimsv2.wreslplus.elements.ModelTemp.absPath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslplus.elements.ResourceUtils.getRelativePath(), wrimsv2.wreslplus.elements.ModelTemp.incFileAbsPathList, wrimsv2.wreslplus.elements.ModelTemp.incFileMap, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList, wrimsv2.wreslplus.elements.ModelTemp.parentAbsPath, wrimsv2.wreslplus.elements.IncFileTemp.pathRelativeToRunDir, wrimsv2.wreslplus.elements.IncFileTemp.rawPath, and wrimsv2.wreslplus.elements.GlobalData.runDir.
processPath() [2/3]
void wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath (ModelTemp m, StudyTemp s) static
Definition at line 20 of file ProcIncFile.java.
References wrimsv2.wreslplus.elements.IncFileTemp.absPath, wrimsv2.wreslplus.elements.ModelTemp.absPath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslplus.elements.ResourceUtils.getRelativePath(), wrimsv2.wreslplus.elements.ModelTemp.incFileAbsPathList, wrimsv2.wreslplus.elements.ModelTemp.incFileMap, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.ModelTemp.parentAbsPath, wrimsv2.wreslplus.elements.IncFileTemp.pathRelativeToRunDir, wrimsv2.wreslplus.elements.IncFileTemp.rawPath, and wrimsv2.wreslplus.elements.GlobalData.runDir.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile(), and processPath().
processPath() [3/3]
void wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath (StudyTemp s) static
Definition at line 61 of file ProcIncFile.java.
References wrimsv2.wreslplus.elements.StudyTemp.fileGroupOrder_incModel, wrimsv2.wreslplus.elements.StudyTemp.modelMap, and processPath().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ProcIncFile.java