Wrims-engine: wrimsv2.evaluator.EvalExpression Class Reference
wrimsv2.evaluator.EvalExpression Class Reference
Public Member Functions
EvalExpression ()
EvalExpression (IntDouble id)
EvalExpression copyOf ()
LinkedHashMap< String, IntDouble > copyOfMultiplier ()
LinkedHashMap< String, IntDouble > getMultiplier ()
IntDouble getValue ()
boolean isNumeric ()
void setMultiplier (LinkedHashMap< String, IntDouble > multiplier)
void setValue (IntDouble intDouble)
Private Attributes
IntDouble intDouble
LinkedHashMap< String, IntDouble > multiplier
Detailed Description
Definition at line 10 of file EvalExpression.java.
Constructor & Destructor Documentation
EvalExpression() [1/2]
wrimsv2.evaluator.EvalExpression.EvalExpression ()
Definition at line 14 of file EvalExpression.java.
References intDouble, and multiplier.
Referenced by copyOf().
EvalExpression() [2/2]
wrimsv2.evaluator.EvalExpression.EvalExpression (IntDouble id)
Definition at line 19 of file EvalExpression.java.
References intDouble, and multiplier.
Member Function Documentation
copyOf()
EvalExpression wrimsv2.evaluator.EvalExpression.copyOf ()
Definition at line 48 of file EvalExpression.java.
References EvalExpression(), copyOfMultiplier(), intDouble, setMultiplier(), and setValue().
copyOfMultiplier()
LinkedHashMap< String, IntDouble > wrimsv2.evaluator.EvalExpression.copyOfMultiplier ()
Definition at line 55 of file EvalExpression.java.
References multiplier.
Referenced by copyOf().
getMultiplier()
LinkedHashMap< String, IntDouble > wrimsv2.evaluator.EvalExpression.getMultiplier ()
Definition at line 32 of file EvalExpression.java.
References multiplier.
Referenced by wrimsv2.tools.CheckWeightSlackSurplus.CheckWeightSlackSurplus(), wrimsv2.evaluator.Evaluation.add(), wrimsv2.tools.MultiStepAnalyzer.analyzeOneConstraint(), wrimsv2.tools.RCCComparison.compareConstraint(), wrimsv2.evaluator.Evaluation.divide(), wrimsv2.components.DebugInterface.getAllControlGoalName(), wrimsv2.components.DebugInterface.getAllGoalFile(), wrimsv2.components.DebugInterface.getAllGoalString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.evaluator.Evaluation.mult(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), wrimsv2.solver.CbcSolver.setConstraintsSkip(), wrimsv2.evaluator.Evaluation.substract(), wrimsv2.evaluator.Evaluation.tafcfs_term(), wrimsv2.evaluator.Evaluation.term_IDENT(), and wrimsv2.evaluator.Evaluation.unary().
getValue()
IntDouble wrimsv2.evaluator.EvalExpression.getValue ()
Definition at line 24 of file EvalExpression.java.
References intDouble.
Referenced by wrimsv2.evaluator.Evaluation.abs(), wrimsv2.evaluator.Evaluation.acos(), wrimsv2.evaluator.Evaluation.acot(), wrimsv2.evaluator.Evaluation.add(), wrimsv2.tools.MultiStepAnalyzer.analyzeOneConstraint(), wrimsv2.evaluator.Evaluation.argFunction(), wrimsv2.evaluator.Evaluation.asin(), wrimsv2.evaluator.Evaluation.assignWhereStatement(), wrimsv2.evaluator.Evaluation.atan(), wrimsv2.tools.RCCComparison.compareConstraint(), wrimsv2.evaluator.Evaluation.cos(), wrimsv2.evaluator.Evaluation.cot(), wrimsv2.evaluator.Evaluation.divide(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.Evaluation.exp(), wrimsv2.evaluator.Evaluation.expressionInput(), wrimsv2.components.DebugInterface.getAllControlGoalName(), wrimsv2.components.DebugInterface.getAllGoalFile(), wrimsv2.components.DebugInterface.getAllGoalString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.intFunc(), wrimsv2.evaluator.Evaluation.log(), wrimsv2.evaluator.Evaluation.log10(), wrimsv2.evaluator.Evaluation.max(), wrimsv2.evaluator.Evaluation.min(), wrimsv2.evaluator.Evaluation.mod(), wrimsv2.evaluator.Evaluation.mult(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.Evaluation.pow(), wrimsv2.evaluator.Evaluation.realFunc(), wrimsv2.evaluator.Evaluation.relationStatement(), wrimsv2.evaluator.Evaluation.round(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), wrimsv2.solver.CbcSolver.setConstraintsSkip(), wrimsv2.evaluator.Evaluation.sin(), wrimsv2.evaluator.Evaluation.substract(), wrimsv2.evaluator.Evaluation.tafcfs_term(), wrimsv2.evaluator.Evaluation.tan(), and wrimsv2.evaluator.Evaluation.unary().
isNumeric()
boolean wrimsv2.evaluator.EvalExpression.isNumeric ()
Definition at line 40 of file EvalExpression.java.
References multiplier.
Referenced by wrimsv2.evaluator.Evaluation.abs(), wrimsv2.evaluator.Evaluation.acos(), wrimsv2.evaluator.Evaluation.acot(), wrimsv2.evaluator.Evaluation.argFunction(), wrimsv2.evaluator.Evaluation.asin(), wrimsv2.evaluator.Evaluation.assignWhereStatement(), wrimsv2.evaluator.Evaluation.atan(), wrimsv2.evaluator.Evaluation.cos(), wrimsv2.evaluator.Evaluation.cot(), wrimsv2.evaluator.Evaluation.divide(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.Evaluation.exp(), wrimsv2.evaluator.Evaluation.expressionInput(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.intFunc(), wrimsv2.evaluator.Evaluation.log(), wrimsv2.evaluator.Evaluation.log10(), wrimsv2.evaluator.Evaluation.max(), wrimsv2.evaluator.Evaluation.min(), wrimsv2.evaluator.Evaluation.mod(), wrimsv2.evaluator.Evaluation.mult(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.Evaluation.pow(), wrimsv2.evaluator.Evaluation.realFunc(), wrimsv2.evaluator.Evaluation.relationStatement(), wrimsv2.evaluator.Evaluation.round(), wrimsv2.evaluator.Evaluation.sin(), wrimsv2.evaluator.Evaluation.tafcfs_term(), and wrimsv2.evaluator.Evaluation.tan().
setMultiplier()
void wrimsv2.evaluator.EvalExpression.setMultiplier (LinkedHashMap< String, IntDouble > multiplier)
Definition at line 36 of file EvalExpression.java.
References multiplier.
Referenced by copyOf(), and wrimsv2.evaluator.Evaluation.getTimeSeries().
setValue()
void wrimsv2.evaluator.EvalExpression.setValue (IntDouble intDouble)
Definition at line 28 of file EvalExpression.java.
References intDouble.
Referenced by wrimsv2.evaluator.Evaluation.add(), copyOf(), wrimsv2.evaluator.Evaluation.divide(), wrimsv2.evaluator.Evaluation.mod(), wrimsv2.evaluator.Evaluation.mult(), wrimsv2.evaluator.Evaluation.round(), wrimsv2.evaluator.Evaluation.substract(), and wrimsv2.evaluator.Evaluation.term_IDENT().
Member Data Documentation
intDouble
IntDouble wrimsv2.evaluator.EvalExpression.intDouble private
Definition at line 11 of file EvalExpression.java.
Referenced by EvalExpression(), EvalExpression(), copyOf(), getValue(), and setValue().
multiplier
LinkedHashMap<String, IntDouble> wrimsv2.evaluator.EvalExpression.multiplier private
Definition at line 12 of file EvalExpression.java.
Referenced by EvalExpression(), EvalExpression(), copyOfMultiplier(), getMultiplier(), isNumeric(), and setMultiplier().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/EvalExpression.java