Wrims-engine: wrimsv2.ilp.CplexLpWriter Class Reference
wrimsv2.ilp.CplexLpWriter Class Reference
Static Public Member Functions
static void writeComment (PrintWriter outFile, String msg)
static void writeObjValue ()
Static Protected Member Functions
static void writeConstraint (PrintWriter outFile)
static void writeDvar (PrintWriter outFile, Set< String > dvar_effective)
static void writeObj (PrintWriter outFile, Map< String, WeightElement > activeWeightMap)
Private Member Functions
CplexLpWriter ()
Detailed Description
Definition at line 17 of file CplexLpWriter.java.
Constructor & Destructor Documentation
CplexLpWriter()
wrimsv2.ilp.CplexLpWriter.CplexLpWriter () private
Definition at line 19 of file CplexLpWriter.java.
Member Function Documentation
writeComment()
void wrimsv2.ilp.CplexLpWriter.writeComment (PrintWriter outFile, String msg) static
Definition at line 23 of file CplexLpWriter.java.
writeConstraint()
void wrimsv2.ilp.CplexLpWriter.writeConstraint (PrintWriter outFile) static protected
Definition at line 69 of file CplexLpWriter.java.
References wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap().
Referenced by wrimsv2.ilp.ILP.writeCplexLpFile().
writeDvar()
void wrimsv2.ilp.CplexLpWriter.writeDvar (PrintWriter outFile, Set< String > dvar_effective) static protected
Definition at line 139 of file CplexLpWriter.java.
References wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.ilp.ILP.intList, wrimsv2.commondata.wresldata.Param.lower_unbounded, wrimsv2.commondata.wresldata.Param.lower_unbounded_double, wrimsv2.commondata.wresldata.Param.upper_unbounded, wrimsv2.commondata.wresldata.Param.upper_unbounded_double, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by wrimsv2.ilp.ILP.writeCplexLpFile().
writeObj()
void wrimsv2.ilp.CplexLpWriter.writeObj (PrintWriter outFile, Map< String, WeightElement > activeWeightMap) static protected
Definition at line 36 of file CplexLpWriter.java.
Referenced by wrimsv2.ilp.ILP.writeCplexLpFile().
writeObjValue()
void wrimsv2.ilp.CplexLpWriter.writeObjValue () static
Definition at line 30 of file CplexLpWriter.java.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/ilp/CplexLpWriter.java