Wrims-engine: wrimsv2.wreslparser.elements.StructTree Class Reference
wrimsv2.wreslparser.elements.StructTree Class Reference
Public Member Functions
void alias (String name, String scope, String kind, String units, String expression, String dependants, String varInCycle)
void alias (String name, String scope, String kind, String units, String expression, String dependants, String varInCycle, String timeArraySizeStr)
void dvarNonStd (String name, String scope, String integer, String kind, String units, String lowerBound, String upperBound)
void dvarNonStd (String name, String scope, String integer, String kind, String units, String lowerBound, String upperBound, String timeArraySizeStr)
void dvarSlackSurplus (String name, String scope, String kind, String units, String conditionStr)
void dvarSlackSurplus (String name, String scope, String kind, String units, String conditionStr, String timeArraySizeStr)
void dvarStd (String name, String scope, String integer, String kind, String units)
void dvarStd (String name, String scope, String integer, String kind, String units, String timeArraySizeStr)
void external (String name, String scope, String externalType)
void goalCase (String name, String scope, Goal gl)
void goalCase (String name, String scope, Goal gl, String timeArraySizeStr)
Goal goalSimple (String name, String scope, String expression, String dependants, String varInCycle)
Goal goalSimple (String name, String scope, String expression, String dependants, String varInCycle, String timeArraySizeStr)
void includeFile (String fileRelativePath, String scope)
void mergeSlackSurplusIntoWeightTable (String name, String value, String scope, String conditionStr, String timeArraySizeStr)
void mergeWeightTable (String name, String value, String scope)
void mergeWeightTable (String name, String value, String scope, String timeArraySizeStr)
void modelList (String name)
void sequenceOrder (String sequenceName, String order, String modelName, String condition, String timeStep)
void svarCase (String name, String scope, Svar sv, String dependants, String varInCycle)
void svarCase (String name, String scope, Svar sv, String dependants, String varInCycle, String timeArraySizeStr)
void svarExpression (String name, String scope, String expression, String dependants, String varInCycle)
void svarExpression (String name, String scope, String expression, String dependants, String varInCycle, String timeArraySizeStr)
void svarSum (String name, String scope, String hdr, String expression, String dependants, String varInCycle)
void svarSum (String name, String scope, String hdr, String expression, String dependants, String varInCycle, String timeArraySizeStr)
void svarTable (String name, String scope, String sqlStr, String dependants, String varInCycle)
void svarTable (String name, String scope, String sqlStr, String dependants, String varInCycle, String timeArraySizeStr)
void timeseriesDss (String name, String scope, String b_part, String kind, String units, String convertToUnits)
Public Attributes
Alias as
Dvar dv
External ex
Goal gl
IncludeFile incFile
SimulationDataSet S
Sequence seq
Svar sv
Timeseries svTs
WeightElement wt
Static Public Attributes
static List< String > r_keys = Arrays.asList(keys)
static List< String > r_mons = Arrays.asList(mons)
Static Private Attributes
static String[] keys = { "define", "goal" }
static String[] mons
Detailed Description
Definition at line 16 of file StructTree.java.
Member Function Documentation
alias() [1/2]
void wrimsv2.wreslparser.elements.StructTree.alias (String name, String scope, String kind, String units, String expression, String dependants, String varInCycle)
Definition at line 229 of file StructTree.java.
References alias().
Referenced by alias().
alias() [2/2]
void wrimsv2.wreslparser.elements.StructTree.alias (String name, String scope, String kind, String units, String expression, String dependants, String varInCycle, String timeArraySizeStr)
Definition at line 233 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asList_global, wrimsv2.wreslparser.elements.SimulationDataSet.asList_local, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.wreslparser.elements.SimulationDataSet.asSet, wrimsv2.wreslparser.elements.SimulationDataSet.asSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.asSet_local, wrimsv2.wreslparser.elements.Tools.convertStrToSet(), wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.commondata.wresldata.Alias.timeArraySize, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
dvarNonStd() [1/2]
void wrimsv2.wreslparser.elements.StructTree.dvarNonStd (String name, String scope, String integer, String kind, String units, String lowerBound, String upperBound)
Definition at line 613 of file StructTree.java.
References dvarNonStd().
Referenced by dvarNonStd().
dvarNonStd() [2/2]
void wrimsv2.wreslparser.elements.StructTree.dvarNonStd (String name, String scope, String integer, String kind, String units, String lowerBound, String upperBound, String timeArraySizeStr)
Definition at line 618 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_local, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.wreslparser.elements.SimulationDataSet.var_all, and wrimsv2.commondata.wresldata.Param.yes.
dvarSlackSurplus() [1/2]
void wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus (String name, String scope, String kind, String units, String conditionStr)
Definition at line 692 of file StructTree.java.
References dvarSlackSurplus().
Referenced by dvarSlackSurplus().
dvarSlackSurplus() [2/2]
void wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus (String name, String scope, String kind, String units, String conditionStr, String timeArraySizeStr)
Definition at line 697 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.commondata.wresldata.Param.dv_std_lowerBound, wrimsv2.commondata.wresldata.Param.dv_std_upperBound, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_local, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.commondata.wresldata.Dvar.timeArraySize, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
dvarStd() [1/2]
void wrimsv2.wreslparser.elements.StructTree.dvarStd (String name, String scope, String integer, String kind, String units)
Definition at line 559 of file StructTree.java.
References dvarStd().
Referenced by dvarStd().
dvarStd() [2/2]
void wrimsv2.wreslparser.elements.StructTree.dvarStd (String name, String scope, String integer, String kind, String units, String timeArraySizeStr)
Definition at line 564 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.commondata.wresldata.Param.dv_std_integer_lowerBound, wrimsv2.commondata.wresldata.Param.dv_std_integer_upperBound, wrimsv2.commondata.wresldata.Param.dv_std_lowerBound, wrimsv2.commondata.wresldata.Param.dv_std_upperBound, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_local, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.wreslparser.elements.SimulationDataSet.var_all, and wrimsv2.commondata.wresldata.Param.yes.
external()
void wrimsv2.wreslparser.elements.StructTree.external (String name, String scope, String externalType)
Definition at line 327 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.wreslparser.elements.SimulationDataSet.exList, wrimsv2.wreslparser.elements.SimulationDataSet.exList_global, wrimsv2.wreslparser.elements.SimulationDataSet.exList_local, wrimsv2.wreslparser.elements.SimulationDataSet.exMap, wrimsv2.wreslparser.elements.SimulationDataSet.exSet, wrimsv2.wreslparser.elements.SimulationDataSet.exSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.exSet_local, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
goalCase() [1/2]
void wrimsv2.wreslparser.elements.StructTree.goalCase (String name, String scope, Goal gl)
Definition at line 191 of file StructTree.java.
References gl, and goalCase().
Referenced by goalCase().
goalCase() [2/2]
void wrimsv2.wreslparser.elements.StructTree.goalCase (String name, String scope, Goal gl, String timeArraySizeStr)
Definition at line 195 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, gl, wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gList_global, wrimsv2.wreslparser.elements.SimulationDataSet.gList_local, wrimsv2.commondata.wresldata.Param.global, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.gSet, wrimsv2.wreslparser.elements.SimulationDataSet.gSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.gSet_local, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
goalSimple() [1/2]
Goal wrimsv2.wreslparser.elements.StructTree.goalSimple (String name, String scope, String expression, String dependants, String varInCycle)
Definition at line 137 of file StructTree.java.
References goalSimple().
Referenced by goalSimple().
goalSimple() [2/2]
Goal wrimsv2.wreslparser.elements.StructTree.goalSimple (String name, String scope, String expression, String dependants, String varInCycle, String timeArraySizeStr)
Definition at line 141 of file StructTree.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.commondata.wresldata.Goal.caseCondition, wrimsv2.commondata.wresldata.Goal.caseExpression, wrimsv2.commondata.wresldata.Goal.caseName, wrimsv2.wreslparser.elements.Tools.convertStrToSet(), wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Goal.expressionDependants, gl, wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gList_global, wrimsv2.wreslparser.elements.SimulationDataSet.gList_local, wrimsv2.commondata.wresldata.Param.global, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.gSet, wrimsv2.wreslparser.elements.SimulationDataSet.gSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.gSet_local, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.commondata.wresldata.Param.reservedSet, wrimsv2.commondata.wresldata.Goal.timeArraySize, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
includeFile()
void wrimsv2.wreslparser.elements.StructTree.includeFile (String fileRelativePath, String scope)
Definition at line 86 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsoluteParent, wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.SimulationDataSet.incFileMap, wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet, wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet_local, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.wreslparser.elements.Tools.replace_pathseperator(), and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
mergeSlackSurplusIntoWeightTable()
void wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable (String name, String value, String scope, String conditionStr, String timeArraySizeStr)
Definition at line 739 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_weightVar_redefined, wrimsv2.commondata.wresldata.Param.local, wrimsv2.commondata.wresldata.WeightElement.timeArraySize, wrimsv2.wreslparser.elements.SimulationDataSet.wtList, wrimsv2.wreslparser.elements.SimulationDataSet.wtList_global, wrimsv2.wreslparser.elements.SimulationDataSet.wtList_local, wrimsv2.wreslparser.elements.SimulationDataSet.wtMap, wrimsv2.wreslparser.elements.SimulationDataSet.wtSet, wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_global, and wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_local.
mergeWeightTable() [1/2]
void wrimsv2.wreslparser.elements.StructTree.mergeWeightTable (String name, String value, String scope)
Definition at line 49 of file StructTree.java.
References mergeWeightTable().
Referenced by mergeWeightTable().
mergeWeightTable() [2/2]
void wrimsv2.wreslparser.elements.StructTree.mergeWeightTable (String name, String value, String scope, String timeArraySizeStr)
Definition at line 53 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_weightVar_redefined, wrimsv2.commondata.wresldata.Param.local, wrimsv2.commondata.wresldata.WeightElement.timeArraySize, wrimsv2.wreslparser.elements.SimulationDataSet.wtList, wrimsv2.wreslparser.elements.SimulationDataSet.wtList_global, wrimsv2.wreslparser.elements.SimulationDataSet.wtList_local, wrimsv2.wreslparser.elements.SimulationDataSet.wtMap, wrimsv2.wreslparser.elements.SimulationDataSet.wtSet, wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_global, and wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_local.
modelList()
void wrimsv2.wreslparser.elements.StructTree.modelList (String name)
Definition at line 35 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_model_redefined, wrimsv2.wreslparser.elements.SimulationDataSet.model_list, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
sequenceOrder()
void wrimsv2.wreslparser.elements.StructTree.sequenceOrder (String sequenceName, String order, String modelName, String condition, String timeStep)
Definition at line 665 of file StructTree.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.SimulationDataSet.error_sequence_order_redefined, wrimsv2.wreslparser.elements.SimulationDataSet.error_sequence_redefined, wrimsv2.wreslparser.elements.SimulationDataSet.seqList, wrimsv2.wreslparser.elements.SimulationDataSet.seqMap, and wrimsv2.wreslparser.elements.Sequence.timeStep.
svarCase() [1/2]
void wrimsv2.wreslparser.elements.StructTree.svarCase (String name, String scope, Svar sv, String dependants, String varInCycle)
Definition at line 281 of file StructTree.java.
References sv, and svarCase().
Referenced by svarCase().
svarCase() [2/2]
void wrimsv2.wreslparser.elements.StructTree.svarCase (String name, String scope, Svar sv, String dependants, String varInCycle, String timeArraySizeStr)
Definition at line 286 of file StructTree.java.
References wrimsv2.wreslparser.elements.Tools.convertStrToSet(), wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, sv, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_local, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
svarExpression() [1/2]
void wrimsv2.wreslparser.elements.StructTree.svarExpression (String name, String scope, String expression, String dependants, String varInCycle)
Definition at line 362 of file StructTree.java.
References svarExpression().
Referenced by svarExpression().
svarExpression() [2/2]
void wrimsv2.wreslparser.elements.StructTree.svarExpression (String name, String scope, String expression, String dependants, String varInCycle, String timeArraySizeStr)
Definition at line 367 of file StructTree.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseName, wrimsv2.wreslparser.elements.Tools.convertStrToSet(), wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_local, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
svarSum() [1/2]
void wrimsv2.wreslparser.elements.StructTree.svarSum (String name, String scope, String hdr, String expression, String dependants, String varInCycle)
Definition at line 417 of file StructTree.java.
References svarSum().
Referenced by svarSum().
svarSum() [2/2]
void wrimsv2.wreslparser.elements.StructTree.svarSum (String name, String scope, String hdr, String expression, String dependants, String varInCycle, String timeArraySizeStr)
Definition at line 422 of file StructTree.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseName, wrimsv2.wreslparser.elements.Tools.convertStrToSet(), wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_local, wrimsv2.commondata.wresldata.Svar.timeArraySize, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
svarTable() [1/2]
void wrimsv2.wreslparser.elements.StructTree.svarTable (String name, String scope, String sqlStr, String dependants, String varInCycle)
Definition at line 469 of file StructTree.java.
References svarTable().
Referenced by svarTable().
svarTable() [2/2]
void wrimsv2.wreslparser.elements.StructTree.svarTable (String name, String scope, String sqlStr, String dependants, String varInCycle, String timeArraySizeStr)
Definition at line 473 of file StructTree.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseName, wrimsv2.wreslparser.elements.Tools.convertStrToSet(), wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_local, wrimsv2.commondata.wresldata.Svar.timeArraySize, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
timeseriesDss()
void wrimsv2.wreslparser.elements.StructTree.timeseriesDss (String name, String scope, String b_part, String kind, String units, String convertToUnits)
Definition at line 521 of file StructTree.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined, wrimsv2.commondata.wresldata.Param.global, wrimsv2.commondata.wresldata.Param.local, wrimsv2.wreslparser.elements.SimulationDataSet.tsList, wrimsv2.wreslparser.elements.SimulationDataSet.tsList_global, wrimsv2.wreslparser.elements.SimulationDataSet.tsList_local, wrimsv2.wreslparser.elements.SimulationDataSet.tsMap, wrimsv2.wreslparser.elements.SimulationDataSet.tsSet, wrimsv2.wreslparser.elements.SimulationDataSet.tsSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.tsSet_local, and wrimsv2.wreslparser.elements.SimulationDataSet.var_all.
Member Data Documentation
as
Alias wrimsv2.wreslparser.elements.StructTree.as
Definition at line 26 of file StructTree.java.
dv
Dvar wrimsv2.wreslparser.elements.StructTree.dv
Definition at line 25 of file StructTree.java.
ex
External wrimsv2.wreslparser.elements.StructTree.ex
Definition at line 22 of file StructTree.java.
gl
Goal wrimsv2.wreslparser.elements.StructTree.gl
Definition at line 27 of file StructTree.java.
Referenced by goalCase(), goalCase(), and goalSimple().
incFile
IncludeFile wrimsv2.wreslparser.elements.StructTree.incFile
Definition at line 21 of file StructTree.java.
keys
String [] wrimsv2.wreslparser.elements.StructTree.keys = { "define", "goal" } static private
Definition at line 28 of file StructTree.java.
mons
String [] wrimsv2.wreslparser.elements.StructTree.mons static private
Initial value:
= { "JAN", "FEB", "MAR", "APR", "MAY", "JUN",
    "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }
Definition at line 29 of file StructTree.java.
r_keys
List<String> wrimsv2.wreslparser.elements.StructTree.r_keys = Arrays.asList(keys) static
Definition at line 32 of file StructTree.java.
r_mons
List<String> wrimsv2.wreslparser.elements.StructTree.r_mons = Arrays.asList(mons) static
Definition at line 33 of file StructTree.java.
S
SimulationDataSet wrimsv2.wreslparser.elements.StructTree.S
Definition at line 18 of file StructTree.java.
seq
Sequence wrimsv2.wreslparser.elements.StructTree.seq
Definition at line 20 of file StructTree.java.
sv
Svar wrimsv2.wreslparser.elements.StructTree.sv
Definition at line 24 of file StructTree.java.
Referenced by svarCase(), and svarCase().
svTs
Timeseries wrimsv2.wreslparser.elements.StructTree.svTs
Definition at line 23 of file StructTree.java.
wt
WeightElement wrimsv2.wreslparser.elements.StructTree.wt
Definition at line 19 of file StructTree.java.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/StructTree.java