Wrims-engine: wrimsv2.tools.solutionRangeFinder.DetectorWorkflow Class Reference
wrimsv2.tools.solutionRangeFinder.DetectorWorkflow Class Reference
Public Member Functions
DetectorWorkflow (MPModel mpm)
DetectorWorkflow (String mpmPath)
int findAltSolutions (ArrayList< String > searchVarList)
LinkedHashMap< String, double[]> getVarsRange ()
Protected Member Functions
boolean validateBaseModel (double obj_constraint_relax_ratio)
boolean validateOriginalModel ()
Private Attributes
MPModel baseModel = null
boolean isBaseValidated
boolean isOriginalValidated
MPModel originalModel = null
LinkedHashMap< String, double[]> varsRange_output
Detailed Description
Definition at line 18 of file DetectorWorkflow.java.
Constructor & Destructor Documentation
DetectorWorkflow() [1/2]
wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.DetectorWorkflow (MPModel mpm)
Definition at line 31 of file DetectorWorkflow.java.
References originalModel.
DetectorWorkflow() [2/2]
wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.DetectorWorkflow (String mpmPath)
Definition at line 41 of file DetectorWorkflow.java.
References wrimsv2.solver.mpmodel.MPModelUtils.load(), and originalModel.
Member Function Documentation
findAltSolutions()
int wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions (ArrayList< String > searchVarList)
Definition at line 146 of file DetectorWorkflow.java.
References wrimsv2.tools.solutionRangeFinder.DetectorParam.altSolutionFound, wrimsv2.tools.solutionRangeFinder.DetectorParam.altSolutionNotFound, baseModel, wrimsv2.tools.solutionRangeFinder.DetectorParam.excludeStrings, wrimsv2.tools.solutionRangeFinder.VarsGroup.filterVarsPool(), wrimsv2.tools.solutionRangeFinder.Misc.filterVarsRange(), wrimsv2.tools.solutionRangeFinder.VarsGroup.findVarsAtVertex(), wrimsv2.tools.solutionRangeFinder.Misc.findVarsRange(), wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), wrimsv2.tools.solutionRangeFinder.DetectorParam.includeStrings, isBaseValidated, isOriginalValidated, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsDir, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsFileNamePrepend, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsLogging, wrimsv2.wreslplus.elements.Tools.mapRetainAll(), wrimsv2.tools.solutionRangeFinder.DetectorParam.modelNotValid, wrimsv2.tools.solutionRangeFinder.DetectorParam.nonunique_min_abs_diff, wrimsv2.tools.solutionRangeFinder.DetectorParam.nonunique_min_ratio_diff, wrimsv2.tools.solutionRangeFinder.VarsGroup.notLowerVertexVars_number, wrimsv2.tools.solutionRangeFinder.VarsGroup.notUpperVertexVars_number, originalModel, wrimsv2.tools.solutionRangeFinder.DetectorParam.otherErrors, wrimsv2.tools.solutionRangeFinder.DetectorParam.searchLevel, wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.setLpsLoggingPath(), wrimsv2.tools.solutionRangeFinder.VarsGroup.setVarsPool(), wrimsv2.tools.solutionRangeFinder.Misc.updateVarsRange(), wrimsv2.tools.solutionRangeFinder.VarsGroup.varsPool, varsRange_output, and wrimsv2.tools.solutionRangeFinder.DetectorParam.vertax_tolerance.
getVarsRange()
LinkedHashMap< String, double[]> wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.getVarsRange ()
Definition at line 68 of file DetectorWorkflow.java.
References varsRange_output.
validateBaseModel()
boolean wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateBaseModel (double obj_constraint_relax_ratio) protected
Definition at line 109 of file DetectorWorkflow.java.
References baseModel, wrimsv2.solver.ortools.OrToolsSolver.delete(), wrimsv2.commondata.wresldata.Param.inf, isBaseValidated, isOriginalValidated, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsDir, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsFileNamePrepend, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsLogging, originalModel, wrimsv2.solver.ortools.OrToolsSolver.setVerbose(), wrimsv2.solver.ortools.OrToolsSolver.solution, wrimsv2.solver.ortools.OrToolsSolver.solve(), wrimsv2.solver.ortools.OrToolsSolver.solver, and wrimsv2.solver.mpmodel.MPModelUtils.toLpSolve().
validateOriginalModel()
boolean wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateOriginalModel () protected
Definition at line 73 of file DetectorWorkflow.java.
References wrimsv2.solver.ortools.OrToolsSolver.delete(), isOriginalValidated, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsDir, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsFileNamePrepend, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsLogging, originalModel, wrimsv2.solver.ortools.OrToolsSolver.setVerbose(), wrimsv2.solver.ortools.OrToolsSolver.solution, wrimsv2.solver.ortools.OrToolsSolver.solve(), wrimsv2.solver.ortools.OrToolsSolver.solver, and wrimsv2.solver.mpmodel.MPModelUtils.toLpSolve().
Member Data Documentation
baseModel
MPModel wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.baseModel = null private
Definition at line 24 of file DetectorWorkflow.java.
Referenced by findAltSolutions(), and validateBaseModel().
isBaseValidated
boolean wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.isBaseValidated private
Definition at line 27 of file DetectorWorkflow.java.
Referenced by findAltSolutions(), and validateBaseModel().
isOriginalValidated
boolean wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.isOriginalValidated private
Definition at line 26 of file DetectorWorkflow.java.
Referenced by findAltSolutions(), validateBaseModel(), and validateOriginalModel().
originalModel
MPModel wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.originalModel = null private
Definition at line 20 of file DetectorWorkflow.java.
Referenced by DetectorWorkflow(), DetectorWorkflow(), findAltSolutions(), validateBaseModel(), and validateOriginalModel().
varsRange_output
LinkedHashMap<String, double[]> wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.varsRange_output private
Definition at line 29 of file DetectorWorkflow.java.
Referenced by findAltSolutions(), and getVarsRange().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/solutionRangeFinder/DetectorWorkflow.java