Wrims-engine: wrimsv2.evaluator.PreEvaluator Class Reference
wrimsv2.evaluator.PreEvaluator Class Reference
Public Member Functions
PreEvaluator (StudyDataSet sds)
void preEvaluateAlias ()
void preEvaluateDvar ()
void preEvaluateGoal ()
void preEvaluateModelCondition (StudyDataSet sds)
void preEvaluateSvar ()
void preEvaluateWeight ()
void preEvaluateWeightSlackSurplus ()
Private Attributes
ArrayList< String > asList
Map< String, Alias > asMap
ArrayList< String > dvList
Map< String, Dvar > dvMap
ArrayList< String > gList
Map< String, Goal > gMap
ArrayList< String > modelConditionList
ArrayList< String > svList
Map< String, Svar > svMap
ArrayList< String > wtList
Map< String, WeightElement > wtMap
ArrayList< String > wtSlackSurplusList
Map< String, WeightElement > wtSlackSurplusMap
Detailed Description
Definition at line 23 of file PreEvaluator.java.
Constructor & Destructor Documentation
PreEvaluator()
wrimsv2.evaluator.PreEvaluator.PreEvaluator (StudyDataSet sds)
Definition at line 38 of file PreEvaluator.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asList, asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, asMap, wrimsv2.commondata.wresldata.ModelDataSet.dvList, dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, dvMap, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionList(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.ModelDataSet.gList, gList, wrimsv2.commondata.wresldata.ModelDataSet.gMap, gMap, modelConditionList, preEvaluateAlias(), preEvaluateDvar(), preEvaluateGoal(), preEvaluateModelCondition(), preEvaluateSvar(), preEvaluateWeight(), preEvaluateWeightSlackSurplus(), wrimsv2.commondata.wresldata.ModelDataSet.svList, svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, svMap, wrimsv2.commondata.wresldata.ModelDataSet.wtList, wtList, wrimsv2.commondata.wresldata.ModelDataSet.wtMap, wtMap, wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusList, wtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusMap, and wtSlackSurplusMap.
Member Function Documentation
preEvaluateAlias()
void wrimsv2.evaluator.PreEvaluator.preEvaluateAlias ()
Definition at line 119 of file PreEvaluator.java.
References asList, asMap, wrimsv2.commondata.wresldata.Alias.expression, and wrimsv2.commondata.wresldata.Alias.timeArraySize.
Referenced by PreEvaluator().
preEvaluateDvar()
void wrimsv2.evaluator.PreEvaluator.preEvaluateDvar ()
Definition at line 138 of file PreEvaluator.java.
References dvList, dvMap, wrimsv2.commondata.wresldata.Dvar.lowerBound, wrimsv2.commondata.wresldata.Dvar.timeArraySize, and wrimsv2.commondata.wresldata.Dvar.upperBound.
Referenced by PreEvaluator().
preEvaluateGoal()
void wrimsv2.evaluator.PreEvaluator.preEvaluateGoal ()
Definition at line 163 of file PreEvaluator.java.
References wrimsv2.commondata.wresldata.Goal.caseCondition, wrimsv2.commondata.wresldata.Goal.caseConditionParsers, wrimsv2.commondata.wresldata.Goal.caseExpression, wrimsv2.commondata.wresldata.Goal.caseExpressionParsers, gList, gMap, and wrimsv2.commondata.wresldata.Goal.timeArraySize.
Referenced by PreEvaluator().
preEvaluateModelCondition()
void wrimsv2.evaluator.PreEvaluator.preEvaluateModelCondition (StudyDataSet sds)
Definition at line 68 of file PreEvaluator.java.
References modelConditionList, and wrimsv2.commondata.wresldata.StudyDataSet.setModelConditionParsers().
Referenced by PreEvaluator().
preEvaluateSvar()
void wrimsv2.evaluator.PreEvaluator.preEvaluateSvar ()
Definition at line 195 of file PreEvaluator.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseConditionParsers, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseExpressionParsers, svList, svMap, and wrimsv2.commondata.wresldata.Svar.timeArraySize.
Referenced by PreEvaluator().
preEvaluateWeight()
void wrimsv2.evaluator.PreEvaluator.preEvaluateWeight ()
Definition at line 81 of file PreEvaluator.java.
References wrimsv2.commondata.wresldata.WeightElement.timeArraySize, wrimsv2.commondata.wresldata.WeightElement.weight, wtList, and wtMap.
Referenced by PreEvaluator().
preEvaluateWeightSlackSurplus()
void wrimsv2.evaluator.PreEvaluator.preEvaluateWeightSlackSurplus ()
Definition at line 100 of file PreEvaluator.java.
References wrimsv2.commondata.wresldata.WeightElement.timeArraySize, wrimsv2.commondata.wresldata.WeightElement.weight, wtSlackSurplusList, and wtSlackSurplusMap.
Referenced by PreEvaluator().
Member Data Documentation
asList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.asList private
Definition at line 30 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateAlias().
asMap
Map<String, Alias> wrimsv2.evaluator.PreEvaluator.asMap private
Definition at line 31 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateAlias().
dvList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.dvList private
Definition at line 28 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateDvar().
dvMap
Map<String, Dvar> wrimsv2.evaluator.PreEvaluator.dvMap private
Definition at line 29 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateDvar().
gList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.gList private
Definition at line 26 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateGoal().
gMap
Map<String, Goal> wrimsv2.evaluator.PreEvaluator.gMap private
Definition at line 27 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateGoal().
modelConditionList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.modelConditionList private
Definition at line 36 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateModelCondition().
svList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.svList private
Definition at line 24 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateSvar().
svMap
Map<String, Svar> wrimsv2.evaluator.PreEvaluator.svMap private
Definition at line 25 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateSvar().
wtList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.wtList private
Definition at line 32 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateWeight().
wtMap
Map<String, WeightElement> wrimsv2.evaluator.PreEvaluator.wtMap private
Definition at line 33 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateWeight().
wtSlackSurplusList
ArrayList<String> wrimsv2.evaluator.PreEvaluator.wtSlackSurplusList private
Definition at line 34 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateWeightSlackSurplus().
wtSlackSurplusMap
Map<String, WeightElement> wrimsv2.evaluator.PreEvaluator.wtSlackSurplusMap private
Definition at line 35 of file PreEvaluator.java.
Referenced by PreEvaluator(), and preEvaluateWeightSlackSurplus().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/PreEvaluator.java