Wrims-engine: wrimsv2.evaluator.DssDataSetFixLength Class Reference
wrimsv2.evaluator.DssDataSetFixLength Class Reference
Public Member Functions
DssDataSetFixLength ()
DssDataSetFixLength (int size)
boolean fromDssFile ()
double[] getData ()
String getKind ()
Date getStartTime ()
String getTimeStep ()
String getUnits ()
void setData (double[] data)
void setFromDssFile (boolean fromDssFile)
void setKind (String kind)
void setStartTime (Date st)
void setTimeStep (String timeStep)
void setUnits (String units)
Public Attributes
double[] data
Private Attributes
boolean fromDssFile =false
String kind
Date startTime
String timeStep
String units
Detailed Description
Definition at line 6 of file DssDataSetFixLength.java.
Constructor & Destructor Documentation
DssDataSetFixLength() [1/2]
wrimsv2.evaluator.DssDataSetFixLength.DssDataSetFixLength ()
Definition at line 14 of file DssDataSetFixLength.java.
DssDataSetFixLength() [2/2]
wrimsv2.evaluator.DssDataSetFixLength.DssDataSetFixLength (int size)
Definition at line 18 of file DssDataSetFixLength.java.
References data.
Member Function Documentation
fromDssFile()
boolean wrimsv2.evaluator.DssDataSetFixLength.fromDssFile ()
Definition at line 49 of file DssDataSetFixLength.java.
References fromDssFile.
getData()
double[] wrimsv2.evaluator.DssDataSetFixLength.getData ()
Definition at line 29 of file DssDataSetFixLength.java.
References data.
Referenced by wrimsv2.hdf5.HDF5Writer.differMonthlyDailyCycle(), wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.DebugInterface.modifyTimeSeries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), wrimsv2.evaluator.DssOperation.shiftDvAliasData(), wrimsv2.components.ControllerDebug.updateVarMonitor(), wrimsv2.sql.MySQLCWriter.writeDailyData(), wrimsv2.sql.MySQLRWriterAlt.writeData(), wrimsv2.sql.SQLServerRWriterAlt.writeData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), and wrimsv2.sql.MySQLCWriter.writeMonthlyData().
getKind()
String wrimsv2.evaluator.DssDataSetFixLength.getKind ()
Definition at line 69 of file DssDataSetFixLength.java.
References kind.
Referenced by wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.sql.MySQLCWriter.formPathName(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.sql.MySQLRWriterAlt.writeData(), wrimsv2.sql.SQLServerRWriterAlt.writeData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
getStartTime()
Date wrimsv2.evaluator.DssDataSetFixLength.getStartTime ()
Definition at line 41 of file DssDataSetFixLength.java.
References startTime.
Referenced by wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.evaluator.Evaluation.timeSeriesIndex(), wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), wrimsv2.sql.MySQLCWriter.writeDailyData(), wrimsv2.sql.MySQLRWriterAlt.writeData(), wrimsv2.sql.SQLServerRWriterAlt.writeData(), and wrimsv2.sql.MySQLCWriter.writeMonthlyData().
getTimeStep()
String wrimsv2.evaluator.DssDataSetFixLength.getTimeStep ()
Definition at line 45 of file DssDataSetFixLength.java.
References timeStep.
Referenced by wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.sql.MySQLCWriter.createTables(), wrimsv2.hdf5.HDF5Writer.differMonthlyDailyCycle(), wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), wrimsv2.evaluator.DssOperation.shiftDvAliasData(), wrimsv2.evaluator.Evaluation.timeSeriesIndex(), wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), wrimsv2.sql.MySQLRWriterAlt.writeData(), wrimsv2.sql.SQLServerRWriterAlt.writeData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
getUnits()
String wrimsv2.evaluator.DssDataSetFixLength.getUnits ()
Definition at line 61 of file DssDataSetFixLength.java.
References units.
Referenced by wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.sql.MySQLCWriter.formUnitsName(), wrimsv2.sql.MySQLRWriterAlt.formUnitsName(), wrimsv2.sql.SQLServerRWriterAlt.formUnitsName(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
setData()
void wrimsv2.evaluator.DssDataSetFixLength.setData (double[] data)
Definition at line 25 of file DssDataSetFixLength.java.
References data.
Referenced by wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength().
setFromDssFile()
void wrimsv2.evaluator.DssDataSetFixLength.setFromDssFile (boolean fromDssFile)
Definition at line 53 of file DssDataSetFixLength.java.
References fromDssFile.
Referenced by wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength().
setKind()
void wrimsv2.evaluator.DssDataSetFixLength.setKind (String kind)
Definition at line 65 of file DssDataSetFixLength.java.
References kind.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), and wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries().
setStartTime()
void wrimsv2.evaluator.DssDataSetFixLength.setStartTime (Date st)
Definition at line 37 of file DssDataSetFixLength.java.
References startTime.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), and wrimsv2.evaluator.DssOperation.shiftDvAliasData().
setTimeStep()
void wrimsv2.evaluator.DssDataSetFixLength.setTimeStep (String timeStep)
Definition at line 33 of file DssDataSetFixLength.java.
References timeStep.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), and wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries().
setUnits()
void wrimsv2.evaluator.DssDataSetFixLength.setUnits (String units)
Definition at line 57 of file DssDataSetFixLength.java.
References units.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), and wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries().
Member Data Documentation
data
double [] wrimsv2.evaluator.DssDataSetFixLength.data
Definition at line 7 of file DssDataSetFixLength.java.
Referenced by DssDataSetFixLength(), getData(), and setData().
fromDssFile
boolean wrimsv2.evaluator.DssDataSetFixLength.fromDssFile =false private
Definition at line 12 of file DssDataSetFixLength.java.
Referenced by fromDssFile(), and setFromDssFile().
kind
String wrimsv2.evaluator.DssDataSetFixLength.kind private
Definition at line 10 of file DssDataSetFixLength.java.
Referenced by getKind(), and setKind().
startTime
Date wrimsv2.evaluator.DssDataSetFixLength.startTime private
Definition at line 11 of file DssDataSetFixLength.java.
Referenced by getStartTime(), and setStartTime().
timeStep
String wrimsv2.evaluator.DssDataSetFixLength.timeStep private
Definition at line 8 of file DssDataSetFixLength.java.
Referenced by getTimeStep(), and setTimeStep().
units
String wrimsv2.evaluator.DssDataSetFixLength.units private
Definition at line 9 of file DssDataSetFixLength.java.
Referenced by getUnits(), and setUnits().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/DssDataSetFixLength.java