Wrims-engine: wrimsv2.launch.LaunchConfiguration Class Reference
wrimsv2.launch.LaunchConfiguration Class Reference
Public Member Functions
LaunchConfiguration (String filePath)
boolean getBooleanAttribute (String key, boolean defaultValue)
int getIntAttribute (String key, int defaultValue)
List getListAttribute (String key, List defaultValue)
Map getMapAttribute (String key, Map defaultValue)
String getStringAttribute (String key, String defaultValue)
String procRelativePath (String path, String launchFilePath)
void setConfig (String filePath)
void setPref ()
Static Public Attributes
static final String ATTR_WPP_ALLOWSVTSINIT =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ALLOWSVTSINIT"
static final String ATTR_WPP_ALLRESTARTFILES =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ALLRESTARTFILES"
static final String ATTR_WPP_APART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_APART"
static final String ATTR_WPP_AUTHOR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_AUTHOR"
static final String ATTR_WPP_CALSIMHYDROEXE =ID_WPP_DEBUG_MODEL + ".CALSIMHYDROEXE"
static final String ATTR_WPP_CALSIMHYDRORUN =ID_WPP_DEBUG_MODEL + ".CALSIMHYDRORUN"
static final String ATTR_WPP_DATABASEURL =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DATABASEURL"
static final String ATTR_WPP_DATATRANSFER =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DATATRANSFER"
static final String ATTR_WPP_DATE =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DATE"
static final String ATTR_WPP_DESCRIPTION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DESCRIPTION"
static final String ATTR_WPP_DVARFILE = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DVAR"
static final String ATTR_WPP_ENDDAY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ENDDAY"
static final String ATTR_WPP_ENDMONTH =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ENDMONTH"
static final String ATTR_WPP_ENDYEAR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ENDYEAR"
static final String ATTR_WPP_FIXEDDURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_MSDURATION"
static final String ATTR_WPP_FREEXA =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_FREEXA"
static final String ATTR_WPP_GWDATAFOLDER =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_GWDATA"
static final String ATTR_WPP_ILPLOG =ID_WPP_DEBUG_MODEL+".ILPLOG"
static final String ATTR_WPP_INITFILE = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_INIT"
static final String ATTR_WPP_INITFPART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_INITFPART"
static final String ATTR_WPP_ISFIXDURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ISFIXDURATION"
static final String ATTR_WPP_ISSENSITIVITYRUN =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ISSENSITIVITYRUN"
static final String ATTR_WPP_LAUNCHTYPE =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_LAUNCHTYPE"
static final String ATTR_WPP_MULTISTUDY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_MULTISTUDY"
static final String ATTR_WPP_NUMBERRESTARTFILES =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_NUMBERRESTARTFILES"
static final String ATTR_WPP_NUMSENSITIVITYRUN =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_NUMSENSITIVITYRUN"
static final String ATTR_WPP_OVFILE =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_OVFILE"
static final String ATTR_WPP_OVOPTION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_OVOPTION"
static final String ATTR_WPP_PADELINIT =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADELINIT"
static final String ATTR_WPP_PADURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADURATION"
static final String ATTR_WPP_PADVSTARTDAY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADVSTARTDAY"
static final String ATTR_WPP_PADVSTARTMONTH =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADVSTARTMONTH"
static final String ATTR_WPP_PADVSTARTYEAR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADVSTARTYEAR"
static final String ATTR_WPP_PARESETDVSTART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PARESETDVSTART"
static final String ATTR_WPP_PASTARTINTERVAL =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PASTARTINTERVAL"
static final String ATTR_WPP_PROGRAM = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PROGRAM"
static final String ATTR_WPP_SENSITIVITYINDEXTABLENAME =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SENSITIVITYINDEXTABLENAME"
static final String ATTR_WPP_SQLGROUP =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SQLGROUP"
static final String ATTR_WPP_STARTDAY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STARTDAY"
static final String ATTR_WPP_STARTMONTH =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STARTMONTH"
static final String ATTR_WPP_STARTYEAR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STARTYEAR"
static final String ATTR_WPP_STUDY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STUDY"
static final String ATTR_WPP_SVARFILE = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SVAR"
static final String ATTR_WPP_SVFPART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SVFPART"
static final String ATTR_WPP_TIMESTEP =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_TIMESTEP"
static final String ATTR_WPP_UNCHANGEGWRESTART =ID_WPP_DEBUG_MODEL + "ATTR_WPP_UNCHANGEGWRESTART"
static final String ATTR_WPP_VARIABLEDURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_VARIABLEDURATION"
static final String ATTR_WPP_VHECLIB =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_VHECLIB"
static final String ATTR_WPP_WRESLPLUS =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_WRESLPLUS"
static final String ID_WPP_ALLGOAL_VIEW ="wpp.allgoalview"
static final String ID_WPP_ALLVARIABLE_VIEW ="wpp.allvariableview"
static final String ID_WPP_CALSIMHYDRO_VIEW = "wpp.calsimhydroview"
static final String ID_WPP_CLEARCONDITIONALBREAKPOINT ="wpp.clearconditionalbreakpoint"
static final String ID_WPP_CONDITIONALBREAKPOINT ="wpp.conditionalbreakpoint"
static final String ID_WPP_DEBUG_MODEL = "wpp.debugModel"
static final String ID_WPP_EDITOR ="wpp.editor"
static final String ID_WPP_EXCEPTION_VIEW = "wpp.exceptionview"
static final String ID_WPP_FILEINCEXPLORE_VIEW = "wpp.fileincexploreview"
static final String ID_WPP_GOAL_VIEW ="wpp.goalview"
static final String ID_WPP_NEXTCYCLE ="wpp.nextcycle"
static final String ID_WPP_NEXTCYCLEBUTTON ="wpp.nextcyclebutton"
static final String ID_WPP_NEXTTIMESTEP ="wpp.nexttimestep"
static final String ID_WPP_NEXTTIMESTEPBUTTON ="wpp.nexttimestepbutton"
static final String ID_WPP_PAUSEMENU ="wpp.pause"
static final String ID_WPP_PAUSERESUMEBUTTON ="wpp.pauseresumebutton"
static final String ID_WPP_PLUGIN ="wrims-ide"
static final String ID_WPP_RESIMMENU ="wpp.resim"
static final String ID_WPP_RESUMEMENU ="wpp.resume"
static final String ID_WPP_SAVETODVFILE ="wpp.savedvfile"
static final String ID_WPP_SAVETOSVFILE ="wpp.savesvfile"
static final String ID_WPP_SOLVEROPTIONMENU ="wpp.solveroption"
static final String ID_WPP_SUSPENDMENU ="wpp.suspend"
static final String ID_WPP_TERMINATEMENU ="wpp.terminate"
static final String ID_WPP_VARIABLE_VIEW ="wpp.variableview"
static final String ID_WPP_VARIABLEDETAIL_VIEW ="wpp.vardetailview"
static final String ID_WPP_VARIABLEMONITOR_VIEW ="wpp.varmonitorview"
static final String ID_WPP_WATCH_VIEW ="wpp.watchview"
Protected Member Functions
String getKeyAttribute (Element element)
String getValueAttribute (Element element)
void initializeFromXML (Element root)
void setAttribute (String key, Object value)
void setBooleanAttribute (Element element)
void setIntegerAttribute (Element element)
void setListAttribute (Element element)
void setMapAttribute (Element element)
void setStringAttribute (Element element)
Private Member Functions
HashMap getAttributeTable ()
Private Attributes
HashMap fAttributes =new HashMap()
Detailed Description
Definition at line 29 of file LaunchConfiguration.java.
Constructor & Destructor Documentation
LaunchConfiguration()
wrimsv2.launch.LaunchConfiguration.LaunchConfiguration (String filePath)
Definition at line 115 of file LaunchConfiguration.java.
References initializeFromXML(), setConfig(), and setPref().
Member Function Documentation
getAttributeTable()
HashMap wrimsv2.launch.LaunchConfiguration.getAttributeTable () private
Definition at line 257 of file LaunchConfiguration.java.
References fAttributes.
Referenced by getBooleanAttribute(), getIntAttribute(), getListAttribute(), getMapAttribute(), getStringAttribute(), and setAttribute().
getBooleanAttribute()
boolean wrimsv2.launch.LaunchConfiguration.getBooleanAttribute (String key, boolean defaultValue)
Definition at line 281 of file LaunchConfiguration.java.
References getAttributeTable().
getIntAttribute()
int wrimsv2.launch.LaunchConfiguration.getIntAttribute (String key, int defaultValue)
Definition at line 271 of file LaunchConfiguration.java.
References getAttributeTable().
getKeyAttribute()
String wrimsv2.launch.LaunchConfiguration.getKeyAttribute (Element element) protected
Definition at line 311 of file LaunchConfiguration.java.
Referenced by setBooleanAttribute(), setIntegerAttribute(), setMapAttribute(), and setStringAttribute().
getListAttribute()
List wrimsv2.launch.LaunchConfiguration.getListAttribute (String key, List defaultValue)
Definition at line 291 of file LaunchConfiguration.java.
References getAttributeTable().
getMapAttribute()
Map wrimsv2.launch.LaunchConfiguration.getMapAttribute (String key, Map defaultValue)
Definition at line 301 of file LaunchConfiguration.java.
References getAttributeTable().
getStringAttribute()
String wrimsv2.launch.LaunchConfiguration.getStringAttribute (String key, String defaultValue)
Definition at line 261 of file LaunchConfiguration.java.
References getAttributeTable().
Referenced by setConfig().
getValueAttribute()
String wrimsv2.launch.LaunchConfiguration.getValueAttribute (Element element) protected
Definition at line 319 of file LaunchConfiguration.java.
Referenced by setBooleanAttribute(), setIntegerAttribute(), setListAttribute(), setMapAttribute(), and setStringAttribute().
initializeFromXML()
void wrimsv2.launch.LaunchConfiguration.initializeFromXML (Element root) protected
Definition at line 136 of file LaunchConfiguration.java.
References setBooleanAttribute(), setIntegerAttribute(), setListAttribute(), setMapAttribute(), and setStringAttribute().
Referenced by LaunchConfiguration().
procRelativePath()
String wrimsv2.launch.LaunchConfiguration.procRelativePath (String path, String launchFilePath)
Definition at line 438 of file LaunchConfiguration.java.
Referenced by setConfig().
setAttribute()
void wrimsv2.launch.LaunchConfiguration.setAttribute (String key, Object value) protected
Definition at line 188 of file LaunchConfiguration.java.
References getAttributeTable().
Referenced by setBooleanAttribute(), setIntegerAttribute(), setListAttribute(), setMapAttribute(), and setStringAttribute().
setBooleanAttribute()
void wrimsv2.launch.LaunchConfiguration.setBooleanAttribute (Element element) protected
Definition at line 208 of file LaunchConfiguration.java.
References getKeyAttribute(), getValueAttribute(), and setAttribute().
Referenced by initializeFromXML().
setConfig()
void wrimsv2.launch.LaunchConfiguration.setConfig (String filePath)
Definition at line 327 of file LaunchConfiguration.java.
References wrimsv2.components.ControlData.allRestartFiles, ATTR_WPP_ALLRESTARTFILES, ATTR_WPP_APART, ATTR_WPP_DATABASEURL, ATTR_WPP_DVARFILE, ATTR_WPP_ENDDAY, ATTR_WPP_ENDMONTH, ATTR_WPP_ENDYEAR, ATTR_WPP_GWDATAFOLDER, ATTR_WPP_ILPLOG, ATTR_WPP_INITFILE, ATTR_WPP_INITFPART, ATTR_WPP_NUMBERRESTARTFILES, ATTR_WPP_OVFILE, ATTR_WPP_OVOPTION, ATTR_WPP_PROGRAM, ATTR_WPP_SQLGROUP, ATTR_WPP_STARTDAY, ATTR_WPP_STARTMONTH, ATTR_WPP_STARTYEAR, ATTR_WPP_SVARFILE, ATTR_WPP_SVFPART, ATTR_WPP_TIMESTEP, ATTR_WPP_UNCHANGEGWRESTART, ATTR_WPP_VHECLIB, ATTR_WPP_WRESLPLUS, wrimsv2.components.ControlData.databaseURL, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, getStringAttribute(), wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingAllCycles, wrimsv2.ilp.ILP.loggingCplexLp, wrimsv2.evaluator.TimeOperation.monthValue(), wrimsv2.components.ControlData.numberRestartFiles, wrimsv2.components.ControlData.ovFile, wrimsv2.components.ControlData.ovOption, wrimsv2.components.ControlData.partA, procRelativePath(), wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.sqlGroup, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.ControlData.svDvPartF, wrimsv2.components.ControlData.timeStep, wrimsv2.components.ControlData.unchangeGWRestart, wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus, and wrimsv2.components.ControlData.vHecLib.
Referenced by LaunchConfiguration().
setIntegerAttribute()
void wrimsv2.launch.LaunchConfiguration.setIntegerAttribute (Element element) protected
Definition at line 202 of file LaunchConfiguration.java.
References getKeyAttribute(), getValueAttribute(), and setAttribute().
Referenced by initializeFromXML().
setListAttribute()
void wrimsv2.launch.LaunchConfiguration.setListAttribute (Element element) protected
Definition at line 214 of file LaunchConfiguration.java.
References getValueAttribute(), and setAttribute().
Referenced by initializeFromXML().
setMapAttribute()
void wrimsv2.launch.LaunchConfiguration.setMapAttribute (Element element) protected
Definition at line 235 of file LaunchConfiguration.java.
References getKeyAttribute(), getValueAttribute(), and setAttribute().
Referenced by initializeFromXML().
setPref()
void wrimsv2.launch.LaunchConfiguration.setPref ()
Definition at line 444 of file LaunchConfiguration.java.
References wrimsv2.launch.SettingPref.load(), and wrimsv2.launch.SettingPref.loadCBCSetting().
Referenced by LaunchConfiguration().
setStringAttribute()
void wrimsv2.launch.LaunchConfiguration.setStringAttribute (Element element) protected
Definition at line 196 of file LaunchConfiguration.java.
References getKeyAttribute(), getValueAttribute(), and setAttribute().
Referenced by initializeFromXML().
Member Data Documentation
ATTR_WPP_ALLOWSVTSINIT
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ALLOWSVTSINIT =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ALLOWSVTSINIT" static
Definition at line 84 of file LaunchConfiguration.java.
ATTR_WPP_ALLRESTARTFILES
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ALLRESTARTFILES =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ALLRESTARTFILES" static
Definition at line 108 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_APART
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_APART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_APART" static
Definition at line 72 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_AUTHOR
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_AUTHOR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_AUTHOR" static
Definition at line 64 of file LaunchConfiguration.java.
ATTR_WPP_CALSIMHYDROEXE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_CALSIMHYDROEXE =ID_WPP_DEBUG_MODEL + ".CALSIMHYDROEXE" static
Definition at line 106 of file LaunchConfiguration.java.
ATTR_WPP_CALSIMHYDRORUN
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_CALSIMHYDRORUN =ID_WPP_DEBUG_MODEL + ".CALSIMHYDRORUN" static
Definition at line 105 of file LaunchConfiguration.java.
ATTR_WPP_DATABASEURL
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_DATABASEURL =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DATABASEURL" static
Definition at line 98 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_DATATRANSFER
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_DATATRANSFER =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DATATRANSFER" static
Definition at line 90 of file LaunchConfiguration.java.
ATTR_WPP_DATE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_DATE =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DATE" static
Definition at line 65 of file LaunchConfiguration.java.
ATTR_WPP_DESCRIPTION
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_DESCRIPTION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DESCRIPTION" static
Definition at line 66 of file LaunchConfiguration.java.
ATTR_WPP_DVARFILE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_DVARFILE = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_DVAR" static
Definition at line 68 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_ENDDAY
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ENDDAY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ENDDAY" static
Definition at line 81 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_ENDMONTH
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ENDMONTH =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ENDMONTH" static
Definition at line 80 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_ENDYEAR
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ENDYEAR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ENDYEAR" static
Definition at line 79 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_FIXEDDURATION
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_FIXEDDURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_MSDURATION" static
Definition at line 88 of file LaunchConfiguration.java.
ATTR_WPP_FREEXA
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_FREEXA =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_FREEXA" static
Definition at line 83 of file LaunchConfiguration.java.
ATTR_WPP_GWDATAFOLDER
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_GWDATAFOLDER =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_GWDATA" static
Definition at line 71 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_ILPLOG
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ILPLOG =ID_WPP_DEBUG_MODEL+".ILPLOG" static
Definition at line 107 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_INITFILE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_INITFILE = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_INIT" static
Definition at line 70 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_INITFPART
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_INITFPART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_INITFPART" static
Definition at line 74 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_ISFIXDURATION
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ISFIXDURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ISFIXDURATION" static
Definition at line 87 of file LaunchConfiguration.java.
ATTR_WPP_ISSENSITIVITYRUN
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_ISSENSITIVITYRUN =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_ISSENSITIVITYRUN" static
Definition at line 102 of file LaunchConfiguration.java.
ATTR_WPP_LAUNCHTYPE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_LAUNCHTYPE =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_LAUNCHTYPE" static
Definition at line 85 of file LaunchConfiguration.java.
ATTR_WPP_MULTISTUDY
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_MULTISTUDY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_MULTISTUDY" static
Definition at line 86 of file LaunchConfiguration.java.
ATTR_WPP_NUMBERRESTARTFILES
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_NUMBERRESTARTFILES =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_NUMBERRESTARTFILES" static
Definition at line 109 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_NUMSENSITIVITYRUN
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_NUMSENSITIVITYRUN =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_NUMSENSITIVITYRUN" static
Definition at line 104 of file LaunchConfiguration.java.
ATTR_WPP_OVFILE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_OVFILE =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_OVFILE" static
Definition at line 101 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_OVOPTION
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_OVOPTION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_OVOPTION" static
Definition at line 100 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_PADELINIT
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PADELINIT =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADELINIT" static
Definition at line 93 of file LaunchConfiguration.java.
ATTR_WPP_PADURATION
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PADURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADURATION" static
Definition at line 92 of file LaunchConfiguration.java.
ATTR_WPP_PADVSTARTDAY
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PADVSTARTDAY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADVSTARTDAY" static
Definition at line 97 of file LaunchConfiguration.java.
ATTR_WPP_PADVSTARTMONTH
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PADVSTARTMONTH =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADVSTARTMONTH" static
Definition at line 96 of file LaunchConfiguration.java.
ATTR_WPP_PADVSTARTYEAR
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PADVSTARTYEAR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PADVSTARTYEAR" static
Definition at line 95 of file LaunchConfiguration.java.
ATTR_WPP_PARESETDVSTART
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PARESETDVSTART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PARESETDVSTART" static
Definition at line 94 of file LaunchConfiguration.java.
ATTR_WPP_PASTARTINTERVAL
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PASTARTINTERVAL =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PASTARTINTERVAL" static
Definition at line 91 of file LaunchConfiguration.java.
ATTR_WPP_PROGRAM
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_PROGRAM = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_PROGRAM" static
Definition at line 67 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_SENSITIVITYINDEXTABLENAME
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_SENSITIVITYINDEXTABLENAME =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SENSITIVITYINDEXTABLENAME" static
Definition at line 103 of file LaunchConfiguration.java.
ATTR_WPP_SQLGROUP
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_SQLGROUP =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SQLGROUP" static
Definition at line 99 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_STARTDAY
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_STARTDAY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STARTDAY" static
Definition at line 78 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_STARTMONTH
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_STARTMONTH =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STARTMONTH" static
Definition at line 77 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_STARTYEAR
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_STARTYEAR =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STARTYEAR" static
Definition at line 76 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_STUDY
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_STUDY =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_STUDY" static
Definition at line 63 of file LaunchConfiguration.java.
ATTR_WPP_SVARFILE
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_SVARFILE = ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SVAR" static
Definition at line 69 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_SVFPART
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_SVFPART =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_SVFPART" static
Definition at line 73 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_TIMESTEP
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_TIMESTEP =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_TIMESTEP" static
Definition at line 75 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_UNCHANGEGWRESTART
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_UNCHANGEGWRESTART =ID_WPP_DEBUG_MODEL + "ATTR_WPP_UNCHANGEGWRESTART" static
Definition at line 110 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_VARIABLEDURATION
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_VARIABLEDURATION =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_VARIABLEDURATION" static
Definition at line 89 of file LaunchConfiguration.java.
ATTR_WPP_VHECLIB
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_VHECLIB =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_VHECLIB" static
Definition at line 111 of file LaunchConfiguration.java.
Referenced by setConfig().
ATTR_WPP_WRESLPLUS
final String wrimsv2.launch.LaunchConfiguration.ATTR_WPP_WRESLPLUS =ID_WPP_DEBUG_MODEL + ".ATTR_WPP_WRESLPLUS" static
Definition at line 82 of file LaunchConfiguration.java.
Referenced by setConfig().
fAttributes
HashMap wrimsv2.launch.LaunchConfiguration.fAttributes =new HashMap() private
Definition at line 31 of file LaunchConfiguration.java.
Referenced by getAttributeTable().
ID_WPP_ALLGOAL_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_ALLGOAL_VIEW ="wpp.allgoalview" static
Definition at line 41 of file LaunchConfiguration.java.
ID_WPP_ALLVARIABLE_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_ALLVARIABLE_VIEW ="wpp.allvariableview" static
Definition at line 36 of file LaunchConfiguration.java.
ID_WPP_CALSIMHYDRO_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_CALSIMHYDRO_VIEW = "wpp.calsimhydroview" static
Definition at line 43 of file LaunchConfiguration.java.
ID_WPP_CLEARCONDITIONALBREAKPOINT
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_CLEARCONDITIONALBREAKPOINT ="wpp.clearconditionalbreakpoint" static
Definition at line 54 of file LaunchConfiguration.java.
ID_WPP_CONDITIONALBREAKPOINT
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_CONDITIONALBREAKPOINT ="wpp.conditionalbreakpoint" static
Definition at line 53 of file LaunchConfiguration.java.
ID_WPP_DEBUG_MODEL
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_DEBUG_MODEL = "wpp.debugModel" static
Definition at line 34 of file LaunchConfiguration.java.
ID_WPP_EDITOR
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_EDITOR ="wpp.editor" static
Definition at line 45 of file LaunchConfiguration.java.
ID_WPP_EXCEPTION_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_EXCEPTION_VIEW = "wpp.exceptionview" static
Definition at line 44 of file LaunchConfiguration.java.
ID_WPP_FILEINCEXPLORE_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_FILEINCEXPLORE_VIEW = "wpp.fileincexploreview" static
Definition at line 42 of file LaunchConfiguration.java.
ID_WPP_GOAL_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_GOAL_VIEW ="wpp.goalview" static
Definition at line 40 of file LaunchConfiguration.java.
ID_WPP_NEXTCYCLE
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_NEXTCYCLE ="wpp.nextcycle" static
Definition at line 51 of file LaunchConfiguration.java.
ID_WPP_NEXTCYCLEBUTTON
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_NEXTCYCLEBUTTON ="wpp.nextcyclebutton" static
Definition at line 60 of file LaunchConfiguration.java.
ID_WPP_NEXTTIMESTEP
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_NEXTTIMESTEP ="wpp.nexttimestep" static
Definition at line 50 of file LaunchConfiguration.java.
ID_WPP_NEXTTIMESTEPBUTTON
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_NEXTTIMESTEPBUTTON ="wpp.nexttimestepbutton" static
Definition at line 61 of file LaunchConfiguration.java.
ID_WPP_PAUSEMENU
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_PAUSEMENU ="wpp.pause" static
Definition at line 48 of file LaunchConfiguration.java.
ID_WPP_PAUSERESUMEBUTTON
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_PAUSERESUMEBUTTON ="wpp.pauseresumebutton" static
Definition at line 59 of file LaunchConfiguration.java.
ID_WPP_PLUGIN
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_PLUGIN ="wrims-ide" static
Definition at line 33 of file LaunchConfiguration.java.
ID_WPP_RESIMMENU
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_RESIMMENU ="wpp.resim" static
Definition at line 52 of file LaunchConfiguration.java.
ID_WPP_RESUMEMENU
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_RESUMEMENU ="wpp.resume" static
Definition at line 46 of file LaunchConfiguration.java.
ID_WPP_SAVETODVFILE
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_SAVETODVFILE ="wpp.savedvfile" static
Definition at line 55 of file LaunchConfiguration.java.
ID_WPP_SAVETOSVFILE
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_SAVETOSVFILE ="wpp.savesvfile" static
Definition at line 56 of file LaunchConfiguration.java.
ID_WPP_SOLVEROPTIONMENU
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_SOLVEROPTIONMENU ="wpp.solveroption" static
Definition at line 57 of file LaunchConfiguration.java.
ID_WPP_SUSPENDMENU
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_SUSPENDMENU ="wpp.suspend" static
Definition at line 49 of file LaunchConfiguration.java.
ID_WPP_TERMINATEMENU
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_TERMINATEMENU ="wpp.terminate" static
Definition at line 47 of file LaunchConfiguration.java.
ID_WPP_VARIABLE_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_VARIABLE_VIEW ="wpp.variableview" static
Definition at line 35 of file LaunchConfiguration.java.
ID_WPP_VARIABLEDETAIL_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_VARIABLEDETAIL_VIEW ="wpp.vardetailview" static
Definition at line 38 of file LaunchConfiguration.java.
ID_WPP_VARIABLEMONITOR_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_VARIABLEMONITOR_VIEW ="wpp.varmonitorview" static
Definition at line 39 of file LaunchConfiguration.java.
ID_WPP_WATCH_VIEW
final String wrimsv2.launch.LaunchConfiguration.ID_WPP_WATCH_VIEW ="wpp.watchview" static
Definition at line 37 of file LaunchConfiguration.java.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/launch/LaunchConfiguration.java