Wrims-engine: JavaTest.JavaTest Class Reference
JavaTest.JavaTest Class Reference
Public Member Functions
__str__ (self)
getAbsoluteDifference (self, a, b)
getText (self)
instanceTest (self)
isAnInteger (self, value)
Detailed Description
Definition at line 6 of file JavaTest.py.
Member Function Documentation
__str__()
JavaTest.JavaTest.__str__ (self)
Definition at line 7 of file JavaTest.py.
getAbsoluteDifference()
JavaTest.JavaTest.getAbsoluteDifference (self, a, b)
Definition at line 29 of file JavaTest.py.
References getAbsoluteDifference(), and JavaTest.MyCustomClass.
Referenced by getAbsoluteDifference().
getText()
JavaTest.JavaTest.getText (self)
Definition at line 23 of file JavaTest.py.
References getText(), and JavaTest.MyCustomClass.
Referenced by getText().
instanceTest()
JavaTest.JavaTest.instanceTest (self)
Definition at line 10 of file JavaTest.py.
References JavaTest.MyCustomClass.
isAnInteger()
JavaTest.JavaTest.isAnInteger (self, value)
Definition at line 26 of file JavaTest.py.
The documentation for this class was generated from the following file:
wrims-core/src/test/resources/python/JavaTest.py