Wrims-engine: wrimsv2.wreslplus.elements.procedures.ProcWeight Class Reference
wrimsv2.wreslplus.elements.procedures.ProcWeight Class Reference
Static Public Member Functions
static void collectWeightVar (ModelTemp mObj)
static void collectWeightVar (ModelTemp mObj, StudyTemp st)
static void collectWeightVar (StudyTemp s)
static void processWeightGroup (ModelTemp mObj)
static void processWeightGroup (StudyTemp st)
Private Member Functions
ProcWeight ()
Detailed Description
Definition at line 14 of file ProcWeight.java.
Constructor & Destructor Documentation
ProcWeight()
wrimsv2.wreslplus.elements.procedures.ProcWeight.ProcWeight () private
Definition at line 16 of file ProcWeight.java.
Member Function Documentation
collectWeightVar() [1/3]
void wrimsv2.wreslplus.elements.procedures.ProcWeight.collectWeightVar (ModelTemp mObj) static
Definition at line 274 of file ProcWeight.java.
References wrimsv2.wreslplus.elements.WeightTable.isWeightGroup, wrimsv2.wreslplus.elements.WeightTable.varList, wrimsv2.wreslplus.elements.ModelTemp.wTableObjList, and wrimsv2.wreslplus.elements.ModelTemp.wvList_post.
collectWeightVar() [2/3]
void wrimsv2.wreslplus.elements.procedures.ProcWeight.collectWeightVar (ModelTemp mObj, StudyTemp st) static
Definition at line 289 of file ProcWeight.java.
References collectWeightVar(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, and wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList_post.
collectWeightVar() [3/3]
void wrimsv2.wreslplus.elements.procedures.ProcWeight.collectWeightVar (StudyTemp s) static
Definition at line 222 of file ProcWeight.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, collectWeightVar(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), collectWeightVar(), collectWeightVar(), and wrimsv2.components.DebugInterface.getVariableInOneFileWP().
processWeightGroup() [1/2]
void wrimsv2.wreslplus.elements.procedures.ProcWeight.processWeightGroup (ModelTemp mObj) static
process subgroup
process subgroup
process main group
process main group
Definition at line 65 of file ProcWeight.java.
References wrimsv2.wreslplus.elements.procedures.Misc.addWeightInGroupWeightMap(), wrimsv2.wreslplus.elements.WeightTable.commonWeight, wrimsv2.wreslplus.elements.WeightTable.condition, wrimsv2.wreslplus.elements.procedures.Misc.createDvarInModelObj(), wrimsv2.wreslplus.elements.procedures.Misc.createGoalInModelObj(), wrimsv2.wreslplus.elements.WeightTable.dependants, wrimsv2.wreslplus.elements.WeightTable.deviationPenalty, wrimsv2.wreslplus.elements.ModelTemp.deviationSlackSurplus_toleranceMap, wrimsv2.wreslplus.elements.WeightTable.deviationTolerance, wrimsv2.wreslplus.elements.ModelTemp.dvList_deviationSlackSurplus, wrimsv2.wreslplus.elements.WeightTable.fromWresl, wrimsv2.wreslplus.elements.WeightTable.id_lowcase, wrimsv2.wreslplus.elements.WeightTable.isWeightGroup, wrimsv2.commondata.wresldata.Param.lower_unbounded, wrimsv2.wreslplus.elements.WeightTable.subgroupMap, wrimsv2.commondata.wresldata.Param.upper_unbounded, wrimsv2.wreslplus.elements.WeightTable.varList, wrimsv2.wreslplus.elements.ModelTemp.wTableObjList, and wrimsv2.commondata.wresldata.Param.zero.
processWeightGroup() [2/2]
void wrimsv2.wreslplus.elements.procedures.ProcWeight.processWeightGroup (StudyTemp st) static
Definition at line 21 of file ProcWeight.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, processWeightGroup(), wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and processWeightGroup().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ProcWeight.java