Wrims-engine: wrimsv2.components.TimeUsage Class Reference
wrimsv2.components.TimeUsage Class Reference
Static Public Member Functions
static void showTimeUsage ()
Static Public Attributes
static Map< String, Integer > cpuTimeMap = new HashMap<String, Integer>()
static Map< String, Integer > nCallsMap = new HashMap<String, Integer>()
Detailed Description
Definition at line 9 of file TimeUsage.java.
Member Function Documentation
showTimeUsage()
void wrimsv2.components.TimeUsage.showTimeUsage () static
Definition at line 14 of file TimeUsage.java.
References wrimsv2.ilp.ILP._noteFile_timeusage, cpuTimeMap, wrimsv2.components.ControlData.n_ann, wrimsv2.components.ControlData.n_annec, wrimsv2.components.ControlData.n_annec_matchdsm2, wrimsv2.components.ControlData.n_anngetndo_x2, wrimsv2.components.ControlData.n_anngetndo_x2_curmonndosplit, wrimsv2.components.ControlData.n_annlinegen, wrimsv2.components.ControlData.n_annx2, nCallsMap, wrimsv2.components.ControlData.t_ann, wrimsv2.components.ControlData.t_annec, wrimsv2.components.ControlData.t_annec_matchdsm2, wrimsv2.components.ControlData.t_anngetndo_x2, wrimsv2.components.ControlData.t_anngetndo_x2_curmonndosplit, wrimsv2.components.ControlData.t_annlinegen, wrimsv2.components.ControlData.t_annx2, wrimsv2.components.ControlData.t_as, wrimsv2.components.ControlData.t_cam, wrimsv2.components.ControlData.t_cbc, wrimsv2.components.ControlData.t_dvar, wrimsv2.components.ControlData.t_goal, wrimsv2.components.ControlData.t_parse, wrimsv2.components.ControlData.t_readTs, wrimsv2.components.ControlData.t_svar, wrimsv2.components.ControlData.t_ts, wrimsv2.components.ControlData.t_writeDss, wrimsv2.components.ControlData.t_wt, wrimsv2.components.ControlData.t_wtss, wrimsv2.components.ControlData.t_xa, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), and wrimsv2.components.ControllerDebug.runModel().
Member Data Documentation
cpuTimeMap
Map<String, Integer> wrimsv2.components.TimeUsage.cpuTimeMap = new HashMap<String, Integer>() static
Definition at line 11 of file TimeUsage.java.
Referenced by wrimsv2.external.Functionemmatonsurrogateec.Functionemmatonsurrogateec(), wrimsv2.external.Functionemmatonsurrogatelinegen.Functionemmatonsurrogatelinegen(), wrimsv2.external.Functionrequiredsac.Functionrequiredsac(), wrimsv2.external.Functionsurrogateec.Functionsurrogateec(), wrimsv2.external.Functionsurrogateeclinearize.Functionsurrogateeclinearize(), wrimsv2.external.Functionemmatonsurrogateec.execute(), wrimsv2.external.Functionemmatonsurrogatelinegen.execute(), wrimsv2.external.Functionrequiredsac.execute(), wrimsv2.external.Functionsurrogateec.execute(), wrimsv2.external.Functionsurrogateeclinearize.execute(), and showTimeUsage().
nCallsMap
Map<String, Integer> wrimsv2.components.TimeUsage.nCallsMap = new HashMap<String, Integer>() static
Definition at line 12 of file TimeUsage.java.
Referenced by wrimsv2.external.Functionemmatonsurrogateec.Functionemmatonsurrogateec(), wrimsv2.external.Functionemmatonsurrogatelinegen.Functionemmatonsurrogatelinegen(), wrimsv2.external.Functionrequiredsac.Functionrequiredsac(), wrimsv2.external.Functionsurrogateec.Functionsurrogateec(), wrimsv2.external.Functionsurrogateeclinearize.Functionsurrogateeclinearize(), wrimsv2.external.Functionemmatonsurrogateec.execute(), wrimsv2.external.Functionemmatonsurrogatelinegen.execute(), wrimsv2.external.Functionrequiredsac.execute(), wrimsv2.external.Functionsurrogateec.execute(), wrimsv2.external.Functionsurrogateeclinearize.execute(), and showTimeUsage().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/TimeUsage.java