Wrims-engine: wrimsv2.hdf5.HDF5Writer Class Reference
wrimsv2.hdf5.HDF5Writer Class Reference
Static Public Member Functions
static void closeDataStructure ()
static void createDataStructure ()
static void createDvarAliasLookup ()
static void differMonthlyDailyCycle (HashMap< String, DssDataSetFixLength > dvAliasCycle)
static void listCycleDvAliasVariables (String strCycleI)
static void listCycleStaticSv (StudyDataSet sds)
static void listDailyTimestepDvarAlias ()
static void listMonthlyTimestepDvarAlias ()
static void skipDailyCycle (ModelDataSet mds, int index)
static void skipDailyCycleStaticSv (ModelDataSet mds, int index)
static void skipMonthlyCycle (ModelDataSet mds, int index)
static void skipMonthlyCycleStaticSv (ModelDataSet mds, int index)
static void skipOneCycle (ModelDataSet mds, int index)
static void writeCyclesDvAlias ()
static void writeDailyCycleDvarAlias (String strCycleI)
static void writeDailyCycleDynamicSv (ModelDataSet mds, int index)
static void writeDailyCycleStaticSv (ModelDataSet mds, int index)
static void writeDailyCycleSv (ModelDataSet mds, int index)
static void writeDailyTimestepDvarAlias ()
static void writeMonthlyCycleDvarAlias (String strCycleI)
static void writeMonthlyCycleDynamicSv (ModelDataSet mds, int index)
static void writeMonthlyCycleStaticSv (ModelDataSet mds, int index)
static void writeMonthlyCycleSv (ModelDataSet mds, int index)
static void writeMonthlyTimestepDvarAlias ()
static void writeMonthlyTimestepDvarAlias_deprecated ()
static void writeOneCycleSv (ModelDataSet mds, int index)
static void writeTimestepData ()
static void writeTimestepDvarAlias ()
Static Private Attributes
static double[][] dailyCycleData
static String[] dailyCycleVarNames
static int dailyDim =0
static Map< String, String > dailyDvarAliasKindMap = new HashMap<String, String>()
static ArrayList< String > dailyDvarAliasList = new ArrayList<String>()
static Map< String, String > dailyDvarAliasMap = new HashMap<String, String>()
static int[] dvAsLookupIndex
static String[] dvAsLookupKinds
static String[] dvAsLookupNames
static String[] dvAsLookupTimestep
static String[] dvAsLookupUnits
static int fid =-1
static String gCS ="Cycles DV Alias"
static String gCSDaily ="Daily"
static String gCSMonthly ="Monthly"
static String gDaily ="Daily"
static String gData ="Data"
static String gDC ="Dynamic Cycle SV"
static String gDCDaily ="Daily"
static String gDCMonthly ="Monthly"
static int gidCS =-1
static int gidCSDaily =-1
static int gidCSMonthly =-1
static int gidDaily =-1
static int gidData =-1
static int gidDC =-1
static int gidDCDaily =-1
static int gidDCMonthly =-1
static int gidInfo =-1
static int gidIOData =-1
static int gidMonthly =-1
static int gidPartA =-1
static int gidPartF =-1
static int gidSC =-1
static int gidSCDaily =-1
static int gidSCMonthly =-1
static String gInfo ="Info"
static String gIOData ="IO Data"
static String gMonthly ="Monthly"
static String gPartA =ControlData.partA
static String gPartF =ControlData.svDvPartF
static String gSC ="Static Cycle SV"
static String gSCDaily ="Daily"
static String gSCMonthly ="Monthly"
static String h5FileName =""
static boolean hasDvarAliasLookup =false
static double[][] monthlyCycleData
static String[] monthlyCycleVarNames
static int monthlyDim =0
static Map< String, String > monthlyDvarAliasKindMap = new HashMap<String, String>()
static ArrayList< String > monthlyDvarAliasList = new ArrayList<String>()
static Map< String, String > monthlyDvarAliasMap = new HashMap<String, String>()
Detailed Description
Definition at line 29 of file HDF5Writer.java.
Member Function Documentation
closeDataStructure()
void wrimsv2.hdf5.HDF5Writer.closeDataStructure () static
Definition at line 1066 of file HDF5Writer.java.
References fid, gidCS, gidCSDaily, gidCSMonthly, gidDaily, gidData, gidDC, gidDCDaily, gidDCMonthly, gidInfo, gidIOData, gidMonthly, gidPartA, gidPartF, gidSC, gidSCDaily, and gidSCMonthly.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
createDataStructure()
void wrimsv2.hdf5.HDF5Writer.createDataStructure () static
Definition at line 84 of file HDF5Writer.java.
References wrimsv2.components.ControlData.dailyStartTime, wrimsv2.evaluator.TimeOperation.dssTimeEndDay(), fid, wrimsv2.components.FilePaths.fullDvarHDF5Path, gCS, gCSDaily, gCSMonthly, gDaily, gData, gDC, gDCDaily, gDCMonthly, gidCS, gidCSDaily, gidCSMonthly, gidDaily, gidData, gidDC, gidDCDaily, gidDCMonthly, gidInfo, gidIOData, gidMonthly, gidPartA, gidPartF, gidSC, gidSCDaily, gidSCMonthly, gInfo, gIOData, gMonthly, gPartA, gPartF, gSC, gSCDaily, gSCMonthly, h5FileName, wrimsv2.hdf5.HDF5Util.locateFile(), wrimsv2.hdf5.HDF5Util.locateGroup(), wrimsv2.components.ControlData.monthlyStartTime, and wrimsv2.hdf5.HDF5Util.writeStringAttr().
Referenced by wrimsv2.components.PreRunModel.PreRunModel().
createDvarAliasLookup()
void wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup () static
Definition at line 279 of file HDF5Writer.java.
References dailyDvarAliasKindMap, dailyDvarAliasList, dailyDvarAliasMap, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, dvAsLookupIndex, dvAsLookupKinds, dvAsLookupNames, dvAsLookupTimestep, dvAsLookupUnits, wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.evaluator.DssDataSetFixLength.getUnits(), gidInfo, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), monthlyDvarAliasKindMap, monthlyDvarAliasList, monthlyDvarAliasMap, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
differMonthlyDailyCycle()
void wrimsv2.hdf5.HDF5Writer.differMonthlyDailyCycle (HashMap< String, DssDataSetFixLength > dvAliasCycle) static
Definition at line 762 of file HDF5Writer.java.
References dailyCycleData, dailyCycleVarNames, dailyDim, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), monthlyCycleData, monthlyCycleVarNames, and monthlyDim.
Referenced by writeCyclesDvAlias().
listCycleDvAliasVariables()
void wrimsv2.hdf5.HDF5Writer.listCycleDvAliasVariables (String strCycleI) static
Definition at line 820 of file HDF5Writer.java.
References dailyCycleVarNames, gidCSDaily, gidCSMonthly, monthlyCycleVarNames, and wrimsv2.hdf5.HDF5Util.writeCycleVariableNames().
Referenced by writeCyclesDvAlias().
listCycleStaticSv()
void wrimsv2.hdf5.HDF5Writer.listCycleStaticSv (StudyDataSet sds) static
Definition at line 740 of file HDF5Writer.java.
References wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), gidSCDaily, gidSCMonthly, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.tools.General.isSelectedCycleOutput(), and wrimsv2.hdf5.HDF5Util.writeCycleStaticSvNames().
Referenced by wrimsv2.components.PreRunModel.PreRunModel().
listDailyTimestepDvarAlias()
void wrimsv2.hdf5.HDF5Writer.listDailyTimestepDvarAlias () static
Definition at line 660 of file HDF5Writer.java.
References dailyDvarAliasKindMap, dailyDvarAliasList, dailyDvarAliasMap, gidDaily, gidInfo, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by writeTimestepDvarAlias().
listMonthlyTimestepDvarAlias()
void wrimsv2.hdf5.HDF5Writer.listMonthlyTimestepDvarAlias () static
Definition at line 600 of file HDF5Writer.java.
References gidInfo, gidMonthly, monthlyDvarAliasKindMap, monthlyDvarAliasList, monthlyDvarAliasMap, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by writeTimestepDvarAlias().
skipDailyCycle()
void wrimsv2.hdf5.HDF5Writer.skipDailyCycle (ModelDataSet mds, int index) static
Definition at line 1020 of file HDF5Writer.java.
References gidSCDaily, and skipDailyCycleStaticSv().
Referenced by skipOneCycle().
skipDailyCycleStaticSv()
void wrimsv2.hdf5.HDF5Writer.skipDailyCycleStaticSv (ModelDataSet mds, int index) static
Definition at line 1046 of file HDF5Writer.java.
References gidSCDaily, wrimsv2.commondata.wresldata.ModelDataSet.svList, and wrimsv2.hdf5.HDF5Util.writeCycleStaticSv().
Referenced by skipDailyCycle().
skipMonthlyCycle()
void wrimsv2.hdf5.HDF5Writer.skipMonthlyCycle (ModelDataSet mds, int index) static
Definition at line 1014 of file HDF5Writer.java.
References gidSCMonthly, and skipMonthlyCycleStaticSv().
Referenced by skipOneCycle().
skipMonthlyCycleStaticSv()
void wrimsv2.hdf5.HDF5Writer.skipMonthlyCycleStaticSv (ModelDataSet mds, int index) static
Definition at line 1026 of file HDF5Writer.java.
References gidSCMonthly, wrimsv2.commondata.wresldata.ModelDataSet.svList, and wrimsv2.hdf5.HDF5Util.writeCycleStaticSv().
Referenced by skipMonthlyCycle().
skipOneCycle()
void wrimsv2.hdf5.HDF5Writer.skipOneCycle (ModelDataSet mds, int index) static
Definition at line 1004 of file HDF5Writer.java.
References fid, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), skipDailyCycle(), skipMonthlyCycle(), and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
writeCyclesDvAlias()
void wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias () static
Definition at line 399 of file HDF5Writer.java.
References differMonthlyDailyCycle(), wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, fid, wrimsv2.components.ControlData.isOutputCycle, wrimsv2.tools.General.isSelectedCycleOutput(), listCycleDvAliasVariables(), writeDailyCycleDvarAlias(), and writeMonthlyCycleDvarAlias().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
writeDailyCycleDvarAlias()
void wrimsv2.hdf5.HDF5Writer.writeDailyCycleDvarAlias (String strCycleI) static
Definition at line 864 of file HDF5Writer.java.
References dailyCycleData, dailyCycleVarNames, dailyDim, and gidCSDaily.
Referenced by writeCyclesDvAlias().
writeDailyCycleDynamicSv()
void wrimsv2.hdf5.HDF5Writer.writeDailyCycleDynamicSv (ModelDataSet mds, int index) static
Definition at line 999 of file HDF5Writer.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, gidDCDaily, and wrimsv2.hdf5.HDF5Util.writeCycleDynamicSv().
Referenced by writeDailyCycleSv().
writeDailyCycleStaticSv()
void wrimsv2.hdf5.HDF5Writer.writeDailyCycleStaticSv (ModelDataSet mds, int index) static
Definition at line 948 of file HDF5Writer.java.
References gidSCDaily, wrimsv2.commondata.wresldata.ModelDataSet.svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, and wrimsv2.hdf5.HDF5Util.writeCycleStaticSv().
Referenced by writeDailyCycleSv().
writeDailyCycleSv()
void wrimsv2.hdf5.HDF5Writer.writeDailyCycleSv (ModelDataSet mds, int index) static
Definition at line 735 of file HDF5Writer.java.
References gidDCDaily, gidSCDaily, writeDailyCycleDynamicSv(), and writeDailyCycleStaticSv().
Referenced by writeOneCycleSv().
writeDailyTimestepDvarAlias()
void wrimsv2.hdf5.HDF5Writer.writeDailyTimestepDvarAlias () static
Definition at line 548 of file HDF5Writer.java.
References dailyDvarAliasList, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, and gidDaily.
Referenced by writeTimestepDvarAlias().
writeMonthlyCycleDvarAlias()
void wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleDvarAlias (String strCycleI) static
Definition at line 825 of file HDF5Writer.java.
References gidCSMonthly, monthlyCycleData, monthlyCycleVarNames, and monthlyDim.
Referenced by writeCyclesDvAlias().
writeMonthlyCycleDynamicSv()
void wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleDynamicSv (ModelDataSet mds, int index) static
Definition at line 994 of file HDF5Writer.java.
References wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, gidDCMonthly, and wrimsv2.hdf5.HDF5Util.writeCycleDynamicSv().
Referenced by writeMonthlyCycleSv().
writeMonthlyCycleStaticSv()
void wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleStaticSv (ModelDataSet mds, int index) static
Definition at line 903 of file HDF5Writer.java.
References gidSCMonthly, wrimsv2.commondata.wresldata.ModelDataSet.svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, and wrimsv2.hdf5.HDF5Util.writeCycleStaticSv().
Referenced by writeMonthlyCycleSv().
writeMonthlyCycleSv()
void wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleSv (ModelDataSet mds, int index) static
Definition at line 728 of file HDF5Writer.java.
References gidDCMonthly, gidSCMonthly, writeMonthlyCycleDynamicSv(), and writeMonthlyCycleStaticSv().
Referenced by writeOneCycleSv().
writeMonthlyTimestepDvarAlias()
void wrimsv2.hdf5.HDF5Writer.writeMonthlyTimestepDvarAlias () static
Definition at line 494 of file HDF5Writer.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasTS, gidMonthly, and monthlyDvarAliasList.
Referenced by writeTimestepDvarAlias().
writeMonthlyTimestepDvarAlias_deprecated()
void wrimsv2.hdf5.HDF5Writer.writeMonthlyTimestepDvarAlias_deprecated () static
Definition at line 424 of file HDF5Writer.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasTS, gidMonthly, and monthlyDvarAliasList.
writeOneCycleSv()
void wrimsv2.hdf5.HDF5Writer.writeOneCycleSv (ModelDataSet mds, int index) static
Definition at line 718 of file HDF5Writer.java.
References fid, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.timeStep, writeDailyCycleSv(), and writeMonthlyCycleSv().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
writeTimestepData()
void wrimsv2.hdf5.HDF5Writer.writeTimestepData () static
Definition at line 393 of file HDF5Writer.java.
References fid, and writeTimestepDvarAlias().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
writeTimestepDvarAlias()
void wrimsv2.hdf5.HDF5Writer.writeTimestepDvarAlias () static
Definition at line 416 of file HDF5Writer.java.
References listDailyTimestepDvarAlias(), listMonthlyTimestepDvarAlias(), writeDailyTimestepDvarAlias(), and writeMonthlyTimestepDvarAlias().
Referenced by writeTimestepData().
Member Data Documentation
dailyCycleData
double [][] wrimsv2.hdf5.HDF5Writer.dailyCycleData static private
Definition at line 80 of file HDF5Writer.java.
Referenced by differMonthlyDailyCycle(), and writeDailyCycleDvarAlias().
dailyCycleVarNames
String [] wrimsv2.hdf5.HDF5Writer.dailyCycleVarNames static private
Definition at line 78 of file HDF5Writer.java.
Referenced by differMonthlyDailyCycle(), listCycleDvAliasVariables(), and writeDailyCycleDvarAlias().
dailyDim
int wrimsv2.hdf5.HDF5Writer.dailyDim =0 static private
Definition at line 82 of file HDF5Writer.java.
Referenced by differMonthlyDailyCycle(), and writeDailyCycleDvarAlias().
dailyDvarAliasKindMap
Map<String, String> wrimsv2.hdf5.HDF5Writer.dailyDvarAliasKindMap = new HashMap<String, String>() static private
Definition at line 42 of file HDF5Writer.java.
Referenced by createDvarAliasLookup(), and listDailyTimestepDvarAlias().
dailyDvarAliasList
ArrayList<String> wrimsv2.hdf5.HDF5Writer.dailyDvarAliasList = new ArrayList<String>() static private
Definition at line 38 of file HDF5Writer.java.
Referenced by createDvarAliasLookup(), listDailyTimestepDvarAlias(), and writeDailyTimestepDvarAlias().
dailyDvarAliasMap
Map<String, String> wrimsv2.hdf5.HDF5Writer.dailyDvarAliasMap = new HashMap<String, String>() static private
Definition at line 40 of file HDF5Writer.java.
Referenced by createDvarAliasLookup(), and listDailyTimestepDvarAlias().
dvAsLookupIndex
int [] wrimsv2.hdf5.HDF5Writer.dvAsLookupIndex static private
Definition at line 36 of file HDF5Writer.java.
Referenced by createDvarAliasLookup().
dvAsLookupKinds
String [] wrimsv2.hdf5.HDF5Writer.dvAsLookupKinds static private
Definition at line 33 of file HDF5Writer.java.
Referenced by createDvarAliasLookup().
dvAsLookupNames
String [] wrimsv2.hdf5.HDF5Writer.dvAsLookupNames static private
Definition at line 32 of file HDF5Writer.java.
Referenced by createDvarAliasLookup().
dvAsLookupTimestep
String [] wrimsv2.hdf5.HDF5Writer.dvAsLookupTimestep static private
Definition at line 35 of file HDF5Writer.java.
Referenced by createDvarAliasLookup().
dvAsLookupUnits
String [] wrimsv2.hdf5.HDF5Writer.dvAsLookupUnits static private
Definition at line 34 of file HDF5Writer.java.
Referenced by createDvarAliasLookup().
fid
int wrimsv2.hdf5.HDF5Writer.fid =-1 static private
Definition at line 44 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), skipOneCycle(), writeCyclesDvAlias(), writeOneCycleSv(), and writeTimestepData().
gCS
String wrimsv2.hdf5.HDF5Writer.gCS ="Cycles DV Alias" static private
Definition at line 63 of file HDF5Writer.java.
Referenced by createDataStructure().
gCSDaily
String wrimsv2.hdf5.HDF5Writer.gCSDaily ="Daily" static private
Definition at line 75 of file HDF5Writer.java.
Referenced by createDataStructure().
gCSMonthly
String wrimsv2.hdf5.HDF5Writer.gCSMonthly ="Monthly" static private
Definition at line 73 of file HDF5Writer.java.
Referenced by createDataStructure().
gDaily
String wrimsv2.hdf5.HDF5Writer.gDaily ="Daily" static private
Definition at line 57 of file HDF5Writer.java.
Referenced by createDataStructure().
gData
String wrimsv2.hdf5.HDF5Writer.gData ="Data" static private
Definition at line 53 of file HDF5Writer.java.
Referenced by createDataStructure().
gDC
String wrimsv2.hdf5.HDF5Writer.gDC ="Dynamic Cycle SV" static private
Definition at line 61 of file HDF5Writer.java.
Referenced by createDataStructure().
gDCDaily
String wrimsv2.hdf5.HDF5Writer.gDCDaily ="Daily" static private
Definition at line 71 of file HDF5Writer.java.
Referenced by createDataStructure().
gDCMonthly
String wrimsv2.hdf5.HDF5Writer.gDCMonthly ="Monthly" static private
Definition at line 69 of file HDF5Writer.java.
Referenced by createDataStructure().
gidCS
int wrimsv2.hdf5.HDF5Writer.gidCS =-1 static private
Definition at line 64 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidCSDaily
int wrimsv2.hdf5.HDF5Writer.gidCSDaily =-1 static private
Definition at line 76 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), listCycleDvAliasVariables(), and writeDailyCycleDvarAlias().
gidCSMonthly
int wrimsv2.hdf5.HDF5Writer.gidCSMonthly =-1 static private
Definition at line 74 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), listCycleDvAliasVariables(), and writeMonthlyCycleDvarAlias().
gidDaily
int wrimsv2.hdf5.HDF5Writer.gidDaily =-1 static private
Definition at line 58 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), listDailyTimestepDvarAlias(), and writeDailyTimestepDvarAlias().
gidData
int wrimsv2.hdf5.HDF5Writer.gidData =-1 static private
Definition at line 54 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidDC
int wrimsv2.hdf5.HDF5Writer.gidDC =-1 static private
Definition at line 62 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidDCDaily
int wrimsv2.hdf5.HDF5Writer.gidDCDaily =-1 static private
Definition at line 72 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), writeDailyCycleDynamicSv(), and writeDailyCycleSv().
gidDCMonthly
int wrimsv2.hdf5.HDF5Writer.gidDCMonthly =-1 static private
Definition at line 70 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), writeMonthlyCycleDynamicSv(), and writeMonthlyCycleSv().
gidInfo
int wrimsv2.hdf5.HDF5Writer.gidInfo =-1 static private
Definition at line 52 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), createDvarAliasLookup(), listDailyTimestepDvarAlias(), and listMonthlyTimestepDvarAlias().
gidIOData
int wrimsv2.hdf5.HDF5Writer.gidIOData =-1 static private
Definition at line 50 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidMonthly
int wrimsv2.hdf5.HDF5Writer.gidMonthly =-1 static private
Definition at line 56 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), listMonthlyTimestepDvarAlias(), writeMonthlyTimestepDvarAlias(), and writeMonthlyTimestepDvarAlias_deprecated().
gidPartA
int wrimsv2.hdf5.HDF5Writer.gidPartA =-1 static private
Definition at line 46 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidPartF
int wrimsv2.hdf5.HDF5Writer.gidPartF =-1 static private
Definition at line 48 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidSC
int wrimsv2.hdf5.HDF5Writer.gidSC =-1 static private
Definition at line 60 of file HDF5Writer.java.
Referenced by closeDataStructure(), and createDataStructure().
gidSCDaily
int wrimsv2.hdf5.HDF5Writer.gidSCDaily =-1 static private
Definition at line 68 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), listCycleStaticSv(), skipDailyCycle(), skipDailyCycleStaticSv(), writeDailyCycleStaticSv(), and writeDailyCycleSv().
gidSCMonthly
int wrimsv2.hdf5.HDF5Writer.gidSCMonthly =-1 static private
Definition at line 66 of file HDF5Writer.java.
Referenced by closeDataStructure(), createDataStructure(), listCycleStaticSv(), skipMonthlyCycle(), skipMonthlyCycleStaticSv(), writeMonthlyCycleStaticSv(), and writeMonthlyCycleSv().
gInfo
String wrimsv2.hdf5.HDF5Writer.gInfo ="Info" static private
Definition at line 51 of file HDF5Writer.java.
Referenced by createDataStructure().
gIOData
String wrimsv2.hdf5.HDF5Writer.gIOData ="IO Data" static private
Definition at line 49 of file HDF5Writer.java.
Referenced by createDataStructure().
gMonthly
String wrimsv2.hdf5.HDF5Writer.gMonthly ="Monthly" static private
Definition at line 55 of file HDF5Writer.java.
Referenced by createDataStructure().
gPartA
String wrimsv2.hdf5.HDF5Writer.gPartA =ControlData.partA static private
Definition at line 45 of file HDF5Writer.java.
Referenced by createDataStructure().
gPartF
String wrimsv2.hdf5.HDF5Writer.gPartF =ControlData.svDvPartF static private
Definition at line 47 of file HDF5Writer.java.
Referenced by createDataStructure().
gSC
String wrimsv2.hdf5.HDF5Writer.gSC ="Static Cycle SV" static private
Definition at line 59 of file HDF5Writer.java.
Referenced by createDataStructure().
gSCDaily
String wrimsv2.hdf5.HDF5Writer.gSCDaily ="Daily" static private
Definition at line 67 of file HDF5Writer.java.
Referenced by createDataStructure().
gSCMonthly
String wrimsv2.hdf5.HDF5Writer.gSCMonthly ="Monthly" static private
Definition at line 65 of file HDF5Writer.java.
Referenced by createDataStructure().
h5FileName
String wrimsv2.hdf5.HDF5Writer.h5FileName ="" static private
Definition at line 43 of file HDF5Writer.java.
Referenced by createDataStructure().
hasDvarAliasLookup
boolean wrimsv2.hdf5.HDF5Writer.hasDvarAliasLookup =false static private
Definition at line 31 of file HDF5Writer.java.
monthlyCycleData
double [][] wrimsv2.hdf5.HDF5Writer.monthlyCycleData static private
Definition at line 79 of file HDF5Writer.java.
Referenced by differMonthlyDailyCycle(), and writeMonthlyCycleDvarAlias().
monthlyCycleVarNames
String [] wrimsv2.hdf5.HDF5Writer.monthlyCycleVarNames static private
Definition at line 77 of file HDF5Writer.java.
Referenced by differMonthlyDailyCycle(), listCycleDvAliasVariables(), and writeMonthlyCycleDvarAlias().
monthlyDim
int wrimsv2.hdf5.HDF5Writer.monthlyDim =0 static private
Definition at line 81 of file HDF5Writer.java.
Referenced by differMonthlyDailyCycle(), and writeMonthlyCycleDvarAlias().
monthlyDvarAliasKindMap
Map<String, String> wrimsv2.hdf5.HDF5Writer.monthlyDvarAliasKindMap = new HashMap<String, String>() static private
Definition at line 41 of file HDF5Writer.java.
Referenced by createDvarAliasLookup(), and listMonthlyTimestepDvarAlias().
monthlyDvarAliasList
ArrayList<String> wrimsv2.hdf5.HDF5Writer.monthlyDvarAliasList = new ArrayList<String>() static private
Definition at line 37 of file HDF5Writer.java.
Referenced by createDvarAliasLookup(), listMonthlyTimestepDvarAlias(), writeMonthlyTimestepDvarAlias(), and writeMonthlyTimestepDvarAlias_deprecated().
monthlyDvarAliasMap
Map<String, String> wrimsv2.hdf5.HDF5Writer.monthlyDvarAliasMap = new HashMap<String, String>() static private
Definition at line 39 of file HDF5Writer.java.
Referenced by createDvarAliasLookup(), and listMonthlyTimestepDvarAlias().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/hdf5/HDF5Writer.java