Wrims-engine: wrimsv2.evaluator.TableOperation Class Reference
wrimsv2.evaluator.TableOperation Class Reference
Static Public Member Functions
static IntDouble calculateValue (Number given, ArrayList< Number > gVList, Map< Number, Number > gVMap, String use, String table, String givenError)
static IntDouble findData (String table, String select, HashMap< String, Number > given, String use)
static IntDouble findData (String table, String select, HashMap< String, Number > where, HashMap< String, Number > given, String use)
static IntDouble generateIntDouble (String valueString)
static boolean isFieldNameRight (String fieldName)
static String removeComment (String text)
static String removeLeadingTailingSpace (String text)
static boolean retrieveLookUpData (String name)
static ArrayList< Number > sortNumberArray (ArrayList< Number > al, String givenError, String table)
Detailed Description
Definition at line 24 of file TableOperation.java.
Member Function Documentation
calculateValue()
IntDouble wrimsv2.evaluator.TableOperation.calculateValue (Number given, ArrayList< Number > gVList, Map< Number, Number > gVMap, String use, String table, String givenError) static
Definition at line 338 of file TableOperation.java.
References wrimsv2.components.Error.addEvaluationError(), and sortNumberArray().
Referenced by findData(), and findData().
findData() [1/2]
IntDouble wrimsv2.evaluator.TableOperation.findData (String table, String select, HashMap< String, Number > given, String use) static
Definition at line 276 of file TableOperation.java.
References wrimsv2.components.Error.addEvaluationError(), calculateValue(), wrimsv2.evaluator.LookUpTable.getData(), wrimsv2.evaluator.LookUpTable.getField(), retrieveLookUpData(), and wrimsv2.evaluator.TableSeries.tableSeries.
findData() [2/2]
IntDouble wrimsv2.evaluator.TableOperation.findData (String table, String select, HashMap< String, Number > where, HashMap< String, Number > given, String use) static
Definition at line 150 of file TableOperation.java.
References wrimsv2.components.Error.addEvaluationError(), calculateValue(), generateIntDouble(), wrimsv2.evaluator.LookUpTable.getData(), wrimsv2.evaluator.LookUpTable.getField(), retrieveLookUpData(), and wrimsv2.evaluator.TableSeries.tableSeries.
Referenced by wrimsv2.evaluator.Evaluation.tableSQL(), and wrimsv2.evaluator.ValueEvaluation.tableSQL().
generateIntDouble()
IntDouble wrimsv2.evaluator.TableOperation.generateIntDouble (String valueString) static
Definition at line 420 of file TableOperation.java.
Referenced by findData().
isFieldNameRight()
boolean wrimsv2.evaluator.TableOperation.isFieldNameRight (String fieldName) static
Definition at line 141 of file TableOperation.java.
Referenced by retrieveLookUpData().
removeComment()
String wrimsv2.evaluator.TableOperation.removeComment (String text) static
Definition at line 130 of file TableOperation.java.
Referenced by retrieveLookUpData().
removeLeadingTailingSpace()
String wrimsv2.evaluator.TableOperation.removeLeadingTailingSpace (String text) static
Definition at line 135 of file TableOperation.java.
Referenced by retrieveLookUpData().
retrieveLookUpData()
boolean wrimsv2.evaluator.TableOperation.retrieveLookUpData (String name) static
Definition at line 25 of file TableOperation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.LookUpTable.getData(), wrimsv2.evaluator.LookUpTable.getField(), isFieldNameRight(), wrimsv2.components.FilePaths.lookupSubDirectory, wrimsv2.components.FilePaths.mainDirectory, removeComment(), removeLeadingTailingSpace(), and wrimsv2.evaluator.TableSeries.tableSeries.
Referenced by findData(), and findData().
sortNumberArray()
ArrayList< Number > wrimsv2.evaluator.TableOperation.sortNumberArray (ArrayList< Number > al, String givenError, String table) static
Definition at line 425 of file TableOperation.java.
References wrimsv2.components.Error.addEvaluationError().
Referenced by calculateValue().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/TableOperation.java