Wrims-engine: wrimsv2.tools.InfeasibilityAnalysis Class Reference
wrimsv2.tools.InfeasibilityAnalysis Class Reference
Static Public Member Functions
static void convertToLowerCase ()
static boolean isStudyInclFile (String fp, ModelDataSet mds)
static LinkedHashSet< String > procFolderToFiles (String absPath, ModelDataSet mds)
static void procIfsFile ()
static void procIfsSelFiles (LinkedHashSet< String > fpSet)
static String procRelativePath (String path, String folderPath)
Static Public Attributes
static LinkedHashSet< String > constraintSet = new LinkedHashSet<String>()
static LinkedHashSet< String > constraintSetMixedCases = new LinkedHashSet<String>()
Static Private Attributes
static final String cPref ="c: "
static final String fPref ="f: "
static final String ifsExt =".ifs"
static final String wExt =".wresl"
Detailed Description
Definition at line 28 of file InfeasibilityAnalysis.java.
Member Function Documentation
convertToLowerCase()
void wrimsv2.tools.InfeasibilityAnalysis.convertToLowerCase () static
Definition at line 156 of file InfeasibilityAnalysis.java.
References constraintSet, and constraintSetMixedCases.
Referenced by procIfsFile().
isStudyInclFile()
boolean wrimsv2.tools.InfeasibilityAnalysis.isStudyInclFile (String fp, ModelDataSet mds) static
Definition at line 144 of file InfeasibilityAnalysis.java.
References wrimsv2.commondata.wresldata.ModelDataSet.incFileList.
Referenced by procFolderToFiles(), and procIfsFile().
procFolderToFiles()
LinkedHashSet< String > wrimsv2.tools.InfeasibilityAnalysis.procFolderToFiles (String absPath, ModelDataSet mds) static
Definition at line 124 of file InfeasibilityAnalysis.java.
References isStudyInclFile(), procFolderToFiles(), and wExt.
Referenced by procFolderToFiles(), and procIfsFile().
procIfsFile()
void wrimsv2.tools.InfeasibilityAnalysis.procIfsFile () static
Definition at line 36 of file InfeasibilityAnalysis.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFilePath, constraintSetMixedCases, convertToLowerCase(), cPref, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currStudyDataSet, fPref, wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), ifsExt, isStudyInclFile(), procFolderToFiles(), procIfsSelFiles(), procRelativePath(), and wExt.
Referenced by wrimsv2.solver.CbcSolver.iis().
procIfsSelFiles()
void wrimsv2.tools.InfeasibilityAnalysis.procIfsSelFiles (LinkedHashSet< String > fpSet) static
Definition at line 90 of file InfeasibilityAnalysis.java.
References constraintSetMixedCases, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslparser.elements.FileParser.parseOneFileForDebug(), wrimsv2.wreslplus.elements.ParserUtils.parseWreslFile(), wrimsv2.wreslplus.elements.ParserUtils.parseWreslMain(), and wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus.
Referenced by procIfsFile().
procRelativePath()
String wrimsv2.tools.InfeasibilityAnalysis.procRelativePath (String path, String folderPath) static
Definition at line 119 of file InfeasibilityAnalysis.java.
Referenced by procIfsFile().
Member Data Documentation
constraintSet
LinkedHashSet<String> wrimsv2.tools.InfeasibilityAnalysis.constraintSet = new LinkedHashSet<String>() static
Definition at line 34 of file InfeasibilityAnalysis.java.
Referenced by convertToLowerCase(), and wrimsv2.solver.CbcSolver.iis().
constraintSetMixedCases
LinkedHashSet<String> wrimsv2.tools.InfeasibilityAnalysis.constraintSetMixedCases = new LinkedHashSet<String>() static
Definition at line 33 of file InfeasibilityAnalysis.java.
Referenced by convertToLowerCase(), procIfsFile(), and procIfsSelFiles().
cPref
final String wrimsv2.tools.InfeasibilityAnalysis.cPref ="c: " static private
Definition at line 31 of file InfeasibilityAnalysis.java.
Referenced by procIfsFile().
fPref
final String wrimsv2.tools.InfeasibilityAnalysis.fPref ="f: " static private
Definition at line 32 of file InfeasibilityAnalysis.java.
Referenced by procIfsFile().
ifsExt
final String wrimsv2.tools.InfeasibilityAnalysis.ifsExt =".ifs" static private
Definition at line 29 of file InfeasibilityAnalysis.java.
Referenced by procIfsFile().
wExt
final String wrimsv2.tools.InfeasibilityAnalysis.wExt =".wresl" static private
Definition at line 30 of file InfeasibilityAnalysis.java.
Referenced by procFolderToFiles(), and procIfsFile().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/InfeasibilityAnalysis.java