Wrims-engine: wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup Class Reference
wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup Class Reference
Static Public Member Functions
static ArrayList< Boolean > evaluateConditions (ArrayList< String > conditionList)
static void process (ModelTemp m)
static void process (StudyTemp st)
Private Member Functions
ProcIfIncItemGroup ()
Detailed Description
Definition at line 30 of file ProcIfIncItemGroup.java.
Constructor & Destructor Documentation
ProcIfIncItemGroup()
wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.ProcIfIncItemGroup () private
Definition at line 32 of file ProcIfIncItemGroup.java.
Member Function Documentation
evaluateConditions()
ArrayList< Boolean > wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.evaluateConditions (ArrayList< String > conditionList) static
Definition at line 237 of file ProcIfIncItemGroup.java.
References wrimsv2.components.Error.getTotalError(), and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.components.DebugInterface.getVariableIfInc(), and process().
process() [1/2]
void wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.process (ModelTemp m) static
Definition at line 47 of file ProcIfIncItemGroup.java.
References wrimsv2.wreslplus.elements.ModelTemp.asList, wrimsv2.wreslplus.elements.ModelTemp.asMap, wrimsv2.commondata.wresldata.Param.asType, wrimsv2.wreslplus.elements.IfIncItemGroup.conditionList, wrimsv2.wreslplus.elements.IfIncItemGroup.conditionValueList, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.wreslplus.elements.ModelTemp.dvMap, wrimsv2.commondata.wresldata.Param.dvType, evaluateConditions(), wrimsv2.wreslplus.elements.IfIncItemGroup.fromWresl, wrimsv2.commondata.wresldata.Param.gl1Type, wrimsv2.wreslplus.elements.ModelTemp.gl2List, wrimsv2.commondata.wresldata.Param.gl2Type, wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.wreslplus.elements.IfIncItemGroup.id, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupIDList, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupMap, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_alias_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_dvar_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_files_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalComplex_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalSimple_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_item_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_svar_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_timeseries_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_weightTable_map_list, wrimsv2.wreslplus.elements.ModelTemp.incFileIDList, wrimsv2.wreslplus.elements.ModelTemp.incFileMap, wrimsv2.commondata.wresldata.Param.incFileType, wrimsv2.wreslplus.elements.ModelTemp.itemList, wrimsv2.wreslplus.elements.ModelTemp.itemTypeList, wrimsv2.wreslplus.elements.ModelTemp.svList, wrimsv2.wreslplus.elements.ModelTemp.svMap, wrimsv2.commondata.wresldata.Param.svType, wrimsv2.wreslplus.elements.ModelTemp.tsList, wrimsv2.wreslplus.elements.ModelTemp.tsMap, wrimsv2.commondata.wresldata.Param.tsType, and wrimsv2.wreslplus.elements.ModelTemp.wTableObjList.
process() [2/2]
void wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.process (StudyTemp st) static
Definition at line 35 of file ProcIfIncItemGroup.java.
References wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, and process().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile(), and process().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ProcIfIncItemGroup.java