Wrims-engine: wrimsv2.evaluator.LookUpTable Class Reference
wrimsv2.evaluator.LookUpTable Class Reference
Public Member Functions
ArrayList< Number[]> getData ()
HashMap< String, Integer > getField ()
String getName ()
void setField (HashMap< String, Integer > field)
void setName (String name)
Private Attributes
ArrayList< Number[]> data =new ArrayList<Number[]>()
HashMap< String, Integer > field = new HashMap<String, Integer>()
String name =null
Detailed Description
Definition at line 6 of file LookUpTable.java.
Member Function Documentation
getData()
ArrayList< Number[]> wrimsv2.evaluator.LookUpTable.getData ()
Definition at line 27 of file LookUpTable.java.
References data.
Referenced by wrimsv2.evaluator.TableOperation.findData(), wrimsv2.evaluator.TableOperation.findData(), and wrimsv2.evaluator.TableOperation.retrieveLookUpData().
getField()
HashMap< String, Integer > wrimsv2.evaluator.LookUpTable.getField ()
Definition at line 19 of file LookUpTable.java.
References field.
Referenced by wrimsv2.evaluator.TableOperation.findData(), wrimsv2.evaluator.TableOperation.findData(), and wrimsv2.evaluator.TableOperation.retrieveLookUpData().
getName()
String wrimsv2.evaluator.LookUpTable.getName ()
Definition at line 11 of file LookUpTable.java.
References name.
setField()
void wrimsv2.evaluator.LookUpTable.setField (HashMap< String, Integer > field)
Definition at line 23 of file LookUpTable.java.
References field.
setName()
void wrimsv2.evaluator.LookUpTable.setName (String name)
Definition at line 15 of file LookUpTable.java.
References name.
Member Data Documentation
data
ArrayList<Number[]> wrimsv2.evaluator.LookUpTable.data =new ArrayList<Number[]>() private
Definition at line 9 of file LookUpTable.java.
Referenced by getData().
field
HashMap<String, Integer> wrimsv2.evaluator.LookUpTable.field = new HashMap<String, Integer>() private
Definition at line 8 of file LookUpTable.java.
Referenced by getField(), and setField().
name
String wrimsv2.evaluator.LookUpTable.name =null private
Definition at line 7 of file LookUpTable.java.
Referenced by getName(), and setName().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/LookUpTable.java