Wrims-engine: wrimsv2.wreslplus.elements.procedures.ToLowerCase Class Reference
wrimsv2.wreslplus.elements.procedures.ToLowerCase Class Reference
Static Public Member Functions
static AliasTemp alias (AliasTemp d)
static void convert (ModelTemp j)
static void convert (StudyTemp s)
static DvarTemp dvar (DvarTemp d)
static ExternalTemp external (ExternalTemp e)
static GoalTemp goal (GoalTemp g)
static GoalCase goalCase (GoalCase d)
static IfIncItemGroup ifIncFileGroup (IfIncItemGroup w)
static IncFileTemp incFile (IncFileTemp w)
static SequenceTemp sequence (SequenceTemp w)
static SvarTemp svar (SvarTemp s)
static TimeseriesTemp timeseries (TimeseriesTemp t)
static WeightTemp weight (WeightTemp w)
static WeightTable weightTable (WeightTable w)
Private Member Functions
ToLowerCase ()
Detailed Description
Definition at line 26 of file ToLowerCase.java.
Constructor & Destructor Documentation
ToLowerCase()
wrimsv2.wreslplus.elements.procedures.ToLowerCase.ToLowerCase () private
Definition at line 29 of file ToLowerCase.java.
Member Function Documentation
alias()
AliasTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.alias (AliasTemp d) static
Definition at line 363 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.AliasTemp.arraySize, wrimsv2.wreslplus.elements.AliasTemp.condition, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.AliasTemp.expression, wrimsv2.wreslplus.elements.AliasTemp.fromWresl, wrimsv2.wreslplus.elements.AliasTemp.id, wrimsv2.wreslplus.elements.AliasTemp.isMovedToDvar, wrimsv2.wreslplus.elements.AliasTemp.kind, wrimsv2.wreslplus.elements.AliasTemp.line, wrimsv2.wreslplus.elements.AliasTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.AliasTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.AliasTemp.noSolver, wrimsv2.wreslplus.elements.AliasTemp.timeArraySize, and wrimsv2.wreslplus.elements.AliasTemp.units.
Referenced by convert(), and ifIncFileGroup().
convert() [1/2]
void wrimsv2.wreslplus.elements.procedures.ToLowerCase.convert (ModelTemp j) static
Definition at line 89 of file ToLowerCase.java.
References alias(), wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.ModelTemp.asList, wrimsv2.wreslplus.elements.ModelTemp.asMap, dvar(), wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.wreslplus.elements.ModelTemp.dvList_fromAlias, wrimsv2.wreslplus.elements.ModelTemp.dvMap, wrimsv2.wreslplus.elements.ModelTemp.exList, wrimsv2.wreslplus.elements.ModelTemp.exMap, external(), wrimsv2.wreslplus.elements.ModelTemp.gl2List, wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.glList_fromAlias, wrimsv2.wreslplus.elements.ModelTemp.glMap, goal(), ifIncFileGroup(), wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupIDList, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupMap, incFile(), wrimsv2.wreslplus.elements.ModelTemp.incFileIDList, wrimsv2.wreslplus.elements.ModelTemp.incFileMap, wrimsv2.wreslplus.elements.ModelTemp.incModelList, wrimsv2.wreslplus.elements.ModelTemp.itemList, svar(), wrimsv2.wreslplus.elements.ModelTemp.svList, wrimsv2.wreslplus.elements.ModelTemp.svMap, timeseries(), wrimsv2.wreslplus.elements.ModelTemp.tsList, wrimsv2.wreslplus.elements.ModelTemp.tsMap, weightTable(), and wrimsv2.wreslplus.elements.ModelTemp.wTableObjList.
convert() [2/2]
void wrimsv2.wreslplus.elements.procedures.ToLowerCase.convert (StudyTemp s) static
Definition at line 33 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), convert(), wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.parameterConstList, wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.wreslplus.elements.StudyTemp.parameterMap, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, sequence(), and svar().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), convert(), and wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile().
dvar()
DvarTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.dvar (DvarTemp d) static
Definition at line 230 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.DvarTemp.arraySize, wrimsv2.wreslplus.elements.DvarTemp.condition, wrimsv2.wreslplus.elements.DvarTemp.fromWresl, wrimsv2.wreslplus.elements.DvarTemp.id, wrimsv2.wreslplus.elements.DvarTemp.isFromAlias, wrimsv2.wreslplus.elements.DvarTemp.isInteger, wrimsv2.wreslplus.elements.DvarTemp.kind, wrimsv2.wreslplus.elements.DvarTemp.line, wrimsv2.wreslplus.elements.DvarTemp.lowerBound, wrimsv2.wreslplus.elements.DvarTemp.timeArraySize, wrimsv2.wreslplus.elements.DvarTemp.units, and wrimsv2.wreslplus.elements.DvarTemp.upperBound.
Referenced by convert(), and ifIncFileGroup().
external()
ExternalTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.external (ExternalTemp e) static
Definition at line 297 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.ExternalTemp.fileName, wrimsv2.wreslplus.elements.ExternalTemp.fromWresl, wrimsv2.wreslplus.elements.ExternalTemp.id, and wrimsv2.wreslplus.elements.ExternalTemp.line.
Referenced by convert().
goal()
GoalTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.goal (GoalTemp g) static
Definition at line 311 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.Tools.add_space_between_logical(), wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.GoalTemp.arraySize, wrimsv2.wreslplus.elements.GoalTemp.caseCondition, wrimsv2.wreslplus.elements.GoalTemp.caseExpression, wrimsv2.wreslplus.elements.GoalTemp.caseMap, wrimsv2.wreslplus.elements.GoalTemp.caseName, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.GoalTemp.fromWresl, goalCase(), wrimsv2.wreslplus.elements.GoalTemp.hasCase, wrimsv2.wreslplus.elements.GoalTemp.hasLhs, wrimsv2.wreslplus.elements.GoalTemp.id, wrimsv2.wreslplus.elements.GoalTemp.lhs, wrimsv2.wreslplus.elements.GoalTemp.line, wrimsv2.wreslplus.elements.GoalTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.GoalTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.Tools.replace_with_space(), and wrimsv2.wreslplus.elements.GoalTemp.timeArraySize.
Referenced by convert(), and ifIncFileGroup().
goalCase()
GoalCase wrimsv2.wreslplus.elements.procedures.ToLowerCase.goalCase (GoalCase d) static
Definition at line 389 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.GoalCase.condition, wrimsv2.wreslplus.elements.GoalCase.id, wrimsv2.wreslplus.elements.GoalCase.lhs_gt_rhs, wrimsv2.wreslplus.elements.GoalCase.lhs_lt_rhs, and wrimsv2.wreslplus.elements.GoalCase.rhs.
Referenced by goal().
ifIncFileGroup()
IfIncItemGroup wrimsv2.wreslplus.elements.procedures.ToLowerCase.ifIncFileGroup (IfIncItemGroup w) static
Definition at line 417 of file ToLowerCase.java.
References alias(), wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.Tools.allToLowerCase2(), wrimsv2.wreslplus.elements.IfIncItemGroup.conditionList, wrimsv2.wreslplus.elements.IfIncItemGroup.dependants, dvar(), wrimsv2.wreslplus.elements.IfIncItemGroup.fromWresl, goal(), wrimsv2.wreslplus.elements.IfIncItemGroup.id, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_alias_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_dvar_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_files_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalComplex_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalSimple_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_item_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_svar_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_timeseries_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_weightTable_map_list, incFile(), wrimsv2.wreslplus.elements.IfIncItemGroup.line, svar(), timeseries(), and weightTable().
Referenced by convert().
incFile()
IncFileTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.incFile (IncFileTemp w) static
Definition at line 404 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.IncFileTemp.id, and wrimsv2.wreslplus.elements.IncFileTemp.rawPath.
Referenced by convert(), and ifIncFileGroup().
sequence()
SequenceTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.sequence (SequenceTemp w) static
Definition at line 70 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.Tools.allToLowerCase_string_set(), wrimsv2.wreslplus.elements.SequenceTemp.condition, wrimsv2.wreslplus.elements.SequenceTemp.dependants, wrimsv2.wreslplus.elements.SequenceTemp.fromWresl, wrimsv2.wreslplus.elements.SequenceTemp.id, wrimsv2.wreslplus.elements.SequenceTemp.line, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.SequenceTemp.neededCycleVarMap, wrimsv2.wreslplus.elements.SequenceTemp.order, and wrimsv2.wreslplus.elements.SequenceTemp.timeStep.
Referenced by convert().
svar()
SvarTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.svar (SvarTemp s) static
Definition at line 178 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.Tools.add_space_between_logical(), wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.SvarTemp.arraySize, wrimsv2.wreslplus.elements.SvarTemp.caseCondition, wrimsv2.wreslplus.elements.SvarTemp.caseExpression, wrimsv2.wreslplus.elements.SvarTemp.caseName, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.dependants_notAllowed, wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.SvarTemp.id, wrimsv2.wreslplus.elements.SvarTemp.kind, wrimsv2.wreslplus.elements.SvarTemp.line, wrimsv2.wreslplus.elements.SvarTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.SvarTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.Tools.replace_with_space(), wrimsv2.wreslplus.elements.SvarTemp.timeArraySize, and wrimsv2.wreslplus.elements.SvarTemp.units.
Referenced by convert(), convert(), and ifIncFileGroup().
timeseries()
TimeseriesTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.timeseries (TimeseriesTemp t) static
Definition at line 212 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.TimeseriesTemp.convertToUnits, wrimsv2.wreslplus.elements.TimeseriesTemp.dssBPart, wrimsv2.wreslplus.elements.TimeseriesTemp.fromWresl, wrimsv2.wreslplus.elements.TimeseriesTemp.id, wrimsv2.wreslplus.elements.TimeseriesTemp.kind, wrimsv2.wreslplus.elements.TimeseriesTemp.line, and wrimsv2.wreslplus.elements.TimeseriesTemp.units.
Referenced by convert(), and ifIncFileGroup().
weight()
WeightTemp wrimsv2.wreslplus.elements.procedures.ToLowerCase.weight (WeightTemp w) static
Definition at line 255 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.WeightTemp.condition, wrimsv2.wreslplus.elements.WeightTemp.fromWresl, wrimsv2.wreslplus.elements.WeightTemp.id, wrimsv2.wreslplus.elements.WeightTemp.line, wrimsv2.wreslplus.elements.WeightTemp.timeArraySize, and wrimsv2.wreslplus.elements.WeightTemp.weight.
weightTable()
WeightTable wrimsv2.wreslplus.elements.procedures.ToLowerCase.weightTable (WeightTable w) static
Definition at line 271 of file ToLowerCase.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.Tools.allToLowerCase_string(), wrimsv2.wreslplus.elements.Tools.allToLowerCase_weightSubgroup(), wrimsv2.wreslplus.elements.Tools.allToLowerCaseString(), wrimsv2.wreslplus.elements.WeightTable.commonWeight, wrimsv2.wreslplus.elements.WeightTable.condition, wrimsv2.wreslplus.elements.WeightTable.dependants, wrimsv2.wreslplus.elements.WeightTable.deviationPenalty, wrimsv2.wreslplus.elements.WeightTable.deviationTolerance, wrimsv2.wreslplus.elements.WeightTable.fromWresl, wrimsv2.wreslplus.elements.WeightTable.id_lowcase, wrimsv2.wreslplus.elements.WeightTable.id_raw, wrimsv2.wreslplus.elements.WeightTable.isWeightGroup, wrimsv2.wreslplus.elements.WeightTable.line, wrimsv2.wreslplus.elements.WeightTable.subgroupMap, wrimsv2.wreslplus.elements.WeightTable.varLineMap, wrimsv2.wreslplus.elements.WeightTable.varList, wrimsv2.wreslplus.elements.WeightTable.varTimeArraySizeMap, and wrimsv2.wreslplus.elements.WeightTable.varWeightMap.
Referenced by convert(), and ifIncFileGroup().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ToLowerCase.java