Wrims-engine: wrimsv2.tools.RCCComparison Class Reference
wrimsv2.tools.RCCComparison Class Reference
Public Member Functions
RCCComparison ()
void compareConstraint (String strLine) throws IOException
void compareDvar (String strLine) throws IOException
void compareObject (String strLine) throws IOException
Private Attributes
Map< String, Alias > aliasMap
int cycle =1
String cycleName
ArrayList< Object > dvarArrayList =new ArrayList<Object> ()
Map< String, Dvar > dvarMap
String gName
ArrayList< Object > gNameArrayList =new ArrayList<Object> ()
BufferedWriter out
BufferedWriter out1
BufferedWriter out2
Map< String, WeightElement > weightMap
ArrayList< Object > wNameArrayList =new ArrayList<Object> ()
Detailed Description
Definition at line 26 of file RCCComparison.java.
Constructor & Destructor Documentation
RCCComparison()
wrimsv2.tools.RCCComparison.RCCComparison ()
Definition at line 40 of file RCCComparison.java.
References aliasMap, compareConstraint(), compareDvar(), compareObject(), wrimsv2.components.ControlData.currAliasMap, cycle, cycleName, dvarArrayList, dvarMap, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), gName, gNameArrayList, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, wrimsv2.components.FilePaths.mainDirectory, out, out1, out2, wrimsv2.commondata.wresldata.Dvar.upperBoundValue, weightMap, and wNameArrayList.
Member Function Documentation
compareConstraint()
void wrimsv2.tools.RCCComparison.compareConstraint (String strLine) throws IOException
Definition at line 194 of file RCCComparison.java.
References wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), gName, gNameArrayList, and out.
Referenced by RCCComparison().
compareDvar()
void wrimsv2.tools.RCCComparison.compareDvar (String strLine) throws IOException
Definition at line 148 of file RCCComparison.java.
References aliasMap, dvarArrayList, dvarMap, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, out2, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
Referenced by RCCComparison().
compareObject()
void wrimsv2.tools.RCCComparison.compareObject (String strLine) throws IOException
Definition at line 172 of file RCCComparison.java.
References out1, weightMap, and wNameArrayList.
Referenced by RCCComparison().
Member Data Documentation
aliasMap
Map<String, Alias> wrimsv2.tools.RCCComparison.aliasMap private
Definition at line 38 of file RCCComparison.java.
Referenced by RCCComparison(), and compareDvar().
cycle
int wrimsv2.tools.RCCComparison.cycle =1 private
Definition at line 27 of file RCCComparison.java.
Referenced by RCCComparison().
cycleName
String wrimsv2.tools.RCCComparison.cycleName private
Definition at line 28 of file RCCComparison.java.
Referenced by RCCComparison().
dvarArrayList
ArrayList<Object> wrimsv2.tools.RCCComparison.dvarArrayList =new ArrayList<Object> () private
Definition at line 35 of file RCCComparison.java.
Referenced by RCCComparison(), and compareDvar().
dvarMap
Map<String, Dvar> wrimsv2.tools.RCCComparison.dvarMap private
Definition at line 37 of file RCCComparison.java.
Referenced by RCCComparison(), and compareDvar().
gName
String wrimsv2.tools.RCCComparison.gName private
Definition at line 32 of file RCCComparison.java.
Referenced by RCCComparison(), and compareConstraint().
gNameArrayList
ArrayList<Object> wrimsv2.tools.RCCComparison.gNameArrayList =new ArrayList<Object> () private
Definition at line 33 of file RCCComparison.java.
Referenced by RCCComparison(), and compareConstraint().
out
BufferedWriter wrimsv2.tools.RCCComparison.out private
Definition at line 29 of file RCCComparison.java.
Referenced by RCCComparison(), and compareConstraint().
out1
BufferedWriter wrimsv2.tools.RCCComparison.out1 private
Definition at line 30 of file RCCComparison.java.
Referenced by RCCComparison(), and compareObject().
out2
BufferedWriter wrimsv2.tools.RCCComparison.out2 private
Definition at line 31 of file RCCComparison.java.
Referenced by RCCComparison(), and compareDvar().
weightMap
Map<String, WeightElement> wrimsv2.tools.RCCComparison.weightMap private
Definition at line 36 of file RCCComparison.java.
Referenced by RCCComparison(), and compareObject().
wNameArrayList
ArrayList<Object> wrimsv2.tools.RCCComparison.wNameArrayList =new ArrayList<Object> () private
Definition at line 34 of file RCCComparison.java.
Referenced by RCCComparison(), and compareObject().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/RCCComparison.java