Wrims-engine: wrimsv2.commondata.wresldata.StudyDataSet Class Reference
wrimsv2.commondata.wresldata.StudyDataSet Class Reference
Public Member Functions
void clearVarCycleIndexByTimeStep ()
void clearVarTimeArrayCycleValueMap ()
String getAbsMainFilePath ()
ArrayList< String > getDvarTimeArrayCycleIndexList ()
ArrayList< String > getModelConditionList ()
ArrayList< ValueEvaluatorParser > getModelConditionParsers ()
Map< String, ModelDataSet > getModelDataSetMap ()
ArrayList< String > getModelList ()
ArrayList< String > getModelTimeStepList ()
ArrayList< String > getParameterList ()
LinkedHashMap< String, Svar > getParameterMap ()
Map< String, Timeseries > getTimeseriesMap ()
Map< String, ArrayList< String > > getTimeseriesTimeStepMap ()
ArrayList< String > getVarCycleIndexList ()
Map< String, Map< String, IntDouble > > getVarCycleIndexValueMap ()
Map< String, Map< String, IntDouble > > getVarCycleValueMap ()
Map< String, Map< String, IntDouble > > getVarTimeArrayCycleValueMap ()
void setAbsMainFilePath (String absMainFilePath)
void setModelConditionList (ArrayList< String > modelConditionList)
void setModelConditionParsers (ArrayList< ValueEvaluatorParser > modelConditionParsers)
void setModelDataSetMap (Map< String, ModelDataSet > modelDataSetMap)
void setModelList (ArrayList< String > modelList)
void setModelTimeStepList (ArrayList< String > modelTimeStepList)
void setParameterList (ArrayList< String > parameterList)
void setParameterMap (LinkedHashMap< String, Svar > parameterMap)
void setTimeseriesMap (Map< String, Timeseries > timeseriesMap)
void setTimeseriesTimeStepMap (Map< String, ArrayList< String > > timeseriesTimeStepMap)
void setVarCycleIndexList (ArrayList< String > varCycleIndexList)
void setVarCycleIndexValueMap (Map< String, Map< String, IntDouble > > varCycleIndexValueMap)
void setVarCycleValueMap (Map< String, Map< String, IntDouble > > varCycleValueMap)
Public Attributes
LinkedHashSet< String > allIntDv =new LinkedHashSet<String>()
LinkedHashMap< String, Svar > controlDataParameterMap = new LinkedHashMap<String, Svar>()
Map< Integer, LinkedHashSet< String > > cycIntDvMap =new HashMap<Integer,LinkedHashSet<String>>()
Private Attributes
String absMainFilePath =""
ArrayList< String > dvarTimeArrayCycleIndexList = new ArrayList<String>()
ArrayList< String > modelConditionList = new ArrayList<String>()
ArrayList< ValueEvaluatorParser > modelConditionParsers =new ArrayList<ValueEvaluatorParser>()
Map< String, ModelDataSet > modelDataSetMap = new HashMap<String, ModelDataSet>()
ArrayList< String > modelList = new ArrayList<String>()
ArrayList< String > modelTimeStepList = new ArrayList<String>()
ArrayList< String > parameterList = new ArrayList<String>()
LinkedHashMap< String, Svar > parameterMap = new LinkedHashMap<String, Svar>()
Map< String, Timeseries > timeseriesMap = new HashMap<String, Timeseries>()
Map< String, ArrayList< String > > timeseriesTimeStepMap = new HashMap<String, ArrayList<String>>()
ArrayList< String > varCycleIndexList = new ArrayList<String>()
Map< String, Map< String, IntDouble > > varCycleIndexValueMap = new HashMap<String, Map<String, IntDouble>>()
Map< String, Map< String, IntDouble > > varCycleValueMap = new HashMap<String, Map<String, IntDouble>>()
Map< String, Map< String, IntDouble > > varTimeArrayCycleValueMap = new HashMap<String, Map<String, IntDouble>>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 16 of file StudyDataSet.java.
Member Function Documentation
clearVarCycleIndexByTimeStep()
void wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep ()
Definition at line 153 of file StudyDataSet.java.
References dvarTimeArrayCycleIndexList, and varCycleIndexValueMap.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
clearVarTimeArrayCycleValueMap()
void wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap ()
Definition at line 149 of file StudyDataSet.java.
References varTimeArrayCycleValueMap.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
getAbsMainFilePath()
String wrimsv2.commondata.wresldata.StudyDataSet.getAbsMainFilePath ()
Definition at line 81 of file StudyDataSet.java.
References absMainFilePath.
getDvarTimeArrayCycleIndexList()
ArrayList< String > wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList ()
Definition at line 169 of file StudyDataSet.java.
References dvarTimeArrayCycleIndexList.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), and wrimsv2.commondata.wresldata.ModelDataSet.processDvar().
getModelConditionList()
ArrayList< String > wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionList ()
Definition at line 97 of file StudyDataSet.java.
References modelConditionList.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), and wrimsv2.wreslparser.elements.WriteCSV.study().
getModelConditionParsers()
ArrayList< ValueEvaluatorParser > wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers ()
Definition at line 113 of file StudyDataSet.java.
References modelConditionParsers.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
getModelDataSetMap()
Map< String, ModelDataSet > wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap ()
Definition at line 121 of file StudyDataSet.java.
References modelDataSetMap.
Referenced by wrimsv2.evaluator.AssignPastCycleVariable.AssignPastCycleVariable(), wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.PreEvaluatorTree.PreEvaluatorTree(), wrimsv2.components.PreRunModel.PreRunModel(), wrimsv2.debug.ReProcessExternal.ReProcessExternal(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycle_subfunction(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.hdf5.HDF5Writer.listCycleStaticSv(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.tools.InfeasibilityAnalysis.procIfsFile(), wrimsv2.evaluator.WeightEval.procWt(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.wreslparser.elements.WriteCSV.study(), and wrimsv2.wreslparser.elements.LogUtils.studySummary_details().
getModelList()
ArrayList< String > wrimsv2.commondata.wresldata.StudyDataSet.getModelList ()
Definition at line 89 of file StudyDataSet.java.
References modelList.
Referenced by wrimsv2.evaluator.AssignPastCycleVariable.AssignPastCycleVariable(), wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.PreEvaluatorTree.PreEvaluatorTree(), wrimsv2.components.PreRunModel.PreRunModel(), wrimsv2.debug.ReProcessExternal.ReProcessExternal(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycle_subfunction(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.Error.getCurrentDateCycleModel(), wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.components.PreRunModel.initialDvarAliasTS(), wrimsv2.hdf5.HDF5Writer.listCycleStaticSv(), wrimsv2.evaluator.Evaluation.pastCycleIndexNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexNoTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.evaluator.WeightEval.procWt(), wrimsv2.components.ControllerDebug.run(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobiTest(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), wrimsv2.wreslparser.elements.WriteCSV.study(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
getModelTimeStepList()
ArrayList< String > wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList ()
Definition at line 101 of file StudyDataSet.java.
References modelTimeStepList.
Referenced by wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.hdf5.HDF5Writer.listCycleStaticSv(), wrimsv2.components.VariableTimeStep.procCycleTimeStep(), wrimsv2.components.ControllerDebug.resetStartDate(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), and wrimsv2.components.VariableTimeStep.setCycleTimeStep().
getParameterList()
ArrayList< String > wrimsv2.commondata.wresldata.StudyDataSet.getParameterList ()
Definition at line 49 of file StudyDataSet.java.
References parameterList.
Referenced by wrimsv2.components.LoadParameter.process().
getParameterMap()
LinkedHashMap< String, Svar > wrimsv2.commondata.wresldata.StudyDataSet.getParameterMap ()
Definition at line 57 of file StudyDataSet.java.
References parameterMap.
Referenced by wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), and wrimsv2.components.LoadParameter.process().
getTimeseriesMap()
Map< String, Timeseries > wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesMap ()
Definition at line 65 of file StudyDataSet.java.
References timeseriesMap.
Referenced by wrimsv2.components.PreRunModel.PreRunModel(), wrimsv2.debug.ReLoadSVDss.ReLoadSVDss(), wrimsv2.hdf5.HDF5Reader.assignTimeseries(), wrimsv2.components.PreRunModel.readTimeseries(), wrimsv2.debug.ReLoadSVDss.readTimeseries(), wrimsv2.wreslparser.elements.WriteCSV.study(), and wrimsv2.wreslparser.elements.WriteCSV.timeseriesTimeStep().
getTimeseriesTimeStepMap()
Map< String, ArrayList< String > > wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesTimeStepMap ()
Definition at line 73 of file StudyDataSet.java.
References timeseriesTimeStepMap.
Referenced by wrimsv2.hdf5.HDF5Reader.assignTimeseries(), wrimsv2.components.PreRunModel.readTimeseries(), wrimsv2.debug.ReLoadSVDss.readTimeseries(), and wrimsv2.wreslparser.elements.WriteCSV.timeseriesTimeStep().
getVarCycleIndexList()
ArrayList< String > wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList ()
Definition at line 158 of file StudyDataSet.java.
References varCycleIndexList.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processDvar(), and wrimsv2.commondata.wresldata.ModelDataSet.processSvar().
getVarCycleIndexValueMap()
Map< String, Map< String, IntDouble > > wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap ()
Definition at line 141 of file StudyDataSet.java.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.evaluator.Evaluation.pastCycleIndexNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexNoTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), and wrimsv2.commondata.wresldata.ModelDataSet.processSvar().
getVarCycleValueMap()
Map< String, Map< String, IntDouble > > wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap ()
Definition at line 129 of file StudyDataSet.java.
Referenced by wrimsv2.evaluator.AssignPastCycleVariable.AssignPastCycleVariable(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycle_subfunction(), wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.components.DebugInterface.modifyCycle(), wrimsv2.evaluator.Evaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleNoTimeArray(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), and wrimsv2.commondata.wresldata.ModelDataSet.processSvar().
getVarTimeArrayCycleValueMap()
Map< String, Map< String, IntDouble > > wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap ()
Definition at line 137 of file StudyDataSet.java.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.components.DebugInterface.modifyCycle(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), and wrimsv2.commondata.wresldata.ModelDataSet.processSvar().
setAbsMainFilePath()
void wrimsv2.commondata.wresldata.StudyDataSet.setAbsMainFilePath (String absMainFilePath)
Definition at line 85 of file StudyDataSet.java.
References absMainFilePath.
setModelConditionList()
void wrimsv2.commondata.wresldata.StudyDataSet.setModelConditionList (ArrayList< String > modelConditionList)
Definition at line 105 of file StudyDataSet.java.
References modelConditionList.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setModelConditionParsers()
void wrimsv2.commondata.wresldata.StudyDataSet.setModelConditionParsers (ArrayList< ValueEvaluatorParser > modelConditionParsers)
Definition at line 117 of file StudyDataSet.java.
References modelConditionParsers.
Referenced by wrimsv2.evaluator.PreEvaluator.preEvaluateModelCondition().
setModelDataSetMap()
void wrimsv2.commondata.wresldata.StudyDataSet.setModelDataSetMap (Map< String, ModelDataSet > modelDataSetMap)
Definition at line 125 of file StudyDataSet.java.
References modelDataSetMap.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setModelList()
void wrimsv2.commondata.wresldata.StudyDataSet.setModelList (ArrayList< String > modelList)
Definition at line 93 of file StudyDataSet.java.
References modelList.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setModelTimeStepList()
void wrimsv2.commondata.wresldata.StudyDataSet.setModelTimeStepList (ArrayList< String > modelTimeStepList)
Definition at line 109 of file StudyDataSet.java.
References modelTimeStepList.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setParameterList()
void wrimsv2.commondata.wresldata.StudyDataSet.setParameterList (ArrayList< String > parameterList)
Definition at line 53 of file StudyDataSet.java.
References parameterList.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy().
setParameterMap()
void wrimsv2.commondata.wresldata.StudyDataSet.setParameterMap (LinkedHashMap< String, Svar > parameterMap)
Definition at line 61 of file StudyDataSet.java.
References parameterMap.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy().
setTimeseriesMap()
void wrimsv2.commondata.wresldata.StudyDataSet.setTimeseriesMap (Map< String, Timeseries > timeseriesMap)
Definition at line 69 of file StudyDataSet.java.
References timeseriesMap.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setTimeseriesTimeStepMap()
void wrimsv2.commondata.wresldata.StudyDataSet.setTimeseriesTimeStepMap (Map< String, ArrayList< String > > timeseriesTimeStepMap)
Definition at line 77 of file StudyDataSet.java.
References timeseriesTimeStepMap.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setVarCycleIndexList()
void wrimsv2.commondata.wresldata.StudyDataSet.setVarCycleIndexList (ArrayList< String > varCycleIndexList)
Definition at line 162 of file StudyDataSet.java.
References varCycleIndexList.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
setVarCycleIndexValueMap()
void wrimsv2.commondata.wresldata.StudyDataSet.setVarCycleIndexValueMap (Map< String, Map< String, IntDouble > > varCycleIndexValueMap)
Definition at line 145 of file StudyDataSet.java.
References varCycleIndexValueMap.
setVarCycleValueMap()
void wrimsv2.commondata.wresldata.StudyDataSet.setVarCycleValueMap (Map< String, Map< String, IntDouble > > varCycleValueMap)
Definition at line 133 of file StudyDataSet.java.
References varCycleValueMap.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy().
Member Data Documentation
absMainFilePath
String wrimsv2.commondata.wresldata.StudyDataSet.absMainFilePath ="" private
Definition at line 20 of file StudyDataSet.java.
Referenced by getAbsMainFilePath(), and setAbsMainFilePath().
allIntDv
LinkedHashSet<String> wrimsv2.commondata.wresldata.StudyDataSet.allIntDv =new LinkedHashSet<String>()
Definition at line 46 of file StudyDataSet.java.
Referenced by wrimsv2.tools.Warmstart.collectIntegerDV_1(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), wrimsv2.ilp.ILP.createNoteFile(), wrimsv2.solver.CbcSolver.init(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logIntCheck(), and wrimsv2.components.ControllerSG.runModelCbc().
controlDataParameterMap
LinkedHashMap<String, Svar> wrimsv2.commondata.wresldata.StudyDataSet.controlDataParameterMap = new LinkedHashMap<String, Svar>()
Definition at line 24 of file StudyDataSet.java.
Referenced by wrimsv2.components.LoadParameter.process().
cycIntDvMap
Map<Integer,LinkedHashSet<String> > wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap =new HashMap<Integer,LinkedHashSet<String>>()
Definition at line 47 of file StudyDataSet.java.
Referenced by wrimsv2.tools.Warmstart.collectIntegerDV_1(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), wrimsv2.tools.Warmstart.collectIntegerDV_3(), wrimsv2.ilp.ILP.createNoteFile(), wrimsv2.wreslplus.elements.Procedures.findWarmStart(), wrimsv2.wreslplus.elements.Procedures.findWarmStart(), wrimsv2.wreslplus.elements.Procedures.findWarmStop(), wrimsv2.wreslplus.elements.Procedures.findWarmStop(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.solver.CbcSolver.logIntVars(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.solver.CbcSolver.solve(), wrimsv2.solver.CbcSolver.solve_jCbc2021(), and wrimsv2.solver.CbcSolver.solve_jCbc2021a().
dvarTimeArrayCycleIndexList
ArrayList<String> wrimsv2.commondata.wresldata.StudyDataSet.dvarTimeArrayCycleIndexList = new ArrayList<String>() private
Definition at line 44 of file StudyDataSet.java.
Referenced by clearVarCycleIndexByTimeStep(), and getDvarTimeArrayCycleIndexList().
modelConditionList
ArrayList<String> wrimsv2.commondata.wresldata.StudyDataSet.modelConditionList = new ArrayList<String>() private
Definition at line 27 of file StudyDataSet.java.
Referenced by getModelConditionList(), and setModelConditionList().
modelConditionParsers
ArrayList<ValueEvaluatorParser> wrimsv2.commondata.wresldata.StudyDataSet.modelConditionParsers =new ArrayList<ValueEvaluatorParser>() private
Definition at line 29 of file StudyDataSet.java.
Referenced by getModelConditionParsers(), and setModelConditionParsers().
modelDataSetMap
Map<String, ModelDataSet> wrimsv2.commondata.wresldata.StudyDataSet.modelDataSetMap = new HashMap<String, ModelDataSet>() private
< modelName, modelDataSet >
Definition at line 36 of file StudyDataSet.java.
Referenced by getModelDataSetMap(), and setModelDataSetMap().
modelList
ArrayList<String> wrimsv2.commondata.wresldata.StudyDataSet.modelList = new ArrayList<String>() private
Definition at line 26 of file StudyDataSet.java.
Referenced by getModelList(), and setModelList().
modelTimeStepList
ArrayList<String> wrimsv2.commondata.wresldata.StudyDataSet.modelTimeStepList = new ArrayList<String>() private
Definition at line 28 of file StudyDataSet.java.
Referenced by getModelTimeStepList(), and setModelTimeStepList().
parameterList
ArrayList<String> wrimsv2.commondata.wresldata.StudyDataSet.parameterList = new ArrayList<String>() private
Definition at line 22 of file StudyDataSet.java.
Referenced by getParameterList(), and setParameterList().
parameterMap
LinkedHashMap<String, Svar> wrimsv2.commondata.wresldata.StudyDataSet.parameterMap = new LinkedHashMap<String, Svar>() private
Definition at line 23 of file StudyDataSet.java.
Referenced by getParameterMap(), and setParameterMap().
serialVersionUID
final long wrimsv2.commondata.wresldata.StudyDataSet.serialVersionUID = 1L static private
Definition at line 18 of file StudyDataSet.java.
timeseriesMap
Map<String, Timeseries> wrimsv2.commondata.wresldata.StudyDataSet.timeseriesMap = new HashMap<String, Timeseries>() private
< timeseries name, timeseries object >
Definition at line 32 of file StudyDataSet.java.
Referenced by getTimeseriesMap(), and setTimeseriesMap().
timeseriesTimeStepMap
Map<String, ArrayList<String> > wrimsv2.commondata.wresldata.StudyDataSet.timeseriesTimeStepMap = new HashMap<String, ArrayList<String>>() private
Definition at line 33 of file StudyDataSet.java.
Referenced by getTimeseriesTimeStepMap(), and setTimeseriesTimeStepMap().
varCycleIndexList
ArrayList<String> wrimsv2.commondata.wresldata.StudyDataSet.varCycleIndexList = new ArrayList<String>() private
Definition at line 43 of file StudyDataSet.java.
Referenced by getVarCycleIndexList(), and setVarCycleIndexList().
varCycleIndexValueMap
Map<String, Map<String, IntDouble> > wrimsv2.commondata.wresldata.StudyDataSet.varCycleIndexValueMap = new HashMap<String, Map<String, IntDouble>>() private
Definition at line 42 of file StudyDataSet.java.
Referenced by clearVarCycleIndexByTimeStep(), and setVarCycleIndexValueMap().
varCycleValueMap
Map<String, Map<String, IntDouble> > wrimsv2.commondata.wresldata.StudyDataSet.varCycleValueMap = new HashMap<String, Map<String, IntDouble>>() private
this map contains value of vars needed for WRESL syntax: varName[cycleName] < VarName, < CycleName, Value >>
Definition at line 40 of file StudyDataSet.java.
Referenced by setVarCycleValueMap().
varTimeArrayCycleValueMap
Map<String, Map<String, IntDouble> > wrimsv2.commondata.wresldata.StudyDataSet.varTimeArrayCycleValueMap = new HashMap<String, Map<String, IntDouble>>() private
Definition at line 41 of file StudyDataSet.java.
Referenced by clearVarTimeArrayCycleValueMap().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/commondata/wresldata/StudyDataSet.java