Wrims-engine: wrimsv2.wreslparser.elements.FileParser Class Reference
wrimsv2.wreslparser.elements.FileParser Class Reference
Public Member Functions
FileParser ()
Static Public Member Functions
static WreslTreeWalker parseFile (String inputFilePath) throws RecognitionException
static WreslTreeWalker parseFile (String inputFilePath, boolean showTree) throws RecognitionException
static WreslTreeWalker parseMainFile (String inputFilePath) throws RecognitionException
static WreslTreeWalker parseMainFile (String inputFilePath, boolean showTree) throws RecognitionException
static WreslTreeWalker parseOneFileForDebug (String inputFilePath) throws RecognitionException
static SimulationDataSet processFileIntoSimulationDataSet (String inputFilePath, String scope) throws RecognitionException, IOException
static Map< String, SimulationDataSet > processNestedFile (String inputFilePath) throws RecognitionException, IOException
static Map< String, SimulationDataSet > processNestedFileExceptFor (String inputFilePath, Set< String > existingSet) throws RecognitionException, IOException
static Map< String, SimulationDataSet > processNestedFileIntoSimulationDataSetMap (String inputFilePath, String scope) throws RecognitionException, IOException
Public Attributes
String expression
String kind
String scope
String units
Static Private Attributes
static CharStream stream
Detailed Description
Definition at line 26 of file FileParser.java.
Constructor & Destructor Documentation
FileParser()
wrimsv2.wreslparser.elements.FileParser.FileParser ()
Definition at line 35 of file FileParser.java.
References expression, kind, scope, wrimsv2.commondata.wresldata.Param.undefined, and units.
Member Function Documentation
parseFile() [1/2]
WreslTreeWalker wrimsv2.wreslparser.elements.FileParser.parseFile (String inputFilePath) throws RecognitionException static
Definition at line 44 of file FileParser.java.
References parseFile().
Referenced by parseFile(), processFileIntoSimulationDataSet(), processNestedFile(), and processNestedFileExceptFor().
parseFile() [2/2]
WreslTreeWalker wrimsv2.wreslparser.elements.FileParser.parseFile (String inputFilePath, boolean showTree) throws RecognitionException static
Definition at line 48 of file FileParser.java.
References wrimsv2.wreslparser.elements.LogUtils.closeLogFile(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.LogUtils.importantMsg(), and stream.
parseMainFile() [1/2]
WreslTreeWalker wrimsv2.wreslparser.elements.FileParser.parseMainFile (String inputFilePath) throws RecognitionException static
Definition at line 199 of file FileParser.java.
References parseMainFile().
Referenced by parseMainFile(), and wrimsv2.wreslparser.elements.StudyParser.processMainFileIntoStudyConfig().
parseMainFile() [2/2]
WreslTreeWalker wrimsv2.wreslparser.elements.FileParser.parseMainFile (String inputFilePath, boolean showTree) throws RecognitionException static
Definition at line 204 of file FileParser.java.
References wrimsv2.wreslparser.elements.LogUtils.closeLogFile(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.LogUtils.importantMsg(), and stream.
parseOneFileForDebug()
WreslTreeWalker wrimsv2.wreslparser.elements.FileParser.parseOneFileForDebug (String inputFilePath) throws RecognitionException static
Definition at line 260 of file FileParser.java.
References stream.
Referenced by wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFile(), and wrimsv2.tools.InfeasibilityAnalysis.procIfsSelFiles().
processFileIntoSimulationDataSet()
SimulationDataSet wrimsv2.wreslparser.elements.FileParser.processFileIntoSimulationDataSet (String inputFilePath, String scope) throws RecognitionException, IOException static
Definition at line 152 of file FileParser.java.
References wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), parseFile(), and scope.
Referenced by processNestedFileIntoSimulationDataSetMap().
processNestedFile()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.FileParser.processNestedFile (String inputFilePath) throws RecognitionException, IOException static
Definition at line 106 of file FileParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, parseFile(), and processNestedFile().
Referenced by processNestedFile(), and processNestedFileExceptFor().
processNestedFileExceptFor()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.FileParser.processNestedFileExceptFor (String inputFilePath, Set< String > existingSet) throws RecognitionException, IOException static
Definition at line 127 of file FileParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet, parseFile(), and processNestedFile().
Referenced by wrimsv2.wreslparser.elements.StudyParser.getNewDataSet().
processNestedFileIntoSimulationDataSetMap()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.FileParser.processNestedFileIntoSimulationDataSetMap (String inputFilePath, String scope) throws RecognitionException, IOException static
Definition at line 169 of file FileParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileMap, processFileIntoSimulationDataSet(), processNestedFileIntoSimulationDataSetMap(), and scope.
Referenced by processNestedFileIntoSimulationDataSetMap().
Member Data Documentation
expression
String wrimsv2.wreslparser.elements.FileParser.expression
Definition at line 32 of file FileParser.java.
Referenced by FileParser().
kind
String wrimsv2.wreslparser.elements.FileParser.kind
Definition at line 30 of file FileParser.java.
Referenced by FileParser().
scope
String wrimsv2.wreslparser.elements.FileParser.scope
Definition at line 29 of file FileParser.java.
Referenced by FileParser(), processFileIntoSimulationDataSet(), and processNestedFileIntoSimulationDataSetMap().
stream
CharStream wrimsv2.wreslparser.elements.FileParser.stream static private
Definition at line 28 of file FileParser.java.
Referenced by parseFile(), parseMainFile(), and parseOneFileForDebug().
units
String wrimsv2.wreslparser.elements.FileParser.units
Definition at line 31 of file FileParser.java.
Referenced by FileParser().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/FileParser.java