Wrims-engine: wrimsv2.solver.SetXALog Class Reference
wrimsv2.solver.SetXALog Class Reference
Static Public Member Functions
static void disableXALog ()
static void enableXALog ()
Static Package Attributes
static boolean isConfigRead =false
static String line ="set sortName YES MPSX Yes Set FreqLog :01"
Detailed Description
Definition at line 12 of file SetXALog.java.
Member Function Documentation
disableXALog()
void wrimsv2.solver.SetXALog.disableXALog () static
Definition at line 39 of file SetXALog.java.
References wrimsv2.components.ControlData.xasolver.
Referenced by wrimsv2.components.DebugInterface.setSolverOptions().
enableXALog()
void wrimsv2.solver.SetXALog.enableXALog () static
Definition at line 16 of file SetXALog.java.
References isConfigRead, line, wrimsv2.components.FilePaths.mainDirectory, and wrimsv2.components.ControlData.xasolver.
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), and wrimsv2.components.DebugInterface.setSolverOptions().
Member Data Documentation
isConfigRead
boolean wrimsv2.solver.SetXALog.isConfigRead =false static package
Definition at line 13 of file SetXALog.java.
Referenced by enableXALog().
line
String wrimsv2.solver.SetXALog.line ="set sortName YES MPSX Yes Set FreqLog :01" static package
Definition at line 14 of file SetXALog.java.
Referenced by enableXALog().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/SetXALog.java