Wrims-engine: wrimsv2.wreslplus.elements.ParserUtils Class Reference
wrimsv2.wreslplus.elements.ParserUtils Class Reference
Static Public Member Functions
static WreslPlusParser initParser (String inputFilePath) throws RecognitionException
static WreslPlusParser initParserSimple (String text) throws RecognitionException
static void parseAllIncFile (ArrayList< String > relativePathList, StudyTemp st)
static ModelTemp parseWreslFile (String inputFilePath)
static StudyTemp parseWreslMain (String inputFilePath)
static void setRunDir (String runDir)
Private Member Functions
ParserUtils ()
Detailed Description
Definition at line 23 of file ParserUtils.java.
Constructor & Destructor Documentation
ParserUtils()
wrimsv2.wreslplus.elements.ParserUtils.ParserUtils () private
Definition at line 27 of file ParserUtils.java.
Member Function Documentation
initParser()
WreslPlusParser wrimsv2.wreslplus.elements.ParserUtils.initParser (String inputFilePath) throws RecognitionException static
Definition at line 30 of file ParserUtils.java.
References wrimsv2.wreslparser.elements.LogUtils.closeLogFile(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslplus.elements.ResourceUtils.getRelativePath(), wrimsv2.wreslparser.elements.LogUtils.importantMsg(), wrimsv2.components.ControlData.isParseStudy, and wrimsv2.wreslplus.elements.GlobalData.runDir.
Referenced by parseWreslFile(), and parseWreslMain().
initParserSimple()
WreslPlusParser wrimsv2.wreslplus.elements.ParserUtils.initParserSimple (String text) throws RecognitionException static
Definition at line 175 of file ParserUtils.java.
Referenced by wrimsv2.config.ConfigUtils.checkExpression().
parseAllIncFile()
void wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile (ArrayList< String > relativePathList, StudyTemp st) static
Definition at line 118 of file ParserUtils.java.
References wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIfStatementHasUnknownDependants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarRedefined(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.convert(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.Tools.getCanonicalLowCasePath(), wrimsv2.wreslplus.elements.ModelTemp.id, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList, wrimsv2.wreslplus.elements.StudyTemp.parameterMap, parseAllIncFile(), parseWreslFile(), wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.process(), wrimsv2.wreslplus.elements.Procedures.processDependants(), wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath(), wrimsv2.wreslplus.elements.procedures.ProcVarIncFileList.replaceIncFile(), and wrimsv2.wreslplus.elements.StudyTemp.runDir.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and parseAllIncFile().
parseWreslFile()
ModelTemp wrimsv2.wreslplus.elements.ParserUtils.parseWreslFile (String inputFilePath) static
Definition at line 98 of file ParserUtils.java.
References initParser().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), parseAllIncFile(), and wrimsv2.tools.InfeasibilityAnalysis.procIfsSelFiles().
parseWreslMain()
StudyTemp wrimsv2.wreslplus.elements.ParserUtils.parseWreslMain (String inputFilePath) static
Definition at line 75 of file ParserUtils.java.
References initParser().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), and wrimsv2.tools.InfeasibilityAnalysis.procIfsSelFiles().
setRunDir()
void wrimsv2.wreslplus.elements.ParserUtils.setRunDir (String runDir) static
Definition at line 169 of file ParserUtils.java.
References wrimsv2.wreslplus.elements.Tools.getCanonicalLowCasePath(), and wrimsv2.wreslplus.elements.GlobalData.runDir.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), wrimsv2.components.ControllerBatch.parse(), and wrimsv2.components.ControllerDebug.parse().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/ParserUtils.java