Wrims-engine: wrimsv2.external.Functiongenfrcstrunofftables Class Reference
wrimsv2.external.Functiongenfrcstrunofftables Class Reference
Public Member Functions
Functiongenfrcstrunofftables ()
void execute (Stack stack)
void formTables (double frcst_fea, double frcst_sac, double frcst_amr)
void writeTable (String tableName, int startMonth, int endMonth, ArrayList< ArrayList< Double > > frcst_arr)
Package Attributes
ArrayList< Double > frcst_amr_list =new ArrayList<Double>()
ArrayList< Double > frcst_fea_list =new ArrayList<Double>()
ArrayList< Double > frcst_sac_list =new ArrayList<Double>()
Private Attributes
ArrayList< ArrayList< Double > > frcst_amr_arr =new ArrayList<ArrayList<Double>>()
ArrayList< ArrayList< Double > > frcst_fea_arr =new ArrayList<ArrayList<Double>>()
ArrayList< ArrayList< Double > > frcst_sac_arr =new ArrayList<ArrayList<Double>>()
ArrayList< Integer > wYears =new ArrayList<Integer>()
Additional Inherited Members
Static Public Attributes inherited from wrimsv2.external.ExternalFunction
static String externalDir =FilePaths.mainDirectory+File.separator+"external"+File.separator
Detailed Description
Definition at line 15 of file Functiongenfrcstrunofftables.java.
Constructor & Destructor Documentation
Functiongenfrcstrunofftables()
wrimsv2.external.Functiongenfrcstrunofftables.Functiongenfrcstrunofftables ()
Definition at line 25 of file Functiongenfrcstrunofftables.java.
Member Function Documentation
execute()
void wrimsv2.external.Functiongenfrcstrunofftables.execute (Stack stack)
Reimplemented from wrimsv2.external.ExternalFunction.
Definition at line 29 of file Functiongenfrcstrunofftables.java.
References formTables().
formTables()
void wrimsv2.external.Functiongenfrcstrunofftables.formTables (double frcst_fea, double frcst_sac, double frcst_amr)
Definition at line 47 of file Functiongenfrcstrunofftables.java.
References wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, frcst_amr_arr, frcst_amr_list, frcst_fea_arr, frcst_fea_list, frcst_sac_arr, frcst_sac_list, wrimsv2.evaluator.TimeOperation.waterYearValue(), writeTable(), and wYears.
Referenced by execute().
writeTable()
void wrimsv2.external.Functiongenfrcstrunofftables.writeTable (String tableName, int startMonth, int endMonth, ArrayList< ArrayList< Double > > frcst_arr)
Definition at line 83 of file Functiongenfrcstrunofftables.java.
References wrimsv2.components.FilePaths.genTableDir, wrimsv2.evaluator.TimeOperation.monthName(), and wYears.
Referenced by formTables().
Member Data Documentation
frcst_amr_arr
ArrayList<ArrayList<Double> > wrimsv2.external.Functiongenfrcstrunofftables.frcst_amr_arr =new ArrayList<ArrayList<Double>>() private
Definition at line 22 of file Functiongenfrcstrunofftables.java.
Referenced by formTables().
frcst_amr_list
ArrayList<Double> wrimsv2.external.Functiongenfrcstrunofftables.frcst_amr_list =new ArrayList<Double>() package
Definition at line 23 of file Functiongenfrcstrunofftables.java.
Referenced by formTables().
frcst_fea_arr
ArrayList<ArrayList<Double> > wrimsv2.external.Functiongenfrcstrunofftables.frcst_fea_arr =new ArrayList<ArrayList<Double>>() private
Definition at line 18 of file Functiongenfrcstrunofftables.java.
Referenced by formTables().
frcst_fea_list
ArrayList<Double> wrimsv2.external.Functiongenfrcstrunofftables.frcst_fea_list =new ArrayList<Double>() package
Definition at line 19 of file Functiongenfrcstrunofftables.java.
Referenced by formTables().
frcst_sac_arr
ArrayList<ArrayList<Double> > wrimsv2.external.Functiongenfrcstrunofftables.frcst_sac_arr =new ArrayList<ArrayList<Double>>() private
Definition at line 20 of file Functiongenfrcstrunofftables.java.
Referenced by formTables().
frcst_sac_list
ArrayList<Double> wrimsv2.external.Functiongenfrcstrunofftables.frcst_sac_list =new ArrayList<Double>() package
Definition at line 21 of file Functiongenfrcstrunofftables.java.
Referenced by formTables().
wYears
ArrayList<Integer> wrimsv2.external.Functiongenfrcstrunofftables.wYears =new ArrayList<Integer>() private
Definition at line 17 of file Functiongenfrcstrunofftables.java.
Referenced by formTables(), and writeTable().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/Functiongenfrcstrunofftables.java