Wrims-engine: wrimsv2.wreslplus.elements.Tools Class Reference
wrimsv2.wreslplus.elements.Tools Class Reference
Static Public Member Functions
static ArrayList< String > add_space_between_logical (ArrayList< String > s)
static String add_space_between_logical (String s)
static ArrayList< String > allToLowerCase (ArrayList< String > inArrayList)
static Set< String > allToLowerCase (Set< String > inSet)
static WeightSubgroup allToLowerCase (WeightSubgroup wsg)
static ArrayList< ArrayList< String > > allToLowerCase2 (ArrayList< ArrayList< String > > inArrayList)
static Map< String, String > allToLowerCase_string (Map< String, String > inMap)
static Map< String, HashSet< String > > allToLowerCase_string_set (Map< String, HashSet< String > > inMap)
static LinkedHashMap< String, WeightSubgroup > allToLowerCase_weightSubgroup (Map< String, WeightSubgroup > inMap)
static Map< String, Integer > allToLowerCaseString (Map< String, Integer > inMap)
static ArrayList< String > allToUpperCase (ArrayList< String > inArrayList)
static Set< String > convertStrToSet (String inStr)
static boolean deleteDir (String dirString)
static HashSet< String > findAllOffspring (String fileName, final Map< String, HashSet< String > > kidMap)
static void findFileHierarchy (ArrayList< HashSet< String > > hierarchySetList, Map< String, HashSet< String > > toBeSorted)
static String findGoalLocation (String goalName)
static String getCanonicalLowCasePath (String filePath)
static Map< String, Set< String > > getCycleVarMap (Set< String > setVarCycle)
static Map< String, Set< String > > getReverseMap (Map< String, Set< String > > t1Map)
static Map< String, ArrayList< String > > getReverseMap_arrayList (Map< String, ArrayList< String > > t1Map)
static ArrayList< String > getScopeList (ArrayList< String > fileList, ArrayList< String > localList)
static Map< String, String > getScopeMap (Set< String > fileSet, Set< String > localSet)
static Set< String > mapRemoveAll (Map< String, ?> map, ArrayList< String > list)
static Set< String > mapRemoveAll (Map< String, ?> map, Set< String > set)
static void mapRetainAll (Map< String, ?> map, ArrayList< String > retainKeys)
static String noZerofmt (double d)
static PrintWriter openFile (String dirPath, String fileName) throws IOException
static PrintWriter openFile (String dirPath, String fileName, boolean isAppend) throws IOException
static void quickLog (String fn, String x)
static void quickLog (String fn, String x, boolean isAppend)
static String readFileAsString (String file, String csName) throws IOException
static String readFileAsString (String filePath)
static String readFileLine (String filePath) throws IOException
static Map< String, String > readFilesFromDirAsMap (String dir) throws IOException
static String remove_nulls (String s)
static Set< String > removeDuplicates (ArrayList< String > list)
static ArrayList< String > replace_ignoreChar (ArrayList< String > s)
static String replace_ignoreChar (String s)
static String replace_regex (String s)
static ArrayList< String > replace_seperator (ArrayList< String > s)
static String replace_seperator (String s)
static ArrayList< String > replace_with_space (ArrayList< String > s)
static String replace_with_space (String s)
static Set< String > restoreOrder (ArrayList< String > toBeRestored, ArrayList< String > referenceOrder, Set< String > member)
static String strip (String s)
Detailed Description
Definition at line 35 of file Tools.java.
Member Function Documentation
add_space_between_logical() [1/2]
ArrayList< String > wrimsv2.wreslplus.elements.Tools.add_space_between_logical (ArrayList< String > s) static
Definition at line 245 of file Tools.java.
References add_space_between_logical().
Referenced by add_space_between_logical(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.goal(), and wrimsv2.wreslplus.elements.procedures.ToLowerCase.svar().
add_space_between_logical() [2/2]
String wrimsv2.wreslplus.elements.Tools.add_space_between_logical (String s) static
Definition at line 253 of file Tools.java.
allToLowerCase() [1/3]
ArrayList< String > wrimsv2.wreslplus.elements.Tools.allToLowerCase (ArrayList< String > inArrayList) static
Definition at line 116 of file Tools.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToLowerCase.alias(), allToLowerCase(), allToLowerCase2(), allToLowerCase_string_set(), allToLowerCase_weightSubgroup(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIncModelNotExistIgnoreCase(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.convert(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.convert(), wrimsv2.wreslplus.elements.CompileLog.doAlias(), wrimsv2.wreslplus.elements.CompileLog.doGoal(), wrimsv2.wreslplus.elements.CompileLog.doModel(), wrimsv2.tools.solutionRangeFinder.VarsGroup.filterVarsPool(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.findDuplicatesIgnoreCase(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.goal(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.ifIncFileGroup(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.sequence(), wrimsv2.tools.solutionRangeFinder.VarsGroup.setVarsPool(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.svar(), and wrimsv2.wreslplus.elements.procedures.ToLowerCase.weightTable().
allToLowerCase() [2/3]
Set< String > wrimsv2.wreslplus.elements.Tools.allToLowerCase (Set< String > inSet) static
Definition at line 188 of file Tools.java.
allToLowerCase() [3/3]
WeightSubgroup wrimsv2.wreslplus.elements.Tools.allToLowerCase (WeightSubgroup wsg) static
Definition at line 177 of file Tools.java.
References allToLowerCase(), wrimsv2.wreslplus.elements.WeightSubgroup.deviationPenalty, wrimsv2.wreslplus.elements.WeightSubgroup.deviationTolerance, wrimsv2.wreslplus.elements.WeightSubgroup.id, and wrimsv2.wreslplus.elements.WeightSubgroup.varList.
allToLowerCase2()
ArrayList< ArrayList< String > > wrimsv2.wreslplus.elements.Tools.allToLowerCase2 (ArrayList< ArrayList< String > > inArrayList) static
Definition at line 126 of file Tools.java.
References allToLowerCase().
Referenced by wrimsv2.wreslplus.elements.procedures.ToLowerCase.ifIncFileGroup().
allToLowerCase_string()
Map< String, String > wrimsv2.wreslplus.elements.Tools.allToLowerCase_string (Map< String, String > inMap) static
Definition at line 137 of file Tools.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToLowerCase.weightTable().
allToLowerCase_string_set()
Map< String, HashSet< String > > wrimsv2.wreslplus.elements.Tools.allToLowerCase_string_set (Map< String, HashSet< String > > inMap) static
Definition at line 147 of file Tools.java.
References allToLowerCase().
Referenced by wrimsv2.wreslplus.elements.procedures.ToLowerCase.sequence().
allToLowerCase_weightSubgroup()
LinkedHashMap< String, WeightSubgroup > wrimsv2.wreslplus.elements.Tools.allToLowerCase_weightSubgroup (Map< String, WeightSubgroup > inMap) static
Definition at line 167 of file Tools.java.
References allToLowerCase().
Referenced by wrimsv2.wreslplus.elements.procedures.ToLowerCase.weightTable().
allToLowerCaseString()
Map< String, Integer > wrimsv2.wreslplus.elements.Tools.allToLowerCaseString (Map< String, Integer > inMap) static
Definition at line 157 of file Tools.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToLowerCase.weightTable().
allToUpperCase()
ArrayList< String > wrimsv2.wreslplus.elements.Tools.allToUpperCase (ArrayList< String > inArrayList) static
Definition at line 105 of file Tools.java.
convertStrToSet()
Set< String > wrimsv2.wreslplus.elements.Tools.convertStrToSet (String inStr) static
Definition at line 490 of file Tools.java.
deleteDir()
boolean wrimsv2.wreslplus.elements.Tools.deleteDir (String dirString) static
Definition at line 370 of file Tools.java.
References deleteDir().
Referenced by deleteDir().
findAllOffspring()
HashSet< String > wrimsv2.wreslplus.elements.Tools.findAllOffspring (String fileName, final Map< String, HashSet< String > > kidMap) static
Definition at line 59 of file Tools.java.
References findAllOffspring().
Referenced by wrimsv2.wreslplus.elements.Procedures.findAllOffSpring(), wrimsv2.wreslplus.elements.procedures.ProcIncModel.findAllOffSpring(), findAllOffspring(), and wrimsv2.wreslplus.elements.procedures.ProcMainFile.findAllOffSpring_incModel().
findFileHierarchy()
void wrimsv2.wreslplus.elements.Tools.findFileHierarchy (ArrayList< HashSet< String > > hierarchySetList, Map< String, HashSet< String > > toBeSorted) static
Definition at line 77 of file Tools.java.
References findFileHierarchy().
Referenced by wrimsv2.wreslplus.elements.Procedures.findFileGroupOrder(), wrimsv2.wreslplus.elements.procedures.ProcIncModel.findFileGroupOrder(), findFileHierarchy(), and wrimsv2.wreslplus.elements.procedures.ProcMainFile.findGroupOrder_incModel().
findGoalLocation()
String wrimsv2.wreslplus.elements.Tools.findGoalLocation (String goalName) static
Definition at line 587 of file Tools.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.Goal.fromWresl, wrimsv2.commondata.wresldata.ModelDataSet.gMap, and wrimsv2.commondata.wresldata.Goal.line.
getCanonicalLowCasePath()
String wrimsv2.wreslplus.elements.Tools.getCanonicalLowCasePath (String filePath) static
Definition at line 41 of file Tools.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile(), and wrimsv2.wreslplus.elements.ParserUtils.setRunDir().
getCycleVarMap()
Map< String, Set< String > > wrimsv2.wreslplus.elements.Tools.getCycleVarMap (Set< String > setVarCycle) static
Definition at line 534 of file Tools.java.
getReverseMap()
Map< String, Set< String > > wrimsv2.wreslplus.elements.Tools.getReverseMap (Map< String, Set< String > > t1Map) static
type 1 map is the shallow included files, e.g., map(f1, [f7,f9])
Definition at line 418 of file Tools.java.
getReverseMap_arrayList()
Map< String, ArrayList< String > > wrimsv2.wreslplus.elements.Tools.getReverseMap_arrayList (Map< String, ArrayList< String > > t1Map) static
type 1 map is the shallow included files, e.g., map(f1, [f7,f9])
Definition at line 442 of file Tools.java.
getScopeList()
ArrayList< String > wrimsv2.wreslplus.elements.Tools.getScopeList (ArrayList< String > fileList, ArrayList< String > localList) static
Definition at line 385 of file Tools.java.
getScopeMap()
Map< String, String > wrimsv2.wreslplus.elements.Tools.getScopeMap (Set< String > fileSet, Set< String > localSet) static
Definition at line 401 of file Tools.java.
References wrimsv2.commondata.wresldata.Param.global, and wrimsv2.commondata.wresldata.Param.local.
mapRemoveAll() [1/2]
Set< String > wrimsv2.wreslplus.elements.Tools.mapRemoveAll (Map< String, ?> map, ArrayList< String > list) static
Definition at line 485 of file Tools.java.
References mapRemoveAll().
mapRemoveAll() [2/2]
Set< String > wrimsv2.wreslplus.elements.Tools.mapRemoveAll (Map< String, ?> map, Set< String > set) static
Definition at line 475 of file Tools.java.
Referenced by mapRemoveAll().
mapRetainAll()
void wrimsv2.wreslplus.elements.Tools.mapRetainAll (Map< String, ?> map, ArrayList< String > retainKeys) static
Definition at line 462 of file Tools.java.
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions(), and wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go().
noZerofmt()
String wrimsv2.wreslplus.elements.Tools.noZerofmt (double d) static
Definition at line 579 of file Tools.java.
openFile() [1/2]
PrintWriter wrimsv2.wreslplus.elements.Tools.openFile (String dirPath, String fileName) throws IOException static
Definition at line 364 of file Tools.java.
References openFile().
openFile() [2/2]
PrintWriter wrimsv2.wreslplus.elements.Tools.openFile (String dirPath, String fileName, boolean isAppend) throws IOException static
Definition at line 353 of file Tools.java.
Referenced by openFile(), wrimsv2.tools.solutionRangeFinder.Misc.openReportFile(), quickLog(), wrimsv2.wreslplus.elements.OutputUtils.setLogFile(), wrimsv2.wreslplus.elements.OutputUtils.setLogFile(), and wrimsv2.tools.solutionRangeFinder.Misc.writeReport().
quickLog() [1/2]
void wrimsv2.wreslplus.elements.Tools.quickLog (String fn, String x) static
Definition at line 575 of file Tools.java.
References quickLog().
quickLog() [2/2]
void wrimsv2.wreslplus.elements.Tools.quickLog (String fn, String x, boolean isAppend) static
Definition at line 560 of file Tools.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.components.FilePaths.mainDirectory, and openFile().
Referenced by wrimsv2.tools.Warmstart.collectIntegerDV_1(), and quickLog().
readFileAsString() [1/2]
String wrimsv2.wreslplus.elements.Tools.readFileAsString (String file, String csName) throws IOException static
Definition at line 322 of file Tools.java.
readFileAsString() [2/2]
String wrimsv2.wreslplus.elements.Tools.readFileAsString (String filePath) static
Definition at line 299 of file Tools.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg().
Referenced by readFilesFromDirAsMap().
readFileLine()
String wrimsv2.wreslplus.elements.Tools.readFileLine (String filePath) throws IOException static
Definition at line 346 of file Tools.java.
readFilesFromDirAsMap()
Map< String, String > wrimsv2.wreslplus.elements.Tools.readFilesFromDirAsMap (String dir) throws IOException static
Definition at line 279 of file Tools.java.
References readFileAsString().
remove_nulls()
String wrimsv2.wreslplus.elements.Tools.remove_nulls (String s) static
Definition at line 209 of file Tools.java.
removeDuplicates()
Set< String > wrimsv2.wreslplus.elements.Tools.removeDuplicates (ArrayList< String > list) static
Definition at line 518 of file Tools.java.
replace_ignoreChar() [1/2]
ArrayList< String > wrimsv2.wreslplus.elements.Tools.replace_ignoreChar (ArrayList< String > s) static
Definition at line 230 of file Tools.java.
References replace_ignoreChar().
Referenced by replace_ignoreChar().
replace_ignoreChar() [2/2]
String wrimsv2.wreslplus.elements.Tools.replace_ignoreChar (String s) static
Definition at line 238 of file Tools.java.
replace_regex()
String wrimsv2.wreslplus.elements.Tools.replace_regex (String s) static
Definition at line 198 of file Tools.java.
replace_seperator() [1/2]
ArrayList< String > wrimsv2.wreslplus.elements.Tools.replace_seperator (ArrayList< String > s) static
Definition at line 266 of file Tools.java.
References replace_seperator().
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertAlias(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertGoal(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertSvar(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertWeight(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processVar(), and replace_seperator().
replace_seperator() [2/2]
String wrimsv2.wreslplus.elements.Tools.replace_seperator (String s) static
Definition at line 274 of file Tools.java.
References wrimsv2.commondata.wresldata.Param.arg_seperator, and wrimsv2.commondata.wresldata.Param.new_seperator.
replace_with_space() [1/2]
ArrayList< String > wrimsv2.wreslplus.elements.Tools.replace_with_space (ArrayList< String > s) static
Definition at line 215 of file Tools.java.
References replace_with_space().
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertWeight(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.goal(), replace_with_space(), and wrimsv2.wreslplus.elements.procedures.ToLowerCase.svar().
replace_with_space() [2/2]
String wrimsv2.wreslplus.elements.Tools.replace_with_space (String s) static
Definition at line 223 of file Tools.java.
restoreOrder()
Set< String > wrimsv2.wreslplus.elements.Tools.restoreOrder (ArrayList< String > toBeRestored, ArrayList< String > referenceOrder, Set< String > member) static
Definition at line 503 of file Tools.java.
strip()
String wrimsv2.wreslplus.elements.Tools.strip (String s) static
Definition at line 36 of file Tools.java.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/Tools.java