Wrims-engine: wrimsv2.config.ConfigUtils Class Reference
wrimsv2.config.ConfigUtils Class Reference
Static Public Member Functions
static void loadArgs (String[] args)
static boolean readBoolean (Map< String, String > cM, String name, boolean defaultV)
static double readDouble (Map< String, String > cM, String name, double defaultV)
static void readParameter (String configFilePath)
Static Public Attributes
static Map< String, String > configMap = new HashMap<String, String>()
static LinkedHashMap< String, ParamTemp > paramMap = new LinkedHashMap<String, ParamTemp>()
Static Private Member Functions
static Map< String, String > checkConfigFile (String configFilePath)
static Set< String > checkExpression (String text) throws RecognitionException
static void loadConfig (String configFile)
static Map< String, String > setDefaultConfig ()
Static Private Attributes
static Map< String, String > argsMap
Detailed Description
Definition at line 29 of file ConfigUtils.java.
Member Function Documentation
checkConfigFile()
Map< String, String > wrimsv2.config.ConfigUtils.checkConfigFile (String configFilePath) static private
Definition at line 1197 of file ConfigUtils.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.wreslparser.elements.StudyUtils.configDir, wrimsv2.wreslparser.elements.StudyUtils.configFileCanonicalPath, configMap, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.evaluator.TimeOperation.numberOfDays(), setDefaultConfig(), and wrimsv2.components.Error.writeErrorLog().
Referenced by loadConfig().
checkExpression()
Set< String > wrimsv2.config.ConfigUtils.checkExpression (String text) throws RecognitionException static private
Definition at line 1477 of file ConfigUtils.java.
References wrimsv2.wreslplus.elements.ParserUtils.initParserSimple().
loadArgs()
void wrimsv2.config.ConfigUtils.loadArgs (String[] args) static
Definition at line 37 of file ConfigUtils.java.
References argsMap, wrimsv2.wreslparser.elements.StudyUtils.compileOnly, wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.Error.getTotalError(), loadConfig(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus, and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.components.ControllerBatch.processArgs(), wrimsv2.hdf5.DSSHDF5Converter.processArgs(), and wrimsv2.components.ControllerDebug.run().
loadConfig()
void wrimsv2.config.ConfigUtils.loadConfig (String configFile) static private
Definition at line 115 of file ConfigUtils.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.components.ControlData.allowSvTsInit, wrimsv2.components.ControlData.allRestartFiles, wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.solver.CbcSolver.cbcHintRelaxPenalty, wrimsv2.solver.CbcSolver.cbcHintTimeMax, wrimsv2.solver.CbcSolver.cbcLibName, wrimsv2.components.ControlData.cbcLogNativeLp, wrimsv2.solver.CbcSolver.cbcLogStartDate, wrimsv2.solver.CbcSolver.cbcLogStopDate, wrimsv2.solver.CbcSolver.cbcSolutionRounding, wrimsv2.solver.CbcSolver.cbcVersion, wrimsv2.solver.CbcSolver.cbcViolationCheck, wrimsv2.solver.CbcSolver.cbcViolationRetry, checkConfigFile(), wrimsv2.wreslparser.elements.StudyUtils.configDir, wrimsv2.solver.LPSolveSolver.configFile, wrimsv2.wreslparser.elements.StudyUtils.configFileName, configMap, wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.databaseURL, wrimsv2.solver.CbcSolver.debugDeviation, wrimsv2.solver.CbcSolver.debugDeviationFindMissing, wrimsv2.solver.CbcSolver.debugDeviationMin, wrimsv2.solver.CbcSolver.debugDeviationWeightMin, wrimsv2.solver.CbcSolver.debugDeviationWeightMultiply, wrimsv2.solver.CbcSolver.debugObjDiff, wrimsv2.components.ControlData.enableProgressLog, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.components.FilePaths.fullSvarFile2Path, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.components.ControlData.genSVCatalog, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.solver.CbcSolver.integerT, wrimsv2.solver.CbcSolver.integerT_check, wrimsv2.components.ControlData.isNameSorting, wrimsv2.components.ControlData.isOutputCycle, wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.solver.CbcSolver.log_if_obj_diff, wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingAllCycles, wrimsv2.ilp.ILP.loggingAmpl, wrimsv2.ilp.ILP.loggingCplexLp, wrimsv2.ilp.ILP.loggingLpSolve, wrimsv2.ilp.ILP.loggingMPModel, wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.ilp.ILP.loggingVariableValueRound, wrimsv2.ilp.ILP.loggingVariableValueRound10, wrimsv2.solver.CbcSolver.logObj, wrimsv2.components.FilePaths.lookupSubDirectory, wrimsv2.solver.CbcSolver.lowerBoundZero_check, wrimsv2.ilp.ILP.maximumFractionDigits, wrimsv2.components.ControlData.monMemSection, wrimsv2.solver.LPSolveSolver.numberOfRetries, wrimsv2.components.ControlData.numberRestartFiles, wrimsv2.components.ControlData.outputAllCycles, wrimsv2.components.ControlData.ovFile, wrimsv2.components.ControlData.ovOption, wrimsv2.wreslparser.elements.StudyUtils.parserCheckVarUndefined, wrimsv2.wreslparser.elements.StudyUtils.parserDataPath, wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.partE, wrimsv2.components.ControlData.printGWFuncCalls, readBoolean(), readDouble(), wrimsv2.solver.CbcSolver.record_if_obj_diff, wrimsv2.components.ControlData.relationTolerance, wrimsv2.components.ControlData.selectedCycleOutput, wrimsv2.components.ControlData.sendAliasToDvar, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFile2Paths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.components.ControlData.showWreslLog, wrimsv2.solver.CbcSolver.solv2, wrimsv2.solver.CbcSolver.solv3, wrimsv2.solver.CbcSolver.solvCallCbc, wrimsv2.solver.CbcSolver.solve_2_primalT, wrimsv2.solver.CbcSolver.solve_2_primalT_relax, wrimsv2.solver.CbcSolver.solve_whs_primalT, wrimsv2.components.ControlData.solverName, wrimsv2.solver.CbcSolver.solvFull, wrimsv2.solver.CbcSolver.solvFunc, wrimsv2.solver.CbcSolver.solvU, wrimsv2.components.ControlData.sqlGroup, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.ControlData.svDvPartF, wrimsv2.components.ControlData.timeStep, wrimsv2.components.ControlData.unchangeGWRestart, wrimsv2.components.ControlData.useCbcWarmStart, wrimsv2.solver.CbcSolver.usejCbc2021, wrimsv2.solver.CbcSolver.usejCbc2021a, wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus, wrimsv2.components.ControlData.vHecLib, wrimsv2.solver.CbcSolver.warm_2nd_solvFunc, wrimsv2.components.ControlData.watchList, wrimsv2.components.ControlData.watchList_tolerance, wrimsv2.solver.CbcSolver.whsSafe, wrimsv2.solver.CbcSolver.whsScaling, wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.components.ControlData.yearOutputSection, and wrimsv2.components.ControlData.zeroTolerance.
Referenced by loadArgs().
readBoolean()
boolean wrimsv2.config.ConfigUtils.readBoolean (Map< String, String > cM, String name, boolean defaultV) static
Definition at line 1487 of file ConfigUtils.java.
Referenced by wrimsv2.external.SalinitySurrogateSetup.getManager(), and loadConfig().
readDouble()
double wrimsv2.config.ConfigUtils.readDouble (Map< String, String > cM, String name, double defaultV) static
Definition at line 1501 of file ConfigUtils.java.
Referenced by loadConfig().
readParameter()
void wrimsv2.config.ConfigUtils.readParameter (String configFilePath) static
Definition at line 1390 of file ConfigUtils.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.wreslplus.elements.ParamTemp.expression, wrimsv2.wreslplus.elements.ParamTemp.id, and paramMap.
setDefaultConfig()
Map< String, String > wrimsv2.config.ConfigUtils.setDefaultConfig () static private
Definition at line 1353 of file ConfigUtils.java.
References configMap.
Referenced by checkConfigFile().
Member Data Documentation
argsMap
Map<String, String> wrimsv2.config.ConfigUtils.argsMap static private
Definition at line 31 of file ConfigUtils.java.
Referenced by loadArgs().
configMap
Map<String, String> wrimsv2.config.ConfigUtils.configMap = new HashMap<String, String>() static
Definition at line 35 of file ConfigUtils.java.
Referenced by checkConfigFile(), wrimsv2.external.SalinitySurrogateSetup.getManager(), loadConfig(), and setDefaultConfig().
paramMap
LinkedHashMap<String, ParamTemp> wrimsv2.config.ConfigUtils.paramMap = new LinkedHashMap<String, ParamTemp>() static
Definition at line 33 of file ConfigUtils.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialVarInConfigNotDeclaredInWresl(), wrimsv2.wreslplus.elements.Workflow.checkStudy(), and readParameter().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/config/ConfigUtils.java