Wrims-engine: wrimsv2.wreslplus.elements.procedures.ToWreslData Class Reference
wrimsv2.wreslplus.elements.procedures.ToWreslData Class Reference
Static Public Member Functions
static Alias convertAlias (AliasTemp d)
static Dvar convertDvar (DvarTemp d)
static External convertExternal (ExternalTemp e)
static Goal convertGoal (GoalTemp g)
static ModelDataSet convertModel (SequenceTemp seq, StudyTemp st)
static StudyDataSet convertStudy (StudyTemp s)
static Svar convertSvar (SvarTemp s)
static Timeseries convertTimeseries (TimeseriesTemp t)
static WeightElement convertWeight (WeightTemp w)
static Map< String, WeightElement > convertWeightTable (WeightTable w)
static Map< String, WeightElement > convertWeightTableGroup (WeightTable w)
static Svar processVar (SvarTemp s)
Private Member Functions
ToWreslData ()
Static Private Member Functions
static LinkedHashMap< String, Svar > convertParameterMap (Map< String, String > simpleMap)
static void initialize ()
static void processAlias (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processDvar (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processGoal (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processGroupWeight (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processSsList_noCase (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processSsWeight_noCase (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processSvar (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processTimeseries (SequenceTemp seq, StudyTemp st, ModelDataSet out)
static void processWeightTableObjList (SequenceTemp seq, StudyTemp st, ModelDataSet out)
Static Private Attributes
static HashBasedTable< String, String, Alias > fileAsMap
static HashBasedTable< String, String, Dvar > fileDvMap
static HashBasedTable< String, String, Goal > fileGlMap
static HashBasedTable< String, String, WeightElement > fileGroupWeightMap
static HashBasedTable< String, String, Dvar > fileSlackSurplusNoCaseMap
static HashBasedTable< String, String, WeightElement > fileSsWeightMap_noCase
static HashBasedTable< String, String, Svar > fileSvMap
static HashBasedTable< String, String, Timeseries > fileTsMap
static HashBasedTable< String, String, WeightElement > fileWeightMap
static HashBasedTable< String, String, HashMap< String, WeightElement > > fileWTableObjMap
static HashBasedTable< String, String, HashMap< String, WeightElement > > mainfileModelWTableObjMap
static HashBasedTable< String, Integer, Svar > StringIntegerSvarMap
Detailed Description
Definition at line 37 of file ToWreslData.java.
Constructor & Destructor Documentation
ToWreslData()
wrimsv2.wreslplus.elements.procedures.ToWreslData.ToWreslData () private
Definition at line 54 of file ToWreslData.java.
Member Function Documentation
convertAlias()
Alias wrimsv2.wreslplus.elements.procedures.ToWreslData.convertAlias (AliasTemp d) static
Definition at line 830 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.AliasTemp.condition, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.AliasTemp.expression, wrimsv2.wreslplus.elements.AliasTemp.fromWresl, wrimsv2.wreslplus.elements.AliasTemp.kind, wrimsv2.wreslplus.elements.AliasTemp.line, wrimsv2.wreslplus.elements.AliasTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.AliasTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.AliasTemp.noSolver, wrimsv2.wreslplus.elements.Tools.replace_seperator(), wrimsv2.wreslplus.elements.AliasTemp.timeArraySize, and wrimsv2.wreslplus.elements.AliasTemp.units.
Referenced by processAlias().
convertDvar()
Dvar wrimsv2.wreslplus.elements.procedures.ToWreslData.convertDvar (DvarTemp d) static
Definition at line 681 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.DvarTemp.condition, wrimsv2.wreslplus.elements.DvarTemp.fromWresl, wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.wreslplus.elements.DvarTemp.isInteger, wrimsv2.wreslplus.elements.DvarTemp.kind, wrimsv2.wreslplus.elements.DvarTemp.line, wrimsv2.wreslplus.elements.DvarTemp.lowerBound, wrimsv2.wreslplus.elements.DvarTemp.timeArraySize, wrimsv2.wreslplus.elements.DvarTemp.units, wrimsv2.wreslplus.elements.DvarTemp.upperBound, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by convertModel(), processDvar(), and processSsList_noCase().
convertExternal()
External wrimsv2.wreslplus.elements.procedures.ToWreslData.convertExternal (ExternalTemp e) static
Definition at line 784 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.ExternalTemp.fileName, wrimsv2.wreslplus.elements.ExternalTemp.fromWresl, and wrimsv2.wreslplus.elements.ExternalTemp.line.
Referenced by convertModel().
convertGoal()
Goal wrimsv2.wreslplus.elements.procedures.ToWreslData.convertGoal (GoalTemp g) static
Definition at line 797 of file ToWreslData.java.
References wrimsv2.commondata.wresldata.Goal.caseCondition, wrimsv2.wreslplus.elements.GoalTemp.caseCondition, wrimsv2.commondata.wresldata.Goal.caseExpression, wrimsv2.wreslplus.elements.GoalTemp.caseExpression, wrimsv2.wreslplus.elements.GoalTemp.caseName, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.GoalTemp.dvarSlackSurplusList, wrimsv2.wreslplus.elements.GoalTemp.dvarWeightMapList, wrimsv2.commondata.wresldata.Goal.expressionDependants, wrimsv2.wreslplus.elements.GoalTemp.fromWresl, wrimsv2.wreslplus.elements.GoalTemp.line, wrimsv2.wreslplus.elements.GoalTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.GoalTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.Tools.replace_seperator(), wrimsv2.commondata.wresldata.Param.reservedSet, and wrimsv2.wreslplus.elements.GoalTemp.timeArraySize.
Referenced by processGoal().
convertModel()
ModelDataSet wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel (SequenceTemp seq, StudyTemp st) static
Definition at line 147 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.SequenceTemp.aliasUsedByLaterCycle, wrimsv2.wreslplus.elements.SequenceTemp.asIncFileList_post, convertDvar(), convertExternal(), convertWeight(), wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.wreslplus.elements.SequenceTemp.deviationSlackSurplus_toleranceMap, wrimsv2.wreslplus.elements.SequenceTemp.dvarUsedByLaterCycle, wrimsv2.wreslplus.elements.SequenceTemp.dvIncFileList_post, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvList_deviationSlackSurplus, wrimsv2.wreslplus.elements.SequenceTemp.dvList_deviationSlackSurplus, wrimsv2.wreslplus.elements.SequenceTemp.dvList_fromAlias, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.wreslplus.elements.SequenceTemp.exIncFileList_post, wrimsv2.commondata.wresldata.ModelDataSet.exList, wrimsv2.commondata.wresldata.ModelDataSet.exMap, wrimsv2.wreslplus.elements.SequenceTemp.exMap, wrimsv2.wreslplus.elements.SequenceTemp.glIncFileList_post, wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.wreslplus.elements.SequenceTemp.glList_fromAlias, wrimsv2.wreslplus.elements.SequenceTemp.incFileAbsPathList_post, wrimsv2.components.ControlData.isNameSorting, processAlias(), processDvar(), processGoal(), processGroupWeight(), processSsList_noCase(), processSsWeight_noCase(), processSvar(), processTimeseries(), processWeightTableObjList(), wrimsv2.wreslplus.elements.SequenceTemp.ssList_hasCase, wrimsv2.wreslplus.elements.SequenceTemp.ssList_noCase, wrimsv2.wreslplus.elements.SequenceTemp.ssMap_hasCase, wrimsv2.wreslplus.elements.SequenceTemp.ssWeightMap_hasCase, wrimsv2.wreslplus.elements.SequenceTemp.svarUsedByLaterCycle, wrimsv2.wreslplus.elements.SequenceTemp.svIncFileList_post, wrimsv2.commondata.wresldata.ModelDataSet.tsList, wrimsv2.wreslplus.elements.SequenceTemp.tsList, wrimsv2.wreslplus.elements.SequenceTemp.varUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.wtList, wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusMap, and wrimsv2.wreslplus.elements.SequenceTemp.wvList.
Referenced by convertStudy().
convertParameterMap()
LinkedHashMap< String, Svar > wrimsv2.wreslplus.elements.procedures.ToWreslData.convertParameterMap (Map< String, String > simpleMap) static private
Definition at line 126 of file ToWreslData.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseName, and wrimsv2.commondata.wresldata.Param.defaultCaseName.
convertStudy()
StudyDataSet wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy (StudyTemp s) static
Definition at line 73 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.SequenceTemp.condition, wrimsv2.wreslplus.elements.StudyTemp.controlDataParameterMap, convertModel(), initialize(), wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.StudyTemp.seqTimeStepList, wrimsv2.commondata.wresldata.StudyDataSet.setModelConditionList(), wrimsv2.commondata.wresldata.StudyDataSet.setModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.setModelList(), wrimsv2.commondata.wresldata.StudyDataSet.setModelTimeStepList(), wrimsv2.commondata.wresldata.StudyDataSet.setParameterList(), wrimsv2.commondata.wresldata.StudyDataSet.setParameterMap(), wrimsv2.commondata.wresldata.StudyDataSet.setTimeseriesMap(), wrimsv2.commondata.wresldata.StudyDataSet.setTimeseriesTimeStepMap(), wrimsv2.commondata.wresldata.StudyDataSet.setVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.setVarCycleValueMap(), wrimsv2.wreslplus.elements.StudyTemp.timeseriesTimeStepMap, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.wreslplus.elements.VarCycleIndex.varCycleIndexList, and wrimsv2.wreslplus.elements.StudyTemp.varCycleValueMap.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.parseWreslPlus().
convertSvar()
Svar wrimsv2.wreslplus.elements.procedures.ToWreslData.convertSvar (SvarTemp s) static
Definition at line 629 of file ToWreslData.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.wreslplus.elements.SvarTemp.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.wreslplus.elements.SvarTemp.caseExpression, wrimsv2.wreslplus.elements.SvarTemp.caseName, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.SvarTemp.id, wrimsv2.wreslplus.elements.SvarTemp.kind, wrimsv2.wreslplus.elements.SvarTemp.line, wrimsv2.wreslplus.elements.SvarTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.SvarTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.Tools.replace_seperator(), wrimsv2.wreslplus.elements.SvarTemp.timeArraySize, and wrimsv2.wreslplus.elements.SvarTemp.units.
Referenced by processSvar().
convertTimeseries()
Timeseries wrimsv2.wreslplus.elements.procedures.ToWreslData.convertTimeseries (TimeseriesTemp t) static
Definition at line 666 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.TimeseriesTemp.convertToUnits, wrimsv2.wreslplus.elements.TimeseriesTemp.dssBPart, wrimsv2.wreslplus.elements.TimeseriesTemp.fromWresl, wrimsv2.wreslplus.elements.TimeseriesTemp.kind, wrimsv2.wreslplus.elements.TimeseriesTemp.line, and wrimsv2.wreslplus.elements.TimeseriesTemp.units.
Referenced by processTimeseries().
convertWeight()
WeightElement wrimsv2.wreslplus.elements.procedures.ToWreslData.convertWeight (WeightTemp w) static
Definition at line 701 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.WeightTemp.condition, wrimsv2.wreslplus.elements.WeightTemp.fromWresl, wrimsv2.wreslplus.elements.WeightTemp.line, wrimsv2.wreslplus.elements.Tools.replace_seperator(), wrimsv2.wreslplus.elements.Tools.replace_with_space(), wrimsv2.wreslplus.elements.WeightTemp.timeArraySize, wrimsv2.commondata.wresldata.WeightElement.weight, and wrimsv2.wreslplus.elements.WeightTemp.weight.
Referenced by convertModel(), processGroupWeight(), and processSsWeight_noCase().
convertWeightTable()
Map< String, WeightElement > wrimsv2.wreslplus.elements.procedures.ToWreslData.convertWeightTable (WeightTable w) static
Definition at line 719 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.WeightTable.condition, wrimsv2.wreslplus.elements.WeightTable.fromWresl, wrimsv2.wreslplus.elements.WeightTable.varLineMap, wrimsv2.wreslplus.elements.WeightTable.varList, wrimsv2.wreslplus.elements.WeightTable.varTimeArraySizeMap, and wrimsv2.wreslplus.elements.WeightTable.varWeightMap.
Referenced by processWeightTableObjList().
convertWeightTableGroup()
Map< String, WeightElement > wrimsv2.wreslplus.elements.procedures.ToWreslData.convertWeightTableGroup (WeightTable w) static
Definition at line 746 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.WeightTable.commonWeight, wrimsv2.wreslplus.elements.WeightTable.condition, wrimsv2.wreslplus.elements.WeightTable.fromWresl, wrimsv2.wreslplus.elements.WeightTable.line, wrimsv2.wreslplus.elements.WeightTable.subgroupMap, and wrimsv2.wreslplus.elements.WeightTable.varList.
Referenced by processWeightTableObjList().
initialize()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.initialize () static private
Definition at line 56 of file ToWreslData.java.
References fileAsMap, fileDvMap, fileGlMap, fileGroupWeightMap, fileSlackSurplusNoCaseMap, fileSsWeightMap_noCase, fileSvMap, fileTsMap, fileWeightMap, fileWTableObjMap, mainfileModelWTableObjMap, and StringIntegerSvarMap.
Referenced by convertStudy().
processAlias()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processAlias (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 568 of file ToWreslData.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.SequenceTemp.asMap, convertAlias(), fileAsMap, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, and wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post.
Referenced by convertModel().
processDvar()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processDvar (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 463 of file ToWreslData.java.
References convertDvar(), wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.wreslplus.elements.SequenceTemp.dvMap, fileDvMap, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, and wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post.
Referenced by convertModel().
processGoal()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processGoal (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 409 of file ToWreslData.java.
References convertGoal(), fileGlMap, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.SequenceTemp.glMap, wrimsv2.commondata.wresldata.ModelDataSet.gMap, and wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post.
Referenced by convertModel().
processGroupWeight()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processGroupWeight (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 542 of file ToWreslData.java.
References convertWeight(), fileGroupWeightMap, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.SequenceTemp.groupWeightMap, wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post, and wrimsv2.commondata.wresldata.ModelDataSet.wtMap.
Referenced by convertModel().
processSsList_noCase()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processSsList_noCase (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 490 of file ToWreslData.java.
References convertDvar(), wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, fileSlackSurplusNoCaseMap, wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.SequenceTemp.ssList_noCase, and wrimsv2.wreslplus.elements.SequenceTemp.ssMap_noCase.
Referenced by convertModel().
processSsWeight_noCase()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processSsWeight_noCase (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 516 of file ToWreslData.java.
References convertWeight(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, fileSsWeightMap_noCase, wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.SequenceTemp.ssWeightMap_noCase, and wrimsv2.commondata.wresldata.ModelDataSet.wtMap.
Referenced by convertModel().
processSvar()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processSvar (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 436 of file ToWreslData.java.
References convertSvar(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, fileSvMap, wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post, wrimsv2.commondata.wresldata.ModelDataSet.svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, and wrimsv2.wreslplus.elements.SequenceTemp.svMap.
Referenced by convertModel().
processTimeseries()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processTimeseries (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 381 of file ToWreslData.java.
References convertTimeseries(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, fileTsMap, wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, and wrimsv2.wreslplus.elements.SequenceTemp.tsMap.
Referenced by convertModel().
processVar()
Svar wrimsv2.wreslplus.elements.procedures.ToWreslData.processVar (SvarTemp s) static
Definition at line 594 of file ToWreslData.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.wreslplus.elements.SvarTemp.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.wreslplus.elements.SvarTemp.caseExpression, wrimsv2.wreslplus.elements.SvarTemp.caseName, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.SvarTemp.id, wrimsv2.wreslplus.elements.SvarTemp.kind, wrimsv2.wreslplus.elements.SvarTemp.line, wrimsv2.wreslplus.elements.SvarTemp.neededVarInCycleSet, wrimsv2.wreslplus.elements.SvarTemp.needVarFromEarlierCycle, wrimsv2.wreslplus.elements.Tools.replace_seperator(), wrimsv2.wreslplus.elements.SvarTemp.timeArraySize, and wrimsv2.wreslplus.elements.SvarTemp.units.
processWeightTableObjList()
void wrimsv2.wreslplus.elements.procedures.ToWreslData.processWeightTableObjList (SequenceTemp seq, StudyTemp st, ModelDataSet out) static private
Definition at line 289 of file ToWreslData.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, convertWeightTable(), convertWeightTableGroup(), wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, fileWeightMap, fileWTableObjMap, wrimsv2.wreslplus.elements.WeightTable.id_lowcase, wrimsv2.wreslplus.elements.SequenceTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.WeightTable.isWeightGroup, mainfileModelWTableObjMap, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.ModelTemp.wTableObjList, and wrimsv2.commondata.wresldata.ModelDataSet.wtMap.
Referenced by convertModel().
Member Data Documentation
fileAsMap
HashBasedTable<String,String,Alias> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileAsMap static private
Definition at line 43 of file ToWreslData.java.
Referenced by initialize(), and processAlias().
fileDvMap
HashBasedTable<String,String,Dvar> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileDvMap static private
Definition at line 41 of file ToWreslData.java.
Referenced by initialize(), and processDvar().
fileGlMap
HashBasedTable<String,String,Goal> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileGlMap static private
Definition at line 44 of file ToWreslData.java.
Referenced by initialize(), and processGoal().
fileGroupWeightMap
HashBasedTable<String,String,WeightElement> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileGroupWeightMap static private
Definition at line 46 of file ToWreslData.java.
Referenced by initialize(), and processGroupWeight().
fileSlackSurplusNoCaseMap
HashBasedTable<String,String,Dvar> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileSlackSurplusNoCaseMap static private
Definition at line 45 of file ToWreslData.java.
Referenced by initialize(), and processSsList_noCase().
fileSsWeightMap_noCase
HashBasedTable<String,String,WeightElement> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileSsWeightMap_noCase static private
Definition at line 47 of file ToWreslData.java.
Referenced by initialize(), and processSsWeight_noCase().
fileSvMap
HashBasedTable<String,String,Svar> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileSvMap static private
Definition at line 40 of file ToWreslData.java.
Referenced by initialize(), and processSvar().
fileTsMap
HashBasedTable<String,String,Timeseries> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileTsMap static private
Definition at line 42 of file ToWreslData.java.
Referenced by initialize(), and processTimeseries().
fileWeightMap
HashBasedTable<String,String,WeightElement> wrimsv2.wreslplus.elements.procedures.ToWreslData.fileWeightMap static private
Definition at line 48 of file ToWreslData.java.
Referenced by initialize(), and processWeightTableObjList().
fileWTableObjMap
HashBasedTable<String,String,HashMap<String,WeightElement> > wrimsv2.wreslplus.elements.procedures.ToWreslData.fileWTableObjMap static private
Definition at line 49 of file ToWreslData.java.
Referenced by initialize(), and processWeightTableObjList().
mainfileModelWTableObjMap
HashBasedTable<String,String,HashMap<String,WeightElement> > wrimsv2.wreslplus.elements.procedures.ToWreslData.mainfileModelWTableObjMap static private
Definition at line 50 of file ToWreslData.java.
Referenced by initialize(), and processWeightTableObjList().
StringIntegerSvarMap
HashBasedTable<String,Integer,Svar> wrimsv2.wreslplus.elements.procedures.ToWreslData.StringIntegerSvarMap static private
Definition at line 52 of file ToWreslData.java.
Referenced by initialize().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ToWreslData.java