Wrims-engine: wrimsv2.components.LoadParameter Class Reference
wrimsv2.components.LoadParameter Class Reference
Static Public Member Functions
static void process (StudyDataSet sds)
Private Member Functions
LoadParameter ()
Static Private Member Functions
static boolean callBooleanEvaluator (String evalString)
static IntDouble callNumberEvaluator (String evalString)
static LinkedHashMap< String, Svar > convertParamMapToSvarMap (Map< String, Svar > simpleMap)
static void evaluateAllParams (ArrayList< String > keyList, Map< String, Svar > map)
Detailed Description
Definition at line 25 of file LoadParameter.java.
Constructor & Destructor Documentation
LoadParameter()
wrimsv2.components.LoadParameter.LoadParameter () private
Definition at line 27 of file LoadParameter.java.
Member Function Documentation
callBooleanEvaluator()
boolean wrimsv2.components.LoadParameter.callBooleanEvaluator (String evalString) static private
Definition at line 67 of file LoadParameter.java.
References wrimsv2.components.Error.getTotalError(), and wrimsv2.components.Error.writeErrorLog().
Referenced by evaluateAllParams().
callNumberEvaluator()
IntDouble wrimsv2.components.LoadParameter.callNumberEvaluator (String evalString) static private
Definition at line 96 of file LoadParameter.java.
References wrimsv2.components.Error.getTotalError(), and wrimsv2.components.Error.writeErrorLog().
Referenced by evaluateAllParams().
convertParamMapToSvarMap()
LinkedHashMap< String, Svar > wrimsv2.components.LoadParameter.convertParamMapToSvarMap (Map< String, Svar > simpleMap) static private
Definition at line 127 of file LoadParameter.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, and wrimsv2.commondata.wresldata.Svar.caseName.
Referenced by process().
evaluateAllParams()
void wrimsv2.components.LoadParameter.evaluateAllParams (ArrayList< String > keyList, Map< String, Svar > map) static private
Definition at line 40 of file LoadParameter.java.
References callBooleanEvaluator(), callNumberEvaluator(), wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, and wrimsv2.commondata.wresldata.Svar.setData().
Referenced by process().
process()
void wrimsv2.components.LoadParameter.process (StudyDataSet sds) static
Definition at line 30 of file LoadParameter.java.
References wrimsv2.commondata.wresldata.StudyDataSet.controlDataParameterMap, convertParamMapToSvarMap(), evaluateAllParams(), wrimsv2.commondata.wresldata.StudyDataSet.getParameterList(), wrimsv2.commondata.wresldata.StudyDataSet.getParameterMap(), and wrimsv2.components.ControlData.parameterMap.
Referenced by wrimsv2.components.ControllerBatch.parse(), and wrimsv2.components.ControllerDebug.parse().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/LoadParameter.java