Wrims-engine: wrimsv2.commondata.wresldata.ModelDataSet Class Reference
wrimsv2.commondata.wresldata.ModelDataSet Class Reference
Public Member Functions
void clearFutureAsMap ()
void clearFutureSvMap ()
void processAlias ()
void processDvar ()
void processGoal ()
void processModel ()
void processSvar ()
void processTimeseries ()
void processWeight ()
void processWeightSlackSurplus ()
void resetSlackSurplusWeight ()
Public Attributes
Set< String > aliasUsedByLaterCycle = new HashSet<String>()
Map< String, Alias > asFutMap = new HashMap<String, Alias>()
ArrayList< String > asList = new ArrayList<String>()
ArrayList< String > asList_global = new ArrayList<String>()
ArrayList< String > asList_local = new ArrayList<String>()
Map< String, Alias > asMap = new HashMap<String, Alias>()
Set< String > asSet_unknown = new HashSet<String>()
Map< String, Double > deviationSlackSurplus_toleranceMap = new HashMap<String, Double>()
Set< String > dvarTimeArrayUsedByLaterCycle = new HashSet<String>()
Set< String > dvarUsedByLaterCycle = new HashSet<String>()
ArrayList< String > dvList = new ArrayList<String>()
ArrayList< String > dvList_deviationSlackSurplus = new ArrayList<String>()
ArrayList< String > dvList_global = new ArrayList<String>()
ArrayList< String > dvList_local = new ArrayList<String>()
Map< String, Dvar > dvMap = new HashMap<String, Dvar>()
ArrayList< String > dvSlackSurplusList = new ArrayList<String>()
Map< String, Dvar > dvSlackSurplusMap = new HashMap<String, Dvar>()
ArrayList< String > dvTimeArrayList = new ArrayList<String>()
ArrayList< String > exList = new ArrayList<String>()
ArrayList< String > exList_global = new ArrayList<String>()
ArrayList< String > exList_local = new ArrayList<String>()
Map< String, External > exMap = new HashMap<String, External>()
ArrayList< String > gList = new ArrayList<String>()
ArrayList< String > gList_global = new ArrayList<String>()
ArrayList< String > gList_local = new ArrayList<String>()
Map< String, Goal > gMap = new HashMap<String, Goal>()
ArrayList< String > gTimeArrayList = new ArrayList<String>()
ArrayList< String > incFileList =new ArrayList<String>()
ArrayList< String > incFileList_global =new ArrayList<String>()
ArrayList< String > incFileList_local =new ArrayList<String>()
Set< String > svarUsedByLaterCycle = new HashSet<String>()
Map< String, Svar > svFutMap = new HashMap<String, Svar>()
ArrayList< String > svList = new ArrayList<String>()
ArrayList< String > svList_global = new ArrayList<String>()
ArrayList< String > svList_local = new ArrayList<String>()
Map< String, Svar > svMap = new HashMap<String, Svar>()
Set< String > svSet_unknown = new HashSet<String>()
ArrayList< String > timeArrayDvList = new ArrayList<String>()
ArrayList< String > tsList = new ArrayList<String>()
ArrayList< String > tsList_global = new ArrayList<String>()
ArrayList< String > tsList_local = new ArrayList<String>()
Map< String, Timeseries > tsMap = new HashMap<String, Timeseries>()
CopyOnWriteArrayList< String > usedWtSlackSurplusDvList = new CopyOnWriteArrayList<String>()
CopyOnWriteArrayList< String > usedWtSlackSurplusList = new CopyOnWriteArrayList<String>()
Set< String > varUsedByLaterCycle = new HashSet<String>()
ArrayList< String > wtList = new ArrayList<String>()
Map< String, WeightElement > wtMap = new HashMap<String, WeightElement>()
ArrayList< String > wtSlackSurplusList = new ArrayList<String>()
Map< String, WeightElement > wtSlackSurplusMap = new HashMap<String, WeightElement>()
ArrayList< String > wtTimeArrayList = new ArrayList<String>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 36 of file ModelDataSet.java.
Member Function Documentation
clearFutureAsMap()
void wrimsv2.commondata.wresldata.ModelDataSet.clearFutureAsMap ()
Definition at line 650 of file ModelDataSet.java.
References asFutMap.
Referenced by wrimsv2.components.ClearValue.clearValues().
clearFutureSvMap()
void wrimsv2.commondata.wresldata.ModelDataSet.clearFutureSvMap ()
Definition at line 646 of file ModelDataSet.java.
References svFutMap.
Referenced by wrimsv2.components.ClearValue.clearValues().
processAlias()
void wrimsv2.commondata.wresldata.ModelDataSet.processAlias ()
Definition at line 378 of file ModelDataSet.java.
References wrimsv2.components.Error.addEvaluationError(), aliasUsedByLaterCycle, asFutMap, asList, asMap, wrimsv2.components.IntDouble.copyOf(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.Alias.data, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.commondata.wresldata.Alias.expressionParser, wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.commondata.wresldata.TimeArray.getTimeArraySize(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.partE, wrimsv2.evaluator.DssDataSetFixLength.setKind(), wrimsv2.evaluator.DssDataSetFixLength.setStartTime(), wrimsv2.evaluator.DssDataSetFixLength.setTimeStep(), wrimsv2.evaluator.DssDataSetFixLength.setUnits(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.components.ControlData.t_as, wrimsv2.parallel.ParallelVars.timeArrayIndex, wrimsv2.commondata.wresldata.Alias.timeArraySize, wrimsv2.commondata.wresldata.Alias.timeArraySizeParser, wrimsv2.components.ControlData.timeStep, wrimsv2.components.ControlData.totalTimeStep, and wrimsv2.commondata.wresldata.Alias.units.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
processDvar()
void wrimsv2.commondata.wresldata.ModelDataSet.processDvar ()
Definition at line 346 of file ModelDataSet.java.
References wrimsv2.commondata.solverdata.SolverData.clearDvarMap(), wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, dvarTimeArrayUsedByLaterCycle, dvarUsedByLaterCycle, dvList, dvMap, dvTimeArrayList, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), and timeArrayDvList.
Referenced by processModel().
processGoal()
void wrimsv2.commondata.wresldata.ModelDataSet.processGoal ()
Definition at line 365 of file ModelDataSet.java.
References wrimsv2.commondata.solverdata.SolverData.clearConstraintDataMap(), wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), gList, gMap, gTimeArrayList, usedWtSlackSurplusDvList, and usedWtSlackSurplusList.
Referenced by processModel().
processModel()
void wrimsv2.commondata.wresldata.ModelDataSet.processModel ()
Definition at line 116 of file ModelDataSet.java.
References processDvar(), processGoal(), processSvar(), processTimeseries(), processWeight(), processWeightSlackSurplus(), resetSlackSurplusWeight(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.components.ControlData.t_dvar, wrimsv2.components.ControlData.t_goal, wrimsv2.components.ControlData.t_svar, wrimsv2.components.ControlData.t_ts, wrimsv2.components.ControlData.t_wt, and wrimsv2.components.ControlData.t_wtss.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
processSvar()
void wrimsv2.commondata.wresldata.ModelDataSet.processSvar ()
Definition at line 174 of file ModelDataSet.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.Svar.caseConditionParsers, wrimsv2.commondata.wresldata.Svar.caseExpressionParsers, wrimsv2.components.IntDouble.copyOf(), wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.TimeArray.getTimeArraySize(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.commondata.wresldata.Svar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, svarUsedByLaterCycle, svFutMap, svList, svMap, wrimsv2.parallel.ParallelVars.timeArrayIndex, and wrimsv2.commondata.wresldata.Svar.timeArraySizeParser.
Referenced by processModel().
processTimeseries()
void wrimsv2.commondata.wresldata.ModelDataSet.processTimeseries ()
Definition at line 336 of file ModelDataSet.java.
References wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, tsList, and tsMap.
Referenced by processModel().
processWeight()
void wrimsv2.commondata.wresldata.ModelDataSet.processWeight ()
Definition at line 149 of file ModelDataSet.java.
References wrimsv2.commondata.solverdata.SolverData.clearWeightMap(), wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wtList, wtMap, and wtTimeArrayList.
Referenced by processModel().
processWeightSlackSurplus()
void wrimsv2.commondata.wresldata.ModelDataSet.processWeightSlackSurplus ()
Definition at line 162 of file ModelDataSet.java.
References wrimsv2.commondata.solverdata.SolverData.clearWeightSlackSurplusMap(), wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), usedWtSlackSurplusDvList, usedWtSlackSurplusList, and wtSlackSurplusMap.
Referenced by processModel().
resetSlackSurplusWeight()
void wrimsv2.commondata.wresldata.ModelDataSet.resetSlackSurplusWeight ()
Definition at line 145 of file ModelDataSet.java.
References usedWtSlackSurplusList.
Referenced by processModel(), and wrimsv2.evaluator.WeightEval.procWt().
Member Data Documentation
aliasUsedByLaterCycle
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.aliasUsedByLaterCycle = new HashSet<String>()
Definition at line 114 of file ModelDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.evaluator.AssignPastCycleVariable.assignAlias(), and processAlias().
asFutMap
Map<String, Alias> wrimsv2.commondata.wresldata.ModelDataSet.asFutMap = new HashMap<String, Alias>()
Definition at line 96 of file ModelDataSet.java.
Referenced by clearFutureAsMap(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), and processAlias().
asList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.asList = new ArrayList<String>()
Definition at line 92 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), processAlias(), and wrimsv2.wreslplus.elements.procedures.ToWreslData.processAlias().
asList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.asList_global = new ArrayList<String>()
Definition at line 93 of file ModelDataSet.java.
asList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.asList_local = new ArrayList<String>()
Definition at line 94 of file ModelDataSet.java.
asMap
Map<String, Alias> wrimsv2.commondata.wresldata.ModelDataSet.asMap = new HashMap<String, Alias>()
Definition at line 95 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.evaluator.AssignPastCycleVariable.assignAlias(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), processAlias(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processAlias(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
asSet_unknown
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.asSet_unknown = new HashSet<String>()
Definition at line 91 of file ModelDataSet.java.
deviationSlackSurplus_toleranceMap
Map<String,Double> wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap = new HashMap<String, Double>()
Definition at line 81 of file ModelDataSet.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
dvarTimeArrayUsedByLaterCycle
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle = new HashSet<String>()
Definition at line 112 of file ModelDataSet.java.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), and processDvar().
dvarUsedByLaterCycle
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle = new HashSet<String>()
Definition at line 111 of file ModelDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.evaluator.AssignPastCycleVariable.assignDvar(), wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), and processDvar().
dvList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.dvList = new ArrayList<String>()
Definition at line 79 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.solver.CbcSolver.loadProblemIIS(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logCbcWatchList(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.solver.ClpSolver.newProblem(), processDvar(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processDvar(), wrimsv2.solver.CbcSolver.reloadProblem(), wrimsv2.solver.CbcSolver.reloadProblemConfirm(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.solver.ortools.Misc.setDVars(), wrimsv2.solver.XASolver.setDVars(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvList_deviationSlackSurplus
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.dvList_deviationSlackSurplus = new ArrayList<String>()
Definition at line 80 of file ModelDataSet.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel().
dvList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.dvList_global = new ArrayList<String>()
Definition at line 85 of file ModelDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.dvList_local = new ArrayList<String>()
Definition at line 86 of file ModelDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvMap
Map<String, Dvar> wrimsv2.commondata.wresldata.ModelDataSet.dvMap = new HashMap<String, Dvar>()
Definition at line 87 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.AssignPastCycleVariable.assignDvar(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), processDvar(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processDvar(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processSsList_noCase(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), and wrimsv2.wreslparser.elements.LogUtils.studySummary_details().
dvSlackSurplusList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusList = new ArrayList<String>()
Definition at line 84 of file ModelDataSet.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvSlackSurplusMap
Map<String, Dvar> wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap = new HashMap<String, Dvar>()
Definition at line 88 of file ModelDataSet.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvTimeArrayList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList = new ArrayList<String>()
Definition at line 82 of file ModelDataSet.java.
Referenced by wrimsv2.solver.CbcSolver.loadProblemIIS(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.solver.ClpSolver.newProblem(), processDvar(), wrimsv2.solver.CbcSolver.reloadProblem(), wrimsv2.solver.CbcSolver.reloadProblemConfirm(), wrimsv2.solver.ortools.Misc.setDVars(), and wrimsv2.solver.XASolver.setDVars().
exList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.exList = new ArrayList<String>()
Definition at line 52 of file ModelDataSet.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), wrimsv2.components.PreRunModel.processExternal(), and wrimsv2.debug.ReProcessExternal.processExternal().
exList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.exList_global = new ArrayList<String>()
Definition at line 53 of file ModelDataSet.java.
exList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.exList_local = new ArrayList<String>()
Definition at line 54 of file ModelDataSet.java.
exMap
Map<String, External> wrimsv2.commondata.wresldata.ModelDataSet.exMap = new HashMap<String, External>()
Definition at line 55 of file ModelDataSet.java.
Referenced by wrimsv2.components.Error.addEvaluationError(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), wrimsv2.components.PreRunModel.processExternal(), and wrimsv2.debug.ReProcessExternal.processExternal().
gList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.gList = new ArrayList<String>()
Definition at line 99 of file ModelDataSet.java.
Referenced by wrimsv2.tools.CheckWeightSlackSurplus.CheckWeightSlackSurplus(), wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), processGoal(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), wrimsv2.solver.CbcSolver.setConstraintsSkip(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
gList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.gList_global = new ArrayList<String>()
Definition at line 101 of file ModelDataSet.java.
gList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.gList_local = new ArrayList<String>()
Definition at line 102 of file ModelDataSet.java.
gMap
Map<String, Goal> wrimsv2.commondata.wresldata.ModelDataSet.gMap = new HashMap<String, Goal>()
Definition at line 103 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.Error.addInfeasibleHint(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.wreslplus.elements.Tools.findGoalLocation(), processGoal(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processGoal(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
gTimeArrayList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList = new ArrayList<String>()
Definition at line 100 of file ModelDataSet.java.
Referenced by processGoal(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), and wrimsv2.solver.CbcSolver.setConstraintsSkip().
incFileList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.incFileList =new ArrayList<String>()
Definition at line 105 of file ModelDataSet.java.
Referenced by wrimsv2.tools.InfeasibilityAnalysis.isStudyInclFile().
incFileList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.incFileList_global =new ArrayList<String>()
Definition at line 106 of file ModelDataSet.java.
incFileList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.incFileList_local =new ArrayList<String>()
Definition at line 107 of file ModelDataSet.java.
serialVersionUID
final long wrimsv2.commondata.wresldata.ModelDataSet.serialVersionUID = 1L static private
Definition at line 38 of file ModelDataSet.java.
svarUsedByLaterCycle
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.svarUsedByLaterCycle = new HashSet<String>()
Definition at line 113 of file ModelDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.evaluator.AssignPastCycleVariable.assignSvar(), and processSvar().
svFutMap
Map<String, Svar> wrimsv2.commondata.wresldata.ModelDataSet.svFutMap = new HashMap<String, Svar>()
Definition at line 76 of file ModelDataSet.java.
Referenced by clearFutureSvMap(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), processSvar(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), and wrimsv2.hdf5.HDF5Util.writeCycleDynamicSv().
svList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.svList = new ArrayList<String>()
Definition at line 72 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.PreEvaluatorTree.PreEvaluatorTree(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.components.DebugInterface.getFutureValueDetail(), processSvar(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processSvar(), wrimsv2.hdf5.HDF5Writer.skipDailyCycleStaticSv(), wrimsv2.hdf5.HDF5Writer.skipMonthlyCycleStaticSv(), wrimsv2.hdf5.HDF5Util.writeCycleStaticSvNames(), wrimsv2.hdf5.HDF5Writer.writeDailyCycleStaticSv(), and wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleStaticSv().
svList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.svList_global = new ArrayList<String>()
Definition at line 73 of file ModelDataSet.java.
svList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.svList_local = new ArrayList<String>()
Definition at line 74 of file ModelDataSet.java.
svMap
Map<String, Svar> wrimsv2.commondata.wresldata.ModelDataSet.svMap = new HashMap<String, Svar>()
Definition at line 75 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.PreEvaluatorTree.PreEvaluatorTree(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.evaluator.AssignPastCycleVariable.assignSvar(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), processSvar(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processSvar(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.hdf5.HDF5Writer.writeDailyCycleStaticSv(), and wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleStaticSv().
svSet_unknown
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.svSet_unknown = new HashSet<String>()
Definition at line 71 of file ModelDataSet.java.
timeArrayDvList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList = new ArrayList<String>()
Definition at line 83 of file ModelDataSet.java.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), and processDvar().
tsList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.tsList = new ArrayList<String>()
Definition at line 65 of file ModelDataSet.java.
Referenced by wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), and processTimeseries().
tsList_global
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.tsList_global = new ArrayList<String>()
Definition at line 66 of file ModelDataSet.java.
tsList_local
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.tsList_local = new ArrayList<String>()
Definition at line 67 of file ModelDataSet.java.
tsMap
Map<String, Timeseries> wrimsv2.commondata.wresldata.ModelDataSet.tsMap = new HashMap<String, Timeseries>()
Definition at line 68 of file ModelDataSet.java.
Referenced by wrimsv2.components.Error.addEvaluationError(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), processTimeseries(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processTimeseries(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
usedWtSlackSurplusDvList
CopyOnWriteArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusDvList = new CopyOnWriteArrayList<String>()
Definition at line 44 of file ModelDataSet.java.
Referenced by processGoal(), and processWeightSlackSurplus().
usedWtSlackSurplusList
CopyOnWriteArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList = new CopyOnWriteArrayList<String>()
Definition at line 43 of file ModelDataSet.java.
Referenced by wrimsv2.tools.CheckWeightSlackSurplus.CheckWeightSlackSurplus(), wrimsv2.ilp.ILP.findActiveWeightMap(), wrimsv2.ilp.ILP.findWeightedDvar(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.ilp.ILP.prepareDvarToWrite(), processGoal(), processWeightSlackSurplus(), resetSlackSurplusWeight(), wrimsv2.solver.ClpSolver.setWeights(), wrimsv2.solver.ortools.Misc.setWeights(), wrimsv2.solver.XASolver.setWeights(), wrimsv2.ilp.AmplWriter.writeDvar(), wrimsv2.ilp.AmplWriter.writeDvarValue(), and wrimsv2.ilp.AmplWriter.writeObj().
varUsedByLaterCycle
Set<String> wrimsv2.commondata.wresldata.ModelDataSet.varUsedByLaterCycle = new HashSet<String>()
Definition at line 109 of file ModelDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles().
wtList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.wtList = new ArrayList<String>()
Definition at line 40 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.WeightEval.collectWt(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), processWeight(), wrimsv2.solver.ClpSolver.setWeights(), wrimsv2.solver.ortools.Misc.setWeights(), wrimsv2.solver.XASolver.setWeights(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
wtMap
Map<String, WeightElement> wrimsv2.commondata.wresldata.ModelDataSet.wtMap = new HashMap<String, WeightElement>()
Definition at line 48 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.WeightEval.collectWt(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processGroupWeight(), wrimsv2.wreslplus.elements.procedures.ToWreslData.processSsWeight_noCase(), processWeight(), and wrimsv2.wreslplus.elements.procedures.ToWreslData.processWeightTableObjList().
wtSlackSurplusList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusList = new ArrayList<String>()
Definition at line 42 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.WeightEval.collectWtSlackSurplus(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
wtSlackSurplusMap
Map<String, WeightElement> wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusMap = new HashMap<String, WeightElement>()
Definition at line 49 of file ModelDataSet.java.
Referenced by wrimsv2.evaluator.PreEvaluator.PreEvaluator(), wrimsv2.evaluator.WeightEval.collectWtSlackSurplus(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertModel(), processWeightSlackSurplus(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
wtTimeArrayList
ArrayList<String> wrimsv2.commondata.wresldata.ModelDataSet.wtTimeArrayList = new ArrayList<String>()
Definition at line 41 of file ModelDataSet.java.
Referenced by wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), processWeight(), wrimsv2.solver.ClpSolver.setWeights(), wrimsv2.solver.ortools.Misc.setWeights(), and wrimsv2.solver.XASolver.setWeights().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/commondata/wresldata/ModelDataSet.java