Wrims-engine: wrimsv2.wreslparser.elements.Tools Class Reference
wrimsv2.wreslparser.elements.Tools Class Reference
Static Public Member Functions
static String add_space_between_logical (String s)
static Map< String, SimulationDataSet > convertSimulationDataSetMapToLocal (Map< String, SimulationDataSet > s)
static SimulationDataSet convertSimulationDataSetToLocal (SimulationDataSet s)
static Set< String > convertStrToSet (String inStr)
static SimulationDataSet correctDataScope_deep (String f, SimulationDataSet ds, Map< String, String > fileScopeMap, Map< String, Set< String > > t1ReverseMap)
static SimulationDataSet correctDataScope_shallow (String f, SimulationDataSet ds, Map< String, String > fileScopeMap, Map< String, Set< String > > t1ReverseMap)
static boolean deleteDir (String dirString)
static Map< String, SimulationDataSet > getAllOffSprings (String nodeFile, Map< String, ArrayList< String > > t1Map, Map< String, SimulationDataSet > fileDataMap)
static Map< String, Set< String > > getCycleVarMap (Set< String > setVarCycle)
static Map< String, String > getFileScopeMap (Map< String, SimulationDataSet > dataMap)
static Map< String, Set< String > > getReverseMap (Map< String, Set< String > > t1Map)
static Map< String, ArrayList< String > > getReverseMap_arrayList (Map< String, ArrayList< String > > t1Map)
static ArrayList< String > getScopeList (ArrayList< String > fileList, ArrayList< String > localList)
static Map< String, String > getScopeMap (Set< String > fileSet, Set< String > localSet)
static Map< String, Set< String > > getType1Map (Map< String, SimulationDataSet > dataMap)
static Map< String, ArrayList< String > > getType1MapScope (Map< String, SimulationDataSet > dataMap)
static Set< String > mapRemoveAll (Map< String, ?> map, ArrayList< String > list)
static Set< String > mapRemoveAll (Map< String, ?> map, Set< String > set)
static PrintWriter openFile (String dirPath, String fileName) throws IOException
static PrintWriter openFile (String dirPath, String fileName, boolean isAppend) throws IOException
static PrintWriter openFile (String filePath) throws IOException
static SimulationDataSet overwrite_set (SimulationDataSet main, SimulationDataSet s)
static Map< String, SimulationDataSet > putDataFileMapFromWholeStudy (String file, Map< String, SimulationDataSet > fileDataMap)
static String readFileAsString (String file, String csName) throws IOException
static String readFileAsString (String filePath)
static String readFileLine (String filePath) throws IOException
static Map< String, String > readFilesFromDirAsMap (String dir) throws IOException
static String remove_nulls (String s)
static Set< String > removeDuplicates (ArrayList< String > list)
static String replace_ignoreChar (String s)
static String replace_pathseperator (String s)
static String replace_regex (String s)
static String replace_seperator (String s)
static Set< String > restoreOrder (ArrayList< String > toBeRestored, ArrayList< String > referenceOrder, Set< String > member)
static PrintWriter setOutputString (String dirPath, String fileName) throws IOException
static String strip (String s)
Detailed Description
Definition at line 25 of file Tools.java.
Member Function Documentation
add_space_between_logical()
String wrimsv2.wreslparser.elements.Tools.add_space_between_logical (String s) static
Definition at line 54 of file Tools.java.
References replace_ignoreChar(), and replace_seperator().
convertSimulationDataSetMapToLocal()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetMapToLocal (Map< String, SimulationDataSet > s) static
Definition at line 207 of file Tools.java.
References convertSimulationDataSetToLocal().
convertSimulationDataSetToLocal()
SimulationDataSet wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal (SimulationDataSet s) static
Definition at line 221 of file Tools.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asList_local, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, wrimsv2.wreslparser.elements.SimulationDataSet.exList, wrimsv2.wreslparser.elements.SimulationDataSet.exList_local, wrimsv2.wreslparser.elements.SimulationDataSet.exMap, wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gList_local, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.SimulationDataSet.incFileMap, wrimsv2.wreslparser.elements.SimulationDataSet.model_list, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.wtList, wrimsv2.wreslparser.elements.SimulationDataSet.wtList_local, and wrimsv2.wreslparser.elements.SimulationDataSet.wtMap.
Referenced by convertSimulationDataSetMapToLocal(), and wrimsv2.wreslparser.elements.FileParser.processFileIntoSimulationDataSet().
convertStrToSet()
Set< String > wrimsv2.wreslparser.elements.Tools.convertStrToSet (String inStr) static
Definition at line 531 of file Tools.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
correctDataScope_deep()
SimulationDataSet wrimsv2.wreslparser.elements.Tools.correctDataScope_deep (String f, SimulationDataSet ds, Map< String, String > fileScopeMap, Map< String, Set< String > > t1ReverseMap) static
Definition at line 436 of file Tools.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.convertToLocal_set(), correctDataScope_deep(), and wrimsv2.commondata.wresldata.Param.local.
Referenced by correctDataScope_deep(), and wrimsv2.wreslparser.elements.StudyParser.correctScopeAndPrioritize().
correctDataScope_shallow()
SimulationDataSet wrimsv2.wreslparser.elements.Tools.correctDataScope_shallow (String f, SimulationDataSet ds, Map< String, String > fileScopeMap, Map< String, Set< String > > t1ReverseMap) static
Definition at line 408 of file Tools.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.convertToLocal_set(), and wrimsv2.commondata.wresldata.Param.local.
deleteDir()
boolean wrimsv2.wreslparser.elements.Tools.deleteDir (String dirString) static
Definition at line 192 of file Tools.java.
References deleteDir().
Referenced by deleteDir(), and wrimsv2.wreslparser.elements.WriteCSV.study().
getAllOffSprings()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.Tools.getAllOffSprings (String nodeFile, Map< String, ArrayList< String > > t1Map, Map< String, SimulationDataSet > fileDataMap) static
Definition at line 476 of file Tools.java.
References getAllOffSprings().
Referenced by getAllOffSprings().
getCycleVarMap()
Map< String, Set< String > > wrimsv2.wreslparser.elements.Tools.getCycleVarMap (Set< String > setVarCycle) static
Definition at line 575 of file Tools.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycle_subfunction().
getFileScopeMap()
Map< String, String > wrimsv2.wreslparser.elements.Tools.getFileScopeMap (Map< String, SimulationDataSet > dataMap) static
Definition at line 371 of file Tools.java.
References getScopeMap(), wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet, and wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet_local.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
getReverseMap()
Map< String, Set< String > > wrimsv2.wreslparser.elements.Tools.getReverseMap (Map< String, Set< String > > t1Map) static
type 1 map is the shallow included files, e.g., map(f1, [f7,f9])
Definition at line 327 of file Tools.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.correctScopeAndPrioritize(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
getReverseMap_arrayList()
Map< String, ArrayList< String > > wrimsv2.wreslparser.elements.Tools.getReverseMap_arrayList (Map< String, ArrayList< String > > t1Map) static
type 1 map is the shallow included files, e.g., map(f1, [f7,f9])
Definition at line 351 of file Tools.java.
getScopeList()
ArrayList< String > wrimsv2.wreslparser.elements.Tools.getScopeList (ArrayList< String > fileList, ArrayList< String > localList) static
Definition at line 277 of file Tools.java.
getScopeMap()
Map< String, String > wrimsv2.wreslparser.elements.Tools.getScopeMap (Set< String > fileSet, Set< String > localSet) static
Definition at line 293 of file Tools.java.
References wrimsv2.commondata.wresldata.Param.global, and wrimsv2.commondata.wresldata.Param.local.
Referenced by wrimsv2.wreslparser.elements.StudyParser.correctScopeAndPrioritize(), and getFileScopeMap().
getType1Map()
Map< String, Set< String > > wrimsv2.wreslparser.elements.Tools.getType1Map (Map< String, SimulationDataSet > dataMap) static
type 1 map is the shallow included files, e.g., map(f1, [f7,f9])
Definition at line 310 of file Tools.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
getType1MapScope()
Map< String, ArrayList< String > > wrimsv2.wreslparser.elements.Tools.getType1MapScope (Map< String, SimulationDataSet > dataMap) static
type 1 map is the scope list for the shallow included files, e.g., map(f1, [f7 scope ,f9 scope])
Definition at line 387 of file Tools.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, and wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local.
mapRemoveAll() [1/2]
Set< String > wrimsv2.wreslparser.elements.Tools.mapRemoveAll (Map< String, ?> map, ArrayList< String > list) static
Definition at line 517 of file Tools.java.
References mapRemoveAll().
mapRemoveAll() [2/2]
Set< String > wrimsv2.wreslparser.elements.Tools.mapRemoveAll (Map< String, ?> map, Set< String > set) static
Definition at line 507 of file Tools.java.
Referenced by mapRemoveAll(), wrimsv2.wreslparser.elements.SimulationDataSet.overwrite_set(), wrimsv2.wreslparser.elements.SimulationDataSet.remove(), and wrimsv2.wreslparser.elements.SimulationDataSet.remove_set().
openFile() [1/3]
PrintWriter wrimsv2.wreslparser.elements.Tools.openFile (String dirPath, String fileName) throws IOException static
Definition at line 172 of file Tools.java.
openFile() [2/3]
PrintWriter wrimsv2.wreslparser.elements.Tools.openFile (String dirPath, String fileName, boolean isAppend) throws IOException static
Definition at line 162 of file Tools.java.
openFile() [3/3]
PrintWriter wrimsv2.wreslparser.elements.Tools.openFile (String filePath) throws IOException static
Definition at line 152 of file Tools.java.
Referenced by wrimsv2.ilp.ILP.createNoteFile(), wrimsv2.wreslparser.elements.WriteCSV.dataset(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.ilp.ILP.reOpenCplexLpFile(), wrimsv2.components.ControllerBatch.runModelGurobiTest(), wrimsv2.ilp.ILP.saveCplexLpStringToFile(), wrimsv2.ilp.ILP.setAmplFile(), wrimsv2.ilp.ILP.setCplexLpFile(), wrimsv2.ilp.ILP.setDvarFile(), wrimsv2.wreslparser.elements.LogUtils.setLogFile(), wrimsv2.wreslparser.elements.LogUtils.setLogFile(), wrimsv2.ilp.ILP.setLpSolveFile(), wrimsv2.ilp.ILP.setObjValueFile(), wrimsv2.ilp.ILP.setSvarFile(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.wreslparser.elements.WriteCSV.study(), wrimsv2.wreslparser.elements.WriteCSV.study(), wrimsv2.solver.mpmodel.MPModelUtils.toLpSolve(), and wrimsv2.components.Error.writeErrorLog().
overwrite_set()
SimulationDataSet wrimsv2.wreslparser.elements.Tools.overwrite_set (SimulationDataSet main, SimulationDataSet s) static
Definition at line 522 of file Tools.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.add(), and wrimsv2.wreslparser.elements.SimulationDataSet.overwrittenWith_set().
putDataFileMapFromWholeStudy()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.Tools.putDataFileMapFromWholeStudy (String file, Map< String, SimulationDataSet > fileDataMap) static
Definition at line 490 of file Tools.java.
References putDataFileMapFromWholeStudy().
Referenced by wrimsv2.wreslparser.elements.StudyParser.copyDataSetToThisModel(), and putDataFileMapFromWholeStudy().
readFileAsString() [1/2]
String wrimsv2.wreslparser.elements.Tools.readFileAsString (String file, String csName) throws IOException static
Definition at line 121 of file Tools.java.
readFileAsString() [2/2]
String wrimsv2.wreslparser.elements.Tools.readFileAsString (String filePath) static
Definition at line 98 of file Tools.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg().
Referenced by readFilesFromDirAsMap().
readFileLine()
String wrimsv2.wreslparser.elements.Tools.readFileLine (String filePath) throws IOException static
Definition at line 145 of file Tools.java.
readFilesFromDirAsMap()
Map< String, String > wrimsv2.wreslparser.elements.Tools.readFilesFromDirAsMap (String dir) throws IOException static
Definition at line 78 of file Tools.java.
References readFileAsString().
Referenced by wrimsv2.wreslparser.elements.Comparison.compareFolder().
remove_nulls()
String wrimsv2.wreslparser.elements.Tools.remove_nulls (String s) static
Definition at line 41 of file Tools.java.
removeDuplicates()
Set< String > wrimsv2.wreslparser.elements.Tools.removeDuplicates (ArrayList< String > list) static
Definition at line 559 of file Tools.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
replace_ignoreChar()
String wrimsv2.wreslparser.elements.Tools.replace_ignoreChar (String s) static
Definition at line 47 of file Tools.java.
Referenced by add_space_between_logical().
replace_pathseperator()
String wrimsv2.wreslparser.elements.Tools.replace_pathseperator (String s) static
Definition at line 72 of file Tools.java.
References wrimsv2.commondata.wresldata.Param.linux_pathseperator, and wrimsv2.commondata.wresldata.Param.windows_pathseperator.
Referenced by wrimsv2.wreslparser.elements.StructTree.includeFile().
replace_regex()
String wrimsv2.wreslparser.elements.Tools.replace_regex (String s) static
Definition at line 30 of file Tools.java.
replace_seperator()
String wrimsv2.wreslparser.elements.Tools.replace_seperator (String s) static
Definition at line 67 of file Tools.java.
References wrimsv2.commondata.wresldata.Param.arg_seperator, and wrimsv2.commondata.wresldata.Param.new_seperator.
Referenced by add_space_between_logical().
restoreOrder()
Set< String > wrimsv2.wreslparser.elements.Tools.restoreOrder (ArrayList< String > toBeRestored, ArrayList< String > referenceOrder, Set< String > member) static
Definition at line 544 of file Tools.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
setOutputString()
PrintWriter wrimsv2.wreslparser.elements.Tools.setOutputString (String dirPath, String fileName) throws IOException static
Definition at line 182 of file Tools.java.
strip()
String wrimsv2.wreslparser.elements.Tools.strip (String s) static
Definition at line 26 of file Tools.java.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/Tools.java