Wrims-engine: wrimsv2.solver.CbcSolver Class Reference
wrimsv2.solver.CbcSolver Class Reference
Static Public Member Functions
static void addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String dvName, boolean isNoteCbc, String append)
static void close ()
static double getObjValue ()
static void init (boolean useLpFile, StudyDataSet sds)
static void logCbcDebug (StudyDataSet sds)
static void logCbcWatchList (StudyDataSet sds)
static void logIntCheck (StudyDataSet sds)
static void main (String argv[])
static void newProblem ()
static void reloadAndWriteLp (String nameAppend, boolean logCbc)
static void reloadAndWriteLp (String nameAppend, boolean logMps, boolean logCbc)
static void resetModel ()
static int[] solve ()
static int[] solve_jCbc2021 ()
static int[] solve_jCbc2021a ()
static boolean violationCheck (SWIGTYPE_p_CbcModel model, String modelName, String solveName)
static void writeCbcLp (String nameAppend, boolean logMps)
Static Public Attributes
static double cbcHintRelaxPenalty = 9000
static int cbcHintTimeMax = 100
static String cbcLibName = "jCbc"
static int cbcLogStartDate = 999900
static int cbcLogStopDate = 999900
static boolean cbcSolutionRounding = true
static String cbcVersion = "None"
static boolean cbcViolationCheck = true
static boolean cbcViolationRetry = true
static final double cbcWriteLpEpsilon = 1e-15
static boolean debugDeviation = false
static boolean debugDeviationFindMissing = false
static double debugDeviationMin = 200
static double debugDeviationWeightMin = 99000
static double debugDeviationWeightMultiply = 100
static boolean debugDeviationWriteWarning = false
static boolean debugObjDiff = false
static double debugObjDiff_tolerance = 1E5
static double integerT = 1e-9
static double integerT_check = 1e-8
static boolean intLog =true
static boolean intViolation =false
static double log_if_obj_diff = 500.0
static boolean logObj =true
static Double lowerBoundZero_check = null
static double maxObjDiff =0
static String maxObjDiff_id =""
static double maxObjDiff_minus =0
static String maxObjDiff_minus_id =""
static Set< String > prioritizeSearchTheseConstraints
static double record_if_obj_diff = 10000.0
static final int solv2 = 20
static final int solv3 = 30
static final int solvCallCbc = 50
static double solve_2_primalT = 1e-9
static double solve_2_primalT_relax = 1e-7
static final HashMap< Integer, String > solve_u_ret
static double solve_whs_primalT = 1e-9
static String solveName =""
static final int solvFull = 90
static int solvFunc = 90
static final int solvU = 100
static boolean usejCbc2021 = false
static boolean usejCbc2021a = false
static LinkedHashMap< String, Double > varDoubleMap
static int warm_2nd_solvFunc = 20
static boolean whsSafe = false
static boolean whsScaling = true
Private Member Functions
CbcSolver ()
Static Private Member Functions
static void assignDvar ()
static void callCbc ()
static void callCbc (String solvName)
static void callCbc_R ()
static void collectDvar ()
static void collectDvar2021 ()
static LinkedHashMap< String, Double > collectDvar2021_simple ()
static void getSolverInformation (int status, int status2)
static void iis ()
static boolean iisSolve (boolean isFirstTimeRun, Set< String > enforceThisConstraint)
static boolean iisSolveConfirm (String skipThisConstraint)
static void loadProblemIIS (boolean isFirstTimeRun, Set< String > enforceThisConstraint)
static void logIntVars (String label)
static void note_msg (String msg)
static void reloadProblem (boolean isNoteCbc, String append)
static void reloadProblemConfirm (String skipThisConstraint)
static void setConstraints (boolean isNoteCbc, String append)
static void setConstraintsIIS (boolean firstTimeRun, Set< String > enforceThisConstraint)
static void setConstraintsSkip (String skipThisConstraint)
static void setDVars (boolean isNoteCbc, String append)
static void setDVars2021 (boolean isNoteCbc)
static void setDVarsIIS ()
static int solve_2 ()
static int solve_2 (double priT, String solvName)
static void solve_3 ()
Static Private Attributes
static Set< String > _pstc
static Map< String, Dvar > dvarMap
static BiMap< Integer, String > dvBiMap
static ArrayList< String > dvBiMapArray
static BiMap< String, Integer > dvBiMapInverse
static LinkedHashMap< String, Integer > dvIntMap
static LinkedHashMap< String, Integer > dvIntMap2021
static ArrayList< String > dvIntPredict
static double elements []
static boolean hasPriorityConstraints = false
static Set< String > iisConfirmConstraint
static LinkedHashMap< String, double[]> iisConstraintElementMap
static LinkedHashMap< String, int[]> iisConstraintIndexMap
static LinkedHashMap< String, Double > iisConstraintRHSMap
static LinkedHashMap< String, String > iisConstraintSignMap
static Map< String, String > iisPossibleConstraintMap
static Map< String, String > iisPossibleConstraintMap_cumulative
static LinkedHashMap< Integer, String > iisSlackMap
static ArrayList< String > iisSlacks
static int index []
static int intSolSize =0
static int intSolSize_eachTS =0
static int intVarSize = -99
static boolean isLogging = false
static double maxValue = 1e28
static SWIGTYPE_p_CbcModel model
static String modelName
static SWIGTYPE_p_CoinModel modelObject
static SWIGTYPE_p_std__string names
static SWIGTYPE_p_std__string names_dummy
static SWIGTYPE_p_std__string names_eachTS
static boolean next_possible_stuck =false
static HashSet originalDvarKeys =null
static final boolean saveIntVars =true
static boolean saveWarm =false
static final double solve_3_primalT = 1e-9
static SWIGTYPE_p_OsiClpSolverInterface solver
static int total_relaxed_constraints = 0
static boolean useLpFile =false
static boolean useWarm =false
static SWIGTYPE_p_int values
static SWIGTYPE_p_int values_dummy
static SWIGTYPE_p_int values_eachTS
static boolean warmArrayExist = false
static boolean warmArrayExist_eachTS = false
static Map< String, WeightElement > wm2
Detailed Description
Definition at line 45 of file CbcSolver.java.
Constructor & Destructor Documentation
CbcSolver()
wrimsv2.solver.CbcSolver.CbcSolver () private
Definition at line 174 of file CbcSolver.java.
Referenced by iis(), iisSolve(), iisSolveConfirm(), init(), logCbcDebug(), logCbcWatchList(), logIntCheck(), newProblem(), and reloadAndWriteLp().
Member Function Documentation
addConditionalSlackSurplusToDvarMap()
void wrimsv2.solver.CbcSolver.addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String dvName, boolean isNoteCbc, String append) static
Definition at line 1879 of file CbcSolver.java.
References dvarMap, wrimsv2.commondata.wresldata.Dvar.integer, maxValue, modelName, modelObject, solveName, wm2, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by setConstraints(), setConstraintsIIS(), and setConstraintsSkip().
assignDvar()
void wrimsv2.solver.CbcSolver.assignDvar () static private
Definition at line 1772 of file CbcSolver.java.
References wrimsv2.components.ControlData.clp_cbc_objective, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, dvarMap, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, maxValue, modelName, wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and varDoubleMap.
Referenced by newProblem().
callCbc() [1/2]
void wrimsv2.solver.CbcSolver.callCbc () static private
Definition at line 2169 of file CbcSolver.java.
References callCbc().
Referenced by callCbc(), iisSolve(), iisSolveConfirm(), newProblem(), solve(), and solve_jCbc2021().
callCbc() [2/2]
void wrimsv2.solver.CbcSolver.callCbc (String solvName) static private
Definition at line 2173 of file CbcSolver.java.
References model, and solveName.
callCbc_R()
void wrimsv2.solver.CbcSolver.callCbc_R () static private
Definition at line 2182 of file CbcSolver.java.
References model, and solveName.
Referenced by solve_jCbc2021().
close()
void wrimsv2.solver.CbcSolver.close () static
Definition at line 215 of file CbcSolver.java.
Referenced by wrimsv2.solver.CloseCurrentSolver.CloseCurrentSolver(), wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), and wrimsv2.components.ControllerBatch.runModelILP().
collectDvar()
void wrimsv2.solver.CbcSolver.collectDvar () static private
Definition at line 1699 of file CbcSolver.java.
References dvIntMap, model, saveIntVars, saveWarm, wrimsv2.components.ControlData.showRunTimeMessage, solver, useWarm, and varDoubleMap.
Referenced by newProblem().
collectDvar2021()
void wrimsv2.solver.CbcSolver.collectDvar2021 () static private
Definition at line 1729 of file CbcSolver.java.
References dvIntMap, dvIntMap2021, model, wrimsv2.components.ControlData.showRunTimeMessage, solver, and varDoubleMap.
Referenced by newProblem().
collectDvar2021_simple()
LinkedHashMap< String, Double > wrimsv2.solver.CbcSolver.collectDvar2021_simple () static private
Definition at line 1759 of file CbcSolver.java.
References model.
Referenced by newProblem().
getObjValue()
double wrimsv2.solver.CbcSolver.getObjValue () static
Definition at line 551 of file CbcSolver.java.
References model.
Referenced by newProblem().
getSolverInformation()
void wrimsv2.solver.CbcSolver.getSolverInformation (int status, int status2) static private
Definition at line 677 of file CbcSolver.java.
References wrimsv2.components.Error.addSolvingError().
Referenced by solve(), solve_jCbc2021(), and solve_jCbc2021a().
iis()
void wrimsv2.solver.CbcSolver.iis () static private
Definition at line 1498 of file CbcSolver.java.
References CbcSolver(), _pstc, wrimsv2.tools.InfeasibilityAnalysis.constraintSet, hasPriorityConstraints, iisConfirmConstraint, iisConstraintElementMap, iisConstraintIndexMap, iisConstraintRHSMap, iisConstraintSignMap, iisPossibleConstraintMap, iisPossibleConstraintMap_cumulative, iisSlacks, iisSolve(), iisSolveConfirm(), prioritizeSearchTheseConstraints, wrimsv2.tools.InfeasibilityAnalysis.procIfsFile(), and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by solve(), solve_jCbc2021(), and solve_jCbc2021a().
iisSolve()
boolean wrimsv2.solver.CbcSolver.iisSolve (boolean isFirstTimeRun, Set< String > enforceThisConstraint) static private
Definition at line 1630 of file CbcSolver.java.
References CbcSolver(), callCbc(), dvBiMap, iisConstraintElementMap, iisConstraintIndexMap, iisConstraintRHSMap, iisConstraintSignMap, iisPossibleConstraintMap, iisSlackMap, index, loadProblemIIS(), model, and solver.
Referenced by iis().
iisSolveConfirm()
boolean wrimsv2.solver.CbcSolver.iisSolveConfirm (String skipThisConstraint) static private
Definition at line 1607 of file CbcSolver.java.
References CbcSolver(), callCbc(), model, reloadProblemConfirm(), and solver.
Referenced by iis().
init()
void wrimsv2.solver.CbcSolver.init (boolean useLpFile, StudyDataSet sds) static
Definition at line 176 of file CbcSolver.java.
References CbcSolver(), wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, cbcSolutionRounding, cbcVersion, cbcViolationCheck, wrimsv2.ilp.ILP.createNoteFile(), dvBiMap, dvBiMapArray, dvIntMap, dvIntMap2021, wrimsv2.ilp.ILP.getIlpDir(), lowerBoundZero_check, names_dummy, solve_2_primalT_relax, usejCbc2021, usejCbc2021a, useLpFile, values_dummy, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.DebugInterface.setSolverOptions().
loadProblemIIS()
void wrimsv2.solver.CbcSolver.loadProblemIIS (boolean isFirstTimeRun, Set< String > enforceThisConstraint) static private
Definition at line 626 of file CbcSolver.java.
References wrimsv2.components.ControlData.currModelDataSet, dvBiMap, dvBiMapInverse, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), iisSlackMap, model, modelName, modelObject, originalDvarKeys, setConstraintsIIS(), setDVarsIIS(), and solver.
Referenced by iisSolve().
logCbcDebug()
void wrimsv2.solver.CbcSolver.logCbcDebug (StudyDataSet sds) static
Definition at line 1993 of file CbcSolver.java.
References CbcSolver(), wrimsv2.ilp.ILP._noteFile_cbc_int, wrimsv2.ilp.ILP._noteFile_cbc_obj, wrimsv2.ilp.ILP._noteFile_xa_int, wrimsv2.ilp.ILP._noteFile_xa_obj, wrimsv2.ilp.ILP._watchFile_cbc, wrimsv2.ilp.ILP._watchFile_xa, wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, wrimsv2.components.ControlData.clp_cbc_objective, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.ilp.ILP.findDvarEffective(), wrimsv2.components.Error.getTotalError(), wrimsv2.ilp.ILP.getYearMonthCycle(), maxObjDiff, maxObjDiff_id, maxObjDiff_minus, maxObjDiff_minus_id, wrimsv2.ilp.ILP.setDvarFile(), wrimsv2.components.ControlData.watchList, wrimsv2.components.ControlData.watchList_tolerance, wrimsv2.ilp.ILP.writeDvarValue_Clp0_Cbc0(), wrimsv2.ilp.ILP.writeDvarValue_XA(), wrimsv2.ilp.ILP.writeNoteLn(), and wrimsv2.components.ControlData.xasolver.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), and wrimsv2.components.ControllerDebug.runModelSolvers().
logCbcWatchList()
void wrimsv2.solver.CbcSolver.logCbcWatchList (StudyDataSet sds) static
Definition at line 1963 of file CbcSolver.java.
References CbcSolver(), wrimsv2.ilp.ILP._watchFile_cbc, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.ilp.ILP.getYearMonthCycle(), wrimsv2.components.ControlData.watchList, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), and wrimsv2.components.ControllerDebug.runModelSolvers().
logIntCheck()
void wrimsv2.solver.CbcSolver.logIntCheck (StudyDataSet sds) static
Definition at line 2187 of file CbcSolver.java.
References CbcSolver(), wrimsv2.ilp.ILP._noteFile_cbc_int_log, wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.components.Error.getTotalError(), wrimsv2.ilp.ILP.getYearMonthCycle(), and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
logIntVars()
void wrimsv2.solver.CbcSolver.logIntVars (String label) static private
Definition at line 1949 of file CbcSolver.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, and dvIntMap.
Referenced by reloadAndWriteLp(), reloadAndWriteLp(), and writeCbcLp().
main()
void wrimsv2.solver.CbcSolver.main (String argv[]) static
Definition at line 2088 of file CbcSolver.java.
References cbcLibName, model, and solver.
newProblem()
void wrimsv2.solver.CbcSolver.newProblem () static
Definition at line 219 of file CbcSolver.java.
References CbcSolver(), wrimsv2.ilp.ILP._noteFile_cbc_obj, wrimsv2.ilp.ILP._noteFile_cbc_time, wrimsv2.components.Error.addSolvingError(), wrimsv2.components.ControlData.adTime, assignDvar(), callCbc(), wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.components.ControlData.cbcLogNativeLp, cbcLogStartDate, cbcLogStopDate, cbcSolutionRounding, cbcViolationCheck, wrimsv2.components.ControlData.cdTime, wrimsv2.components.ControlData.clp_cbc_objective, collectDvar(), collectDvar2021(), collectDvar2021_simple(), wrimsv2.ilp.ILP.cplexLpFilePath, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycWarmStart, wrimsv2.components.ControlData.cycWarmUse, debugDeviation, debugDeviationFindMissing, debugDeviationMin, debugDeviationWeightMin, debugDeviationWeightMultiply, debugDeviationWriteWarning, debugObjDiff, debugObjDiff_tolerance, dvarMap, dvBiMap, dvBiMapArray, dvBiMapInverse, dvIntMap, dvIntPredict, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.components.Error.error_solving, wrimsv2.ilp.ILP.findDvarEffective(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), getObjValue(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), wrimsv2.ilp.ILP.getYearMonthCycle(), integerT, integerT_check, intSolSize, isLogging, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, lowerBoundZero_check, model, modelName, modelObject, names, note_msg(), originalDvarKeys, reloadAndWriteLp(), reloadProblem(), saveWarm, setConstraints(), setDVars(), setDVars2021(), wrimsv2.commondata.wresldata.WeightElement.setValue(), wrimsv2.ilp.ILP.setVarFile(), solve(), solve_jCbc2021(), solve_jCbc2021a(), solve_whs_primalT, solveName, solver, wrimsv2.components.ControlData.solverCreationTime_cbc, wrimsv2.components.ControlData.solverTime_cbc_this, wrimsv2.components.ControlData.t_cbc, wrimsv2.components.ControlData.useCbcWarmStart, usejCbc2021, usejCbc2021a, useLpFile, useWarm, values, varDoubleMap, wrimsv2.components.ControlData.watchList, wm2, writeCbcLp(), wrimsv2.ilp.ILP.writeDvarValue_Clp0_Cbc0(), wrimsv2.ilp.ILP.writeNoteLn(), and wrimsv2.ilp.ILP.writeSvarValue().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
note_msg()
void wrimsv2.solver.CbcSolver.note_msg (String msg) static private
Definition at line 2142 of file CbcSolver.java.
References solver, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
reloadAndWriteLp() [1/2]
void wrimsv2.solver.CbcSolver.reloadAndWriteLp (String nameAppend, boolean logCbc) static
Definition at line 1925 of file CbcSolver.java.
References cbcWriteLpEpsilon, wrimsv2.ilp.ILP.getIlpDir(), logIntVars(), model, modelName, reloadProblem(), and solveName.
reloadAndWriteLp() [2/2]
void wrimsv2.solver.CbcSolver.reloadAndWriteLp (String nameAppend, boolean logMps, boolean logCbc) static
Definition at line 1903 of file CbcSolver.java.
References CbcSolver(), cbcWriteLpEpsilon, wrimsv2.ilp.ILP.getIlpDir(), logIntVars(), model, modelName, reloadProblem(), solveName, wrimsv2.ilp.ILP.writeNoteLn(), and wrimsv2.components.ControlData.zeroTolerance.
Referenced by newProblem(), wrimsv2.components.ControllerSG.runModelCbc(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
reloadProblem()
void wrimsv2.solver.CbcSolver.reloadProblem (boolean isNoteCbc, String append) static private
Definition at line 555 of file CbcSolver.java.
References wrimsv2.components.ControlData.currModelDataSet, dvBiMap, dvBiMapArray, dvBiMapInverse, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), model, modelName, modelObject, originalDvarKeys, setConstraints(), setDVars(), and solver.
Referenced by newProblem(), reloadAndWriteLp(), reloadAndWriteLp(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
reloadProblemConfirm()
void wrimsv2.solver.CbcSolver.reloadProblemConfirm (String skipThisConstraint) static private
Definition at line 594 of file CbcSolver.java.
References wrimsv2.components.ControlData.currModelDataSet, dvBiMap, dvBiMapInverse, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), model, modelName, modelObject, originalDvarKeys, setConstraintsSkip(), setDVarsIIS(), and solver.
Referenced by iisSolveConfirm().
resetModel()
void wrimsv2.solver.CbcSolver.resetModel () static
Definition at line 663 of file CbcSolver.java.
References dvBiMap, dvBiMapArray, dvBiMapInverse, model, modelObject, and useLpFile.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
setConstraints()
void wrimsv2.solver.CbcSolver.setConstraints (boolean isNoteCbc, String append) static private
Definition at line 713 of file CbcSolver.java.
References addConditionalSlackSurplusToDvarMap(), wrimsv2.components.ControlData.currModelDataSet, dvarMap, dvBiMap, dvBiMapArray, dvBiMapInverse, elements, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList, index, maxValue, modelName, modelObject, wrimsv2.components.ControlData.showRunTimeMessage, solveName, solver, and wrimsv2.components.ControlData.zeroTolerance.
Referenced by newProblem(), and reloadProblem().
setConstraintsIIS()
void wrimsv2.solver.CbcSolver.setConstraintsIIS (boolean firstTimeRun, Set< String > enforceThisConstraint) static private
Definition at line 889 of file CbcSolver.java.
References _pstc, addConditionalSlackSurplusToDvarMap(), cbcHintRelaxPenalty, wrimsv2.components.ControlData.currModelDataSet, dvarMap, dvBiMap, dvBiMapInverse, elements, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList, hasPriorityConstraints, iisConstraintElementMap, iisConstraintIndexMap, iisConstraintRHSMap, iisConstraintSignMap, iisSlackMap, index, maxValue, modelObject, solver, total_relaxed_constraints, wrimsv2.ilp.ILP.writeNoteLn(), and wrimsv2.components.ControlData.zeroTolerance.
Referenced by loadProblemIIS().
setConstraintsSkip()
void wrimsv2.solver.CbcSolver.setConstraintsSkip (String skipThisConstraint) static private
Definition at line 807 of file CbcSolver.java.
References addConditionalSlackSurplusToDvarMap(), wrimsv2.components.ControlData.currModelDataSet, dvarMap, dvBiMap, dvBiMapInverse, elements, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList, index, maxValue, modelObject, solver, and wrimsv2.components.ControlData.zeroTolerance.
Referenced by reloadProblemConfirm().
setDVars()
void wrimsv2.solver.CbcSolver.setDVars (boolean isNoteCbc, String append) static private
Definition at line 1009 of file CbcSolver.java.
References dvarMap, dvBiMap, dvBiMapArray, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, modelName, modelObject, wrimsv2.components.ControlData.showRunTimeMessage, solveName, wrimsv2.commondata.wresldata.Dvar.upperBoundValue, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by newProblem(), and reloadProblem().
setDVars2021()
void wrimsv2.solver.CbcSolver.setDVars2021 (boolean isNoteCbc) static private
Definition at line 1037 of file CbcSolver.java.
References dvarMap, dvBiMap, dvBiMapArray, dvIntMap2021, dvIntPredict, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.wresldata.Dvar.integer, intVarSize, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, modelName, modelObject, wrimsv2.components.ControlData.showRunTimeMessage, solveName, wrimsv2.commondata.wresldata.Dvar.upperBoundValue, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by newProblem().
setDVarsIIS()
void wrimsv2.solver.CbcSolver.setDVarsIIS () static private
Definition at line 1084 of file CbcSolver.java.
References dvarMap, dvBiMap, wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, modelObject, wrimsv2.commondata.wresldata.Dvar.upperBoundValue, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by loadProblemIIS(), and reloadProblemConfirm().
solve()
int[] wrimsv2.solver.CbcSolver.solve () static
Definition at line 1096 of file CbcSolver.java.
References callCbc(), cbcViolationRetry, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, dvIntMap, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), getSolverInformation(), iis(), integerT, integerT_check, intSolSize, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, lowerBoundZero_check, model, modelName, names, note_msg(), reloadAndWriteLp(), reloadProblem(), saveWarm, wrimsv2.components.ControlData.showRunTimeMessage, solv2, solv3, solvCallCbc, solve_2(), solve_2_primalT, solve_2_primalT_relax, solve_3(), solve_3_primalT, solve_u_ret, solve_whs_primalT, solveName, solver, wrimsv2.components.ControlData.solverTime_cbc, wrimsv2.components.ControlData.solverTime_cbc_this, solvFull, solvFunc, solvU, useWarm, values, warm_2nd_solvFunc, warmArrayExist, wrimsv2.components.ControlData.writeCbcSolvingTime, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by newProblem().
solve_2() [1/2]
int wrimsv2.solver.CbcSolver.solve_2 () static private
Definition at line 2147 of file CbcSolver.java.
References solve_2(), and solve_2_primalT.
Referenced by solve(), solve_2(), and solve_jCbc2021().
solve_2() [2/2]
int wrimsv2.solver.CbcSolver.solve_2 (double priT, String solvName) static private
Definition at line 2153 of file CbcSolver.java.
References integerT, model, solveName, and solver.
solve_3()
void wrimsv2.solver.CbcSolver.solve_3 () static private
Definition at line 2162 of file CbcSolver.java.
References integerT, model, solve_3_primalT, solveName, and solver.
Referenced by solve().
solve_jCbc2021()
int[] wrimsv2.solver.CbcSolver.solve_jCbc2021 () static
Definition at line 1347 of file CbcSolver.java.
References callCbc(), callCbc_R(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, dvIntMap, getSolverInformation(), iis(), integerT, intSolSize, isLogging, model, modelName, names, note_msg(), reloadAndWriteLp(), reloadProblem(), saveWarm, wrimsv2.components.ControlData.showRunTimeMessage, solve_2(), solve_2_primalT_relax, solve_whs_primalT, solveName, solver, wrimsv2.components.ControlData.solverTime_cbc, wrimsv2.components.ControlData.solverTime_cbc_this, useWarm, values, violationCheck(), warmArrayExist, wrimsv2.components.ControlData.writeCbcSolvingTime, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by newProblem().
solve_jCbc2021a()
int[] wrimsv2.solver.CbcSolver.solve_jCbc2021a () static
Definition at line 2258 of file CbcSolver.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, dvIntMap, getSolverInformation(), iis(), integerT, intSolSize, model, names, note_msg(), reloadAndWriteLp(), reloadProblem(), saveWarm, wrimsv2.components.ControlData.showRunTimeMessage, solve_whs_primalT, solveName, solver, wrimsv2.components.ControlData.solverTime_cbc, wrimsv2.components.ControlData.solverTime_cbc_this, useWarm, values, warmArrayExist, wrimsv2.components.ControlData.writeCbcSolvingTime, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by newProblem().
violationCheck()
boolean wrimsv2.solver.CbcSolver.violationCheck (SWIGTYPE_p_CbcModel model, String modelName, String solveName) static
Definition at line 2225 of file CbcSolver.java.
References cbcViolationCheck, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), integerT_check, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, lowerBoundZero_check, model, modelName, solveName, and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by solve_jCbc2021().
writeCbcLp()
void wrimsv2.solver.CbcSolver.writeCbcLp (String nameAppend, boolean logMps) static
Definition at line 1936 of file CbcSolver.java.
References cbcWriteLpEpsilon, wrimsv2.ilp.ILP.getIlpDir(), logIntVars(), model, modelName, and solveName.
Referenced by newProblem().
Member Data Documentation
_pstc
Set<String> wrimsv2.solver.CbcSolver._pstc static private
Definition at line 58 of file CbcSolver.java.
Referenced by iis(), and setConstraintsIIS().
cbcHintRelaxPenalty
double wrimsv2.solver.CbcSolver.cbcHintRelaxPenalty = 9000 static
Definition at line 69 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.launch.SettingPref.loadCBCSetting(), wrimsv2.config.ConfigUtils.loadConfig(), and setConstraintsIIS().
cbcHintTimeMax
int wrimsv2.solver.CbcSolver.cbcHintTimeMax = 100 static
Definition at line 91 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.launch.SettingPref.loadCBCSetting(), and wrimsv2.config.ConfigUtils.loadConfig().
cbcLibName
String wrimsv2.solver.CbcSolver.cbcLibName = "jCbc" static
Definition at line 89 of file CbcSolver.java.
Referenced by wrimsv2.ilp.ILP.createNoteFile(), wrimsv2.launch.SettingPref.load(), wrimsv2.config.ConfigUtils.loadConfig(), main(), and wrimsv2.components.DebugInterface.setSolverOptions().
cbcLogStartDate
int wrimsv2.solver.CbcSolver.cbcLogStartDate = 999900 static
Definition at line 97 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
cbcLogStopDate
int wrimsv2.solver.CbcSolver.cbcLogStopDate = 999900 static
Definition at line 98 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
cbcSolutionRounding
boolean wrimsv2.solver.CbcSolver.cbcSolutionRounding = true static
Definition at line 95 of file CbcSolver.java.
Referenced by init(), wrimsv2.config.ConfigUtils.loadConfig(), newProblem(), wrimsv2.evaluator.Evaluation.relationStatement(), and wrimsv2.evaluator.ValueEvaluation.relationStatement().
cbcVersion
String wrimsv2.solver.CbcSolver.cbcVersion = "None" static
Definition at line 90 of file CbcSolver.java.
Referenced by init(), and wrimsv2.config.ConfigUtils.loadConfig().
cbcViolationCheck
boolean wrimsv2.solver.CbcSolver.cbcViolationCheck = true static
Definition at line 94 of file CbcSolver.java.
Referenced by init(), wrimsv2.config.ConfigUtils.loadConfig(), newProblem(), and violationCheck().
cbcViolationRetry
boolean wrimsv2.solver.CbcSolver.cbcViolationRetry = true static
Definition at line 96 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
cbcWriteLpEpsilon
final double wrimsv2.solver.CbcSolver.cbcWriteLpEpsilon = 1e-15 static
Definition at line 88 of file CbcSolver.java.
Referenced by reloadAndWriteLp(), reloadAndWriteLp(), and writeCbcLp().
debugDeviation
boolean wrimsv2.solver.CbcSolver.debugDeviation = false static
Definition at line 104 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
debugDeviationFindMissing
boolean wrimsv2.solver.CbcSolver.debugDeviationFindMissing = false static
Definition at line 108 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
debugDeviationMin
double wrimsv2.solver.CbcSolver.debugDeviationMin = 200 static
Definition at line 105 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
debugDeviationWeightMin
double wrimsv2.solver.CbcSolver.debugDeviationWeightMin = 99000 static
Definition at line 106 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
debugDeviationWeightMultiply
double wrimsv2.solver.CbcSolver.debugDeviationWeightMultiply = 100 static
Definition at line 107 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
debugDeviationWriteWarning
boolean wrimsv2.solver.CbcSolver.debugDeviationWriteWarning = false static
Definition at line 109 of file CbcSolver.java.
Referenced by newProblem().
debugObjDiff
boolean wrimsv2.solver.CbcSolver.debugObjDiff = false static
Definition at line 100 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
debugObjDiff_tolerance
double wrimsv2.solver.CbcSolver.debugObjDiff_tolerance = 1E5 static
Definition at line 101 of file CbcSolver.java.
Referenced by newProblem().
dvarMap
Map<String, Dvar> wrimsv2.solver.CbcSolver.dvarMap static private
Definition at line 71 of file CbcSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), assignDvar(), newProblem(), setConstraints(), setConstraintsIIS(), setConstraintsSkip(), setDVars(), setDVars2021(), and setDVarsIIS().
dvBiMap
BiMap<Integer, String> wrimsv2.solver.CbcSolver.dvBiMap static private
Definition at line 72 of file CbcSolver.java.
Referenced by iisSolve(), init(), loadProblemIIS(), newProblem(), reloadProblem(), reloadProblemConfirm(), resetModel(), setConstraints(), setConstraintsIIS(), setConstraintsSkip(), setDVars(), setDVars2021(), and setDVarsIIS().
dvBiMapArray
ArrayList<String> wrimsv2.solver.CbcSolver.dvBiMapArray static private
Definition at line 73 of file CbcSolver.java.
Referenced by init(), newProblem(), reloadProblem(), resetModel(), setConstraints(), setDVars(), and setDVars2021().
dvBiMapInverse
BiMap<String, Integer> wrimsv2.solver.CbcSolver.dvBiMapInverse static private
Definition at line 74 of file CbcSolver.java.
Referenced by loadProblemIIS(), newProblem(), reloadProblem(), reloadProblemConfirm(), resetModel(), setConstraints(), setConstraintsIIS(), and setConstraintsSkip().
dvIntMap
LinkedHashMap<String, Integer> wrimsv2.solver.CbcSolver.dvIntMap static private
Definition at line 124 of file CbcSolver.java.
Referenced by collectDvar(), collectDvar2021(), init(), logIntVars(), newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
dvIntMap2021
LinkedHashMap<String, Integer> wrimsv2.solver.CbcSolver.dvIntMap2021 static private
Definition at line 125 of file CbcSolver.java.
Referenced by collectDvar2021(), init(), and setDVars2021().
dvIntPredict
ArrayList<String> wrimsv2.solver.CbcSolver.dvIntPredict static private
Definition at line 126 of file CbcSolver.java.
Referenced by newProblem(), and setDVars2021().
elements
double wrimsv2.solver.CbcSolver.elements[] static private
Definition at line 117 of file CbcSolver.java.
Referenced by setConstraints(), setConstraintsIIS(), and setConstraintsSkip().
hasPriorityConstraints
boolean wrimsv2.solver.CbcSolver.hasPriorityConstraints = false static private
Definition at line 57 of file CbcSolver.java.
Referenced by iis(), and setConstraintsIIS().
iisConfirmConstraint
Set<String> wrimsv2.solver.CbcSolver.iisConfirmConstraint static private
Definition at line 55 of file CbcSolver.java.
Referenced by iis().
iisConstraintElementMap
LinkedHashMap<String, double[]> wrimsv2.solver.CbcSolver.iisConstraintElementMap static private
Definition at line 66 of file CbcSolver.java.
Referenced by iis(), iisSolve(), and setConstraintsIIS().
iisConstraintIndexMap
LinkedHashMap<String, int[]> wrimsv2.solver.CbcSolver.iisConstraintIndexMap static private
Definition at line 65 of file CbcSolver.java.
Referenced by iis(), iisSolve(), and setConstraintsIIS().
iisConstraintRHSMap
LinkedHashMap<String, Double> wrimsv2.solver.CbcSolver.iisConstraintRHSMap static private
Definition at line 64 of file CbcSolver.java.
Referenced by iis(), iisSolve(), and setConstraintsIIS().
iisConstraintSignMap
LinkedHashMap<String, String> wrimsv2.solver.CbcSolver.iisConstraintSignMap static private
Definition at line 63 of file CbcSolver.java.
Referenced by iis(), iisSolve(), and setConstraintsIIS().
iisPossibleConstraintMap
Map<String, String> wrimsv2.solver.CbcSolver.iisPossibleConstraintMap static private
Definition at line 53 of file CbcSolver.java.
Referenced by iis(), and iisSolve().
iisPossibleConstraintMap_cumulative
Map<String, String> wrimsv2.solver.CbcSolver.iisPossibleConstraintMap_cumulative static private
Definition at line 54 of file CbcSolver.java.
Referenced by iis().
iisSlackMap
LinkedHashMap<Integer, String> wrimsv2.solver.CbcSolver.iisSlackMap static private
Definition at line 62 of file CbcSolver.java.
Referenced by iisSolve(), loadProblemIIS(), and setConstraintsIIS().
iisSlacks
ArrayList<String> wrimsv2.solver.CbcSolver.iisSlacks static private
Definition at line 67 of file CbcSolver.java.
Referenced by iis().
index
int wrimsv2.solver.CbcSolver.index[] static private
Definition at line 116 of file CbcSolver.java.
Referenced by iisSolve(), setConstraints(), setConstraintsIIS(), and setConstraintsSkip().
integerT
double wrimsv2.solver.CbcSolver.integerT = 1e-9 static
Definition at line 85 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.launch.SettingPref.loadCBCSetting(), wrimsv2.config.ConfigUtils.loadConfig(), newProblem(), solve(), solve_2(), solve_3(), solve_jCbc2021(), and solve_jCbc2021a().
integerT_check
double wrimsv2.solver.CbcSolver.integerT_check = 1e-8 static
Definition at line 86 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.launch.SettingPref.loadCBCSetting(), wrimsv2.config.ConfigUtils.loadConfig(), newProblem(), solve(), and violationCheck().
intLog
boolean wrimsv2.solver.CbcSolver.intLog =true static
Definition at line 151 of file CbcSolver.java.
Referenced by wrimsv2.ilp.ILP.createNoteFile(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
intSolSize
int wrimsv2.solver.CbcSolver.intSolSize =0 static private
Definition at line 131 of file CbcSolver.java.
Referenced by newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
intSolSize_eachTS
int wrimsv2.solver.CbcSolver.intSolSize_eachTS =0 static private
Definition at line 136 of file CbcSolver.java.
intVarSize
int wrimsv2.solver.CbcSolver.intVarSize = -99 static private
Definition at line 127 of file CbcSolver.java.
Referenced by setDVars2021().
intViolation
boolean wrimsv2.solver.CbcSolver.intViolation =false static
Definition at line 152 of file CbcSolver.java.
isLogging
boolean wrimsv2.solver.CbcSolver.isLogging = false static private
Definition at line 99 of file CbcSolver.java.
Referenced by newProblem(), and solve_jCbc2021().
log_if_obj_diff
double wrimsv2.solver.CbcSolver.log_if_obj_diff = 500.0 static
Definition at line 167 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and wrimsv2.components.ControllerSG.runModelCbc().
logObj
boolean wrimsv2.solver.CbcSolver.logObj =true static
Definition at line 150 of file CbcSolver.java.
Referenced by wrimsv2.ilp.ILP.createNoteFile(), and wrimsv2.config.ConfigUtils.loadConfig().
lowerBoundZero_check
Double wrimsv2.solver.CbcSolver.lowerBoundZero_check = null static
Definition at line 87 of file CbcSolver.java.
Referenced by init(), wrimsv2.config.ConfigUtils.loadConfig(), newProblem(), solve(), and violationCheck().
maxObjDiff
double wrimsv2.solver.CbcSolver.maxObjDiff =0 static
Definition at line 143 of file CbcSolver.java.
Referenced by logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
maxObjDiff_id
String wrimsv2.solver.CbcSolver.maxObjDiff_id ="" static
Definition at line 144 of file CbcSolver.java.
Referenced by logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
maxObjDiff_minus
double wrimsv2.solver.CbcSolver.maxObjDiff_minus =0 static
Definition at line 145 of file CbcSolver.java.
Referenced by logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
maxObjDiff_minus_id
String wrimsv2.solver.CbcSolver.maxObjDiff_minus_id ="" static
Definition at line 146 of file CbcSolver.java.
Referenced by logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
maxValue
double wrimsv2.solver.CbcSolver.maxValue = 1e28 static private
Definition at line 76 of file CbcSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), assignDvar(), setConstraints(), setConstraintsIIS(), and setConstraintsSkip().
model
SWIGTYPE_p_CbcModel wrimsv2.solver.CbcSolver.model static private
Definition at line 50 of file CbcSolver.java.
Referenced by callCbc(), callCbc_R(), collectDvar(), collectDvar2021(), collectDvar2021_simple(), getObjValue(), iisSolve(), iisSolveConfirm(), loadProblemIIS(), main(), newProblem(), reloadAndWriteLp(), reloadAndWriteLp(), reloadProblem(), reloadProblemConfirm(), resetModel(), solve(), solve_2(), solve_3(), solve_jCbc2021(), solve_jCbc2021a(), violationCheck(), and writeCbcLp().
modelName
String wrimsv2.solver.CbcSolver.modelName static private
Definition at line 110 of file CbcSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), assignDvar(), loadProblemIIS(), newProblem(), reloadAndWriteLp(), reloadAndWriteLp(), reloadProblem(), reloadProblemConfirm(), setConstraints(), setDVars(), setDVars2021(), solve(), solve_jCbc2021(), violationCheck(), and writeCbcLp().
modelObject
SWIGTYPE_p_CoinModel wrimsv2.solver.CbcSolver.modelObject static private
Definition at line 51 of file CbcSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), loadProblemIIS(), newProblem(), reloadProblem(), reloadProblemConfirm(), resetModel(), setConstraints(), setConstraintsIIS(), setConstraintsSkip(), setDVars(), setDVars2021(), and setDVarsIIS().
names
SWIGTYPE_p_std__string wrimsv2.solver.CbcSolver.names static private
Definition at line 129 of file CbcSolver.java.
Referenced by newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
names_dummy
SWIGTYPE_p_std__string wrimsv2.solver.CbcSolver.names_dummy static private
Definition at line 139 of file CbcSolver.java.
Referenced by init().
names_eachTS
SWIGTYPE_p_std__string wrimsv2.solver.CbcSolver.names_eachTS static private
Definition at line 134 of file CbcSolver.java.
next_possible_stuck
boolean wrimsv2.solver.CbcSolver.next_possible_stuck =false static private
Definition at line 163 of file CbcSolver.java.
originalDvarKeys
HashSet wrimsv2.solver.CbcSolver.originalDvarKeys =null static private
Definition at line 147 of file CbcSolver.java.
Referenced by loadProblemIIS(), newProblem(), reloadProblem(), and reloadProblemConfirm().
prioritizeSearchTheseConstraints
Set<String> wrimsv2.solver.CbcSolver.prioritizeSearchTheseConstraints static
Definition at line 56 of file CbcSolver.java.
Referenced by iis().
record_if_obj_diff
double wrimsv2.solver.CbcSolver.record_if_obj_diff = 10000.0 static
Definition at line 166 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and wrimsv2.components.ControllerSG.runModelCbc().
saveIntVars
final boolean wrimsv2.solver.CbcSolver.saveIntVars =true static private
Definition at line 121 of file CbcSolver.java.
Referenced by collectDvar().
saveWarm
boolean wrimsv2.solver.CbcSolver.saveWarm =false static private
Definition at line 119 of file CbcSolver.java.
Referenced by collectDvar(), newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
solv2
final int wrimsv2.solver.CbcSolver.solv2 = 20 static
Definition at line 158 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
solv3
final int wrimsv2.solver.CbcSolver.solv3 = 30 static
Definition at line 159 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
solvCallCbc
final int wrimsv2.solver.CbcSolver.solvCallCbc = 50 static
Definition at line 160 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
solve_2_primalT
double wrimsv2.solver.CbcSolver.solve_2_primalT = 1e-9 static
Definition at line 78 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.launch.SettingPref.loadCBCSetting(), wrimsv2.config.ConfigUtils.loadConfig(), solve(), and solve_2().
solve_2_primalT_relax
double wrimsv2.solver.CbcSolver.solve_2_primalT_relax = 1e-7 static
Definition at line 79 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), init(), wrimsv2.launch.SettingPref.loadCBCSetting(), wrimsv2.config.ConfigUtils.loadConfig(), solve(), and solve_jCbc2021().
solve_3_primalT
final double wrimsv2.solver.CbcSolver.solve_3_primalT = 1e-9 static private
Definition at line 81 of file CbcSolver.java.
Referenced by solve(), and solve_3().
solve_u_ret
final HashMap<Integer, String> wrimsv2.solver.CbcSolver.solve_u_ret static
Initial value:
= new HashMap<Integer, String>() {{
        put(6,"whs");put(5,"2__");put(4,"2_r");put(1,"inf");
    }}
Definition at line 169 of file CbcSolver.java.
Referenced by solve().
solve_whs_primalT
double wrimsv2.solver.CbcSolver.solve_whs_primalT = 1e-9 static
Definition at line 83 of file CbcSolver.java.
Referenced by wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.launch.SettingPref.loadCBCSetting(), wrimsv2.config.ConfigUtils.loadConfig(), newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
solveName
String wrimsv2.solver.CbcSolver.solveName ="" static
Definition at line 149 of file CbcSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), callCbc(), callCbc_R(), newProblem(), reloadAndWriteLp(), reloadAndWriteLp(), wrimsv2.components.ControllerSG.runModelCbc(), setConstraints(), setDVars(), setDVars2021(), solve(), solve_2(), solve_3(), solve_jCbc2021(), solve_jCbc2021a(), violationCheck(), and writeCbcLp().
solver
SWIGTYPE_p_OsiClpSolverInterface wrimsv2.solver.CbcSolver.solver static private
Definition at line 49 of file CbcSolver.java.
Referenced by collectDvar(), collectDvar2021(), iisSolve(), iisSolveConfirm(), loadProblemIIS(), main(), newProblem(), note_msg(), reloadProblem(), reloadProblemConfirm(), setConstraints(), setConstraintsIIS(), setConstraintsSkip(), solve(), solve_2(), solve_3(), solve_jCbc2021(), and solve_jCbc2021a().
solvFull
final int wrimsv2.solver.CbcSolver.solvFull = 90 static
Definition at line 161 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
solvFunc
int wrimsv2.solver.CbcSolver.solvFunc = 90 static
Definition at line 154 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
solvU
final int wrimsv2.solver.CbcSolver.solvU = 100 static
Definition at line 162 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
total_relaxed_constraints
int wrimsv2.solver.CbcSolver.total_relaxed_constraints = 0 static private
Definition at line 59 of file CbcSolver.java.
Referenced by setConstraintsIIS().
usejCbc2021
boolean wrimsv2.solver.CbcSolver.usejCbc2021 = false static
Definition at line 92 of file CbcSolver.java.
Referenced by init(), wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
usejCbc2021a
boolean wrimsv2.solver.CbcSolver.usejCbc2021a = false static
Definition at line 93 of file CbcSolver.java.
Referenced by init(), wrimsv2.config.ConfigUtils.loadConfig(), and newProblem().
useLpFile
boolean wrimsv2.solver.CbcSolver.useLpFile =false static private
Definition at line 114 of file CbcSolver.java.
Referenced by init(), newProblem(), and resetModel().
useWarm
boolean wrimsv2.solver.CbcSolver.useWarm =false static private
Definition at line 120 of file CbcSolver.java.
Referenced by collectDvar(), newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
values
SWIGTYPE_p_int wrimsv2.solver.CbcSolver.values static private
Definition at line 130 of file CbcSolver.java.
Referenced by newProblem(), solve(), solve_jCbc2021(), and solve_jCbc2021a().
values_dummy
SWIGTYPE_p_int wrimsv2.solver.CbcSolver.values_dummy static private
Definition at line 140 of file CbcSolver.java.
Referenced by init().
values_eachTS
SWIGTYPE_p_int wrimsv2.solver.CbcSolver.values_eachTS static private
Definition at line 135 of file CbcSolver.java.
varDoubleMap
LinkedHashMap<String, Double> wrimsv2.solver.CbcSolver.varDoubleMap static
Definition at line 47 of file CbcSolver.java.
Referenced by assignDvar(), collectDvar(), collectDvar2021(), newProblem(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
warm_2nd_solvFunc
int wrimsv2.solver.CbcSolver.warm_2nd_solvFunc = 20 static
Definition at line 155 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
warmArrayExist
boolean wrimsv2.solver.CbcSolver.warmArrayExist = false static private
Definition at line 132 of file CbcSolver.java.
Referenced by solve(), solve_jCbc2021(), and solve_jCbc2021a().
warmArrayExist_eachTS
boolean wrimsv2.solver.CbcSolver.warmArrayExist_eachTS = false static private
Definition at line 137 of file CbcSolver.java.
whsSafe
boolean wrimsv2.solver.CbcSolver.whsSafe = false static
Definition at line 103 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig().
whsScaling
boolean wrimsv2.solver.CbcSolver.whsScaling = true static
Definition at line 102 of file CbcSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig().
wm2
Map<String, WeightElement> wrimsv2.solver.CbcSolver.wm2 static private
Definition at line 112 of file CbcSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), and newProblem().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/CbcSolver.java