Wrims-engine: wrimsv2.hdf5.DSSHDF5Converter Class Reference
wrimsv2.hdf5.DSSHDF5Converter Class Reference
Public Member Functions
DSSHDF5Converter (String[] args)
void convertInitFile ()
void convertInitFileDssToHDF5 ()
void convertInitFileHDF5ToDss ()
void convertSVFile ()
void convertSVFileDssToHDF5 ()
void convertSVFileHDF5ToDss ()
int getTotalTimeStep (String timestepStr)
void process ()
void processArgs (String[] args)
void procLaunch (String[] args)
void readDailyInitDssFile ()
void readDailySVDssFile ()
void readMonthlyInitDssFile ()
void readMonthlySVDssFile ()
void setControlData (String[] args)
void writeDailyInitHDF5File ()
void writeDailySVHDF5File ()
void writeMonthlyInitHDF5File ()
void writeMonthlySVHDF5File ()
Static Public Member Functions
static void closeInitHDF5DataStructure ()
static void closeSVHDF5DataStructure ()
static void createInitHDF5DataStructure ()
static void createInitLookup ()
static void createSVHDF5DataStructure ()
static void createSVLookup ()
static void listDailyInitHDF5File ()
static void listDailySVHDF5File ()
static void listMonthlyInitHDF5File ()
static void listMonthlySVHDF5File ()
static void main (String[] args)
static String regularExp (String part)
Static Private Attributes
static Date firstDateDaily
static Date firstDateMonthly
static String gDaily ="Daily"
static String gData ="Data"
static String gInfo ="Info"
static String gIOData ="IO Data"
static String gMonthly ="Monthly"
static Map< String, double[]> initDailyData = new HashMap<String, double[]>()
static ArrayList< String > initDailyKinds = new ArrayList<String>()
static ArrayList< String > initDailyNames = new ArrayList<String>()
static int initFid =-1
static int initGidDaily =-1
static int initGidData =-1
static int initGidInfo =-1
static int initGidIOData =-1
static int initGidMonthly =-1
static int initGidPartA =-1
static int initGidPartF =-1
static String initH5FileName =""
static int initIndex =0
static ArrayList< Integer > initLookupIndex = new ArrayList<Integer>()
static ArrayList< String > initLookupKinds = new ArrayList<String>()
static ArrayList< String > initLookupNames = new ArrayList<String>()
static ArrayList< String > initLookupTimestep = new ArrayList<String>()
static ArrayList< String > initLookupUnits = new ArrayList<String>()
static Map< String, double[]> initMonthlyData = new HashMap<String, double[]>()
static ArrayList< String > initMonthlyKinds = new ArrayList<String>()
static ArrayList< String > initMonthlyNames = new ArrayList<String>()
static Map< String, double[]> svDailyData = new HashMap<String, double[]>()
static ArrayList< String > svDailyKinds = new ArrayList<String>()
static ArrayList< String > svDailyNames = new ArrayList<String>()
static int svFid =-1
static int svGidDaily =-1
static int svGidData =-1
static int svGidInfo =-1
static int svGidIOData =-1
static int svGidMonthly =-1
static int svGidPartA =-1
static int svGidPartF =-1
static String svH5FileName =""
static int svIndex =0
static ArrayList< Integer > svLookupIndex = new ArrayList<Integer>()
static ArrayList< String > svLookupKinds = new ArrayList<String>()
static ArrayList< String > svLookupNames = new ArrayList<String>()
static ArrayList< String > svLookupTimestep = new ArrayList<String>()
static ArrayList< String > svLookupUnits = new ArrayList<String>()
static Map< String, double[]> svMonthlyData = new HashMap<String, double[]>()
static ArrayList< String > svMonthlyKinds = new ArrayList<String>()
static ArrayList< String > svMonthlyNames = new ArrayList<String>()
Detailed Description
Definition at line 47 of file DSSHDF5Converter.java.
Constructor & Destructor Documentation
DSSHDF5Converter()
wrimsv2.hdf5.DSSHDF5Converter.DSSHDF5Converter (String[] args)
Definition at line 103 of file DSSHDF5Converter.java.
References processArgs().
Referenced by main().
Member Function Documentation
closeInitHDF5DataStructure()
void wrimsv2.hdf5.DSSHDF5Converter.closeInitHDF5DataStructure () static
Definition at line 543 of file DSSHDF5Converter.java.
References initFid, initGidDaily, initGidData, initGidInfo, initGidIOData, initGidMonthly, initGidPartA, and initGidPartF.
Referenced by convertInitFileDssToHDF5().
closeSVHDF5DataStructure()
void wrimsv2.hdf5.DSSHDF5Converter.closeSVHDF5DataStructure () static
Definition at line 519 of file DSSHDF5Converter.java.
References svFid, svGidDaily, svGidData, svGidInfo, svGidIOData, svGidMonthly, svGidPartA, and svGidPartF.
Referenced by convertSVFileDssToHDF5().
convertInitFile()
void wrimsv2.hdf5.DSSHDF5Converter.convertInitFile ()
Definition at line 960 of file DSSHDF5Converter.java.
References convertInitFileDssToHDF5(), convertInitFileHDF5ToDss(), and wrimsv2.components.FilePaths.initFile.
Referenced by process().
convertInitFileDssToHDF5()
void wrimsv2.hdf5.DSSHDF5Converter.convertInitFileDssToHDF5 ()
Definition at line 968 of file DSSHDF5Converter.java.
References closeInitHDF5DataStructure(), createInitHDF5DataStructure(), createInitLookup(), initIndex, initLookupIndex, initLookupKinds, initLookupNames, initLookupTimestep, initLookupUnits, listDailyInitHDF5File(), listMonthlyInitHDF5File(), readDailyInitDssFile(), readMonthlyInitDssFile(), writeDailyInitHDF5File(), and writeMonthlyInitHDF5File().
Referenced by convertInitFile().
convertInitFileHDF5ToDss()
void wrimsv2.hdf5.DSSHDF5Converter.convertInitFileHDF5ToDss ()
Definition at line 1249 of file DSSHDF5Converter.java.
Referenced by convertInitFile().
convertSVFile()
void wrimsv2.hdf5.DSSHDF5Converter.convertSVFile ()
Definition at line 113 of file DSSHDF5Converter.java.
References convertSVFileDssToHDF5(), convertSVFileHDF5ToDss(), and wrimsv2.components.FilePaths.svarFile.
Referenced by process().
convertSVFileDssToHDF5()
void wrimsv2.hdf5.DSSHDF5Converter.convertSVFileDssToHDF5 ()
Definition at line 121 of file DSSHDF5Converter.java.
References closeSVHDF5DataStructure(), createSVHDF5DataStructure(), createSVLookup(), listDailySVHDF5File(), listMonthlySVHDF5File(), readDailySVDssFile(), readMonthlySVDssFile(), svIndex, svLookupIndex, svLookupKinds, svLookupNames, svLookupTimestep, svLookupUnits, writeDailySVHDF5File(), and writeMonthlySVHDF5File().
Referenced by convertSVFile().
convertSVFileHDF5ToDss()
void wrimsv2.hdf5.DSSHDF5Converter.convertSVFileHDF5ToDss ()
Definition at line 956 of file DSSHDF5Converter.java.
Referenced by convertSVFile().
createInitHDF5DataStructure()
void wrimsv2.hdf5.DSSHDF5Converter.createInitHDF5DataStructure () static
Definition at line 641 of file DSSHDF5Converter.java.
References wrimsv2.evaluator.TimeOperation.dssTimeEndDay(), firstDateDaily, firstDateMonthly, wrimsv2.components.FilePaths.fullInitFilePath, gDaily, gData, gInfo, gIOData, gMonthly, initFid, initGidDaily, initGidData, initGidInfo, initGidIOData, initGidMonthly, initGidPartA, initGidPartF, initH5FileName, wrimsv2.components.ControlData.initPartF, wrimsv2.hdf5.HDF5Util.locateFile(), wrimsv2.hdf5.HDF5Util.locateGroup(), wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.components.ControlData.partA, and wrimsv2.hdf5.HDF5Util.writeStringAttr().
Referenced by convertInitFileDssToHDF5().
createInitLookup()
void wrimsv2.hdf5.DSSHDF5Converter.createInitLookup () static
Definition at line 437 of file DSSHDF5Converter.java.
References initGidInfo, initLookupIndex, initLookupKinds, initLookupNames, initLookupTimestep, initLookupUnits, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by convertInitFileDssToHDF5().
createSVHDF5DataStructure()
void wrimsv2.hdf5.DSSHDF5Converter.createSVHDF5DataStructure () static
Definition at line 567 of file DSSHDF5Converter.java.
References wrimsv2.evaluator.TimeOperation.dssTimeEndDay(), wrimsv2.components.FilePaths.fullSvarFilePath, gDaily, gData, gInfo, gIOData, gMonthly, wrimsv2.hdf5.HDF5Util.locateFile(), wrimsv2.hdf5.HDF5Util.locateGroup(), wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.components.ControlData.partA, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.ControlData.svDvPartF, svFid, svGidDaily, svGidData, svGidInfo, svGidIOData, svGidMonthly, svGidPartA, svGidPartF, svH5FileName, and wrimsv2.hdf5.HDF5Util.writeStringAttr().
Referenced by convertSVFileDssToHDF5().
createSVLookup()
void wrimsv2.hdf5.DSSHDF5Converter.createSVLookup () static
Definition at line 355 of file DSSHDF5Converter.java.
References svGidInfo, svLookupIndex, svLookupKinds, svLookupNames, svLookupTimestep, svLookupUnits, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by convertSVFileDssToHDF5().
getTotalTimeStep()
int wrimsv2.hdf5.DSSHDF5Converter.getTotalTimeStep (String timestepStr)
Definition at line 1302 of file DSSHDF5Converter.java.
References wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by readDailySVDssFile(), and readMonthlySVDssFile().
listDailyInitHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.listDailyInitHDF5File () static
Definition at line 302 of file DSSHDF5Converter.java.
References initDailyKinds, initDailyNames, initGidDaily, initGidInfo, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by convertInitFileDssToHDF5().
listDailySVHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.listDailySVHDF5File () static
Definition at line 196 of file DSSHDF5Converter.java.
References svDailyKinds, svDailyNames, svGidDaily, svGidInfo, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by convertSVFileDssToHDF5().
listMonthlyInitHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.listMonthlyInitHDF5File () static
Definition at line 249 of file DSSHDF5Converter.java.
References initGidInfo, initGidMonthly, initMonthlyKinds, initMonthlyNames, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by convertInitFileDssToHDF5().
listMonthlySVHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.listMonthlySVHDF5File () static
Definition at line 143 of file DSSHDF5Converter.java.
References svGidInfo, svGidMonthly, svMonthlyKinds, svMonthlyNames, and wrimsv2.hdf5.HDF5Util.writeStringData().
Referenced by convertSVFileDssToHDF5().
main()
void wrimsv2.hdf5.DSSHDF5Converter.main (String[] args) static
Definition at line 1292 of file DSSHDF5Converter.java.
References DSSHDF5Converter(), and process().
process()
void wrimsv2.hdf5.DSSHDF5Converter.process ()
Definition at line 107 of file DSSHDF5Converter.java.
References convertInitFile(), and convertSVFile().
Referenced by main().
processArgs()
void wrimsv2.hdf5.DSSHDF5Converter.processArgs (String[] args)
Definition at line 1253 of file DSSHDF5Converter.java.
References wrimsv2.config.ConfigUtils.loadArgs(), procLaunch(), and setControlData().
Referenced by DSSHDF5Converter().
procLaunch()
void wrimsv2.hdf5.DSSHDF5Converter.procLaunch (String[] args)
Definition at line 1264 of file DSSHDF5Converter.java.
Referenced by processArgs().
readDailyInitDssFile()
void wrimsv2.hdf5.DSSHDF5Converter.readDailyInitDssFile ()
Definition at line 1114 of file DSSHDF5Converter.java.
References wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), firstDateDaily, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths(), initDailyData, initDailyKinds, initDailyNames, initIndex, initLookupIndex, initLookupKinds, initLookupNames, initLookupTimestep, initLookupUnits, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.partA, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by convertInitFileDssToHDF5().
readDailySVDssFile()
void wrimsv2.hdf5.DSSHDF5Converter.readDailySVDssFile ()
Definition at line 841 of file DSSHDF5Converter.java.
References wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths(), getTotalTimeStep(), wrimsv2.components.ControlData.partA, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, svDailyData, svDailyKinds, svDailyNames, wrimsv2.components.ControlData.svDvPartF, svIndex, svLookupIndex, svLookupKinds, svLookupNames, svLookupTimestep, and svLookupUnits.
Referenced by convertSVFileDssToHDF5().
readMonthlyInitDssFile()
void wrimsv2.hdf5.DSSHDF5Converter.readMonthlyInitDssFile ()
Definition at line 989 of file DSSHDF5Converter.java.
References wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), firstDateMonthly, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths(), initIndex, initLookupIndex, initLookupKinds, initLookupNames, initLookupTimestep, initLookupUnits, initMonthlyData, initMonthlyKinds, initMonthlyNames, wrimsv2.components.ControlData.initPartF, wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.components.ControlData.partA, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by convertInitFileDssToHDF5().
readMonthlySVDssFile()
void wrimsv2.hdf5.DSSHDF5Converter.readMonthlySVDssFile ()
Definition at line 733 of file DSSHDF5Converter.java.
References wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths(), getTotalTimeStep(), wrimsv2.components.ControlData.partA, wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.ControlData.svDvPartF, svIndex, svLookupIndex, svLookupKinds, svLookupNames, svLookupTimestep, svLookupUnits, svMonthlyData, svMonthlyKinds, and svMonthlyNames.
Referenced by convertSVFileDssToHDF5().
regularExp()
String wrimsv2.hdf5.DSSHDF5Converter.regularExp (String part) static
Definition at line 1298 of file DSSHDF5Converter.java.
setControlData()
void wrimsv2.hdf5.DSSHDF5Converter.setControlData (String[] args)
Definition at line 1269 of file DSSHDF5Converter.java.
References wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.partA, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
Referenced by processArgs().
writeDailyInitHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.writeDailyInitHDF5File ()
Definition at line 1197 of file DSSHDF5Converter.java.
References initDailyData, initDailyKinds, initDailyNames, and initGidDaily.
Referenced by convertInitFileDssToHDF5().
writeDailySVHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.writeDailySVHDF5File ()
Definition at line 904 of file DSSHDF5Converter.java.
References svDailyData, svDailyKinds, svDailyNames, and svGidDaily.
Referenced by convertSVFileDssToHDF5().
writeMonthlyInitHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.writeMonthlyInitHDF5File ()
Definition at line 1062 of file DSSHDF5Converter.java.
References initGidMonthly, initMonthlyData, initMonthlyKinds, and initMonthlyNames.
Referenced by convertInitFileDssToHDF5().
writeMonthlySVHDF5File()
void wrimsv2.hdf5.DSSHDF5Converter.writeMonthlySVHDF5File ()
Definition at line 789 of file DSSHDF5Converter.java.
References svGidMonthly, svMonthlyData, svMonthlyKinds, and svMonthlyNames.
Referenced by convertSVFileDssToHDF5().
Member Data Documentation
firstDateDaily
Date wrimsv2.hdf5.DSSHDF5Converter.firstDateDaily static private
Definition at line 100 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and readDailyInitDssFile().
firstDateMonthly
Date wrimsv2.hdf5.DSSHDF5Converter.firstDateMonthly static private
Definition at line 101 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and readMonthlyInitDssFile().
gDaily
String wrimsv2.hdf5.DSSHDF5Converter.gDaily ="Daily" static private
Definition at line 97 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and createSVHDF5DataStructure().
gData
String wrimsv2.hdf5.DSSHDF5Converter.gData ="Data" static private
Definition at line 91 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and createSVHDF5DataStructure().
gInfo
String wrimsv2.hdf5.DSSHDF5Converter.gInfo ="Info" static private
Definition at line 88 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and createSVHDF5DataStructure().
gIOData
String wrimsv2.hdf5.DSSHDF5Converter.gIOData ="IO Data" static private
Definition at line 87 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and createSVHDF5DataStructure().
gMonthly
String wrimsv2.hdf5.DSSHDF5Converter.gMonthly ="Monthly" static private
Definition at line 94 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure(), and createSVHDF5DataStructure().
initDailyData
Map<String, double[]> wrimsv2.hdf5.DSSHDF5Converter.initDailyData = new HashMap<String, double[]>() static private
Definition at line 75 of file DSSHDF5Converter.java.
Referenced by readDailyInitDssFile(), and writeDailyInitHDF5File().
initDailyKinds
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initDailyKinds = new ArrayList<String>() static private
Definition at line 74 of file DSSHDF5Converter.java.
Referenced by listDailyInitHDF5File(), readDailyInitDssFile(), and writeDailyInitHDF5File().
initDailyNames
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initDailyNames = new ArrayList<String>() static private
Definition at line 73 of file DSSHDF5Converter.java.
Referenced by listDailyInitHDF5File(), readDailyInitDssFile(), and writeDailyInitHDF5File().
initFid
int wrimsv2.hdf5.DSSHDF5Converter.initFid =-1 static private
Definition at line 80 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), and createInitHDF5DataStructure().
initGidDaily
int wrimsv2.hdf5.DSSHDF5Converter.initGidDaily =-1 static private
Definition at line 99 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), createInitHDF5DataStructure(), listDailyInitHDF5File(), and writeDailyInitHDF5File().
initGidData
int wrimsv2.hdf5.DSSHDF5Converter.initGidData =-1 static private
Definition at line 93 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), and createInitHDF5DataStructure().
initGidInfo
int wrimsv2.hdf5.DSSHDF5Converter.initGidInfo =-1 static private
Definition at line 90 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), createInitHDF5DataStructure(), createInitLookup(), listDailyInitHDF5File(), and listMonthlyInitHDF5File().
initGidIOData
int wrimsv2.hdf5.DSSHDF5Converter.initGidIOData =-1 static private
Definition at line 86 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), and createInitHDF5DataStructure().
initGidMonthly
int wrimsv2.hdf5.DSSHDF5Converter.initGidMonthly =-1 static private
Definition at line 96 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), createInitHDF5DataStructure(), listMonthlyInitHDF5File(), and writeMonthlyInitHDF5File().
initGidPartA
int wrimsv2.hdf5.DSSHDF5Converter.initGidPartA =-1 static private
Definition at line 82 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), and createInitHDF5DataStructure().
initGidPartF
int wrimsv2.hdf5.DSSHDF5Converter.initGidPartF =-1 static private
Definition at line 84 of file DSSHDF5Converter.java.
Referenced by closeInitHDF5DataStructure(), and createInitHDF5DataStructure().
initH5FileName
String wrimsv2.hdf5.DSSHDF5Converter.initH5FileName ="" static private
Definition at line 78 of file DSSHDF5Converter.java.
Referenced by createInitHDF5DataStructure().
initIndex
int wrimsv2.hdf5.DSSHDF5Converter.initIndex =0 static private
Definition at line 61 of file DSSHDF5Converter.java.
Referenced by convertInitFileDssToHDF5(), readDailyInitDssFile(), and readMonthlyInitDssFile().
initLookupIndex
ArrayList<Integer> wrimsv2.hdf5.DSSHDF5Converter.initLookupIndex = new ArrayList<Integer>() static private
Definition at line 60 of file DSSHDF5Converter.java.
Referenced by convertInitFileDssToHDF5(), createInitLookup(), readDailyInitDssFile(), and readMonthlyInitDssFile().
initLookupKinds
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initLookupKinds = new ArrayList<String>() static private
Definition at line 57 of file DSSHDF5Converter.java.
Referenced by convertInitFileDssToHDF5(), createInitLookup(), readDailyInitDssFile(), and readMonthlyInitDssFile().
initLookupNames
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initLookupNames = new ArrayList<String>() static private
Definition at line 56 of file DSSHDF5Converter.java.
Referenced by convertInitFileDssToHDF5(), createInitLookup(), readDailyInitDssFile(), and readMonthlyInitDssFile().
initLookupTimestep
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initLookupTimestep = new ArrayList<String>() static private
Definition at line 59 of file DSSHDF5Converter.java.
Referenced by convertInitFileDssToHDF5(), createInitLookup(), readDailyInitDssFile(), and readMonthlyInitDssFile().
initLookupUnits
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initLookupUnits = new ArrayList<String>() static private
Definition at line 58 of file DSSHDF5Converter.java.
Referenced by convertInitFileDssToHDF5(), createInitLookup(), readDailyInitDssFile(), and readMonthlyInitDssFile().
initMonthlyData
Map<String, double[]> wrimsv2.hdf5.DSSHDF5Converter.initMonthlyData = new HashMap<String, double[]>() static private
Definition at line 72 of file DSSHDF5Converter.java.
Referenced by readMonthlyInitDssFile(), and writeMonthlyInitHDF5File().
initMonthlyKinds
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initMonthlyKinds = new ArrayList<String>() static private
Definition at line 71 of file DSSHDF5Converter.java.
Referenced by listMonthlyInitHDF5File(), readMonthlyInitDssFile(), and writeMonthlyInitHDF5File().
initMonthlyNames
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.initMonthlyNames = new ArrayList<String>() static private
Definition at line 70 of file DSSHDF5Converter.java.
Referenced by listMonthlyInitHDF5File(), readMonthlyInitDssFile(), and writeMonthlyInitHDF5File().
svDailyData
Map<String, double[]> wrimsv2.hdf5.DSSHDF5Converter.svDailyData = new HashMap<String, double[]>() static private
Definition at line 68 of file DSSHDF5Converter.java.
Referenced by readDailySVDssFile(), and writeDailySVHDF5File().
svDailyKinds
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svDailyKinds = new ArrayList<String>() static private
Definition at line 67 of file DSSHDF5Converter.java.
Referenced by listDailySVHDF5File(), readDailySVDssFile(), and writeDailySVHDF5File().
svDailyNames
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svDailyNames = new ArrayList<String>() static private
Definition at line 66 of file DSSHDF5Converter.java.
Referenced by listDailySVHDF5File(), readDailySVDssFile(), and writeDailySVHDF5File().
svFid
int wrimsv2.hdf5.DSSHDF5Converter.svFid =-1 static private
Definition at line 79 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), and createSVHDF5DataStructure().
svGidDaily
int wrimsv2.hdf5.DSSHDF5Converter.svGidDaily =-1 static private
Definition at line 98 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), createSVHDF5DataStructure(), listDailySVHDF5File(), and writeDailySVHDF5File().
svGidData
int wrimsv2.hdf5.DSSHDF5Converter.svGidData =-1 static private
Definition at line 92 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), and createSVHDF5DataStructure().
svGidInfo
int wrimsv2.hdf5.DSSHDF5Converter.svGidInfo =-1 static private
Definition at line 89 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), createSVHDF5DataStructure(), createSVLookup(), listDailySVHDF5File(), and listMonthlySVHDF5File().
svGidIOData
int wrimsv2.hdf5.DSSHDF5Converter.svGidIOData =-1 static private
Definition at line 85 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), and createSVHDF5DataStructure().
svGidMonthly
int wrimsv2.hdf5.DSSHDF5Converter.svGidMonthly =-1 static private
Definition at line 95 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), createSVHDF5DataStructure(), listMonthlySVHDF5File(), and writeMonthlySVHDF5File().
svGidPartA
int wrimsv2.hdf5.DSSHDF5Converter.svGidPartA =-1 static private
Definition at line 81 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), and createSVHDF5DataStructure().
svGidPartF
int wrimsv2.hdf5.DSSHDF5Converter.svGidPartF =-1 static private
Definition at line 83 of file DSSHDF5Converter.java.
Referenced by closeSVHDF5DataStructure(), and createSVHDF5DataStructure().
svH5FileName
String wrimsv2.hdf5.DSSHDF5Converter.svH5FileName ="" static private
Definition at line 77 of file DSSHDF5Converter.java.
Referenced by createSVHDF5DataStructure().
svIndex
int wrimsv2.hdf5.DSSHDF5Converter.svIndex =0 static private
Definition at line 54 of file DSSHDF5Converter.java.
Referenced by convertSVFileDssToHDF5(), readDailySVDssFile(), and readMonthlySVDssFile().
svLookupIndex
ArrayList<Integer> wrimsv2.hdf5.DSSHDF5Converter.svLookupIndex = new ArrayList<Integer>() static private
Definition at line 53 of file DSSHDF5Converter.java.
Referenced by convertSVFileDssToHDF5(), createSVLookup(), readDailySVDssFile(), and readMonthlySVDssFile().
svLookupKinds
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svLookupKinds = new ArrayList<String>() static private
Definition at line 50 of file DSSHDF5Converter.java.
Referenced by convertSVFileDssToHDF5(), createSVLookup(), readDailySVDssFile(), and readMonthlySVDssFile().
svLookupNames
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svLookupNames = new ArrayList<String>() static private
Definition at line 49 of file DSSHDF5Converter.java.
Referenced by convertSVFileDssToHDF5(), createSVLookup(), readDailySVDssFile(), and readMonthlySVDssFile().
svLookupTimestep
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svLookupTimestep = new ArrayList<String>() static private
Definition at line 52 of file DSSHDF5Converter.java.
Referenced by convertSVFileDssToHDF5(), createSVLookup(), readDailySVDssFile(), and readMonthlySVDssFile().
svLookupUnits
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svLookupUnits = new ArrayList<String>() static private
Definition at line 51 of file DSSHDF5Converter.java.
Referenced by convertSVFileDssToHDF5(), createSVLookup(), readDailySVDssFile(), and readMonthlySVDssFile().
svMonthlyData
Map<String, double[]> wrimsv2.hdf5.DSSHDF5Converter.svMonthlyData = new HashMap<String, double[]>() static private
Definition at line 65 of file DSSHDF5Converter.java.
Referenced by readMonthlySVDssFile(), and writeMonthlySVHDF5File().
svMonthlyKinds
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svMonthlyKinds = new ArrayList<String>() static private
Definition at line 64 of file DSSHDF5Converter.java.
Referenced by listMonthlySVHDF5File(), readMonthlySVDssFile(), and writeMonthlySVHDF5File().
svMonthlyNames
ArrayList<String> wrimsv2.hdf5.DSSHDF5Converter.svMonthlyNames = new ArrayList<String>() static private
Definition at line 63 of file DSSHDF5Converter.java.
Referenced by listMonthlySVHDF5File(), readMonthlySVDssFile(), and writeMonthlySVHDF5File().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/hdf5/DSSHDF5Converter.java