Wrims-engine: wrimsv2.components.ControllerSG Class Reference
wrimsv2.components.ControllerSG Class Reference
Public Member Functions
ControllerSG ()
ControllerSG (String[] args)
void generateStudyFile ()
StudyDataSet parse () throws RecognitionException, IOException
void runModel (StudyDataSet sds)
void runModelCbc (StudyDataSet sds)
void runModelXA (StudyDataSet sds)
void setControlData ()
void setControlData (String[] args)
void writeOutputDssEveryTenYears ()
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 32 of file ControllerSG.java.
Constructor & Destructor Documentation
ControllerSG() [1/2]
wrimsv2.components.ControllerSG.ControllerSG ()
Definition at line 34 of file ControllerSG.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.components.FilePaths.mainDirectory, parse(), runModel(), setControlData(), wrimsv2.wreslparser.elements.StudyUtils.total_errors, and wrimsv2.wreslparser.elements.StudyUtils.writeObj().
Referenced by main().
ControllerSG() [2/2]
wrimsv2.components.ControllerSG.ControllerSG (String[] args)
Definition at line 57 of file ControllerSG.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.components.FilePaths.mainDirectory, parse(), runModel(), setControlData(), wrimsv2.wreslparser.elements.StudyUtils.total_errors, and wrimsv2.wreslparser.elements.StudyUtils.writeObj().
Member Function Documentation
generateStudyFile()
void wrimsv2.components.ControllerSG.generateStudyFile ()
Definition at line 135 of file ControllerSG.java.
References wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
main()
void wrimsv2.components.ControllerSG.main (String[] args) static
Definition at line 620 of file ControllerSG.java.
References ControllerSG().
parse()
StudyDataSet wrimsv2.components.ControllerSG.parse () throws RecognitionException, IOException
Definition at line 188 of file ControllerSG.java.
References wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.StudyUtils.loadObject(), wrimsv2.wreslparser.elements.StudyUtils.loadParserData, and wrimsv2.wreslparser.elements.StudyUtils.parserDataPath.
Referenced by ControllerSG(), and ControllerSG().
runModel()
void wrimsv2.components.ControllerSG.runModel (StudyDataSet sds)
Definition at line 196 of file ControllerSG.java.
References runModelCbc(), runModelXA(), and wrimsv2.components.ControlData.solverName.
Referenced by ControllerSG(), and ControllerSG().
runModelCbc()
void wrimsv2.components.ControllerSG.runModelCbc (StudyDataSet sds)
Definition at line 339 of file ControllerSG.java.
References wrimsv2.ilp.ILP._noteFile_cbc_int, wrimsv2.ilp.ILP._noteFile_cbc_int_log, wrimsv2.ilp.ILP._noteFile_cbc_obj, wrimsv2.ilp.ILP._noteFile_xa_int, wrimsv2.ilp.ILP._noteFile_xa_obj, wrimsv2.ilp.ILP._watchFile_cbc, wrimsv2.ilp.ILP._watchFile_xa, wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.solver.CbcSolver.close(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.components.ControlData.clp_cbc_objective, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.ilp.ILP.getYearMonthCycle(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.solver.CbcSolver.init(), wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.solver.CbcSolver.intLog, wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.solver.CbcSolver.log_if_obj_diff, wrimsv2.solver.CbcSolver.maxObjDiff, wrimsv2.solver.CbcSolver.maxObjDiff_id, wrimsv2.solver.CbcSolver.maxObjDiff_minus, wrimsv2.solver.CbcSolver.maxObjDiff_minus_id, wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.ControlData.outputType, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.solver.CbcSolver.record_if_obj_diff, wrimsv2.solver.CbcSolver.reloadAndWriteLp(), wrimsv2.solver.CbcSolver.resetModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.solver.CbcSolver.solveName, wrimsv2.components.ControlData.solverTime_cbc_this, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.solver.CbcSolver.varDoubleMap, wrimsv2.components.ControlData.watchList, wrimsv2.components.ControlData.watchList_tolerance, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeNoteLn(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), and wrimsv2.components.ControlData.xasolver.
Referenced by runModel().
runModelXA()
void wrimsv2.components.ControllerSG.runModelXA (StudyDataSet sds)
Definition at line 208 of file ControllerSG.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.components.ControlData.outputType, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.components.ControlData.solverName, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), and wrimsv2.components.ControlData.xasolver.
Referenced by runModel().
setControlData() [1/2]
void wrimsv2.components.ControllerSG.setControlData ()
Definition at line 81 of file ControllerSG.java.
References wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
Referenced by ControllerSG(), and ControllerSG().
setControlData() [2/2]
void wrimsv2.components.ControllerSG.setControlData (String[] args)
Definition at line 105 of file ControllerSG.java.
References wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.ControlData.svDvPartF, and wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus.
writeOutputDssEveryTenYears()
void wrimsv2.components.ControllerSG.writeOutputDssEveryTenYears ()
Definition at line 610 of file ControllerSG.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.timeStep, and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/ControllerSG.java