Wrims-engine: wrimsv2.solver.clp.FilePassingUtils Class Reference
wrimsv2.solver.clp.FilePassingUtils Class Reference
Static Public Member Functions
static void main (String[] args)
static int parseReturnFile (String filePath)
Static Public Attributes
static Double objective_value
static int solverErrorCode
static String solverMessage = ""
static Map< String, Double > varDoubleMap
Static Private Member Functions
static String parseObjectiveValue ()
static void parseSolution ()
static String parseSolverMessage ()
static void reset ()
static void setReturnFile (String filePath)
Static Private Attributes
static File soluFile
static String soluPath
static Scanner soluScan
Detailed Description
Definition at line 27 of file FilePassingUtils.java.
Member Function Documentation
main()
void wrimsv2.solver.clp.FilePassingUtils.main (String[] args) static
Definition at line 178 of file FilePassingUtils.java.
References objective_value, parseReturnFile(), solverErrorCode, solverMessage, and varDoubleMap.
parseObjectiveValue()
String wrimsv2.solver.clp.FilePassingUtils.parseObjectiveValue () static private
Definition at line 114 of file FilePassingUtils.java.
References soluScan.
Referenced by parseReturnFile().
parseReturnFile()
int wrimsv2.solver.clp.FilePassingUtils.parseReturnFile (String filePath) static
Definition at line 39 of file FilePassingUtils.java.
References objective_value, parseObjectiveValue(), parseSolution(), parseSolverMessage(), reset(), setReturnFile(), solverErrorCode, solverMessage, and varDoubleMap.
Referenced by main().
parseSolution()
void wrimsv2.solver.clp.FilePassingUtils.parseSolution () static private
Definition at line 139 of file FilePassingUtils.java.
References soluScan, and varDoubleMap.
Referenced by parseReturnFile().
parseSolverMessage()
String wrimsv2.solver.clp.FilePassingUtils.parseSolverMessage () static private
Definition at line 104 of file FilePassingUtils.java.
References soluScan.
Referenced by parseReturnFile().
reset()
void wrimsv2.solver.clp.FilePassingUtils.reset () static private
Definition at line 77 of file FilePassingUtils.java.
References objective_value, soluFile, soluPath, soluScan, solverErrorCode, solverMessage, and varDoubleMap.
Referenced by parseReturnFile().
setReturnFile()
void wrimsv2.solver.clp.FilePassingUtils.setReturnFile (String filePath) static private
Definition at line 90 of file FilePassingUtils.java.
References soluFile, soluPath, and soluScan.
Referenced by parseReturnFile().
Member Data Documentation
objective_value
Double wrimsv2.solver.clp.FilePassingUtils.objective_value static
Definition at line 31 of file FilePassingUtils.java.
Referenced by main(), parseReturnFile(), and reset().
soluFile
File wrimsv2.solver.clp.FilePassingUtils.soluFile static private
Definition at line 34 of file FilePassingUtils.java.
Referenced by reset(), and setReturnFile().
soluPath
String wrimsv2.solver.clp.FilePassingUtils.soluPath static private
Definition at line 33 of file FilePassingUtils.java.
Referenced by reset(), and setReturnFile().
soluScan
Scanner wrimsv2.solver.clp.FilePassingUtils.soluScan static private
Definition at line 35 of file FilePassingUtils.java.
Referenced by parseObjectiveValue(), parseSolution(), parseSolverMessage(), reset(), and setReturnFile().
solverErrorCode
int wrimsv2.solver.clp.FilePassingUtils.solverErrorCode static
Definition at line 29 of file FilePassingUtils.java.
Referenced by main(), parseReturnFile(), and reset().
solverMessage
String wrimsv2.solver.clp.FilePassingUtils.solverMessage = "" static
Definition at line 30 of file FilePassingUtils.java.
Referenced by main(), parseReturnFile(), and reset().
varDoubleMap
Map<String, Double> wrimsv2.solver.clp.FilePassingUtils.varDoubleMap static
Definition at line 32 of file FilePassingUtils.java.
Referenced by main(), parseReturnFile(), parseSolution(), and reset().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/clp/FilePassingUtils.java