Wrims-engine: wrimsv2.components.Controller Class Reference
wrimsv2.components.Controller Class Reference
Public Member Functions
Controller ()
Controller (String[] args)
void generateStudyFile ()
StudyDataSet parse () throws RecognitionException, IOException
void runModel (StudyDataSet sds)
void runModelGurobi (StudyDataSet sds)
void runModelILP (StudyDataSet sds)
void runModelXA (StudyDataSet sds)
void setControlData ()
void setControlData (String[] args)
void writeOutputDssEveryTenYears ()
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 29 of file Controller.java.
Constructor & Destructor Documentation
Controller() [1/2]
wrimsv2.components.Controller.Controller ()
Definition at line 31 of file Controller.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.components.FilePaths.mainDirectory, parse(), runModel(), setControlData(), wrimsv2.wreslparser.elements.StudyUtils.total_errors, and wrimsv2.wreslparser.elements.StudyUtils.writeObj().
Referenced by main().
Controller() [2/2]
wrimsv2.components.Controller.Controller (String[] args)
Definition at line 54 of file Controller.java.
References parse(), runModel(), setControlData(), and wrimsv2.wreslparser.elements.StudyUtils.total_errors.
Member Function Documentation
generateStudyFile()
void wrimsv2.components.Controller.generateStudyFile ()
Definition at line 122 of file Controller.java.
References wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
main()
void wrimsv2.components.Controller.main (String[] args) static
Definition at line 443 of file Controller.java.
References Controller().
parse()
StudyDataSet wrimsv2.components.Controller.parse () throws RecognitionException, IOException
Definition at line 176 of file Controller.java.
References wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.StudyUtils.loadObject(), wrimsv2.wreslparser.elements.StudyUtils.loadParserData, and wrimsv2.wreslparser.elements.StudyUtils.parserDataPath.
Referenced by Controller(), and Controller().
runModel()
void wrimsv2.components.Controller.runModel (StudyDataSet sds)
Definition at line 184 of file Controller.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.components.Error.getTotalError(), wrimsv2.ilp.ILP.logging, runModelGurobi(), runModelILP(), runModelXA(), wrimsv2.components.ControlData.solverName, and wrimsv2.components.Error.writeErrorLog().
Referenced by Controller(), and Controller().
runModelGurobi()
void wrimsv2.components.Controller.runModelGurobi (StudyDataSet sds)
Definition at line 314 of file Controller.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.Error.addSolvingError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.ilp.ILP.closeIlpFile(), wrimsv2.ilp.ILP.cplexLpFilePath, wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.solver.Gurobi.GurobiSolver.dispose(), wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.solver.Gurobi.GurobiSolver.initialize(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.components.ControlData.isPostProcessing, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.ilp.ILP.setIlpFile(), wrimsv2.solver.Gurobi.GurobiSolver.setLp(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.solver.Gurobi.GurobiSolver.solve(), wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.ilp.ILP.writeDvarValue_Gurobi(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.ilp.ILP.writeIlp(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeObjValue_Gurobi(), wrimsv2.components.Error.writeSolvingErrorFile(), and wrimsv2.ilp.ILP.writeSvarValue().
Referenced by runModel().
runModelILP()
void wrimsv2.components.Controller.runModelILP (StudyDataSet sds)
Definition at line 447 of file Controller.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.ilp.ILP.closeIlpFile(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.components.ControlData.isPostProcessing, wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.ilp.ILP.lpSolveFilePath, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.ilp.ILP.setIlpFile(), wrimsv2.solver.LPSolveSolver.setLP(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.solver.LPSolveSolver.solve(), wrimsv2.commondata.wresldata.Param.SOLVER_LPSOLVE, wrimsv2.commondata.wresldata.Param.SOLVER_XA, wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.solverType, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.ilp.ILP.writeDvarValue_LPSOLVE(), wrimsv2.ilp.ILP.writeDvarValue_XA(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.ilp.ILP.writeIlp(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeObjValue_LPSOLVE(), wrimsv2.ilp.ILP.writeObjValue_XA(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.ilp.ILP.writeSvarValue(), and wrimsv2.components.ControlData.xasolver.
Referenced by runModel().
runModelXA()
void wrimsv2.components.Controller.runModelXA (StudyDataSet sds)
Definition at line 206 of file Controller.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.components.ControlData.isPostProcessing, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.components.ControlData.solverName, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.components.Error.writeSolvingErrorFile(), and wrimsv2.components.ControlData.xasolver.
Referenced by runModel().
setControlData() [1/2]
void wrimsv2.components.Controller.setControlData ()
Definition at line 74 of file Controller.java.
References wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
Referenced by Controller(), and Controller().
setControlData() [2/2]
void wrimsv2.components.Controller.setControlData (String[] args)
Definition at line 98 of file Controller.java.
References wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
writeOutputDssEveryTenYears()
void wrimsv2.components.Controller.writeOutputDssEveryTenYears ()
Definition at line 433 of file Controller.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.timeStep, and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/Controller.java