Wrims-engine: wrimsv2.wreslparser.elements.LogUtils Class Reference
wrimsv2.wreslparser.elements.LogUtils Class Reference
Static Public Member Functions
static void closeLogFile ()
static void consoleMsgOnly (String msg)
static void criticalMsg (String msg)
static void dvarsList (String msg, ArrayList< String > list_all, ArrayList< String > list_g, ArrayList< String > list_l, Map< String, Dvar > dvMap)
static void dvarsList (String msg, ArrayList< String > list_all, Map< String, Dvar > dvMap)
static void errMsg (String msg)
static void errMsg (String msg, ArrayList< String > list)
static void errMsg (String msg, String file)
static void errMsg (String msg, String file1, String file2, Map< String, Set< String > > reverseMap)
static void errMsgLocation (String filePath, int lineNumber, String msg)
static void fileSummary (SimulationDataSet S)
static void importantMsg (ArrayList< String > msg)
static void importantMsg (String msg)
static void importantMsg (String msg, ArrayList< String > dvList, Map< String, Dvar > dvMap)
static void mainFileSummary (StudyConfig studyConfig)
static void normalMsg (String msg)
static void parsingSummaryMsg (String msg, int errors)
static void seqList (ArrayList< String > list, Map< Integer, Sequence > seqMap)
static void setLogFile (String logFileName)
static void setLogFile (String parentDir, String logFileName)
static void studySummary (StudyConfig studyConfig, Map< String, SimulationDataSet > modelDataMap)
static void studySummary_details (StudyConfig studyConfig, Map< String, SimulationDataSet > modelDataMap)
static void studySummary_details (StudyDataSet sd)
static void titleMsg (String msg)
static void typeRedefinedErrMsg (String msg) throws TypeRedefinedException
static void varsList (String msg, ArrayList< String > list_all, ArrayList< String > list_g, ArrayList< String > list_l, String description)
static void varsList (String msg, ArrayList< String > list_all, String description)
static void warningMsg (String msg)
static void warningMsgLocation (String filePath, int lineNumber, String msg)
Static Public Attributes
static PrintWriter _logFile
Static Private Member Functions
static void printTree (String f, Map< String, Set< String > > reverseMap, String level)
Detailed Description
Definition at line 17 of file LogUtils.java.
Member Function Documentation
closeLogFile()
void wrimsv2.wreslparser.elements.LogUtils.closeLogFile () static
Definition at line 21 of file LogUtils.java.
References _logFile.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.wreslplus.elements.ParserUtils.initParser(), wrimsv2.wreslparser.elements.FileParser.parseFile(), and wrimsv2.wreslparser.elements.FileParser.parseMainFile().
consoleMsgOnly()
void wrimsv2.wreslparser.elements.LogUtils.consoleMsgOnly (String msg) static
Definition at line 252 of file LogUtils.java.
References wrimsv2.components.ControlData.showWreslLog.
criticalMsg()
void wrimsv2.wreslparser.elements.LogUtils.criticalMsg (String msg) static
Definition at line 214 of file LogUtils.java.
References _logFile.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
dvarsList() [1/2]
void wrimsv2.wreslparser.elements.LogUtils.dvarsList (String msg, ArrayList< String > list_all, ArrayList< String > list_g, ArrayList< String > list_l, Map< String, Dvar > dvMap) static
Definition at line 53 of file LogUtils.java.
References importantMsg().
Referenced by studySummary_details(), and studySummary_details().
dvarsList() [2/2]
void wrimsv2.wreslparser.elements.LogUtils.dvarsList (String msg, ArrayList< String > list_all, Map< String, Dvar > dvMap) static
Definition at line 70 of file LogUtils.java.
References importantMsg().
errMsg() [1/4]
void wrimsv2.wreslparser.elements.LogUtils.errMsg (String msg) static
Definition at line 298 of file LogUtils.java.
References _logFile, wrimsv2.components.ControlData.showWreslLog, and wrimsv2.wreslparser.elements.StudyParser.total_errors.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycle_subfunction(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIncModelNotExistIgnoreCase(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialConst(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkModelRedefined(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkModelRedefinedIgnoreCase(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSequenceHasUniqueModel(), wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarRedefined(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightObjList(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightVarNotInDvar(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap(), wrimsv2.components.IncFileCollector.copyWreslsAndLookupTablesTo(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), errMsg(), errMsg(), errMsg(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslplus.elements.procedures.ProcMainFile.findEffectiveModel(), wrimsv2.wreslplus.elements.Tools.getCanonicalLowCasePath(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.SimulationDataSet.hasDuplicateIn(), wrimsv2.wreslparser.elements.StructTree.includeFile(), wrimsv2.wreslplus.elements.ParserUtils.initParser(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), wrimsv2.wreslparser.elements.StructTree.modelList(), wrimsv2.wreslparser.elements.FileParser.parseFile(), wrimsv2.wreslparser.elements.FileParser.parseMainFile(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.wreslparser.elements.FileParser.processFileIntoSimulationDataSet(), wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath(), wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath(), wrimsv2.wreslparser.elements.Tools.readFileAsString(), wrimsv2.wreslplus.elements.Tools.readFileAsString(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
errMsg() [2/4]
void wrimsv2.wreslparser.elements.LogUtils.errMsg (String msg, ArrayList< String > list) static
Definition at line 308 of file LogUtils.java.
References errMsg().
errMsg() [3/4]
void wrimsv2.wreslparser.elements.LogUtils.errMsg (String msg, String file) static
Definition at line 316 of file LogUtils.java.
References errMsg().
errMsg() [4/4]
void wrimsv2.wreslparser.elements.LogUtils.errMsg (String msg, String file1, String file2, Map< String, Set< String > > reverseMap) static
Definition at line 322 of file LogUtils.java.
References _logFile, errMsg(), printTree(), and wrimsv2.components.ControlData.showWreslLog.
errMsgLocation()
void wrimsv2.wreslparser.elements.LogUtils.errMsgLocation (String filePath, int lineNumber, String msg) static
Definition at line 288 of file LogUtils.java.
References _logFile, wrimsv2.wreslparser.elements.StudyParser.error_summary, wrimsv2.components.ControlData.showWreslLog, and wrimsv2.wreslparser.elements.StudyParser.total_errors.
Referenced by wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkParameterHasUnknownDepedants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSeqConditionHasUnknownDepedants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarRedefined(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarUsedBeforeDefined(), wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap(), and wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap().
fileSummary()
void wrimsv2.wreslparser.elements.LogUtils.fileSummary (SimulationDataSet S) static
Definition at line 115 of file LogUtils.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, and varsList().
importantMsg() [1/3]
void wrimsv2.wreslparser.elements.LogUtils.importantMsg (ArrayList< String > msg) static
Definition at line 228 of file LogUtils.java.
References importantMsg().
importantMsg() [2/3]
void wrimsv2.wreslparser.elements.LogUtils.importantMsg (String msg) static
Definition at line 221 of file LogUtils.java.
References _logFile, and wrimsv2.components.ControlData.showWreslLog.
Referenced by wrimsv2.components.IncFileCollector.IncFileCollector(), wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslparser.elements.StudyUtils.compileObject(), wrimsv2.components.IncFileCollector.copyWreslsAndLookupTablesTo(), dvarsList(), dvarsList(), importantMsg(), importantMsg(), wrimsv2.wreslplus.elements.ParserUtils.initParser(), mainFileSummary(), wrimsv2.wreslparser.elements.FileParser.parseFile(), wrimsv2.wreslparser.elements.FileParser.parseMainFile(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.components.IncFileCollector.parseWresl(), wrimsv2.wreslparser.elements.StudyParser.processMainFileIntoStudyConfig(), seqList(), studySummary(), studySummary_details(), studySummary_details(), varsList(), and varsList().
importantMsg() [3/3]
void wrimsv2.wreslparser.elements.LogUtils.importantMsg (String msg, ArrayList< String > dvList, Map< String, Dvar > dvMap) static
Definition at line 235 of file LogUtils.java.
References importantMsg().
mainFileSummary()
void wrimsv2.wreslparser.elements.LogUtils.mainFileSummary (StudyConfig studyConfig) static
Definition at line 125 of file LogUtils.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, importantMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.StudyConfig.modelDataMap, seqList(), wrimsv2.wreslparser.elements.StudyConfig.sequenceList, wrimsv2.wreslparser.elements.StudyConfig.sequenceMap, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, and varsList().
normalMsg()
void wrimsv2.wreslparser.elements.LogUtils.normalMsg (String msg) static
Definition at line 242 of file LogUtils.java.
References _logFile, wrimsv2.commondata.wresldata.Param.printLevel, and wrimsv2.components.ControlData.showWreslLog.
parsingSummaryMsg()
void wrimsv2.wreslparser.elements.LogUtils.parsingSummaryMsg (String msg, int errors) static
Definition at line 199 of file LogUtils.java.
References _logFile.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
printTree()
void wrimsv2.wreslparser.elements.LogUtils.printTree (String f, Map< String, Set< String > > reverseMap, String level) static private
Definition at line 338 of file LogUtils.java.
References _logFile, printTree(), and wrimsv2.components.ControlData.showWreslLog.
Referenced by errMsg(), and printTree().
seqList()
void wrimsv2.wreslparser.elements.LogUtils.seqList (ArrayList< String > list, Map< Integer, Sequence > seqMap) static
Definition at line 104 of file LogUtils.java.
References importantMsg().
Referenced by mainFileSummary(), studySummary(), and studySummary_details().
setLogFile() [1/2]
void wrimsv2.wreslparser.elements.LogUtils.setLogFile (String logFileName) static
Definition at line 38 of file LogUtils.java.
References _logFile, and wrimsv2.wreslparser.elements.Tools.openFile().
setLogFile() [2/2]
void wrimsv2.wreslparser.elements.LogUtils.setLogFile (String parentDir, String logFileName) static
Definition at line 26 of file LogUtils.java.
References _logFile, and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), and wrimsv2.components.IncFileCollector.initialize().
studySummary()
void wrimsv2.wreslparser.elements.LogUtils.studySummary (StudyConfig studyConfig, Map< String, SimulationDataSet > modelDataMap) static
Definition at line 157 of file LogUtils.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, importantMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.StudyConfig.modelList, seqList(), wrimsv2.wreslparser.elements.StudyConfig.sequenceList, wrimsv2.wreslparser.elements.StudyConfig.sequenceMap, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, and varsList().
studySummary_details() [1/2]
void wrimsv2.wreslparser.elements.LogUtils.studySummary_details (StudyConfig studyConfig, Map< String, SimulationDataSet > modelDataMap) static
Definition at line 141 of file LogUtils.java.
References dvarsList(), wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, importantMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.StudyConfig.modelList, seqList(), wrimsv2.wreslparser.elements.StudyConfig.sequenceList, wrimsv2.wreslparser.elements.StudyConfig.sequenceMap, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, and varsList().
studySummary_details() [2/2]
void wrimsv2.wreslparser.elements.LogUtils.studySummary_details (StudyDataSet sd) static
Definition at line 173 of file LogUtils.java.
References dvarsList(), wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), and importantMsg().
titleMsg()
void wrimsv2.wreslparser.elements.LogUtils.titleMsg (String msg) static
Definition at line 186 of file LogUtils.java.
References _logFile.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.checkStudy().
typeRedefinedErrMsg()
void wrimsv2.wreslparser.elements.LogUtils.typeRedefinedErrMsg (String msg) throws TypeRedefinedException static
Definition at line 276 of file LogUtils.java.
References _logFile, wrimsv2.components.ControlData.showWreslLog, and wrimsv2.wreslparser.elements.StudyParser.total_errors.
Referenced by wrimsv2.wreslparser.elements.SimulationDataSet.replaceGlobalWithDuplicateLocal().
varsList() [1/2]
void wrimsv2.wreslparser.elements.LogUtils.varsList (String msg, ArrayList< String > list_all, ArrayList< String > list_g, ArrayList< String > list_l, String description) static
Definition at line 81 of file LogUtils.java.
References importantMsg().
Referenced by fileSummary(), mainFileSummary(), studySummary(), and studySummary_details().
varsList() [2/2]
void wrimsv2.wreslparser.elements.LogUtils.varsList (String msg, ArrayList< String > list_all, String description) static
Definition at line 95 of file LogUtils.java.
References importantMsg().
warningMsg()
void wrimsv2.wreslparser.elements.LogUtils.warningMsg (String msg) static
Definition at line 258 of file LogUtils.java.
References _logFile, wrimsv2.components.ControlData.showWreslLog, and wrimsv2.wreslparser.elements.StudyParser.total_warnings.
Referenced by wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), wrimsv2.components.IncFileCollector.copyWreslsAndLookupTablesTo(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), and wrimsv2.wreslparser.elements.Sort.sort().
warningMsgLocation()
void wrimsv2.wreslparser.elements.LogUtils.warningMsgLocation (String filePath, int lineNumber, String msg) static
Definition at line 268 of file LogUtils.java.
References _logFile, and wrimsv2.components.ControlData.showWreslLog.
Referenced by wrimsv2.components.IncFileCollector.initParser().
Member Data Documentation
_logFile
PrintWriter wrimsv2.wreslparser.elements.LogUtils._logFile static
Definition at line 19 of file LogUtils.java.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), closeLogFile(), criticalMsg(), errMsg(), errMsg(), errMsgLocation(), importantMsg(), normalMsg(), parsingSummaryMsg(), printTree(), setLogFile(), setLogFile(), titleMsg(), typeRedefinedErrMsg(), warningMsg(), and warningMsgLocation().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/LogUtils.java