Wrims-engine: wrimsv2.components.ControllerDebug Class Reference
wrimsv2.components.ControllerDebug Class Reference
Public Member Functions
ControllerDebug (String[] args, DebugInterface di)
void connectToDataBase ()
void debugTimeAddOneDay ()
void debugTimeAddOneMonth ()
void deferPause (int i)
void generateStudyFile ()
StudyDataSet parse () throws RecognitionException, IOException
void pauseForDebug (int i)
void prepareInitialTimeStep ()
void procLaunch (String[] args)
void resetStartDate (StudyDataSet sds)
void run ()
void runModel (StudyDataSet sds)
void runModelSolvers (StudyDataSet sds)
void setControlData (String[] args)
void updateVarMonitor ()
void writeOutputDssEveryTenYears ()
Public Attributes
String[] args
String conditionalBreakpoint
ValueEvaluatorParser conditionalBreakpointParser
int debugCycle
int debugDay
int debugMonth
int debugYear
int modelIndex
int totalCycles =0
Static Public Attributes
static ArrayList< Integer > initialTimeStep
Private Member Functions
void checkConditionalBreakpoint ()
Private Attributes
DebugInterface di
MySQLCWriter mySQLCWriter
MySQLRWriter mySQLRWriter
SQLServerRWriter sqlServerRWriter
Detailed Description
Definition at line 58 of file ControllerDebug.java.
Constructor & Destructor Documentation
ControllerDebug()
wrimsv2.components.ControllerDebug.ControllerDebug (String[] args, DebugInterface di)
Definition at line 75 of file ControllerDebug.java.
References args, and di.
Member Function Documentation
checkConditionalBreakpoint()
void wrimsv2.components.ControllerDebug.checkConditionalBreakpoint () private
Definition at line 614 of file ControllerDebug.java.
References conditionalBreakpoint, conditionalBreakpointParser, wrimsv2.components.ControlData.currEvalTypeIndex, debugCycle, debugDay, debugMonth, debugYear, di, and wrimsv2.components.Error.error_evaluation.
Referenced by pauseForDebug().
connectToDataBase()
void wrimsv2.components.ControllerDebug.connectToDataBase ()
Definition at line 706 of file ControllerDebug.java.
References mySQLCWriter, mySQLRWriter, wrimsv2.components.ControlData.outputType, and sqlServerRWriter.
Referenced by run().
debugTimeAddOneDay()
void wrimsv2.components.ControllerDebug.debugTimeAddOneDay ()
Definition at line 603 of file ControllerDebug.java.
References debugDay, debugMonth, and debugYear.
Referenced by deferPause().
debugTimeAddOneMonth()
void wrimsv2.components.ControllerDebug.debugTimeAddOneMonth ()
Definition at line 594 of file ControllerDebug.java.
References debugDay, debugMonth, debugYear, and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by deferPause().
deferPause()
void wrimsv2.components.ControllerDebug.deferPause (int i)
Definition at line 573 of file ControllerDebug.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, debugCycle, debugDay, debugMonth, debugTimeAddOneDay(), debugTimeAddOneMonth(), debugYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.timeStep, and totalCycles.
Referenced by runModelSolvers().
generateStudyFile()
void wrimsv2.components.ControllerDebug.generateStudyFile ()
Definition at line 142 of file ControllerDebug.java.
References wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
parse()
StudyDataSet wrimsv2.components.ControllerDebug.parse () throws RecognitionException, IOException
Definition at line 194 of file ControllerDebug.java.
References wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.components.FilePaths.fullMainPath, wrimsv2.wreslparser.elements.StudyUtils.loadObject(), wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.wreslparser.elements.StudyUtils.parserDataPath, wrimsv2.components.LoadParameter.process(), and wrimsv2.wreslplus.elements.ParserUtils.setRunDir().
Referenced by run().
pauseForDebug()
void wrimsv2.components.ControllerDebug.pauseForDebug (int i)
Definition at line 537 of file ControllerDebug.java.
References checkConditionalBreakpoint(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, debugCycle, debugDay, debugMonth, debugYear, di, wrimsv2.components.Error.getTotalError(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), and wrimsv2.components.ControlData.timeStep.
Referenced by runModelSolvers().
prepareInitialTimeStep()
void wrimsv2.components.ControllerDebug.prepareInitialTimeStep ()
Definition at line 504 of file ControllerDebug.java.
References wrimsv2.components.ControlData.currTimeStep, and initialTimeStep.
Referenced by runModelSolvers().
procLaunch()
void wrimsv2.components.ControllerDebug.procLaunch (String[] args)
Definition at line 716 of file ControllerDebug.java.
References args.
Referenced by run().
resetStartDate()
void wrimsv2.components.ControllerDebug.resetStartDate (StudyDataSet sds)
Definition at line 511 of file ControllerDebug.java.
References wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), initialTimeStep, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.VariableTimeStep.procCycleTimeStep(), wrimsv2.components.ControlData.resimDay, wrimsv2.components.ControlData.resimMonth, and wrimsv2.components.ControlData.resimYear.
Referenced by runModelSolvers().
run()
void wrimsv2.components.ControllerDebug.run ()
Definition at line 81 of file ControllerDebug.java.
References args, wrimsv2.wreslparser.elements.StudyUtils.configFileName, connectToDataBase(), di, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.tools.General.getPID(), wrimsv2.config.ConfigUtils.loadArgs(), wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.components.FilePaths.mainDirectory, parse(), procLaunch(), runModel(), wrimsv2.components.ControlData.t_parse, wrimsv2.wreslparser.elements.StudyParser.total_errors, totalCycles, and wrimsv2.wreslparser.elements.StudyUtils.writeObj().
runModel()
void wrimsv2.components.ControllerDebug.runModel (StudyDataSet sds)
Definition at line 207 of file ControllerDebug.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.components.ControlData.dvDss, wrimsv2.components.ControlData.outputType, runModelSolvers(), wrimsv2.components.ControlData.showTimeUsage, wrimsv2.components.TimeUsage.showTimeUsage(), wrimsv2.components.ControlData.solverName, and wrimsv2.components.Error.writeErrorLog().
Referenced by run().
runModelSolvers()
void wrimsv2.components.ControllerDebug.runModelSolvers (StudyDataSet sds)
Definition at line 223 of file ControllerDebug.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.ilp.ILP.closeIlpFile(), wrimsv2.ilp.ILP.cplexLpFilePath, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.ilp.ILP.createNoteFile(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, deferPause(), wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, di, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.ilp.ILP.getIlpDir(), wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.solver.CbcSolver.init(), wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.solver.Gurobi.GurobiSolver.initialize(), wrimsv2.ilp.ILP.initializeIlp(), initialTimeStep, wrimsv2.evaluator.TimeOperation.initMemDate(), wrimsv2.evaluator.TimeOperation.initOutputDate(), wrimsv2.solver.CbcSolver.intLog, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logCbcWatchList(), wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.ilp.ILP.logUsageMemory(), wrimsv2.ilp.ILP.lpSolveFilePath, modelIndex, wrimsv2.components.ControlData.monMemSection, mySQLCWriter, mySQLRWriter, wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputType, wrimsv2.evaluator.WeightEval.outputWtTableAR(), wrimsv2.components.ControlData.outputYear, pauseForDebug(), prepareInitialTimeStep(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.solver.CbcSolver.resetModel(), resetStartDate(), wrimsv2.components.ControlData.resimDate, wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.ilp.ILP.setIlpFile(), wrimsv2.solver.LPSolveSolver.setLP(), wrimsv2.solver.Gurobi.GurobiSolver.setLp(), wrimsv2.ilp.ILP.setMaximumFractionDigits(), wrimsv2.evaluator.TimeOperation.setMemDate(), wrimsv2.evaluator.TimeOperation.setOutputDate(), wrimsv2.ilp.ILP.setSvarFile(), wrimsv2.ilp.ILP.setVarDir(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.evaluator.DssOperation.shiftData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.solver.Gurobi.GurobiSolver.solve(), wrimsv2.solver.LPSolveSolver.solve(), wrimsv2.components.ControlData.solverName, sqlServerRWriter, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, updateVarMonitor(), wrimsv2.solver.CbcSolver.varDoubleMap, wrimsv2.components.ControlData.watchList, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.ilp.ILP.writeDvarValue_Clp0_Cbc0(), wrimsv2.ilp.ILP.writeDvarValue_Gurobi(), wrimsv2.ilp.ILP.writeDvarValue_LPSOLVE(), wrimsv2.ilp.ILP.writeDvarValue_XA(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.ilp.ILP.writeIlp(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeNoteLn(), wrimsv2.ilp.ILP.writeObjValue_Clp0_Cbc0(), wrimsv2.ilp.ILP.writeObjValue_LPSOLVE(), wrimsv2.ilp.ILP.writeObjValue_XA(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.ilp.ILP.writeSvarValue(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), and wrimsv2.components.ControlData.yearOutputSection.
Referenced by runModel().
setControlData()
void wrimsv2.components.ControllerDebug.setControlData (String[] args)
Definition at line 118 of file ControllerDebug.java.
References args, wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
updateVarMonitor()
void wrimsv2.components.ControllerDebug.updateVarMonitor ()
Definition at line 641 of file ControllerDebug.java.
References wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, di, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex().
Referenced by runModelSolvers().
writeOutputDssEveryTenYears()
void wrimsv2.components.ControllerDebug.writeOutputDssEveryTenYears ()
Definition at line 696 of file ControllerDebug.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.timeStep, and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
Member Data Documentation
args
String [] wrimsv2.components.ControllerDebug.args
Definition at line 67 of file ControllerDebug.java.
Referenced by ControllerDebug(), procLaunch(), run(), and setControlData().
conditionalBreakpoint
String wrimsv2.components.ControllerDebug.conditionalBreakpoint
Definition at line 65 of file ControllerDebug.java.
Referenced by checkConditionalBreakpoint().
conditionalBreakpointParser
ValueEvaluatorParser wrimsv2.components.ControllerDebug.conditionalBreakpointParser
Definition at line 66 of file ControllerDebug.java.
Referenced by checkConditionalBreakpoint().
debugCycle
int wrimsv2.components.ControllerDebug.debugCycle
Definition at line 63 of file ControllerDebug.java.
Referenced by checkConditionalBreakpoint(), deferPause(), and pauseForDebug().
debugDay
int wrimsv2.components.ControllerDebug.debugDay
Definition at line 62 of file ControllerDebug.java.
Referenced by checkConditionalBreakpoint(), debugTimeAddOneDay(), debugTimeAddOneMonth(), deferPause(), and pauseForDebug().
debugMonth
int wrimsv2.components.ControllerDebug.debugMonth
Definition at line 61 of file ControllerDebug.java.
Referenced by checkConditionalBreakpoint(), debugTimeAddOneDay(), debugTimeAddOneMonth(), deferPause(), and pauseForDebug().
debugYear
int wrimsv2.components.ControllerDebug.debugYear
Definition at line 60 of file ControllerDebug.java.
Referenced by checkConditionalBreakpoint(), debugTimeAddOneDay(), debugTimeAddOneMonth(), deferPause(), and pauseForDebug().
di
DebugInterface wrimsv2.components.ControllerDebug.di private
Definition at line 59 of file ControllerDebug.java.
Referenced by ControllerDebug(), checkConditionalBreakpoint(), pauseForDebug(), run(), runModelSolvers(), and updateVarMonitor().
initialTimeStep
ArrayList<Integer> wrimsv2.components.ControllerDebug.initialTimeStep static
Definition at line 69 of file ControllerDebug.java.
Referenced by prepareInitialTimeStep(), resetStartDate(), and runModelSolvers().
modelIndex
int wrimsv2.components.ControllerDebug.modelIndex
Definition at line 68 of file ControllerDebug.java.
Referenced by runModelSolvers().
mySQLCWriter
MySQLCWriter wrimsv2.components.ControllerDebug.mySQLCWriter private
Definition at line 71 of file ControllerDebug.java.
Referenced by connectToDataBase(), and runModelSolvers().
mySQLRWriter
MySQLRWriter wrimsv2.components.ControllerDebug.mySQLRWriter private
Definition at line 72 of file ControllerDebug.java.
Referenced by connectToDataBase(), and runModelSolvers().
sqlServerRWriter
SQLServerRWriter wrimsv2.components.ControllerDebug.sqlServerRWriter private
Definition at line 73 of file ControllerDebug.java.
Referenced by connectToDataBase(), and runModelSolvers().
totalCycles
int wrimsv2.components.ControllerDebug.totalCycles =0
Definition at line 64 of file ControllerDebug.java.
Referenced by deferPause(), and run().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/ControllerDebug.java