Wrims-engine: wrimsv2.wreslplus.elements.VarCycleIndex Class Reference
wrimsv2.wreslplus.elements.VarCycleIndex Class Reference
Static Public Member Functions
static void clearVarCycleIndexList ()
Static Public Attributes
static ArrayList< String > varCycleIndexList = new ArrayList<String>()
Detailed Description
Definition at line 5 of file VarCycleIndex.java.
Member Function Documentation
clearVarCycleIndexList()
void wrimsv2.wreslplus.elements.VarCycleIndex.clearVarCycleIndexList () static
Definition at line 8 of file VarCycleIndex.java.
References varCycleIndexList.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), and wrimsv2.wreslparser.elements.StudyUtils.parseWresl().
Member Data Documentation
varCycleIndexList
ArrayList<String> wrimsv2.wreslplus.elements.VarCycleIndex.varCycleIndexList = new ArrayList<String>() static
Definition at line 6 of file VarCycleIndex.java.
Referenced by clearVarCycleIndexList(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/VarCycleIndex.java