Wrims-engine: wrimsv2.wreslplus.elements.procedures.ProcParameter Class Reference
wrimsv2.wreslplus.elements.procedures.ProcParameter Class Reference
Static Public Member Functions
static void process (StudyTemp st)
Private Member Functions
ProcParameter ()
Static Private Member Functions
static boolean callBooleanEvaluator (String evalString)
static IntDouble callNumberEvaluator (String evalString)
static LinkedHashMap< String, Svar > convertParamMapToSvarMap (Map< String, SvarTemp > simpleMap)
static void evaluateAllParams (ArrayList< String > keyList, Map< String, Svar > map)
Detailed Description
Definition at line 24 of file ProcParameter.java.
Constructor & Destructor Documentation
ProcParameter()
wrimsv2.wreslplus.elements.procedures.ProcParameter.ProcParameter () private
Definition at line 26 of file ProcParameter.java.
Member Function Documentation
callBooleanEvaluator()
boolean wrimsv2.wreslplus.elements.procedures.ProcParameter.callBooleanEvaluator (String evalString) static private
Definition at line 66 of file ProcParameter.java.
References wrimsv2.components.Error.getTotalError(), and wrimsv2.components.Error.writeErrorLog().
Referenced by evaluateAllParams().
callNumberEvaluator()
IntDouble wrimsv2.wreslplus.elements.procedures.ProcParameter.callNumberEvaluator (String evalString) static private
Definition at line 95 of file ProcParameter.java.
References wrimsv2.components.Error.getTotalError(), and wrimsv2.components.Error.writeErrorLog().
Referenced by evaluateAllParams().
convertParamMapToSvarMap()
LinkedHashMap< String, Svar > wrimsv2.wreslplus.elements.procedures.ProcParameter.convertParamMapToSvarMap (Map< String, SvarTemp > simpleMap) static private
Definition at line 126 of file ProcParameter.java.
References wrimsv2.wreslplus.elements.SvarTemp.caseCondition, wrimsv2.wreslplus.elements.SvarTemp.caseExpression, and wrimsv2.wreslplus.elements.SvarTemp.caseName.
Referenced by process().
evaluateAllParams()
void wrimsv2.wreslplus.elements.procedures.ProcParameter.evaluateAllParams (ArrayList< String > keyList, Map< String, Svar > map) static private
Definition at line 39 of file ProcParameter.java.
References callBooleanEvaluator(), callNumberEvaluator(), wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, and wrimsv2.commondata.wresldata.Svar.setData().
Referenced by process().
process()
void wrimsv2.wreslplus.elements.procedures.ProcParameter.process (StudyTemp st) static
Definition at line 29 of file ProcParameter.java.
References wrimsv2.wreslplus.elements.StudyTemp.controlDataParameterMap, convertParamMapToSvarMap(), evaluateAllParams(), wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.components.ControlData.parameterMap, and wrimsv2.wreslplus.elements.StudyTemp.parameterMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ProcParameter.java