Wrims-engine: wrimsv2.evaluator.DssDataSet Class Reference
wrimsv2.evaluator.DssDataSet Class Reference
Public Member Functions
boolean fromDssFile ()
void generateStudyStartIndex ()
String getConvertToUnits ()
ArrayList< Double > getData ()
String getKind ()
Date getStartTime ()
int getStudyStartIndex ()
ArrayList< Double > getTimeseriesDataWithOptions (String selMon, Date selSd, Date selEd)
String getTimeStep ()
String getUnits ()
void setConvertToUnits (String convertToUnits)
void setData (ArrayList< Double > data)
void setFromDssFile (boolean fromDssFile)
void setKind (String kind)
void setStartTime (Date st)
void setTimeStep (String timeStep)
void setUnits (String units)
Static Public Member Functions
static double getExceedance (ArrayList< Double > optedData, double exc)
static int getExceedance_tsi (ArrayList< Double > optedData, double exc)
Private Attributes
String convertToUnits =""
ArrayList< Double > data
boolean fromDssFile =false
String kind
Date startTime
int studyStartIndex =-1
String timeStep
String units
Static Private Attributes
static HashMap< Double, Date > selDataMap =new HashMap<Double, Date>()
Detailed Description
Definition at line 15 of file DssDataSet.java.
Member Function Documentation
fromDssFile()
boolean wrimsv2.evaluator.DssDataSet.fromDssFile ()
Definition at line 50 of file DssDataSet.java.
References fromDssFile.
generateStudyStartIndex()
void wrimsv2.evaluator.DssDataSet.generateStudyStartIndex ()
Definition at line 82 of file DssDataSet.java.
References getStartTime(), getTimeStep(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and studyStartIndex.
Referenced by wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
getConvertToUnits()
String wrimsv2.evaluator.DssDataSet.getConvertToUnits ()
Definition at line 62 of file DssDataSet.java.
References convertToUnits.
Referenced by wrimsv2.evaluator.CsvOperation.ouputCSV().
getData()
ArrayList< Double > wrimsv2.evaluator.DssDataSet.getData ()
Definition at line 30 of file DssDataSet.java.
References data.
Referenced by wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.DebugInterface.modifyTimeSeries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), wrimsv2.evaluator.ValueEvaluation.svarTimeSeries(), wrimsv2.components.ControllerDebug.updateVarMonitor(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
getExceedance()
double wrimsv2.evaluator.DssDataSet.getExceedance (ArrayList< Double > optedData, double exc) static
Definition at line 159 of file DssDataSet.java.
References wrimsv2.components.Error.addEvaluationError().
Referenced by wrimsv2.evaluator.Evaluation.exceedance(), and wrimsv2.evaluator.ValueEvaluation.exceedance().
getExceedance_tsi()
int wrimsv2.evaluator.DssDataSet.getExceedance_tsi (ArrayList< Double > optedData, double exc) static
Definition at line 182 of file DssDataSet.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), selDataMap, and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.evaluator.Evaluation.exceedance_tsi(), and wrimsv2.evaluator.ValueEvaluation.exceedance_tsi().
getKind()
String wrimsv2.evaluator.DssDataSet.getKind ()
Definition at line 78 of file DssDataSet.java.
References kind.
Referenced by wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
getStartTime()
Date wrimsv2.evaluator.DssDataSet.getStartTime ()
Definition at line 42 of file DssDataSet.java.
References startTime.
Referenced by generateStudyStartIndex(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), wrimsv2.evaluator.Evaluation.timeSeriesIndex(), wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
getStudyStartIndex()
int wrimsv2.evaluator.DssDataSet.getStudyStartIndex ()
Definition at line 101 of file DssDataSet.java.
References studyStartIndex.
Referenced by wrimsv2.evaluator.Evaluation.svarTimeSeries(), and wrimsv2.evaluator.ValueEvaluation.svarTimeSeries().
getTimeseriesDataWithOptions()
ArrayList< Double > wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions (String selMon, Date selSd, Date selEd)
Definition at line 105 of file DssDataSet.java.
References wrimsv2.evaluator.TimeOperation.addOneDay(), wrimsv2.evaluator.TimeOperation.addOneMonth(), wrimsv2.evaluator.TimeOperation.backOneDay(), wrimsv2.evaluator.TimeOperation.backOneMonth(), data, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.TimeOperation.range(), selDataMap, startTime, and timeStep.
Referenced by wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), and wrimsv2.evaluator.ValueEvaluation.exceedance_tsi().
getTimeStep()
String wrimsv2.evaluator.DssDataSet.getTimeStep ()
Definition at line 46 of file DssDataSet.java.
References timeStep.
Referenced by generateStudyStartIndex(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), wrimsv2.evaluator.Evaluation.timeSeriesIndex(), wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
getUnits()
String wrimsv2.evaluator.DssDataSet.getUnits ()
Definition at line 70 of file DssDataSet.java.
References units.
Referenced by wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
setConvertToUnits()
void wrimsv2.evaluator.DssDataSet.setConvertToUnits (String convertToUnits)
Definition at line 66 of file DssDataSet.java.
References convertToUnits.
Referenced by wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), and wrimsv2.evaluator.DssOperation.getSVTimeseries().
setData()
void wrimsv2.evaluator.DssDataSet.setData (ArrayList< Double > data)
Definition at line 26 of file DssDataSet.java.
References data.
Referenced by wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
setFromDssFile()
void wrimsv2.evaluator.DssDataSet.setFromDssFile (boolean fromDssFile)
Definition at line 54 of file DssDataSet.java.
References fromDssFile.
Referenced by wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
setKind()
void wrimsv2.evaluator.DssDataSet.setKind (String kind)
Definition at line 74 of file DssDataSet.java.
References kind.
Referenced by wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
setStartTime()
void wrimsv2.evaluator.DssDataSet.setStartTime (Date st)
Definition at line 38 of file DssDataSet.java.
References startTime.
Referenced by wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
setTimeStep()
void wrimsv2.evaluator.DssDataSet.setTimeStep (String timeStep)
Definition at line 34 of file DssDataSet.java.
References timeStep.
Referenced by wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
setUnits()
void wrimsv2.evaluator.DssDataSet.setUnits (String units)
Definition at line 58 of file DssDataSet.java.
References units.
Referenced by wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), and wrimsv2.sql.DssToSQLDatabase.readDssData().
Member Data Documentation
convertToUnits
String wrimsv2.evaluator.DssDataSet.convertToUnits ="" private
Definition at line 19 of file DssDataSet.java.
Referenced by getConvertToUnits(), and setConvertToUnits().
data
ArrayList<Double> wrimsv2.evaluator.DssDataSet.data private
Definition at line 16 of file DssDataSet.java.
Referenced by getData(), getTimeseriesDataWithOptions(), and setData().
fromDssFile
boolean wrimsv2.evaluator.DssDataSet.fromDssFile =false private
Definition at line 22 of file DssDataSet.java.
Referenced by fromDssFile(), setFromDssFile(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), and wrimsv2.evaluator.ValueEvaluation.svarTimeSeries().
kind
String wrimsv2.evaluator.DssDataSet.kind private
Definition at line 20 of file DssDataSet.java.
Referenced by getKind(), and setKind().
selDataMap
HashMap<Double, Date> wrimsv2.evaluator.DssDataSet.selDataMap =new HashMap<Double, Date>() static private
Definition at line 24 of file DssDataSet.java.
Referenced by getExceedance_tsi(), and getTimeseriesDataWithOptions().
startTime
Date wrimsv2.evaluator.DssDataSet.startTime private
Definition at line 21 of file DssDataSet.java.
Referenced by getStartTime(), getTimeseriesDataWithOptions(), and setStartTime().
studyStartIndex
int wrimsv2.evaluator.DssDataSet.studyStartIndex =-1 private
Definition at line 23 of file DssDataSet.java.
Referenced by generateStudyStartIndex(), and getStudyStartIndex().
timeStep
String wrimsv2.evaluator.DssDataSet.timeStep private
Definition at line 17 of file DssDataSet.java.
Referenced by getTimeseriesDataWithOptions(), getTimeStep(), and setTimeStep().
units
String wrimsv2.evaluator.DssDataSet.units private
Definition at line 18 of file DssDataSet.java.
Referenced by getUnits(), and setUnits().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/DssDataSet.java