Wrims-engine: wrimsv2.wreslplus.elements.procedures.ProcGoal Class Reference
wrimsv2.wreslplus.elements.procedures.ProcGoal Class Reference
Static Public Member Functions
static Map< String, String > convertPenalty (GoalTemp goal, String goalName, int caseIndex, String lhs, GoalCase cm)
static boolean isConstrain (String v)
static boolean isFree (String v)
static boolean isNumber (String v)
static void processGoalHS2 (ModelTemp mObj)
static void processGoalHS2 (ModelTemp mt, SequenceTemp seq)
static void processGoalHS2 (StudyTemp st)
Private Member Functions
ProcGoal ()
Detailed Description
Definition at line 18 of file ProcGoal.java.
Constructor & Destructor Documentation
ProcGoal()
wrimsv2.wreslplus.elements.procedures.ProcGoal.ProcGoal () private
Definition at line 20 of file ProcGoal.java.
Referenced by convertPenalty(), and processGoalHS2().
Member Function Documentation
convertPenalty()
Map< String, String > wrimsv2.wreslplus.elements.procedures.ProcGoal.convertPenalty (GoalTemp goal, String goalName, int caseIndex, String lhs, GoalCase cm) static
Definition at line 185 of file ProcGoal.java.
References ProcGoal(), wrimsv2.wreslplus.elements.GoalCase.lhs_gt_rhs, wrimsv2.wreslplus.elements.GoalCase.lhs_lt_rhs, wrimsv2.wreslplus.elements.GoalCase.rhs, and wrimsv2.wreslplus.elements.GoalTemp.timeArraySize.
isConstrain()
boolean wrimsv2.wreslplus.elements.procedures.ProcGoal.isConstrain (String v) static
Definition at line 342 of file ProcGoal.java.
References wrimsv2.commondata.wresldata.Param.constrain.
isFree()
boolean wrimsv2.wreslplus.elements.procedures.ProcGoal.isFree (String v) static
Definition at line 348 of file ProcGoal.java.
isNumber()
boolean wrimsv2.wreslplus.elements.procedures.ProcGoal.isNumber (String v) static
Definition at line 363 of file ProcGoal.java.
processGoalHS2() [1/3]
void wrimsv2.wreslplus.elements.procedures.ProcGoal.processGoalHS2 (ModelTemp mObj) static
Definition at line 76 of file ProcGoal.java.
References ProcGoal(), wrimsv2.wreslplus.elements.GoalTemp.caseCondition, wrimsv2.wreslplus.elements.GoalTemp.caseExpression, wrimsv2.wreslplus.elements.GoalTemp.caseMap, wrimsv2.wreslplus.elements.GoalTemp.caseName, wrimsv2.wreslplus.elements.GoalCase.condition, wrimsv2.commondata.wresldata.Param.conditional, wrimsv2.wreslplus.elements.GoalTemp.dvarSlackSurplusList, wrimsv2.wreslplus.elements.GoalTemp.dvarWeightMapList, wrimsv2.wreslplus.elements.GoalTemp.fromWresl, wrimsv2.wreslplus.elements.ModelTemp.gl2List, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.wreslplus.elements.GoalTemp.hasCase, wrimsv2.wreslplus.elements.GoalTemp.id, wrimsv2.wreslplus.elements.GoalTemp.lhs, wrimsv2.wreslplus.elements.GoalTemp.slackList, wrimsv2.wreslplus.elements.ModelTemp.ssList_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssList_noCase, wrimsv2.wreslplus.elements.ModelTemp.ssMap_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssMap_noCase, wrimsv2.wreslplus.elements.ModelTemp.ssWeightMap_hasCase, wrimsv2.wreslplus.elements.ModelTemp.ssWeightMap_noCase, wrimsv2.wreslplus.elements.GoalTemp.surplusList, wrimsv2.wreslplus.elements.DvarTemp.timeArraySize, wrimsv2.wreslplus.elements.GoalTemp.timeArraySize, wrimsv2.wreslplus.elements.WeightTemp.timeArraySize, and wrimsv2.wreslplus.elements.WeightTemp.weight.
processGoalHS2() [2/3]
void wrimsv2.wreslplus.elements.procedures.ProcGoal.processGoalHS2 (ModelTemp mt, SequenceTemp seq) static
Definition at line 70 of file ProcGoal.java.
References processGoalHS2().
processGoalHS2() [3/3]
void wrimsv2.wreslplus.elements.procedures.ProcGoal.processGoalHS2 (StudyTemp st) static
Definition at line 23 of file ProcGoal.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList_post, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, processGoalHS2(), wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), processGoalHS2(), and processGoalHS2().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ProcGoal.java