Wrims-engine: wrimsv2.commondata.solverdata.SolverData Class Reference
wrimsv2.commondata.solverdata.SolverData Class Reference
Static Public Member Functions
static void clearConstraintDataMap ()
static void clearDvarMap ()
static void clearWeightMap ()
static void clearWeightSlackSurplusMap ()
static ConcurrentHashMap< String, EvalConstraint > getConstraintDataMap ()
static ConcurrentHashMap< String, Dvar > getDvarMap ()
static ConcurrentHashMap< String, WeightElement > getWeightMap ()
static ConcurrentHashMap< String, WeightElement > getWeightSlackSurplusMap ()
Static Private Attributes
static ConcurrentHashMap< String, EvalConstraint > constraintDataMap =new ConcurrentHashMap<String, EvalConstraint>()
static ConcurrentHashMap< String, Dvar > dvarMap = new ConcurrentHashMap<String, Dvar>()
static ConcurrentHashMap< String, WeightElement > weightMap = new ConcurrentHashMap<String, WeightElement>()
static ConcurrentHashMap< String, WeightElement > weightSlackSurplusMap = new ConcurrentHashMap<String, WeightElement>()
Detailed Description
Definition at line 13 of file SolverData.java.
Member Function Documentation
clearConstraintDataMap()
void wrimsv2.commondata.solverdata.SolverData.clearConstraintDataMap () static
Definition at line 47 of file SolverData.java.
References constraintDataMap.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processGoal().
clearDvarMap()
void wrimsv2.commondata.solverdata.SolverData.clearDvarMap () static
Definition at line 39 of file SolverData.java.
References dvarMap.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processDvar().
clearWeightMap()
void wrimsv2.commondata.solverdata.SolverData.clearWeightMap () static
Definition at line 23 of file SolverData.java.
References weightMap.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processWeight().
clearWeightSlackSurplusMap()
void wrimsv2.commondata.solverdata.SolverData.clearWeightSlackSurplusMap () static
Definition at line 31 of file SolverData.java.
References weightSlackSurplusMap.
Referenced by wrimsv2.commondata.wresldata.ModelDataSet.processWeightSlackSurplus().
getConstraintDataMap()
ConcurrentHashMap< String, EvalConstraint > wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap () static
Definition at line 43 of file SolverData.java.
References constraintDataMap.
Referenced by wrimsv2.tools.CheckWeightSlackSurplus.CheckWeightSlackSurplus(), wrimsv2.tools.MultiStepAnalyzer.MultiStepAnalyzer(), wrimsv2.tools.RCCComparison.RCCComparison(), wrimsv2.tools.RCCComparison.compareConstraint(), wrimsv2.ilp.ILP.findDvarInConstraint(), wrimsv2.components.DebugInterface.getAllControlGoalName(), wrimsv2.components.DebugInterface.getAllGoalFile(), wrimsv2.components.DebugInterface.getAllGoalString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.commondata.wresldata.ModelDataSet.processGoal(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), wrimsv2.solver.CbcSolver.setConstraintsSkip(), wrimsv2.ilp.AmplWriter.writeConstraint(), wrimsv2.ilp.CplexLpWriter.writeConstraint(), wrimsv2.ilp.LpSolveWriter.writeConstraint(), and wrimsv2.solver.mpmodel.export.CplexExport.writeConstraint().
getDvarMap()
ConcurrentHashMap< String, Dvar > wrimsv2.commondata.solverdata.SolverData.getDvarMap () static
Definition at line 35 of file SolverData.java.
References dvarMap.
Referenced by wrimsv2.tools.RCCComparison.RCCComparison(), wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.components.DebugInterface.getAllControlGoalName(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.solver.CbcSolver.loadProblemIIS(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.solver.ClpSolver.newProblem(), wrimsv2.ilp.ILP.prepareDvarToWrite(), wrimsv2.commondata.wresldata.ModelDataSet.processDvar(), wrimsv2.solver.CbcSolver.reloadProblem(), wrimsv2.solver.CbcSolver.reloadProblemConfirm(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setDVars(), wrimsv2.solver.ortools.Misc.setDVars(), wrimsv2.solver.XASolver.setDVars(), wrimsv2.solver.CbcSolver.solve(), wrimsv2.solver.CbcSolver.violationCheck(), wrimsv2.ilp.AmplWriter.writeDvar(), wrimsv2.ilp.AmplWriter.writeDvar(), wrimsv2.ilp.CplexLpWriter.writeDvar(), wrimsv2.ilp.LpSolveWriter.writeDvar(), wrimsv2.ilp.LpSolveWriter.writeDvar(), wrimsv2.solver.mpmodel.export.CplexExport.writeDvar(), and wrimsv2.ilp.AmplWriter.writeDvarValue().
getWeightMap()
ConcurrentHashMap< String, WeightElement > wrimsv2.commondata.solverdata.SolverData.getWeightMap () static
Definition at line 19 of file SolverData.java.
References weightMap.
Referenced by wrimsv2.tools.RCCComparison.RCCComparison(), wrimsv2.ilp.ILP.findActiveWeightMap(), wrimsv2.ilp.ILP.findWeightedDvar(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.ilp.ILP.prepareDvarToWrite(), wrimsv2.commondata.wresldata.ModelDataSet.processWeight(), wrimsv2.solver.CbcSolver.setDVars(), wrimsv2.solver.Gurobi.GurobiSolver.setDVars(), wrimsv2.solver.CbcSolver.setDVars2021(), wrimsv2.solver.ClpSolver.setWeights(), wrimsv2.solver.ortools.Misc.setWeights(), wrimsv2.solver.XASolver.setWeights(), wrimsv2.ilp.AmplWriter.writeDvarValue(), and wrimsv2.ilp.AmplWriter.writeObj().
getWeightSlackSurplusMap()
ConcurrentHashMap< String, WeightElement > wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap () static
Definition at line 27 of file SolverData.java.
References weightSlackSurplusMap.
Referenced by wrimsv2.tools.CheckWeightSlackSurplus.CheckWeightSlackSurplus(), wrimsv2.ilp.ILP.findActiveWeightMap(), wrimsv2.components.DebugInterface.getAllVariableFiles(), wrimsv2.components.DebugInterface.getAllVariableString(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.commondata.wresldata.ModelDataSet.processWeightSlackSurplus(), wrimsv2.solver.ClpSolver.setWeights(), wrimsv2.solver.ortools.Misc.setWeights(), and wrimsv2.solver.XASolver.setWeights().
Member Data Documentation
constraintDataMap
ConcurrentHashMap<String, EvalConstraint> wrimsv2.commondata.solverdata.SolverData.constraintDataMap =new ConcurrentHashMap<String, EvalConstraint>() static private
Definition at line 14 of file SolverData.java.
Referenced by clearConstraintDataMap(), and getConstraintDataMap().
dvarMap
ConcurrentHashMap<String, Dvar> wrimsv2.commondata.solverdata.SolverData.dvarMap = new ConcurrentHashMap<String, Dvar>() static private
Definition at line 15 of file SolverData.java.
Referenced by clearDvarMap(), and getDvarMap().
weightMap
ConcurrentHashMap<String, WeightElement> wrimsv2.commondata.solverdata.SolverData.weightMap = new ConcurrentHashMap<String, WeightElement>() static private
Definition at line 16 of file SolverData.java.
Referenced by clearWeightMap(), and getWeightMap().
weightSlackSurplusMap
ConcurrentHashMap<String, WeightElement> wrimsv2.commondata.solverdata.SolverData.weightSlackSurplusMap = new ConcurrentHashMap<String, WeightElement>() static private
Definition at line 17 of file SolverData.java.
Referenced by clearWeightSlackSurplusMap(), and getWeightSlackSurplusMap().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/commondata/solverdata/SolverData.java