Wrims-engine: wrimsv2.sql.DssToSQLDatabase Class Reference
wrimsv2.sql.DssToSQLDatabase Class Reference
Public Member Functions
DssToSQLDatabase (String[] args)
void convertData ()
void dssReader (String[] dssFilePaths)
boolean getDssFilePaths ()
HashMap< String, DssDataSet > readDssData (String dssPath)
HashMap< String, DssDataSetFixLength > readDssDataFixLength (String dssPath)
void setSQLAttr (String dvFilePath)
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static String dssInfoFilePath =""
Private Attributes
ArrayList< String[]> dssFilePathArr =new ArrayList<String[]> ()
Detailed Description
Definition at line 36 of file DssToSQLDatabase.java.
Constructor & Destructor Documentation
DssToSQLDatabase()
wrimsv2.sql.DssToSQLDatabase.DssToSQLDatabase (String[] args)
Definition at line 41 of file DssToSQLDatabase.java.
References convertData(), dssFilePathArr, dssReader(), getDssFilePaths(), and setSQLAttr().
Referenced by main().
Member Function Documentation
convertData()
void wrimsv2.sql.DssToSQLDatabase.convertData ()
Definition at line 66 of file DssToSQLDatabase.java.
References wrimsv2.components.ControlData.databaseURL, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.ControlData.isSimOutput, wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.sql.MySQLRWriter.process(), and wrimsv2.sql.SQLServerRWriter.process().
Referenced by DssToSQLDatabase().
dssReader()
void wrimsv2.sql.DssToSQLDatabase.dssReader (String[] dssFilePaths)
Definition at line 116 of file DssToSQLDatabase.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, readDssData(), readDssDataFixLength(), and wrimsv2.evaluator.DataTimeSeries.svTS.
Referenced by DssToSQLDatabase().
getDssFilePaths()
boolean wrimsv2.sql.DssToSQLDatabase.getDssFilePaths ()
Definition at line 82 of file DssToSQLDatabase.java.
References dssFilePathArr, dssInfoFilePath, wrimsv2.components.ControlData.partA, and wrimsv2.components.ControlData.svDvPartF.
Referenced by DssToSQLDatabase().
main()
void wrimsv2.sql.DssToSQLDatabase.main (String[] args) static
Definition at line 54 of file DssToSQLDatabase.java.
References DssToSQLDatabase().
readDssData()
HashMap< String, DssDataSet > wrimsv2.sql.DssToSQLDatabase.readDssData (String dssPath)
Definition at line 126 of file DssToSQLDatabase.java.
References wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.generateStudyStartIndex(), wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths(), wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setFromDssFile(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), and wrimsv2.evaluator.DssDataSet.setUnits().
Referenced by dssReader().
readDssDataFixLength()
HashMap< String, DssDataSetFixLength > wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength (String dssPath)
Definition at line 159 of file DssToSQLDatabase.java.
References wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths(), wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord(), wrimsv2.evaluator.DssDataSetFixLength.setData(), wrimsv2.evaluator.DssDataSetFixLength.setFromDssFile(), wrimsv2.evaluator.DssDataSetFixLength.setKind(), wrimsv2.evaluator.DssDataSetFixLength.setStartTime(), wrimsv2.evaluator.DssDataSetFixLength.setTimeStep(), and wrimsv2.evaluator.DssDataSetFixLength.setUnits().
Referenced by dssReader().
setSQLAttr()
void wrimsv2.sql.DssToSQLDatabase.setSQLAttr (String dvFilePath)
Definition at line 58 of file DssToSQLDatabase.java.
References wrimsv2.components.FilePaths.dvarDssDirectory, wrimsv2.components.FilePaths.fullDvarDssPath, and wrimsv2.components.FilePaths.sqlScenarioName.
Referenced by DssToSQLDatabase().
Member Data Documentation
dssFilePathArr
ArrayList<String[]> wrimsv2.sql.DssToSQLDatabase.dssFilePathArr =new ArrayList<String[]> () private
Definition at line 39 of file DssToSQLDatabase.java.
Referenced by DssToSQLDatabase(), and getDssFilePaths().
dssInfoFilePath
String wrimsv2.sql.DssToSQLDatabase.dssInfoFilePath ="" static
Definition at line 38 of file DssToSQLDatabase.java.
Referenced by wrimsv2.sql.DataBaseProfile.DataBaseProfile(), and getDssFilePaths().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/sql/DssToSQLDatabase.java