Wrims-engine: wrimsv2.wreslparser.elements.SimulationDataSet Class Reference
wrimsv2.wreslparser.elements.SimulationDataSet Class Reference
Public Member Functions
SimulationDataSet ()
SimulationDataSet (SimulationDataSet s)
SimulationDataSet add (SimulationDataSet s)
SimulationDataSet addChildren (String nodeFile, Map< String, Set< String > > t1Map, Map< String, SimulationDataSet > fileDataMap)
SimulationDataSet addNonDuplicate (SimulationDataSet s)
SimulationDataSet convertToLocal ()
SimulationDataSet convertToLocal_set ()
SimulationDataSet dePrioritize (SimulationDataSet laterFileData, String filePath_forErrorMessage, Map< String, Set< String > > reverseMap)
Set< String > getAllGlobalVarsSet_except_file_and_weight ()
Set< String > getAllLocalVarsSet_except_file_and_weight ()
Set< String > getAllVarsSet_except_file_and_weight ()
SimulationDataSet getGlobalVars ()
SimulationDataSet getGlobalVars_set ()
Set< String > getSvarAliasExternTimeseries ()
boolean hasDuplicateIn (SimulationDataSet s, String filePath, Map< String, Set< String > > reverseMap)
SimulationDataSet insert (SimulationDataSet s)
void lousyConvert ()
SimulationDataSet overwrite (SimulationDataSet s)
SimulationDataSet overwrite_set (SimulationDataSet s)
SimulationDataSet overwrite_set (SimulationDataSet s, boolean errMessage)
SimulationDataSet overwrittenWith (SimulationDataSet s)
SimulationDataSet overwrittenWith_set (SimulationDataSet s)
SimulationDataSet prioritize_append (SimulationDataSet laterFileData, String filePath_forErrorMessage, Map< String, Set< String > > reverseMap)
SimulationDataSet prioritize_prepend (SimulationDataSet laterFileData, String filePath_forErrorMessage, Map< String, Set< String > > reverseMap)
SimulationDataSet remove (SimulationDataSet s)
SimulationDataSet remove_set (Set< String > s)
SimulationDataSet replaceGlobalWithDuplicateGlobal (Set< String > keys, SimulationDataSet s)
SimulationDataSet replaceGlobalWithDuplicateLocal (Set< String > keys, SimulationDataSet s) throws TypeRedefinedException
Public Attributes
ArrayList< String > asList = new ArrayList<String>()
ArrayList< String > asList_global = new ArrayList<String>()
ArrayList< String > asList_local = new ArrayList<String>()
Map< String, Alias > asMap = new HashMap<String, Alias>()
Set< String > asSet = new LinkedHashSet<String>()
Set< String > asSet_global = new LinkedHashSet<String>()
Set< String > asSet_local = new LinkedHashSet<String>()
Set< String > asSet_unknown = new LinkedHashSet<String>()
String currentAbsoluteParent
String currentAbsolutePath
ArrayList< String > dvList = new ArrayList<String>()
ArrayList< String > dvList_global = new ArrayList<String>()
ArrayList< String > dvList_local = new ArrayList<String>()
Map< String, Dvar > dvMap = new HashMap<String, Dvar>()
Set< String > dvSet = new LinkedHashSet<String>()
Set< String > dvSet_global = new LinkedHashSet<String>()
Set< String > dvSet_local = new LinkedHashSet<String>()
ArrayList< String > error_includeFile_redefined = new ArrayList<String>()
ArrayList< String > error_model_redefined = new ArrayList<String>()
ArrayList< Integer > error_sequence_order_redefined = new ArrayList<Integer>()
ArrayList< String > error_sequence_redefined = new ArrayList<String>()
Map< String, String > error_var_redefined = new HashMap<String, String>()
Map< String, String > error_weightVar_redefined = new HashMap<String, String>()
ArrayList< String > exList = new ArrayList<String>()
ArrayList< String > exList_global = new ArrayList<String>()
ArrayList< String > exList_local = new ArrayList<String>()
Map< String, External > exMap = new HashMap<String, External>()
Set< String > exSet = new LinkedHashSet<String>()
Set< String > exSet_global = new LinkedHashSet<String>()
Set< String > exSet_local = new LinkedHashSet<String>()
ArrayList< String > gList = new ArrayList<String>()
ArrayList< String > gList_global = new ArrayList<String>()
ArrayList< String > gList_local = new ArrayList<String>()
Map< String, Goal > gMap = new HashMap<String, Goal>()
Set< String > gSet = new LinkedHashSet<String>()
Set< String > gSet_global = new LinkedHashSet<String>()
Set< String > gSet_local = new LinkedHashSet<String>()
ArrayList< String > incFileList = new ArrayList<String>()
ArrayList< String > incFileList_global = new ArrayList<String>()
ArrayList< String > incFileList_local = new ArrayList<String>()
Map< String, IncludeFile > incFileMap = new HashMap<String, IncludeFile>()
Set< String > incFileSet = new LinkedHashSet<String>()
Set< String > incFileSet_global = new LinkedHashSet<String>()
Set< String > incFileSet_local = new LinkedHashSet<String>()
ArrayList< String > model_list = new ArrayList<String>()
ArrayList< String > ordered_list = new ArrayList<String>()
ArrayList< String > ordered_list_global = new ArrayList<String>()
ArrayList< String > ordered_list_including_files = new ArrayList<String>()
ArrayList< String > ordered_list_including_files_global = new ArrayList<String>()
ArrayList< String > seqList = new ArrayList<String>()
Map< Integer, Sequence > seqMap = new HashMap<Integer, Sequence>()
ArrayList< String > svList = new ArrayList<String>()
ArrayList< String > svList_global = new ArrayList<String>()
ArrayList< String > svList_local = new ArrayList<String>()
Map< String, Svar > svMap = new HashMap<String, Svar>()
Set< String > svSet = new LinkedHashSet<String>()
Set< String > svSet_global = new LinkedHashSet<String>()
Set< String > svSet_local = new LinkedHashSet<String>()
Set< String > svSet_unknown = new LinkedHashSet<String>()
ArrayList< String > tsList = new ArrayList<String>()
ArrayList< String > tsList_global = new ArrayList<String>()
ArrayList< String > tsList_local = new ArrayList<String>()
Map< String, Timeseries > tsMap = new HashMap<String, Timeseries>()
Set< String > tsSet = new LinkedHashSet<String>()
Set< String > tsSet_global = new LinkedHashSet<String>()
Set< String > tsSet_local = new LinkedHashSet<String>()
Map< String, String > var_all = new HashMap<String, String>()
Map< String, Set< String > > var_neededVarCycle_map = new HashMap<String, Set<String>>()
Set< String > varNeedEarlierCycle = new LinkedHashSet<String>()
ArrayList< String > wtList = new ArrayList<String>()
ArrayList< String > wtList_global = new ArrayList<String>()
ArrayList< String > wtList_local = new ArrayList<String>()
Map< String, WeightElement > wtMap = new HashMap<String, WeightElement>()
Set< String > wtSet = new LinkedHashSet<String>()
Set< String > wtSet_global = new LinkedHashSet<String>()
Set< String > wtSet_local = new LinkedHashSet<String>()
Detailed Description
Definition at line 18 of file SimulationDataSet.java.
Constructor & Destructor Documentation
SimulationDataSet() [1/2]
wrimsv2.wreslparser.elements.SimulationDataSet.SimulationDataSet ()
Definition at line 113 of file SimulationDataSet.java.
Referenced by SimulationDataSet(), add(), addChildren(), addNonDuplicate(), convertToLocal(), convertToLocal_set(), dePrioritize(), getGlobalVars(), getGlobalVars_set(), hasDuplicateIn(), insert(), overwrite(), overwrite_set(), overwrite_set(), overwrittenWith(), overwrittenWith_set(), prioritize_append(), prioritize_prepend(), remove(), remove_set(), replaceGlobalWithDuplicateGlobal(), and replaceGlobalWithDuplicateLocal().
SimulationDataSet() [2/2]
wrimsv2.wreslparser.elements.SimulationDataSet.SimulationDataSet (SimulationDataSet s)
warning: this is partial copy
Definition at line 119 of file SimulationDataSet.java.
References SimulationDataSet(), and overwrittenWith_set().
Member Function Documentation
add()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.add (SimulationDataSet s)
Definition at line 433 of file SimulationDataSet.java.
References SimulationDataSet(), asList, asList_global, asList_local, asMap, dvList, dvList_global, dvList_local, dvMap, exList, exList_global, exList_local, exMap, gList, gList_global, gList_local, gMap, incFileList, incFileList_global, incFileList_local, incFileMap, model_list, seqList, seqMap, svList, svList_global, svList_local, svMap, tsList, tsList_global, tsList_local, tsMap, var_neededVarCycle_map, varNeedEarlierCycle, wtList, wtList_global, wtList_local, and wtMap.
Referenced by addNonDuplicate(), dePrioritize(), overwrite(), wrimsv2.wreslparser.elements.Tools.overwrite_set(), overwrittenWith(), and prioritize_append().
addChildren()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.addChildren (String nodeFile, Map< String, Set< String > > t1Map, Map< String, SimulationDataSet > fileDataMap)
Definition at line 549 of file SimulationDataSet.java.
References SimulationDataSet(), addChildren(), and overwrittenWith_set().
Referenced by addChildren(), and wrimsv2.wreslparser.elements.StudyParser.correctScopeAndPrioritize().
addNonDuplicate()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.addNonDuplicate (SimulationDataSet s)
Definition at line 507 of file SimulationDataSet.java.
References SimulationDataSet(), add(), and remove().
convertToLocal()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.convertToLocal ()
Definition at line 227 of file SimulationDataSet.java.
References SimulationDataSet().
convertToLocal_set()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.convertToLocal_set ()
Definition at line 912 of file SimulationDataSet.java.
References SimulationDataSet().
Referenced by wrimsv2.wreslparser.elements.Tools.correctDataScope_deep(), and wrimsv2.wreslparser.elements.Tools.correctDataScope_shallow().
dePrioritize()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.dePrioritize (SimulationDataSet laterFileData, String filePath_forErrorMessage, Map< String, Set< String > > reverseMap)
Definition at line 514 of file SimulationDataSet.java.
References SimulationDataSet(), add(), hasDuplicateIn(), and overwrite().
getAllGlobalVarsSet_except_file_and_weight()
Set< String > wrimsv2.wreslparser.elements.SimulationDataSet.getAllGlobalVarsSet_except_file_and_weight ()
Definition at line 941 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
getAllLocalVarsSet_except_file_and_weight()
Set< String > wrimsv2.wreslparser.elements.SimulationDataSet.getAllLocalVarsSet_except_file_and_weight ()
Definition at line 954 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
getAllVarsSet_except_file_and_weight()
Set< String > wrimsv2.wreslparser.elements.SimulationDataSet.getAllVarsSet_except_file_and_weight ()
Definition at line 967 of file SimulationDataSet.java.
getGlobalVars()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.getGlobalVars ()
Definition at line 273 of file SimulationDataSet.java.
References SimulationDataSet(), asList_global, dvList, dvList_global, dvMap, exList, exList_global, exMap, gList, gList_global, gMap, incFileList, incFileList_global, incFileMap, svList, svList_global, svMap, tsList, tsList_global, tsMap, var_neededVarCycle_map, varNeedEarlierCycle, wtList, wtList_global, and wtMap.
getGlobalVars_set()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.getGlobalVars_set ()
Definition at line 822 of file SimulationDataSet.java.
References SimulationDataSet(), asMap, asSet, asSet_global, dvMap, dvSet, dvSet_global, exMap, exSet, exSet_global, gMap, gSet, gSet_global, incFileMap, incFileSet, incFileSet_global, svMap, svSet, svSet_global, tsMap, tsSet, tsSet_global, var_neededVarCycle_map, varNeedEarlierCycle, wtMap, wtSet, and wtSet_global.
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
getSvarAliasExternTimeseries()
Set< String > wrimsv2.wreslparser.elements.SimulationDataSet.getSvarAliasExternTimeseries ()
Definition at line 980 of file SimulationDataSet.java.
hasDuplicateIn()
boolean wrimsv2.wreslparser.elements.SimulationDataSet.hasDuplicateIn (SimulationDataSet s, String filePath, Map< String, Set< String > > reverseMap)
Definition at line 140 of file SimulationDataSet.java.
References SimulationDataSet(), asList, asMap, dvList, dvMap, wrimsv2.wreslparser.elements.LogUtils.errMsg(), gList, gMap, incFileList, incFileMap, model_list, seqList, svList, svMap, tsList, tsMap, wtList, and wtMap.
Referenced by dePrioritize(), prioritize_append(), and prioritize_prepend().
insert()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.insert (SimulationDataSet s)
Definition at line 561 of file SimulationDataSet.java.
References SimulationDataSet(), asList, asList_global, asList_local, asMap, dvList, dvList_global, dvList_local, dvMap, exList, exList_global, exList_local, exMap, gList, gList_global, gList_local, gMap, incFileList, incFileList_global, incFileList_local, incFileMap, model_list, seqList, seqMap, svList, svList_global, svList_local, svMap, tsList, tsList_global, tsList_local, tsMap, var_neededVarCycle_map, varNeedEarlierCycle, wtList, wtList_global, wtList_local, and wtMap.
Referenced by prioritize_prepend().
lousyConvert()
void wrimsv2.wreslparser.elements.SimulationDataSet.lousyConvert ()
Definition at line 1119 of file SimulationDataSet.java.
Referenced by overwrittenWith_set(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
overwrite()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.overwrite (SimulationDataSet s)
Definition at line 132 of file SimulationDataSet.java.
References SimulationDataSet(), add(), and remove().
Referenced by dePrioritize().
overwrite_set() [1/2]
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.overwrite_set (SimulationDataSet s)
Definition at line 636 of file SimulationDataSet.java.
References SimulationDataSet(), and overwrite_set().
Referenced by overwrite_set(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
overwrite_set() [2/2]
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.overwrite_set (SimulationDataSet s, boolean errMessage)
Definition at line 639 of file SimulationDataSet.java.
References SimulationDataSet(), asMap, asSet, asSet_global, asSet_local, dvMap, dvSet, dvSet_global, dvSet_local, exMap, exSet, exSet_global, exSet_local, gMap, gSet, gSet_global, gSet_local, incFileMap, incFileSet, incFileSet_global, incFileSet_local, wrimsv2.wreslparser.elements.Tools.mapRemoveAll(), svMap, svSet, svSet_global, svSet_local, tsMap, tsSet, tsSet_global, tsSet_local, var_neededVarCycle_map, varNeedEarlierCycle, wtMap, wtSet, wtSet_global, and wtSet_local.
overwrittenWith()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.overwrittenWith (SimulationDataSet s)
Definition at line 125 of file SimulationDataSet.java.
References SimulationDataSet(), and add().
overwrittenWith_set()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.overwrittenWith_set (SimulationDataSet s)
Definition at line 1059 of file SimulationDataSet.java.
References SimulationDataSet(), asMap, asSet, asSet_global, asSet_local, dvMap, dvSet, dvSet_global, dvSet_local, exMap, exSet, exSet_global, exSet_local, gMap, gSet, gSet_global, gSet_local, incFileMap, incFileSet, incFileSet_global, incFileSet_local, lousyConvert(), svMap, svSet, svSet_global, svSet_local, tsMap, tsSet, tsSet_global, tsSet_local, var_neededVarCycle_map, varNeedEarlierCycle, wtMap, wtSet, wtSet_global, and wtSet_local.
Referenced by SimulationDataSet(), addChildren(), wrimsv2.wreslparser.elements.StudyParser.correctScopeAndPrioritize(), and wrimsv2.wreslparser.elements.Tools.overwrite_set().
prioritize_append()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.prioritize_append (SimulationDataSet laterFileData, String filePath_forErrorMessage, Map< String, Set< String > > reverseMap)
Definition at line 527 of file SimulationDataSet.java.
References SimulationDataSet(), add(), and hasDuplicateIn().
prioritize_prepend()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.prioritize_prepend (SimulationDataSet laterFileData, String filePath_forErrorMessage, Map< String, Set< String > > reverseMap)
Definition at line 538 of file SimulationDataSet.java.
References SimulationDataSet(), hasDuplicateIn(), and insert().
remove()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.remove (SimulationDataSet s)
Definition at line 355 of file SimulationDataSet.java.
References SimulationDataSet(), and wrimsv2.wreslparser.elements.Tools.mapRemoveAll().
Referenced by addNonDuplicate(), and overwrite().
remove_set()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.remove_set (Set< String > s)
Definition at line 992 of file SimulationDataSet.java.
References SimulationDataSet(), and wrimsv2.wreslparser.elements.Tools.mapRemoveAll().
replaceGlobalWithDuplicateGlobal()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.replaceGlobalWithDuplicateGlobal (Set< String > keys, SimulationDataSet s)
Definition at line 728 of file SimulationDataSet.java.
References SimulationDataSet(), asMap, dvMap, exMap, gMap, svMap, tsMap, and var_neededVarCycle_map.
replaceGlobalWithDuplicateLocal()
SimulationDataSet wrimsv2.wreslparser.elements.SimulationDataSet.replaceGlobalWithDuplicateLocal (Set< String > keys, SimulationDataSet s) throws TypeRedefinedException
Definition at line 771 of file SimulationDataSet.java.
References SimulationDataSet(), and wrimsv2.wreslparser.elements.LogUtils.typeRedefinedErrMsg().
Referenced by wrimsv2.wreslparser.elements.StudyParser.parseModels().
Member Data Documentation
asList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.asList = new ArrayList<String>()
Definition at line 96 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.wreslparser.elements.StudyParser.sortDependency(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
asList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.asList_global = new ArrayList<String>()
Definition at line 97 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), getGlobalVars(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
asList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.asList_local = new ArrayList<String>()
Definition at line 98 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
asMap
Map<String, Alias> wrimsv2.wreslparser.elements.SimulationDataSet.asMap = new HashMap<String, Alias>()
Definition at line 99 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars_set(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), overwrite_set(), overwrittenWith_set(), replaceGlobalWithDuplicateGlobal(), wrimsv2.wreslparser.elements.StudyParser.sortDependency(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
asSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.asSet = new LinkedHashSet<String>()
Definition at line 93 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.checkAliasInGoalExpression(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.StudyParser.convertRestAliasInGoalExpression(), getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), and wrimsv2.wreslparser.elements.StudyParser.sortDependency().
asSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.asSet_global = new LinkedHashSet<String>()
Definition at line 94 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), getGlobalVars_set(), overwrite_set(), and overwrittenWith_set().
asSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.asSet_local = new LinkedHashSet<String>()
Definition at line 95 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), overwrite_set(), and overwrittenWith_set().
asSet_unknown
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.asSet_unknown = new LinkedHashSet<String>()
Definition at line 92 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.sortDependency(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
currentAbsoluteParent
String wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsoluteParent
Definition at line 21 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.includeFile().
currentAbsolutePath
String wrimsv2.wreslparser.elements.SimulationDataSet.currentAbsolutePath
Definition at line 20 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.includeFile(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), wrimsv2.wreslparser.elements.StructTree.modelList(), wrimsv2.wreslparser.elements.StructTree.sequenceOrder(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
dvList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.dvList = new ArrayList<String>()
Definition at line 87 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), getGlobalVars(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global = new ArrayList<String>()
Definition at line 88 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), getGlobalVars(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local = new ArrayList<String>()
Definition at line 89 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvMap
Map<String, Dvar> wrimsv2.wreslparser.elements.SimulationDataSet.dvMap = new HashMap<String, Dvar>()
Definition at line 90 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), getGlobalVars(), getGlobalVars_set(), hasDuplicateIn(), insert(), overwrite_set(), overwrittenWith_set(), replaceGlobalWithDuplicateGlobal(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
dvSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.dvSet = new LinkedHashSet<String>()
Definition at line 84 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.checkAliasInGoalExpression(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), and wrimsv2.wreslparser.elements.StudyParser.sortDependency().
dvSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_global = new LinkedHashSet<String>()
Definition at line 85 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), getGlobalVars_set(), overwrite_set(), and overwrittenWith_set().
dvSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_local = new LinkedHashSet<String>()
Definition at line 86 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), overwrite_set(), and overwrittenWith_set().
error_includeFile_redefined
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.error_includeFile_redefined = new ArrayList<String>()
Definition at line 48 of file SimulationDataSet.java.
error_model_redefined
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.error_model_redefined = new ArrayList<String>()
Definition at line 24 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.modelList().
error_sequence_order_redefined
ArrayList<Integer> wrimsv2.wreslparser.elements.SimulationDataSet.error_sequence_order_redefined = new ArrayList<Integer>()
Definition at line 27 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.sequenceOrder().
error_sequence_redefined
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.error_sequence_redefined = new ArrayList<String>()
Definition at line 26 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.sequenceOrder().
error_var_redefined
Map<String, String> wrimsv2.wreslparser.elements.SimulationDataSet.error_var_redefined = new HashMap<String, String>()
Definition at line 57 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.includeFile(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
error_weightVar_redefined
Map<String, String> wrimsv2.wreslparser.elements.SimulationDataSet.error_weightVar_redefined = new HashMap<String, String>()
Definition at line 39 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), and wrimsv2.wreslparser.elements.StructTree.mergeWeightTable().
exList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.exList = new ArrayList<String>()
Definition at line 62 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.external(), getGlobalVars(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
exList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.exList_global = new ArrayList<String>()
Definition at line 63 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StructTree.external(), getGlobalVars(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
exList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.exList_local = new ArrayList<String>()
Definition at line 64 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.external(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
exMap
Map<String, External> wrimsv2.wreslparser.elements.SimulationDataSet.exMap = new HashMap<String, External>()
Definition at line 65 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.external(), getGlobalVars(), getGlobalVars_set(), insert(), overwrite_set(), overwrittenWith_set(), replaceGlobalWithDuplicateGlobal(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
exSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.exSet = new LinkedHashSet<String>()
Definition at line 59 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.external(), getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), and wrimsv2.wreslparser.elements.StudyParser.sortDependency().
exSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.exSet_global = new LinkedHashSet<String>()
Definition at line 60 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.external(), getGlobalVars_set(), overwrite_set(), and overwrittenWith_set().
exSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.exSet_local = new LinkedHashSet<String>()
Definition at line 61 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.external(), overwrite_set(), and overwrittenWith_set().
gList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.gList = new ArrayList<String>()
Definition at line 104 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), hasDuplicateIn(), insert(), wrimsv2.tools.InfeasibilityAnalysis.procIfsSelFiles(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
gList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.gList_global = new ArrayList<String>()
Definition at line 105 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), getGlobalVars(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
gList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.gList_local = new ArrayList<String>()
Definition at line 106 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), insert(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
gMap
Map<String, Goal> wrimsv2.wreslparser.elements.SimulationDataSet.gMap = new HashMap<String, Goal>()
Definition at line 107 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.checkAliasInGoalExpression(), wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars(), getGlobalVars_set(), wrimsv2.components.DebugInterface.getVariableInOneFile(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), hasDuplicateIn(), insert(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), replaceGlobalWithDuplicateGlobal(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
gSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.gSet = new LinkedHashSet<String>()
Definition at line 101 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.convertAlias(), getGlobalVars_set(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
gSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.gSet_global = new LinkedHashSet<String>()
Definition at line 102 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.convertAlias(), getGlobalVars_set(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), overwrite_set(), and overwrittenWith_set().
gSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.gSet_local = new LinkedHashSet<String>()
Definition at line 103 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.convertAlias(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), overwrite_set(), and overwrittenWith_set().
incFileList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.incFileList = new ArrayList<String>()
Definition at line 44 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), getGlobalVars(), wrimsv2.wreslparser.elements.StudyParser.getOrderedList(), wrimsv2.wreslparser.elements.Tools.getType1MapScope(), hasDuplicateIn(), wrimsv2.wreslparser.elements.StructTree.includeFile(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.FileParser.processNestedFile(), wrimsv2.wreslparser.elements.FileParser.processNestedFileIntoSimulationDataSetMap(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
incFileList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global = new ArrayList<String>()
Definition at line 45 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), getGlobalVars(), wrimsv2.wreslparser.elements.StructTree.includeFile(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
incFileList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local = new ArrayList<String>()
Definition at line 46 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), wrimsv2.wreslparser.elements.Tools.getType1MapScope(), wrimsv2.wreslparser.elements.StructTree.includeFile(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
incFileMap
Map<String, IncludeFile> wrimsv2.wreslparser.elements.SimulationDataSet.incFileMap = new HashMap<String, IncludeFile>()
Definition at line 47 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars(), getGlobalVars_set(), hasDuplicateIn(), wrimsv2.wreslparser.elements.StructTree.includeFile(), insert(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.FileParser.processNestedFileIntoSimulationDataSetMap().
incFileSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet = new LinkedHashSet<String>()
Definition at line 41 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.Tools.getFileScopeMap(), getGlobalVars_set(), wrimsv2.wreslparser.elements.Tools.getType1Map(), wrimsv2.wreslparser.elements.StructTree.includeFile(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), and wrimsv2.wreslparser.elements.FileParser.processNestedFileExceptFor().
incFileSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet_global = new LinkedHashSet<String>()
Definition at line 42 of file SimulationDataSet.java.
Referenced by getGlobalVars_set(), wrimsv2.wreslparser.elements.StructTree.includeFile(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
incFileSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet_local = new LinkedHashSet<String>()
Definition at line 43 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.Tools.getFileScopeMap(), wrimsv2.wreslparser.elements.StructTree.includeFile(), overwrite_set(), and overwrittenWith_set().
model_list
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.model_list = new ArrayList<String>()
Definition at line 23 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), hasDuplicateIn(), insert(), and wrimsv2.wreslparser.elements.StructTree.modelList().
ordered_list
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list = new ArrayList<String>()
Definition at line 51 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
ordered_list_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_global = new ArrayList<String>()
Definition at line 54 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
ordered_list_including_files
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files = new ArrayList<String>()
Definition at line 50 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StudyParser.getOrderedList(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.includeFile(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
ordered_list_including_files_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files_global = new ArrayList<String>()
Definition at line 53 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.includeFile(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
seqList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.seqList = new ArrayList<String>()
Definition at line 30 of file SimulationDataSet.java.
Referenced by add(), hasDuplicateIn(), insert(), and wrimsv2.wreslparser.elements.StructTree.sequenceOrder().
seqMap
Map<Integer, Sequence> wrimsv2.wreslparser.elements.SimulationDataSet.seqMap = new HashMap<Integer, Sequence>()
Definition at line 29 of file SimulationDataSet.java.
Referenced by add(), insert(), and wrimsv2.wreslparser.elements.StructTree.sequenceOrder().
svList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.svList = new ArrayList<String>()
Definition at line 79 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), getGlobalVars(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.wreslparser.elements.StudyParser.sortDependency(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
svList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.svList_global = new ArrayList<String>()
Definition at line 80 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), getGlobalVars(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
svList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.svList_local = new ArrayList<String>()
Definition at line 81 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), wrimsv2.wreslparser.elements.LogUtils.fileSummary(), insert(), wrimsv2.wreslparser.elements.LogUtils.mainFileSummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary(), wrimsv2.wreslparser.elements.LogUtils.studySummary_details(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
svMap
Map<String, Svar> wrimsv2.wreslparser.elements.SimulationDataSet.svMap = new HashMap<String, Svar>()
Definition at line 82 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars(), getGlobalVars_set(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), overwrite_set(), overwrittenWith_set(), replaceGlobalWithDuplicateGlobal(), wrimsv2.wreslparser.elements.StudyParser.sortDependency(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
svSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.svSet = new LinkedHashSet<String>()
Definition at line 76 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.checkAliasInGoalExpression(), getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.wreslparser.elements.StudyParser.sortDependency(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
svSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.svSet_global = new LinkedHashSet<String>()
Definition at line 77 of file SimulationDataSet.java.
Referenced by getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
svSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.svSet_local = new LinkedHashSet<String>()
Definition at line 78 of file SimulationDataSet.java.
Referenced by overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), and wrimsv2.wreslparser.elements.StructTree.svarTable().
svSet_unknown
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.svSet_unknown = new LinkedHashSet<String>()
Definition at line 75 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.sortDependency(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
tsList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.tsList = new ArrayList<String>()
Definition at line 70 of file SimulationDataSet.java.
Referenced by add(), getGlobalVars(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), wrimsv2.wreslparser.elements.StructTree.timeseriesDss(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
tsList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.tsList_global = new ArrayList<String>()
Definition at line 71 of file SimulationDataSet.java.
Referenced by add(), getGlobalVars(), insert(), wrimsv2.wreslparser.elements.StructTree.timeseriesDss(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
tsList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.tsList_local = new ArrayList<String>()
Definition at line 72 of file SimulationDataSet.java.
Referenced by add(), insert(), wrimsv2.wreslparser.elements.StructTree.timeseriesDss(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
tsMap
Map<String, Timeseries> wrimsv2.wreslparser.elements.SimulationDataSet.tsMap = new HashMap<String, Timeseries>()
Definition at line 73 of file SimulationDataSet.java.
Referenced by add(), getGlobalVars(), getGlobalVars_set(), hasDuplicateIn(), insert(), overwrite_set(), overwrittenWith_set(), replaceGlobalWithDuplicateGlobal(), wrimsv2.wreslparser.elements.StructTree.timeseriesDss(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
tsSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.tsSet = new LinkedHashSet<String>()
Definition at line 67 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StudyParser.checkAliasInGoalExpression(), wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined(), getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.wreslparser.elements.StudyParser.sortDependency(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
tsSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.tsSet_global = new LinkedHashSet<String>()
Definition at line 68 of file SimulationDataSet.java.
Referenced by getGlobalVars_set(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
tsSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.tsSet_local = new LinkedHashSet<String>()
Definition at line 69 of file SimulationDataSet.java.
Referenced by overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
var_all
Map<String, String> wrimsv2.wreslparser.elements.SimulationDataSet.var_all = new HashMap<String, String>()
Definition at line 56 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.alias(), wrimsv2.wreslparser.elements.StructTree.dvarNonStd(), wrimsv2.wreslparser.elements.StructTree.dvarSlackSurplus(), wrimsv2.wreslparser.elements.StructTree.dvarStd(), wrimsv2.wreslparser.elements.StructTree.external(), wrimsv2.wreslparser.elements.StructTree.goalCase(), wrimsv2.wreslparser.elements.StructTree.goalSimple(), wrimsv2.wreslparser.elements.StructTree.includeFile(), wrimsv2.wreslparser.elements.StructTree.modelList(), wrimsv2.wreslparser.elements.StructTree.svarCase(), wrimsv2.wreslparser.elements.StructTree.svarExpression(), wrimsv2.wreslparser.elements.StructTree.svarSum(), wrimsv2.wreslparser.elements.StructTree.svarTable(), and wrimsv2.wreslparser.elements.StructTree.timeseriesDss().
var_neededVarCycle_map
Map<String, Set<String> > wrimsv2.wreslparser.elements.SimulationDataSet.var_neededVarCycle_map = new HashMap<String, Set<String>>()
Definition at line 110 of file SimulationDataSet.java.
Referenced by add(), getGlobalVars(), getGlobalVars_set(), insert(), overwrite_set(), overwrittenWith_set(), and replaceGlobalWithDuplicateGlobal().
varNeedEarlierCycle
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.varNeedEarlierCycle = new LinkedHashSet<String>()
Definition at line 109 of file SimulationDataSet.java.
Referenced by add(), getGlobalVars(), getGlobalVars_set(), insert(), overwrite_set(), and overwrittenWith_set().
wtList
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.wtList = new ArrayList<String>()
Definition at line 35 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars(), wrimsv2.components.DebugInterface.getVariableInOneFile(), hasDuplicateIn(), insert(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
wtList_global
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.wtList_global = new ArrayList<String>()
Definition at line 36 of file SimulationDataSet.java.
Referenced by add(), getGlobalVars(), insert(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), and wrimsv2.wreslparser.elements.StructTree.mergeWeightTable().
wtList_local
ArrayList<String> wrimsv2.wreslparser.elements.SimulationDataSet.wtList_local = new ArrayList<String>()
Definition at line 37 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), insert(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), and wrimsv2.wreslparser.elements.StructTree.mergeWeightTable().
wtMap
Map<String, WeightElement> wrimsv2.wreslparser.elements.SimulationDataSet.wtMap = new HashMap<String, WeightElement>()
Definition at line 38 of file SimulationDataSet.java.
Referenced by add(), wrimsv2.wreslparser.elements.Tools.convertSimulationDataSetToLocal(), getGlobalVars(), getGlobalVars_set(), hasDuplicateIn(), insert(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
wtSet
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.wtSet = new LinkedHashSet<String>()
Definition at line 32 of file SimulationDataSet.java.
Referenced by getGlobalVars_set(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
wtSet_global
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_global = new LinkedHashSet<String>()
Definition at line 33 of file SimulationDataSet.java.
Referenced by getGlobalVars_set(), wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), overwrite_set(), overwrittenWith_set(), and wrimsv2.wreslparser.elements.StudyParser.parseModels().
wtSet_local
Set<String> wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_local = new LinkedHashSet<String>()
Definition at line 34 of file SimulationDataSet.java.
Referenced by wrimsv2.wreslparser.elements.StructTree.mergeSlackSurplusIntoWeightTable(), wrimsv2.wreslparser.elements.StructTree.mergeWeightTable(), overwrite_set(), and overwrittenWith_set().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/SimulationDataSet.java