Wrims-engine: wrimsv2.tools.solutionRangeFinder.Detector Class Reference
wrimsv2.tools.solutionRangeFinder.Detector Class Reference
Public Member Functions
Detector (MPModel mpm)
LinkedHashMap< String, double[]> detect (ArrayList< String > searchVarList)
void validateBase ()
void validateBase (double obj_constraint_relax_ratio)
Static Public Member Functions
static void main (String[] args) throws Exception
Private Attributes
DetectorWorkflow dwf = null
Detailed Description
Definition at line 13 of file Detector.java.
Constructor & Destructor Documentation
Detector()
wrimsv2.tools.solutionRangeFinder.Detector.Detector (MPModel mpm)
Definition at line 61 of file Detector.java.
References dwf.
Referenced by main().
Member Function Documentation
detect()
LinkedHashMap< String, double[]> wrimsv2.tools.solutionRangeFinder.Detector.detect (ArrayList< String > searchVarList)
Definition at line 88 of file Detector.java.
References wrimsv2.tools.solutionRangeFinder.DetectorParam.altSolutionFound, and dwf.
Referenced by main(), and wrimsv2.tools.solutionRangeFinder.Main.main().
main()
void wrimsv2.tools.solutionRangeFinder.Detector.main (String[] args) throws Exception static
Definition at line 17 of file Detector.java.
References Detector(), detect(), wrimsv2.solver.ortools.OrToolsSolver.initialize(), wrimsv2.solver.mpmodel.MPModelUtils.load(), wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsDir, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsFileNamePrepend, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsLogging, wrimsv2.tools.solutionRangeFinder.Misc.openReportFile(), wrimsv2.tools.solutionRangeFinder.DetectorParam.searchVarList, validateBase(), and wrimsv2.tools.solutionRangeFinder.Misc.writeReport().
validateBase() [1/2]
void wrimsv2.tools.solutionRangeFinder.Detector.validateBase ()
Definition at line 73 of file Detector.java.
References wrimsv2.tools.solutionRangeFinder.DetectorParam.obj_constraint_relax_ratio, and validateBase().
Referenced by main(), wrimsv2.tools.solutionRangeFinder.Main.main(), and validateBase().
validateBase() [2/2]
void wrimsv2.tools.solutionRangeFinder.Detector.validateBase (double obj_constraint_relax_ratio)
Definition at line 79 of file Detector.java.
References dwf.
Member Data Documentation
dwf
DetectorWorkflow wrimsv2.tools.solutionRangeFinder.Detector.dwf = null private
Definition at line 15 of file Detector.java.
Referenced by Detector(), detect(), and validateBase().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/solutionRangeFinder/Detector.java