Wrims-engine: wrimsv2.evaluator.Evaluation Class Reference
wrimsv2.evaluator.Evaluation Class Reference
Static Public Member Functions
static EvalExpression abs (EvalExpression ee1)
static IntDouble absOperation (IntDouble id1)
static EvalExpression acos (EvalExpression ee1)
static EvalExpression acot (EvalExpression ee1)
static EvalExpression add (EvalExpression ee1, EvalExpression ee2)
static IntDouble addOperation (IntDouble id1, IntDouble id2)
static EvalExpression argFunction (String ident, ArrayList< ArrayList< EvalExpression > > eeArray, Stack< LoopIndex > sumIndex)
static EvalExpression asin (EvalExpression ee1)
static Number assignWhereStatement (EvalExpression ee)
static EvalExpression atan (EvalExpression ee1)
static EvalConstraint constraintStatement (EvalExpression ee1, EvalExpression ee2, String s)
static String convertDoubleToString (double value)
static String convertIntToString (int value)
static double convertStringToDouble (String text)
static int convertStringToInt (String text)
static EvalExpression cos (EvalExpression ee1)
static EvalExpression cot (EvalExpression ee1)
static EvalExpression daysIn ()
static EvalExpression daysInTimeStep ()
static EvalExpression divide (EvalExpression ee1, EvalExpression ee2)
static IntDouble divideOperation (IntDouble id1, IntDouble id2)
static double dvarAliasCycleTimeSeries (String ident, int indexValue, int ci, ParallelVars prvs)
static double dvarAliasTimeSeries (String ident, int indexValue, ParallelVars prvs)
static double dvarAliasTimeSeries (String ident, ParallelVars prvs)
static EvalExpression exceedance (String tsName, EvalExpression exc_ee, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr)
static EvalExpression exceedance_tsi (String tsName, EvalExpression exc_ee, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr)
static EvalExpression exp (EvalExpression ee1)
static IntDouble expOperation (IntDouble id1)
static IntDouble expressionInput (EvalExpression ee)
static boolean getDVAliasInitTimeseries (String ident)
static boolean getSVInitTimeseries (String ident)
static EvalExpression getTimeSeries (String ident, ArrayList< EvalExpression > eeArray, Stack< LoopIndex > sumIndex)
static void initSumExpression (EvalExpression ee1, EvalExpression ee2, String s, Stack< LoopIndex > sumIndex)
static EvalExpression intFunc (EvalExpression ee1)
static IntDouble intOperation (IntDouble id1)
static EvalExpression log (EvalExpression ee1)
static EvalExpression log10 (EvalExpression ee1)
static IntDouble log10Operation (IntDouble id1)
static IntDouble logOperation (IntDouble id1)
static EvalExpression max (EvalExpression ee1, EvalExpression ee2)
static IntDouble maxOperation (IntDouble id1, IntDouble id2)
static EvalExpression min (EvalExpression ee1, EvalExpression ee2)
static IntDouble minOperation (IntDouble id1, IntDouble id2)
static EvalExpression mod (EvalExpression ee1, EvalExpression ee2)
static IntDouble modOperation (IntDouble id1, IntDouble id2)
static EvalExpression mult (EvalExpression ee1, EvalExpression ee2)
static IntDouble multiplyOperation (IntDouble id1, IntDouble id2)
static EvalExpression noArgFunction (String ident)
static IntDouble pastCycleIndexNoTimeArray (String ident, int index)
static IntDouble pastCycleIndexTimeArray (String ident, int pci, EvalExpression ee)
static IntDouble pastCycleNoTimeArray (String ident, String cycle)
static IntDouble pastCycleTimeArray (String ident, String cycle, EvalExpression ee)
static EvalExpression pastTSFV (String ident, EvalExpression ee1, ArrayList< ArrayList< EvalExpression > > eeArray, ParallelVars prvs)
static EvalExpression pow (EvalExpression ee1, EvalExpression ee2)
static IntDouble powOperation (IntDouble id1, IntDouble id2)
static boolean range (String m1, String m2)
static EvalExpression realFunc (EvalExpression ee1)
static IntDouble realOperation (IntDouble id1)
static boolean relationStatement (EvalExpression ee1, EvalExpression ee2, String relation)
static boolean relationStatementSeries (boolean r1, boolean r2, String s)
static EvalExpression round (EvalExpression ee1)
static EvalExpression sin (EvalExpression ee1)
static EvalExpression substract (EvalExpression ee1, EvalExpression ee2)
static IntDouble substractOperation (IntDouble id1, IntDouble id2)
static EvalExpression sumExpression (EvalExpression ee, String expression, Stack< LoopIndex > sumIndex)
static void sumExpression_IDENT (String ident, Stack< LoopIndex > sumIndex)
static double svarTimeSeries (String ident, int idValue, ParallelVars prvs)
static EvalExpression tableSQL (String table, String select, HashMap< String, Number > where, HashMap< String, Number > given, String use)
static double tafcfs (String ident, ParallelVars prvs)
static EvalExpression tafcfs_term (String ident, EvalExpression ee, Stack< LoopIndex > sumIndex)
static EvalExpression tan (EvalExpression ee1)
static EvalExpression term_ARRAY_ITERATOR (ParallelVars prvs)
static EvalExpression term_DAY ()
static EvalExpression term_FLOAT (String floatValue)
static EvalExpression term_IDENT (String ident, Stack< LoopIndex > sumIndex)
static EvalExpression term_INTEGER (String integer)
static EvalExpression term_knownTS (IntDouble result)
static EvalExpression term_MONTH ()
static EvalExpression term_MONTH_CONST (String month)
static EvalExpression term_PASTMONTH (String pastMonth)
static EvalExpression term_SVAR (String ident)
static EvalExpression term_YEAR ()
static EvalExpression timeseries ()
static double timeseries (String tsName)
static int timeSeriesIndex (DssDataSet dds, ParallelVars prvs)
static int timeSeriesIndex (DssDataSetFixLength dds, ParallelVars prvs)
static ArrayList< EvalExpression > trunk_timeArray (String ident, IntDouble start, IntDouble end)
static EvalExpression unary (String s, EvalExpression ee)
Detailed Description
Definition at line 31 of file Evaluation.java.
Member Function Documentation
abs()
EvalExpression wrimsv2.evaluator.Evaluation.abs (EvalExpression ee1) static
Definition at line 1449 of file Evaluation.java.
References absOperation(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
absOperation()
IntDouble wrimsv2.evaluator.Evaluation.absOperation (IntDouble id1) static
Definition at line 1456 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by abs().
acos()
EvalExpression wrimsv2.evaluator.Evaluation.acos (EvalExpression ee1) static
Definition at line 1591 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
acot()
EvalExpression wrimsv2.evaluator.Evaluation.acot (EvalExpression ee1) static
Definition at line 1611 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
add()
EvalExpression wrimsv2.evaluator.Evaluation.add (EvalExpression ee1, EvalExpression ee2) static
Definition at line 408 of file Evaluation.java.
References addOperation(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.setValue().
Referenced by sumExpression().
addOperation()
IntDouble wrimsv2.evaluator.Evaluation.addOperation (IntDouble id1, IntDouble id2) static
Definition at line 429 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by add().
argFunction()
EvalExpression wrimsv2.evaluator.Evaluation.argFunction (String ident, ArrayList< ArrayList< EvalExpression > > eeArray, Stack< LoopIndex > sumIndex) static
Definition at line 513 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.allExternalFunctionMap, wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.ControlData.currTsMap, wrimsv2.external.ExternalFunction.execute(), wrimsv2.components.IntDouble.getData(), getTimeSeries(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.evaluator.TimeOperation.month_const, wrimsv2.evaluator.ValueEvaluation.setSvarDoubleValue(), and wrimsv2.evaluator.ValueEvaluation.setSvarIntValue().
asin()
EvalExpression wrimsv2.evaluator.Evaluation.asin (EvalExpression ee1) static
Definition at line 1581 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
assignWhereStatement()
Number wrimsv2.evaluator.Evaluation.assignWhereStatement (EvalExpression ee) static
Definition at line 1913 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
atan()
EvalExpression wrimsv2.evaluator.Evaluation.atan (EvalExpression ee1) static
Definition at line 1601 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
constraintStatement()
EvalConstraint wrimsv2.evaluator.Evaluation.constraintStatement (EvalExpression ee1, EvalExpression ee2, String s) static
Definition at line 125 of file Evaluation.java.
References wrimsv2.evaluator.EvalConstraint.setEvalExpression(), wrimsv2.evaluator.EvalConstraint.setSign(), and substract().
convertDoubleToString()
String wrimsv2.evaluator.Evaluation.convertDoubleToString (double value) static
Definition at line 40 of file Evaluation.java.
convertIntToString()
String wrimsv2.evaluator.Evaluation.convertIntToString (int value) static
Definition at line 44 of file Evaluation.java.
Referenced by wrimsv2.evaluator.TimeOperation.dayName().
convertStringToDouble()
double wrimsv2.evaluator.Evaluation.convertStringToDouble (String text) static
Definition at line 32 of file Evaluation.java.
Referenced by term_FLOAT().
convertStringToInt()
int wrimsv2.evaluator.Evaluation.convertStringToInt (String text) static
Definition at line 36 of file Evaluation.java.
Referenced by initSumExpression(), and term_INTEGER().
cos()
EvalExpression wrimsv2.evaluator.Evaluation.cos (EvalExpression ee1) static
Definition at line 1548 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
cot()
EvalExpression wrimsv2.evaluator.Evaluation.cot (EvalExpression ee1) static
Definition at line 1568 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
daysIn()
EvalExpression wrimsv2.evaluator.Evaluation.daysIn () static
Definition at line 1708 of file Evaluation.java.
References wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by daysInTimeStep().
daysInTimeStep()
EvalExpression wrimsv2.evaluator.Evaluation.daysInTimeStep () static
Definition at line 1714 of file Evaluation.java.
References daysIn(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), and wrimsv2.components.ControlData.timeStep.
divide()
EvalExpression wrimsv2.evaluator.Evaluation.divide (EvalExpression ee1, EvalExpression ee2) static
Definition at line 329 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), divideOperation(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and wrimsv2.evaluator.EvalExpression.setValue().
divideOperation()
IntDouble wrimsv2.evaluator.Evaluation.divideOperation (IntDouble id1, IntDouble id2) static
Definition at line 353 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by divide().
dvarAliasCycleTimeSeries()
double wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries (String ident, int indexValue, int ci, ParallelVars prvs) static
Definition at line 946 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by pastCycleIndexTimeArray(), and pastCycleTimeArray().
dvarAliasTimeSeries() [1/2]
double wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries (String ident, int indexValue, ParallelVars prvs) static
Definition at line 885 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
dvarAliasTimeSeries() [2/2]
double wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries (String ident, ParallelVars prvs) static
Definition at line 836 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by getTimeSeries().
exceedance()
EvalExpression wrimsv2.evaluator.Evaluation.exceedance (String tsName, EvalExpression exc_ee, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr) static
Definition at line 1624 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSet.getExceedance(), wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.evaluator.TimeOperation.monthValue(), wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.components.ControlData.timeStep.
exceedance_tsi()
EvalExpression wrimsv2.evaluator.Evaluation.exceedance_tsi (String tsName, EvalExpression exc_ee, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr) static
Definition at line 1666 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSet.getExceedance_tsi(), wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.evaluator.TimeOperation.monthValue(), wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.components.ControlData.timeStep.
exp()
EvalExpression wrimsv2.evaluator.Evaluation.exp (EvalExpression ee1) static
Definition at line 1466 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), expOperation(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
expOperation()
IntDouble wrimsv2.evaluator.Evaluation.expOperation (IntDouble id1) static
Definition at line 1473 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by exp().
expressionInput()
IntDouble wrimsv2.evaluator.Evaluation.expressionInput (EvalExpression ee) static
Definition at line 1931 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
getDVAliasInitTimeseries()
boolean wrimsv2.evaluator.Evaluation.getDVAliasInitTimeseries (String ident) static
Definition at line 1002 of file Evaluation.java.
References wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), and wrimsv2.components.ControlData.initHDF5.
Referenced by dvarAliasCycleTimeSeries(), dvarAliasTimeSeries(), dvarAliasTimeSeries(), and pastTSFV().
getSVInitTimeseries()
boolean wrimsv2.evaluator.Evaluation.getSVInitTimeseries (String ident) static
Definition at line 828 of file Evaluation.java.
References wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), and wrimsv2.components.ControlData.initHDF5.
Referenced by svarTimeSeries().
getTimeSeries()
EvalExpression wrimsv2.evaluator.Evaluation.getTimeSeries (String ident, ArrayList< EvalExpression > eeArray, Stack< LoopIndex > sumIndex) static
Definition at line 647 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.copyOf(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, dvarAliasTimeSeries(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.LoopIndex.getIndexStart(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.LoopIndex.getName(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.LoopIndex.getValue(), wrimsv2.components.ControlData.ignoreError, wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.evaluator.EvalExpression.setMultiplier(), and svarTimeSeries().
Referenced by argFunction().
initSumExpression()
void wrimsv2.evaluator.Evaluation.initSumExpression (EvalExpression ee1, EvalExpression ee2, String s, Stack< LoopIndex > sumIndex) static
Definition at line 1831 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), convertStringToInt(), wrimsv2.evaluator.LoopIndex.end, wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.components.ControlData.ignoreError, wrimsv2.components.IntDouble.isInt(), wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.evaluator.LoopIndex.setIndexStart(), wrimsv2.evaluator.LoopIndex.setValue(), wrimsv2.evaluator.LoopIndex.start, and wrimsv2.evaluator.LoopIndex.step.
intFunc()
EvalExpression wrimsv2.evaluator.Evaluation.intFunc (EvalExpression ee1) static
Definition at line 1417 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), intOperation(), and wrimsv2.evaluator.EvalExpression.isNumeric().
intOperation()
IntDouble wrimsv2.evaluator.Evaluation.intOperation (IntDouble id1) static
Definition at line 1424 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by intFunc().
log()
EvalExpression wrimsv2.evaluator.Evaluation.log (EvalExpression ee1) static
Definition at line 1483 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and logOperation().
log10()
EvalExpression wrimsv2.evaluator.Evaluation.log10 (EvalExpression ee1) static
Definition at line 1500 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and log10Operation().
log10Operation()
IntDouble wrimsv2.evaluator.Evaluation.log10Operation (IntDouble id1) static
Definition at line 1507 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by log10().
logOperation()
IntDouble wrimsv2.evaluator.Evaluation.logOperation (IntDouble id1) static
Definition at line 1490 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by log().
max()
EvalExpression wrimsv2.evaluator.Evaluation.max (EvalExpression ee1, EvalExpression ee2) static
Definition at line 1375 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and maxOperation().
maxOperation()
IntDouble wrimsv2.evaluator.Evaluation.maxOperation (IntDouble id1, IntDouble id2) static
Definition at line 1382 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by max().
min()
EvalExpression wrimsv2.evaluator.Evaluation.min (EvalExpression ee1, EvalExpression ee2) static
Definition at line 1396 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and minOperation().
minOperation()
IntDouble wrimsv2.evaluator.Evaluation.minOperation (IntDouble id1, IntDouble id2) static
Definition at line 1403 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by min().
mod()
EvalExpression wrimsv2.evaluator.Evaluation.mod (EvalExpression ee1, EvalExpression ee2) static
Definition at line 367 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), modOperation(), and wrimsv2.evaluator.EvalExpression.setValue().
modOperation()
IntDouble wrimsv2.evaluator.Evaluation.modOperation (IntDouble id1, IntDouble id2) static
Definition at line 379 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by mod().
mult()
EvalExpression wrimsv2.evaluator.Evaluation.mult (EvalExpression ee1, EvalExpression ee2) static
Definition at line 272 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), multiplyOperation(), and wrimsv2.evaluator.EvalExpression.setValue().
multiplyOperation()
IntDouble wrimsv2.evaluator.Evaluation.multiplyOperation (IntDouble id1, IntDouble id2) static
Definition at line 315 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by mult().
noArgFunction()
EvalExpression wrimsv2.evaluator.Evaluation.noArgFunction (String ident) static
Definition at line 479 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.allExternalFunctionMap, and wrimsv2.external.ExternalFunction.execute().
pastCycleIndexNoTimeArray()
IntDouble wrimsv2.evaluator.Evaluation.pastCycleIndexNoTimeArray (String ident, int index) static
Definition at line 1190 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), and wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap().
Referenced by pastCycleIndexTimeArray().
pastCycleIndexTimeArray()
IntDouble wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray (String ident, int pci, EvalExpression ee) static
Definition at line 1272 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, dvarAliasCycleTimeSeries(), wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.components.IntDouble.isInt(), wrimsv2.evaluator.EvalExpression.isNumeric(), and pastCycleIndexNoTimeArray().
pastCycleNoTimeArray()
IntDouble wrimsv2.evaluator.Evaluation.pastCycleNoTimeArray (String ident, String cycle) static
Definition at line 1168 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), and wrimsv2.components.IntDouble.isInt().
Referenced by pastCycleTimeArray().
pastCycleTimeArray()
IntDouble wrimsv2.evaluator.Evaluation.pastCycleTimeArray (String ident, String cycle, EvalExpression ee) static
Definition at line 1209 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currStudyDataSet, dvarAliasCycleTimeSeries(), wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.components.IntDouble.isInt(), wrimsv2.evaluator.EvalExpression.isNumeric(), and pastCycleNoTimeArray().
pastTSFV()
EvalExpression wrimsv2.evaluator.Evaluation.pastTSFV (String ident, EvalExpression ee1, ArrayList< ArrayList< EvalExpression > > eeArray, ParallelVars prvs) static
Definition at line 1065 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.components.IntDouble.isInt(), wrimsv2.evaluator.EvalExpression.isNumeric(), timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
pow()
EvalExpression wrimsv2.evaluator.Evaluation.pow (EvalExpression ee1, EvalExpression ee2) static
Definition at line 1517 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and powOperation().
powOperation()
IntDouble wrimsv2.evaluator.Evaluation.powOperation (IntDouble id1, IntDouble id2) static
Definition at line 1524 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by pow().
range()
boolean wrimsv2.evaluator.Evaluation.range (String m1, String m2) static
Definition at line 113 of file Evaluation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.evaluator.TimeOperation.range().
realFunc()
EvalExpression wrimsv2.evaluator.Evaluation.realFunc (EvalExpression ee1) static
Definition at line 1433 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and realOperation().
realOperation()
IntDouble wrimsv2.evaluator.Evaluation.realOperation (IntDouble id1) static
Definition at line 1440 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by realFunc().
relationStatement()
boolean wrimsv2.evaluator.Evaluation.relationStatement (EvalExpression ee1, EvalExpression ee2, String relation) static
Definition at line 48 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.solver.CbcSolver.cbcSolutionRounding, wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.components.ControlData.relationTolerance, and wrimsv2.components.ControlData.solverName.
relationStatementSeries()
boolean wrimsv2.evaluator.Evaluation.relationStatementSeries (boolean r1, boolean r2, String s) static
Definition at line 117 of file Evaluation.java.
round()
EvalExpression wrimsv2.evaluator.Evaluation.round (EvalExpression ee1) static
Definition at line 397 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), wrimsv2.evaluator.ValueEvaluation.round(), and wrimsv2.evaluator.EvalExpression.setValue().
sin()
EvalExpression wrimsv2.evaluator.Evaluation.sin (EvalExpression ee1) static
Definition at line 1538 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
substract()
EvalExpression wrimsv2.evaluator.Evaluation.substract (EvalExpression ee1, EvalExpression ee2) static
Definition at line 443 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.EvalExpression.setValue(), and substractOperation().
Referenced by constraintStatement().
substractOperation()
IntDouble wrimsv2.evaluator.Evaluation.substractOperation (IntDouble id1, IntDouble id2) static
Definition at line 465 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by substract().
sumExpression()
EvalExpression wrimsv2.evaluator.Evaluation.sumExpression (EvalExpression ee, String expression, Stack< LoopIndex > sumIndex) static
Definition at line 1855 of file Evaluation.java.
References add(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.LoopIndex.end, wrimsv2.components.ControlData.ignoreError, wrimsv2.evaluator.LoopIndex.setIndexStart(), wrimsv2.evaluator.LoopIndex.setValue(), wrimsv2.evaluator.LoopIndex.start, and wrimsv2.evaluator.LoopIndex.step.
sumExpression_IDENT()
void wrimsv2.evaluator.Evaluation.sumExpression_IDENT (String ident, Stack< LoopIndex > sumIndex) static
Definition at line 1825 of file Evaluation.java.
svarTimeSeries()
double wrimsv2.evaluator.Evaluation.svarTimeSeries (String ident, int idValue, ParallelVars prvs) static
Definition at line 766 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.allowSvTsInit, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.fromDssFile, wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getStudyStartIndex(), getSVInitTimeseries(), wrimsv2.evaluator.DataTimeSeries.lookInitDss, wrimsv2.evaluator.DataTimeSeries.svInit, wrimsv2.evaluator.DataTimeSeries.svTS, timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by getTimeSeries(), timeseries(), and timeseries().
tableSQL()
EvalExpression wrimsv2.evaluator.Evaluation.tableSQL (String table, String select, HashMap< String, Number > where, HashMap< String, Number > given, String use) static
Definition at line 1921 of file Evaluation.java.
References wrimsv2.evaluator.TableOperation.findData().
tafcfs()
double wrimsv2.evaluator.Evaluation.tafcfs (String ident, ParallelVars prvs) static
Definition at line 1758 of file Evaluation.java.
References wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.TimeOperation.numberOfDays(), and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), and tafcfs_term().
tafcfs_term()
EvalExpression wrimsv2.evaluator.Evaluation.tafcfs_term (String ident, EvalExpression ee, Stack< LoopIndex > sumIndex) static
Definition at line 1723 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.LoopIndex.getName(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.evaluator.LoopIndex.getValue(), wrimsv2.evaluator.EvalExpression.isNumeric(), and tafcfs().
tan()
EvalExpression wrimsv2.evaluator.Evaluation.tan (EvalExpression ee1) static
Definition at line 1558 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getValue(), and wrimsv2.evaluator.EvalExpression.isNumeric().
term_ARRAY_ITERATOR()
EvalExpression wrimsv2.evaluator.Evaluation.term_ARRAY_ITERATOR (ParallelVars prvs) static
Definition at line 1820 of file Evaluation.java.
References wrimsv2.parallel.ParallelVars.timeArrayIndex.
term_DAY()
EvalExpression wrimsv2.evaluator.Evaluation.term_DAY () static
Definition at line 1798 of file Evaluation.java.
References wrimsv2.components.ControlData.currDay.
term_FLOAT()
EvalExpression wrimsv2.evaluator.Evaluation.term_FLOAT (String floatValue) static
Definition at line 244 of file Evaluation.java.
References convertStringToDouble().
term_IDENT()
EvalExpression wrimsv2.evaluator.Evaluation.term_IDENT (String ident, Stack< LoopIndex > sumIndex) static
Definition at line 137 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.LoopIndex.getIndexStart(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.LoopIndex.getName(), wrimsv2.evaluator.LoopIndex.getValue(), wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.components.IntDouble.isInt(), wrimsv2.components.ControlData.isPostProcessing, wrimsv2.components.ControlData.parameterMap, wrimsv2.evaluator.EvalExpression.setValue(), and wrimsv2.commondata.wresldata.Param.yes.
term_INTEGER()
EvalExpression wrimsv2.evaluator.Evaluation.term_INTEGER (String integer) static
Definition at line 239 of file Evaluation.java.
References convertStringToInt().
term_knownTS()
EvalExpression wrimsv2.evaluator.Evaluation.term_knownTS (IntDouble result) static
Definition at line 133 of file Evaluation.java.
term_MONTH()
EvalExpression wrimsv2.evaluator.Evaluation.term_MONTH () static
Definition at line 1793 of file Evaluation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.evaluator.TimeOperation.waterMonthValue().
term_MONTH_CONST()
EvalExpression wrimsv2.evaluator.Evaluation.term_MONTH_CONST (String month) static
Definition at line 1803 of file Evaluation.java.
References wrimsv2.evaluator.TimeOperation.monthValue(), and wrimsv2.evaluator.TimeOperation.waterMonthValue().
term_PASTMONTH()
EvalExpression wrimsv2.evaluator.Evaluation.term_PASTMONTH (String pastMonth) static
Definition at line 1809 of file Evaluation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.evaluator.TimeOperation.monthValue().
term_SVAR()
EvalExpression wrimsv2.evaluator.Evaluation.term_SVAR (String ident) static
Definition at line 217 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currSvMap, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
term_YEAR()
EvalExpression wrimsv2.evaluator.Evaluation.term_YEAR () static
Definition at line 1788 of file Evaluation.java.
References wrimsv2.evaluator.TimeOperation.waterYearValue().
timeseries() [1/2]
EvalExpression wrimsv2.evaluator.Evaluation.timeseries () static
Definition at line 1052 of file Evaluation.java.
References wrimsv2.components.ControlData.currEvalName, wrimsv2.evaluator.TimeOperation.findTime(), and svarTimeSeries().
Referenced by wrimsv2.parallel.ProcessTimeseries.computeDirectly().
timeseries() [2/2]
double wrimsv2.evaluator.Evaluation.timeseries (String tsName) static
Definition at line 1060 of file Evaluation.java.
References wrimsv2.evaluator.TimeOperation.findTime(), and svarTimeSeries().
timeSeriesIndex() [1/2]
int wrimsv2.evaluator.Evaluation.timeSeriesIndex (DssDataSet dds, ParallelVars prvs) static
Definition at line 1010 of file Evaluation.java.
References wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), and wrimsv2.evaluator.TimeOperation.isMonthlyInterval().
Referenced by dvarAliasCycleTimeSeries(), dvarAliasTimeSeries(), dvarAliasTimeSeries(), pastTSFV(), and svarTimeSeries().
timeSeriesIndex() [2/2]
int wrimsv2.evaluator.Evaluation.timeSeriesIndex (DssDataSetFixLength dds, ParallelVars prvs) static
Definition at line 1031 of file Evaluation.java.
References wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), and wrimsv2.evaluator.TimeOperation.isMonthlyInterval().
trunk_timeArray()
ArrayList< EvalExpression > wrimsv2.evaluator.Evaluation.trunk_timeArray (String ident, IntDouble start, IntDouble end) static
Definition at line 1331 of file Evaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.ValueEvaluation.argFunction(), wrimsv2.components.IntDouble.getData(), wrimsv2.components.IntDouble.isInt(), and wrimsv2.components.IntDouble.setIndex().
unary()
EvalExpression wrimsv2.evaluator.Evaluation.unary (String s, EvalExpression ee) static
Definition at line 249 of file Evaluation.java.
References wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.components.IntDouble.isInt(), and wrimsv2.components.IntDouble.setData().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/Evaluation.java