Wrims-engine: wrimsv2.evaluator.WeightEval Class Reference
wrimsv2.evaluator.WeightEval Class Reference
Static Public Member Functions
static void collectWt (ModelDataSet mds, int ci)
static void collectWtRT (String name, WeightElement wt)
static void collectWtSlackSurplus (ModelDataSet mds, int ci)
static int getTimeArraySize (ValueEvaluatorParser timeArraySizeParser)
static void outputExtreme ()
static void outputWtTable ()
static void outputWtTableAR ()
static void procWt (StudyDataSet sds)
Static Private Attributes
static String farstr = "WeightTableAR.csv"
static String fstr = "WeightTable.csv"
static ArrayList< Integer > maxCa =new ArrayList<Integer>()
static ArrayList< String > maxPa =new ArrayList<String>()
static double maxw =1.0
static ArrayList< String > maxwva =new ArrayList<String>()
static ArrayList< Integer > minCa =new ArrayList<Integer>()
static ArrayList< String > minPa =new ArrayList<String>()
static double minw =1.0
static ArrayList< String > minwva =new ArrayList<String>()
static ArrayList< String > variedwList =new ArrayList<String>()
static ArrayList< String > wList =new ArrayList<String>()
static CopyOnWriteArrayList< String > wListAR =new CopyOnWriteArrayList<String>()
static HashMap< String, LinkedHashMap< Integer, ArrayList< Double > > > wMap = new HashMap<String, LinkedHashMap<Integer, ArrayList<Double>>>()
static ConcurrentHashMap< String, WeightElement > wMapAR =new ConcurrentHashMap<String, WeightElement>()
Detailed Description
Definition at line 28 of file WeightEval.java.
Member Function Documentation
collectWt()
void wrimsv2.evaluator.WeightEval.collectWt (ModelDataSet mds, int ci) static
Definition at line 79 of file WeightEval.java.
References wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.commondata.wresldata.WeightElement.fromWresl, getTimeArraySize(), wrimsv2.commondata.wresldata.WeightElement.line, maxCa, maxPa, maxw, maxwva, minCa, minPa, minw, minwva, wrimsv2.parallel.ParallelVars.timeArrayIndex, wrimsv2.commondata.wresldata.WeightElement.timeArraySizeParser, variedwList, wrimsv2.commondata.wresldata.WeightElement.weightParser, wList, wMap, wrimsv2.commondata.wresldata.ModelDataSet.wtList, and wrimsv2.commondata.wresldata.ModelDataSet.wtMap.
Referenced by procWt().
collectWtRT()
void wrimsv2.evaluator.WeightEval.collectWtRT (String name, WeightElement wt) static
Definition at line 408 of file WeightEval.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.WeightElement.getValue(), wrimsv2.commondata.wresldata.WeightElement.max, wrimsv2.commondata.wresldata.WeightElement.maxTC, wrimsv2.commondata.wresldata.WeightElement.min, wrimsv2.commondata.wresldata.WeightElement.minTC, wListAR, and wMapAR.
Referenced by wrimsv2.parallel.ProcessWeight.computeDirectly(), and wrimsv2.parallel.ProcessWeightSurplusSlack.computeDirectly().
collectWtSlackSurplus()
void wrimsv2.evaluator.WeightEval.collectWtSlackSurplus (ModelDataSet mds, int ci) static
Definition at line 209 of file WeightEval.java.
References wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.commondata.wresldata.WeightElement.fromWresl, getTimeArraySize(), wrimsv2.commondata.wresldata.WeightElement.line, maxCa, maxPa, maxw, maxwva, minCa, minPa, minw, minwva, wrimsv2.parallel.ParallelVars.timeArrayIndex, wrimsv2.commondata.wresldata.WeightElement.timeArraySizeParser, variedwList, wrimsv2.commondata.wresldata.WeightElement.weightParser, wList, wMap, wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusList, and wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusMap.
Referenced by procWt().
getTimeArraySize()
int wrimsv2.evaluator.WeightEval.getTimeArraySize (ValueEvaluatorParser timeArraySizeParser) static
Definition at line 339 of file WeightEval.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by collectWt(), and collectWtSlackSurplus().
outputExtreme()
void wrimsv2.evaluator.WeightEval.outputExtreme () static
Definition at line 388 of file WeightEval.java.
References maxCa, maxPa, maxw, maxwva, minCa, minPa, minw, minwva, and variedwList.
Referenced by procWt().
outputWtTable()
void wrimsv2.evaluator.WeightEval.outputWtTable () static
Definition at line 356 of file WeightEval.java.
References fstr, wrimsv2.components.FilePaths.mainDirectory, wList, and wMap.
Referenced by procWt().
outputWtTableAR()
void wrimsv2.evaluator.WeightEval.outputWtTableAR () static
Definition at line 438 of file WeightEval.java.
References farstr, wrimsv2.ilp.ILP.getIlpDir(), wrimsv2.commondata.wresldata.WeightElement.max, wrimsv2.commondata.wresldata.WeightElement.maxTC, wrimsv2.commondata.wresldata.WeightElement.min, wrimsv2.commondata.wresldata.WeightElement.minTC, wListAR, and wMapAR.
Referenced by wrimsv2.components.ControllerBatch.runModel(), and wrimsv2.components.ControllerDebug.runModelSolvers().
procWt()
void wrimsv2.evaluator.WeightEval.procWt (StudyDataSet sds) static
Definition at line 47 of file WeightEval.java.
References collectWt(), collectWtSlackSurplus(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), outputExtreme(), outputWtTable(), wrimsv2.commondata.wresldata.ModelDataSet.resetSlackSurplusWeight(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.compileStudy().
Member Data Documentation
farstr
String wrimsv2.evaluator.WeightEval.farstr = "WeightTableAR.csv" static private
Definition at line 38 of file WeightEval.java.
Referenced by outputWtTableAR().
fstr
String wrimsv2.evaluator.WeightEval.fstr = "WeightTable.csv" static private
Definition at line 37 of file WeightEval.java.
Referenced by outputWtTable().
maxCa
ArrayList<Integer> wrimsv2.evaluator.WeightEval.maxCa =new ArrayList<Integer>() static private
Definition at line 36 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
maxPa
ArrayList<String> wrimsv2.evaluator.WeightEval.maxPa =new ArrayList<String>() static private
Definition at line 34 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
maxw
double wrimsv2.evaluator.WeightEval.maxw =1.0 static private
Definition at line 30 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
maxwva
ArrayList<String> wrimsv2.evaluator.WeightEval.maxwva =new ArrayList<String>() static private
Definition at line 32 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
minCa
ArrayList<Integer> wrimsv2.evaluator.WeightEval.minCa =new ArrayList<Integer>() static private
Definition at line 35 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
minPa
ArrayList<String> wrimsv2.evaluator.WeightEval.minPa =new ArrayList<String>() static private
Definition at line 33 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
minw
double wrimsv2.evaluator.WeightEval.minw =1.0 static private
Definition at line 29 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
minwva
ArrayList<String> wrimsv2.evaluator.WeightEval.minwva =new ArrayList<String>() static private
Definition at line 31 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
variedwList
ArrayList<String> wrimsv2.evaluator.WeightEval.variedwList =new ArrayList<String>() static private
Definition at line 42 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputExtreme().
wList
ArrayList<String> wrimsv2.evaluator.WeightEval.wList =new ArrayList<String>() static private
Definition at line 40 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputWtTable().
wListAR
CopyOnWriteArrayList<String> wrimsv2.evaluator.WeightEval.wListAR =new CopyOnWriteArrayList<String>() static private
Definition at line 44 of file WeightEval.java.
Referenced by collectWtRT(), and outputWtTableAR().
wMap
HashMap<String, LinkedHashMap<Integer, ArrayList<Double> > > wrimsv2.evaluator.WeightEval.wMap = new HashMap<String, LinkedHashMap<Integer, ArrayList<Double>>>() static private
Definition at line 41 of file WeightEval.java.
Referenced by collectWt(), collectWtSlackSurplus(), and outputWtTable().
wMapAR
ConcurrentHashMap<String, WeightElement> wrimsv2.evaluator.WeightEval.wMapAR =new ConcurrentHashMap<String, WeightElement>() static private
Definition at line 45 of file WeightEval.java.
Referenced by collectWtRT(), and outputWtTableAR().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/WeightEval.java