Wrims-engine: wrimsv2.hdf5.HDF5Reader Class Reference
wrimsv2.hdf5.HDF5Reader Class Reference
Static Public Member Functions
static void assignTimeseries ()
static void closeFileAndGroup (int flag)
static boolean getDVAliasInitTimeseries (String name)
static boolean getSVInitTimeseries (String name)
static boolean getSVTimeseries (String name, String timeStep)
static int openFileAndGroup (int flag)
static void readDailyTimestepData (int flag)
static void readDailyTimestepList (int flag)
static void readInitialData ()
static void readLookupTable (int flag)
static void readMonthlyTimestepData (int flag)
static void readMonthlyTimestepList (int flag)
static void readTimeseries ()
static void readTimestepData (int flag)
static void readTimestepList (int flag)
Static Private Attributes
static String gDaily ="Daily"
static String gData ="Data"
static String gInfo ="Info"
static String gIOData ="IO Data"
static String gMonthly ="Monthly"
static double[][] initDailyData =new double[0][0]
static String[] initDailyListKind = new String[0]
static String[] initDailyListName = new String[0]
static Date initDailyStartDate =new Date(21,9,1,24,0)
static int initFid =-1
static int initGidDaily =-1
static int initGidData =-1
static int initGidInfo =-1
static int initGidIOData =-1
static int initGidMonthly =-1
static int initGidPartA =-1
static int initGidPartF =-1
static String[] initLookupKind =new String[0]
static String[] initLookupName =new String[0]
static String[] initLookupTimestep =new String[0]
static String[] initLookupUnit =new String[0]
static double[][] initMonthlyData =new double[0][0]
static String[] initMonthlyListKind = new String[0]
static String[] initMonthlyListName = new String[0]
static Date initMonthlyStartDate =new Date(21,9,31,24,0)
static double[][] svDailyData =new double[0][0]
static String[] svDailyListKind = new String[0]
static String[] svDailyListName = new String[0]
static Date svDailyStartDate =new Date(21,9,1,24,0)
static int svFid =-1
static int svGidDaily =-1
static int svGidData =-1
static int svGidInfo =-1
static int svGidIOData =-1
static int svGidMonthly =-1
static int svGidPartA =-1
static int svGidPartF =-1
static String[] svLookupKind =new String[0]
static String[] svLookupName =new String[0]
static String[] svLookupTimestep =new String[0]
static String[] svLookupUnit =new String[0]
static double[][] svMonthlyData =new double[0][0]
static String[] svMonthlyListKind = new String[0]
static String[] svMonthlyListName = new String[0]
static Date svMonthlyStartDate =new Date(21,9,31,24,0)
Detailed Description
Definition at line 24 of file HDF5Reader.java.
Member Function Documentation
assignTimeseries()
void wrimsv2.hdf5.HDF5Reader.assignTimeseries () static
Definition at line 658 of file HDF5Reader.java.
References wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.evaluator.DssOperation.entryNameTS(), getSVTimeseries(), wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesMap(), wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesTimeStepMap(), wrimsv2.evaluator.DataTimeSeries.lookSvDss, svDailyData, svDailyListKind, svDailyListName, svLookupKind, svLookupName, svLookupTimestep, svLookupUnit, svMonthlyData, svMonthlyListKind, and svMonthlyListName.
Referenced by readTimeseries().
closeFileAndGroup()
void wrimsv2.hdf5.HDF5Reader.closeFileAndGroup (int flag) static
Definition at line 229 of file HDF5Reader.java.
References initFid, initGidDaily, initGidData, initGidInfo, initGidIOData, initGidMonthly, initGidPartA, initGidPartF, svFid, svGidDaily, svGidData, svGidInfo, svGidIOData, svGidMonthly, svGidPartA, and svGidPartF.
Referenced by readInitialData(), and readTimeseries().
getDVAliasInitTimeseries()
boolean wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries (String name) static
Definition at line 781 of file HDF5Reader.java.
References wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.generateStudyStartIndex(), initDailyData, initDailyListKind, initDailyListName, initDailyStartDate, initLookupKind, initLookupName, initLookupTimestep, initLookupUnit, initMonthlyData, initMonthlyListKind, initMonthlyListName, initMonthlyStartDate, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setFromDssFile(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), wrimsv2.evaluator.DssDataSet.setUnits(), wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.Alias.units, and wrimsv2.commondata.wresldata.Dvar.units.
Referenced by wrimsv2.evaluator.Evaluation.getDVAliasInitTimeseries(), and wrimsv2.evaluator.ValueEvaluation.getDVAliasInitTimeseries().
getSVInitTimeseries()
boolean wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries (String name) static
Definition at line 855 of file HDF5Reader.java.
References wrimsv2.commondata.wresldata.Timeseries.convertToUnits, wrimsv2.components.ControlData.currTsMap, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.generateStudyStartIndex(), initDailyData, initDailyListKind, initDailyListName, initDailyStartDate, initLookupKind, initLookupName, initLookupTimestep, initLookupUnit, initMonthlyData, initMonthlyListKind, initMonthlyListName, initMonthlyStartDate, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setFromDssFile(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), wrimsv2.evaluator.DssDataSet.setUnits(), wrimsv2.evaluator.DataTimeSeries.svInit, wrimsv2.evaluator.Evaluation.tafcfs(), wrimsv2.components.ControlData.timeStep, and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by wrimsv2.evaluator.Evaluation.getSVInitTimeseries(), and wrimsv2.evaluator.ValueEvaluation.getSVInitTimeseries().
getSVTimeseries()
boolean wrimsv2.hdf5.HDF5Reader.getSVTimeseries (String name, String timeStep) static
Definition at line 688 of file HDF5Reader.java.
References wrimsv2.components.ControlData.allTsMap, wrimsv2.commondata.wresldata.Timeseries.convertToUnits, wrimsv2.commondata.wresldata.Timeseries.dssBPart, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.generateStudyStartIndex(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.components.ControlData.partE, wrimsv2.evaluator.DssDataSet.setData(), wrimsv2.evaluator.DssDataSet.setFromDssFile(), wrimsv2.evaluator.DssDataSet.setKind(), wrimsv2.evaluator.DssDataSet.setStartTime(), wrimsv2.evaluator.DssDataSet.setTimeStep(), wrimsv2.evaluator.DssDataSet.setUnits(), svDailyData, svDailyListKind, svDailyListName, svDailyStartDate, svLookupKind, svLookupName, svLookupTimestep, svLookupUnit, svMonthlyData, svMonthlyListKind, svMonthlyListName, svMonthlyStartDate, wrimsv2.evaluator.DataTimeSeries.svTS, wrimsv2.evaluator.Evaluation.tafcfs(), wrimsv2.components.ControlData.timeStep, and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by assignTimeseries().
openFileAndGroup()
int wrimsv2.hdf5.HDF5Reader.openFileAndGroup (int flag) static
Definition at line 92 of file HDF5Reader.java.
References wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullSvarFilePath, gDaily, gData, gInfo, gIOData, gMonthly, initDailyStartDate, initFid, initGidDaily, initGidData, initGidInfo, initGidIOData, initGidMonthly, initGidPartA, initGidPartF, initMonthlyStartDate, wrimsv2.components.ControlData.initPartF, wrimsv2.hdf5.HDF5Util.locateGroup(), wrimsv2.evaluator.TimeOperation.monthValue(), wrimsv2.components.ControlData.partA, wrimsv2.hdf5.HDF5Util.readStringAttr(), svDailyStartDate, wrimsv2.components.ControlData.svDvPartF, svFid, svGidDaily, svGidData, svGidInfo, svGidIOData, svGidMonthly, svGidPartA, svGidPartF, and svMonthlyStartDate.
Referenced by readInitialData(), and readTimeseries().
readDailyTimestepData()
void wrimsv2.hdf5.HDF5Reader.readDailyTimestepData (int flag) static
Definition at line 606 of file HDF5Reader.java.
References initDailyData, initGidDaily, svDailyData, and svGidDaily.
Referenced by readTimestepData().
readDailyTimestepList()
void wrimsv2.hdf5.HDF5Reader.readDailyTimestepList (int flag) static
Definition at line 471 of file HDF5Reader.java.
References initDailyListKind, initDailyListName, initGidDaily, wrimsv2.hdf5.HDF5Util.readStringData(), svDailyListKind, svDailyListName, and svGidDaily.
Referenced by readTimestepList().
readInitialData()
void wrimsv2.hdf5.HDF5Reader.readInitialData () static
Definition at line 83 of file HDF5Reader.java.
References closeFileAndGroup(), openFileAndGroup(), readLookupTable(), readTimestepData(), and readTimestepList().
Referenced by wrimsv2.components.PreRunModel.PreRunModel().
readLookupTable()
void wrimsv2.hdf5.HDF5Reader.readLookupTable (int flag) static
Definition at line 271 of file HDF5Reader.java.
References initGidInfo, initLookupKind, initLookupName, initLookupTimestep, initLookupUnit, wrimsv2.hdf5.HDF5Util.readStringData(), svGidInfo, svLookupKind, svLookupName, svLookupTimestep, and svLookupUnit.
Referenced by readInitialData(), and readTimeseries().
readMonthlyTimestepData()
void wrimsv2.hdf5.HDF5Reader.readMonthlyTimestepData (int flag) static
Definition at line 553 of file HDF5Reader.java.
References initGidMonthly, initMonthlyData, svGidMonthly, and svMonthlyData.
Referenced by readTimestepData().
readMonthlyTimestepList()
void wrimsv2.hdf5.HDF5Reader.readMonthlyTimestepList (int flag) static
Definition at line 394 of file HDF5Reader.java.
References initGidMonthly, initMonthlyListKind, initMonthlyListName, wrimsv2.hdf5.HDF5Util.readStringData(), svGidMonthly, svMonthlyListKind, and svMonthlyListName.
Referenced by readTimestepList().
readTimeseries()
void wrimsv2.hdf5.HDF5Reader.readTimeseries () static
Definition at line 72 of file HDF5Reader.java.
References assignTimeseries(), closeFileAndGroup(), openFileAndGroup(), readLookupTable(), readTimestepData(), and readTimestepList().
Referenced by wrimsv2.components.PreRunModel.PreRunModel().
readTimestepData()
void wrimsv2.hdf5.HDF5Reader.readTimestepData (int flag) static
Definition at line 548 of file HDF5Reader.java.
References readDailyTimestepData(), and readMonthlyTimestepData().
Referenced by readInitialData(), and readTimeseries().
readTimestepList()
void wrimsv2.hdf5.HDF5Reader.readTimestepList (int flag) static
Definition at line 389 of file HDF5Reader.java.
References readDailyTimestepList(), and readMonthlyTimestepList().
Referenced by readInitialData(), and readTimeseries().
Member Data Documentation
gDaily
String wrimsv2.hdf5.HDF5Reader.gDaily ="Daily" static private
Definition at line 44 of file HDF5Reader.java.
Referenced by openFileAndGroup().
gData
String wrimsv2.hdf5.HDF5Reader.gData ="Data" static private
Definition at line 38 of file HDF5Reader.java.
Referenced by openFileAndGroup().
gInfo
String wrimsv2.hdf5.HDF5Reader.gInfo ="Info" static private
Definition at line 35 of file HDF5Reader.java.
Referenced by openFileAndGroup().
gIOData
String wrimsv2.hdf5.HDF5Reader.gIOData ="IO Data" static private
Definition at line 34 of file HDF5Reader.java.
Referenced by openFileAndGroup().
gMonthly
String wrimsv2.hdf5.HDF5Reader.gMonthly ="Monthly" static private
Definition at line 41 of file HDF5Reader.java.
Referenced by openFileAndGroup().
initDailyData
double [][] wrimsv2.hdf5.HDF5Reader.initDailyData =new double[0][0] static private
Definition at line 54 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readDailyTimestepData().
initDailyListKind
String [] wrimsv2.hdf5.HDF5Reader.initDailyListKind = new String[0] static private
Definition at line 62 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readDailyTimestepList().
initDailyListName
String [] wrimsv2.hdf5.HDF5Reader.initDailyListName = new String[0] static private
Definition at line 61 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readDailyTimestepList().
initDailyStartDate
Date wrimsv2.hdf5.HDF5Reader.initDailyStartDate =new Date(21,9,1,24,0) static private
Definition at line 50 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and openFileAndGroup().
initFid
int wrimsv2.hdf5.HDF5Reader.initFid =-1 static private
Definition at line 27 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
initGidDaily
int wrimsv2.hdf5.HDF5Reader.initGidDaily =-1 static private
Definition at line 46 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), openFileAndGroup(), readDailyTimestepData(), and readDailyTimestepList().
initGidData
int wrimsv2.hdf5.HDF5Reader.initGidData =-1 static private
Definition at line 40 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
initGidInfo
int wrimsv2.hdf5.HDF5Reader.initGidInfo =-1 static private
Definition at line 37 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), openFileAndGroup(), and readLookupTable().
initGidIOData
int wrimsv2.hdf5.HDF5Reader.initGidIOData =-1 static private
Definition at line 33 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
initGidMonthly
int wrimsv2.hdf5.HDF5Reader.initGidMonthly =-1 static private
Definition at line 43 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), openFileAndGroup(), readMonthlyTimestepData(), and readMonthlyTimestepList().
initGidPartA
int wrimsv2.hdf5.HDF5Reader.initGidPartA =-1 static private
Definition at line 29 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
initGidPartF
int wrimsv2.hdf5.HDF5Reader.initGidPartF =-1 static private
Definition at line 31 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
initLookupKind
String [] wrimsv2.hdf5.HDF5Reader.initLookupKind =new String[0] static private
Definition at line 68 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readLookupTable().
initLookupName
String [] wrimsv2.hdf5.HDF5Reader.initLookupName =new String[0] static private
Definition at line 67 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readLookupTable().
initLookupTimestep
String [] wrimsv2.hdf5.HDF5Reader.initLookupTimestep =new String[0] static private
Definition at line 70 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readLookupTable().
initLookupUnit
String [] wrimsv2.hdf5.HDF5Reader.initLookupUnit =new String[0] static private
Definition at line 69 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readLookupTable().
initMonthlyData
double [][] wrimsv2.hdf5.HDF5Reader.initMonthlyData =new double[0][0] static private
Definition at line 53 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readMonthlyTimestepData().
initMonthlyListKind
String [] wrimsv2.hdf5.HDF5Reader.initMonthlyListKind = new String[0] static private
Definition at line 60 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readMonthlyTimestepList().
initMonthlyListName
String [] wrimsv2.hdf5.HDF5Reader.initMonthlyListName = new String[0] static private
Definition at line 59 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and readMonthlyTimestepList().
initMonthlyStartDate
Date wrimsv2.hdf5.HDF5Reader.initMonthlyStartDate =new Date(21,9,31,24,0) static private
Definition at line 49 of file HDF5Reader.java.
Referenced by getDVAliasInitTimeseries(), getSVInitTimeseries(), and openFileAndGroup().
svDailyData
double [][] wrimsv2.hdf5.HDF5Reader.svDailyData =new double[0][0] static private
Definition at line 52 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readDailyTimestepData().
svDailyListKind
String [] wrimsv2.hdf5.HDF5Reader.svDailyListKind = new String[0] static private
Definition at line 58 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readDailyTimestepList().
svDailyListName
String [] wrimsv2.hdf5.HDF5Reader.svDailyListName = new String[0] static private
Definition at line 57 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readDailyTimestepList().
svDailyStartDate
Date wrimsv2.hdf5.HDF5Reader.svDailyStartDate =new Date(21,9,1,24,0) static private
Definition at line 48 of file HDF5Reader.java.
Referenced by getSVTimeseries(), and openFileAndGroup().
svFid
int wrimsv2.hdf5.HDF5Reader.svFid =-1 static private
Definition at line 26 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
svGidDaily
int wrimsv2.hdf5.HDF5Reader.svGidDaily =-1 static private
Definition at line 45 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), openFileAndGroup(), readDailyTimestepData(), and readDailyTimestepList().
svGidData
int wrimsv2.hdf5.HDF5Reader.svGidData =-1 static private
Definition at line 39 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
svGidInfo
int wrimsv2.hdf5.HDF5Reader.svGidInfo =-1 static private
Definition at line 36 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), openFileAndGroup(), and readLookupTable().
svGidIOData
int wrimsv2.hdf5.HDF5Reader.svGidIOData =-1 static private
Definition at line 32 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
svGidMonthly
int wrimsv2.hdf5.HDF5Reader.svGidMonthly =-1 static private
Definition at line 42 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), openFileAndGroup(), readMonthlyTimestepData(), and readMonthlyTimestepList().
svGidPartA
int wrimsv2.hdf5.HDF5Reader.svGidPartA =-1 static private
Definition at line 28 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
svGidPartF
int wrimsv2.hdf5.HDF5Reader.svGidPartF =-1 static private
Definition at line 30 of file HDF5Reader.java.
Referenced by closeFileAndGroup(), and openFileAndGroup().
svLookupKind
String [] wrimsv2.hdf5.HDF5Reader.svLookupKind =new String[0] static private
Definition at line 64 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readLookupTable().
svLookupName
String [] wrimsv2.hdf5.HDF5Reader.svLookupName =new String[0] static private
Definition at line 63 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readLookupTable().
svLookupTimestep
String [] wrimsv2.hdf5.HDF5Reader.svLookupTimestep =new String[0] static private
Definition at line 66 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readLookupTable().
svLookupUnit
String [] wrimsv2.hdf5.HDF5Reader.svLookupUnit =new String[0] static private
Definition at line 65 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readLookupTable().
svMonthlyData
double [][] wrimsv2.hdf5.HDF5Reader.svMonthlyData =new double[0][0] static private
Definition at line 51 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readMonthlyTimestepData().
svMonthlyListKind
String [] wrimsv2.hdf5.HDF5Reader.svMonthlyListKind = new String[0] static private
Definition at line 56 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readMonthlyTimestepList().
svMonthlyListName
String [] wrimsv2.hdf5.HDF5Reader.svMonthlyListName = new String[0] static private
Definition at line 55 of file HDF5Reader.java.
Referenced by assignTimeseries(), getSVTimeseries(), and readMonthlyTimestepList().
svMonthlyStartDate
Date wrimsv2.hdf5.HDF5Reader.svMonthlyStartDate =new Date(21,9,31,24,0) static private
Definition at line 47 of file HDF5Reader.java.
Referenced by getSVTimeseries(), and openFileAndGroup().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/hdf5/HDF5Reader.java