Wrims-engine: wrimsv2.components.PreRunModel Class Reference
wrimsv2.components.PreRunModel Class Reference
Public Member Functions
PreRunModel (StudyDataSet sds)
void initialDvarAliasTS ()
void processExternal ()
void procOVFile ()
void readTimeseries ()
void setGenTableDir ()
void setGroundwaterInitFile ()
void setGroundwaterInitFilePath (File backup, File input)
void setSelectedOutputCycles ()
Detailed Description
Definition at line 43 of file PreRunModel.java.
Constructor & Destructor Documentation
PreRunModel()
wrimsv2.components.PreRunModel.PreRunModel (StudyDataSet sds)
Definition at line 44 of file PreRunModel.java.
References wrimsv2.components.Error.addEngineError(), wrimsv2.components.ControlData.allDll, wrimsv2.components.ControlData.allTsMap, wrimsv2.components.ControlData.cacheInit, wrimsv2.components.ControlData.cacheSvar, wrimsv2.components.ControlData.cacheSvar2, wrimsv2.evaluator.CondensedReferenceCacheAndRead.createCondensedCache(), wrimsv2.hdf5.HDF5Writer.createDataStructure(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.dailyStartTime, wrimsv2.components.ControlData.dvDss, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullSvarFile2Path, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesMap(), wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.components.FilePaths.initFile, wrimsv2.components.ControlData.initHDF5, initialDvarAliasTS(), wrimsv2.hdf5.HDF5Writer.listCycleStaticSv(), wrimsv2.components.ControlData.monthlyStartTime, wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.ovOption, wrimsv2.components.VariableTimeStep.procCycleTimeStep(), processExternal(), procOVFile(), wrimsv2.hdf5.HDF5Reader.readInitialData(), readTimeseries(), wrimsv2.hdf5.HDF5Reader.readTimeseries(), setGenTableDir(), setGroundwaterInitFile(), setSelectedOutputCycles(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.FilePaths.svarFile, wrimsv2.components.ControlData.t_readTs, wrimsv2.components.ControlData.totalTimeStep, wrimsv2.components.ControlData.unchangeGWRestart, and wrimsv2.components.ControlData.vHecLib.
Member Function Documentation
initialDvarAliasTS()
void wrimsv2.components.PreRunModel.initialDvarAliasTS ()
Definition at line 159 of file PreRunModel.java.
References wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.cycleDataStartDay, wrimsv2.components.ControlData.cycleDataStartMonth, wrimsv2.components.ControlData.cycleDataStartYear, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by PreRunModel().
processExternal()
void wrimsv2.components.PreRunModel.processExternal ()
Definition at line 174 of file PreRunModel.java.
References wrimsv2.components.ControlData.allDll, wrimsv2.components.ControlData.allExternalFunction, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currExMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.ModelDataSet.exList, and wrimsv2.commondata.wresldata.ModelDataSet.exMap.
Referenced by PreRunModel().
procOVFile()
void wrimsv2.components.PreRunModel.procOVFile ()
Definition at line 265 of file PreRunModel.java.
References wrimsv2.components.ControlData.ovFile, wrimsv2.components.ControlData.ovOption, and wrimsv2.components.ControlData.ovPartBC.
Referenced by PreRunModel().
readTimeseries()
void wrimsv2.components.PreRunModel.readTimeseries ()
Definition at line 134 of file PreRunModel.java.
References wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.FilePaths.fullSvarFile2Path, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesMap(), wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesTimeStepMap(), and wrimsv2.evaluator.DataTimeSeries.lookSvDss.
Referenced by PreRunModel().
setGenTableDir()
void wrimsv2.components.PreRunModel.setGenTableDir ()
Definition at line 246 of file PreRunModel.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.components.FilePaths.genTableDir, and wrimsv2.components.FilePaths.mainDirectory.
Referenced by PreRunModel().
setGroundwaterInitFile()
void wrimsv2.components.PreRunModel.setGroundwaterInitFile ()
Definition at line 198 of file PreRunModel.java.
References wrimsv2.components.FilePaths.groundwaterDir, and setGroundwaterInitFilePath().
Referenced by PreRunModel().
setGroundwaterInitFilePath()
void wrimsv2.components.PreRunModel.setGroundwaterInitFilePath (File backup, File input)
Definition at line 213 of file PreRunModel.java.
References wrimsv2.evaluator.TimeOperation.monthName(), wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by setGroundwaterInitFile().
setSelectedOutputCycles()
void wrimsv2.components.PreRunModel.setSelectedOutputCycles ()
Definition at line 193 of file PreRunModel.java.
References wrimsv2.components.ControlData.selectedCycleOutput, and wrimsv2.components.ControlData.selectedCycles.
Referenced by PreRunModel().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/PreRunModel.java