Wrims-engine: wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache Class Reference
wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache Class Reference
Public Member Functions
Set< String > getAllPaths ()
CondensedReference getCondensedReference (String pathname)
DSSPathname getNominalPathname (String pathname)
TimeSeriesContainer readFullRecord (String pathname)
Private Member Functions
CondensedReferenceCache (String fileName, SortedMap< String, CondensedReference > condensedReferences)
Private Attributes
final SortedMap< String, CondensedReference > condensedReferences
final String fileName
Detailed Description
Definition at line 41 of file CondensedReferenceCacheAndRead.java.
Constructor & Destructor Documentation
CondensedReferenceCache()
wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.CondensedReferenceCache (String fileName, SortedMap< String, CondensedReference > condensedReferences) private
Definition at line 45 of file CondensedReferenceCacheAndRead.java.
References condensedReferences, and fileName.
Member Function Documentation
getAllPaths()
Set< String > wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getAllPaths ()
Definition at line 50 of file CondensedReferenceCacheAndRead.java.
Referenced by wrimsv2.hdf5.DSSHDF5Converter.readDailyInitDssFile(), wrimsv2.hdf5.DSSHDF5Converter.readDailySVDssFile(), wrimsv2.sql.DssToSQLDatabase.readDssData(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), wrimsv2.hdf5.DSSHDF5Converter.readMonthlyInitDssFile(), and wrimsv2.hdf5.DSSHDF5Converter.readMonthlySVDssFile().
getCondensedReference()
CondensedReference wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getCondensedReference (String pathname)
Definition at line 64 of file CondensedReferenceCacheAndRead.java.
References condensedReferences.
Referenced by readFullRecord().
getNominalPathname()
DSSPathname wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.getNominalPathname (String pathname)
Definition at line 54 of file CondensedReferenceCacheAndRead.java.
References condensedReferences.
Referenced by wrimsv2.evaluator.DssOperation.getDataForInitial(), and wrimsv2.evaluator.DssOperation.getDataForSvar().
readFullRecord()
TimeSeriesContainer wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.readFullRecord (String pathname)
Definition at line 73 of file CondensedReferenceCacheAndRead.java.
References getCondensedReference().
Referenced by wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.DSSHDF5Converter.readDailyInitDssFile(), wrimsv2.hdf5.DSSHDF5Converter.readDailySVDssFile(), wrimsv2.sql.DssToSQLDatabase.readDssData(), wrimsv2.sql.DssToSQLDatabase.readDssDataFixLength(), wrimsv2.hdf5.DSSHDF5Converter.readMonthlyInitDssFile(), and wrimsv2.hdf5.DSSHDF5Converter.readMonthlySVDssFile().
Member Data Documentation
condensedReferences
final SortedMap<String, CondensedReference> wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.condensedReferences private
Definition at line 42 of file CondensedReferenceCacheAndRead.java.
Referenced by CondensedReferenceCache(), getCondensedReference(), and getNominalPathname().
fileName
final String wrimsv2.evaluator.CondensedReferenceCacheAndRead.CondensedReferenceCache.fileName private
Definition at line 43 of file CondensedReferenceCacheAndRead.java.
Referenced by CondensedReferenceCache().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/CondensedReferenceCacheAndRead.java