Wrims-engine: wrimsv2.sql.MySQLCWriter Class Reference
wrimsv2.sql.MySQLCWriter Class Reference
Public Member Functions
MySQLCWriter ()
Date addOneDay (Date date)
Date addOneMonth (Date date)
void close ()
void connectToDataBase ()
void createTables ()
void deleteTablesByNames (String tableName)
void deleteTablesIfExist ()
String formDateData (Date date)
String formPathName (DssDataSetFixLength ts, String name, String timestep)
String formUnitsName (DssDataSetFixLength ts)
void process ()
void writeDailyData ()
void writeData ()
void writeMonthlyData ()
Private Attributes
int col_limit =750
Connection conn = null
ArrayList< ArrayList< String > > dailyEntriesArr
String dailyTableName =FilePaths.sqlScenarioName+"_"+ControlData.partA+"_"+ControlData.svDvPartF+"_D"
String database
String JDBC_DRIVER = "com.mysql.jdbc.Driver"
ArrayList< ArrayList< String > > monthlyEntriesArr
String monthlyTableName =FilePaths.sqlScenarioName+"_"+ControlData.partA+"_"+ControlData.svDvPartF+"_M"
String slackPrefix ="slack__"
Statement stmt = null
String surplusPrefix ="surplus__"
String URL
Detailed Description
Definition at line 23 of file MySQLCWriter.java.
Constructor & Destructor Documentation
MySQLCWriter()
wrimsv2.sql.MySQLCWriter.MySQLCWriter ()
Definition at line 44 of file MySQLCWriter.java.
References connectToDataBase().
Member Function Documentation
addOneDay()
Date wrimsv2.sql.MySQLCWriter.addOneDay (Date date)
Definition at line 307 of file MySQLCWriter.java.
Referenced by writeDailyData().
addOneMonth()
Date wrimsv2.sql.MySQLCWriter.addOneMonth (Date date)
Definition at line 295 of file MySQLCWriter.java.
References wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by writeMonthlyData().
close()
void wrimsv2.sql.MySQLCWriter.close ()
Definition at line 315 of file MySQLCWriter.java.
References conn, and stmt.
Referenced by process().
connectToDataBase()
void wrimsv2.sql.MySQLCWriter.connectToDataBase ()
Definition at line 55 of file MySQLCWriter.java.
References conn, database, wrimsv2.components.ControlData.databaseURL, JDBC_DRIVER, wrimsv2.components.ControlData.PASS, stmt, URL, and wrimsv2.components.ControlData.USER.
Referenced by MySQLCWriter().
createTables()
void wrimsv2.sql.MySQLCWriter.createTables ()
Definition at line 117 of file MySQLCWriter.java.
References col_limit, conn, dailyEntriesArr, dailyTableName, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, formPathName(), formUnitsName(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), monthlyEntriesArr, monthlyTableName, slackPrefix, stmt, and surplusPrefix.
Referenced by process().
deleteTablesByNames()
void wrimsv2.sql.MySQLCWriter.deleteTablesByNames (String tableName)
Definition at line 95 of file MySQLCWriter.java.
References conn, database, and stmt.
Referenced by deleteTablesIfExist().
deleteTablesIfExist()
void wrimsv2.sql.MySQLCWriter.deleteTablesIfExist ()
Definition at line 87 of file MySQLCWriter.java.
References dailyTableName, deleteTablesByNames(), and monthlyTableName.
Referenced by process().
formDateData()
String wrimsv2.sql.MySQLCWriter.formDateData (Date date)
Definition at line 288 of file MySQLCWriter.java.
References wrimsv2.evaluator.TimeOperation.dayName(), and wrimsv2.evaluator.TimeOperation.monthNameNumeric().
Referenced by writeDailyData(), and writeMonthlyData().
formPathName()
String wrimsv2.sql.MySQLCWriter.formPathName (DssDataSetFixLength ts, String name, String timestep)
Definition at line 282 of file MySQLCWriter.java.
References wrimsv2.evaluator.DssDataSetFixLength.getKind(), and wrimsv2.evaluator.DssOperation.getTSName().
Referenced by createTables().
formUnitsName()
String wrimsv2.sql.MySQLCWriter.formUnitsName (DssDataSetFixLength ts)
Definition at line 277 of file MySQLCWriter.java.
References wrimsv2.evaluator.DssDataSetFixLength.getUnits().
Referenced by createTables().
process()
void wrimsv2.sql.MySQLCWriter.process ()
Definition at line 48 of file MySQLCWriter.java.
References close(), createTables(), deleteTablesIfExist(), and writeData().
writeDailyData()
void wrimsv2.sql.MySQLCWriter.writeDailyData ()
Definition at line 245 of file MySQLCWriter.java.
References addOneDay(), conn, dailyEntriesArr, dailyTableName, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, formDateData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), and wrimsv2.evaluator.DssDataSetFixLength.getStartTime().
Referenced by writeData().
writeData()
void wrimsv2.sql.MySQLCWriter.writeData ()
Definition at line 206 of file MySQLCWriter.java.
References writeDailyData(), and writeMonthlyData().
Referenced by process().
writeMonthlyData()
void wrimsv2.sql.MySQLCWriter.writeMonthlyData ()
Definition at line 213 of file MySQLCWriter.java.
References addOneMonth(), conn, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, formDateData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), monthlyEntriesArr, and monthlyTableName.
Referenced by writeData().
Member Data Documentation
col_limit
int wrimsv2.sql.MySQLCWriter.col_limit =750 private
Definition at line 39 of file MySQLCWriter.java.
Referenced by createTables().
conn
Connection wrimsv2.sql.MySQLCWriter.conn = null private
Definition at line 30 of file MySQLCWriter.java.
Referenced by close(), connectToDataBase(), createTables(), deleteTablesByNames(), writeDailyData(), and writeMonthlyData().
dailyEntriesArr
ArrayList<ArrayList<String> > wrimsv2.sql.MySQLCWriter.dailyEntriesArr private
Definition at line 34 of file MySQLCWriter.java.
Referenced by createTables(), and writeDailyData().
dailyTableName
String wrimsv2.sql.MySQLCWriter.dailyTableName =FilePaths.sqlScenarioName+"_"+ControlData.partA+"_"+ControlData.svDvPartF+"_D" private
Definition at line 37 of file MySQLCWriter.java.
Referenced by createTables(), deleteTablesIfExist(), and writeDailyData().
database
String wrimsv2.sql.MySQLCWriter.database private
Definition at line 28 of file MySQLCWriter.java.
Referenced by connectToDataBase(), and deleteTablesByNames().
JDBC_DRIVER
String wrimsv2.sql.MySQLCWriter.JDBC_DRIVER = "com.mysql.jdbc.Driver" private
Definition at line 25 of file MySQLCWriter.java.
Referenced by connectToDataBase().
monthlyEntriesArr
ArrayList<ArrayList<String> > wrimsv2.sql.MySQLCWriter.monthlyEntriesArr private
Definition at line 33 of file MySQLCWriter.java.
Referenced by createTables(), and writeMonthlyData().
monthlyTableName
String wrimsv2.sql.MySQLCWriter.monthlyTableName =FilePaths.sqlScenarioName+"_"+ControlData.partA+"_"+ControlData.svDvPartF+"_M" private
Definition at line 36 of file MySQLCWriter.java.
Referenced by createTables(), deleteTablesIfExist(), and writeMonthlyData().
slackPrefix
String wrimsv2.sql.MySQLCWriter.slackPrefix ="slack__" private
Definition at line 41 of file MySQLCWriter.java.
Referenced by createTables().
stmt
Statement wrimsv2.sql.MySQLCWriter.stmt = null private
Definition at line 31 of file MySQLCWriter.java.
Referenced by close(), connectToDataBase(), createTables(), and deleteTablesByNames().
surplusPrefix
String wrimsv2.sql.MySQLCWriter.surplusPrefix ="surplus__" private
Definition at line 42 of file MySQLCWriter.java.
Referenced by createTables().
URL
String wrimsv2.sql.MySQLCWriter.URL private
Definition at line 27 of file MySQLCWriter.java.
Referenced by connectToDataBase().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/sql/MySQLCWriter.java