Wrims-engine: main.WreslCheckGUI.InputFilePanel Class Reference
main.WreslCheckGUI.InputFilePanel Class Reference
Public Member Functions
InputFilePanel (String label)
String getMainFilePath ()
Private Attributes
JButton browseButton
JTextField textfield
Detailed Description
Creates a panel consisting of label, a textfield populated by a browse (file browser) button.
Definition at line 127 of file WreslCheckGUI.java.
Constructor & Destructor Documentation
InputFilePanel()
main.WreslCheckGUI.InputFilePanel.InputFilePanel (String label)
Definition at line 131 of file WreslCheckGUI.java.
References InputFilePanel(), browseButton, and textfield.
Referenced by InputFilePanel().
Member Function Documentation
getMainFilePath()
String main.WreslCheckGUI.InputFilePanel.getMainFilePath ()
Definition at line 151 of file WreslCheckGUI.java.
References textfield.
Referenced by main.WreslCheckGUI.main().
Member Data Documentation
browseButton
JButton main.WreslCheckGUI.InputFilePanel.browseButton private
Definition at line 129 of file WreslCheckGUI.java.
Referenced by InputFilePanel().
textfield
JTextField main.WreslCheckGUI.InputFilePanel.textfield private
Definition at line 128 of file WreslCheckGUI.java.
Referenced by InputFilePanel(), and getMainFilePath().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/main/WreslCheckGUI.java