Wrims-engine: wrimsv2.tools.Warmstart Class Reference
wrimsv2.tools.Warmstart Class Reference
Static Public Member Functions
static void collectIntegerDV_1 (StudyTemp st)
static void collectIntegerDV_2 (StudyDataSet sd)
static void collectIntegerDV_3 (StudyDataSet sd)
Detailed Description
Definition at line 18 of file Warmstart.java.
Member Function Documentation
collectIntegerDV_1()
void wrimsv2.tools.Warmstart.collectIntegerDV_1 (StudyTemp st) static
Definition at line 20 of file Warmstart.java.
References wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, wrimsv2.commondata.wresldata.Param.cbcMinIntNumber, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.components.ControlData.cycWarmStart, wrimsv2.components.ControlData.cycWarmStop, wrimsv2.components.ControlData.cycWarmUse, wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslplus.elements.SequenceTemp.dvMap, wrimsv2.wreslplus.elements.Procedures.findWarmStart(), wrimsv2.wreslplus.elements.Procedures.findWarmStop(), wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.Tools.quickLog(), wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, and wrimsv2.components.ControlData.useCbcWarmStart.
collectIntegerDV_2()
void wrimsv2.tools.Warmstart.collectIntegerDV_2 (StudyDataSet sd) static
Definition at line 149 of file Warmstart.java.
References wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, wrimsv2.commondata.wresldata.Param.cbcMinIntNumber, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.components.ControlData.cycWarmStart, wrimsv2.components.ControlData.cycWarmStop, wrimsv2.components.ControlData.cycWarmUse, wrimsv2.wreslplus.elements.Procedures.findWarmStart(), wrimsv2.wreslplus.elements.Procedures.findWarmStop(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.ControlData.useCbcWarmStart, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), and wrimsv2.components.DebugInterface.setSolverOptions().
collectIntegerDV_3()
void wrimsv2.tools.Warmstart.collectIntegerDV_3 (StudyDataSet sd) static
Definition at line 254 of file Warmstart.java.
References wrimsv2.commondata.wresldata.Param.cbcMinIntNumber, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.components.ControlData.cycWarmStart, wrimsv2.components.ControlData.cycWarmStop, wrimsv2.components.ControlData.cycWarmUse, wrimsv2.wreslplus.elements.Procedures.findWarmStart(), wrimsv2.wreslplus.elements.Procedures.findWarmStop(), and wrimsv2.components.ControlData.useCbcWarmStart.
Referenced by wrimsv2.components.ControllerBatch.parse().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/Warmstart.java