Wrims-engine: wrimsv2.wreslplus.elements.CompileLog Class Reference
wrimsv2.wreslplus.elements.CompileLog Class Reference
Static Public Member Functions
static String createMainWreslLog (StudyTemp st, LinkedHashMap< String, Integer > fileMap_reverse)
static String createWreslFileLog (ModelTemp mt, Set< String > deps)
static String writeLog (String r, String canonicalFilePath)
Private Member Functions
CompileLog ()
Static Private Member Functions
static String doAlias (ModelTemp mt, Set< String > deps)
static String doDv (ModelTemp mt)
static String doGoal (ModelTemp mt, Set< String > deps)
static String doIncModel (StudyTemp st)
static String doModel (ModelTemp mt, Set< String > deps)
static String doModels (StudyTemp st, LinkedHashMap< String, Integer > fileMap_reverse)
static String doSequence (StudyTemp st)
static String doSv (SvarTemp svT)
static String doSvIncFileModel (ModelTemp mt)
static String doSvIncFileModel (ModelTemp mt, LinkedHashMap< String, Integer > fileMap_reverse)
static String doTimeseries (ModelTemp mt)
Detailed Description
Definition at line 16 of file CompileLog.java.
Constructor & Destructor Documentation
CompileLog()
wrimsv2.wreslplus.elements.CompileLog.CompileLog () private
Definition at line 18 of file CompileLog.java.
Member Function Documentation
createMainWreslLog()
String wrimsv2.wreslplus.elements.CompileLog.createMainWreslLog (StudyTemp st, LinkedHashMap< String, Integer > fileMap_reverse) static
Definition at line 20 of file CompileLog.java.
References doIncModel(), doModels(), and doSequence().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog().
createWreslFileLog()
String wrimsv2.wreslplus.elements.CompileLog.createWreslFileLog (ModelTemp mt, Set< String > deps) static
Definition at line 48 of file CompileLog.java.
References doModel().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog().
doAlias()
String wrimsv2.wreslplus.elements.CompileLog.doAlias (ModelTemp mt, Set< String > deps) static private
Definition at line 184 of file CompileLog.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.ModelTemp.asList, wrimsv2.wreslplus.elements.ModelTemp.asMap, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.AliasTemp.expression, wrimsv2.wreslplus.elements.AliasTemp.kind, wrimsv2.commondata.wresldata.Param.reservedSet, wrimsv2.commondata.wresldata.Param.undefined, and wrimsv2.wreslplus.elements.AliasTemp.units.
Referenced by doModel(), and doModels().
doDv()
String wrimsv2.wreslplus.elements.CompileLog.doDv (ModelTemp mt) static private
Definition at line 266 of file CompileLog.java.
References wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.wreslplus.elements.ModelTemp.dvMap, wrimsv2.wreslplus.elements.DvarTemp.lowerBound, and wrimsv2.wreslplus.elements.DvarTemp.upperBound.
Referenced by doModel(), and doModels().
doGoal()
String wrimsv2.wreslplus.elements.CompileLog.doGoal (ModelTemp mt, Set< String > deps) static private
Definition at line 204 of file CompileLog.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslplus.elements.GoalTemp.caseExpression, wrimsv2.wreslplus.elements.GoalTemp.caseMap, wrimsv2.wreslplus.elements.GoalTemp.caseName, wrimsv2.wreslplus.elements.GoalCase.condition, wrimsv2.commondata.wresldata.Param.constrain, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.wreslplus.elements.GoalTemp.hasCase, wrimsv2.wreslplus.elements.GoalTemp.hasLhs, wrimsv2.wreslplus.elements.GoalTemp.lhs, wrimsv2.wreslplus.elements.GoalCase.lhs_gt_rhs, wrimsv2.wreslplus.elements.GoalCase.lhs_lt_rhs, wrimsv2.commondata.wresldata.Param.reservedSet, and wrimsv2.wreslplus.elements.GoalCase.rhs.
Referenced by doModel(), and doModels().
doIncModel()
String wrimsv2.wreslplus.elements.CompileLog.doIncModel (StudyTemp st) static private
Definition at line 281 of file CompileLog.java.
References wrimsv2.wreslplus.elements.StudyTemp.modelList, and wrimsv2.wreslplus.elements.StudyTemp.modelMap.
Referenced by createMainWreslLog().
doModel()
String wrimsv2.wreslplus.elements.CompileLog.doModel (ModelTemp mt, Set< String > deps) static private
Definition at line 57 of file CompileLog.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslplus.elements.ModelTemp.asList, doAlias(), doDv(), doGoal(), doSvIncFileModel(), doTimeseries(), wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.wreslplus.elements.ModelTemp.svList, and wrimsv2.wreslplus.elements.ModelTemp.tsList.
Referenced by createWreslFileLog().
doModels()
String wrimsv2.wreslplus.elements.CompileLog.doModels (StudyTemp st, LinkedHashMap< String, Integer > fileMap_reverse) static private
Definition at line 88 of file CompileLog.java.
References doAlias(), doDv(), doGoal(), doSvIncFileModel(), doTimeseries(), wrimsv2.wreslplus.elements.StudyTemp.modelList, and wrimsv2.wreslplus.elements.StudyTemp.modelMap.
Referenced by createMainWreslLog().
doSequence()
String wrimsv2.wreslplus.elements.CompileLog.doSequence (StudyTemp st) static private
Definition at line 303 of file CompileLog.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, and wrimsv2.commondata.wresldata.Param.undefined.
Referenced by createMainWreslLog().
doSv()
String wrimsv2.wreslplus.elements.CompileLog.doSv (SvarTemp svT) static private
Definition at line 251 of file CompileLog.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslplus.elements.SvarTemp.caseCondition, wrimsv2.wreslplus.elements.SvarTemp.caseExpression, and wrimsv2.wreslplus.elements.SvarTemp.caseName.
Referenced by doSvIncFileModel().
doSvIncFileModel() [1/2]
String wrimsv2.wreslplus.elements.CompileLog.doSvIncFileModel (ModelTemp mt) static private
Definition at line 120 of file CompileLog.java.
References doSv(), wrimsv2.wreslplus.elements.ModelTemp.incFileMap, wrimsv2.commondata.wresldata.Param.incFileType, wrimsv2.wreslplus.elements.ModelTemp.itemList, wrimsv2.wreslplus.elements.ModelTemp.itemTypeList, wrimsv2.wreslplus.elements.ModelTemp.svMap, and wrimsv2.commondata.wresldata.Param.svType.
Referenced by doModel(), and doModels().
doSvIncFileModel() [2/2]
String wrimsv2.wreslplus.elements.CompileLog.doSvIncFileModel (ModelTemp mt, LinkedHashMap< String, Integer > fileMap_reverse) static private
Definition at line 143 of file CompileLog.java.
References wrimsv2.wreslplus.elements.ModelTemp.incFileMap, wrimsv2.commondata.wresldata.Param.incFileType, wrimsv2.commondata.wresldata.Param.incModelType, wrimsv2.wreslplus.elements.ModelTemp.itemList, wrimsv2.wreslplus.elements.ModelTemp.itemTypeList, and wrimsv2.commondata.wresldata.Param.svType.
doTimeseries()
String wrimsv2.wreslplus.elements.CompileLog.doTimeseries (ModelTemp mt) static private
Definition at line 171 of file CompileLog.java.
References wrimsv2.wreslplus.elements.TimeseriesTemp.dssBPart, wrimsv2.wreslplus.elements.TimeseriesTemp.kind, wrimsv2.wreslplus.elements.ModelTemp.tsList, wrimsv2.wreslplus.elements.ModelTemp.tsMap, wrimsv2.commondata.wresldata.Param.undefined, and wrimsv2.wreslplus.elements.TimeseriesTemp.units.
Referenced by doModel(), and doModels().
writeLog()
String wrimsv2.wreslplus.elements.CompileLog.writeLog (String r, String canonicalFilePath) static
Definition at line 30 of file CompileLog.java.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/CompileLog.java