Wrims-engine: wrimsv2.components.Error Class Reference
wrimsv2.components.Error Class Reference
Static Public Member Functions
static void addConfigError (String error)
static void addDeviationError (String error)
static void addEngineError (String error)
static void addEvaluationError (String error)
static void addInfeasibleHint (String goalName, String moreMsg)
static void addInitialError (String error)
static void addSolvingError (String error)
static void clear ()
static String getCurrentDateCycleModel ()
static int getTotalError ()
static void writeConfigErrorFile (String fileName)
static void writeDeviationErrorFile (String fileName)
static void writeErrorLog ()
static void writeEvaluationErrorFile (String fileName)
static void writeGrammerErrorFile (String fileName)
static void writeSolvingErrorFile (String fileName)
Static Public Attributes
static ArrayList< String > error_config =new ArrayList<String>()
static ArrayList< String > error_deviation =new ArrayList<String>()
static ArrayList< String > error_engine =new ArrayList<String>()
static ArrayList< String > error_evaluation = new ArrayList<String> ()
static ArrayList< String > error_grammer = new ArrayList<String> ()
static ArrayList< String > error_initial =new ArrayList<String>()
static ArrayList< String > error_solving =new ArrayList<String>()
Detailed Description
Definition at line 21 of file Error.java.
Member Function Documentation
addConfigError()
void wrimsv2.components.Error.addConfigError (String error) static
Definition at line 235 of file Error.java.
References error_config.
Referenced by wrimsv2.config.ConfigUtils.checkConfigFile(), wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.debug.ChangeSolver.loadLPSolveConfigFile(), wrimsv2.config.ConfigUtils.readParameter(), wrimsv2.components.Controller.runModel(), wrimsv2.components.ControllerBatch.runModel(), wrimsv2.components.ControllerDebug.runModel(), wrimsv2.components.Controller.runModelILP(), and wrimsv2.components.ControllerBatch.runModelILP().
addDeviationError()
void wrimsv2.components.Error.addDeviationError (String error) static
Definition at line 243 of file Error.java.
References error_deviation, and getCurrentDateCycleModel().
Referenced by wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus().
addEngineError()
void wrimsv2.components.Error.addEngineError (String error) static
Definition at line 230 of file Error.java.
References error_engine.
Referenced by wrimsv2.solver.InitialXASolver.InitialXASolver(), and wrimsv2.components.PreRunModel.PreRunModel().
addEvaluationError()
void wrimsv2.components.Error.addEvaluationError (String error) static
Definition at line 149 of file Error.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currEvalName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, error_evaluation, wrimsv2.commondata.wresldata.ModelDataSet.exMap, wrimsv2.commondata.wresldata.Alias.fromWresl, wrimsv2.commondata.wresldata.Dvar.fromWresl, wrimsv2.commondata.wresldata.External.fromWresl, wrimsv2.commondata.wresldata.Goal.fromWresl, wrimsv2.commondata.wresldata.Svar.fromWresl, wrimsv2.commondata.wresldata.Timeseries.fromWresl, wrimsv2.commondata.wresldata.WeightElement.fromWresl, getCurrentDateCycleModel(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.commondata.wresldata.Alias.line, wrimsv2.commondata.wresldata.Dvar.line, wrimsv2.commondata.wresldata.External.line, wrimsv2.commondata.wresldata.Goal.line, wrimsv2.commondata.wresldata.Svar.line, wrimsv2.commondata.wresldata.Timeseries.line, wrimsv2.commondata.wresldata.WeightElement.line, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, and wrimsv2.commondata.wresldata.ModelDataSet.wtMap.
Referenced by wrimsv2.evaluator.Evaluation.abs(), wrimsv2.evaluator.Evaluation.acos(), wrimsv2.evaluator.Evaluation.acot(), wrimsv2.evaluator.Evaluation.argFunction(), wrimsv2.evaluator.ValueEvaluation.argFunction(), wrimsv2.evaluator.Evaluation.asin(), wrimsv2.evaluator.Evaluation.atan(), wrimsv2.evaluator.TableOperation.calculateValue(), wrimsv2.parallel.ProcessConstraint.computeDirectly(), wrimsv2.parallel.ProcessDvar.computeDirectly(), wrimsv2.parallel.ProcessWeight.computeDirectly(), wrimsv2.parallel.ProcessWeightSurplusSlack.computeDirectly(), wrimsv2.evaluator.Evaluation.cos(), wrimsv2.evaluator.Evaluation.cot(), wrimsv2.evaluator.Evaluation.divide(), wrimsv2.evaluator.ValueEvaluation.divide(), wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.evaluator.Evaluation.exp(), wrimsv2.evaluator.Evaluation.expressionInput(), wrimsv2.evaluator.TableOperation.findData(), wrimsv2.evaluator.TableOperation.findData(), wrimsv2.evaluator.DssDataSet.getExceedance(), wrimsv2.evaluator.DssDataSet.getExceedance_tsi(), wrimsv2.commondata.wresldata.TimeArray.getTimeArraySize(), wrimsv2.evaluator.WeightEval.getTimeArraySize(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.ValueEvaluation.getTimeSeries(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.intFunc(), wrimsv2.evaluator.Evaluation.log(), wrimsv2.evaluator.Evaluation.log10(), wrimsv2.evaluator.Evaluation.max(), wrimsv2.evaluator.Evaluation.min(), wrimsv2.evaluator.Evaluation.mod(), wrimsv2.evaluator.ValueEvaluation.mod(), wrimsv2.evaluator.Evaluation.modOperation(), wrimsv2.evaluator.Evaluation.mult(), wrimsv2.evaluator.Evaluation.noArgFunction(), wrimsv2.evaluator.ValueEvaluation.noArgFunction(), wrimsv2.evaluator.Evaluation.pastCycleIndexNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexNoTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleNoTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.evaluator.Evaluation.pow(), wrimsv2.evaluator.PreEvaluatorTree.preEvaluateSvar(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processSvar(), wrimsv2.evaluator.Evaluation.realFunc(), wrimsv2.evaluator.Evaluation.relationStatement(), wrimsv2.evaluator.TableOperation.retrieveLookUpData(), wrimsv2.evaluator.Evaluation.round(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.external.Functionsuitablehabitat.setPythonEnv(), wrimsv2.evaluator.Evaluation.sin(), wrimsv2.evaluator.TableOperation.sortNumberArray(), wrimsv2.external.Functionsuitablehabitat.SuitableHabitat(), wrimsv2.evaluator.Evaluation.sumExpression(), wrimsv2.evaluator.ValueEvaluation.sumExpression(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), wrimsv2.evaluator.ValueEvaluation.svarTimeSeries(), wrimsv2.evaluator.Evaluation.tafcfs_term(), wrimsv2.evaluator.ValueEvaluation.tafcfs_term(), wrimsv2.evaluator.Evaluation.tan(), wrimsv2.evaluator.Evaluation.term_IDENT(), wrimsv2.evaluator.ValueEvaluation.term_IDENT(), wrimsv2.evaluator.Evaluation.term_SVAR(), wrimsv2.evaluator.ValueEvaluation.term_SVAR(), wrimsv2.evaluator.Evaluation.trunk_timeArray(), and wrimsv2.evaluator.ValueEvaluation.trunk_timeArray().
addInfeasibleHint()
void wrimsv2.components.Error.addInfeasibleHint (String goalName, String moreMsg) static
Definition at line 219 of file Error.java.
References wrimsv2.components.ControlData.currModelDataSet, error_solving, wrimsv2.commondata.wresldata.Goal.fromWresl, wrimsv2.commondata.wresldata.ModelDataSet.gMap, and wrimsv2.commondata.wresldata.Goal.line.
addInitialError()
void wrimsv2.components.Error.addInitialError (String error) static
Definition at line 239 of file Error.java.
References error_initial.
Referenced by wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIfStatementHasUnknownDependants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialConst(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialVarInConfigNotDeclaredInWresl(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkParameterHasUnknownDepedants(), and wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSeqConditionHasUnknownDepedants().
addSolvingError()
void wrimsv2.components.Error.addSolvingError (String error) static
Definition at line 214 of file Error.java.
References error_solving, and getCurrentDateCycleModel().
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.CbcSolver.getSolverInformation(), wrimsv2.solver.ClpSolver.getSolverInformation(), wrimsv2.solver.LPSolveSolver.getSolverInformation(), wrimsv2.solver.ortools.Misc.getSolverInformation(), wrimsv2.solver.XASolver.getSolverInformation(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.LPSolveSolver.setLP(), wrimsv2.solver.Gurobi.GurobiSolver.setLp(), wrimsv2.solver.Clp0Solver.solve(), wrimsv2.solver.Gurobi.GurobiSolver.solve(), wrimsv2.solver.LPSolveSolver.solve(), and wrimsv2.solver.Cbc0Solver.solve_command().
clear()
void wrimsv2.components.Error.clear () static
Definition at line 258 of file Error.java.
References error_config, error_deviation, error_engine, error_evaluation, error_grammer, error_initial, and error_solving.
Referenced by wrimsv2.components.DebugInterface.handleRequest().
getCurrentDateCycleModel()
String wrimsv2.components.Error.getCurrentDateCycleModel () static
Definition at line 268 of file Error.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, and wrimsv2.commondata.wresldata.StudyDataSet.getModelList().
Referenced by addDeviationError(), addEvaluationError(), and addSolvingError().
getTotalError()
int wrimsv2.components.Error.getTotalError () static
Definition at line 248 of file Error.java.
References error_config, error_deviation, error_engine, error_evaluation, error_grammer, error_initial, and error_solving.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.components.LoadParameter.callBooleanEvaluator(), wrimsv2.wreslplus.elements.procedures.ProcParameter.callBooleanEvaluator(), wrimsv2.components.LoadParameter.callNumberEvaluator(), wrimsv2.wreslplus.elements.procedures.ProcParameter.callNumberEvaluator(), wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.evaluateConditions(), wrimsv2.config.ConfigUtils.loadArgs(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.components.ControllerBatch.parse(), wrimsv2.components.ControllerDebug.pauseForDebug(), wrimsv2.components.Controller.runModel(), wrimsv2.components.ControllerBatch.runModel(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.ilp.ILP.writeObjValue(), and wrimsv2.ilp.ILP.writeObjValueLog().
writeConfigErrorFile()
void wrimsv2.components.Error.writeConfigErrorFile (String fileName) static
Definition at line 78 of file Error.java.
References error_config, and wrimsv2.components.FilePaths.mainDirectory.
writeDeviationErrorFile()
void wrimsv2.components.Error.writeDeviationErrorFile (String fileName) static
Definition at line 94 of file Error.java.
References error_deviation, and wrimsv2.components.FilePaths.mainDirectory.
Referenced by wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus().
writeErrorLog()
void wrimsv2.components.Error.writeErrorLog () static
Definition at line 110 of file Error.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.dateTimeAppend, error_config, error_deviation, error_evaluation, error_initial, error_solving, wrimsv2.ilp.ILP.getYearMonthCycle(), wrimsv2.components.FilePaths.mainDirectory, and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.components.LoadParameter.callBooleanEvaluator(), wrimsv2.wreslplus.elements.procedures.ProcParameter.callBooleanEvaluator(), wrimsv2.components.LoadParameter.callNumberEvaluator(), wrimsv2.wreslplus.elements.procedures.ProcParameter.callNumberEvaluator(), wrimsv2.config.ConfigUtils.checkConfigFile(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIfStatementHasUnknownDependants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialConst(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialVarInConfigNotDeclaredInWresl(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkParameterHasUnknownDepedants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSeqConditionHasUnknownDepedants(), wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.evaluateConditions(), wrimsv2.config.ConfigUtils.loadArgs(), wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.debug.ChangeSolver.loadLPSolveConfigFile(), wrimsv2.components.Controller.runModel(), wrimsv2.components.ControllerBatch.runModel(), wrimsv2.components.ControllerDebug.runModel(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
writeEvaluationErrorFile()
void wrimsv2.components.Error.writeEvaluationErrorFile (String fileName) static
Definition at line 46 of file Error.java.
References error_evaluation, and wrimsv2.components.FilePaths.mainDirectory.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
writeGrammerErrorFile()
void wrimsv2.components.Error.writeGrammerErrorFile (String fileName) static
Definition at line 30 of file Error.java.
References error_grammer, and wrimsv2.components.FilePaths.mainDirectory.
writeSolvingErrorFile()
void wrimsv2.components.Error.writeSolvingErrorFile (String fileName) static
Definition at line 62 of file Error.java.
References error_solving, and wrimsv2.components.FilePaths.mainDirectory.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
Member Data Documentation
error_config
ArrayList<String> wrimsv2.components.Error.error_config =new ArrayList<String>() static
Definition at line 26 of file Error.java.
Referenced by addConfigError(), clear(), getTotalError(), writeConfigErrorFile(), and writeErrorLog().
error_deviation
ArrayList<String> wrimsv2.components.Error.error_deviation =new ArrayList<String>() static
Definition at line 28 of file Error.java.
Referenced by addDeviationError(), clear(), getTotalError(), writeDeviationErrorFile(), and writeErrorLog().
error_engine
ArrayList<String> wrimsv2.components.Error.error_engine =new ArrayList<String>() static
Definition at line 25 of file Error.java.
Referenced by addEngineError(), clear(), and getTotalError().
error_evaluation
ArrayList<String> wrimsv2.components.Error.error_evaluation = new ArrayList<String> () static
Definition at line 23 of file Error.java.
Referenced by addEvaluationError(), wrimsv2.components.ControllerDebug.checkConditionalBreakpoint(), clear(), getTotalError(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), writeErrorLog(), and writeEvaluationErrorFile().
error_grammer
ArrayList<String> wrimsv2.components.Error.error_grammer = new ArrayList<String> () static
Definition at line 22 of file Error.java.
Referenced by clear(), getTotalError(), and writeGrammerErrorFile().
error_initial
ArrayList<String> wrimsv2.components.Error.error_initial =new ArrayList<String>() static
Definition at line 27 of file Error.java.
Referenced by addInitialError(), clear(), getTotalError(), and writeErrorLog().
error_solving
ArrayList<String> wrimsv2.components.Error.error_solving =new ArrayList<String>() static
Definition at line 24 of file Error.java.
Referenced by wrimsv2.solver.XASolver.XASolver(), addInfeasibleHint(), addSolvingError(), clear(), getTotalError(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.solver.ClpSolver.newProblem(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.solver.Clp0Solver.solve(), wrimsv2.solver.LPSolveSolver.solve(), wrimsv2.solver.Cbc0Solver.solve_command(), writeErrorLog(), and writeSolvingErrorFile().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/Error.java