Wrims-engine: wrimsv2.parallel.ProcessConstraint Class Reference
wrimsv2.parallel.ProcessConstraint Class Reference
Public Member Functions
ProcessConstraint (ArrayList< String > gList, Map< String, Goal > gMap, ConcurrentHashMap< String, EvalConstraint > solverGMap, ArrayList< String > gTimeArrayList, CopyOnWriteArrayList< String > usedWtSlackSurplusList, CopyOnWriteArrayList< String > usedWtSlackSurplusDvList, int start, int end)
Protected Member Functions
Integer compute ()
int computeDirectly ()
Private Attributes
int end
ArrayList< String > gList
Map< String, Goal > gMap
ArrayList< String > gTimeArrayList
ConcurrentHashMap< String, EvalConstraint > solverGMap
int start
int threshold
ArrayList< String > timeArrayDvList
CopyOnWriteArrayList< String > usedWtSlackSurplusDvList = new CopyOnWriteArrayList<String>()
CopyOnWriteArrayList< String > usedWtSlackSurplusList = new CopyOnWriteArrayList<String>()
Detailed Description
Definition at line 30 of file ProcessConstraint.java.
Constructor & Destructor Documentation
ProcessConstraint()
wrimsv2.parallel.ProcessConstraint.ProcessConstraint (ArrayList< String > gList, Map< String, Goal > gMap, ConcurrentHashMap< String, EvalConstraint > solverGMap, ArrayList< String > gTimeArrayList, CopyOnWriteArrayList< String > usedWtSlackSurplusList, CopyOnWriteArrayList< String > usedWtSlackSurplusDvList, int start, int end)
Definition at line 43 of file ProcessConstraint.java.
References end, gList, gMap, gTimeArrayList, wrimsv2.components.ControlData.nThreads, solverGMap, start, threshold, usedWtSlackSurplusDvList, and usedWtSlackSurplusList.
Referenced by compute().
Member Function Documentation
compute()
Integer wrimsv2.parallel.ProcessConstraint.compute () protected
Definition at line 56 of file ProcessConstraint.java.
References ProcessConstraint(), computeDirectly(), end, gList, gMap, gTimeArrayList, wrimsv2.components.ControlData.nThreads, solverGMap, start, threshold, usedWtSlackSurplusDvList, and usedWtSlackSurplusList.
computeDirectly()
int wrimsv2.parallel.ProcessConstraint.computeDirectly () protected
Definition at line 88 of file ProcessConstraint.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.Goal.caseConditionParsers, wrimsv2.commondata.wresldata.Goal.caseExpressionParsers, wrimsv2.components.ControlData.currEvalName, wrimsv2.commondata.wresldata.Goal.dvarSlackSurplusList, wrimsv2.commondata.wresldata.Goal.dvarWeightMapList, end, wrimsv2.commondata.wresldata.TimeArray.getTimeArraySize(), gList, gMap, gTimeArrayList, wrimsv2.components.ControlData.showRunTimeMessage, solverGMap, start, wrimsv2.parallel.ParallelVars.timeArrayIndex, wrimsv2.commondata.wresldata.Goal.timeArraySizeParser, usedWtSlackSurplusDvList, and usedWtSlackSurplusList.
Referenced by compute().
Member Data Documentation
end
int wrimsv2.parallel.ProcessConstraint.end private
Definition at line 34 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
gList
ArrayList<String> wrimsv2.parallel.ProcessConstraint.gList private
Definition at line 35 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
gMap
Map<String, Goal> wrimsv2.parallel.ProcessConstraint.gMap private
Definition at line 36 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
gTimeArrayList
ArrayList<String> wrimsv2.parallel.ProcessConstraint.gTimeArrayList private
Definition at line 39 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
solverGMap
ConcurrentHashMap<String, EvalConstraint> wrimsv2.parallel.ProcessConstraint.solverGMap private
Definition at line 37 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
start
int wrimsv2.parallel.ProcessConstraint.start private
Definition at line 33 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
threshold
int wrimsv2.parallel.ProcessConstraint.threshold private
Definition at line 32 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), and compute().
timeArrayDvList
ArrayList<String> wrimsv2.parallel.ProcessConstraint.timeArrayDvList private
Definition at line 38 of file ProcessConstraint.java.
usedWtSlackSurplusDvList
CopyOnWriteArrayList<String> wrimsv2.parallel.ProcessConstraint.usedWtSlackSurplusDvList = new CopyOnWriteArrayList<String>() private
Definition at line 41 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
usedWtSlackSurplusList
CopyOnWriteArrayList<String> wrimsv2.parallel.ProcessConstraint.usedWtSlackSurplusList = new CopyOnWriteArrayList<String>() private
Definition at line 40 of file ProcessConstraint.java.
Referenced by ProcessConstraint(), compute(), and computeDirectly().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/parallel/ProcessConstraint.java