Wrims-engine: wrimsv2.solver.Clp0Solver Class Reference
wrimsv2.solver.Clp0Solver Class Reference
Static Public Member Functions
static void getSolverInformation (int modelStatus)
static void init ()
static void setDefaultOption ()
static void setLP (String filePath)
static void solve ()
Static Public Attributes
static int errorCode
static Map< String, Double > varDoubleMap
Static Private Member Functions
static void assignDvar ()
static String callClp (String arg_lpPath, String arg_soluDir, String arg_soluName, String tolerance) throws IOException, InterruptedException
static void collectDvar ()
Static Private Attributes
static String clpPath
static String lpFilePath
static String soluPath
static String tolerance1 = "-primalT 1e-008"
static String tolerance2 = "-primalT 1e-007"
Detailed Description
Definition at line 30 of file Clp0Solver.java.
Member Function Documentation
assignDvar()
void wrimsv2.solver.Clp0Solver.assignDvar () static private
Definition at line 152 of file Clp0Solver.java.
References wrimsv2.components.Error.addSolvingError(), wrimsv2.components.ControlData.clp_cbc_objective, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), errorCode, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and varDoubleMap.
Referenced by solve().
callClp()
String wrimsv2.solver.Clp0Solver.callClp (String arg_lpPath, String arg_soluDir, String arg_soluName, String tolerance) throws IOException, InterruptedException static private
Definition at line 113 of file Clp0Solver.java.
References clpPath.
Referenced by solve().
collectDvar()
void wrimsv2.solver.Clp0Solver.collectDvar () static private
Definition at line 135 of file Clp0Solver.java.
References wrimsv2.solver.cbc.FilePassingUtils.varDoubleMap, and varDoubleMap.
Referenced by solve().
getSolverInformation()
void wrimsv2.solver.Clp0Solver.getSolverInformation (int modelStatus) static
Definition at line 145 of file Clp0Solver.java.
init()
void wrimsv2.solver.Clp0Solver.init () static
Definition at line 40 of file Clp0Solver.java.
References clpPath.
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
setDefaultOption()
void wrimsv2.solver.Clp0Solver.setDefaultOption () static
Definition at line 141 of file Clp0Solver.java.
setLP()
void wrimsv2.solver.Clp0Solver.setLP (String filePath) static
Definition at line 47 of file Clp0Solver.java.
References lpFilePath, and soluPath.
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
solve()
void wrimsv2.solver.Clp0Solver.solve () static
Definition at line 59 of file Clp0Solver.java.
References wrimsv2.components.Error.addSolvingError(), assignDvar(), callClp(), wrimsv2.components.ControlData.clp_cbc_note, wrimsv2.components.ControlData.clp_cbc_objective, collectDvar(), wrimsv2.components.Error.error_solving, errorCode, wrimsv2.ilp.ILP.getYearMonthCycle(), lpFilePath, wrimsv2.solver.cbc.FilePassingUtils.objective_value, wrimsv2.solver.cbc.FilePassingUtils.parseReturnFile(), soluPath, wrimsv2.solver.cbc.FilePassingUtils.solverMessage, tolerance1, and tolerance2.
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
Member Data Documentation
clpPath
String wrimsv2.solver.Clp0Solver.clpPath static private
Definition at line 36 of file Clp0Solver.java.
Referenced by callClp(), and init().
errorCode
int wrimsv2.solver.Clp0Solver.errorCode static
Definition at line 32 of file Clp0Solver.java.
Referenced by assignDvar(), and solve().
lpFilePath
String wrimsv2.solver.Clp0Solver.lpFilePath static private
Definition at line 34 of file Clp0Solver.java.
Referenced by setLP(), and solve().
soluPath
String wrimsv2.solver.Clp0Solver.soluPath static private
Definition at line 35 of file Clp0Solver.java.
Referenced by setLP(), and solve().
tolerance1
String wrimsv2.solver.Clp0Solver.tolerance1 = "-primalT 1e-008" static private
Definition at line 37 of file Clp0Solver.java.
Referenced by solve().
tolerance2
String wrimsv2.solver.Clp0Solver.tolerance2 = "-primalT 1e-007" static private
Definition at line 38 of file Clp0Solver.java.
Referenced by solve().
varDoubleMap
Map<String, Double> wrimsv2.solver.Clp0Solver.varDoubleMap static
Definition at line 33 of file Clp0Solver.java.
Referenced by assignDvar(), collectDvar(), and wrimsv2.components.ControllerBatch.runModelILP().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/Clp0Solver.java