Wrims-engine: wrimsv2.evaluator.TimeOperation Class Reference
wrimsv2.evaluator.TimeOperation Class Reference
Static Public Member Functions
static Date addOneDay (Date date)
static Date addOneMonth (Date date)
static Date backOneDay (Date date)
static Date backOneMonth (Date date)
static String dayName (int day)
static String dssTime (int year, int month, int day)
static String dssTimeEndDay (int year, int month, int day)
static String dssTimeFrame (int year1, int month1, int day1, int year2, int month2, int day2)
static ParallelVars findTime (int value)
static ParallelVars findTime (int value, int year, int month, int day)
static int getNumberOfTimestep (Date dateA, Date dateB, String timeStep)
static void initMemDate (int month)
static void initOutputDate (int year)
static boolean isLeapYear (int year)
static boolean isMonthlyInterval (String intervalName)
static String monthName (int month)
static String monthNameNumeric (int month)
static int monthValue (String month)
static int numberOfDays (int month, int year)
static boolean range (int dataMonth, String m1, String m2)
static void setMemDate (int month)
static void setOutputDate (int year)
static int waterMonthValue (int month)
static int waterMonthValue (String month)
static int waterYearValue ()
Static Public Attributes
static String[] month_const ={"jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"}
Detailed Description
Definition at line 13 of file TimeOperation.java.
Member Function Documentation
addOneDay()
Date wrimsv2.evaluator.TimeOperation.addOneDay (Date date) static
Definition at line 299 of file TimeOperation.java.
Referenced by wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
addOneMonth()
Date wrimsv2.evaluator.TimeOperation.addOneMonth (Date date) static
Definition at line 287 of file TimeOperation.java.
References numberOfDays().
Referenced by wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
backOneDay()
Date wrimsv2.evaluator.TimeOperation.backOneDay (Date date) static
Definition at line 319 of file TimeOperation.java.
Referenced by wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), and wrimsv2.evaluator.CsvOperation.ouputCSV().
backOneMonth()
Date wrimsv2.evaluator.TimeOperation.backOneMonth (Date date) static
Definition at line 307 of file TimeOperation.java.
References numberOfDays().
Referenced by wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), and wrimsv2.evaluator.CsvOperation.ouputCSV().
dayName()
String wrimsv2.evaluator.TimeOperation.dayName (int day) static
Definition at line 28 of file TimeOperation.java.
References wrimsv2.evaluator.Evaluation.convertIntToString().
Referenced by dssTime(), dssTimeEndDay(), dssTimeFrame(), wrimsv2.evaluator.CsvOperation.formDateData(), wrimsv2.sql.MySQLCWriter.formDateData(), wrimsv2.sql.MySQLRWriterAlt.formDateData(), and wrimsv2.sql.SQLServerRWriterAlt.formDateData().
dssTime()
String wrimsv2.evaluator.TimeOperation.dssTime (int year, int month, int day) static
Definition at line 20 of file TimeOperation.java.
References dayName(), and monthName().
dssTimeEndDay()
String wrimsv2.evaluator.TimeOperation.dssTimeEndDay (int year, int month, int day) static
Definition at line 24 of file TimeOperation.java.
References dayName(), and monthName().
Referenced by wrimsv2.hdf5.HDF5Writer.createDataStructure(), wrimsv2.hdf5.DSSHDF5Converter.createInitHDF5DataStructure(), and wrimsv2.hdf5.DSSHDF5Converter.createSVHDF5DataStructure().
dssTimeFrame()
String wrimsv2.evaluator.TimeOperation.dssTimeFrame (int year1, int month1, int day1, int year2, int month2, int day2) static
Definition at line 16 of file TimeOperation.java.
References dayName(), and monthName().
findTime() [1/2]
ParallelVars wrimsv2.evaluator.TimeOperation.findTime (int value) static
Definition at line 178 of file TimeOperation.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, isMonthlyInterval(), numberOfDays(), and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.components.DebugInterface.getFutureValueDetail(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.ValueEvaluation.getTimeSeries(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.DebugInterface.modifyTimeSeries(), wrimsv2.evaluator.Evaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray(), wrimsv2.evaluator.Evaluation.pastCycleTimeArray(), wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), wrimsv2.evaluator.ValueEvaluation.svarTimeSeries(), wrimsv2.evaluator.Evaluation.tafcfs_term(), wrimsv2.evaluator.ValueEvaluation.tafcfs_term(), wrimsv2.evaluator.Evaluation.timeseries(), wrimsv2.evaluator.Evaluation.timeseries(), wrimsv2.evaluator.ValueEvaluation.timeseries(), wrimsv2.evaluator.ValueEvaluation.timeseries(), and wrimsv2.components.ControllerDebug.updateVarMonitor().
findTime() [2/2]
ParallelVars wrimsv2.evaluator.TimeOperation.findTime (int value, int year, int month, int day) static
Definition at line 214 of file TimeOperation.java.
References wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, isMonthlyInterval(), numberOfDays(), and wrimsv2.components.ControlData.timeStep.
getNumberOfTimestep()
int wrimsv2.evaluator.TimeOperation.getNumberOfTimestep (Date dateA, Date dateB, String timeStep) static
Definition at line 264 of file TimeOperation.java.
References isMonthlyInterval().
Referenced by wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), wrimsv2.evaluator.DssOperation.shiftDvAliasData(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
initMemDate()
void wrimsv2.evaluator.TimeOperation.initMemDate (int month) static
Definition at line 394 of file TimeOperation.java.
References wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.memStartDay, wrimsv2.components.ControlData.memStartMonth, wrimsv2.components.ControlData.memStartYear, wrimsv2.components.ControlData.prevMemDate, wrimsv2.components.ControlData.prevMemDay, wrimsv2.components.ControlData.prevMemMonth, wrimsv2.components.ControlData.prevMemYear, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
initOutputDate()
void wrimsv2.evaluator.TimeOperation.initOutputDate (int year) static
Definition at line 346 of file TimeOperation.java.
References isMonthlyInterval(), numberOfDays(), wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputYear, wrimsv2.components.ControlData.prevOutputDate, wrimsv2.components.ControlData.prevOutputDay, wrimsv2.components.ControlData.prevOutputMonth, wrimsv2.components.ControlData.prevOutputYear, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
isLeapYear()
boolean wrimsv2.evaluator.TimeOperation.isLeapYear (int year) static
Definition at line 164 of file TimeOperation.java.
Referenced by numberOfDays().
isMonthlyInterval()
boolean wrimsv2.evaluator.TimeOperation.isMonthlyInterval (String intervalName) static
Definition at line 433 of file TimeOperation.java.
Referenced by wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.evaluator.Evaluation.daysInTimeStep(), wrimsv2.evaluator.ValueEvaluation.daysInTimeStep(), wrimsv2.components.ControllerDebug.deferPause(), wrimsv2.hdf5.HDF5Writer.differMonthlyDailyCycle(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.evaluator.CsvOperation.factorCfsToTaf(), wrimsv2.evaluator.CsvOperation.factorTafToCfs(), findTime(), findTime(), wrimsv2.evaluator.DssDataSet.generateStudyStartIndex(), wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.DssDataSet.getExceedance_tsi(), getNumberOfTimestep(), wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.hdf5.DSSHDF5Converter.getTotalTimeStep(), initOutputDate(), wrimsv2.hdf5.HDF5Writer.listCycleStaticSv(), wrimsv2.components.ControllerDebug.pauseForDebug(), wrimsv2.components.VariableTimeStep.procCycleTimeStep(), wrimsv2.components.ControllerDebug.resetStartDate(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.evaluator.DssOperation.savedTimeStep(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.components.VariableTimeStep.setCurrentDate(), setMemDate(), wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.evaluator.Evaluation.tafcfs(), wrimsv2.evaluator.ValueEvaluation.tafcfs(), wrimsv2.components.ControllerBatchTest.testIsMonthlyInterval(), wrimsv2.components.ControllerBatchTest.testIsNotMonthlyInterval(), wrimsv2.evaluator.Evaluation.timeSeriesIndex(), wrimsv2.evaluator.Evaluation.timeSeriesIndex(), wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), wrimsv2.components.ControllerDebug.updateVarMonitor(), wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.ControllerBatch.writeOutputDssEveryTenYears(), and wrimsv2.components.ControllerDebug.writeOutputDssEveryTenYears().
monthName()
String wrimsv2.evaluator.TimeOperation.monthName (int month) static
Definition at line 108 of file TimeOperation.java.
Referenced by dssTime(), dssTimeEndDay(), dssTimeFrame(), wrimsv2.components.PreRunModel.setGroundwaterInitFilePath(), and wrimsv2.external.Functiongenfrcstrunofftables.writeTable().
monthNameNumeric()
String wrimsv2.evaluator.TimeOperation.monthNameNumeric (int month) static
Definition at line 136 of file TimeOperation.java.
Referenced by wrimsv2.evaluator.CsvOperation.formDateData(), wrimsv2.sql.MySQLCWriter.formDateData(), wrimsv2.sql.MySQLRWriterAlt.formDateData(), and wrimsv2.sql.SQLServerRWriterAlt.formDateData().
monthValue()
int wrimsv2.evaluator.TimeOperation.monthValue (String month) static
Definition at line 36 of file TimeOperation.java.
Referenced by wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.hdf5.HDF5Reader.openFileAndGroup(), range(), wrimsv2.launch.LaunchConfiguration.setConfig(), wrimsv2.evaluator.Evaluation.term_MONTH_CONST(), wrimsv2.evaluator.ValueEvaluation.term_MONTH_CONST(), wrimsv2.evaluator.Evaluation.term_PASTMONTH(), and wrimsv2.evaluator.ValueEvaluation.term_PASTMONTH().
numberOfDays()
int wrimsv2.evaluator.TimeOperation.numberOfDays (int month, int year) static
Definition at line 247 of file TimeOperation.java.
References isLeapYear().
Referenced by wrimsv2.components.PreRunModel.PreRunModel(), addOneMonth(), wrimsv2.sql.MySQLCWriter.addOneMonth(), wrimsv2.sql.MySQLRWriterAlt.addOneMonth(), wrimsv2.sql.SQLServerRWriterAlt.addOneMonth(), backOneMonth(), wrimsv2.config.ConfigUtils.checkConfigFile(), wrimsv2.hdf5.DSSHDF5Converter.createInitHDF5DataStructure(), wrimsv2.hdf5.DSSHDF5Converter.createSVHDF5DataStructure(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.evaluator.Evaluation.daysIn(), wrimsv2.evaluator.ValueEvaluation.daysIn(), wrimsv2.components.ControllerDebug.debugTimeAddOneMonth(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.evaluator.CsvOperation.factorCfsToTaf(), wrimsv2.evaluator.CsvOperation.factorTafToCfs(), findTime(), findTime(), initOutputDate(), wrimsv2.hdf5.DSSHDF5Converter.readMonthlyInitDssFile(), wrimsv2.components.VariableTimeStep.setCurrentDate(), setMemDate(), wrimsv2.evaluator.Evaluation.tafcfs(), and wrimsv2.evaluator.ValueEvaluation.tafcfs().
range()
boolean wrimsv2.evaluator.TimeOperation.range (int dataMonth, String m1, String m2) static
Definition at line 327 of file TimeOperation.java.
References monthValue().
Referenced by wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.Evaluation.range(), and wrimsv2.evaluator.ValueEvaluation.range().
setMemDate()
void wrimsv2.evaluator.TimeOperation.setMemDate (int month) static
Definition at line 407 of file TimeOperation.java.
References isMonthlyInterval(), wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.memStartDay, wrimsv2.components.ControlData.memStartMonth, wrimsv2.components.ControlData.memStartYear, numberOfDays(), wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputYear, wrimsv2.components.ControlData.prevMemDate, wrimsv2.components.ControlData.prevMemDay, wrimsv2.components.ControlData.prevMemMonth, wrimsv2.components.ControlData.prevMemYear, and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
setOutputDate()
void wrimsv2.evaluator.TimeOperation.setOutputDate (int year) static
Definition at line 382 of file TimeOperation.java.
References wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputYear, wrimsv2.components.ControlData.prevOutputDate, wrimsv2.components.ControlData.prevOutputDay, wrimsv2.components.ControlData.prevOutputMonth, and wrimsv2.components.ControlData.prevOutputYear.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
waterMonthValue() [1/2]
int wrimsv2.evaluator.TimeOperation.waterMonthValue (int month) static
Definition at line 92 of file TimeOperation.java.
waterMonthValue() [2/2]
int wrimsv2.evaluator.TimeOperation.waterMonthValue (String month) static
Definition at line 64 of file TimeOperation.java.
Referenced by wrimsv2.evaluator.Evaluation.term_MONTH(), wrimsv2.evaluator.ValueEvaluation.term_MONTH(), wrimsv2.evaluator.Evaluation.term_MONTH_CONST(), and wrimsv2.evaluator.ValueEvaluation.term_MONTH_CONST().
waterYearValue()
int wrimsv2.evaluator.TimeOperation.waterYearValue () static
Definition at line 100 of file TimeOperation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.components.ControlData.currYear.
Referenced by wrimsv2.external.Functiongenfrcstrunofftables.formTables(), wrimsv2.evaluator.Evaluation.term_YEAR(), and wrimsv2.evaluator.ValueEvaluation.term_YEAR().
Member Data Documentation
month_const
String [] wrimsv2.evaluator.TimeOperation.month_const ={"jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"} static
Definition at line 14 of file TimeOperation.java.
Referenced by wrimsv2.evaluator.Evaluation.argFunction(), and wrimsv2.evaluator.ValueEvaluation.argFunction().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/TimeOperation.java