Wrims-engine: wrimsv2.wreslplus.elements.procedures.ProcMainFile Class Reference
wrimsv2.wreslplus.elements.procedures.ProcMainFile Class Reference
Static Public Member Functions
static void findAllOffSpring_incModel (StudyTemp st)
static void findEffectiveIncludeModel (StudyTemp st)
static void findEffectiveModel (StudyTemp st)
static void findGroupOrder_incModel (StudyTemp st)
static void findKidMap_incModel (StudyTemp st)
Private Member Functions
ProcMainFile ()
Detailed Description
Definition at line 12 of file ProcMainFile.java.
Constructor & Destructor Documentation
ProcMainFile()
wrimsv2.wreslplus.elements.procedures.ProcMainFile.ProcMainFile () private
Definition at line 14 of file ProcMainFile.java.
Member Function Documentation
findAllOffSpring_incModel()
void wrimsv2.wreslplus.elements.procedures.ProcMainFile.findAllOffSpring_incModel (StudyTemp st) static
Definition at line 40 of file ProcMainFile.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, wrimsv2.wreslplus.elements.Tools.findAllOffspring(), and wrimsv2.wreslplus.elements.StudyTemp.kidMap_incModel.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findEffectiveIncludeModel()
void wrimsv2.wreslplus.elements.procedures.ProcMainFile.findEffectiveIncludeModel (StudyTemp st) static
Definition at line 67 of file ProcMainFile.java.
References wrimsv2.wreslplus.elements.StudyTemp.kidMap_incModel.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findEffectiveModel()
void wrimsv2.wreslplus.elements.procedures.ProcMainFile.findEffectiveModel (StudyTemp st) static
Definition at line 80 of file ProcMainFile.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslplus.elements.StudyTemp.incModelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findGroupOrder_incModel()
void wrimsv2.wreslplus.elements.procedures.ProcMainFile.findGroupOrder_incModel (StudyTemp st) static
Definition at line 54 of file ProcMainFile.java.
References wrimsv2.wreslplus.elements.StudyTemp.allOffspringMap_incModel, wrimsv2.wreslplus.elements.StudyTemp.fileGroupOrder_incModel, wrimsv2.wreslplus.elements.Tools.findFileHierarchy(), and wrimsv2.wreslplus.elements.StudyTemp.noKid_incModel.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
findKidMap_incModel()
void wrimsv2.wreslplus.elements.procedures.ProcMainFile.findKidMap_incModel (StudyTemp st) static
Definition at line 18 of file ProcMainFile.java.
References wrimsv2.wreslplus.elements.StudyTemp.kidMap_incModel, wrimsv2.wreslplus.elements.StudyTemp.modelMap, and wrimsv2.wreslplus.elements.StudyTemp.noKid_incModel.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ProcMainFile.java