Wrims-engine: wrimsv2.solver.ortools.Misc Class Reference
wrimsv2.solver.ortools.Misc Class Reference
Static Protected Member Functions
static void addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName)
static void assignDvar (LinkedHashMap< String, Double > solution)
static void getSolverInformation (int modelStatus)
static void setConstraints (MPModel m)
static void setDVars (MPModel m)
static void setWeights (MPModel m)
Detailed Description
Definition at line 26 of file Misc.java.
Member Function Documentation
addConditionalSlackSurplusToDvarMap()
void wrimsv2.solver.ortools.Misc.addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName) static protected
Definition at line 94 of file Misc.java.
References wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
Referenced by setConstraints().
assignDvar()
void wrimsv2.solver.ortools.Misc.assignDvar (LinkedHashMap< String, Double > solution) static protected
Definition at line 101 of file Misc.java.
References wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.solver.ortools.OrToolsSolver.run().
getSolverInformation()
void wrimsv2.solver.ortools.Misc.getSolverInformation (int modelStatus) static protected
Definition at line 216 of file Misc.java.
References wrimsv2.components.Error.addSolvingError().
Referenced by wrimsv2.solver.ortools.OrToolsSolver.run().
setConstraints()
void wrimsv2.solver.ortools.Misc.setConstraints (MPModel m) static protected
Definition at line 29 of file Misc.java.
References addConditionalSlackSurplusToDvarMap(), wrimsv2.components.Error.addSolvingError(), wrimsv2.solver.mpmodel.MPModel.createConstraint(), wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList, and wrimsv2.commondata.wresldata.Param.inf.
Referenced by wrimsv2.solver.ortools.OrToolsSolver.createModel().
setDVars()
void wrimsv2.solver.ortools.Misc.setDVars (MPModel m) static protected
Definition at line 159 of file Misc.java.
References wrimsv2.solver.mpmodel.MPModel.addGeneralVar(), wrimsv2.solver.mpmodel.MPModel.addIntVar(), wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
Referenced by wrimsv2.solver.ortools.OrToolsSolver.createModel().
setWeights()
void wrimsv2.solver.ortools.Misc.setWeights (MPModel m) static protected
Definition at line 185 of file Misc.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtList, and wrimsv2.commondata.wresldata.ModelDataSet.wtTimeArrayList.
Referenced by wrimsv2.solver.ortools.OrToolsSolver.createModel().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/ortools/Misc.java