Wrims-engine: wrimsv2.components.VariableTimeStep Class Reference
wrimsv2.components.VariableTimeStep Class Reference
Static Public Member Functions
static int checkEndDate (int day1, int month1, int year1, int day2, int month2, int year2)
static void currTimeAddOneDay ()
static void currTimeAddOneMonth ()
static int getTotalTimeStep (String timeStep)
static ArrayList< Integer > getTotalTimeStep (StudyDataSet sds)
static void initialCurrTimeStep (ArrayList< String > modelList)
static void initialCycleStartDate ()
static void procCycleTimeStep (StudyDataSet sds)
static void setCurrentDate (StudyDataSet sds, int day, int month, int year)
static void setCycleEndDate (StudyDataSet sds)
static void setCycleStartDate (int day, int month, int year)
static void setCycleTimeStep (StudyDataSet sds)
Static Private Member Functions
static void addOneDayToCycleEndDate ()
static void addOneMonthToCycleEndDate ()
Detailed Description
Definition at line 13 of file VariableTimeStep.java.
Member Function Documentation
addOneDayToCycleEndDate()
void wrimsv2.components.VariableTimeStep.addOneDayToCycleEndDate () static private
Definition at line 73 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, and wrimsv2.components.ControlData.cycleStartYear.
Referenced by setCycleEndDate().
addOneMonthToCycleEndDate()
void wrimsv2.components.VariableTimeStep.addOneMonthToCycleEndDate () static private
Definition at line 42 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartMonth, and wrimsv2.components.ControlData.cycleStartYear.
Referenced by setCycleEndDate().
checkEndDate()
int wrimsv2.components.VariableTimeStep.checkEndDate (int day1, int month1, int year1, int day2, int month2, int year2) static
Definition at line 162 of file VariableTimeStep.java.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
currTimeAddOneDay()
void wrimsv2.components.VariableTimeStep.currTimeAddOneDay () static
Definition at line 62 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, and wrimsv2.components.ControlData.currYear.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
currTimeAddOneMonth()
void wrimsv2.components.VariableTimeStep.currTimeAddOneMonth () static
Definition at line 52 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
getTotalTimeStep() [1/2]
int wrimsv2.components.VariableTimeStep.getTotalTimeStep (String timeStep) static
Definition at line 115 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
getTotalTimeStep() [2/2]
ArrayList< Integer > wrimsv2.components.VariableTimeStep.getTotalTimeStep (StudyDataSet sds) static
Definition at line 84 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.monMemSection, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, wrimsv2.components.ControlData.totalTimeStep, and wrimsv2.components.ControlData.yearOutputSection.
Referenced by wrimsv2.components.PreRunModel.PreRunModel(), wrimsv2.external.Functioninitgwsystem.execute(), wrimsv2.components.Controller.generateStudyFile(), wrimsv2.components.ControllerBatch.generateStudyFile(), wrimsv2.components.ControllerDebug.generateStudyFile(), and wrimsv2.components.ControllerSG.generateStudyFile().
initialCurrTimeStep()
void wrimsv2.components.VariableTimeStep.initialCurrTimeStep (ArrayList< String > modelList) static
Definition at line 149 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.currTimeStep.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
initialCycleStartDate()
void wrimsv2.components.VariableTimeStep.initialCycleStartDate () static
Definition at line 156 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, and wrimsv2.components.ControlData.startYear.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
procCycleTimeStep()
void wrimsv2.components.VariableTimeStep.procCycleTimeStep (StudyDataSet sds) static
Definition at line 133 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.cycleTimeStepPriority, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), and wrimsv2.evaluator.TimeOperation.isMonthlyInterval().
Referenced by wrimsv2.components.PreRunModel.PreRunModel(), and wrimsv2.components.ControllerDebug.resetStartDate().
setCurrentDate()
void wrimsv2.components.VariableTimeStep.setCurrentDate (StudyDataSet sds, int day, int month, int year) static
Definition at line 176 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
setCycleEndDate()
void wrimsv2.components.VariableTimeStep.setCycleEndDate (StudyDataSet sds) static
Definition at line 26 of file VariableTimeStep.java.
References addOneDayToCycleEndDate(), addOneMonthToCycleEndDate(), wrimsv2.components.ControlData.cycleTimeStepPriority, and wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
setCycleStartDate()
void wrimsv2.components.VariableTimeStep.setCycleStartDate (int day, int month, int year) static
Definition at line 36 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, and wrimsv2.components.ControlData.cycleStartYear.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
setCycleTimeStep()
void wrimsv2.components.VariableTimeStep.setCycleTimeStep (StudyDataSet sds) static
Definition at line 15 of file VariableTimeStep.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), wrimsv2.components.ControlData.partE, wrimsv2.components.ControlData.timeStep, and wrimsv2.commondata.wresldata.Param.undefined.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/VariableTimeStep.java