Wrims-engine: wrimsv2.evaluator.PreEvaluatorTree Class Reference
wrimsv2.evaluator.PreEvaluatorTree Class Reference
Public Member Functions
PreEvaluatorTree (StudyDataSet sds)
void preEvaluateSvar ()
Private Attributes
ArrayList< String > svList
Map< String, Svar > svMap
Detailed Description
Definition at line 21 of file PreEvaluatorTree.java.
Constructor & Destructor Documentation
PreEvaluatorTree()
wrimsv2.evaluator.PreEvaluatorTree.PreEvaluatorTree (StudyDataSet sds)
Definition at line 25 of file PreEvaluatorTree.java.
References wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), preEvaluateSvar(), wrimsv2.commondata.wresldata.ModelDataSet.svList, svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, and svMap.
Member Function Documentation
preEvaluateSvar()
void wrimsv2.evaluator.PreEvaluatorTree.preEvaluateSvar ()
Definition at line 37 of file PreEvaluatorTree.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseConditionWalkers, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseExpressionWalkers, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currEvalName, svList, and svMap.
Referenced by PreEvaluatorTree().
Member Data Documentation
svList
ArrayList<String> wrimsv2.evaluator.PreEvaluatorTree.svList private
Definition at line 22 of file PreEvaluatorTree.java.
Referenced by PreEvaluatorTree(), and preEvaluateSvar().
svMap
Map<String, Svar> wrimsv2.evaluator.PreEvaluatorTree.svMap private
Definition at line 23 of file PreEvaluatorTree.java.
Referenced by PreEvaluatorTree(), and preEvaluateSvar().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/PreEvaluatorTree.java