Wrims-engine: wrimsv2.tools.MultiStepAnalyzer Class Reference
wrimsv2.tools.MultiStepAnalyzer Class Reference
Public Member Functions
MultiStepAnalyzer ()
Private Member Functions
void analyzeConstraints ()
void analyzeOneConstraint (String constraintKey, EvalConstraint ec)
String processVariable (String variable)
Private Attributes
Map< String, EvalConstraint > constraintMap
int fammonths =4
int ifut
BufferedWriter out
ArrayList< String > sortedConstraintKeys
Detailed Description
Definition at line 20 of file MultiStepAnalyzer.java.
Constructor & Destructor Documentation
MultiStepAnalyzer()
wrimsv2.tools.MultiStepAnalyzer.MultiStepAnalyzer ()
Definition at line 27 of file MultiStepAnalyzer.java.
References analyzeConstraints(), constraintMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, fammonths, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), ifut, wrimsv2.components.FilePaths.mainDirectory, out, and sortedConstraintKeys.
Member Function Documentation
analyzeConstraints()
void wrimsv2.tools.MultiStepAnalyzer.analyzeConstraints () private
Definition at line 51 of file MultiStepAnalyzer.java.
References analyzeOneConstraint(), constraintMap, ifut, and sortedConstraintKeys.
Referenced by MultiStepAnalyzer().
analyzeOneConstraint()
void wrimsv2.tools.MultiStepAnalyzer.analyzeOneConstraint (String constraintKey, EvalConstraint ec) private
Definition at line 68 of file MultiStepAnalyzer.java.
References wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), out, and processVariable().
Referenced by analyzeConstraints().
processVariable()
String wrimsv2.tools.MultiStepAnalyzer.processVariable (String variable) private
Definition at line 95 of file MultiStepAnalyzer.java.
References ifut.
Referenced by analyzeOneConstraint().
Member Data Documentation
constraintMap
Map<String, EvalConstraint> wrimsv2.tools.MultiStepAnalyzer.constraintMap private
Definition at line 21 of file MultiStepAnalyzer.java.
Referenced by MultiStepAnalyzer(), and analyzeConstraints().
fammonths
int wrimsv2.tools.MultiStepAnalyzer.fammonths =4 private
Definition at line 22 of file MultiStepAnalyzer.java.
Referenced by MultiStepAnalyzer().
ifut
int wrimsv2.tools.MultiStepAnalyzer.ifut private
Definition at line 25 of file MultiStepAnalyzer.java.
Referenced by MultiStepAnalyzer(), analyzeConstraints(), and processVariable().
out
BufferedWriter wrimsv2.tools.MultiStepAnalyzer.out private
Definition at line 23 of file MultiStepAnalyzer.java.
Referenced by MultiStepAnalyzer(), and analyzeOneConstraint().
sortedConstraintKeys
ArrayList<String> wrimsv2.tools.MultiStepAnalyzer.sortedConstraintKeys private
Definition at line 24 of file MultiStepAnalyzer.java.
Referenced by MultiStepAnalyzer(), and analyzeConstraints().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/MultiStepAnalyzer.java