Wrims-engine: wrimsv2.external.Functiongetfinalmrdo Class Reference
wrimsv2.external.Functiongetfinalmrdo Class Reference
Public Member Functions
Functiongetfinalmrdo ()
void execute (Stack stack)
Private Member Functions
float getFinalMrdo (float Qroe, int bday_roe, int eday_roe, float Qchs, int bday_chs, int eday_chs, float Qcnf, int bday_cnf, int eday_cnf, float Qemt1, int bday_emt1, int eday_emt1, float Qemt2, int bday_emt2, int eday_emt2, float Qjpt1, int bday_jpt1, int eday_jpt1, float Qjpt2, int bday_jpt2, int eday_jpt2, float Qcol1, int bday_col1, int eday_col1, float Qcol2, int bday_col2, int eday_col2, float Qrsl1, int bday_rsl1, int eday_rsl1, float Qrsl2, int bday_rsl2, int eday_rsl2, float Qflw, int bday_flw, int eday_flw, int wyear, int month, int daysin)
float sum (float[] array)
Private Attributes
int _lastmonth
Additional Inherited Members
Static Public Attributes inherited from wrimsv2.external.ExternalFunction
static String externalDir =FilePaths.mainDirectory+File.separator+"external"+File.separator
Detailed Description
Custom JEP class for calculating Final Mrdo.
Author
Clay Booher
Definition at line 10 of file Functiongetfinalmrdo.java.
Constructor & Destructor Documentation
Functiongetfinalmrdo()
wrimsv2.external.Functiongetfinalmrdo.Functiongetfinalmrdo ()
Definition at line 14 of file Functiongetfinalmrdo.java.
Member Function Documentation
execute()
void wrimsv2.external.Functiongetfinalmrdo.execute (Stack stack)
Reimplemented from wrimsv2.external.ExternalFunction.
Definition at line 18 of file Functiongetfinalmrdo.java.
References getFinalMrdo().
getFinalMrdo()
float wrimsv2.external.Functiongetfinalmrdo.getFinalMrdo (float Qroe, int bday_roe, int eday_roe, float Qchs, int bday_chs, int eday_chs, float Qcnf, int bday_cnf, int eday_cnf, float Qemt1, int bday_emt1, int eday_emt1, float Qemt2, int bday_emt2, int eday_emt2, float Qjpt1, int bday_jpt1, int eday_jpt1, float Qjpt2, int bday_jpt2, int eday_jpt2, float Qcol1, int bday_col1, int eday_col1, float Qcol2, int bday_col2, int eday_col2, float Qrsl1, int bday_rsl1, int eday_rsl1, float Qrsl2, int bday_rsl2, int eday_rsl2, float Qflw, int bday_flw, int eday_flw, int wyear, int month, int daysin) private
Definition at line 111 of file Functiongetfinalmrdo.java.
References _lastmonth, and sum().
Referenced by execute().
sum()
float wrimsv2.external.Functiongetfinalmrdo.sum (float[] array) private
Definition at line 246 of file Functiongetfinalmrdo.java.
References sum().
Referenced by getFinalMrdo(), and sum().
Member Data Documentation
_lastmonth
int wrimsv2.external.Functiongetfinalmrdo._lastmonth private
Definition at line 11 of file Functiongetfinalmrdo.java.
Referenced by getFinalMrdo().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/Functiongetfinalmrdo.java