Wrims-engine: wrimsv2.tools.General Class Reference
wrimsv2.tools.General Class Reference
Static Public Member Functions
static void getPID ()
static boolean isSelectedCycleOutput (String strCycleI)
Detailed Description
Definition at line 5 of file General.java.
Member Function Documentation
getPID()
void wrimsv2.tools.General.getPID () static
Definition at line 19 of file General.java.
References wrimsv2.components.ControlData.pid.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), and wrimsv2.components.ControllerDebug.run().
isSelectedCycleOutput()
boolean wrimsv2.tools.General.isSelectedCycleOutput (String strCycleI) static
Definition at line 6 of file General.java.
References wrimsv2.components.ControlData.outputAllCycles, and wrimsv2.components.ControlData.selectedCycles.
Referenced by wrimsv2.hdf5.HDF5Writer.listCycleStaticSv(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.ControllerBatch.runModelXA(), wrimsv2.components.ControllerSG.runModelXA(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), and wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/General.java