Wrims-engine: wrimsv2.external.ExternalFunction Class Reference
wrimsv2.external.ExternalFunction Class Reference abstract
Public Member Functions
abstract void execute (Stack stack)
Static Public Attributes
static String externalDir =FilePaths.mainDirectory+File.separator+"external"+File.separator
Detailed Description
Definition at line 8 of file ExternalFunction.java.
Member Function Documentation
execute()
abstract void wrimsv2.external.ExternalFunction.execute (Stack stack) abstract
Reimplemented in wrimsv2.external.Functiona56_allocation, wrimsv2.external.Functionadvancegwstate, wrimsv2.external.Functionann_x2, wrimsv2.external.Functionann_x2_daily, wrimsv2.external.Functionannec, wrimsv2.external.Functionannec_a, wrimsv2.external.Functionannec_curmoninpsplit_a, wrimsv2.external.Functionannec_matchdsm2, wrimsv2.external.Functionannec_matchdsm2_a, wrimsv2.external.Functionannlinegen, wrimsv2.external.Functionannlinegen_a, wrimsv2.external.Functionannlinegen_daily, wrimsv2.external.Functioncamdll, wrimsv2.external.Functioncamsjrdll, wrimsv2.external.Functiondoestimation, wrimsv2.external.Functionemmatonsurrogateec, wrimsv2.external.Functionemmatonsurrogatelinegen, wrimsv2.external.Functiongenfrcstrunofftables, wrimsv2.external.Functionget_req_do, wrimsv2.external.Functiongetfinalmrdo, wrimsv2.external.Functiongetghbflow, wrimsv2.external.Functiongetgw_h, wrimsv2.external.Functiongetndo_x2, wrimsv2.external.Functiongetndo_x2_curmonndosplit, wrimsv2.external.Functiongetndo_x2_daily, wrimsv2.external.Functiongetpercentpumpshort, wrimsv2.external.Functiongetpumpshort, wrimsv2.external.Functiongetseep, wrimsv2.external.Functiongetseep_givenstrmflow, wrimsv2.external.Functiongetstrm_h, wrimsv2.external.Functiongettdrainintostream, wrimsv2.external.Functionhydroforecast, wrimsv2.external.Functioninitgwsystem, wrimsv2.external.Functionprintgwresults, wrimsv2.external.Functionrequiredsac, wrimsv2.external.Functionsetdp, wrimsv2.external.Functionsetgeneralheadbc, wrimsv2.external.Functionsetgp, wrimsv2.external.Functionsetspecifiedflowbc, wrimsv2.external.Functionsetspecifiedheadbc, wrimsv2.external.Functionsetstrmflow, wrimsv2.external.Functionsimgw, wrimsv2.external.Functionsuitablehabitat, wrimsv2.external.Functionsurrogateec, wrimsv2.external.Functionsurrogateeclinearize, wrimsv2.external.Functiontablegen, and wrimsv2.external.Functiontablegen1.
Referenced by wrimsv2.evaluator.Evaluation.argFunction(), wrimsv2.evaluator.ValueEvaluation.argFunction(), wrimsv2.evaluator.Evaluation.noArgFunction(), and wrimsv2.evaluator.ValueEvaluation.noArgFunction().
Member Data Documentation
externalDir
String wrimsv2.external.ExternalFunction.externalDir =FilePaths.mainDirectory+File.separator+"external"+File.separator static
Definition at line 10 of file ExternalFunction.java.
Referenced by wrimsv2.external.Functiondoestimation.doestimation(), wrimsv2.external.Functionemmatonsurrogateec.emmatonANN(), wrimsv2.external.Functionemmatonsurrogatelinegen.emmatonANN(), wrimsv2.external.SalinitySurrogateSetup.emmatonANN(), and wrimsv2.external.Functionsuitablehabitat.SuitableHabitat().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/ExternalFunction.java