Wrims-engine: wrimsv2.wreslparser.elements.IncludeFile Class Reference
wrimsv2.wreslparser.elements.IncludeFile Class Reference
Public Member Functions
IncludeFile ()
String equalEva ()
boolean equals (Object obj)
Public Attributes
String absFilePath
String fromWresl
String scope
Detailed Description
Definition at line 5 of file IncludeFile.java.
Constructor & Destructor Documentation
IncludeFile()
wrimsv2.wreslparser.elements.IncludeFile.IncludeFile ()
Definition at line 11 of file IncludeFile.java.
References fromWresl, scope, and wrimsv2.commondata.wresldata.Param.undefined.
Referenced by equals().
Member Function Documentation
equalEva()
String wrimsv2.wreslparser.elements.IncludeFile.equalEva ()
Definition at line 17 of file IncludeFile.java.
References scope.
Referenced by equals().
equals()
boolean wrimsv2.wreslparser.elements.IncludeFile.equals (Object obj)
Definition at line 25 of file IncludeFile.java.
References IncludeFile(), and equalEva().
Member Data Documentation
absFilePath
String wrimsv2.wreslparser.elements.IncludeFile.absFilePath
Definition at line 8 of file IncludeFile.java.
fromWresl
String wrimsv2.wreslparser.elements.IncludeFile.fromWresl
Definition at line 9 of file IncludeFile.java.
Referenced by IncludeFile().
scope
String wrimsv2.wreslparser.elements.IncludeFile.scope
Definition at line 7 of file IncludeFile.java.
Referenced by IncludeFile(), and equalEva().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/IncludeFile.java