Wrims-engine: wrimsv2.sql.socket.SQLServer Class Reference
wrimsv2.sql.socket.SQLServer Class Reference
Public Member Functions
SQLServer ()
void downloadFile ()
void newServer ()
void process ()
Static Public Member Functions
static void main (String[] args)
Public Attributes
int port =13267
Private Attributes
File dstFile = null
FileEvent fileEvent
FileOutputStream fileOutputStream = null
ObjectInputStream inputStream = null
String returnMessage = "CSV Transferred"
ServerSocket serverSocket = null
Socket socket = null
Detailed Description
Definition at line 13 of file SQLServer.java.
Constructor & Destructor Documentation
SQLServer()
wrimsv2.sql.socket.SQLServer.SQLServer ()
Definition at line 24 of file SQLServer.java.
Referenced by main(), and newServer().
Member Function Documentation
downloadFile()
void wrimsv2.sql.socket.SQLServer.downloadFile ()
Definition at line 61 of file SQLServer.java.
References dstFile, fileEvent, fileOutputStream, inputStream, returnMessage, and socket.
Referenced by process().
main()
void wrimsv2.sql.socket.SQLServer.main (String[] args) static
Definition at line 107 of file SQLServer.java.
References SQLServer(), and process().
newServer()
void wrimsv2.sql.socket.SQLServer.newServer ()
Definition at line 102 of file SQLServer.java.
References SQLServer(), and process().
Referenced by process().
process()
void wrimsv2.sql.socket.SQLServer.process ()
Accepts socket connection.
Definition at line 31 of file SQLServer.java.
References downloadFile(), inputStream, newServer(), port, serverSocket, and socket.
Referenced by main(), and newServer().
Member Data Documentation
dstFile
File wrimsv2.sql.socket.SQLServer.dstFile = null private
Definition at line 18 of file SQLServer.java.
Referenced by downloadFile().
fileEvent
FileEvent wrimsv2.sql.socket.SQLServer.fileEvent private
Definition at line 17 of file SQLServer.java.
Referenced by downloadFile().
fileOutputStream
FileOutputStream wrimsv2.sql.socket.SQLServer.fileOutputStream = null private
Definition at line 19 of file SQLServer.java.
Referenced by downloadFile().
inputStream
ObjectInputStream wrimsv2.sql.socket.SQLServer.inputStream = null private
Definition at line 16 of file SQLServer.java.
Referenced by downloadFile(), and process().
port
int wrimsv2.sql.socket.SQLServer.port =13267
Definition at line 22 of file SQLServer.java.
Referenced by process().
returnMessage
String wrimsv2.sql.socket.SQLServer.returnMessage = "CSV Transferred" private
Definition at line 20 of file SQLServer.java.
Referenced by downloadFile().
serverSocket
ServerSocket wrimsv2.sql.socket.SQLServer.serverSocket = null private
Definition at line 14 of file SQLServer.java.
Referenced by process().
socket
Socket wrimsv2.sql.socket.SQLServer.socket = null private
Definition at line 15 of file SQLServer.java.
Referenced by downloadFile(), and process().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/sql/socket/SQLServer.java