Wrims-engine: wrimsv2.ilp.ILP Class Reference
wrimsv2.ilp.ILP Class Reference
Static Public Member Functions
static void closeCplexLpFile ()
static void closeIlpFile ()
static void createNoteFile ()
static void findDvarEffective ()
static File getIlpDir ()
static String getYearMonthCycle ()
static void initializeIlp ()
static void logUsageMemory (int year, int month, int day, int cycleIndex)
static void reOpenCplexLpFile (boolean isAppend)
static void saveCplexLpStringToFile ()
static void setCplxLpDir (String dir)
static void setDvarFile (String append)
static void setIlpFile ()
static void setLPSolveDir (String dir)
static void setMaximumFractionDigits ()
static void setObjValueFile ()
static void setSvarFile ()
static void setVarDir ()
static void setVarFile ()
static void writeDvarValue_Clp0_Cbc0 (Map< String, Double > varDoubleMap)
static void writeDvarValue_Gurobi ()
static void writeDvarValue_LPSOLVE ()
static void writeDvarValue_OrTools ()
static void writeDvarValue_XA ()
static void writeIlp ()
static void writeMPModelFile (MPModel m)
static void writeNote (String msg, PrintWriter outFile)
static void writeNoteLn (String msg)
static void writeNoteLn (String msg, boolean printToScreen, boolean isErr)
static void writeNoteLn (String msg, PrintWriter outFile)
static void writeNoteLn (String msg, String noteStr)
static void writeNoteLn (String msg, String noteStr, PrintWriter outFile)
static void writeObjValue_Clp0_Cbc0 ()
static void writeObjValue_Gurobi ()
static void writeObjValue_LPSOLVE ()
static void writeObjValue_OrTools ()
static void writeObjValue_XA ()
static void writeObjValueLog (String msg, String objValueStr, PrintWriter outFile)
static void writeSvarValue ()
Static Public Attributes
static PrintWriter _noteFile
static PrintWriter _noteFile_cbc_int
static PrintWriter _noteFile_cbc_int_log
static PrintWriter _noteFile_cbc_obj
static PrintWriter _noteFile_cbc_time
static PrintWriter _noteFile_memory
static PrintWriter _noteFile_timeusage
static PrintWriter _noteFile_xa_int
static PrintWriter _noteFile_xa_obj
static PrintWriter _watchFile_cbc
static PrintWriter _watchFile_xa
static String amplFilePath
static String cplexLpFilePath
static ArrayList< String > intList = null
static boolean logging = false
static boolean loggingAllCycles = true
static boolean loggingAmpl = false
static boolean loggingCplexLp = false
static boolean loggingLpSolve = false
static boolean loggingMPModel = false
static boolean loggingUsageMemeory = false
static boolean loggingVariableValue = false
static boolean loggingVariableValueRound = false
static boolean loggingVariableValueRound10 = false
static String lpSolveFilePath
static int maximumFractionDigits = 16
static String mpModelFilePath
Private Member Functions
ILP ()
Static Private Member Functions
static Map< String, WeightElement > findActiveWeightMap ()
static Set< String > findDvarInConstraint ()
static String findDvarValueStr_XA (Set< String > dvar)
static String findHeaderStr (String commentSymbol)
static String findSvarValueStr ()
static Set< String > findUnWeightedDvarInConstraint (Set< String > dvar_inConstraint, Set< String > dvar_weighted)
static Set< String > findWeightedDvar ()
static ArrayList< ArrayList< String > > prepareDvarToWrite (Set< String > dvar_effective)
static void setAmplFile ()
static void setCplexLpFile ()
static void setCplexLpString ()
static void setLpSolveFile ()
static void setMPModelFile ()
static void writeAmplFile ()
static void writeCplexLpFile ()
static void writeDvarValue_Clp0_Cbc0 (PrintWriter dvarFile, Set< String > dvar_effective, Map< String, Double > varDoubleMap)
static void writeDvarValue_Gurobi (PrintWriter dvarFile, Set< String > dvar_effective)
static void writeDvarValue_LPSOLVE (PrintWriter dvarFile, Set< String > dvar_effective)
static void writeDvarValue_OrTools (PrintWriter dvarFile, Set< String > dvar_effective)
static void writeDvarValue_XA (PrintWriter dvarFile, Set< String > dvar_effective)
static void writeLpSolveFile ()
static void writeObjValue (String objValueStr, PrintWriter outFile, String commentSym)
static void writeSvarValue (PrintWriter svarFile)
Static Private Attributes
static String _amplDir
static PrintWriter _amplFile
static String _cplexLpDir
static PrintWriter _cplexLpFile
static StringWriter _cplexLpString
static File _dvarDir
static PrintWriter _dvarFile
static File _ilpDir
static File _ilpRootDir
static String _lpSolveDir
static PrintWriter _lpSolveFile
static String _mpModelDir
static ObjectOutputStream _mpModelFile
static PrintWriter _objValueFile
static File _svarDir
static PrintWriter _svarFile
static final String ampl_comment_Symbol = "#"
static final String cplexLp_comment_Symbol = "\\"
static String cplexLpFileName
static DecimalFormat df
static Set< String > dvar_effective
static final String lpSolve_comment_Symbol = "//"
Detailed Description
Definition at line 46 of file ILP.java.
Constructor & Destructor Documentation
ILP()
wrimsv2.ilp.ILP.ILP () private
Definition at line 100 of file ILP.java.
Referenced by closeIlpFile(), createNoteFile(), initializeIlp(), logUsageMemory(), setIlpFile(), writeIlp(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
Member Function Documentation
closeCplexLpFile()
void wrimsv2.ilp.ILP.closeCplexLpFile () static
Definition at line 614 of file ILP.java.
References _cplexLpFile.
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
closeIlpFile()
void wrimsv2.ilp.ILP.closeIlpFile () static
Definition at line 433 of file ILP.java.
References ILP(), _amplFile, _cplexLpFile, _dvarFile, _lpSolveFile, _mpModelFile, and _svarFile.
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), and wrimsv2.components.ControllerDebug.runModelSolvers().
createNoteFile()
void wrimsv2.ilp.ILP.createNoteFile () static
Definition at line 110 of file ILP.java.
References ILP(), _ilpDir, _noteFile, _noteFile_cbc_int, _noteFile_cbc_int_log, _noteFile_cbc_obj, _noteFile_cbc_time, _noteFile_memory, _noteFile_timeusage, _noteFile_xa_int, _noteFile_xa_obj, _watchFile_cbc, _watchFile_xa, wrimsv2.commondata.wresldata.StudyDataSet.allIntDv, wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.solver.CbcSolver.cbcLibName, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.StudyDataSet.cycIntDvMap, wrimsv2.components.ControlData.dateTimeAppend, wrimsv2.solver.CbcSolver.intLog, wrimsv2.solver.CbcSolver.logObj, wrimsv2.wreslparser.elements.Tools.openFile(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.watchList, and writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.solver.CbcSolver.init(), initializeIlp(), and wrimsv2.components.ControllerDebug.runModelSolvers().
findActiveWeightMap()
Map< String, WeightElement > wrimsv2.ilp.ILP.findActiveWeightMap () static private
Definition at line 713 of file ILP.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), and wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList.
Referenced by writeAmplFile(), writeCplexLpFile(), and writeLpSolveFile().
findDvarEffective()
void wrimsv2.ilp.ILP.findDvarEffective () static
Definition at line 246 of file ILP.java.
References dvar_effective, findDvarInConstraint(), and findWeightedDvar().
Referenced by wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.newProblem(), and writeIlp().
findDvarInConstraint()
Set< String > wrimsv2.ilp.ILP.findDvarInConstraint () static private
Definition at line 686 of file ILP.java.
References wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap().
Referenced by findDvarEffective().
findDvarValueStr_XA()
String wrimsv2.ilp.ILP.findDvarValueStr_XA (Set< String > dvar) static private
Definition at line 745 of file ILP.java.
References wrimsv2.components.ControlData.xasolver.
findHeaderStr()
String wrimsv2.ilp.ILP.findHeaderStr (String commentSymbol) static private
Definition at line 659 of file ILP.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, and wrimsv2.components.ControlData.solverName.
Referenced by writeAmplFile(), writeCplexLpFile(), and writeLpSolveFile().
findSvarValueStr()
String wrimsv2.ilp.ILP.findSvarValueStr () static private
Definition at line 728 of file ILP.java.
References wrimsv2.components.ControlData.currSvMap.
findUnWeightedDvarInConstraint()
Set< String > wrimsv2.ilp.ILP.findUnWeightedDvarInConstraint (Set< String > dvar_inConstraint, Set< String > dvar_weighted) static private
Definition at line 702 of file ILP.java.
findWeightedDvar()
Set< String > wrimsv2.ilp.ILP.findWeightedDvar () static private
Definition at line 676 of file ILP.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), and wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList.
Referenced by findDvarEffective().
getIlpDir()
File wrimsv2.ilp.ILP.getIlpDir () static
Definition at line 104 of file ILP.java.
References _ilpDir, _ilpRootDir, wrimsv2.wreslparser.elements.StudyUtils.configFileName, and wrimsv2.components.FilePaths.mainDirectory.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.external.SalinitySurrogateSetup.getManager(), wrimsv2.solver.CbcSolver.init(), wrimsv2.evaluator.WeightEval.outputWtTableAR(), wrimsv2.solver.CbcSolver.reloadAndWriteLp(), wrimsv2.solver.CbcSolver.reloadAndWriteLp(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.DebugInterface.setSolverOptions(), and wrimsv2.solver.CbcSolver.writeCbcLp().
getYearMonthCycle()
String wrimsv2.ilp.ILP.getYearMonthCycle () static
Definition at line 500 of file ILP.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currMonth, and wrimsv2.components.ControlData.currYear.
Referenced by wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logCbcWatchList(), wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.ControllerSG.runModelCbc(), saveCplexLpStringToFile(), setAmplFile(), setCplexLpFile(), setDvarFile(), setSvarFile(), setVarFile(), wrimsv2.solver.Clp0Solver.solve(), wrimsv2.components.Error.writeErrorLog(), writeObjValue_Clp0_Cbc0(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
initializeIlp()
void wrimsv2.ilp.ILP.initializeIlp () static
Definition at line 183 of file ILP.java.
References ILP(), _amplDir, _cplexLpDir, _ilpDir, _ilpRootDir, _lpSolveDir, _mpModelDir, _objValueFile, wrimsv2.wreslparser.elements.StudyUtils.configFileName, createNoteFile(), wrimsv2.components.FilePaths.mainDirectory, wrimsv2.wreslparser.elements.Tools.openFile(), setMaximumFractionDigits(), and setVarDir().
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.DebugInterface.setSolverOptions().
logUsageMemory()
void wrimsv2.ilp.ILP.logUsageMemory (int year, int month, int day, int cycleIndex) static
Definition at line 1121 of file ILP.java.
References ILP(), and wrimsv2.components.ControlData.pid.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
prepareDvarToWrite()
ArrayList< ArrayList< String > > wrimsv2.ilp.ILP.prepareDvarToWrite (Set< String > dvar_effective) static private
Definition at line 826 of file ILP.java.
References wrimsv2.components.ControlData.currModelDataSet, dvar_effective, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), and wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList.
Referenced by writeDvarValue_Clp0_Cbc0(), writeDvarValue_Gurobi(), writeDvarValue_LPSOLVE(), writeDvarValue_OrTools(), and writeDvarValue_XA().
reOpenCplexLpFile()
void wrimsv2.ilp.ILP.reOpenCplexLpFile (boolean isAppend) static
Definition at line 628 of file ILP.java.
References _cplexLpDir, _cplexLpFile, cplexLpFileName, and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
saveCplexLpStringToFile()
void wrimsv2.ilp.ILP.saveCplexLpStringToFile () static
Definition at line 594 of file ILP.java.
References _cplexLpDir, _cplexLpFile, _cplexLpString, cplexLpFileName, cplexLpFilePath, getYearMonthCycle(), and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
setAmplFile()
void wrimsv2.ilp.ILP.setAmplFile () static private
Definition at line 642 of file ILP.java.
References _amplDir, _amplFile, amplFilePath, getYearMonthCycle(), and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by setIlpFile().
setCplexLpFile()
void wrimsv2.ilp.ILP.setCplexLpFile () static private
Definition at line 566 of file ILP.java.
References _cplexLpDir, _cplexLpFile, cplexLpFileName, cplexLpFilePath, getYearMonthCycle(), and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by setIlpFile().
setCplexLpString()
void wrimsv2.ilp.ILP.setCplexLpString () static private
Definition at line 583 of file ILP.java.
References _cplexLpFile, and _cplexLpString.
Referenced by setIlpFile().
setCplxLpDir()
void wrimsv2.ilp.ILP.setCplxLpDir (String dir) static
Definition at line 1117 of file ILP.java.
References _cplexLpDir.
setDvarFile()
void wrimsv2.ilp.ILP.setDvarFile (String append) static
Definition at line 552 of file ILP.java.
References _dvarDir, _dvarFile, getYearMonthCycle(), and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.solver.CbcSolver.logCbcDebug().
setIlpFile()
void wrimsv2.ilp.ILP.setIlpFile () static
Definition at line 213 of file ILP.java.
References ILP(), setAmplFile(), setCplexLpFile(), setCplexLpString(), setLpSolveFile(), setMPModelFile(), wrimsv2.commondata.wresldata.Param.SOLVER_CBC0, wrimsv2.commondata.wresldata.Param.SOLVER_CBC1, wrimsv2.components.ControlData.solverType, and wrimsv2.components.ControlData.useCplexLpString.
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), and wrimsv2.components.ControllerDebug.runModelSolvers().
setLPSolveDir()
void wrimsv2.ilp.ILP.setLPSolveDir (String dir) static
Definition at line 1113 of file ILP.java.
References _lpSolveDir.
setLpSolveFile()
void wrimsv2.ilp.ILP.setLpSolveFile () static private
Definition at line 473 of file ILP.java.
References _lpSolveDir, _lpSolveFile, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, lpSolveFilePath, and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by setIlpFile().
setMaximumFractionDigits()
void wrimsv2.ilp.ILP.setMaximumFractionDigits () static
Definition at line 206 of file ILP.java.
References df, and maximumFractionDigits.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), initializeIlp(), and wrimsv2.components.ControllerDebug.runModelSolvers().
setMPModelFile()
void wrimsv2.ilp.ILP.setMPModelFile () static private
Definition at line 450 of file ILP.java.
References _mpModelDir, _mpModelFile, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, and mpModelFilePath.
Referenced by setIlpFile().
setObjValueFile()
void wrimsv2.ilp.ILP.setObjValueFile () static
Definition at line 510 of file ILP.java.
References _ilpDir, _objValueFile, and wrimsv2.wreslparser.elements.Tools.openFile().
setSvarFile()
void wrimsv2.ilp.ILP.setSvarFile () static
Definition at line 539 of file ILP.java.
References _svarDir, _svarFile, getYearMonthCycle(), and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), and wrimsv2.components.ControllerDebug.runModelSolvers().
setVarDir()
void wrimsv2.ilp.ILP.setVarDir () static
Definition at line 493 of file ILP.java.
References _dvarDir, _ilpDir, and _svarDir.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), initializeIlp(), and wrimsv2.components.ControllerDebug.runModelSolvers().
setVarFile()
void wrimsv2.ilp.ILP.setVarFile () static
Definition at line 523 of file ILP.java.
References _dvarDir, _dvarFile, _svarDir, _svarFile, getYearMonthCycle(), and wrimsv2.wreslparser.elements.Tools.openFile().
Referenced by wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), and wrimsv2.components.ControllerDebug.runModelSolvers().
writeAmplFile()
void wrimsv2.ilp.ILP.writeAmplFile () static private
Definition at line 377 of file ILP.java.
References _amplFile, ampl_comment_Symbol, dvar_effective, findActiveWeightMap(), findHeaderStr(), wrimsv2.ilp.AmplWriter.writeConstraint(), wrimsv2.ilp.AmplWriter.writeDvar(), and wrimsv2.ilp.AmplWriter.writeObj().
Referenced by writeIlp().
writeCplexLpFile()
void wrimsv2.ilp.ILP.writeCplexLpFile () static private
Definition at line 355 of file ILP.java.
References _cplexLpFile, cplexLp_comment_Symbol, dvar_effective, findActiveWeightMap(), findHeaderStr(), wrimsv2.ilp.CplexLpWriter.writeConstraint(), wrimsv2.ilp.CplexLpWriter.writeDvar(), and wrimsv2.ilp.CplexLpWriter.writeObj().
Referenced by writeIlp().
writeDvarValue_Clp0_Cbc0() [1/2]
void wrimsv2.ilp.ILP.writeDvarValue_Clp0_Cbc0 (Map< String, Double > varDoubleMap) static
Definition at line 409 of file ILP.java.
References _dvarFile, dvar_effective, and writeDvarValue_Clp0_Cbc0().
Referenced by wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and writeDvarValue_Clp0_Cbc0().
writeDvarValue_Clp0_Cbc0() [2/2]
void wrimsv2.ilp.ILP.writeDvarValue_Clp0_Cbc0 (PrintWriter dvarFile, Set< String > dvar_effective, Map< String, Double > varDoubleMap) static private
Definition at line 942 of file ILP.java.
References df, dvar_effective, intList, loggingVariableValueRound, loggingVariableValueRound10, and prepareDvarToWrite().
writeDvarValue_Gurobi() [1/2]
void wrimsv2.ilp.ILP.writeDvarValue_Gurobi () static
Definition at line 415 of file ILP.java.
References _dvarFile, dvar_effective, and writeDvarValue_Gurobi().
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerDebug.runModelSolvers(), and writeDvarValue_Gurobi().
writeDvarValue_Gurobi() [2/2]
void wrimsv2.ilp.ILP.writeDvarValue_Gurobi (PrintWriter dvarFile, Set< String > dvar_effective) static private
Definition at line 992 of file ILP.java.
References df, dvar_effective, prepareDvarToWrite(), and wrimsv2.solver.Gurobi.GurobiSolver.varDoubleMap.
writeDvarValue_LPSOLVE() [1/2]
void wrimsv2.ilp.ILP.writeDvarValue_LPSOLVE () static
Definition at line 403 of file ILP.java.
References _dvarFile, dvar_effective, and writeDvarValue_LPSOLVE().
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and writeDvarValue_LPSOLVE().
writeDvarValue_LPSOLVE() [2/2]
void wrimsv2.ilp.ILP.writeDvarValue_LPSOLVE (PrintWriter dvarFile, Set< String > dvar_effective) static private
Definition at line 900 of file ILP.java.
References df, dvar_effective, prepareDvarToWrite(), and wrimsv2.solver.LPSolveSolver.varDoubleMap.
writeDvarValue_OrTools() [1/2]
void wrimsv2.ilp.ILP.writeDvarValue_OrTools () static
Definition at line 421 of file ILP.java.
References _dvarFile, dvar_effective, and writeDvarValue_OrTools().
Referenced by wrimsv2.components.ControllerBatch.runModelOrTools(), and writeDvarValue_OrTools().
writeDvarValue_OrTools() [2/2]
void wrimsv2.ilp.ILP.writeDvarValue_OrTools (PrintWriter dvarFile, Set< String > dvar_effective) static private
Definition at line 1035 of file ILP.java.
References df, dvar_effective, wrimsv2.components.ControlData.otsolver, prepareDvarToWrite(), and wrimsv2.solver.ortools.OrToolsSolver.solution.
writeDvarValue_XA() [1/2]
void wrimsv2.ilp.ILP.writeDvarValue_XA () static
Definition at line 397 of file ILP.java.
References _dvarFile, dvar_effective, and writeDvarValue_XA().
Referenced by wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and writeDvarValue_XA().
writeDvarValue_XA() [2/2]
void wrimsv2.ilp.ILP.writeDvarValue_XA (PrintWriter dvarFile, Set< String > dvar_effective) static private
Definition at line 855 of file ILP.java.
References df, dvar_effective, intList, loggingVariableValueRound, loggingVariableValueRound10, prepareDvarToWrite(), and wrimsv2.components.ControlData.xasolver.
writeIlp()
void wrimsv2.ilp.ILP.writeIlp () static
Definition at line 228 of file ILP.java.
References ILP(), findDvarEffective(), writeAmplFile(), writeCplexLpFile(), and writeLpSolveFile().
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), and wrimsv2.components.ControllerDebug.runModelSolvers().
writeLpSolveFile()
void wrimsv2.ilp.ILP.writeLpSolveFile () static private
Definition at line 334 of file ILP.java.
References _lpSolveFile, dvar_effective, findActiveWeightMap(), findHeaderStr(), lpSolve_comment_Symbol, wrimsv2.ilp.LpSolveWriter.writeConstraint(), wrimsv2.ilp.LpSolveWriter.writeDvar(), and wrimsv2.ilp.LpSolveWriter.writeObj().
Referenced by writeIlp().
writeMPModelFile()
void wrimsv2.ilp.ILP.writeMPModelFile (MPModel m) static
Definition at line 324 of file ILP.java.
References _mpModelFile.
Referenced by wrimsv2.components.ControllerBatch.runModelOrTools().
writeNote()
void wrimsv2.ilp.ILP.writeNote (String msg, PrintWriter outFile) static
Definition at line 806 of file ILP.java.
writeNoteLn() [1/5]
void wrimsv2.ilp.ILP.writeNoteLn (String msg) static
Definition at line 780 of file ILP.java.
References writeNoteLn().
writeNoteLn() [2/5]
void wrimsv2.ilp.ILP.writeNoteLn (String msg, boolean printToScreen, boolean isErr) static
Definition at line 771 of file ILP.java.
References _noteFile, and writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), createNoteFile(), wrimsv2.solver.CbcSolver.iis(), wrimsv2.solver.CbcSolver.init(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logCbcWatchList(), wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.solver.CbcSolver.note_msg(), wrimsv2.solver.CbcSolver.reloadAndWriteLp(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), wrimsv2.components.TimeUsage.showTimeUsage(), wrimsv2.solver.Cbc0Solver.solve(), wrimsv2.solver.CbcSolver.solve(), wrimsv2.solver.CbcSolver.solve_jCbc2021(), wrimsv2.solver.CbcSolver.solve_jCbc2021a(), wrimsv2.solver.CbcSolver.violationCheck(), writeNoteLn(), writeNoteLn(), writeNoteLn(), and writeObjValue_Clp0_Cbc0().
writeNoteLn() [3/5]
void wrimsv2.ilp.ILP.writeNoteLn (String msg, PrintWriter outFile) static
Definition at line 800 of file ILP.java.
writeNoteLn() [4/5]
void wrimsv2.ilp.ILP.writeNoteLn (String msg, String noteStr) static
Definition at line 785 of file ILP.java.
References _noteFile, and writeNoteLn().
writeNoteLn() [5/5]
void wrimsv2.ilp.ILP.writeNoteLn (String msg, String noteStr, PrintWriter outFile) static
Definition at line 790 of file ILP.java.
writeObjValue()
void wrimsv2.ilp.ILP.writeObjValue (String objValueStr, PrintWriter outFile, String commentSym) static private
Definition at line 812 of file ILP.java.
References wrimsv2.components.Error.getTotalError().
Referenced by writeObjValue_Clp0_Cbc0(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
writeObjValue_Clp0_Cbc0()
void wrimsv2.ilp.ILP.writeObjValue_Clp0_Cbc0 () static
Definition at line 284 of file ILP.java.
References _cplexLpFile, _noteFile, _objValueFile, wrimsv2.components.ControlData.clp_cbc_note, wrimsv2.components.ControlData.clp_cbc_objective, cplexLp_comment_Symbol, getYearMonthCycle(), writeNoteLn(), writeObjValue(), and writeObjValueLog().
Referenced by wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
writeObjValue_Gurobi()
void wrimsv2.ilp.ILP.writeObjValue_Gurobi () static
Definition at line 298 of file ILP.java.
References ILP(), _amplFile, _cplexLpFile, _lpSolveFile, _objValueFile, ampl_comment_Symbol, cplexLp_comment_Symbol, getYearMonthCycle(), wrimsv2.components.ControlData.gurobi_objective, lpSolve_comment_Symbol, writeObjValue(), and writeObjValueLog().
Referenced by wrimsv2.components.Controller.runModelGurobi(), and wrimsv2.components.ControllerBatch.runModelGurobi().
writeObjValue_LPSOLVE()
void wrimsv2.ilp.ILP.writeObjValue_LPSOLVE () static
Definition at line 271 of file ILP.java.
References ILP(), _amplFile, _cplexLpFile, _lpSolveFile, _objValueFile, ampl_comment_Symbol, cplexLp_comment_Symbol, getYearMonthCycle(), lpSolve_comment_Symbol, wrimsv2.components.ControlData.lpsolve_objective, writeObjValue(), and writeObjValueLog().
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
writeObjValue_OrTools()
void wrimsv2.ilp.ILP.writeObjValue_OrTools () static
Definition at line 311 of file ILP.java.
References ILP(), _amplFile, _cplexLpFile, _lpSolveFile, _objValueFile, ampl_comment_Symbol, cplexLp_comment_Symbol, getYearMonthCycle(), lpSolve_comment_Symbol, wrimsv2.components.ControlData.otsolver, wrimsv2.solver.ortools.OrToolsSolver.solver, writeObjValue(), and writeObjValueLog().
Referenced by wrimsv2.components.ControllerBatch.runModelOrTools().
writeObjValue_XA()
void wrimsv2.ilp.ILP.writeObjValue_XA () static
Definition at line 258 of file ILP.java.
References ILP(), _amplFile, _cplexLpFile, _lpSolveFile, _objValueFile, ampl_comment_Symbol, cplexLp_comment_Symbol, getYearMonthCycle(), lpSolve_comment_Symbol, writeObjValue(), writeObjValueLog(), and wrimsv2.components.ControlData.xasolver.
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
writeObjValueLog()
void wrimsv2.ilp.ILP.writeObjValueLog (String msg, String objValueStr, PrintWriter outFile) static
Definition at line 761 of file ILP.java.
References wrimsv2.components.Error.getTotalError().
Referenced by wrimsv2.components.ControllerBatch.runModelGurobiTest(), writeObjValue_Clp0_Cbc0(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
writeSvarValue() [1/2]
void wrimsv2.ilp.ILP.writeSvarValue () static
Definition at line 427 of file ILP.java.
References _svarFile, and writeSvarValue().
Referenced by wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), and writeSvarValue().
writeSvarValue() [2/2]
void wrimsv2.ilp.ILP.writeSvarValue (PrintWriter svarFile) static private
Definition at line 1078 of file ILP.java.
References wrimsv2.components.ControlData.currSvMap, df, loggingVariableValueRound, and loggingVariableValueRound10.
Member Data Documentation
_amplDir
String wrimsv2.ilp.ILP._amplDir static private
Definition at line 51 of file ILP.java.
Referenced by initializeIlp(), and setAmplFile().
_amplFile
PrintWriter wrimsv2.ilp.ILP._amplFile static private
Definition at line 61 of file ILP.java.
Referenced by closeIlpFile(), setAmplFile(), writeAmplFile(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
_cplexLpDir
String wrimsv2.ilp.ILP._cplexLpDir static private
Definition at line 50 of file ILP.java.
Referenced by initializeIlp(), reOpenCplexLpFile(), saveCplexLpStringToFile(), setCplexLpFile(), and setCplxLpDir().
_cplexLpFile
PrintWriter wrimsv2.ilp.ILP._cplexLpFile static private
Definition at line 58 of file ILP.java.
Referenced by closeCplexLpFile(), closeIlpFile(), reOpenCplexLpFile(), saveCplexLpStringToFile(), setCplexLpFile(), setCplexLpString(), writeCplexLpFile(), writeObjValue_Clp0_Cbc0(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
_cplexLpString
StringWriter wrimsv2.ilp.ILP._cplexLpString static private
Definition at line 59 of file ILP.java.
Referenced by saveCplexLpStringToFile(), and setCplexLpString().
_dvarDir
File wrimsv2.ilp.ILP._dvarDir static private
Definition at line 96 of file ILP.java.
Referenced by setDvarFile(), setVarDir(), and setVarFile().
_dvarFile
PrintWriter wrimsv2.ilp.ILP._dvarFile static private
Definition at line 63 of file ILP.java.
Referenced by closeIlpFile(), setDvarFile(), setVarFile(), writeDvarValue_Clp0_Cbc0(), writeDvarValue_Gurobi(), writeDvarValue_LPSOLVE(), writeDvarValue_OrTools(), and writeDvarValue_XA().
_ilpDir
File wrimsv2.ilp.ILP._ilpDir static private
Definition at line 94 of file ILP.java.
Referenced by createNoteFile(), getIlpDir(), initializeIlp(), setObjValueFile(), and setVarDir().
_ilpRootDir
File wrimsv2.ilp.ILP._ilpRootDir static private
Definition at line 93 of file ILP.java.
Referenced by getIlpDir(), and initializeIlp().
_lpSolveDir
String wrimsv2.ilp.ILP._lpSolveDir static private
Definition at line 49 of file ILP.java.
Referenced by initializeIlp(), setLPSolveDir(), and setLpSolveFile().
_lpSolveFile
PrintWriter wrimsv2.ilp.ILP._lpSolveFile static private
Definition at line 57 of file ILP.java.
Referenced by closeIlpFile(), setLpSolveFile(), writeLpSolveFile(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
_mpModelDir
String wrimsv2.ilp.ILP._mpModelDir static private
Definition at line 48 of file ILP.java.
Referenced by initializeIlp(), and setMPModelFile().
_mpModelFile
ObjectOutputStream wrimsv2.ilp.ILP._mpModelFile static private
Definition at line 56 of file ILP.java.
Referenced by closeIlpFile(), setMPModelFile(), and writeMPModelFile().
_noteFile
PrintWriter wrimsv2.ilp.ILP._noteFile static
Definition at line 65 of file ILP.java.
Referenced by createNoteFile(), writeNoteLn(), writeNoteLn(), and writeObjValue_Clp0_Cbc0().
_noteFile_cbc_int
PrintWriter wrimsv2.ilp.ILP._noteFile_cbc_int static
Definition at line 70 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
_noteFile_cbc_int_log
PrintWriter wrimsv2.ilp.ILP._noteFile_cbc_int_log static
Definition at line 71 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logIntCheck(), and wrimsv2.components.ControllerSG.runModelCbc().
_noteFile_cbc_obj
PrintWriter wrimsv2.ilp.ILP._noteFile_cbc_obj static
Definition at line 68 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.newProblem(), and wrimsv2.components.ControllerSG.runModelCbc().
_noteFile_cbc_time
PrintWriter wrimsv2.ilp.ILP._noteFile_cbc_time static
Definition at line 69 of file ILP.java.
Referenced by createNoteFile(), and wrimsv2.solver.CbcSolver.newProblem().
_noteFile_memory
PrintWriter wrimsv2.ilp.ILP._noteFile_memory static
Definition at line 72 of file ILP.java.
Referenced by createNoteFile().
_noteFile_timeusage
PrintWriter wrimsv2.ilp.ILP._noteFile_timeusage static
Definition at line 73 of file ILP.java.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), createNoteFile(), and wrimsv2.components.TimeUsage.showTimeUsage().
_noteFile_xa_int
PrintWriter wrimsv2.ilp.ILP._noteFile_xa_int static
Definition at line 67 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
_noteFile_xa_obj
PrintWriter wrimsv2.ilp.ILP._noteFile_xa_obj static
Definition at line 66 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
_objValueFile
PrintWriter wrimsv2.ilp.ILP._objValueFile static private
Definition at line 64 of file ILP.java.
Referenced by initializeIlp(), setObjValueFile(), writeObjValue_Clp0_Cbc0(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
_svarDir
File wrimsv2.ilp.ILP._svarDir static private
Definition at line 95 of file ILP.java.
Referenced by setSvarFile(), setVarDir(), and setVarFile().
_svarFile
PrintWriter wrimsv2.ilp.ILP._svarFile static private
Definition at line 62 of file ILP.java.
Referenced by closeIlpFile(), setSvarFile(), setVarFile(), and writeSvarValue().
_watchFile_cbc
PrintWriter wrimsv2.ilp.ILP._watchFile_cbc static
Definition at line 75 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logCbcWatchList(), and wrimsv2.components.ControllerSG.runModelCbc().
_watchFile_xa
PrintWriter wrimsv2.ilp.ILP._watchFile_xa static
Definition at line 74 of file ILP.java.
Referenced by createNoteFile(), wrimsv2.solver.CbcSolver.logCbcDebug(), and wrimsv2.components.ControllerSG.runModelCbc().
ampl_comment_Symbol
final String wrimsv2.ilp.ILP.ampl_comment_Symbol = "#" static private
Definition at line 78 of file ILP.java.
Referenced by writeAmplFile(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
amplFilePath
String wrimsv2.ilp.ILP.amplFilePath static
Definition at line 55 of file ILP.java.
Referenced by setAmplFile().
cplexLp_comment_Symbol
final String wrimsv2.ilp.ILP.cplexLp_comment_Symbol = "\\" static private
Definition at line 79 of file ILP.java.
Referenced by writeCplexLpFile(), writeObjValue_Clp0_Cbc0(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
cplexLpFileName
String wrimsv2.ilp.ILP.cplexLpFileName static private
Definition at line 60 of file ILP.java.
Referenced by reOpenCplexLpFile(), saveCplexLpStringToFile(), and setCplexLpFile().
cplexLpFilePath
String wrimsv2.ilp.ILP.cplexLpFilePath static
Definition at line 54 of file ILP.java.
Referenced by wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), saveCplexLpStringToFile(), and setCplexLpFile().
df
DecimalFormat wrimsv2.ilp.ILP.df static private
Definition at line 80 of file ILP.java.
Referenced by setMaximumFractionDigits(), writeDvarValue_Clp0_Cbc0(), writeDvarValue_Gurobi(), writeDvarValue_LPSOLVE(), writeDvarValue_OrTools(), writeDvarValue_XA(), and writeSvarValue().
dvar_effective
Set<String> wrimsv2.ilp.ILP.dvar_effective static private
Definition at line 76 of file ILP.java.
Referenced by findDvarEffective(), prepareDvarToWrite(), writeAmplFile(), writeCplexLpFile(), writeDvarValue_Clp0_Cbc0(), writeDvarValue_Clp0_Cbc0(), writeDvarValue_Gurobi(), writeDvarValue_Gurobi(), writeDvarValue_LPSOLVE(), writeDvarValue_LPSOLVE(), writeDvarValue_OrTools(), writeDvarValue_OrTools(), writeDvarValue_XA(), writeDvarValue_XA(), and writeLpSolveFile().
intList
ArrayList<String> wrimsv2.ilp.ILP.intList = null static
Definition at line 98 of file ILP.java.
Referenced by wrimsv2.ilp.CplexLpWriter.writeDvar(), writeDvarValue_Clp0_Cbc0(), and writeDvarValue_XA().
logging
boolean wrimsv2.ilp.ILP.logging = false static
Definition at line 86 of file ILP.java.
Referenced by wrimsv2.external.Functioninitgwsystem.execute(), wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.components.Controller.runModel(), wrimsv2.components.ControllerBatch.runModel(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.launch.LaunchConfiguration.setConfig(), and wrimsv2.components.DebugInterface.setSolverOptions().
loggingAllCycles
boolean wrimsv2.ilp.ILP.loggingAllCycles = true static
Definition at line 85 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.launch.LaunchConfiguration.setConfig(), and wrimsv2.components.DebugInterface.setSolverOptions().
loggingAmpl
boolean wrimsv2.ilp.ILP.loggingAmpl = false static
Definition at line 87 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig().
loggingCplexLp
boolean wrimsv2.ilp.ILP.loggingCplexLp = false static
Definition at line 88 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.launch.LaunchConfiguration.setConfig(), and wrimsv2.components.DebugInterface.setSolverOptions().
loggingLpSolve
boolean wrimsv2.ilp.ILP.loggingLpSolve = false static
Definition at line 89 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and wrimsv2.components.DebugInterface.setSolverOptions().
loggingMPModel
boolean wrimsv2.ilp.ILP.loggingMPModel = false static
Definition at line 90 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and wrimsv2.components.ControllerBatch.runModelOrTools().
loggingUsageMemeory
boolean wrimsv2.ilp.ILP.loggingUsageMemeory = false static
Definition at line 91 of file ILP.java.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.components.ControllerDebug.run(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.ControllerBatch.runModelXA().
loggingVariableValue
boolean wrimsv2.ilp.ILP.loggingVariableValue = false static
Definition at line 82 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.DebugInterface.setSolverOptions().
loggingVariableValueRound
boolean wrimsv2.ilp.ILP.loggingVariableValueRound = false static
Definition at line 83 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), writeDvarValue_Clp0_Cbc0(), writeDvarValue_XA(), and writeSvarValue().
loggingVariableValueRound10
boolean wrimsv2.ilp.ILP.loggingVariableValueRound10 = false static
Definition at line 84 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), writeDvarValue_Clp0_Cbc0(), writeDvarValue_XA(), and writeSvarValue().
lpSolve_comment_Symbol
final String wrimsv2.ilp.ILP.lpSolve_comment_Symbol = "//" static private
Definition at line 77 of file ILP.java.
Referenced by writeLpSolveFile(), writeObjValue_Gurobi(), writeObjValue_LPSOLVE(), writeObjValue_OrTools(), and writeObjValue_XA().
lpSolveFilePath
String wrimsv2.ilp.ILP.lpSolveFilePath static
Definition at line 53 of file ILP.java.
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerDebug.runModelSolvers(), and setLpSolveFile().
maximumFractionDigits
int wrimsv2.ilp.ILP.maximumFractionDigits = 16 static
Definition at line 81 of file ILP.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and setMaximumFractionDigits().
mpModelFilePath
String wrimsv2.ilp.ILP.mpModelFilePath static
Definition at line 52 of file ILP.java.
Referenced by setMPModelFile().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/ilp/ILP.java