Wrims-engine: wrimsv2.wreslparser.elements.Sort Class Reference
wrimsv2.wreslparser.elements.Sort Class Reference
Public Member Functions
Sort (Map< String, SimulationDataSet > file_data_map)
Sort (Map< String, Svar > in_svMap, Map< String, Alias > in_asMap, Set< String >dvSet, Set< String >tsSet, Set< String >exSet)
Set< String > sort (ArrayList< String > toBeSortedList)
Private Member Functions
Set< String > getGroup1 ()
boolean getNextGroup (Set< String > out)
Private Attributes
Set< String > outSet = new HashSet<String>()
Set< String > previousSet = new HashSet<String>()
Map< String, Set< String > > varDependentMap
Map< String, String > varTypeMap = new HashMap<String, String>()
Detailed Description
Definition at line 14 of file Sort.java.
Constructor & Destructor Documentation
Sort() [1/2]
wrimsv2.wreslparser.elements.Sort.Sort (Map< String, SimulationDataSet > file_data_map)
Definition at line 34 of file Sort.java.
References varDependentMap, and varTypeMap.
Sort() [2/2]
wrimsv2.wreslparser.elements.Sort.Sort (Map< String, Svar > in_svMap, Map< String, Alias > in_asMap, Set< String > dvSet, Set< String > tsSet, Set< String > exSet)
Definition at line 47 of file Sort.java.
References wrimsv2.commondata.wresldata.Param.reservedSet, varDependentMap, and varTypeMap.
Member Function Documentation
getGroup1()
Set< String > wrimsv2.wreslparser.elements.Sort.getGroup1 () private
Definition at line 113 of file Sort.java.
References previousSet, and varDependentMap.
Referenced by sort().
getNextGroup()
boolean wrimsv2.wreslparser.elements.Sort.getNextGroup (Set< String > out) private
Definition at line 135 of file Sort.java.
References previousSet, and varDependentMap.
Referenced by sort().
sort()
Set< String > wrimsv2.wreslparser.elements.Sort.sort (ArrayList< String > toBeSortedList)
Definition at line 78 of file Sort.java.
References wrimsv2.commondata.wresldata.Param.debug, getGroup1(), getNextGroup(), outSet, varDependentMap, varTypeMap, and wrimsv2.wreslparser.elements.LogUtils.warningMsg().
Referenced by wrimsv2.wreslparser.elements.StudyParser.getOrderedList(), and wrimsv2.wreslparser.elements.StudyParser.sortDependency().
Member Data Documentation
outSet
Set<String> wrimsv2.wreslparser.elements.Sort.outSet = new HashSet<String>() private
Definition at line 21 of file Sort.java.
Referenced by sort().
previousSet
Set<String> wrimsv2.wreslparser.elements.Sort.previousSet = new HashSet<String>() private
Definition at line 18 of file Sort.java.
Referenced by getGroup1(), and getNextGroup().
varDependentMap
Map<String, Set<String> > wrimsv2.wreslparser.elements.Sort.varDependentMap private
Definition at line 16 of file Sort.java.
Referenced by Sort(), Sort(), getGroup1(), getNextGroup(), and sort().
varTypeMap
Map<String, String> wrimsv2.wreslparser.elements.Sort.varTypeMap = new HashMap<String, String>() private
Definition at line 17 of file Sort.java.
Referenced by Sort(), Sort(), and sort().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/Sort.java