Wrims-engine: wrimsv2.sql.MySQLRWriter Class Reference
wrimsv2.sql.MySQLRWriter Class Reference
Public Member Functions
MySQLRWriter ()
void close ()
void connectToDataBase ()
void createCSV ()
void createIndex ()
void createScenarioCSV ()
void createTable ()
void deleteOldData ()
void process ()
void setScenarioIndex ()
void writeData ()
Private Attributes
Connection conn = null
File csvFile
String csvMySQLPath
String csvPath
String database
String JDBC_DRIVER = "com.mysql.jdbc.Driver"
int scenarioIndex
String scenarioName =FilePaths.sqlScenarioName
String scenarioTableName ="Scenario"
Statement stmt = null
String tableName = ControlData.sqlGroup
String URL
Detailed Description
Definition at line 29 of file MySQLRWriter.java.
Constructor & Destructor Documentation
MySQLRWriter()
wrimsv2.sql.MySQLRWriter.MySQLRWriter ()
Definition at line 48 of file MySQLRWriter.java.
References connectToDataBase().
Member Function Documentation
close()
void wrimsv2.sql.MySQLRWriter.close ()
Definition at line 239 of file MySQLRWriter.java.
References conn, and stmt.
Referenced by process().
connectToDataBase()
void wrimsv2.sql.MySQLRWriter.connectToDataBase ()
Definition at line 66 of file MySQLRWriter.java.
References conn, database, wrimsv2.components.ControlData.databaseURL, JDBC_DRIVER, wrimsv2.components.ControlData.PASS, stmt, URL, and wrimsv2.components.ControlData.USER.
Referenced by MySQLRWriter().
createCSV()
void wrimsv2.sql.MySQLRWriter.createCSV ()
Definition at line 197 of file MySQLRWriter.java.
References csvMySQLPath, csvPath, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.evaluator.CsvOperation.ouputCSV(), scenarioIndex, and URL.
Referenced by process().
createIndex()
void wrimsv2.sql.MySQLRWriter.createIndex ()
Definition at line 220 of file MySQLRWriter.java.
References conn, database, stmt, and tableName.
Referenced by process().
createScenarioCSV()
void wrimsv2.sql.MySQLRWriter.createScenarioCSV ()
Definition at line 135 of file MySQLRWriter.java.
References wrimsv2.components.FilePaths.dvarDssDirectory, scenarioTableName, and stmt.
Referenced by process().
createTable()
void wrimsv2.sql.MySQLRWriter.createTable ()
Definition at line 163 of file MySQLRWriter.java.
References conn, database, stmt, and tableName.
Referenced by process().
deleteOldData()
void wrimsv2.sql.MySQLRWriter.deleteOldData ()
Definition at line 185 of file MySQLRWriter.java.
References conn, scenarioIndex, stmt, and tableName.
Referenced by process().
process()
void wrimsv2.sql.MySQLRWriter.process ()
Definition at line 52 of file MySQLRWriter.java.
References close(), createCSV(), createIndex(), createScenarioCSV(), createTable(), deleteOldData(), scenarioTableName, setScenarioIndex(), tableName, and writeData().
Referenced by wrimsv2.sql.DssToSQLDatabase.convertData().
setScenarioIndex()
void wrimsv2.sql.MySQLRWriter.setScenarioIndex ()
Definition at line 98 of file MySQLRWriter.java.
References conn, wrimsv2.components.ControlData.partA, scenarioIndex, scenarioName, scenarioTableName, stmt, wrimsv2.components.ControlData.svDvPartF, and tableName.
Referenced by process().
writeData()
void wrimsv2.sql.MySQLRWriter.writeData ()
Definition at line 208 of file MySQLRWriter.java.
References conn, csvMySQLPath, stmt, and tableName.
Referenced by process().
Member Data Documentation
conn
Connection wrimsv2.sql.MySQLRWriter.conn = null private
Definition at line 38 of file MySQLRWriter.java.
Referenced by close(), connectToDataBase(), createIndex(), createTable(), deleteOldData(), setScenarioIndex(), and writeData().
csvFile
File wrimsv2.sql.MySQLRWriter.csvFile private
Definition at line 46 of file MySQLRWriter.java.
csvMySQLPath
String wrimsv2.sql.MySQLRWriter.csvMySQLPath private
Definition at line 45 of file MySQLRWriter.java.
Referenced by createCSV(), and writeData().
csvPath
String wrimsv2.sql.MySQLRWriter.csvPath private
Definition at line 44 of file MySQLRWriter.java.
Referenced by createCSV().
database
String wrimsv2.sql.MySQLRWriter.database private
Definition at line 36 of file MySQLRWriter.java.
Referenced by connectToDataBase(), createIndex(), and createTable().
JDBC_DRIVER
String wrimsv2.sql.MySQLRWriter.JDBC_DRIVER = "com.mysql.jdbc.Driver" private
Definition at line 31 of file MySQLRWriter.java.
Referenced by connectToDataBase().
scenarioIndex
int wrimsv2.sql.MySQLRWriter.scenarioIndex private
Definition at line 42 of file MySQLRWriter.java.
Referenced by createCSV(), deleteOldData(), and setScenarioIndex().
scenarioName
String wrimsv2.sql.MySQLRWriter.scenarioName =FilePaths.sqlScenarioName private
Definition at line 41 of file MySQLRWriter.java.
Referenced by setScenarioIndex().
scenarioTableName
String wrimsv2.sql.MySQLRWriter.scenarioTableName ="Scenario" private
Definition at line 33 of file MySQLRWriter.java.
Referenced by createScenarioCSV(), process(), and setScenarioIndex().
stmt
Statement wrimsv2.sql.MySQLRWriter.stmt = null private
Definition at line 39 of file MySQLRWriter.java.
Referenced by close(), connectToDataBase(), createIndex(), createScenarioCSV(), createTable(), deleteOldData(), setScenarioIndex(), and writeData().
tableName
String wrimsv2.sql.MySQLRWriter.tableName = ControlData.sqlGroup private
Definition at line 32 of file MySQLRWriter.java.
Referenced by createIndex(), createTable(), deleteOldData(), process(), setScenarioIndex(), and writeData().
URL
String wrimsv2.sql.MySQLRWriter.URL private
Definition at line 35 of file MySQLRWriter.java.
Referenced by connectToDataBase(), and createCSV().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/sql/MySQLRWriter.java