Wrims-engine: wrimsv2.evaluator.LoopIndex Class Reference
wrimsv2.evaluator.LoopIndex Class Reference
Public Member Functions
LoopIndex (String name, int value, boolean indexStart, int start, int end, int step)
boolean getIndexStart ()
String getName ()
int getValue ()
void setIndexStart (boolean indexStart)
void setName (String name)
void setValue (int value)
Public Attributes
int end
int start
int step
Private Attributes
boolean indexStart
String name
int value
Detailed Description
Definition at line 3 of file LoopIndex.java.
Constructor & Destructor Documentation
LoopIndex()
wrimsv2.evaluator.LoopIndex.LoopIndex (String name, int value, boolean indexStart, int start, int end, int step)
Definition at line 11 of file LoopIndex.java.
References end, indexStart, name, start, step, and value.
Member Function Documentation
getIndexStart()
boolean wrimsv2.evaluator.LoopIndex.getIndexStart ()
Definition at line 36 of file LoopIndex.java.
References indexStart.
Referenced by wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.Evaluation.term_IDENT(), and wrimsv2.evaluator.ValueEvaluation.term_IDENT().
getName()
String wrimsv2.evaluator.LoopIndex.getName ()
Definition at line 28 of file LoopIndex.java.
References name.
Referenced by wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.Evaluation.tafcfs_term(), wrimsv2.evaluator.Evaluation.term_IDENT(), and wrimsv2.evaluator.ValueEvaluation.term_IDENT().
getValue()
int wrimsv2.evaluator.LoopIndex.getValue ()
Definition at line 32 of file LoopIndex.java.
References value.
Referenced by wrimsv2.evaluator.Evaluation.getTimeSeries(), wrimsv2.evaluator.Evaluation.tafcfs_term(), wrimsv2.evaluator.Evaluation.term_IDENT(), and wrimsv2.evaluator.ValueEvaluation.term_IDENT().
setIndexStart()
void wrimsv2.evaluator.LoopIndex.setIndexStart (boolean indexStart)
Definition at line 40 of file LoopIndex.java.
References indexStart.
Referenced by wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.sumExpression(), and wrimsv2.evaluator.ValueEvaluation.sumExpression().
setName()
void wrimsv2.evaluator.LoopIndex.setName (String name)
Definition at line 20 of file LoopIndex.java.
References name.
setValue()
void wrimsv2.evaluator.LoopIndex.setValue (int value)
Definition at line 24 of file LoopIndex.java.
References value.
Referenced by wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.sumExpression(), and wrimsv2.evaluator.ValueEvaluation.sumExpression().
Member Data Documentation
end
int wrimsv2.evaluator.LoopIndex.end
Definition at line 8 of file LoopIndex.java.
Referenced by LoopIndex(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.sumExpression(), and wrimsv2.evaluator.ValueEvaluation.sumExpression().
indexStart
boolean wrimsv2.evaluator.LoopIndex.indexStart private
Definition at line 6 of file LoopIndex.java.
Referenced by LoopIndex(), getIndexStart(), and setIndexStart().
name
String wrimsv2.evaluator.LoopIndex.name private
Definition at line 4 of file LoopIndex.java.
Referenced by LoopIndex(), getName(), and setName().
start
int wrimsv2.evaluator.LoopIndex.start
Definition at line 7 of file LoopIndex.java.
Referenced by LoopIndex(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.sumExpression(), and wrimsv2.evaluator.ValueEvaluation.sumExpression().
step
int wrimsv2.evaluator.LoopIndex.step
Definition at line 9 of file LoopIndex.java.
Referenced by LoopIndex(), wrimsv2.evaluator.Evaluation.initSumExpression(), wrimsv2.evaluator.ValueEvaluation.initSumExpression(), wrimsv2.evaluator.Evaluation.sumExpression(), and wrimsv2.evaluator.ValueEvaluation.sumExpression().
value
int wrimsv2.evaluator.LoopIndex.value private
Definition at line 5 of file LoopIndex.java.
Referenced by LoopIndex(), getValue(), and setValue().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/LoopIndex.java