Wrims-engine: wrimsv2.wreslparser.elements.WriteCSV Class Reference
wrimsv2.wreslparser.elements.WriteCSV Class Reference
Static Public Member Functions
static void alias (Map< String, Alias > asMap, ArrayList< String > list, PrintWriter out)
static void alias_unknown (Map< String, Alias > asMap, Map< String, Dvar > dvMap, ArrayList< String > list, PrintWriter out)
static void dataset (ModelDataSet ds, String outFolder) throws IOException
static void dvar (Map< String, Dvar > dMap, ArrayList< String > list, PrintWriter out)
static void external (Map< String, External > exMap, ArrayList< String > list, PrintWriter out)
static void goal (Map< String, Goal > gMap, ArrayList< String > list, PrintWriter out)
static void incFile (ArrayList< String > list, PrintWriter out)
static void mapStringListMerged (Object obj, PrintWriter out)
static void output (Map< String, ModelDataSet > modelDataMap, String outParent)
static void sequence (ArrayList< String > modelList, ArrayList< String > modelConditionList, PrintWriter out)
static void sequence (Map< Integer, Sequence > seqMap, ArrayList< Integer > list, PrintWriter out)
static void study (StudyConfig sc, Map< String, ModelDataSet > modelDataMap, String outParent)
static void study (StudyDataSet sd, String outParent)
static void svar (Map< String, Svar > sMap, ArrayList< String > list, PrintWriter out)
static void timeseries_model (Map< String, Timeseries > sTsMap, ArrayList< String > list, PrintWriter out)
static void timeseries_wholeStudy (Map< String, Timeseries > tsMap, PrintWriter out)
static void timeseriesTimeStep (StudyDataSet sd, PrintWriter out)
static void weight (Map< String, WeightElement > wtMap, ArrayList< String > list, PrintWriter out)
Static Public Attributes
static String alias_header ="NAME,TIME_ARRAY_SIZE,TYPE,UNITS,EXPRESSION,DEPENDANT,FROM_WRESL_FILE,NEED_VAR_FROM_CYCLE,USED_IN_LATER_CYCLE"
static String dvar_header ="NAME,TIME_ARRAY_SIZE,CONDITION,LOWER_BOUND,UPPER_BOUND,INTEGER,UNITS,TYPE,FROM_WRESL_FILE,USED_IN_LATER_CYCLE"
static String external_header ="FUNCTION,FILE,FROM_WRESL_FILE"
static String goal_header = "NAME,TIME_ARRAY_SIZE,CASE,ORDER,CONDITION,EXPRESSION,DEPENDANT,FROM_WRESL_FILE,NEED_VAR_FROM_CYCLE,"
static String sequence_header ="CYCLE,CONDITION,TIMESTEP"
static String svar_header ="NAME,TIME_ARRAY_SIZE,CASE,ORDER,CONDITION,EXPRESSION,DEPENDANT,FROM_WRESL_FILE,NEED_VAR_FROM_CYCLE,USED_IN_LATER_CYCLE"
static String timeseries_header ="NAME,B_PART,TYPE,UNITS,CONVERT_TO_UNITS,FROM_WRESL_FILE"
static String timeseries_timestep_header ="NAME,B_PART,TIMESTEP"
static String weight_header ="DVAR,TIME_ARRAY_SIZE,CONDITION,WEIGHT"
Static Private Attributes
static ModelDataSet currentModelDataSet
Detailed Description
Definition at line 26 of file WriteCSV.java.
Member Function Documentation
alias()
void wrimsv2.wreslparser.elements.WriteCSV.alias (Map< String, Alias > asMap, ArrayList< String > list, PrintWriter out) static
Definition at line 536 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator, currentModelDataSet, wrimsv2.commondata.wresldata.Alias.dependants, wrimsv2.commondata.wresldata.Alias.expression, wrimsv2.commondata.wresldata.Alias.fromWresl, wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Alias.neededVarInCycleSet, wrimsv2.commondata.wresldata.Alias.timeArraySize, and wrimsv2.commondata.wresldata.Alias.units.
Referenced by dataset().
alias_unknown()
void wrimsv2.wreslparser.elements.WriteCSV.alias_unknown (Map< String, Alias > asMap, Map< String, Dvar > dvMap, ArrayList< String > list, PrintWriter out) static
Definition at line 483 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.Alias.dependants, wrimsv2.commondata.wresldata.Dvar.dependants, wrimsv2.commondata.wresldata.Alias.expression, wrimsv2.commondata.wresldata.Dvar.expression, wrimsv2.commondata.wresldata.Alias.fromWresl, wrimsv2.commondata.wresldata.Dvar.fromWresl, wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Alias.timeArraySize, wrimsv2.commondata.wresldata.Alias.units, and wrimsv2.commondata.wresldata.Dvar.units.
Referenced by dataset().
dataset()
void wrimsv2.wreslparser.elements.WriteCSV.dataset (ModelDataSet ds, String outFolder) throws IOException static
Definition at line 112 of file WriteCSV.java.
References alias(), alias_header, alias_unknown(), currentModelDataSet, dvar(), dvar_header, external(), external_header, goal(), goal_header, incFile(), wrimsv2.wreslparser.elements.Tools.openFile(), svar(), svar_header, timeseries_header, timeseries_model(), weight(), and weight_header.
Referenced by output().
dvar()
void wrimsv2.wreslparser.elements.WriteCSV.dvar (Map< String, Dvar > dMap, ArrayList< String > list, PrintWriter out) static
Definition at line 450 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Dvar.condition, wrimsv2.commondata.wresldata.Param.csv_seperator, currentModelDataSet, wrimsv2.commondata.wresldata.Dvar.fromWresl, wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Dvar.lowerBound, wrimsv2.commondata.wresldata.Dvar.timeArraySize, wrimsv2.commondata.wresldata.Dvar.units, and wrimsv2.commondata.wresldata.Dvar.upperBound.
Referenced by dataset().
external()
void wrimsv2.wreslparser.elements.WriteCSV.external (Map< String, External > exMap, ArrayList< String > list, PrintWriter out) static
Definition at line 401 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.External.fromWresl, and wrimsv2.commondata.wresldata.External.type.
Referenced by dataset().
goal()
void wrimsv2.wreslparser.elements.WriteCSV.goal (Map< String, Goal > gMap, ArrayList< String > list, PrintWriter out) static
Definition at line 588 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Goal.caseCondition, wrimsv2.commondata.wresldata.Goal.caseExpression, wrimsv2.commondata.wresldata.Goal.caseName, wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.Goal.expressionDependants, wrimsv2.commondata.wresldata.Goal.fromWresl, wrimsv2.commondata.wresldata.Goal.neededVarInCycleSet, and wrimsv2.commondata.wresldata.Goal.timeArraySize.
Referenced by dataset().
incFile()
void wrimsv2.wreslparser.elements.WriteCSV.incFile (ArrayList< String > list, PrintWriter out) static
Definition at line 384 of file WriteCSV.java.
Referenced by dataset().
mapStringListMerged()
void wrimsv2.wreslparser.elements.WriteCSV.mapStringListMerged (Object obj, PrintWriter out) static
Definition at line 651 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator.
output()
void wrimsv2.wreslparser.elements.WriteCSV.output (Map< String, ModelDataSet > modelDataMap, String outParent) static
Definition at line 95 of file WriteCSV.java.
References dataset().
Referenced by study(), and study().
sequence() [1/2]
void wrimsv2.wreslparser.elements.WriteCSV.sequence (ArrayList< String > modelList, ArrayList< String > modelConditionList, PrintWriter out) static
Definition at line 304 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator.
Referenced by study(), and study().
sequence() [2/2]
void wrimsv2.wreslparser.elements.WriteCSV.sequence (Map< Integer, Sequence > seqMap, ArrayList< Integer > list, PrintWriter out) static
Definition at line 315 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator.
study() [1/2]
void wrimsv2.wreslparser.elements.WriteCSV.study (StudyConfig sc, Map< String, ModelDataSet > modelDataMap, String outParent) static
Definition at line 77 of file WriteCSV.java.
References wrimsv2.wreslparser.elements.Tools.deleteDir(), wrimsv2.wreslparser.elements.Tools.openFile(), output(), sequence(), sequence_header, wrimsv2.wreslparser.elements.StudyConfig.sequenceMap, and wrimsv2.wreslparser.elements.StudyConfig.sequenceOrder.
study() [2/2]
void wrimsv2.wreslparser.elements.WriteCSV.study (StudyDataSet sd, String outParent) static
Definition at line 43 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionList(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesMap(), wrimsv2.wreslparser.elements.Tools.openFile(), output(), sequence(), sequence_header, timeseries_header, timeseries_timestep_header, timeseries_wholeStudy(), and timeseriesTimeStep().
Referenced by wrimsv2.wreslparser.elements.StudyUtils.checkStudy().
svar()
void wrimsv2.wreslparser.elements.WriteCSV.svar (Map< String, Svar > sMap, ArrayList< String > list, PrintWriter out) static
Definition at line 237 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Svar.caseCondition, wrimsv2.commondata.wresldata.Svar.caseExpression, wrimsv2.commondata.wresldata.Svar.caseName, wrimsv2.commondata.wresldata.Param.csv_seperator, currentModelDataSet, wrimsv2.commondata.wresldata.Svar.dependants, wrimsv2.commondata.wresldata.Svar.fromWresl, wrimsv2.commondata.wresldata.Svar.neededVarInCycleSet, and wrimsv2.commondata.wresldata.Svar.timeArraySize.
Referenced by dataset().
timeseries_model()
void wrimsv2.wreslparser.elements.WriteCSV.timeseries_model (Map< String, Timeseries > sTsMap, ArrayList< String > list, PrintWriter out) static
Definition at line 215 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Timeseries.convertToUnits, wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.Timeseries.dssBPart, wrimsv2.commondata.wresldata.Timeseries.fromWresl, wrimsv2.commondata.wresldata.Timeseries.kind, and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by dataset().
timeseries_wholeStudy()
void wrimsv2.wreslparser.elements.WriteCSV.timeseries_wholeStudy (Map< String, Timeseries > tsMap, PrintWriter out) static
Definition at line 330 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Timeseries.convertToUnits, wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.Timeseries.dssBPart, wrimsv2.commondata.wresldata.Timeseries.fromWresl, wrimsv2.commondata.wresldata.Timeseries.kind, and wrimsv2.commondata.wresldata.Timeseries.units.
Referenced by study().
timeseriesTimeStep()
void wrimsv2.wreslparser.elements.WriteCSV.timeseriesTimeStep (StudyDataSet sd, PrintWriter out) static
Definition at line 355 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.Timeseries.dssBPart, wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesMap(), and wrimsv2.commondata.wresldata.StudyDataSet.getTimeseriesTimeStepMap().
Referenced by study().
weight()
void wrimsv2.wreslparser.elements.WriteCSV.weight (Map< String, WeightElement > wtMap, ArrayList< String > list, PrintWriter out) static
Definition at line 422 of file WriteCSV.java.
References wrimsv2.commondata.wresldata.WeightElement.condition, wrimsv2.commondata.wresldata.Param.csv_seperator, wrimsv2.commondata.wresldata.WeightElement.timeArraySize, and wrimsv2.commondata.wresldata.WeightElement.weight.
Referenced by dataset().
Member Data Documentation
alias_header
String wrimsv2.wreslparser.elements.WriteCSV.alias_header ="NAME,TIME_ARRAY_SIZE,TYPE,UNITS,EXPRESSION,DEPENDANT,FROM_WRESL_FILE,NEED_VAR_FROM_CYCLE,USED_IN_LATER_CYCLE" static
Definition at line 38 of file WriteCSV.java.
Referenced by dataset().
currentModelDataSet
ModelDataSet wrimsv2.wreslparser.elements.WriteCSV.currentModelDataSet static private
Definition at line 40 of file WriteCSV.java.
Referenced by alias(), dataset(), dvar(), and svar().
dvar_header
String wrimsv2.wreslparser.elements.WriteCSV.dvar_header ="NAME,TIME_ARRAY_SIZE,CONDITION,LOWER_BOUND,UPPER_BOUND,INTEGER,UNITS,TYPE,FROM_WRESL_FILE,USED_IN_LATER_CYCLE" static
Definition at line 37 of file WriteCSV.java.
Referenced by dataset().
external_header
String wrimsv2.wreslparser.elements.WriteCSV.external_header ="FUNCTION,FILE,FROM_WRESL_FILE" static
Definition at line 33 of file WriteCSV.java.
Referenced by dataset().
goal_header
String wrimsv2.wreslparser.elements.WriteCSV.goal_header = "NAME,TIME_ARRAY_SIZE,CASE,ORDER,CONDITION,EXPRESSION,DEPENDANT,FROM_WRESL_FILE,NEED_VAR_FROM_CYCLE," static
Definition at line 39 of file WriteCSV.java.
Referenced by dataset().
sequence_header
String wrimsv2.wreslparser.elements.WriteCSV.sequence_header ="CYCLE,CONDITION,TIMESTEP" static
Definition at line 31 of file WriteCSV.java.
Referenced by study(), and study().
svar_header
String wrimsv2.wreslparser.elements.WriteCSV.svar_header ="NAME,TIME_ARRAY_SIZE,CASE,ORDER,CONDITION,EXPRESSION,DEPENDANT,FROM_WRESL_FILE,NEED_VAR_FROM_CYCLE,USED_IN_LATER_CYCLE" static
Definition at line 34 of file WriteCSV.java.
Referenced by dataset().
timeseries_header
String wrimsv2.wreslparser.elements.WriteCSV.timeseries_header ="NAME,B_PART,TYPE,UNITS,CONVERT_TO_UNITS,FROM_WRESL_FILE" static
Definition at line 35 of file WriteCSV.java.
Referenced by dataset(), and study().
timeseries_timestep_header
String wrimsv2.wreslparser.elements.WriteCSV.timeseries_timestep_header ="NAME,B_PART,TIMESTEP" static
Definition at line 36 of file WriteCSV.java.
Referenced by study().
weight_header
String wrimsv2.wreslparser.elements.WriteCSV.weight_header ="DVAR,TIME_ARRAY_SIZE,CONDITION,WEIGHT" static
Definition at line 32 of file WriteCSV.java.
Referenced by dataset().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/WriteCSV.java