Wrims-engine: wrimsv2.wreslplus.elements.Workflow Class Reference
wrimsv2.wreslplus.elements.Workflow Class Reference
Static Public Member Functions
static StudyTemp checkStudy (String mainFilePath)
static StudyTemp checkStudy_compileLog (String mainFilePath)
Private Member Functions
Workflow ()
Detailed Description
Definition at line 29 of file Workflow.java.
Constructor & Destructor Documentation
Workflow()
wrimsv2.wreslplus.elements.Workflow.Workflow () private
Definition at line 32 of file Workflow.java.
Member Function Documentation
checkStudy()
StudyTemp wrimsv2.wreslplus.elements.Workflow.checkStudy (String mainFilePath) static
put effective models into fileModelDataTable
put effective include models into fileModelDataTable
Definition at line 35 of file Workflow.java.
References wrimsv2.wreslparser.elements.LogUtils._logFile, wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslplus.elements.Procedures.analyzeVarNeededFromCycle(), wrimsv2.wreslplus.elements.SvarTemp.caseCondition, wrimsv2.wreslplus.elements.SvarTemp.caseExpression, wrimsv2.wreslplus.elements.SvarTemp.caseName, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIfStatementHasUnknownDependants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIncModelNotExistIgnoreCase(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialConst(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialVarInConfigNotDeclaredInWresl(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkModelRedefinedIgnoreCase(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkParameterHasUnknownDepedants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSeqConditionHasUnknownDepedants(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSequenceHasUniqueModel(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarRedefined(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarUsedBeforeDefined(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightObjList(), wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightVarNotInDvar(), wrimsv2.wreslplus.elements.Procedures.classifyDependants(), wrimsv2.wreslplus.elements.VarCycleIndex.clearVarCycleIndexList(), wrimsv2.wreslplus.elements.Procedures.collectTimeStep(), wrimsv2.wreslplus.elements.procedures.ProcWeight.collectWeightVar(), wrimsv2.wreslplus.elements.procedures.ToLowerCase.convert(), wrimsv2.wreslplus.elements.Procedures.convertAliasToGoal(), wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap(), wrimsv2.wreslplus.elements.Procedures.createSpaceInVarCycleValueMap(), wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.wreslplus.elements.ParamTemp.dependants, wrimsv2.wreslparser.elements.StudyParser.error_summary, wrimsv2.wreslplus.elements.ParamTemp.expression, wrimsv2.wreslplus.elements.StudyTemp.fileModelDataTable, wrimsv2.wreslplus.elements.StudyTemp.fileModelNameMap, wrimsv2.wreslplus.elements.Procedures.findAllOffSpring(), wrimsv2.wreslplus.elements.procedures.ProcMainFile.findAllOffSpring_incModel(), wrimsv2.wreslplus.elements.procedures.ProcMainFile.findEffectiveIncludeModel(), wrimsv2.wreslplus.elements.procedures.ProcMainFile.findEffectiveModel(), wrimsv2.wreslplus.elements.Procedures.findFileGroupOrder(), wrimsv2.wreslplus.elements.procedures.ProcMainFile.findGroupOrder_incModel(), wrimsv2.wreslplus.elements.Procedures.findKidMap(), wrimsv2.wreslplus.elements.procedures.ProcMainFile.findKidMap_incModel(), wrimsv2.wreslplus.elements.Tools.getCanonicalLowCasePath(), wrimsv2.wreslplus.elements.ParamTemp.id, wrimsv2.wreslparser.elements.LogUtils.importantMsg(), wrimsv2.wreslplus.elements.ModelTemp.incFileRelativePathList, wrimsv2.wreslplus.elements.StudyTemp.incModelList_effective, wrimsv2.wreslplus.elements.SequenceTemp.model, wrimsv2.wreslplus.elements.StudyTemp.modelList_effective, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.parameterMap, wrimsv2.config.ConfigUtils.paramMap, wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile(), wrimsv2.wreslparser.elements.StudyUtils.parserCheckVarUndefined, wrimsv2.wreslplus.elements.ParserUtils.parseWreslMain(), wrimsv2.wreslparser.elements.LogUtils.parsingSummaryMsg(), wrimsv2.wreslplus.elements.ModelTemp.pathRelativeToRunDir, wrimsv2.wreslplus.elements.Procedures.postProcessIncFileList(), wrimsv2.wreslplus.elements.Procedures.postProcessVarListinIncFile(), wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.process(), wrimsv2.wreslplus.elements.procedures.ProcParameter.process(), wrimsv2.wreslplus.elements.Procedures.processDependants(), wrimsv2.wreslplus.elements.procedures.ProcGoal.processGoalHS2(), wrimsv2.wreslplus.elements.procedures.ProcIncFile.processPath(), wrimsv2.wreslplus.elements.procedures.ProcWeight.processWeightGroup(), wrimsv2.wreslplus.elements.procedures.ProcVarIncFileList.replaceIncFile(), wrimsv2.wreslparser.elements.StudyParser.reset(), wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.ParserUtils.setRunDir(), wrimsv2.components.ControlData.showWreslLog, and wrimsv2.wreslparser.elements.StudyParser.total_errors.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.parseWreslPlus().
checkStudy_compileLog()
StudyTemp wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog (String mainFilePath) static
Definition at line 266 of file Workflow.java.
References wrimsv2.wreslplus.elements.VarCycleIndex.clearVarCycleIndexList(), wrimsv2.wreslplus.elements.CompileLog.createMainWreslLog(), wrimsv2.wreslplus.elements.CompileLog.createWreslFileLog(), wrimsv2.wreslplus.elements.Tools.getCanonicalLowCasePath(), wrimsv2.wreslplus.elements.ParserUtils.parseWreslFile(), wrimsv2.wreslplus.elements.ParserUtils.parseWreslMain(), wrimsv2.wreslparser.elements.StudyParser.reset(), wrimsv2.wreslplus.elements.ParserUtils.setRunDir(), and wrimsv2.wreslplus.elements.CompileLog.writeLog().
Referenced by wrimsv2.wreslparser.elements.StudyUtils.parseWreslPlus().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/Workflow.java