Wrims-engine: wrimsv2.external.SalinitySurrogateSetup Class Reference
wrimsv2.external.SalinitySurrogateSetup Class Reference
Public Member Functions
SalinitySurrogateSetup ()
Static Public Member Functions
static Surrogate emmatonANN ()
static SalinitySurrogateManager getManager ()
Static Package Attributes
static boolean isInitialized = false
static SalinitySurrogateManager ssm
Detailed Description
Definition at line 8 of file SalinitySurrogateSetup.java.
Constructor & Destructor Documentation
SalinitySurrogateSetup()
wrimsv2.external.SalinitySurrogateSetup.SalinitySurrogateSetup ()
Definition at line 12 of file SalinitySurrogateSetup.java.
Member Function Documentation
emmatonANN()
Surrogate wrimsv2.external.SalinitySurrogateSetup.emmatonANN () static
Definition at line 48 of file SalinitySurrogateSetup.java.
References wrimsv2.external.ExternalFunction.externalDir.
Referenced by getManager().
getManager()
SalinitySurrogateManager wrimsv2.external.SalinitySurrogateSetup.getManager () static
Definition at line 14 of file SalinitySurrogateSetup.java.
References wrimsv2.config.ConfigUtils.configMap, emmatonANN(), wrimsv2.ilp.ILP.getIlpDir(), isInitialized, wrimsv2.config.ConfigUtils.readBoolean(), and ssm.
Referenced by wrimsv2.external.Functionrequiredsac.Functionrequiredsac(), wrimsv2.external.Functionsurrogateec.Functionsurrogateec(), and wrimsv2.external.Functionsurrogateeclinearize.Functionsurrogateeclinearize().
Member Data Documentation
isInitialized
boolean wrimsv2.external.SalinitySurrogateSetup.isInitialized = false static package
Definition at line 9 of file SalinitySurrogateSetup.java.
Referenced by getManager().
ssm
SalinitySurrogateManager wrimsv2.external.SalinitySurrogateSetup.ssm static package
Definition at line 10 of file SalinitySurrogateSetup.java.
Referenced by getManager().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/SalinitySurrogateSetup.java