Wrims-engine: wrimsv2.components.ClearValue Class Reference
wrimsv2.components.ClearValue Class Reference
Static Public Member Functions
static void clearCycleLoopValue (ArrayList< String > modelList, Map< String, ModelDataSet > modelDataSetMap)
static void clearValues (ArrayList< String > modelList, Map< String, ModelDataSet > modelDataSetMap)
Detailed Description
Definition at line 11 of file ClearValue.java.
Member Function Documentation
clearCycleLoopValue()
void wrimsv2.components.ClearValue.clearCycleLoopValue (ArrayList< String > modelList, Map< String, ModelDataSet > modelDataSetMap) static
Definition at line 13 of file ClearValue.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.Alias.setData(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.commondata.wresldata.Svar.setData(), wrimsv2.commondata.wresldata.ModelDataSet.svList, and wrimsv2.commondata.wresldata.ModelDataSet.svMap.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
clearValues()
void wrimsv2.components.ClearValue.clearValues (ArrayList< String > modelList, Map< String, ModelDataSet > modelDataSetMap) static
Definition at line 36 of file ClearValue.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.commondata.wresldata.ModelDataSet.clearFutureAsMap(), wrimsv2.commondata.wresldata.ModelDataSet.clearFutureSvMap(), wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.Alias.setData(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.commondata.wresldata.Svar.setData(), wrimsv2.commondata.wresldata.ModelDataSet.svList, and wrimsv2.commondata.wresldata.ModelDataSet.svMap.
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/ClearValue.java