Wrims-engine: wrimsv2.components.IncFileCollector Class Reference
wrimsv2.components.IncFileCollector Class Reference
Public Member Functions
IncFileCollector (String mainWreslPath, String targetDir)
IncFileCollector (String mainWreslPath, String targetDir, String lookupSubDir)
Static Public Member Functions
static void collect ()
static void initialize (String mainFilePath)
static IncFileFinderParser initParser (IncFileSimple ifs) throws RecognitionException
static void main (String[] args)
static ArrayList< IncFileSimple > parseWresl (IncFileSimple ifs)
static void searchIncFiles (ArrayList< IncFileSimple > ifs_array)
Static Public Attributes
static LinkedHashSet< String > incFileList_all
static LinkedHashSet< String > lookupTableList_all
static int number_of_errors
Static Private Member Functions
static void copyWreslsAndLookupTablesTo (String targetDir)
Static Private Attributes
static String baseDir
static final String logFileName = "=FileCollector=.log"
static String lookupSubDir =""
static String mainFilePath
static String runDir
static ArrayList< IncFileSimple > tempList
Detailed Description
Definition at line 21 of file IncFileCollector.java.
Constructor & Destructor Documentation
IncFileCollector() [1/2]
wrimsv2.components.IncFileCollector.IncFileCollector (String mainWreslPath, String targetDir)
Definition at line 34 of file IncFileCollector.java.
References IncFileCollector().
Referenced by IncFileCollector(), and main().
IncFileCollector() [2/2]
wrimsv2.components.IncFileCollector.IncFileCollector (String mainWreslPath, String targetDir, String lookupSubDir)
Definition at line 40 of file IncFileCollector.java.
References collect(), copyWreslsAndLookupTablesTo(), wrimsv2.wreslparser.elements.LogUtils.importantMsg(), initialize(), lookupSubDir, and number_of_errors.
Member Function Documentation
collect()
void wrimsv2.components.IncFileCollector.collect () static
Definition at line 90 of file IncFileCollector.java.
References mainFilePath, and searchIncFiles().
Referenced by IncFileCollector().
copyWreslsAndLookupTablesTo()
void wrimsv2.components.IncFileCollector.copyWreslsAndLookupTablesTo (String targetDir) static private
Definition at line 188 of file IncFileCollector.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.LogUtils.importantMsg(), incFileList_all, lookupSubDir, lookupTableList_all, runDir, and wrimsv2.wreslparser.elements.LogUtils.warningMsg().
Referenced by IncFileCollector().
initialize()
void wrimsv2.components.IncFileCollector.initialize (String mainFilePath) static
Definition at line 66 of file IncFileCollector.java.
References incFileList_all, logFileName, lookupTableList_all, mainFilePath, number_of_errors, runDir, and wrimsv2.wreslparser.elements.LogUtils.setLogFile().
Referenced by IncFileCollector().
initParser()
IncFileFinderParser wrimsv2.components.IncFileCollector.initParser (IncFileSimple ifs) throws RecognitionException static
Definition at line 152 of file IncFileCollector.java.
References wrimsv2.wreslparser.elements.LogUtils.warningMsgLocation().
Referenced by parseWresl().
main()
void wrimsv2.components.IncFileCollector.main (String[] args) static
Definition at line 239 of file IncFileCollector.java.
References IncFileCollector().
parseWresl()
ArrayList< IncFileSimple > wrimsv2.components.IncFileCollector.parseWresl (IncFileSimple ifs) static
Definition at line 118 of file IncFileCollector.java.
References wrimsv2.wreslplus.elements.IncFileSimple.absPath, wrimsv2.wreslparser.elements.LogUtils.importantMsg(), incFileList_all, initParser(), lookupTableList_all, and wrimsv2.wreslplus.elements.LookupTableSimple.tableName.
Referenced by searchIncFiles().
searchIncFiles()
void wrimsv2.components.IncFileCollector.searchIncFiles (ArrayList< IncFileSimple > ifs_array) static
Definition at line 105 of file IncFileCollector.java.
References parseWresl(), searchIncFiles(), and tempList.
Referenced by collect(), and searchIncFiles().
Member Data Documentation
baseDir
String wrimsv2.components.IncFileCollector.baseDir static private
Definition at line 27 of file IncFileCollector.java.
incFileList_all
LinkedHashSet<String> wrimsv2.components.IncFileCollector.incFileList_all static
Definition at line 23 of file IncFileCollector.java.
Referenced by copyWreslsAndLookupTablesTo(), initialize(), and parseWresl().
logFileName
final String wrimsv2.components.IncFileCollector.logFileName = "=FileCollector=.log" static private
Definition at line 30 of file IncFileCollector.java.
Referenced by initialize().
lookupSubDir
String wrimsv2.components.IncFileCollector.lookupSubDir ="" static private
Definition at line 31 of file IncFileCollector.java.
Referenced by IncFileCollector(), and copyWreslsAndLookupTablesTo().
lookupTableList_all
LinkedHashSet<String> wrimsv2.components.IncFileCollector.lookupTableList_all static
Definition at line 24 of file IncFileCollector.java.
Referenced by copyWreslsAndLookupTablesTo(), initialize(), and parseWresl().
mainFilePath
String wrimsv2.components.IncFileCollector.mainFilePath static private
Definition at line 29 of file IncFileCollector.java.
Referenced by collect(), and initialize().
number_of_errors
int wrimsv2.components.IncFileCollector.number_of_errors static
Definition at line 25 of file IncFileCollector.java.
Referenced by IncFileCollector(), and initialize().
runDir
String wrimsv2.components.IncFileCollector.runDir static private
Definition at line 28 of file IncFileCollector.java.
Referenced by copyWreslsAndLookupTablesTo(), and initialize().
tempList
ArrayList<IncFileSimple> wrimsv2.components.IncFileCollector.tempList static private
Definition at line 26 of file IncFileCollector.java.
Referenced by searchIncFiles().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/IncFileCollector.java