Wrims-engine: wrimsv2.components.ControllerBatch Class Reference
wrimsv2.components.ControllerBatch Class Reference
Public Member Functions
ControllerBatch ()
ControllerBatch (String[] args)
void connectToDataBase ()
void generateStudyFile ()
boolean isRunCompleted ()
StudyDataSet parse () throws RecognitionException, IOException
void processArgs (String[] args)
void procLaunch (String[] args)
void runModel (StudyDataSet sds)
void runModelCbc (StudyDataSet sds)
void runModelClp (StudyDataSet sds)
void runModelGurobi (StudyDataSet sds)
void runModelGurobiTest (StudyDataSet sds)
void runModelILP (StudyDataSet sds)
void runModelOrTools (StudyDataSet sds, String mpSolverType)
void runModelXA (StudyDataSet sds)
void setControlData (String[] args)
void writeOutputDssEveryTenYears ()
Static Public Member Functions
static void main (String[] args)
Public Attributes
boolean enableConfigProgress = false
boolean enableProgressLog = false
Private Attributes
MySQLCWriter mySQLCWriter
MySQLRWriter mySQLRWriter
boolean runCompleted = false
SQLServerRWriter sqlServerRWriter
Detailed Description
Definition at line 58 of file ControllerBatch.java.
Constructor & Destructor Documentation
ControllerBatch() [1/2]
wrimsv2.components.ControllerBatch.ControllerBatch ()
Definition at line 67 of file ControllerBatch.java.
Referenced by main().
ControllerBatch() [2/2]
wrimsv2.components.ControllerBatch.ControllerBatch (String[] args)
Definition at line 69 of file ControllerBatch.java.
References wrimsv2.ilp.ILP._noteFile_timeusage, wrimsv2.wreslparser.elements.StudyUtils.compileOnly, wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.wreslparser.elements.StudyUtils.configFilePath, connectToDataBase(), wrimsv2.ilp.ILP.createNoteFile(), enableConfigProgress, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.ilp.ILP.getIlpDir(), wrimsv2.tools.General.getPID(), wrimsv2.components.Error.getTotalError(), wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.components.FilePaths.mainDirectory, parse(), processArgs(), runCompleted, runModel(), wrimsv2.ilp.ILP.setMaximumFractionDigits(), wrimsv2.ilp.ILP.setVarDir(), wrimsv2.components.ControlData.showTimeUsage, wrimsv2.components.TimeUsage.showTimeUsage(), wrimsv2.components.ControlData.t_parse, wrimsv2.wreslparser.elements.StudyUtils.total_errors, wrimsv2.ilp.ILP.writeNoteLn(), and wrimsv2.wreslparser.elements.StudyUtils.writeObj().
Member Function Documentation
connectToDataBase()
void wrimsv2.components.ControllerBatch.connectToDataBase ()
Definition at line 1782 of file ControllerBatch.java.
References mySQLCWriter, mySQLRWriter, wrimsv2.components.ControlData.outputType, and sqlServerRWriter.
Referenced by ControllerBatch().
generateStudyFile()
void wrimsv2.components.ControllerBatch.generateStudyFile ()
Definition at line 174 of file ControllerBatch.java.
References wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.components.FilePaths.fullInitFilePath, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.components.FilePaths.fullSvarFilePath, wrimsv2.components.VariableTimeStep.getTotalTimeStep(), wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
isRunCompleted()
boolean wrimsv2.components.ControllerBatch.isRunCompleted ()
Definition at line 127 of file ControllerBatch.java.
References runCompleted.
Referenced by main().
main()
void wrimsv2.components.ControllerBatch.main (String[] args) static
Definition at line 508 of file ControllerBatch.java.
References ControllerBatch(), and isRunCompleted().
parse()
StudyDataSet wrimsv2.components.ControllerBatch.parse () throws RecognitionException, IOException
Definition at line 228 of file ControllerBatch.java.
References wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.components.ControlData.cbcCheckIntErr, wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.tools.Warmstart.collectIntegerDV_3(), wrimsv2.wreslparser.elements.StudyUtils.compileOnly, wrimsv2.wreslparser.elements.StudyUtils.compileStudy(), wrimsv2.components.FilePaths.fullMainPath, wrimsv2.components.Error.getTotalError(), wrimsv2.wreslparser.elements.StudyUtils.loadObject(), wrimsv2.wreslparser.elements.StudyUtils.loadParserData, wrimsv2.wreslparser.elements.StudyUtils.parserDataPath, wrimsv2.components.LoadParameter.process(), wrimsv2.wreslplus.elements.ParserUtils.setRunDir(), wrimsv2.components.ControlData.solverName, and wrimsv2.components.ControlData.useCbcWarmStart.
Referenced by ControllerBatch().
processArgs()
void wrimsv2.components.ControllerBatch.processArgs (String[] args)
Definition at line 131 of file ControllerBatch.java.
References enableConfigProgress, wrimsv2.components.ControlData.enableProgressLog, enableProgressLog, wrimsv2.config.ConfigUtils.loadArgs(), procLaunch(), and setControlData().
Referenced by ControllerBatch().
procLaunch()
void wrimsv2.components.ControllerBatch.procLaunch (String[] args)
Definition at line 1792 of file ControllerBatch.java.
Referenced by processArgs().
runModel()
void wrimsv2.components.ControllerBatch.runModel (StudyDataSet sds)
Definition at line 265 of file ControllerBatch.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.components.Error.getTotalError(), wrimsv2.ilp.ILP.logging, wrimsv2.evaluator.WeightEval.outputWtTableAR(), runModelCbc(), runModelClp(), runModelGurobi(), runModelILP(), runModelOrTools(), runModelXA(), wrimsv2.components.ControlData.solverName, and wrimsv2.components.Error.writeErrorLog().
Referenced by ControllerBatch().
runModelCbc()
void wrimsv2.components.ControllerBatch.runModelCbc (StudyDataSet sds)
Definition at line 1536 of file ControllerBatch.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.solver.CbcSolver.close(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, enableConfigProgress, enableProgressLog, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.solver.CbcSolver.init(), wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.evaluator.TimeOperation.initMemDate(), wrimsv2.evaluator.TimeOperation.initOutputDate(), wrimsv2.solver.CbcSolver.intLog, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.solver.CbcSolver.logCbcDebug(), wrimsv2.solver.CbcSolver.logCbcWatchList(), wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.ilp.ILP.logUsageMemory(), wrimsv2.components.FilePaths.mainDirectory, wrimsv2.components.ControlData.monMemSection, mySQLCWriter, mySQLRWriter, wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.outputYear, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.solver.CbcSolver.resetModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.evaluator.TimeOperation.setMemDate(), wrimsv2.evaluator.TimeOperation.setOutputDate(), wrimsv2.ilp.ILP.setSvarFile(), wrimsv2.evaluator.DssOperation.shiftData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), sqlServerRWriter, wrimsv2.components.ControlData.startYear, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.components.ControlData.watchList, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeNoteLn(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.ilp.ILP.writeSvarValue(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), wrimsv2.components.ControlData.xasolver, and wrimsv2.components.ControlData.yearOutputSection.
Referenced by runModel().
runModelClp()
void wrimsv2.components.ControllerBatch.runModelClp (StudyDataSet sds)
Definition at line 1342 of file ControllerBatch.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.solver.ClpSolver.close(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, enableConfigProgress, enableProgressLog, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.solver.ClpSolver.init(), wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.logUsageMemory(), wrimsv2.components.FilePaths.mainDirectory, mySQLCWriter, mySQLRWriter, wrimsv2.solver.ClpSolver.newProblem(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputType, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), sqlServerRWriter, wrimsv2.components.ControlData.startYear, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), and wrimsv2.hdf5.HDF5Writer.writeTimestepData().
Referenced by runModel().
runModelGurobi()
void wrimsv2.components.ControllerBatch.runModelGurobi (StudyDataSet sds)
Definition at line 903 of file ControllerBatch.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.Error.addSolvingError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.ilp.ILP.closeIlpFile(), wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.ilp.ILP.cplexLpFilePath, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.solver.Gurobi.GurobiSolver.dispose(), wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, enableConfigProgress, enableProgressLog, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.solver.Gurobi.GurobiSolver.initialize(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.evaluator.TimeOperation.initMemDate(), wrimsv2.evaluator.TimeOperation.initOutputDate(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.ilp.ILP.logUsageMemory(), wrimsv2.components.FilePaths.mainDirectory, wrimsv2.components.ControlData.monMemSection, mySQLCWriter, mySQLRWriter, wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.outputYear, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.ilp.ILP.setIlpFile(), wrimsv2.solver.Gurobi.GurobiSolver.setLp(), wrimsv2.evaluator.TimeOperation.setMemDate(), wrimsv2.evaluator.TimeOperation.setOutputDate(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.evaluator.DssOperation.shiftData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.solver.Gurobi.GurobiSolver.solve(), sqlServerRWriter, wrimsv2.components.ControlData.startYear, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.ilp.ILP.writeDvarValue_Gurobi(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.ilp.ILP.writeIlp(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeObjValue_Gurobi(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.ilp.ILP.writeSvarValue(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), and wrimsv2.components.ControlData.yearOutputSection.
Referenced by runModel().
runModelGurobiTest()
void wrimsv2.components.ControllerBatch.runModelGurobiTest (StudyDataSet sds)
Definition at line 1118 of file ControllerBatch.java.
References wrimsv2.wreslparser.elements.StudyUtils.configFileName, wrimsv2.solver.Gurobi.GurobiSolver.dispose(), wrimsv2.components.ControlData.endYear, wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.ControlData.gurobi_objective, wrimsv2.solver.Gurobi.GurobiSolver.initialize(), wrimsv2.components.FilePaths.mainDirectory, wrimsv2.wreslparser.elements.Tools.openFile(), wrimsv2.solver.Gurobi.GurobiSolver.setLp(), wrimsv2.solver.Gurobi.GurobiSolver.solve(), wrimsv2.components.ControlData.startYear, and wrimsv2.ilp.ILP.writeObjValueLog().
runModelILP()
void wrimsv2.components.ControllerBatch.runModelILP (StudyDataSet sds)
Definition at line 516 of file ControllerBatch.java.
References wrimsv2.components.Error.addConfigError(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.solver.CbcSolver.close(), wrimsv2.solver.ClpSolver.close(), wrimsv2.ilp.ILP.closeCplexLpFile(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.ilp.ILP.closeIlpFile(), wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.ilp.ILP.cplexLpFilePath, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, enableConfigProgress, enableProgressLog, wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.solver.Cbc0Solver.init(), wrimsv2.solver.CbcSolver.init(), wrimsv2.solver.Clp0Solver.init(), wrimsv2.solver.ClpSolver.init(), wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.evaluator.TimeOperation.initMemDate(), wrimsv2.evaluator.TimeOperation.initOutputDate(), wrimsv2.solver.CbcSolver.intLog, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingAllCycles, wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.solver.CbcSolver.logIntCheck(), wrimsv2.ilp.ILP.logUsageMemory(), wrimsv2.components.ControlData.lpFileWritingTime, wrimsv2.ilp.ILP.lpSolveFilePath, wrimsv2.components.FilePaths.mainDirectory, wrimsv2.components.ControlData.monMemSection, mySQLCWriter, mySQLRWriter, wrimsv2.solver.CbcSolver.newProblem(), wrimsv2.solver.ClpSolver.newProblem(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.outputYear, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.ilp.ILP.reOpenCplexLpFile(), wrimsv2.solver.CbcSolver.resetModel(), wrimsv2.components.ControlData.saveCplexLpStringToFile, wrimsv2.ilp.ILP.saveCplexLpStringToFile(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.ilp.ILP.setIlpFile(), wrimsv2.solver.Cbc0Solver.setLP(), wrimsv2.solver.Clp0Solver.setLP(), wrimsv2.solver.LPSolveSolver.setLP(), wrimsv2.evaluator.TimeOperation.setMemDate(), wrimsv2.evaluator.TimeOperation.setOutputDate(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.evaluator.DssOperation.shiftData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.solver.Cbc0Solver.solve(), wrimsv2.solver.Clp0Solver.solve(), wrimsv2.solver.LPSolveSolver.solve(), wrimsv2.commondata.wresldata.Param.SOLVER_CBC, wrimsv2.commondata.wresldata.Param.SOLVER_CBC0, wrimsv2.commondata.wresldata.Param.SOLVER_CBC1, wrimsv2.commondata.wresldata.Param.SOLVER_CLP, wrimsv2.commondata.wresldata.Param.SOLVER_CLP0, wrimsv2.commondata.wresldata.Param.SOLVER_CLP1, wrimsv2.commondata.wresldata.Param.SOLVER_LPSOLVE, wrimsv2.commondata.wresldata.Param.SOLVER_XA, wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.solverType, sqlServerRWriter, wrimsv2.components.ControlData.startYear, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.components.ControlData.useCplexLpString, wrimsv2.solver.Cbc0Solver.varDoubleMap, wrimsv2.solver.CbcSolver.varDoubleMap, wrimsv2.solver.Clp0Solver.varDoubleMap, wrimsv2.solver.ClpSolver.varDoubleMap, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.ilp.ILP.writeDvarValue_Clp0_Cbc0(), wrimsv2.ilp.ILP.writeDvarValue_LPSOLVE(), wrimsv2.ilp.ILP.writeDvarValue_XA(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.ilp.ILP.writeIlp(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeObjValue_Clp0_Cbc0(), wrimsv2.ilp.ILP.writeObjValue_LPSOLVE(), wrimsv2.ilp.ILP.writeObjValue_XA(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.ilp.ILP.writeSvarValue(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), wrimsv2.components.ControlData.xasolver, and wrimsv2.components.ControlData.yearOutputSection.
Referenced by runModel().
runModelOrTools()
void wrimsv2.components.ControllerBatch.runModelOrTools (StudyDataSet sds, String mpSolverType)
Definition at line 1170 of file ControllerBatch.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.Error.addSolvingError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.ilp.ILP.closeIlpFile(), wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.solver.ortools.OrToolsSolver.createModel(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.solver.ortools.OrToolsSolver.delete(), wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.solver.ortools.OrToolsSolver.initialize(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingMPModel, wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.ilp.ILP.logUsageMemory(), mySQLCWriter, mySQLRWriter, wrimsv2.components.ControlData.otsolver, wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputType, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.solver.ortools.OrToolsSolver.run(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.ilp.ILP.setIlpFile(), wrimsv2.ilp.ILP.setVarFile(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), sqlServerRWriter, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.ilp.ILP.writeDvarValue_OrTools(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.ilp.ILP.writeIlp(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.ilp.ILP.writeMPModelFile(), wrimsv2.ilp.ILP.writeObjValue_OrTools(), wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.ilp.ILP.writeSvarValue(), and wrimsv2.hdf5.HDF5Writer.writeTimestepData().
Referenced by runModel().
runModelXA()
void wrimsv2.components.ControllerBatch.runModelXA (StudyDataSet sds)
Definition at line 296 of file ControllerBatch.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus(), wrimsv2.components.VariableTimeStep.checkEndDate(), wrimsv2.components.ClearValue.clearCycleLoopValue(), wrimsv2.components.ClearValue.clearValues(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarCycleIndexByTimeStep(), wrimsv2.commondata.wresldata.StudyDataSet.clearVarTimeArrayCycleValueMap(), wrimsv2.hdf5.HDF5Writer.closeDataStructure(), wrimsv2.wreslparser.elements.StudyUtils.configFilePath, wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currDvSlackSurplusMap, wrimsv2.components.ControlData.currGoalMap, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.VariableTimeStep.currTimeAddOneDay(), wrimsv2.components.VariableTimeStep.currTimeAddOneMonth(), wrimsv2.components.ControlData.currTimeStep, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.cycleStartDay, wrimsv2.components.ControlData.cycleStartMonth, wrimsv2.components.ControlData.cycleStartYear, wrimsv2.commondata.wresldata.ModelDataSet.deviationSlackSurplus_toleranceMap, wrimsv2.components.ControlData.dvDss, wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, enableConfigProgress, enableProgressLog, wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.Error.error_evaluation, wrimsv2.components.Error.error_solving, wrimsv2.components.FilePaths.fullCsvPath, wrimsv2.commondata.wresldata.StudyDataSet.getModelConditionParsers(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.components.Error.getTotalError(), wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.components.VariableTimeStep.initialCurrTimeStep(), wrimsv2.components.VariableTimeStep.initialCycleStartDate(), wrimsv2.evaluator.TimeOperation.initMemDate(), wrimsv2.evaluator.TimeOperation.initOutputDate(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isPostProcessing, wrimsv2.tools.General.isSelectedCycleOutput(), wrimsv2.ilp.ILP.loggingUsageMemeory, wrimsv2.ilp.ILP.logUsageMemory(), wrimsv2.components.FilePaths.mainDirectory, wrimsv2.components.ControlData.monMemSection, mySQLCWriter, mySQLRWriter, wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.components.ControlData.outputDay, wrimsv2.components.ControlData.outputMonth, wrimsv2.components.ControlData.outputType, wrimsv2.components.ControlData.outputYear, wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), wrimsv2.commondata.wresldata.ModelDataSet.processModel(), wrimsv2.components.VariableTimeStep.setCurrentDate(), wrimsv2.components.VariableTimeStep.setCycleEndDate(), wrimsv2.components.VariableTimeStep.setCycleStartDate(), wrimsv2.components.VariableTimeStep.setCycleTimeStep(), wrimsv2.evaluator.TimeOperation.setMemDate(), wrimsv2.evaluator.TimeOperation.setOutputDate(), wrimsv2.evaluator.DssOperation.shiftData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.hdf5.HDF5Writer.skipOneCycle(), wrimsv2.components.ControlData.solverName, sqlServerRWriter, wrimsv2.components.ControlData.startYear, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.components.Error.writeErrorLog(), wrimsv2.components.Error.writeEvaluationErrorFile(), wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(), wrimsv2.components.ControlData.writeInitToDVOutput, wrimsv2.hdf5.HDF5Writer.writeOneCycleSv(), wrimsv2.components.Error.writeSolvingErrorFile(), wrimsv2.hdf5.HDF5Writer.writeTimestepData(), wrimsv2.components.ControlData.xasolver, and wrimsv2.components.ControlData.yearOutputSection.
Referenced by runModel().
setControlData()
void wrimsv2.components.ControllerBatch.setControlData (String[] args)
Definition at line 151 of file ControllerBatch.java.
References wrimsv2.components.FilePaths.csvFolderName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.components.ControlData.endDay, wrimsv2.components.ControlData.endMonth, wrimsv2.components.ControlData.endYear, wrimsv2.components.FilePaths.groundwaterDir, wrimsv2.components.ControlData.initPartF, wrimsv2.components.ControlData.partA, wrimsv2.components.FilePaths.setDvarFilePaths(), wrimsv2.components.FilePaths.setInitFilePaths(), wrimsv2.components.FilePaths.setMainFilePaths(), wrimsv2.components.FilePaths.setSvarFilePaths(), wrimsv2.components.ControlData.solverName, wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, and wrimsv2.components.ControlData.svDvPartF.
Referenced by processArgs().
writeOutputDssEveryTenYears()
void wrimsv2.components.ControllerBatch.writeOutputDssEveryTenYears ()
Definition at line 498 of file ControllerBatch.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.timeStep, and wrimsv2.evaluator.DssOperation.writeDVAliasToDSS().
Member Data Documentation
enableConfigProgress
boolean wrimsv2.components.ControllerBatch.enableConfigProgress = false
Definition at line 61 of file ControllerBatch.java.
Referenced by ControllerBatch(), processArgs(), runModelCbc(), runModelClp(), runModelGurobi(), runModelILP(), and runModelXA().
enableProgressLog
boolean wrimsv2.components.ControllerBatch.enableProgressLog = false
Definition at line 60 of file ControllerBatch.java.
Referenced by processArgs(), runModelCbc(), runModelClp(), runModelGurobi(), runModelILP(), and runModelXA().
mySQLCWriter
MySQLCWriter wrimsv2.components.ControllerBatch.mySQLCWriter private
Definition at line 63 of file ControllerBatch.java.
Referenced by connectToDataBase(), runModelCbc(), runModelClp(), runModelGurobi(), runModelILP(), runModelOrTools(), and runModelXA().
mySQLRWriter
MySQLRWriter wrimsv2.components.ControllerBatch.mySQLRWriter private
Definition at line 64 of file ControllerBatch.java.
Referenced by connectToDataBase(), runModelCbc(), runModelClp(), runModelGurobi(), runModelILP(), runModelOrTools(), and runModelXA().
runCompleted
boolean wrimsv2.components.ControllerBatch.runCompleted = false private
Definition at line 62 of file ControllerBatch.java.
Referenced by ControllerBatch(), and isRunCompleted().
sqlServerRWriter
SQLServerRWriter wrimsv2.components.ControllerBatch.sqlServerRWriter private
Definition at line 65 of file ControllerBatch.java.
Referenced by connectToDataBase(), runModelCbc(), runModelClp(), runModelGurobi(), runModelILP(), runModelOrTools(), and runModelXA().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/ControllerBatch.java