Wrims-engine: wrimsv2.external.Functionemmatonsurrogatelinegen Class Reference
wrimsv2.external.Functionemmatonsurrogatelinegen Class Reference
Public Member Functions
Functionemmatonsurrogatelinegen ()
double emmatonsurrogatelinegen (double[] Qsac_prv, double Qsac_est, double[] Qexp_prv, double Qexp_est, double[] Qsjr_prv, double Qsjr_fut, double[] DXC_prv, double DXC_fut, double[] DICU_prv, double DICU_fut, double[] SMSCG_prv, double SMSCG_fut, double ECTARGET, int location, int variable, int ave_type, int currMonth, int currYear)
void execute (Stack stack)
Static Public Member Functions
static Surrogate emmatonANN ()
Private Attributes
final boolean DEBUG = false
SalinitySurrogateManager ssm
Static Private Attributes
static int cpuTime =0
static int nCalls =0
Additional Inherited Members
Static Public Attributes inherited from wrimsv2.external.ExternalFunction
static String externalDir =FilePaths.mainDirectory+File.separator+"external"+File.separator
Detailed Description
Definition at line 18 of file Functionemmatonsurrogatelinegen.java.
Constructor & Destructor Documentation
Functionemmatonsurrogatelinegen()
wrimsv2.external.Functionemmatonsurrogatelinegen.Functionemmatonsurrogatelinegen ()
Definition at line 24 of file Functionemmatonsurrogatelinegen.java.
References cpuTime, wrimsv2.components.TimeUsage.cpuTimeMap, emmatonANN(), nCalls, wrimsv2.components.TimeUsage.nCallsMap, and ssm.
Member Function Documentation
emmatonANN()
Surrogate wrimsv2.external.Functionemmatonsurrogatelinegen.emmatonANN () static
Definition at line 172 of file Functionemmatonsurrogatelinegen.java.
References wrimsv2.external.ExternalFunction.externalDir.
Referenced by Functionemmatonsurrogatelinegen().
emmatonsurrogatelinegen()
double wrimsv2.external.Functionemmatonsurrogatelinegen.emmatonsurrogatelinegen (double[] Qsac_prv, double Qsac_est, double[] Qexp_prv, double Qexp_est, double[] Qsjr_prv, double Qsjr_fut, double[] DXC_prv, double DXC_fut, double[] DICU_prv, double DICU_fut, double[] SMSCG_prv, double SMSCG_fut, double ECTARGET, int location, int variable, int ave_type, int currMonth, int currYear)
Definition at line 132 of file Functionemmatonsurrogatelinegen.java.
References ssm.
Referenced by execute().
execute()
void wrimsv2.external.Functionemmatonsurrogatelinegen.execute (Stack stack)
Reimplemented from wrimsv2.external.ExternalFunction.
Definition at line 46 of file Functionemmatonsurrogatelinegen.java.
References cpuTime, wrimsv2.components.TimeUsage.cpuTimeMap, emmatonsurrogatelinegen(), nCalls, and wrimsv2.components.TimeUsage.nCallsMap.
Member Data Documentation
cpuTime
int wrimsv2.external.Functionemmatonsurrogatelinegen.cpuTime =0 static private
Definition at line 20 of file Functionemmatonsurrogatelinegen.java.
Referenced by Functionemmatonsurrogatelinegen(), and execute().
DEBUG
final boolean wrimsv2.external.Functionemmatonsurrogatelinegen.DEBUG = false private
Definition at line 19 of file Functionemmatonsurrogatelinegen.java.
nCalls
int wrimsv2.external.Functionemmatonsurrogatelinegen.nCalls =0 static private
Definition at line 21 of file Functionemmatonsurrogatelinegen.java.
Referenced by Functionemmatonsurrogatelinegen(), and execute().
ssm
SalinitySurrogateManager wrimsv2.external.Functionemmatonsurrogatelinegen.ssm private
Definition at line 22 of file Functionemmatonsurrogatelinegen.java.
Referenced by Functionemmatonsurrogatelinegen(), and emmatonsurrogatelinegen().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/Functionemmatonsurrogatelinegen.java