Wrims-engine: wrimsv2.evaluator.EvalConstraint Class Reference
wrimsv2.evaluator.EvalConstraint Class Reference
Public Member Functions
EvalConstraint copyOf ()
EvalExpression getEvalExpression ()
String getSign ()
void setEvalExpression (EvalExpression ee)
void setSign (String sign)
Private Attributes
EvalExpression evalExpression =new EvalExpression()
String sign
Detailed Description
Definition at line 3 of file EvalConstraint.java.
Member Function Documentation
copyOf()
EvalConstraint wrimsv2.evaluator.EvalConstraint.copyOf ()
Definition at line 23 of file EvalConstraint.java.
References evalExpression, setEvalExpression(), setSign(), and sign.
getEvalExpression()
EvalExpression wrimsv2.evaluator.EvalConstraint.getEvalExpression ()
Definition at line 15 of file EvalConstraint.java.
References evalExpression.
Referenced by wrimsv2.tools.CheckWeightSlackSurplus.CheckWeightSlackSurplus(), wrimsv2.tools.MultiStepAnalyzer.analyzeOneConstraint(), wrimsv2.tools.RCCComparison.compareConstraint(), wrimsv2.components.DebugInterface.getAllControlGoalName(), wrimsv2.components.DebugInterface.getAllGoalFile(), wrimsv2.components.DebugInterface.getAllGoalString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), and wrimsv2.solver.CbcSolver.setConstraintsSkip().
getSign()
String wrimsv2.evaluator.EvalConstraint.getSign ()
Definition at line 19 of file EvalConstraint.java.
References sign.
Referenced by wrimsv2.tools.MultiStepAnalyzer.analyzeOneConstraint(), wrimsv2.tools.RCCComparison.compareConstraint(), wrimsv2.components.DebugInterface.getAllGoalFile(), wrimsv2.components.DebugInterface.getAllGoalString(), wrimsv2.components.DebugInterface.getFilterGoal(), wrimsv2.components.DebugInterface.getGoalInOneFile(), wrimsv2.components.DebugInterface.getGoalInOneFileWP(), wrimsv2.components.DebugInterface.getWatch(), wrimsv2.solver.CbcSolver.setConstraints(), wrimsv2.solver.ClpSolver.setConstraints(), wrimsv2.solver.Gurobi.GurobiSolver.setConstraints(), wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.XASolver.setConstraints(), wrimsv2.solver.CbcSolver.setConstraintsIIS(), and wrimsv2.solver.CbcSolver.setConstraintsSkip().
setEvalExpression()
void wrimsv2.evaluator.EvalConstraint.setEvalExpression (EvalExpression ee)
Definition at line 7 of file EvalConstraint.java.
References evalExpression.
Referenced by wrimsv2.evaluator.Evaluation.constraintStatement(), and copyOf().
setSign()
void wrimsv2.evaluator.EvalConstraint.setSign (String sign)
Definition at line 11 of file EvalConstraint.java.
References sign.
Referenced by wrimsv2.evaluator.Evaluation.constraintStatement(), and copyOf().
Member Data Documentation
evalExpression
EvalExpression wrimsv2.evaluator.EvalConstraint.evalExpression =new EvalExpression() private
Definition at line 4 of file EvalConstraint.java.
Referenced by copyOf(), getEvalExpression(), and setEvalExpression().
sign
String wrimsv2.evaluator.EvalConstraint.sign private
Definition at line 5 of file EvalConstraint.java.
Referenced by copyOf(), getSign(), and setSign().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/EvalConstraint.java