Wrims-engine: wrimsv2.sql.SQLServerRWriterAlt Class Reference
wrimsv2.sql.SQLServerRWriterAlt Class Reference
Public Member Functions
SQLServerRWriterAlt ()
Date addOneDay (Date date)
Date addOneMonth (Date date)
void close ()
void connectToDataBase ()
void createTable ()
void deleteOldData ()
String formDateData (Date date)
String formKindName (String name)
String formUnitsName (DssDataSetFixLength ts)
String formVariableName (String name)
void process ()
void setScenarioIndex ()
void writeData ()
Private Attributes
Connection conn = null
String database
String JDBC_DRIVER = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
int scenarioIndex
String scenarioName =FilePaths.sqlScenarioName
String scenarioTableName ="Scenario"
String slackPrefix ="slack__"
Statement stmt = null
String surplusPrefix ="surplus__"
String tableName = ControlData.sqlGroup
String URL
Detailed Description
Definition at line 21 of file SQLServerRWriterAlt.java.
Constructor & Destructor Documentation
SQLServerRWriterAlt()
wrimsv2.sql.SQLServerRWriterAlt.SQLServerRWriterAlt ()
Definition at line 39 of file SQLServerRWriterAlt.java.
References connectToDataBase().
Member Function Documentation
addOneDay()
Date wrimsv2.sql.SQLServerRWriterAlt.addOneDay (Date date)
Definition at line 229 of file SQLServerRWriterAlt.java.
Referenced by writeData().
addOneMonth()
Date wrimsv2.sql.SQLServerRWriterAlt.addOneMonth (Date date)
Definition at line 217 of file SQLServerRWriterAlt.java.
References wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by writeData().
close()
void wrimsv2.sql.SQLServerRWriterAlt.close ()
Definition at line 237 of file SQLServerRWriterAlt.java.
References conn, and stmt.
Referenced by process().
connectToDataBase()
void wrimsv2.sql.SQLServerRWriterAlt.connectToDataBase ()
Definition at line 54 of file SQLServerRWriterAlt.java.
References conn, database, wrimsv2.components.ControlData.databaseURL, JDBC_DRIVER, wrimsv2.components.ControlData.PASS, stmt, URL, and wrimsv2.components.ControlData.USER.
Referenced by SQLServerRWriterAlt().
createTable()
void wrimsv2.sql.SQLServerRWriterAlt.createTable ()
Definition at line 123 of file SQLServerRWriterAlt.java.
References conn, stmt, and tableName.
Referenced by process().
deleteOldData()
void wrimsv2.sql.SQLServerRWriterAlt.deleteOldData ()
Definition at line 135 of file SQLServerRWriterAlt.java.
References conn, scenarioIndex, stmt, and tableName.
Referenced by process().
formDateData()
String wrimsv2.sql.SQLServerRWriterAlt.formDateData (Date date)
Definition at line 210 of file SQLServerRWriterAlt.java.
References wrimsv2.evaluator.TimeOperation.dayName(), and wrimsv2.evaluator.TimeOperation.monthNameNumeric().
Referenced by writeData().
formKindName()
String wrimsv2.sql.SQLServerRWriterAlt.formKindName (String name)
Definition at line 205 of file SQLServerRWriterAlt.java.
Referenced by writeData().
formUnitsName()
String wrimsv2.sql.SQLServerRWriterAlt.formUnitsName (DssDataSetFixLength ts)
Definition at line 195 of file SQLServerRWriterAlt.java.
References wrimsv2.evaluator.DssDataSetFixLength.getUnits().
Referenced by writeData().
formVariableName()
String wrimsv2.sql.SQLServerRWriterAlt.formVariableName (String name)
Definition at line 200 of file SQLServerRWriterAlt.java.
References wrimsv2.evaluator.DssOperation.getTSName().
Referenced by writeData().
process()
void wrimsv2.sql.SQLServerRWriterAlt.process ()
Definition at line 43 of file SQLServerRWriterAlt.java.
References close(), createTable(), deleteOldData(), scenarioTableName, setScenarioIndex(), tableName, and writeData().
setScenarioIndex()
void wrimsv2.sql.SQLServerRWriterAlt.setScenarioIndex ()
Definition at line 86 of file SQLServerRWriterAlt.java.
References conn, wrimsv2.components.ControlData.partA, scenarioIndex, scenarioName, scenarioTableName, stmt, wrimsv2.components.ControlData.svDvPartF, and tableName.
Referenced by process().
writeData()
void wrimsv2.sql.SQLServerRWriterAlt.writeData ()
Definition at line 147 of file SQLServerRWriterAlt.java.
References addOneDay(), addOneMonth(), conn, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, formDateData(), formKindName(), formUnitsName(), formVariableName(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.DssDataSetFixLength.getKind(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), scenarioIndex, slackPrefix, stmt, surplusPrefix, and tableName.
Referenced by process().
Member Data Documentation
conn
Connection wrimsv2.sql.SQLServerRWriterAlt.conn = null private
Definition at line 30 of file SQLServerRWriterAlt.java.
Referenced by close(), connectToDataBase(), createTable(), deleteOldData(), setScenarioIndex(), and writeData().
database
String wrimsv2.sql.SQLServerRWriterAlt.database private
Definition at line 28 of file SQLServerRWriterAlt.java.
Referenced by connectToDataBase().
JDBC_DRIVER
String wrimsv2.sql.SQLServerRWriterAlt.JDBC_DRIVER = "com.microsoft.sqlserver.jdbc.SQLServerDriver" private
Definition at line 23 of file SQLServerRWriterAlt.java.
Referenced by connectToDataBase().
scenarioIndex
int wrimsv2.sql.SQLServerRWriterAlt.scenarioIndex private
Definition at line 34 of file SQLServerRWriterAlt.java.
Referenced by deleteOldData(), setScenarioIndex(), and writeData().
scenarioName
String wrimsv2.sql.SQLServerRWriterAlt.scenarioName =FilePaths.sqlScenarioName private
Definition at line 33 of file SQLServerRWriterAlt.java.
Referenced by setScenarioIndex().
scenarioTableName
String wrimsv2.sql.SQLServerRWriterAlt.scenarioTableName ="Scenario" private
Definition at line 25 of file SQLServerRWriterAlt.java.
Referenced by process(), and setScenarioIndex().
slackPrefix
String wrimsv2.sql.SQLServerRWriterAlt.slackPrefix ="slack__" private
Definition at line 36 of file SQLServerRWriterAlt.java.
Referenced by writeData().
stmt
Statement wrimsv2.sql.SQLServerRWriterAlt.stmt = null private
Definition at line 31 of file SQLServerRWriterAlt.java.
Referenced by close(), connectToDataBase(), createTable(), deleteOldData(), setScenarioIndex(), and writeData().
surplusPrefix
String wrimsv2.sql.SQLServerRWriterAlt.surplusPrefix ="surplus__" private
Definition at line 37 of file SQLServerRWriterAlt.java.
Referenced by writeData().
tableName
String wrimsv2.sql.SQLServerRWriterAlt.tableName = ControlData.sqlGroup private
Definition at line 24 of file SQLServerRWriterAlt.java.
Referenced by createTable(), deleteOldData(), process(), setScenarioIndex(), and writeData().
URL
String wrimsv2.sql.SQLServerRWriterAlt.URL private
Definition at line 27 of file SQLServerRWriterAlt.java.
Referenced by connectToDataBase().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/sql/SQLServerRWriterAlt.java