Wrims-engine: wrimsv2.commondata.tabledata.IlpData Class Reference
wrimsv2.commondata.tabledata.IlpData Class Reference
Static Public Member Functions
static void addAliasToArray (Map< String, Alias > alias)
static void addConstraintToArray (Map< String, Constraint > constraint)
static void addDvarToArray (Map< String, Dvar > dvar)
static void addFunctionToArray (Map< String, String > function)
static void addLgrToArray (Map< String, LRWeight > lgr)
static void addOutputSvarToArray (ArrayList< String > outputSvar)
static void addRglToArray (Map< String, LRWeight > rgl)
static void addSvarToArray (Map< String, Svar > svar)
static void addWeightToArray (Map< String, String > weight)
static ArrayList< Map< String, Alias > > getAliasArray ()
static ArrayList< Map< String, Constraint > > getConstraintArray ()
static ArrayList< Map< String, Dvar > > getDvarArray ()
static ArrayList< Map< String, String > > getFunctionArray ()
static ArrayList< Map< String, LRWeight > > getLgrArray ()
static ArrayList< ArrayList< String > > getOutputSvarArray ()
static ArrayList< Map< String, LRWeight > > getRglArray ()
static ArrayList< Map< String, Svar > > getSvarArray ()
static ArrayList< Map< String, String > > getWeightArray ()
Static Private Attributes
static ArrayList< Map< String, Alias > > aliasArray = new ArrayList<Map<String, Alias>>()
static ArrayList< Map< String, Constraint > > constraintArray = new ArrayList<Map<String, Constraint>> ()
static ArrayList< Map< String, Dvar > > dvarArray = new ArrayList<Map<String, Dvar>>()
static ArrayList< ArrayList< String > > fileArray = new ArrayList<ArrayList<String>>()
static ArrayList< Map< String, String > > functionArray = new ArrayList<Map<String, String>>()
static ArrayList< Map< String, LRWeight > > lgrArray = new ArrayList<Map<String, LRWeight>>()
static ArrayList< Map< String, ArrayList< String > > > nodeArray = new ArrayList<Map<String, ArrayList<String>>>()
static ArrayList< ArrayList< String > > outputSvarArray = new ArrayList<ArrayList<String>>()
static ArrayList< Map< String, LRWeight > > rglArray = new ArrayList<Map<String, LRWeight>>()
static ArrayList< Map< String, Svar > > svarArray = new ArrayList<Map<String, Svar>>()
static ArrayList< Map< String, String > > weightArray = new ArrayList<Map<String, String>>()
Detailed Description
Definition at line 6 of file IlpData.java.
Member Function Documentation
addAliasToArray()
void wrimsv2.commondata.tabledata.IlpData.addAliasToArray (Map< String, Alias > alias) static
Definition at line 87 of file IlpData.java.
References aliasArray.
addConstraintToArray()
void wrimsv2.commondata.tabledata.IlpData.addConstraintToArray (Map< String, Constraint > constraint) static
Definition at line 55 of file IlpData.java.
References constraintArray.
addDvarToArray()
void wrimsv2.commondata.tabledata.IlpData.addDvarToArray (Map< String, Dvar > dvar) static
Definition at line 23 of file IlpData.java.
References dvarArray.
addFunctionToArray()
void wrimsv2.commondata.tabledata.IlpData.addFunctionToArray (Map< String, String > function) static
Definition at line 79 of file IlpData.java.
References functionArray.
addLgrToArray()
void wrimsv2.commondata.tabledata.IlpData.addLgrToArray (Map< String, LRWeight > lgr) static
Definition at line 63 of file IlpData.java.
References lgrArray.
addOutputSvarToArray()
void wrimsv2.commondata.tabledata.IlpData.addOutputSvarToArray (ArrayList< String > outputSvar) static
Definition at line 39 of file IlpData.java.
References outputSvarArray.
addRglToArray()
void wrimsv2.commondata.tabledata.IlpData.addRglToArray (Map< String, LRWeight > rgl) static
Definition at line 71 of file IlpData.java.
References rglArray.
addSvarToArray()
void wrimsv2.commondata.tabledata.IlpData.addSvarToArray (Map< String, Svar > svar) static
Definition at line 31 of file IlpData.java.
References svarArray.
addWeightToArray()
void wrimsv2.commondata.tabledata.IlpData.addWeightToArray (Map< String, String > weight) static
Definition at line 47 of file IlpData.java.
References weightArray.
getAliasArray()
ArrayList< Map< String, Alias > > wrimsv2.commondata.tabledata.IlpData.getAliasArray () static
Definition at line 83 of file IlpData.java.
References aliasArray.
getConstraintArray()
ArrayList< Map< String, Constraint > > wrimsv2.commondata.tabledata.IlpData.getConstraintArray () static
Definition at line 51 of file IlpData.java.
References constraintArray.
getDvarArray()
ArrayList< Map< String, Dvar > > wrimsv2.commondata.tabledata.IlpData.getDvarArray () static
Definition at line 19 of file IlpData.java.
References dvarArray.
getFunctionArray()
ArrayList< Map< String, String > > wrimsv2.commondata.tabledata.IlpData.getFunctionArray () static
Definition at line 75 of file IlpData.java.
References functionArray.
getLgrArray()
ArrayList< Map< String, LRWeight > > wrimsv2.commondata.tabledata.IlpData.getLgrArray () static
Definition at line 59 of file IlpData.java.
References lgrArray.
getOutputSvarArray()
ArrayList< ArrayList< String > > wrimsv2.commondata.tabledata.IlpData.getOutputSvarArray () static
Definition at line 35 of file IlpData.java.
References outputSvarArray.
getRglArray()
ArrayList< Map< String, LRWeight > > wrimsv2.commondata.tabledata.IlpData.getRglArray () static
Definition at line 67 of file IlpData.java.
References rglArray.
getSvarArray()
ArrayList< Map< String, Svar > > wrimsv2.commondata.tabledata.IlpData.getSvarArray () static
Definition at line 27 of file IlpData.java.
References svarArray.
getWeightArray()
ArrayList< Map< String, String > > wrimsv2.commondata.tabledata.IlpData.getWeightArray () static
Definition at line 43 of file IlpData.java.
References weightArray.
Member Data Documentation
aliasArray
ArrayList<Map<String, Alias> > wrimsv2.commondata.tabledata.IlpData.aliasArray = new ArrayList<Map<String, Alias>>() static private
Definition at line 17 of file IlpData.java.
Referenced by addAliasToArray(), and getAliasArray().
constraintArray
ArrayList<Map<String, Constraint> > wrimsv2.commondata.tabledata.IlpData.constraintArray = new ArrayList<Map<String, Constraint>> () static private
Definition at line 13 of file IlpData.java.
Referenced by addConstraintToArray(), and getConstraintArray().
dvarArray
ArrayList<Map<String, Dvar> > wrimsv2.commondata.tabledata.IlpData.dvarArray = new ArrayList<Map<String, Dvar>>() static private
Definition at line 8 of file IlpData.java.
Referenced by addDvarToArray(), and getDvarArray().
fileArray
ArrayList<ArrayList<String> > wrimsv2.commondata.tabledata.IlpData.fileArray = new ArrayList<ArrayList<String>>() static private
Definition at line 12 of file IlpData.java.
functionArray
ArrayList<Map<String, String> > wrimsv2.commondata.tabledata.IlpData.functionArray = new ArrayList<Map<String, String>>() static private
Definition at line 16 of file IlpData.java.
Referenced by addFunctionToArray(), and getFunctionArray().
lgrArray
ArrayList<Map<String, LRWeight> > wrimsv2.commondata.tabledata.IlpData.lgrArray = new ArrayList<Map<String, LRWeight>>() static private
Definition at line 14 of file IlpData.java.
Referenced by addLgrToArray(), and getLgrArray().
nodeArray
ArrayList<Map<String, ArrayList<String> > > wrimsv2.commondata.tabledata.IlpData.nodeArray = new ArrayList<Map<String, ArrayList<String>>>() static private
Definition at line 7 of file IlpData.java.
outputSvarArray
ArrayList<ArrayList<String> > wrimsv2.commondata.tabledata.IlpData.outputSvarArray = new ArrayList<ArrayList<String>>() static private
Definition at line 10 of file IlpData.java.
Referenced by addOutputSvarToArray(), and getOutputSvarArray().
rglArray
ArrayList<Map<String, LRWeight> > wrimsv2.commondata.tabledata.IlpData.rglArray = new ArrayList<Map<String, LRWeight>>() static private
Definition at line 15 of file IlpData.java.
Referenced by addRglToArray(), and getRglArray().
svarArray
ArrayList<Map<String, Svar> > wrimsv2.commondata.tabledata.IlpData.svarArray = new ArrayList<Map<String, Svar>>() static private
Definition at line 9 of file IlpData.java.
Referenced by addSvarToArray(), and getSvarArray().
weightArray
ArrayList<Map<String, String> > wrimsv2.commondata.tabledata.IlpData.weightArray = new ArrayList<Map<String, String>>() static private
Definition at line 11 of file IlpData.java.
Referenced by addWeightToArray(), and getWeightArray().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/commondata/tabledata/IlpData.java