Wrims-engine: wrimsv2.solver.LPSolveSolver Class Reference
wrimsv2.solver.LPSolveSolver Class Reference
Static Public Member Functions
static void addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName)
static void getSolverInformation (int modelStatus)
static void setDefaultOption ()
static void setLP (String filePath)
static void solve ()
Static Public Attributes
static String configFile = null
static int numberOfRetries = 0
static Map< String, Double > varDoubleMap
Static Private Member Functions
static void assignDvar () throws LpSolveException
static void collectDvar () throws LpSolveException
Static Private Attributes
static String lpFilePath
static ArrayList< String > origcolName
static LpSolve solver
Detailed Description
Definition at line 22 of file LPSolveSolver.java.
Member Function Documentation
addConditionalSlackSurplusToDvarMap()
void wrimsv2.solver.LPSolveSolver.addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName) static
Definition at line 245 of file LPSolveSolver.java.
References wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
assignDvar()
void wrimsv2.solver.LPSolveSolver.assignDvar () throws LpSolveException static private
Definition at line 175 of file LPSolveSolver.java.
References wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.components.ControlData.lpsolve_objective, wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and varDoubleMap.
Referenced by solve().
collectDvar()
void wrimsv2.solver.LPSolveSolver.collectDvar () throws LpSolveException static private
Definition at line 150 of file LPSolveSolver.java.
References origcolName, solver, and varDoubleMap.
Referenced by solve().
getSolverInformation()
void wrimsv2.solver.LPSolveSolver.getSolverInformation (int modelStatus) static
Definition at line 144 of file LPSolveSolver.java.
References wrimsv2.components.Error.addSolvingError(), lpFilePath, and solver.
Referenced by solve().
setDefaultOption()
void wrimsv2.solver.LPSolveSolver.setDefaultOption () static
Definition at line 125 of file LPSolveSolver.java.
References solver.
setLP()
void wrimsv2.solver.LPSolveSolver.setLP (String filePath) static
Definition at line 34 of file LPSolveSolver.java.
References wrimsv2.components.Error.addSolvingError(), configFile, lpFilePath, origcolName, and solver.
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
solve()
void wrimsv2.solver.LPSolveSolver.solve () static
Definition at line 73 of file LPSolveSolver.java.
References wrimsv2.components.Error.addSolvingError(), assignDvar(), collectDvar(), configFile, wrimsv2.components.Error.error_solving, getSolverInformation(), lpFilePath, wrimsv2.components.ControlData.lpsolve_objective, numberOfRetries, and solver.
Referenced by wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), and wrimsv2.components.ControllerDebug.runModelSolvers().
Member Data Documentation
configFile
String wrimsv2.solver.LPSolveSolver.configFile = null static
Definition at line 29 of file LPSolveSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.debug.ChangeSolver.loadLPSolveConfigFile(), setLP(), and solve().
lpFilePath
String wrimsv2.solver.LPSolveSolver.lpFilePath static private
Definition at line 26 of file LPSolveSolver.java.
Referenced by getSolverInformation(), setLP(), and solve().
numberOfRetries
int wrimsv2.solver.LPSolveSolver.numberOfRetries = 0 static
Definition at line 31 of file LPSolveSolver.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), and solve().
origcolName
ArrayList<String> wrimsv2.solver.LPSolveSolver.origcolName static private
Definition at line 27 of file LPSolveSolver.java.
Referenced by collectDvar(), and setLP().
solver
LpSolve wrimsv2.solver.LPSolveSolver.solver static private
Definition at line 25 of file LPSolveSolver.java.
Referenced by collectDvar(), getSolverInformation(), setDefaultOption(), setLP(), and solve().
varDoubleMap
Map<String, Double> wrimsv2.solver.LPSolveSolver.varDoubleMap static
Definition at line 24 of file LPSolveSolver.java.
Referenced by assignDvar(), collectDvar(), and wrimsv2.ilp.ILP.writeDvarValue_LPSOLVE().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/LPSolveSolver.java