Wrims-engine: wrimsv2.solver.XASolver Class Reference
wrimsv2.solver.XASolver Class Reference
Public Member Functions
XASolver ()
void addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName)
void assignDvar ()
void getSolverInformation ()
void setDVars ()
void setWeights ()
Package Attributes
int modelStatus
Private Member Functions
void setConstraints ()
Detailed Description
Definition at line 39 of file XASolver.java.
Constructor & Destructor Documentation
XASolver()
wrimsv2.solver.XASolver.XASolver ()
Definition at line 42 of file XASolver.java.
References assignDvar(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.Error.error_solving, getSolverInformation(), modelStatus, setConstraints(), setDVars(), setWeights(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.components.ControlData.t_xa, and wrimsv2.components.ControlData.xasolver.
Member Function Documentation
addConditionalSlackSurplusToDvarMap()
void wrimsv2.solver.XASolver.addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName)
Definition at line 240 of file XASolver.java.
References wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
Referenced by setConstraints().
assignDvar()
void wrimsv2.solver.XASolver.assignDvar ()
Definition at line 181 of file XASolver.java.
References wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and wrimsv2.components.ControlData.xasolver.
Referenced by XASolver().
getSolverInformation()
void wrimsv2.solver.XASolver.getSolverInformation ()
Definition at line 61 of file XASolver.java.
References wrimsv2.components.Error.addSolvingError(), modelStatus, and wrimsv2.components.ControlData.xasolver.
Referenced by XASolver().
setConstraints()
void wrimsv2.solver.XASolver.setConstraints () private
Definition at line 139 of file XASolver.java.
References addConditionalSlackSurplusToDvarMap(), wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList, wrimsv2.components.ControlData.showRunTimeMessage, and wrimsv2.components.ControlData.xasolver.
Referenced by XASolver().
setDVars()
void wrimsv2.solver.XASolver.setDVars ()
Definition at line 83 of file XASolver.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.Dvar.integer, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.Dvar.upperBoundValue, and wrimsv2.components.ControlData.xasolver.
Referenced by XASolver().
setWeights()
void wrimsv2.solver.XASolver.setWeights ()
Definition at line 111 of file XASolver.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtList, wrimsv2.commondata.wresldata.ModelDataSet.wtTimeArrayList, and wrimsv2.components.ControlData.xasolver.
Referenced by XASolver().
Member Data Documentation
modelStatus
int wrimsv2.solver.XASolver.modelStatus package
Definition at line 40 of file XASolver.java.
Referenced by XASolver(), and getSolverInformation().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/XASolver.java