Wrims-engine: wrimsv2.solver.Cbc0Solver Class Reference
wrimsv2.solver.Cbc0Solver Class Reference
Static Public Member Functions
static void getSolverInformation (int modelStatus)
static void init ()
static void setDefaultOption ()
static void setLP (String filePath)
static void solve ()
static void solve_command ()
Static Public Attributes
static int errorCode
static Map< String, Double > varDoubleMap
Static Private Member Functions
static void assignDvar ()
static void callExe (String arg_lpPath, String arg_soluDir, String arg_soluName, String tolerance) throws IOException, InterruptedException
static void collectDvar ()
Static Private Attributes
static String cbcPath
static String lpFilePath
static String soluPath
static String tolerance1 = "-primalT 1e-008"
static String tolerance2 = "-primalT 1e-007"
Detailed Description
Definition at line 26 of file Cbc0Solver.java.
Member Function Documentation
assignDvar()
void wrimsv2.solver.Cbc0Solver.assignDvar () static private
Definition at line 191 of file Cbc0Solver.java.
References wrimsv2.components.Error.addSolvingError(), wrimsv2.components.ControlData.clp_cbc_objective, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), errorCode, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and varDoubleMap.
Referenced by solve_command().
callExe()
void wrimsv2.solver.Cbc0Solver.callExe (String arg_lpPath, String arg_soluDir, String arg_soluName, String tolerance) throws IOException, InterruptedException static private
Definition at line 130 of file Cbc0Solver.java.
References cbcPath.
Referenced by solve_command().
collectDvar()
void wrimsv2.solver.Cbc0Solver.collectDvar () static private
Definition at line 174 of file Cbc0Solver.java.
References wrimsv2.solver.cbc.FilePassingUtils.varDoubleMap, and varDoubleMap.
Referenced by solve_command().
getSolverInformation()
void wrimsv2.solver.Cbc0Solver.getSolverInformation (int modelStatus) static
Definition at line 184 of file Cbc0Solver.java.
init()
void wrimsv2.solver.Cbc0Solver.init () static
Definition at line 36 of file Cbc0Solver.java.
References cbcPath.
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
setDefaultOption()
void wrimsv2.solver.Cbc0Solver.setDefaultOption () static
Definition at line 180 of file Cbc0Solver.java.
setLP()
void wrimsv2.solver.Cbc0Solver.setLP (String filePath) static
Definition at line 43 of file Cbc0Solver.java.
References lpFilePath, and soluPath.
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
solve()
void wrimsv2.solver.Cbc0Solver.solve () static
Definition at line 55 of file Cbc0Solver.java.
References soluPath, solve_command(), and wrimsv2.ilp.ILP.writeNoteLn().
Referenced by wrimsv2.components.ControllerBatch.runModelILP().
solve_command()
void wrimsv2.solver.Cbc0Solver.solve_command () static
Definition at line 75 of file Cbc0Solver.java.
References wrimsv2.components.Error.addSolvingError(), assignDvar(), callExe(), wrimsv2.components.ControlData.clp_cbc_note, wrimsv2.components.ControlData.clp_cbc_objective, collectDvar(), wrimsv2.components.Error.error_solving, errorCode, lpFilePath, wrimsv2.solver.cbc.FilePassingUtils.objective_value, wrimsv2.solver.cbc.FilePassingUtils.parseReturnFile(), soluPath, wrimsv2.solver.cbc.FilePassingUtils.solverMessage, and tolerance1.
Referenced by solve().
Member Data Documentation
cbcPath
String wrimsv2.solver.Cbc0Solver.cbcPath static private
Definition at line 32 of file Cbc0Solver.java.
Referenced by callExe(), and init().
errorCode
int wrimsv2.solver.Cbc0Solver.errorCode static
Definition at line 28 of file Cbc0Solver.java.
Referenced by assignDvar(), and solve_command().
lpFilePath
String wrimsv2.solver.Cbc0Solver.lpFilePath static private
Definition at line 30 of file Cbc0Solver.java.
Referenced by setLP(), and solve_command().
soluPath
String wrimsv2.solver.Cbc0Solver.soluPath static private
Definition at line 31 of file Cbc0Solver.java.
Referenced by setLP(), solve(), and solve_command().
tolerance1
String wrimsv2.solver.Cbc0Solver.tolerance1 = "-primalT 1e-008" static private
Definition at line 33 of file Cbc0Solver.java.
Referenced by solve_command().
tolerance2
String wrimsv2.solver.Cbc0Solver.tolerance2 = "-primalT 1e-007" static private
Definition at line 34 of file Cbc0Solver.java.
varDoubleMap
Map<String, Double> wrimsv2.solver.Cbc0Solver.varDoubleMap static
Definition at line 29 of file Cbc0Solver.java.
Referenced by assignDvar(), collectDvar(), and wrimsv2.components.ControllerBatch.runModelILP().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/Cbc0Solver.java