Wrims-engine: wrimsv2.components.DebugInterface Class Reference
wrimsv2.components.DebugInterface Class Reference
Public Member Functions
DebugInterface (int requestPort, int eventPort, String args[])
String getAllControlGoalName ()
String getAllGoalFile ()
String getAllGoalString ()
String getAllVariableFiles ()
String getAllVariableString ()
String getCycleValueDetail (String variableName)
String getDataString ()
String getFilterGoal (String fileName)
String getFutureValueDetail (String variableName)
String getGoalInOneFile (String fileFullPath)
String getGoalInOneFileWP (String fileFullPath)
String getTimeseriesDetail (String variableNames)
ArrayList< String > getVariableIfInc (ModelTemp modelTemp)
String getVariableInOneFile (String fileFullPath)
String getVariableInOneFileWP (String fileFullPath)
String getWatch (String vGNameString)
void handleRequest (String request)
boolean modifyCycle (String[] requestParts)
boolean modifyTimeSeries (String[] requestParts)
boolean procFilterFile (String filterName)
boolean saveDvDss (String fileName)
boolean saveInitDss (String fileName)
boolean saveSvDss (String fileName)
void sendEvent (String event) throws IOException
void sendRequest (String request) throws IOException
void setSelectedOutputCycles ()
void setSolverOptions (String[] requestParts)
Static Public Member Functions
static void main (String[] args)
Public Attributes
ArrayList< String > breakFile =new ArrayList<String>()
ArrayList< String > breakIndex =new ArrayList<String>()
DecimalFormat df = new DecimalFormat("#.####")
PrintWriter fileOut
boolean isDebugging =true
Static Public Attributes
static String[] monitorVarNames =new String[0]
static String monitorVarTimeStep =""
Private Member Functions
void initOutputCycleDataToDss ()
void setConditionalBreakpoint (String request)
Private Attributes
String[] allDebugVariables
ControllerDebug controllerDebug
String dataDir ="data"
String[] debugAlias
String[] debugDvar
String[] debugSvar
Socket eventConnection
BufferedReader eventIn
PrintWriter eventOut
ServerSocket eventSocket
ArrayList< String > filterGoalNames =new ArrayList<String>()
Map< String, FilterGoal > filterGoals =new HashMap<String, FilterGoal>()
boolean isStart =false
Socket requestConnection
BufferedReader requestIn
PrintWriter requestOut
ServerSocket requestSocket
FileWriter statusFile
int terminateCode =0
Detailed Description
Definition at line 84 of file DebugInterface.java.
Constructor & Destructor Documentation
DebugInterface()
wrimsv2.components.DebugInterface.DebugInterface (int requestPort, int eventPort, String args[])
Definition at line 112 of file DebugInterface.java.
References controllerDebug, eventConnection, eventIn, eventOut, eventSocket, fileOut, handleRequest(), isDebugging, requestConnection, requestIn, requestOut, requestSocket, statusFile, and terminateCode.
Referenced by main().
Member Function Documentation
getAllControlGoalName()
String wrimsv2.components.DebugInterface.getAllControlGoalName ()
Definition at line 2091 of file DebugInterface.java.
References wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), and wrimsv2.evaluator.EvalExpression.getValue().
Referenced by handleRequest().
getAllGoalFile()
String wrimsv2.components.DebugInterface.getAllGoalFile ()
Definition at line 1882 of file DebugInterface.java.
References dataDir, df, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), and wrimsv2.evaluator.EvalExpression.getValue().
Referenced by handleRequest().
getAllGoalString()
String wrimsv2.components.DebugInterface.getAllGoalString ()
Definition at line 1824 of file DebugInterface.java.
References df, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), and wrimsv2.evaluator.EvalExpression.getValue().
getAllVariableFiles()
String wrimsv2.components.DebugInterface.getAllVariableFiles ()
Definition at line 1644 of file DebugInterface.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, dataDir, df, wrimsv2.commondata.wresldata.Alias.getData(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.commondata.wresldata.Svar.getData(), wrimsv2.commondata.wresldata.Timeseries.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getParameterMap(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Svar.kind, wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtList, and wrimsv2.commondata.wresldata.ModelDataSet.wtTimeArrayList.
Referenced by handleRequest().
getAllVariableString()
String wrimsv2.components.DebugInterface.getAllVariableString ()
Definition at line 1484 of file DebugInterface.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, df, wrimsv2.commondata.wresldata.Alias.getData(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.commondata.wresldata.Svar.getData(), wrimsv2.commondata.wresldata.Timeseries.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getParameterMap(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Svar.kind, wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtList, and wrimsv2.commondata.wresldata.ModelDataSet.wtTimeArrayList.
getCycleValueDetail()
String wrimsv2.components.DebugInterface.getCycleValueDetail (String variableName)
Definition at line 2231 of file DebugInterface.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currTimeStep, df, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getModelTimeStepList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), and wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap().
Referenced by handleRequest().
getDataString()
String wrimsv2.components.DebugInterface.getDataString ()
Definition at line 2372 of file DebugInterface.java.
References allDebugVariables, wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, and wrimsv2.components.ControlData.currSvMap.
Referenced by handleRequest().
getFilterGoal()
String wrimsv2.components.DebugInterface.getFilterGoal (String fileName)
Definition at line 1355 of file DebugInterface.java.
References dataDir, df, filterGoalNames, filterGoals, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.debug.FilterGoal.getTolerance(), wrimsv2.evaluator.EvalExpression.getValue(), and procFilterFile().
Referenced by handleRequest().
getFutureValueDetail()
String wrimsv2.components.DebugInterface.getFutureValueDetail (String variableName)
Definition at line 2180 of file DebugInterface.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, df, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, and wrimsv2.commondata.wresldata.ModelDataSet.svList.
Referenced by handleRequest().
getGoalInOneFile()
String wrimsv2.components.DebugInterface.getGoalInOneFile (String fileFullPath)
Definition at line 1139 of file DebugInterface.java.
References df, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.wreslparser.elements.SimulationDataSet.gList, and wrimsv2.wreslparser.elements.FileParser.parseOneFileForDebug().
Referenced by handleRequest().
getGoalInOneFileWP()
String wrimsv2.components.DebugInterface.getGoalInOneFileWP (String fileFullPath)
Definition at line 1226 of file DebugInterface.java.
References wrimsv2.wreslplus.elements.IfIncItemGroup.conditionList, df, wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.evaluateConditions(), wrimsv2.components.FilePaths.fullMainPath, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupIDList, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupMap, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalComplex_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalSimple_map_list, wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.ParserUtils.parseWreslFile(), and wrimsv2.wreslplus.elements.ParserUtils.parseWreslMain().
Referenced by handleRequest().
getTimeseriesDetail()
String wrimsv2.components.DebugInterface.getTimeseriesDetail (String variableNames)
Definition at line 2129 of file DebugInterface.java.
References controllerDebug, wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, df, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), monitorVarNames, monitorVarTimeStep, wrimsv2.evaluator.DataTimeSeries.svTS, wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by handleRequest().
getVariableIfInc()
ArrayList< String > wrimsv2.components.DebugInterface.getVariableIfInc (ModelTemp modelTemp)
Definition at line 1054 of file DebugInterface.java.
References wrimsv2.wreslplus.elements.IfIncItemGroup.conditionList, wrimsv2.wreslplus.elements.AliasTemp.dependants, wrimsv2.wreslplus.elements.DvarTemp.dependants, wrimsv2.wreslplus.elements.GoalTemp.dependants, wrimsv2.wreslplus.elements.IfIncItemGroup.dependants, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.procedures.ProcIfIncItemGroup.evaluateConditions(), wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupIDList, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupMap, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_alias_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_dvar_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalComplex_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_goalSimple_map_list, wrimsv2.wreslplus.elements.IfIncItemGroup.inc_svar_map_list, and wrimsv2.wreslplus.elements.IfIncItemGroup.inc_timeseries_map_list.
Referenced by getVariableInOneFileWP().
getVariableInOneFile()
String wrimsv2.components.DebugInterface.getVariableInOneFile (String fileFullPath)
Definition at line 754 of file DebugInterface.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, df, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.commondata.wresldata.Alias.getData(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.commondata.wresldata.Svar.getData(), wrimsv2.commondata.wresldata.Timeseries.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Svar.kind, wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.wreslparser.elements.FileParser.parseOneFileForDebug(), wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.wreslparser.elements.SimulationDataSet.tsList, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, and wrimsv2.wreslparser.elements.SimulationDataSet.wtList.
Referenced by handleRequest().
getVariableInOneFileWP()
String wrimsv2.components.DebugInterface.getVariableInOneFileWP (String fileFullPath)
Definition at line 862 of file DebugInterface.java.
References wrimsv2.wreslplus.elements.ModelTemp.asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.wreslplus.elements.ModelTemp.asMap, wrimsv2.wreslplus.elements.procedures.ProcWeight.collectWeightVar(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, df, wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.components.FilePaths.fullMainPath, wrimsv2.commondata.wresldata.Alias.getData(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.commondata.wresldata.Svar.getData(), wrimsv2.commondata.wresldata.Timeseries.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getParameterMap(), getVariableIfInc(), wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Svar.kind, wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.wreslplus.elements.ParserUtils.parseWreslFile(), wrimsv2.wreslplus.elements.ParserUtils.parseWreslMain(), wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.wreslplus.elements.ModelTemp.svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.wreslplus.elements.ModelTemp.svMap, wrimsv2.components.ControlData.timeStep, wrimsv2.wreslplus.elements.ModelTemp.tsList, wrimsv2.commondata.wresldata.ModelDataSet.tsMap, and wrimsv2.wreslplus.elements.ModelTemp.wvList_post.
Referenced by handleRequest().
getWatch()
String wrimsv2.components.DebugInterface.getWatch (String vGNameString)
Definition at line 1953 of file DebugInterface.java.
References wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, df, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.commondata.wresldata.Alias.getData(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.commondata.wresldata.Svar.getData(), wrimsv2.commondata.wresldata.Timeseries.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.commondata.wresldata.StudyDataSet.getParameterMap(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.commondata.wresldata.Svar.kind, wrimsv2.commondata.wresldata.Timeseries.kind, wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, wrimsv2.commondata.wresldata.ModelDataSet.svMap, wrimsv2.components.ControlData.timeStep, and wrimsv2.commondata.wresldata.ModelDataSet.tsMap.
Referenced by handleRequest().
handleRequest()
void wrimsv2.components.DebugInterface.handleRequest (String request)
Definition at line 160 of file DebugInterface.java.
References allDebugVariables, wrimsv2.solver.CbcSolver.cbcHintRelaxPenalty, wrimsv2.solver.CbcSolver.cbcHintTimeMax, wrimsv2.components.Error.clear(), wrimsv2.solver.CbcSolver.close(), controllerDebug, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleDataStartDay, wrimsv2.components.ControlData.cycleDataStartMonth, wrimsv2.components.ControlData.cycleDataStartYear, wrimsv2.components.ControlData.cycleEndDay, wrimsv2.components.ControlData.cycleEndMonth, wrimsv2.components.ControlData.cycleEndYear, wrimsv2.components.ControlData.dvDss, wrimsv2.components.FilePaths.fullDvarDssPath, getAllControlGoalName(), getAllGoalFile(), getAllVariableFiles(), getCycleValueDetail(), getDataString(), getFilterGoal(), getFutureValueDetail(), getGoalInOneFile(), getGoalInOneFileWP(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), getTimeseriesDetail(), getVariableInOneFile(), getVariableInOneFileWP(), getWatch(), initOutputCycleDataToDss(), wrimsv2.solver.CbcSolver.integerT, wrimsv2.solver.CbcSolver.integerT_check, isDebugging, wrimsv2.components.ControlData.isOutputCycle, wrimsv2.components.ControlData.isParseStudy, isStart, wrimsv2.ilp.ILP.loggingUsageMemeory, modifyCycle(), modifyTimeSeries(), wrimsv2.components.ControlData.outputAllCycles, wrimsv2.components.ControlData.printGWFuncCalls, wrimsv2.components.ControlData.relationTolerance, wrimsv2.components.ControlData.resimDate, wrimsv2.components.ControlData.resimDay, wrimsv2.components.ControlData.resimGroundwater, wrimsv2.components.ControlData.resimMonth, wrimsv2.components.ControlData.resimYear, wrimsv2.evaluator.DssOperation.saveDvarData(), saveDvDss(), saveInitDss(), wrimsv2.evaluator.DssOperation.saveInitialData(), saveSvDss(), wrimsv2.components.ControlData.selectedCycleOutput, sendEvent(), sendRequest(), setConditionalBreakpoint(), setSelectedOutputCycles(), setSolverOptions(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.solver.CbcSolver.solve_2_primalT, wrimsv2.solver.CbcSolver.solve_2_primalT_relax, wrimsv2.solver.CbcSolver.solve_whs_primalT, wrimsv2.components.ControlData.solverName, wrimsv2.evaluator.TableSeries.tableSeries, terminateCode, wrimsv2.wreslparser.elements.StudyParser.total_errors, wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus, wrimsv2.components.ControlData.xasolver, and wrimsv2.components.ControlData.zeroTolerance.
Referenced by DebugInterface().
initOutputCycleDataToDss()
void wrimsv2.components.DebugInterface.initOutputCycleDataToDss () private
Definition at line 2579 of file DebugInterface.java.
References wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.components.ControlData.cycleDataStartDay, wrimsv2.components.ControlData.cycleDataStartMonth, wrimsv2.components.ControlData.cycleDataStartYear, and wrimsv2.components.ControlData.isOutputCycle.
Referenced by handleRequest().
main()
void wrimsv2.components.DebugInterface.main (String[] args) static
Definition at line 2597 of file DebugInterface.java.
References DebugInterface().
modifyCycle()
boolean wrimsv2.components.DebugInterface.modifyCycle (String[] requestParts)
Definition at line 2347 of file DebugInterface.java.
References wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), and wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap().
Referenced by handleRequest().
modifyTimeSeries()
boolean wrimsv2.components.DebugInterface.modifyTimeSeries (String[] requestParts)
Definition at line 2318 of file DebugInterface.java.
References wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), monitorVarTimeStep, wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex().
Referenced by handleRequest().
procFilterFile()
boolean wrimsv2.components.DebugInterface.procFilterFile (String filterName)
Definition at line 1446 of file DebugInterface.java.
References filterGoalNames, filterGoals, wrimsv2.debug.FilterGoal.setAlias(), and wrimsv2.debug.FilterGoal.setTolerance().
Referenced by getFilterGoal().
saveDvDss()
boolean wrimsv2.components.DebugInterface.saveDvDss (String fileName)
Definition at line 2535 of file DebugInterface.java.
References wrimsv2.components.ControlData.dvDss, wrimsv2.components.FilePaths.fullDvarDssPath, wrimsv2.evaluator.DssOperation.saveDvarData(), and wrimsv2.evaluator.DssOperation.saveInitialData().
Referenced by handleRequest().
saveInitDss()
boolean wrimsv2.components.DebugInterface.saveInitDss (String fileName)
Definition at line 2501 of file DebugInterface.java.
References wrimsv2.evaluator.DssOperation.saveDVInitialData(), and wrimsv2.evaluator.DssOperation.saveSVInitialData().
Referenced by handleRequest().
saveSvDss()
boolean wrimsv2.components.DebugInterface.saveSvDss (String fileName)
Definition at line 2523 of file DebugInterface.java.
References wrimsv2.evaluator.DssOperation.saveSvarTSData().
Referenced by handleRequest().
sendEvent()
void wrimsv2.components.DebugInterface.sendEvent (String event) throws IOException
Definition at line 743 of file DebugInterface.java.
References eventConnection, and eventOut.
Referenced by handleRequest().
sendRequest()
void wrimsv2.components.DebugInterface.sendRequest (String request) throws IOException
Definition at line 732 of file DebugInterface.java.
References requestConnection, and requestOut.
Referenced by handleRequest().
setConditionalBreakpoint()
void wrimsv2.components.DebugInterface.setConditionalBreakpoint (String request) private
Definition at line 2563 of file DebugInterface.java.
References controllerDebug.
Referenced by handleRequest().
setSelectedOutputCycles()
void wrimsv2.components.DebugInterface.setSelectedOutputCycles ()
Definition at line 2592 of file DebugInterface.java.
References wrimsv2.components.ControlData.selectedCycleOutput, and wrimsv2.components.ControlData.selectedCycles.
Referenced by handleRequest().
setSolverOptions()
void wrimsv2.components.DebugInterface.setSolverOptions (String[] requestParts)
Definition at line 2393 of file DebugInterface.java.
References wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.components.ControlData.cbcCheckIntErr, wrimsv2.solver.CbcSolver.cbcLibName, wrimsv2.tools.Warmstart.collectIntegerDV_2(), wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.solver.SetXALog.disableXALog(), wrimsv2.solver.SetXALog.enableXALog(), wrimsv2.ilp.ILP.getIlpDir(), wrimsv2.solver.CbcSolver.init(), wrimsv2.solver.Gurobi.GurobiSolver.initialize(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.debug.ChangeSolver.loadLPSolveConfigFile(), wrimsv2.ilp.ILP.logging, wrimsv2.ilp.ILP.loggingAllCycles, wrimsv2.ilp.ILP.loggingCplexLp, wrimsv2.ilp.ILP.loggingLpSolve, wrimsv2.ilp.ILP.loggingVariableValue, wrimsv2.components.ControlData.solverName, and wrimsv2.components.ControlData.useCbcWarmStart.
Referenced by handleRequest().
Member Data Documentation
allDebugVariables
String [] wrimsv2.components.DebugInterface.allDebugVariables private
Definition at line 103 of file DebugInterface.java.
Referenced by getDataString(), and handleRequest().
breakFile
ArrayList<String> wrimsv2.components.DebugInterface.breakFile =new ArrayList<String>()
Definition at line 94 of file DebugInterface.java.
breakIndex
ArrayList<String> wrimsv2.components.DebugInterface.breakIndex =new ArrayList<String>()
Definition at line 93 of file DebugInterface.java.
controllerDebug
ControllerDebug wrimsv2.components.DebugInterface.controllerDebug private
Definition at line 96 of file DebugInterface.java.
Referenced by DebugInterface(), getTimeseriesDetail(), handleRequest(), and setConditionalBreakpoint().
dataDir
String wrimsv2.components.DebugInterface.dataDir ="data" private
Definition at line 109 of file DebugInterface.java.
Referenced by getAllGoalFile(), getAllVariableFiles(), and getFilterGoal().
debugAlias
String [] wrimsv2.components.DebugInterface.debugAlias private
Definition at line 102 of file DebugInterface.java.
debugDvar
String [] wrimsv2.components.DebugInterface.debugDvar private
Definition at line 101 of file DebugInterface.java.
debugSvar
String [] wrimsv2.components.DebugInterface.debugSvar private
Definition at line 100 of file DebugInterface.java.
df
DecimalFormat wrimsv2.components.DebugInterface.df = new DecimalFormat("#.####")
Definition at line 106 of file DebugInterface.java.
Referenced by getAllGoalFile(), getAllGoalString(), getAllVariableFiles(), getAllVariableString(), getCycleValueDetail(), getFilterGoal(), getFutureValueDetail(), getGoalInOneFile(), getGoalInOneFileWP(), getTimeseriesDetail(), getVariableInOneFile(), getVariableInOneFileWP(), and getWatch().
eventConnection
Socket wrimsv2.components.DebugInterface.eventConnection private
Definition at line 88 of file DebugInterface.java.
Referenced by DebugInterface(), and sendEvent().
eventIn
BufferedReader wrimsv2.components.DebugInterface.eventIn private
Definition at line 92 of file DebugInterface.java.
Referenced by DebugInterface().
eventOut
PrintWriter wrimsv2.components.DebugInterface.eventOut private
Definition at line 91 of file DebugInterface.java.
Referenced by DebugInterface(), and sendEvent().
eventSocket
ServerSocket wrimsv2.components.DebugInterface.eventSocket private
Definition at line 87 of file DebugInterface.java.
Referenced by DebugInterface().
fileOut
PrintWriter wrimsv2.components.DebugInterface.fileOut
Definition at line 98 of file DebugInterface.java.
Referenced by DebugInterface().
filterGoalNames
ArrayList<String> wrimsv2.components.DebugInterface.filterGoalNames =new ArrayList<String>() private
Definition at line 104 of file DebugInterface.java.
Referenced by getFilterGoal(), and procFilterFile().
filterGoals
Map<String, FilterGoal> wrimsv2.components.DebugInterface.filterGoals =new HashMap<String, FilterGoal>() private
Definition at line 105 of file DebugInterface.java.
Referenced by getFilterGoal(), and procFilterFile().
isDebugging
boolean wrimsv2.components.DebugInterface.isDebugging =true
Definition at line 95 of file DebugInterface.java.
Referenced by DebugInterface(), and handleRequest().
isStart
boolean wrimsv2.components.DebugInterface.isStart =false private
Definition at line 99 of file DebugInterface.java.
Referenced by handleRequest().
monitorVarNames
String [] wrimsv2.components.DebugInterface.monitorVarNames =new String[0] static
Definition at line 107 of file DebugInterface.java.
Referenced by getTimeseriesDetail().
monitorVarTimeStep
String wrimsv2.components.DebugInterface.monitorVarTimeStep ="" static
Definition at line 108 of file DebugInterface.java.
Referenced by getTimeseriesDetail(), and modifyTimeSeries().
requestConnection
Socket wrimsv2.components.DebugInterface.requestConnection private
Definition at line 86 of file DebugInterface.java.
Referenced by DebugInterface(), and sendRequest().
requestIn
BufferedReader wrimsv2.components.DebugInterface.requestIn private
Definition at line 90 of file DebugInterface.java.
Referenced by DebugInterface().
requestOut
PrintWriter wrimsv2.components.DebugInterface.requestOut private
Definition at line 89 of file DebugInterface.java.
Referenced by DebugInterface(), and sendRequest().
requestSocket
ServerSocket wrimsv2.components.DebugInterface.requestSocket private
Definition at line 85 of file DebugInterface.java.
Referenced by DebugInterface().
statusFile
FileWriter wrimsv2.components.DebugInterface.statusFile private
Definition at line 97 of file DebugInterface.java.
Referenced by DebugInterface().
terminateCode
int wrimsv2.components.DebugInterface.terminateCode =0 private
Definition at line 110 of file DebugInterface.java.
Referenced by DebugInterface(), and handleRequest().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/components/DebugInterface.java