Wrims-engine: wrimsv2.wreslparser.elements.StudyUtils Class Reference
wrimsv2.wreslparser.elements.StudyUtils Class Reference
Static Public Member Functions
static StudyDataSet checkStudy (String inMainWreslPath) throws IOException
static StudyDataSet checkStudy (String inMainWreslPath, String csvFolderName, boolean sendAliasToDvar) throws IOException
static StudyDataSet checkStudy (String inMainWreslPath, String logFileName, String csvFolderName, boolean sendAliasToDvar) throws IOException
static void compileObject (String inMainWreslPath, StudyDataSet sds)
static StudyDataSet compileStudy (String inMainWreslPath) throws IOException
static StudyDataSet loadObject (String objFilePath)
static void registerClasses (Kryo kryo)
static void reset ()
static void writeObj (StudyDataSet sds, String objFilePath)
Static Public Attributes
static boolean compileOnly =false
static int config_errors = 0
static String configDir = ""
static String configFileCanonicalPath = ""
static String configFileName = "default"
static String configFilePath = ""
static boolean loadParserData =false
static boolean parserCheckVarUndefined = true
static String parserDataPath = ""
static boolean showCompileLog = false
static int total_errors = 0
static boolean useWreslPlus = false
Private Member Functions
StudyUtils ()
Static Private Member Functions
static StudyDataSet parseWresl (File validatedMainWreslFile, boolean sendAliasToDvar) throws RecognitionException, IOException
static StudyDataSet parseWreslPlus (File validatedMainWreslFile) throws RecognitionException, IOException
static StudyDataSet readObj (String objFilePath)
static File sanityCheck (String inMainWreslPath) throws IOException
Detailed Description
Definition at line 36 of file StudyUtils.java.
Constructor & Destructor Documentation
StudyUtils()
wrimsv2.wreslparser.elements.StudyUtils.StudyUtils () private
Definition at line 52 of file StudyUtils.java.
Referenced by checkStudy(), and parseWreslPlus().
Member Function Documentation
checkStudy() [1/3]
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.checkStudy (String inMainWreslPath) throws IOException static
Definition at line 71 of file StudyUtils.java.
References checkStudy(), wrimsv2.components.FilePaths.mainFile, wrimsv2.components.ControlData.outputWreslCSV, and wrimsv2.components.ControlData.sendAliasToDvar.
Referenced by wrimsv2.debug.Compile.checkStudy(), checkStudy(), checkStudy(), compileStudy(), main.WreslCheck.main(), main.WreslCheckGUI.main(), wrimsv2.components.Controller.parse(), wrimsv2.components.ControllerBatch.parse(), wrimsv2.components.ControllerDebug.parse(), and wrimsv2.components.ControllerSG.parse().
checkStudy() [2/3]
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.checkStudy (String inMainWreslPath, String csvFolderName, boolean sendAliasToDvar) throws IOException static
Definition at line 89 of file StudyUtils.java.
References checkStudy(), and wrimsv2.components.FilePaths.mainFile.
checkStudy() [3/3]
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.checkStudy (String inMainWreslPath, String logFileName, String csvFolderName, boolean sendAliasToDvar) throws IOException static
Definition at line 99 of file StudyUtils.java.
References StudyUtils(), wrimsv2.components.ControlData.cbc_debug_routeCbc, wrimsv2.components.ControlData.cbc_debug_routeXA, wrimsv2.components.ControlData.cbcCheckIntErr, wrimsv2.wreslparser.elements.LogUtils.closeLogFile(), wrimsv2.tools.Warmstart.collectIntegerDV_2(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.components.FilePaths.fullMainPath, parseWresl(), parseWreslPlus(), sanityCheck(), wrimsv2.wreslparser.elements.LogUtils.setLogFile(), wrimsv2.components.ControlData.solverName, wrimsv2.wreslparser.elements.WriteCSV.study(), wrimsv2.wreslparser.elements.LogUtils.titleMsg(), wrimsv2.wreslparser.elements.StudyParser.total_errors, total_errors, wrimsv2.components.ControlData.useCbcWarmStart, useWreslPlus, and wrimsv2.commondata.wresldata.Param.wreslChekerName.
compileObject()
void wrimsv2.wreslparser.elements.StudyUtils.compileObject (String inMainWreslPath, StudyDataSet sds) static
Definition at line 158 of file StudyUtils.java.
References wrimsv2.wreslparser.elements.LogUtils.importantMsg(), wrimsv2.components.FilePaths.mainFile, and writeObj().
compileStudy()
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.compileStudy (String inMainWreslPath) throws IOException static
Definition at line 63 of file StudyUtils.java.
References checkStudy(), compileOnly, and wrimsv2.evaluator.WeightEval.procWt().
Referenced by wrimsv2.components.ControllerBatch.parse().
loadObject()
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.loadObject (String objFilePath) static
Definition at line 174 of file StudyUtils.java.
References readObj().
Referenced by wrimsv2.components.Controller.parse(), wrimsv2.components.ControllerBatch.parse(), wrimsv2.components.ControllerDebug.parse(), and wrimsv2.components.ControllerSG.parse().
parseWresl()
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.parseWresl (File validatedMainWreslFile, boolean sendAliasToDvar) throws RecognitionException, IOException static private
Definition at line 203 of file StudyUtils.java.
References wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles(), wrimsv2.wreslplus.elements.VarCycleIndex.clearVarCycleIndexList(), wrimsv2.wreslparser.elements.StudyParser.parseModels(), wrimsv2.wreslparser.elements.StudyParser.processMainFileIntoStudyConfig(), wrimsv2.wreslparser.elements.StudyParser.reset(), wrimsv2.wreslparser.elements.StudyParser.total_errors, total_errors, and wrimsv2.wreslparser.elements.StudyParser.writeWreslData().
Referenced by checkStudy().
parseWreslPlus()
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.parseWreslPlus (File validatedMainWreslFile) throws RecognitionException, IOException static private
Definition at line 232 of file StudyUtils.java.
References StudyUtils(), wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), wrimsv2.wreslplus.elements.procedures.ToWreslData.convertStudy(), and showCompileLog.
Referenced by checkStudy().
readObj()
StudyDataSet wrimsv2.wreslparser.elements.StudyUtils.readObj (String objFilePath) static private
Definition at line 293 of file StudyUtils.java.
References registerClasses().
Referenced by loadObject().
registerClasses()
void wrimsv2.wreslparser.elements.StudyUtils.registerClasses (Kryo kryo) static
Definition at line 327 of file StudyUtils.java.
Referenced by readObj(), and writeObj().
reset()
void wrimsv2.wreslparser.elements.StudyUtils.reset () static
Definition at line 56 of file StudyUtils.java.
References config_errors, wrimsv2.wreslparser.elements.StudyParser.reset(), and total_errors.
sanityCheck()
File wrimsv2.wreslparser.elements.StudyUtils.sanityCheck (String inMainWreslPath) throws IOException static private
Definition at line 182 of file StudyUtils.java.
Referenced by checkStudy().
writeObj()
void wrimsv2.wreslparser.elements.StudyUtils.writeObj (StudyDataSet sds, String objFilePath) static
Definition at line 263 of file StudyUtils.java.
References registerClasses().
Referenced by wrimsv2.components.Controller.Controller(), wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.components.ControllerSG.ControllerSG(), wrimsv2.components.ControllerSG.ControllerSG(), compileObject(), and wrimsv2.components.ControllerDebug.run().
Member Data Documentation
compileOnly
boolean wrimsv2.wreslparser.elements.StudyUtils.compileOnly =false static
Definition at line 41 of file StudyUtils.java.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), compileStudy(), wrimsv2.config.ConfigUtils.loadArgs(), and wrimsv2.components.ControllerBatch.parse().
config_errors
int wrimsv2.wreslparser.elements.StudyUtils.config_errors = 0 static
Definition at line 38 of file StudyUtils.java.
Referenced by reset().
configDir
String wrimsv2.wreslparser.elements.StudyUtils.configDir = "" static
Definition at line 46 of file StudyUtils.java.
Referenced by wrimsv2.config.ConfigUtils.checkConfigFile(), wrimsv2.config.ConfigUtils.loadConfig(), and wrimsv2.debug.ChangeSolver.loadLPSolveConfigFile().
configFileCanonicalPath
String wrimsv2.wreslparser.elements.StudyUtils.configFileCanonicalPath = "" static
Definition at line 45 of file StudyUtils.java.
Referenced by wrimsv2.config.ConfigUtils.checkConfigFile().
configFileName
String wrimsv2.wreslparser.elements.StudyUtils.configFileName = "default" static
Definition at line 47 of file StudyUtils.java.
Referenced by wrimsv2.components.Controller.Controller(), wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.components.ControllerSG.ControllerSG(), wrimsv2.components.ControllerSG.ControllerSG(), wrimsv2.ilp.ILP.getIlpDir(), wrimsv2.ilp.ILP.initializeIlp(), wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.wreslplus.elements.Tools.quickLog(), wrimsv2.components.ControllerDebug.run(), wrimsv2.components.ControllerBatch.runModelGurobiTest(), and wrimsv2.components.Error.writeErrorLog().
configFilePath
String wrimsv2.wreslparser.elements.StudyUtils.configFilePath = "" static
Definition at line 44 of file StudyUtils.java.
Referenced by wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.config.ConfigUtils.loadArgs(), wrimsv2.tools.InfeasibilityAnalysis.procIfsFile(), wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.PreRunModel.setGenTableDir().
loadParserData
boolean wrimsv2.wreslparser.elements.StudyUtils.loadParserData =false static
Definition at line 40 of file StudyUtils.java.
Referenced by wrimsv2.components.Controller.Controller(), wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.components.ControllerSG.ControllerSG(), wrimsv2.components.ControllerSG.ControllerSG(), wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.components.Controller.parse(), wrimsv2.components.ControllerBatch.parse(), wrimsv2.components.ControllerDebug.parse(), wrimsv2.components.ControllerSG.parse(), and wrimsv2.components.ControllerDebug.run().
parserCheckVarUndefined
boolean wrimsv2.wreslparser.elements.StudyUtils.parserCheckVarUndefined = true static
Definition at line 49 of file StudyUtils.java.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and wrimsv2.config.ConfigUtils.loadConfig().
parserDataPath
String wrimsv2.wreslparser.elements.StudyUtils.parserDataPath = "" static
Definition at line 43 of file StudyUtils.java.
Referenced by wrimsv2.config.ConfigUtils.loadConfig(), wrimsv2.components.Controller.parse(), wrimsv2.components.ControllerBatch.parse(), wrimsv2.components.ControllerDebug.parse(), and wrimsv2.components.ControllerSG.parse().
showCompileLog
boolean wrimsv2.wreslparser.elements.StudyUtils.showCompileLog = false static
Definition at line 50 of file StudyUtils.java.
Referenced by parseWreslPlus().
total_errors
int wrimsv2.wreslparser.elements.StudyUtils.total_errors = 0 static
Definition at line 39 of file StudyUtils.java.
Referenced by wrimsv2.components.Controller.Controller(), wrimsv2.components.Controller.Controller(), wrimsv2.components.ControllerBatch.ControllerBatch(), wrimsv2.components.ControllerSG.ControllerSG(), wrimsv2.components.ControllerSG.ControllerSG(), checkStudy(), main.WreslCheckGUI.main(), parseWresl(), and reset().
useWreslPlus
boolean wrimsv2.wreslparser.elements.StudyUtils.useWreslPlus = false static
Definition at line 48 of file StudyUtils.java.
Referenced by wrimsv2.debug.Compile.checkStudy(), checkStudy(), wrimsv2.components.DebugInterface.handleRequest(), wrimsv2.config.ConfigUtils.loadArgs(), wrimsv2.config.ConfigUtils.loadConfig(), main.WreslCheckGUI.main(), wrimsv2.tools.InfeasibilityAnalysis.procIfsSelFiles(), wrimsv2.launch.LaunchConfiguration.setConfig(), and wrimsv2.components.ControllerSG.setControlData().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/StudyUtils.java