Wrims-engine: wrimsv2.solver.ortools.OrToolsSolver Class Reference
wrimsv2.solver.ortools.OrToolsSolver Class Reference
Public Member Functions
OrToolsSolver (String mpSolverType)
MPModel createModel ()
void delete ()
void refreshObjFunc (LinkedHashMap< String, Double > newObjFunc)
void run ()
void setModel (MPModel m)
void setVerbose (int verbosity)
int solve ()
int solve (MPModel m)
Static Public Member Functions
static void initialize ()
Public Attributes
MPModel model
LinkedHashMap< String, Double > solution = null
MPSolver solver
Private Attributes
Map< String, MPConstraint > _solverConstraintMap = null
Map< String, MPVariable > _solverVarMap = null
int verbosity = 0
Detailed Description
Definition at line 15 of file OrToolsSolver.java.
Constructor & Destructor Documentation
OrToolsSolver()
wrimsv2.solver.ortools.OrToolsSolver.OrToolsSolver (String mpSolverType)
Definition at line 28 of file OrToolsSolver.java.
References solver, and verbosity.
Member Function Documentation
createModel()
MPModel wrimsv2.solver.ortools.OrToolsSolver.createModel ()
Definition at line 166 of file OrToolsSolver.java.
References model, wrimsv2.solver.ortools.Misc.setConstraints(), wrimsv2.solver.ortools.Misc.setDVars(), and wrimsv2.solver.ortools.Misc.setWeights().
Referenced by wrimsv2.components.ControllerBatch.runModelOrTools().
delete()
void wrimsv2.solver.ortools.OrToolsSolver.delete ()
Definition at line 159 of file OrToolsSolver.java.
References solver.
Referenced by wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateBaseModel(), and wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateOriginalModel().
initialize()
void wrimsv2.solver.ortools.OrToolsSolver.initialize () static
Definition at line 47 of file OrToolsSolver.java.
Referenced by wrimsv2.tools.solutionRangeFinder.Detector.main(), wrimsv2.tools.solutionRangeFinder.Main.main(), and wrimsv2.components.ControllerBatch.runModelOrTools().
refreshObjFunc()
void wrimsv2.solver.ortools.OrToolsSolver.refreshObjFunc (LinkedHashMap< String, Double > newObjFunc)
Definition at line 100 of file OrToolsSolver.java.
References _solverVarMap, and solver.
Referenced by wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go().
run()
void wrimsv2.solver.ortools.OrToolsSolver.run ()
Definition at line 178 of file OrToolsSolver.java.
References _solverVarMap, wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.ortools.Misc.getSolverInformation(), model, solution, solve(), and verbosity.
Referenced by wrimsv2.components.ControllerBatch.runModelOrTools().
setModel()
void wrimsv2.solver.ortools.OrToolsSolver.setModel (MPModel m)
Definition at line 53 of file OrToolsSolver.java.
References _solverConstraintMap, _solverVarMap, wrimsv2.solver.mpmodel.MPModel.constraintLhs, wrimsv2.solver.mpmodel.MPModel.constraintRhs, wrimsv2.commondata.wresldata.Param.inf, model, wrimsv2.solver.mpmodel.MPModel.objFunction, solver, wrimsv2.solver.mpmodel.MPModel.varMap_integer, and wrimsv2.solver.mpmodel.MPModel.varMap_number.
Referenced by wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), and solve().
setVerbose()
void wrimsv2.solver.ortools.OrToolsSolver.setVerbose (int verbosity)
Definition at line 113 of file OrToolsSolver.java.
References verbosity.
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateBaseModel(), and wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateOriginalModel().
solve() [1/2]
int wrimsv2.solver.ortools.OrToolsSolver.solve ()
Definition at line 126 of file OrToolsSolver.java.
References _solverVarMap, solution, solver, and verbosity.
Referenced by run(), and solve().
solve() [2/2]
int wrimsv2.solver.ortools.OrToolsSolver.solve (MPModel m)
Definition at line 118 of file OrToolsSolver.java.
References setModel(), and solve().
Referenced by wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateBaseModel(), and wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateOriginalModel().
Member Data Documentation
_solverConstraintMap
Map<String, MPConstraint> wrimsv2.solver.ortools.OrToolsSolver._solverConstraintMap = null private
Definition at line 23 of file OrToolsSolver.java.
Referenced by setModel().
_solverVarMap
Map<String, MPVariable> wrimsv2.solver.ortools.OrToolsSolver._solverVarMap = null private
Definition at line 22 of file OrToolsSolver.java.
Referenced by refreshObjFunc(), run(), setModel(), and solve().
model
MPModel wrimsv2.solver.ortools.OrToolsSolver.model
Definition at line 21 of file OrToolsSolver.java.
Referenced by createModel(), wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), run(), and setModel().
solution
LinkedHashMap<String, Double> wrimsv2.solver.ortools.OrToolsSolver.solution = null
Definition at line 24 of file OrToolsSolver.java.
Referenced by wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), run(), solve(), wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateBaseModel(), wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateOriginalModel(), and wrimsv2.ilp.ILP.writeDvarValue_OrTools().
solver
MPSolver wrimsv2.solver.ortools.OrToolsSolver.solver
Definition at line 20 of file OrToolsSolver.java.
Referenced by OrToolsSolver(), delete(), wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go(), refreshObjFunc(), setModel(), solve(), wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateBaseModel(), wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.validateOriginalModel(), and wrimsv2.ilp.ILP.writeObjValue_OrTools().
verbosity
int wrimsv2.solver.ortools.OrToolsSolver.verbosity = 0 private
Definition at line 25 of file OrToolsSolver.java.
Referenced by OrToolsSolver(), run(), setVerbose(), and solve().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/ortools/OrToolsSolver.java