Wrims-engine: wrimsv2.evaluator.DataTimeSeries Class Reference
wrimsv2.evaluator.DataTimeSeries Class Reference
Static Public Member Functions
static void saveDataToTimeSeries (String dvName, String entryNameTS, double value, Dvar dvar)
static void saveDataToTimeSeries (String entryNameTS, double value, Dvar dvar, int offset)
Static Public Attributes
static HashMap< String, DssDataSet > dvAliasInit = new HashMap<String, DssDataSet> ()
static HashMap< String, DssDataSetFixLength > dvAliasTS = new HashMap<String, DssDataSetFixLength> ()
static ArrayList< HashMap< String, DssDataSetFixLength > > dvAliasTSCycles = new ArrayList<HashMap<String, DssDataSetFixLength>> ()
static ArrayList< String > lookInitDss =new ArrayList<String>()
static ArrayList< String > lookSvDss =new ArrayList<String>()
static HashMap< String, DssDataSet > svInit = new HashMap<String, DssDataSet> ()
static HashMap< String, DssDataSet > svTS = new HashMap<String, DssDataSet> ()
Detailed Description
Definition at line 10 of file DataTimeSeries.java.
Member Function Documentation
saveDataToTimeSeries() [1/2]
void wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries (String dvName, String entryNameTS, double value, Dvar dvar) static
Definition at line 19 of file DataTimeSeries.java.
References wrimsv2.evaluator.DssOperation.entryNameTS(), saveDataToTimeSeries(), and wrimsv2.components.ControlData.timeStep.
Referenced by wrimsv2.solver.Cbc0Solver.assignDvar(), wrimsv2.solver.CbcSolver.assignDvar(), wrimsv2.solver.Clp0Solver.assignDvar(), wrimsv2.solver.ClpSolver.assignDvar(), wrimsv2.solver.Gurobi.GurobiSolver.assignDvar(), wrimsv2.solver.LPSolveSolver.assignDvar(), wrimsv2.solver.ortools.Misc.assignDvar(), wrimsv2.solver.XASolver.assignDvar(), and saveDataToTimeSeries().
saveDataToTimeSeries() [2/2]
void wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries (String entryNameTS, double value, Dvar dvar, int offset) static
Definition at line 34 of file DataTimeSeries.java.
References wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, dvAliasTS, dvAliasTSCycles, wrimsv2.evaluator.DssDataSetFixLength.getData(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.commondata.wresldata.Dvar.kind, wrimsv2.components.ControlData.memStartDate, wrimsv2.components.ControlData.partE, wrimsv2.evaluator.DssDataSetFixLength.setKind(), wrimsv2.evaluator.DssDataSetFixLength.setStartTime(), wrimsv2.evaluator.DssDataSetFixLength.setTimeStep(), wrimsv2.evaluator.DssDataSetFixLength.setUnits(), wrimsv2.components.ControlData.totalTimeStep, and wrimsv2.commondata.wresldata.Dvar.units.
Member Data Documentation
dvAliasInit
HashMap<String, DssDataSet> wrimsv2.evaluator.DataTimeSeries.dvAliasInit = new HashMap<String, DssDataSet> () static
Definition at line 15 of file DataTimeSeries.java.
Referenced by wrimsv2.sql.DssToSQLDatabase.dssReader(), wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.evaluator.DssOperation.saveDVInitialData(), wrimsv2.evaluator.DssOperation.saveInitialData(), and wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS().
dvAliasTS
HashMap<String, DssDataSetFixLength> wrimsv2.evaluator.DataTimeSeries.dvAliasTS = new HashMap<String, DssDataSetFixLength> () static
Definition at line 12 of file DataTimeSeries.java.
Referenced by wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.sql.MySQLCWriter.createTables(), wrimsv2.sql.DssToSQLDatabase.dssReader(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.Evaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.PreRunModel.initialDvarAliasTS(), wrimsv2.components.DebugInterface.modifyTimeSeries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.Evaluation.pastTSFV(), wrimsv2.evaluator.ValueEvaluation.pastTSFV(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), saveDataToTimeSeries(), wrimsv2.evaluator.DssOperation.saveDvarData(), wrimsv2.evaluator.DssOperation.shiftDvAliasData(), wrimsv2.components.ControllerDebug.updateVarMonitor(), wrimsv2.sql.MySQLCWriter.writeDailyData(), wrimsv2.hdf5.HDF5Writer.writeDailyTimestepDvarAlias(), wrimsv2.sql.MySQLRWriterAlt.writeData(), wrimsv2.sql.SQLServerRWriterAlt.writeData(), wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(), wrimsv2.sql.MySQLCWriter.writeMonthlyData(), wrimsv2.hdf5.HDF5Writer.writeMonthlyTimestepDvarAlias(), and wrimsv2.hdf5.HDF5Writer.writeMonthlyTimestepDvarAlias_deprecated().
dvAliasTSCycles
ArrayList<HashMap<String, DssDataSetFixLength> > wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles = new ArrayList<HashMap<String, DssDataSetFixLength>> () static
Definition at line 13 of file DataTimeSeries.java.
Referenced by wrimsv2.evaluator.Evaluation.dvarAliasCycleTimeSeries(), wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries(), wrimsv2.components.DebugInterface.getCycleValueDetail(), wrimsv2.components.PreRunModel.initialDvarAliasTS(), wrimsv2.commondata.wresldata.ModelDataSet.processAlias(), saveDataToTimeSeries(), wrimsv2.evaluator.DssOperation.saveDvarCycleData(), wrimsv2.evaluator.DssOperation.shiftDvAliasCycleData(), wrimsv2.hdf5.HDF5Writer.writeCyclesDvAlias(), and wrimsv2.evaluator.DssOperation.writeDVAliasCycleDataToDSS().
lookInitDss
ArrayList<String> wrimsv2.evaluator.DataTimeSeries.lookInitDss =new ArrayList<String>() static
Definition at line 17 of file DataTimeSeries.java.
Referenced by wrimsv2.evaluator.Evaluation.svarTimeSeries(), and wrimsv2.evaluator.ValueEvaluation.svarTimeSeries().
lookSvDss
ArrayList<String> wrimsv2.evaluator.DataTimeSeries.lookSvDss =new ArrayList<String>() static
Definition at line 16 of file DataTimeSeries.java.
Referenced by wrimsv2.hdf5.HDF5Reader.assignTimeseries(), wrimsv2.components.PreRunModel.readTimeseries(), and wrimsv2.debug.ReLoadSVDss.readTimeseries().
svInit
HashMap<String, DssDataSet> wrimsv2.evaluator.DataTimeSeries.svInit = new HashMap<String, DssDataSet> () static
Definition at line 14 of file DataTimeSeries.java.
Referenced by wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveSVInitialData(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), and wrimsv2.evaluator.ValueEvaluation.svarTimeSeries().
svTS
HashMap<String, DssDataSet> wrimsv2.evaluator.DataTimeSeries.svTS = new HashMap<String, DssDataSet> () static
Definition at line 11 of file DataTimeSeries.java.
Referenced by wrimsv2.sql.DssToSQLDatabase.dssReader(), wrimsv2.evaluator.Evaluation.exceedance(), wrimsv2.evaluator.ValueEvaluation.exceedance(), wrimsv2.evaluator.Evaluation.exceedance_tsi(), wrimsv2.evaluator.ValueEvaluation.exceedance_tsi(), wrimsv2.evaluator.DssOperation.getSVTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVTimeseries(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.DebugInterface.modifyTimeSeries(), wrimsv2.evaluator.CsvOperation.ouputCSV(), wrimsv2.evaluator.DssOperation.saveSvarTSData(), wrimsv2.evaluator.Evaluation.svarTimeSeries(), wrimsv2.evaluator.ValueEvaluation.svarTimeSeries(), and wrimsv2.components.ControllerDebug.updateVarMonitor().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/DataTimeSeries.java