Wrims-engine: wrimsv2.sql.SQLServerRWriter Class Reference
wrimsv2.sql.SQLServerRWriter Class Reference
Public Member Functions
SQLServerRWriter ()
void close ()
void connectToDataBase ()
void createCSV ()
void createIndex ()
void createScenarioCSV ()
void createTable ()
void deleteOldData ()
void process ()
void setScenarioIndex ()
boolean transferCSV ()
void writeData ()
Private Attributes
Connection conn = null
String csvLocalPath
String csvRemotePath
String database
String host
String JDBC_DRIVER = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
int scenarioIndex
String scenarioName =FilePaths.sqlScenarioName
String scenarioTableName ="Scenario"
Statement stmt = null
String tableName = ControlData.sqlGroup
String URL
Detailed Description
Definition at line 31 of file SQLServerRWriter.java.
Constructor & Destructor Documentation
SQLServerRWriter()
wrimsv2.sql.SQLServerRWriter.SQLServerRWriter ()
Definition at line 50 of file SQLServerRWriter.java.
References connectToDataBase().
Member Function Documentation
close()
void wrimsv2.sql.SQLServerRWriter.close ()
Definition at line 234 of file SQLServerRWriter.java.
References conn, and stmt.
Referenced by process().
connectToDataBase()
void wrimsv2.sql.SQLServerRWriter.connectToDataBase ()
Definition at line 70 of file SQLServerRWriter.java.
References conn, database, wrimsv2.components.ControlData.databaseURL, JDBC_DRIVER, wrimsv2.components.ControlData.PASS, stmt, URL, and wrimsv2.components.ControlData.USER.
Referenced by SQLServerRWriter().
createCSV()
void wrimsv2.sql.SQLServerRWriter.createCSV ()
Definition at line 193 of file SQLServerRWriter.java.
References csvLocalPath, csvRemotePath, wrimsv2.components.FilePaths.fullDvarDssPath, host, wrimsv2.evaluator.CsvOperation.ouputCSV(), scenarioIndex, and URL.
Referenced by process().
createIndex()
void wrimsv2.sql.SQLServerRWriter.createIndex ()
Definition at line 222 of file SQLServerRWriter.java.
References conn, stmt, and tableName.
Referenced by process().
createScenarioCSV()
void wrimsv2.sql.SQLServerRWriter.createScenarioCSV ()
Definition at line 139 of file SQLServerRWriter.java.
References wrimsv2.components.FilePaths.dvarDssDirectory, scenarioTableName, and stmt.
Referenced by process().
createTable()
void wrimsv2.sql.SQLServerRWriter.createTable ()
Definition at line 167 of file SQLServerRWriter.java.
References conn, stmt, and tableName.
Referenced by process().
deleteOldData()
void wrimsv2.sql.SQLServerRWriter.deleteOldData ()
Definition at line 181 of file SQLServerRWriter.java.
References conn, scenarioIndex, stmt, and tableName.
Referenced by process().
process()
void wrimsv2.sql.SQLServerRWriter.process ()
Definition at line 54 of file SQLServerRWriter.java.
References close(), createCSV(), createIndex(), createScenarioCSV(), createTable(), deleteOldData(), scenarioTableName, setScenarioIndex(), tableName, transferCSV(), and writeData().
Referenced by wrimsv2.sql.DssToSQLDatabase.convertData().
setScenarioIndex()
void wrimsv2.sql.SQLServerRWriter.setScenarioIndex ()
Definition at line 102 of file SQLServerRWriter.java.
References conn, wrimsv2.components.ControlData.partA, scenarioIndex, scenarioName, scenarioTableName, stmt, wrimsv2.components.ControlData.svDvPartF, and tableName.
Referenced by process().
transferCSV()
boolean wrimsv2.sql.SQLServerRWriter.transferCSV ()
Definition at line 204 of file SQLServerRWriter.java.
References wrimsv2.sql.socket.Client.connect(), csvLocalPath, host, and wrimsv2.sql.socket.Client.sendFile().
Referenced by process().
writeData()
void wrimsv2.sql.SQLServerRWriter.writeData ()
Definition at line 210 of file SQLServerRWriter.java.
References conn, csvRemotePath, stmt, and tableName.
Referenced by process().
Member Data Documentation
conn
Connection wrimsv2.sql.SQLServerRWriter.conn = null private
Definition at line 40 of file SQLServerRWriter.java.
Referenced by close(), connectToDataBase(), createIndex(), createTable(), deleteOldData(), setScenarioIndex(), and writeData().
csvLocalPath
String wrimsv2.sql.SQLServerRWriter.csvLocalPath private
Definition at line 47 of file SQLServerRWriter.java.
Referenced by createCSV(), and transferCSV().
csvRemotePath
String wrimsv2.sql.SQLServerRWriter.csvRemotePath private
Definition at line 46 of file SQLServerRWriter.java.
Referenced by createCSV(), and writeData().
database
String wrimsv2.sql.SQLServerRWriter.database private
Definition at line 38 of file SQLServerRWriter.java.
Referenced by connectToDataBase().
host
String wrimsv2.sql.SQLServerRWriter.host private
Definition at line 48 of file SQLServerRWriter.java.
Referenced by createCSV(), and transferCSV().
JDBC_DRIVER
String wrimsv2.sql.SQLServerRWriter.JDBC_DRIVER = "com.microsoft.sqlserver.jdbc.SQLServerDriver" private
Definition at line 33 of file SQLServerRWriter.java.
Referenced by connectToDataBase().
scenarioIndex
int wrimsv2.sql.SQLServerRWriter.scenarioIndex private
Definition at line 44 of file SQLServerRWriter.java.
Referenced by createCSV(), deleteOldData(), and setScenarioIndex().
scenarioName
String wrimsv2.sql.SQLServerRWriter.scenarioName =FilePaths.sqlScenarioName private
Definition at line 43 of file SQLServerRWriter.java.
Referenced by setScenarioIndex().
scenarioTableName
String wrimsv2.sql.SQLServerRWriter.scenarioTableName ="Scenario" private
Definition at line 35 of file SQLServerRWriter.java.
Referenced by createScenarioCSV(), process(), and setScenarioIndex().
stmt
Statement wrimsv2.sql.SQLServerRWriter.stmt = null private
Definition at line 41 of file SQLServerRWriter.java.
Referenced by close(), connectToDataBase(), createIndex(), createScenarioCSV(), createTable(), deleteOldData(), setScenarioIndex(), and writeData().
tableName
String wrimsv2.sql.SQLServerRWriter.tableName = ControlData.sqlGroup private
Definition at line 34 of file SQLServerRWriter.java.
Referenced by createIndex(), createTable(), deleteOldData(), process(), setScenarioIndex(), and writeData().
URL
String wrimsv2.sql.SQLServerRWriter.URL private
Definition at line 37 of file SQLServerRWriter.java.
Referenced by connectToDataBase(), and createCSV().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/sql/SQLServerRWriter.java