Wrims-engine: wrimsv2.wreslparser.elements.StudyParser Class Reference
wrimsv2.wreslparser.elements.StudyParser Class Reference
Static Public Member Functions
static void analyzeVarNeededFromCycles (StudyConfig sc, StudyDataSet sd)
static Map< String, SimulationDataSet > parseModels (StudyConfig sc, TempData td) throws RecognitionException, IOException
static Map< String, SimulationDataSet > parseModels (StudyConfig sc, TempData td, boolean rewrite_list_based_on_dependency, boolean send_all_alias_to_dvar) throws RecognitionException, IOException
static StudyConfig processMainFileIntoStudyConfig (String relativeMainFilePath) throws RecognitionException, IOException
static StudyConfig processMainFileIntoStudyConfig (String relativeMainFilePath, boolean showTree) throws RecognitionException, IOException
static void reset ()
static StudyDataSet writeWreslData (StudyConfig sc, TempData td)
Static Public Attributes
static ArrayList< String > error_summary = new ArrayList<String>()
static int total_errors = 0
static int total_warnings = 0
Static Private Member Functions
static void analyzeVarNeededFromCycle_subfunction (String varName, Set< String > neededVarInCycle, String fromWresl, StudyDataSet sd)
static Set< String > checkAliasInGoalExpression (SimulationDataSet ds, Set< String > goalSetToCheck)
static void checkUsedBeforeDefined (SimulationDataSet ds, ArrayList< String > ordered_list_sv_as_ex, Set< String > previous_global_sv_as_ex_ts)
static void convertAlias (SimulationDataSet ds, String aliasName, String goalName)
static void convertRestAliasInGoalExpression (SimulationDataSet ds)
static Map< String, SimulationDataSet > copyDataSetToThisModel (Set< String > incFileSet, Map< String, SimulationDataSet > fileDataMap_wholeStudy)
static SimulationDataSet correctScopeAndPrioritize (String modelName, SimulationDataSet adhoc, String absMainFilePath, Map< String, SimulationDataSet > fileDataMap_thisModel, Map< String, SimulationDataSet > fileDataMap_wholeStudy, Map< String, Set< String > > t1Map_wholeStudy, Map< String, String > fileScopeMap_wholeStudy) throws RecognitionException, IOException
static Map< String, SimulationDataSet > getNewDataSet (Set< String > adhoc_incFileSet, Set< String > fileDataMap_wholeStudy_keySet) throws RecognitionException, IOException
static ArrayList< String > getOrderedList (Map< String, SimulationDataSet > fileDataMap_thisModel, SimulationDataSet adhoc)
static boolean sortDependency (SimulationDataSet model_dataset, boolean rewrite_list_based_on_dependency)
Static Private Attributes
static Set< String > allValidCycleNames
static Map< String, String > cycleNameConditionMap
static Map< String, String > cycleNameTimeStepMap
static Map< String, Map< String, String > > cycleVarTypeMap
static int n_buffer = 3
Detailed Description
Definition at line 28 of file StudyParser.java.
Member Function Documentation
analyzeVarNeededFromCycle_subfunction()
void wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycle_subfunction (String varName, Set< String > neededVarInCycle, String fromWresl, StudyDataSet sd) static private
Definition at line 548 of file StudyParser.java.
References allValidCycleNames, cycleNameConditionMap, cycleVarTypeMap, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.Tools.getCycleVarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), and n_buffer.
Referenced by analyzeVarNeededFromCycles().
analyzeVarNeededFromCycles()
void wrimsv2.wreslparser.elements.StudyParser.analyzeVarNeededFromCycles (StudyConfig sc, StudyDataSet sd) static
create map for var and varType
Definition at line 439 of file StudyParser.java.
References wrimsv2.commondata.wresldata.ModelDataSet.aliasUsedByLaterCycle, allValidCycleNames, analyzeVarNeededFromCycle_subfunction(), wrimsv2.commondata.wresldata.ModelDataSet.asList, wrimsv2.commondata.wresldata.ModelDataSet.asMap, cycleVarTypeMap, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.Alias.fromWresl, wrimsv2.commondata.wresldata.Goal.fromWresl, wrimsv2.commondata.wresldata.Svar.fromWresl, wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gMap, wrimsv2.wreslparser.elements.LogUtils.importantMsg(), wrimsv2.commondata.wresldata.Alias.neededVarInCycleSet, wrimsv2.commondata.wresldata.Goal.neededVarInCycleSet, wrimsv2.commondata.wresldata.Svar.neededVarInCycleSet, wrimsv2.commondata.wresldata.Alias.needVarFromEarlierCycle, wrimsv2.commondata.wresldata.Goal.needVarFromEarlierCycle, wrimsv2.commondata.wresldata.Svar.needVarFromEarlierCycle, wrimsv2.wreslparser.elements.StudyConfig.sequenceMap, wrimsv2.wreslparser.elements.StudyConfig.sequenceOrder, wrimsv2.commondata.wresldata.ModelDataSet.svarUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.svList, wrimsv2.commondata.wresldata.ModelDataSet.svMap, total_errors, and wrimsv2.commondata.wresldata.ModelDataSet.varUsedByLaterCycle.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.parseWresl().
checkAliasInGoalExpression()
Set< String > wrimsv2.wreslparser.elements.StudyParser.checkAliasInGoalExpression (SimulationDataSet ds, Set< String > goalSetToCheck) static private
Definition at line 699 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asSet, convertAlias(), wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, and wrimsv2.wreslparser.elements.SimulationDataSet.tsSet.
Referenced by parseModels().
checkUsedBeforeDefined()
void wrimsv2.wreslparser.elements.StudyParser.checkUsedBeforeDefined (SimulationDataSet ds, ArrayList< String > ordered_list_sv_as_ex, Set< String > previous_global_sv_as_ex_ts) static private
Definition at line 632 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.tsSet, and wrimsv2.wreslparser.elements.LogUtils.warningMsg().
Referenced by parseModels().
convertAlias()
void wrimsv2.wreslparser.elements.StudyParser.convertAlias (SimulationDataSet ds, String aliasName, String goalName) static private
Definition at line 893 of file StudyParser.java.
References wrimsv2.commondata.wresldata.Param.always, wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asList_global, wrimsv2.wreslparser.elements.SimulationDataSet.asList_local, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.wreslparser.elements.SimulationDataSet.asSet, wrimsv2.wreslparser.elements.SimulationDataSet.asSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.asSet_local, wrimsv2.commondata.wresldata.Goal.caseCondition, wrimsv2.commondata.wresldata.Goal.caseExpression, wrimsv2.commondata.wresldata.Goal.caseName, wrimsv2.commondata.wresldata.Param.defaultCaseName, wrimsv2.commondata.wresldata.Alias.dependants, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet_local, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.commondata.wresldata.Alias.expression, wrimsv2.commondata.wresldata.Alias.fromWresl, wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gList_global, wrimsv2.wreslparser.elements.SimulationDataSet.gList_local, wrimsv2.commondata.wresldata.Param.global, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.gSet, wrimsv2.wreslparser.elements.SimulationDataSet.gSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.gSet_local, wrimsv2.commondata.wresldata.Alias.kind, wrimsv2.commondata.wresldata.Param.local, wrimsv2.commondata.wresldata.Param.lower_unbounded, wrimsv2.commondata.wresldata.Alias.neededVarInCycleSet, wrimsv2.commondata.wresldata.Alias.needVarFromEarlierCycle, wrimsv2.commondata.wresldata.Alias.scope, wrimsv2.commondata.wresldata.Alias.timeArraySize, wrimsv2.commondata.wresldata.Goal.timeArraySize, wrimsv2.commondata.wresldata.Alias.units, and wrimsv2.commondata.wresldata.Param.upper_unbounded.
Referenced by checkAliasInGoalExpression(), and convertRestAliasInGoalExpression().
convertRestAliasInGoalExpression()
void wrimsv2.wreslparser.elements.StudyParser.convertRestAliasInGoalExpression (SimulationDataSet ds) static private
Definition at line 687 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asSet, and convertAlias().
Referenced by parseModels().
copyDataSetToThisModel()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.StudyParser.copyDataSetToThisModel (Set< String > incFileSet, Map< String, SimulationDataSet > fileDataMap_wholeStudy) static private
Definition at line 746 of file StudyParser.java.
References wrimsv2.wreslparser.elements.Tools.putDataFileMapFromWholeStudy().
Referenced by parseModels().
correctScopeAndPrioritize()
SimulationDataSet wrimsv2.wreslparser.elements.StudyParser.correctScopeAndPrioritize (String modelName, SimulationDataSet adhoc, String absMainFilePath, Map< String, SimulationDataSet > fileDataMap_thisModel, Map< String, SimulationDataSet > fileDataMap_wholeStudy, Map< String, Set< String > > t1Map_wholeStudy, Map< String, String > fileScopeMap_wholeStudy) throws RecognitionException, IOException static private
Definition at line 758 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.addChildren(), wrimsv2.wreslparser.elements.Tools.correctDataScope_deep(), wrimsv2.wreslparser.elements.Tools.getReverseMap(), wrimsv2.wreslparser.elements.Tools.getScopeMap(), and wrimsv2.wreslparser.elements.SimulationDataSet.overwrittenWith_set().
Referenced by parseModels().
getNewDataSet()
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.StudyParser.getNewDataSet (Set< String > adhoc_incFileSet, Set< String > fileDataMap_wholeStudy_keySet) throws RecognitionException, IOException static private
Definition at line 728 of file StudyParser.java.
References wrimsv2.wreslparser.elements.FileParser.processNestedFileExceptFor().
Referenced by parseModels().
getOrderedList()
ArrayList< String > wrimsv2.wreslparser.elements.StudyParser.getOrderedList (Map< String, SimulationDataSet > fileDataMap_thisModel, SimulationDataSet adhoc) static private
Definition at line 832 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.ordered_list_including_files, and wrimsv2.wreslparser.elements.Sort.sort().
Referenced by parseModels().
parseModels() [1/2]
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.StudyParser.parseModels (StudyConfig sc, TempData td) throws RecognitionException, IOException static
Definition at line 212 of file StudyParser.java.
References parseModels().
Referenced by parseModels(), and wrimsv2.wreslparser.elements.StudyUtils.parseWresl().
parseModels() [2/2]
Map< String, SimulationDataSet > wrimsv2.wreslparser.elements.StudyParser.parseModels (StudyConfig sc, TempData td, boolean rewrite_list_based_on_dependency, boolean send_all_alias_to_dvar) throws RecognitionException, IOException static
check for redefined weight // TODO: what to do?
check for redefined file
check for redefined globals
add previous globals
finish adding globals
check if goal dependents are defined
check if weight var is defined in dvar set
check if alias is used in goal's constraint expression.
check if var size > 100
Definition at line 217 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asSet, checkAliasInGoalExpression(), checkUsedBeforeDefined(), convertRestAliasInGoalExpression(), copyDataSetToThisModel(), correctScopeAndPrioritize(), wrimsv2.wreslparser.elements.LogUtils.criticalMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.exSet, wrimsv2.wreslparser.elements.SimulationDataSet.getAllGlobalVarsSet_except_file_and_weight(), wrimsv2.wreslparser.elements.SimulationDataSet.getAllLocalVarsSet_except_file_and_weight(), wrimsv2.wreslparser.elements.Tools.getFileScopeMap(), wrimsv2.wreslparser.elements.SimulationDataSet.getGlobalVars_set(), getNewDataSet(), getOrderedList(), wrimsv2.wreslparser.elements.Tools.getReverseMap(), wrimsv2.wreslparser.elements.Tools.getType1Map(), wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.gSet, wrimsv2.wreslparser.elements.LogUtils.importantMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet, wrimsv2.wreslparser.elements.SimulationDataSet.incFileSet_global, wrimsv2.wreslparser.elements.SimulationDataSet.lousyConvert(), wrimsv2.wreslparser.elements.SimulationDataSet.overwrite_set(), wrimsv2.wreslparser.elements.Tools.removeDuplicates(), wrimsv2.wreslparser.elements.SimulationDataSet.replaceGlobalWithDuplicateLocal(), wrimsv2.commondata.wresldata.Param.reservedSet, wrimsv2.wreslparser.elements.Tools.restoreOrder(), sortDependency(), wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, total_errors, total_warnings, wrimsv2.wreslparser.elements.SimulationDataSet.tsSet, wrimsv2.wreslparser.elements.LogUtils.warningMsg(), wrimsv2.wreslparser.elements.SimulationDataSet.wtSet, and wrimsv2.wreslparser.elements.SimulationDataSet.wtSet_global.
processMainFileIntoStudyConfig() [1/2]
StudyConfig wrimsv2.wreslparser.elements.StudyParser.processMainFileIntoStudyConfig (String relativeMainFilePath) throws RecognitionException, IOException static
reset total errors
Definition at line 165 of file StudyParser.java.
References processMainFileIntoStudyConfig(), and total_errors.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.parseWresl(), and processMainFileIntoStudyConfig().
processMainFileIntoStudyConfig() [2/2]
StudyConfig wrimsv2.wreslparser.elements.StudyParser.processMainFileIntoStudyConfig (String relativeMainFilePath, boolean showTree) throws RecognitionException, IOException static
Sort sequence order
Definition at line 171 of file StudyParser.java.
References cycleNameConditionMap, cycleNameTimeStepMap, wrimsv2.wreslparser.elements.LogUtils.importantMsg(), wrimsv2.wreslparser.elements.StudyConfig.modelConditionList, wrimsv2.wreslparser.elements.StudyConfig.modelList, wrimsv2.wreslparser.elements.StudyConfig.modelTimeStepList, wrimsv2.wreslparser.elements.FileParser.parseMainFile(), wrimsv2.wreslparser.elements.StudyConfig.sequenceList, wrimsv2.wreslparser.elements.StudyConfig.sequenceMap, and wrimsv2.wreslparser.elements.StudyConfig.sequenceOrder.
reset()
void wrimsv2.wreslparser.elements.StudyParser.reset () static
Definition at line 40 of file StudyParser.java.
References allValidCycleNames, cycleNameConditionMap, cycleNameTimeStepMap, cycleVarTypeMap, error_summary, total_errors, and total_warnings.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy_compileLog(), wrimsv2.wreslparser.elements.StudyUtils.parseWresl(), and wrimsv2.wreslparser.elements.StudyUtils.reset().
sortDependency()
boolean wrimsv2.wreslparser.elements.StudyParser.sortDependency (SimulationDataSet model_dataset, boolean rewrite_list_based_on_dependency) static private
Definition at line 794 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.wreslparser.elements.SimulationDataSet.asSet, wrimsv2.wreslparser.elements.SimulationDataSet.asSet_unknown, wrimsv2.wreslparser.elements.SimulationDataSet.dvSet, wrimsv2.wreslparser.elements.SimulationDataSet.exSet, wrimsv2.wreslparser.elements.Sort.sort(), wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_unknown, and wrimsv2.wreslparser.elements.SimulationDataSet.tsSet.
Referenced by parseModels().
writeWreslData()
StudyDataSet wrimsv2.wreslparser.elements.StudyParser.writeWreslData (StudyConfig sc, TempData td) static
Definition at line 50 of file StudyParser.java.
References wrimsv2.wreslparser.elements.SimulationDataSet.asList, wrimsv2.wreslparser.elements.SimulationDataSet.asList_global, wrimsv2.wreslparser.elements.SimulationDataSet.asList_local, wrimsv2.wreslparser.elements.SimulationDataSet.asMap, wrimsv2.wreslparser.elements.SimulationDataSet.asSet_unknown, wrimsv2.commondata.wresldata.Param.conditional, wrimsv2.components.ControlData.defaultTimeStep, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.wreslparser.elements.SimulationDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvList_global, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_global, wrimsv2.commondata.wresldata.ModelDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvList_local, wrimsv2.wreslparser.elements.SimulationDataSet.dvMap, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.dvSlackSurplusMap, wrimsv2.wreslparser.elements.SimulationDataSet.exList, wrimsv2.wreslparser.elements.SimulationDataSet.exList_global, wrimsv2.wreslparser.elements.SimulationDataSet.exList_local, wrimsv2.wreslparser.elements.SimulationDataSet.exMap, wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gList, wrimsv2.wreslparser.elements.SimulationDataSet.gList_global, wrimsv2.wreslparser.elements.SimulationDataSet.gList_local, wrimsv2.wreslparser.elements.SimulationDataSet.gMap, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_global, wrimsv2.wreslparser.elements.SimulationDataSet.incFileList_local, wrimsv2.wreslparser.elements.TempData.model_dataset_map, wrimsv2.wreslparser.elements.StudyConfig.modelConditionList, wrimsv2.wreslparser.elements.StudyConfig.modelList, wrimsv2.wreslparser.elements.StudyConfig.modelTimeStepList, wrimsv2.commondata.wresldata.StudyDataSet.setModelConditionList(), wrimsv2.commondata.wresldata.StudyDataSet.setModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.setModelList(), wrimsv2.commondata.wresldata.StudyDataSet.setModelTimeStepList(), wrimsv2.commondata.wresldata.StudyDataSet.setTimeseriesMap(), wrimsv2.commondata.wresldata.StudyDataSet.setTimeseriesTimeStepMap(), wrimsv2.commondata.wresldata.StudyDataSet.setVarCycleIndexList(), wrimsv2.wreslparser.elements.SimulationDataSet.svList, wrimsv2.wreslparser.elements.SimulationDataSet.svList_global, wrimsv2.wreslparser.elements.SimulationDataSet.svList_local, wrimsv2.wreslparser.elements.SimulationDataSet.svMap, wrimsv2.wreslparser.elements.SimulationDataSet.svSet_unknown, wrimsv2.wreslparser.elements.SimulationDataSet.tsList, wrimsv2.wreslparser.elements.SimulationDataSet.tsList_global, wrimsv2.wreslparser.elements.SimulationDataSet.tsList_local, wrimsv2.wreslparser.elements.SimulationDataSet.tsMap, wrimsv2.commondata.wresldata.Param.undefined, wrimsv2.wreslplus.elements.VarCycleIndex.varCycleIndexList, wrimsv2.commondata.wresldata.ModelDataSet.wtList, wrimsv2.wreslparser.elements.SimulationDataSet.wtList, wrimsv2.wreslparser.elements.SimulationDataSet.wtMap, wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusList, and wrimsv2.commondata.wresldata.ModelDataSet.wtSlackSurplusMap.
Referenced by wrimsv2.wreslparser.elements.StudyUtils.parseWresl().
Member Data Documentation
allValidCycleNames
Set<String> wrimsv2.wreslparser.elements.StudyParser.allValidCycleNames static private
Definition at line 34 of file StudyParser.java.
Referenced by analyzeVarNeededFromCycle_subfunction(), analyzeVarNeededFromCycles(), and reset().
cycleNameConditionMap
Map<String, String> wrimsv2.wreslparser.elements.StudyParser.cycleNameConditionMap static private
Definition at line 35 of file StudyParser.java.
Referenced by analyzeVarNeededFromCycle_subfunction(), processMainFileIntoStudyConfig(), and reset().
cycleNameTimeStepMap
Map<String, String> wrimsv2.wreslparser.elements.StudyParser.cycleNameTimeStepMap static private
Definition at line 36 of file StudyParser.java.
Referenced by processMainFileIntoStudyConfig(), and reset().
cycleVarTypeMap
Map<String, Map<String, String> > wrimsv2.wreslparser.elements.StudyParser.cycleVarTypeMap static private
Definition at line 33 of file StudyParser.java.
Referenced by analyzeVarNeededFromCycle_subfunction(), analyzeVarNeededFromCycles(), and reset().
error_summary
ArrayList<String> wrimsv2.wreslparser.elements.StudyParser.error_summary = new ArrayList<String>() static
Definition at line 31 of file StudyParser.java.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), and reset().
n_buffer
int wrimsv2.wreslparser.elements.StudyParser.n_buffer = 3 static private
Definition at line 37 of file StudyParser.java.
Referenced by analyzeVarNeededFromCycle_subfunction().
total_errors
int wrimsv2.wreslparser.elements.StudyParser.total_errors = 0 static
Definition at line 30 of file StudyParser.java.
Referenced by analyzeVarNeededFromCycles(), wrimsv2.wreslparser.elements.StudyUtils.checkStudy(), wrimsv2.wreslplus.elements.Workflow.checkStudy(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.components.DebugInterface.handleRequest(), parseModels(), wrimsv2.wreslparser.elements.StudyUtils.parseWresl(), processMainFileIntoStudyConfig(), reset(), wrimsv2.components.ControllerDebug.run(), and wrimsv2.wreslparser.elements.LogUtils.typeRedefinedErrMsg().
total_warnings
int wrimsv2.wreslparser.elements.StudyParser.total_warnings = 0 static
Definition at line 32 of file StudyParser.java.
Referenced by parseModels(), reset(), and wrimsv2.wreslparser.elements.LogUtils.warningMsg().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslparser/elements/StudyParser.java