Wrims-engine: wrimsv2.solver.ClpSolver Class Reference
wrimsv2.solver.ClpSolver Class Reference
Public Member Functions
void setDefaultOption ()
Static Public Member Functions
static void addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName)
static void close ()
static double getObjValue ()
static void init (boolean useLpFile)
static void main (String argv[])
static void newProblem (String modelName, boolean useLpFile)
static int solve (double tolerance, boolean useLpFile)
Static Public Attributes
static int errorCode = 99
static Map< String, Double > varDoubleMap
Private Member Functions
ClpSolver ()
Static Private Member Functions
static void assignDvar ()
static void collectDvar ()
static void getSolverInformation (int modelStatus)
static void resetModel (boolean useLpFile)
static void setConstraints ()
static void setDVars ()
static void setWeights ()
Static Private Attributes
static SWIGTYPE_p_CoinBuild buildObject
static Map< String, Dvar > dvarMap
static ArrayList< String > dvKeys
static double maxValue = 1.0e23
static SWIGTYPE_p_ClpSimplex model
static ArrayList< SWIGTYPE_p_int > rowIndex_array
static ArrayList< SWIGTYPE_p_double > rowValue_array
Detailed Description
Definition at line 27 of file ClpSolver.java.
Constructor & Destructor Documentation
ClpSolver()
wrimsv2.solver.ClpSolver.ClpSolver () private
Definition at line 40 of file ClpSolver.java.
Member Function Documentation
addConditionalSlackSurplusToDvarMap()
void wrimsv2.solver.ClpSolver.addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName) static
Definition at line 433 of file ClpSolver.java.
References dvarMap, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
Referenced by setConstraints().
assignDvar()
void wrimsv2.solver.ClpSolver.assignDvar () static private
Definition at line 362 of file ClpSolver.java.
References wrimsv2.components.Error.addSolvingError(), wrimsv2.components.ControlData.clp_cbc_objective, wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, dvarMap, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), errorCode, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), model, wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and varDoubleMap.
Referenced by newProblem().
close()
void wrimsv2.solver.ClpSolver.close () static
Definition at line 50 of file ClpSolver.java.
Referenced by wrimsv2.components.ControllerBatch.runModelClp(), and wrimsv2.components.ControllerBatch.runModelILP().
collectDvar()
void wrimsv2.solver.ClpSolver.collectDvar () static private
Definition at line 335 of file ClpSolver.java.
References model, and varDoubleMap.
Referenced by newProblem().
getObjValue()
double wrimsv2.solver.ClpSolver.getObjValue () static
Definition at line 119 of file ClpSolver.java.
References model.
Referenced by newProblem().
getSolverInformation()
void wrimsv2.solver.ClpSolver.getSolverInformation (int modelStatus) static private
Definition at line 141 of file ClpSolver.java.
References wrimsv2.components.Error.addSolvingError(), and errorCode.
Referenced by newProblem().
init()
void wrimsv2.solver.ClpSolver.init (boolean useLpFile) static
Definition at line 42 of file ClpSolver.java.
References model.
Referenced by wrimsv2.components.ControllerBatch.runModelClp(), and wrimsv2.components.ControllerBatch.runModelILP().
main()
void wrimsv2.solver.ClpSolver.main (String argv[]) static
Definition at line 442 of file ClpSolver.java.
newProblem()
void wrimsv2.solver.ClpSolver.newProblem (String modelName, boolean useLpFile) static
Definition at line 55 of file ClpSolver.java.
References assignDvar(), buildObject, wrimsv2.components.ControlData.clp_cbc_objective, collectDvar(), wrimsv2.components.ControlData.currModelDataSet, dvarMap, dvKeys, wrimsv2.commondata.wresldata.ModelDataSet.dvList, wrimsv2.commondata.wresldata.ModelDataSet.dvTimeArrayList, wrimsv2.components.Error.error_solving, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), getObjValue(), getSolverInformation(), model, resetModel(), rowIndex_array, rowValue_array, setConstraints(), setDVars(), setWeights(), and solve().
Referenced by wrimsv2.components.ControllerBatch.runModelClp(), and wrimsv2.components.ControllerBatch.runModelILP().
resetModel()
void wrimsv2.solver.ClpSolver.resetModel (boolean useLpFile) static private
Definition at line 123 of file ClpSolver.java.
References buildObject, model, rowIndex_array, and rowValue_array.
Referenced by newProblem().
setConstraints()
void wrimsv2.solver.ClpSolver.setConstraints () static private
Definition at line 154 of file ClpSolver.java.
References addConditionalSlackSurplusToDvarMap(), buildObject, wrimsv2.components.ControlData.currModelDataSet, dvarMap, dvKeys, wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), wrimsv2.commondata.wresldata.ModelDataSet.gList, wrimsv2.commondata.wresldata.ModelDataSet.gTimeArrayList, maxValue, model, rowIndex_array, and rowValue_array.
Referenced by newProblem().
setDefaultOption()
void wrimsv2.solver.ClpSolver.setDefaultOption ()
Definition at line 357 of file ClpSolver.java.
setDVars()
void wrimsv2.solver.ClpSolver.setDVars () static private
Definition at line 274 of file ClpSolver.java.
References dvarMap, dvKeys, wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, model, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
Referenced by newProblem().
setWeights()
void wrimsv2.solver.ClpSolver.setWeights () static private
Definition at line 244 of file ClpSolver.java.
References wrimsv2.components.ControlData.currModelDataSet, dvKeys, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.solverdata.SolverData.getWeightSlackSurplusMap(), model, wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, wrimsv2.commondata.wresldata.ModelDataSet.wtList, and wrimsv2.commondata.wresldata.ModelDataSet.wtTimeArrayList.
Referenced by newProblem().
solve()
int wrimsv2.solver.ClpSolver.solve (double tolerance, boolean useLpFile) static
Definition at line 287 of file ClpSolver.java.
References model.
Referenced by newProblem().
Member Data Documentation
buildObject
SWIGTYPE_p_CoinBuild wrimsv2.solver.ClpSolver.buildObject static private
Definition at line 32 of file ClpSolver.java.
Referenced by newProblem(), resetModel(), and setConstraints().
dvarMap
Map<String, Dvar> wrimsv2.solver.ClpSolver.dvarMap static private
Definition at line 34 of file ClpSolver.java.
Referenced by addConditionalSlackSurplusToDvarMap(), assignDvar(), newProblem(), setConstraints(), and setDVars().
dvKeys
ArrayList<String> wrimsv2.solver.ClpSolver.dvKeys static private
Definition at line 33 of file ClpSolver.java.
Referenced by newProblem(), setConstraints(), setDVars(), and setWeights().
errorCode
int wrimsv2.solver.ClpSolver.errorCode = 99 static
Definition at line 29 of file ClpSolver.java.
Referenced by assignDvar(), and getSolverInformation().
maxValue
double wrimsv2.solver.ClpSolver.maxValue = 1.0e23 static private
Definition at line 38 of file ClpSolver.java.
Referenced by setConstraints().
model
SWIGTYPE_p_ClpSimplex wrimsv2.solver.ClpSolver.model static private
Definition at line 31 of file ClpSolver.java.
Referenced by assignDvar(), collectDvar(), getObjValue(), init(), newProblem(), resetModel(), setConstraints(), setDVars(), setWeights(), and solve().
rowIndex_array
ArrayList<SWIGTYPE_p_int> wrimsv2.solver.ClpSolver.rowIndex_array static private
Definition at line 36 of file ClpSolver.java.
Referenced by newProblem(), resetModel(), and setConstraints().
rowValue_array
ArrayList<SWIGTYPE_p_double> wrimsv2.solver.ClpSolver.rowValue_array static private
Definition at line 37 of file ClpSolver.java.
Referenced by newProblem(), resetModel(), and setConstraints().
varDoubleMap
Map<String, Double> wrimsv2.solver.ClpSolver.varDoubleMap static
Definition at line 30 of file ClpSolver.java.
Referenced by assignDvar(), collectDvar(), and wrimsv2.components.ControllerBatch.runModelILP().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/ClpSolver.java