Wrims-engine: wrimsv2.wreslplus.elements.procedures.ErrorCheck Class Reference
wrimsv2.wreslplus.elements.procedures.ErrorCheck Class Reference
Static Public Member Functions
static boolean checkDeviationSlackSurplus (Map< String, Double > deviationSS_toleranceMap, Map< String, Dvar > dvMap)
static boolean checkIfStatementHasUnknownDependants (ModelTemp m, Set< String > parameters)
static void checkIfStatementHasUnknownDependants (StudyTemp st)
static boolean checkIncModelNotExistIgnoreCase (StudyTemp s)
static boolean checkInitialConst (StudyTemp st)
static boolean checkInitialVarInConfigNotDeclaredInWresl (StudyTemp st)
static int checkModelRedefined (StudyTemp s)
static int checkModelRedefinedIgnoreCase (StudyTemp s)
static boolean checkParameterHasUnknownDepedants (StudyTemp st)
static boolean checkSeqConditionHasUnknownDepedants (StudyTemp st)
static int checkSequenceHasUniqueModel (StudyTemp s)
static int checkVarRedefined (ModelTemp m, StudyTemp st)
static int checkVarRedefined (StudyTemp s)
static void checkVarUsedBeforeDefined (SequenceTemp seqObj)
static void checkVarUsedBeforeDefined (StudyTemp s)
static boolean checkWeightObjList (StudyTemp st)
static void checkWeightVarNotInDvar (SequenceTemp seqObj)
static void checkWeightVarNotInDvar (StudyTemp s)
static ArrayList< String > findDuplicates (ArrayList< String > a)
static ArrayList< String > findDuplicatesIgnoreCase (ArrayList< String > a)
static ArrayList< String > removeDuplicates (ArrayList< String > a)
Private Member Functions
ErrorCheck ()
Detailed Description
Definition at line 28 of file ErrorCheck.java.
Constructor & Destructor Documentation
ErrorCheck()
wrimsv2.wreslplus.elements.procedures.ErrorCheck.ErrorCheck () private
Definition at line 31 of file ErrorCheck.java.
Member Function Documentation
checkDeviationSlackSurplus()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkDeviationSlackSurplus (Map< String, Double > deviationSS_toleranceMap, Map< String, Dvar > dvMap) static
Definition at line 63 of file ErrorCheck.java.
References wrimsv2.components.Error.addDeviationError(), wrimsv2.components.Error.writeDeviationErrorFile(), and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.components.ControllerBatch.runModelCbc(), wrimsv2.components.ControllerSG.runModelCbc(), wrimsv2.components.ControllerBatch.runModelClp(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.Controller.runModelILP(), wrimsv2.components.ControllerBatch.runModelILP(), wrimsv2.components.ControllerBatch.runModelOrTools(), wrimsv2.components.ControllerDebug.runModelSolvers(), wrimsv2.components.Controller.runModelXA(), wrimsv2.components.ControllerBatch.runModelXA(), and wrimsv2.components.ControllerSG.runModelXA().
checkIfStatementHasUnknownDependants() [1/2]
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIfStatementHasUnknownDependants (ModelTemp m, Set< String > parameters) static
Definition at line 742 of file ErrorCheck.java.
References wrimsv2.components.Error.addInitialError(), wrimsv2.wreslplus.elements.IfIncItemGroup.dependants, wrimsv2.wreslplus.elements.IfIncItemGroup.fromWresl, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupIDList, wrimsv2.wreslplus.elements.ModelTemp.ifIncItemGroupMap, and wrimsv2.components.Error.writeErrorLog().
checkIfStatementHasUnknownDependants() [2/2]
void wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIfStatementHasUnknownDependants (StudyTemp st) static
Definition at line 729 of file ErrorCheck.java.
References checkIfStatementHasUnknownDependants(), wrimsv2.wreslplus.elements.StudyTemp.modelList, wrimsv2.wreslplus.elements.StudyTemp.modelMap, and wrimsv2.wreslplus.elements.StudyTemp.parameterMap.
Referenced by checkIfStatementHasUnknownDependants(), wrimsv2.wreslplus.elements.Workflow.checkStudy(), and wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile().
checkIncModelNotExistIgnoreCase()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkIncModelNotExistIgnoreCase (StudyTemp s) static
Definition at line 184 of file ErrorCheck.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase(), wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslplus.elements.StudyTemp.modelList, and wrimsv2.wreslplus.elements.StudyTemp.modelMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkInitialConst()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialConst (StudyTemp st) static
Definition at line 652 of file ErrorCheck.java.
References wrimsv2.components.Error.addInitialError(), wrimsv2.wreslplus.elements.SvarTemp.caseExpression, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslplus.elements.StudyTemp.parameterConstList, wrimsv2.wreslplus.elements.StudyTemp.parameterMap, and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkInitialVarInConfigNotDeclaredInWresl()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkInitialVarInConfigNotDeclaredInWresl (StudyTemp st) static
Definition at line 633 of file ErrorCheck.java.
References wrimsv2.components.Error.addInitialError(), wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.config.ConfigUtils.paramMap, and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkModelRedefined()
int wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkModelRedefined (StudyTemp s) static
Definition at line 248 of file ErrorCheck.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg(), findDuplicates(), wrimsv2.wreslplus.elements.StudyTemp.modelList, and wrimsv2.wreslplus.elements.StudyTemp.modelMap.
checkModelRedefinedIgnoreCase()
int wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkModelRedefinedIgnoreCase (StudyTemp s) static
Definition at line 235 of file ErrorCheck.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg(), findDuplicatesIgnoreCase(), and wrimsv2.wreslplus.elements.StudyTemp.modelList.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkParameterHasUnknownDepedants()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkParameterHasUnknownDepedants (StudyTemp st) static
Definition at line 681 of file ErrorCheck.java.
References wrimsv2.components.Error.addInitialError(), wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.dependants_notAllowed, wrimsv2.wreslplus.elements.SvarTemp.dependants_unknown, wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.SvarTemp.line, wrimsv2.wreslplus.elements.StudyTemp.parameterList, wrimsv2.wreslplus.elements.StudyTemp.parameterMap, and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkSeqConditionHasUnknownDepedants()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSeqConditionHasUnknownDepedants (StudyTemp st) static
Definition at line 769 of file ErrorCheck.java.
References wrimsv2.components.Error.addInitialError(), wrimsv2.wreslplus.elements.StudyTemp.controlDataParameterMap, wrimsv2.wreslplus.elements.SequenceTemp.dependants, wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.wreslplus.elements.SequenceTemp.fromWresl, wrimsv2.wreslplus.elements.SequenceTemp.line, wrimsv2.commondata.wresldata.Param.reservedSet, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, and wrimsv2.components.Error.writeErrorLog().
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkSequenceHasUniqueModel()
int wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkSequenceHasUniqueModel (StudyTemp s) static
Definition at line 211 of file ErrorCheck.java.
References wrimsv2.wreslparser.elements.LogUtils.errMsg(), findDuplicatesIgnoreCase(), and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkVarRedefined() [1/2]
int wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarRedefined (ModelTemp m, StudyTemp st) static
Definition at line 281 of file ErrorCheck.java.
References wrimsv2.wreslplus.elements.ModelTemp.absPath, wrimsv2.wreslplus.elements.ModelTemp.asList, wrimsv2.wreslplus.elements.ModelTemp.asMap, wrimsv2.wreslplus.elements.StudyTemp.controlDataParameterMap, wrimsv2.wreslplus.elements.ModelTemp.dvList, wrimsv2.wreslplus.elements.ModelTemp.dvMap, wrimsv2.wreslparser.elements.LogUtils.errMsg(), wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.wreslplus.elements.ModelTemp.exList, wrimsv2.wreslplus.elements.ModelTemp.exMap, findDuplicates(), wrimsv2.wreslplus.elements.DvarTemp.fromWresl, wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.ModelTemp.glList, wrimsv2.wreslplus.elements.ModelTemp.glMap, wrimsv2.wreslplus.elements.DvarTemp.id, wrimsv2.wreslplus.elements.SvarTemp.id, wrimsv2.wreslplus.elements.ModelTemp.itemList, wrimsv2.wreslplus.elements.DvarTemp.line, wrimsv2.wreslplus.elements.SvarTemp.line, removeDuplicates(), wrimsv2.wreslplus.elements.ModelTemp.svList, wrimsv2.wreslplus.elements.ModelTemp.svMap, wrimsv2.wreslplus.elements.ModelTemp.tsList, wrimsv2.wreslplus.elements.ModelTemp.tsMap, and wrimsv2.wreslplus.elements.ModelTemp.wvList_post.
checkVarRedefined() [2/2]
int wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarRedefined (StudyTemp s) static
Definition at line 261 of file ErrorCheck.java.
References checkVarRedefined(), wrimsv2.wreslplus.elements.StudyTemp.modelList, and wrimsv2.wreslplus.elements.StudyTemp.modelMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), checkVarRedefined(), and wrimsv2.wreslplus.elements.ParserUtils.parseAllIncFile().
checkVarUsedBeforeDefined() [1/2]
void wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarUsedBeforeDefined (SequenceTemp seqObj) static
Definition at line 103 of file ErrorCheck.java.
References wrimsv2.wreslplus.elements.SequenceTemp.asMap, wrimsv2.wreslplus.elements.SvarTemp.dependants, wrimsv2.wreslplus.elements.SvarTemp.dependants_parameter, wrimsv2.wreslplus.elements.SvarTemp.dependants_svar, wrimsv2.wreslplus.elements.SvarTemp.dependants_unknown, wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslparser.elements.LogUtils.errMsgLocation(), wrimsv2.wreslplus.elements.SequenceTemp.exList, wrimsv2.wreslplus.elements.SvarTemp.fromWresl, wrimsv2.wreslplus.elements.SequenceTemp.id, wrimsv2.wreslplus.elements.SvarTemp.line, wrimsv2.wreslplus.elements.SequenceTemp.svIncFileList_post, wrimsv2.wreslplus.elements.SequenceTemp.svMap, and wrimsv2.wreslplus.elements.SequenceTemp.tsList.
checkVarUsedBeforeDefined() [2/2]
void wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkVarUsedBeforeDefined (StudyTemp s) static
Definition at line 93 of file ErrorCheck.java.
References checkVarUsedBeforeDefined(), wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and checkVarUsedBeforeDefined().
checkWeightObjList()
boolean wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightObjList (StudyTemp st) static
Definition at line 417 of file ErrorCheck.java.
References wrimsv2.wreslplus.elements.WeightTable.deviationPenalty, wrimsv2.wreslplus.elements.WeightTable.deviationTolerance, wrimsv2.wreslparser.elements.LogUtils.errMsg(), findDuplicates(), wrimsv2.wreslplus.elements.WeightTable.id_lowcase, wrimsv2.wreslplus.elements.WeightTable.id_raw, wrimsv2.wreslplus.elements.WeightTable.isWeightGroup, wrimsv2.wreslplus.elements.StudyTemp.seqList, wrimsv2.wreslplus.elements.StudyTemp.seqMap, wrimsv2.wreslplus.elements.WeightTable.subgroupMap, wrimsv2.wreslplus.elements.WeightTable.varList, and wrimsv2.wreslplus.elements.SequenceTemp.wTableObjList.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy().
checkWeightVarNotInDvar() [1/2]
void wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightVarNotInDvar (SequenceTemp seqObj) static
Definition at line 613 of file ErrorCheck.java.
References wrimsv2.wreslplus.elements.SequenceTemp.dvList, wrimsv2.wreslplus.elements.SequenceTemp.dvList_fromAlias, wrimsv2.wreslparser.elements.LogUtils.errMsg(), and wrimsv2.wreslplus.elements.SequenceTemp.wvList.
checkWeightVarNotInDvar() [2/2]
void wrimsv2.wreslplus.elements.procedures.ErrorCheck.checkWeightVarNotInDvar (StudyTemp s) static
Definition at line 603 of file ErrorCheck.java.
References checkWeightVarNotInDvar(), wrimsv2.wreslplus.elements.StudyTemp.seqList, and wrimsv2.wreslplus.elements.StudyTemp.seqMap.
Referenced by wrimsv2.wreslplus.elements.Workflow.checkStudy(), and checkWeightVarNotInDvar().
findDuplicates()
ArrayList< String > wrimsv2.wreslplus.elements.procedures.ErrorCheck.findDuplicates (ArrayList< String > a) static
Definition at line 387 of file ErrorCheck.java.
Referenced by checkModelRedefined(), checkVarRedefined(), and checkWeightObjList().
findDuplicatesIgnoreCase()
ArrayList< String > wrimsv2.wreslplus.elements.procedures.ErrorCheck.findDuplicatesIgnoreCase (ArrayList< String > a) static
Definition at line 367 of file ErrorCheck.java.
References wrimsv2.wreslplus.elements.Tools.allToLowerCase().
Referenced by checkModelRedefinedIgnoreCase(), checkSequenceHasUniqueModel(), wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap(), and wrimsv2.wreslplus.elements.Procedures.copyModelVarMapToSequenceVarMap().
removeDuplicates()
ArrayList< String > wrimsv2.wreslplus.elements.procedures.ErrorCheck.removeDuplicates (ArrayList< String > a) static
Definition at line 405 of file ErrorCheck.java.
Referenced by checkVarRedefined().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/wreslplus/elements/procedures/ErrorCheck.java