Wrims-engine: wrimsv2.evaluator.ValueEvaluation Class Reference
wrimsv2.evaluator.ValueEvaluation Class Reference
Static Public Member Functions
static IntDouble abs (IntDouble id1)
static IntDouble acos (IntDouble id1)
static IntDouble acot (IntDouble id1)
static IntDouble add (IntDouble id1, IntDouble id2)
static IntDouble argFunction (String ident, ArrayList< ArrayList< IntDouble > > idArray)
static IntDouble asin (IntDouble id1)
static Number assignWhereStatement (IntDouble id)
static IntDouble atan (IntDouble id1)
static String convertDoubleToString (double value)
static String convertIntToString (int value)
static double convertStringToDouble (String text)
static int convertStringToInt (String text)
static IntDouble cos (IntDouble id1)
static IntDouble cot (IntDouble id1)
static IntDouble daysIn ()
static IntDouble daysInTimeStep ()
static IntDouble divide (IntDouble id1, IntDouble id2)
static double dvarAliasCycleTimeSeries (String ident, int indexValue, int ci, ParallelVars prvs)
static double dvarAliasTimeSeries (String ident, int indexValue, ParallelVars prvs)
static double dvarAliasTimeSeries (String ident, ParallelVars prvs)
static IntDouble exceedance (String tsName, IntDouble exc_id, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr)
static IntDouble exceedance_tsi (String tsName, IntDouble exc_id, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr)
static IntDouble exp (IntDouble id1)
static IntDouble expressionInput (IntDouble id)
static boolean getDVAliasInitTimeseries (String ident)
static boolean getSVInitTimeseries (String ident)
static IntDouble getTimeSeries (String ident, ArrayList< IntDouble > idArray)
static void initSumExpression (IntDouble id1, IntDouble id2, String s, Stack< LoopIndex > sumIndex)
static IntDouble intFunc (IntDouble id1)
static IntDouble log (IntDouble id1)
static IntDouble log10 (IntDouble id1)
static IntDouble max (IntDouble id1, IntDouble id2)
static IntDouble min (IntDouble id1, IntDouble id2)
static IntDouble mod (IntDouble id1, IntDouble id2)
static IntDouble mult (IntDouble id1, IntDouble id2)
static IntDouble noArgFunction (String ident)
static IntDouble pastCycleIndexNoTimeArray (String ident, int index)
static IntDouble pastCycleIndexTimeArray (String ident, int pci, IntDouble id)
static IntDouble pastCycleNoTimeArray (String ident, String cycle)
static IntDouble pastCycleTimeArray (String ident, String cycle, IntDouble id)
static IntDouble pastTSFV (String ident, IntDouble id1, ArrayList< ArrayList< IntDouble > > idArray, ParallelVars prvs)
static IntDouble pow (IntDouble id1, IntDouble id2)
static boolean range (String m1, String m2)
static IntDouble realFunc (IntDouble id1)
static boolean relationStatement (IntDouble id1, IntDouble id2, String relation)
static boolean relationStatementSeries (boolean r1, boolean r2, String s)
static IntDouble round (IntDouble id1)
static void setSvarDoubleValue (IntDouble id, double value)
static void setSvarIntValue (IntDouble id, int value)
static IntDouble sin (IntDouble id1)
static IntDouble substract (IntDouble id1, IntDouble id2)
static IntDouble sumExpression (IntDouble id, String expression, Stack< LoopIndex > sumIndex)
static void sumExpression_IDENT (String ident, Stack< LoopIndex > sumIndex)
static double svarTimeSeries (String ident, int idValue, ParallelVars prvs)
static IntDouble tableSQL (String table, String select, HashMap< String, Number > where, HashMap< String, Number > given, String use)
static double tafcfs (String ident, ParallelVars prvs)
static IntDouble tafcfs_term (String ident, IntDouble id)
static IntDouble tan (IntDouble id1)
static IntDouble term_ARRAY_ITERATOR (ParallelVars prvs)
static IntDouble term_DAY ()
static IntDouble term_FLOAT (String floatValue)
static IntDouble term_IDENT (String ident, Stack< LoopIndex > sumIndex)
static IntDouble term_INTEGER (String integer)
static IntDouble term_knownTS (IntDouble result)
static IntDouble term_MONTH ()
static IntDouble term_MONTH_CONST (String month)
static IntDouble term_PASTMONTH (String pastMonth)
static IntDouble term_SVAR (String ident)
static IntDouble term_YEAR ()
static IntDouble timeseries ()
static double timeseries (String tsName)
static int timeSeriesIndex (DssDataSet dds, ParallelVars prvs)
static int timeSeriesIndex (DssDataSetFixLength dds, ParallelVars prvs)
static ArrayList< IntDouble > trunk_timeArray (String ident, IntDouble start, IntDouble end)
static IntDouble unary (String s, IntDouble id)
Detailed Description
Definition at line 28 of file ValueEvaluation.java.
Member Function Documentation
abs()
IntDouble wrimsv2.evaluator.ValueEvaluation.abs (IntDouble id1) static
Definition at line 1105 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
acos()
IntDouble wrimsv2.evaluator.ValueEvaluation.acos (IntDouble id1) static
Definition at line 1192 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
acot()
IntDouble wrimsv2.evaluator.ValueEvaluation.acot (IntDouble id1) static
Definition at line 1204 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
add()
IntDouble wrimsv2.evaluator.ValueEvaluation.add (IntDouble id1, IntDouble id2) static
Definition at line 254 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
Referenced by sumExpression().
argFunction()
IntDouble wrimsv2.evaluator.ValueEvaluation.argFunction (String ident, ArrayList< ArrayList< IntDouble > > idArray) static
Definition at line 314 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.allExternalFunctionMap, wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.ControlData.currTsMap, wrimsv2.external.ExternalFunction.execute(), getTimeSeries(), wrimsv2.evaluator.TimeOperation.month_const, setSvarDoubleValue(), and setSvarIntValue().
Referenced by wrimsv2.evaluator.Evaluation.trunk_timeArray(), and trunk_timeArray().
asin()
IntDouble wrimsv2.evaluator.ValueEvaluation.asin (IntDouble id1) static
Definition at line 1186 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
assignWhereStatement()
Number wrimsv2.evaluator.ValueEvaluation.assignWhereStatement (IntDouble id) static
Definition at line 1461 of file ValueEvaluation.java.
atan()
IntDouble wrimsv2.evaluator.ValueEvaluation.atan (IntDouble id1) static
Definition at line 1198 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
convertDoubleToString()
String wrimsv2.evaluator.ValueEvaluation.convertDoubleToString (double value) static
Definition at line 37 of file ValueEvaluation.java.
convertIntToString()
String wrimsv2.evaluator.ValueEvaluation.convertIntToString (int value) static
Definition at line 41 of file ValueEvaluation.java.
convertStringToDouble()
double wrimsv2.evaluator.ValueEvaluation.convertStringToDouble (String text) static
Definition at line 29 of file ValueEvaluation.java.
Referenced by term_FLOAT().
convertStringToInt()
int wrimsv2.evaluator.ValueEvaluation.convertStringToInt (String text) static
Definition at line 33 of file ValueEvaluation.java.
Referenced by initSumExpression(), and term_INTEGER().
cos()
IntDouble wrimsv2.evaluator.ValueEvaluation.cos (IntDouble id1) static
Definition at line 1165 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
cot()
IntDouble wrimsv2.evaluator.ValueEvaluation.cot (IntDouble id1) static
Definition at line 1177 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
daysIn()
IntDouble wrimsv2.evaluator.ValueEvaluation.daysIn () static
Definition at line 1285 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, and wrimsv2.evaluator.TimeOperation.numberOfDays().
Referenced by daysInTimeStep().
daysInTimeStep()
IntDouble wrimsv2.evaluator.ValueEvaluation.daysInTimeStep () static
Definition at line 1290 of file ValueEvaluation.java.
References daysIn(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), and wrimsv2.components.ControlData.timeStep.
divide()
IntDouble wrimsv2.evaluator.ValueEvaluation.divide (IntDouble id1, IntDouble id2) static
Definition at line 212 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
dvarAliasCycleTimeSeries()
double wrimsv2.evaluator.ValueEvaluation.dvarAliasCycleTimeSeries (String ident, int indexValue, int ci, ParallelVars prvs) static
Definition at line 655 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asFutMap, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTSCycles, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by pastCycleIndexTimeArray(), and pastCycleTimeArray().
dvarAliasTimeSeries() [1/2]
double wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries (String ident, int indexValue, ParallelVars prvs) static
Definition at line 580 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asFutMap, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currEvalTypeIndex, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
dvarAliasTimeSeries() [2/2]
double wrimsv2.evaluator.ValueEvaluation.dvarAliasTimeSeries (String ident, ParallelVars prvs) static
Definition at line 531 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.components.ControlData.startDay, wrimsv2.components.ControlData.startMonth, wrimsv2.components.ControlData.startYear, timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by getTimeSeries().
exceedance()
IntDouble wrimsv2.evaluator.ValueEvaluation.exceedance (String tsName, IntDouble exc_id, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr) static
Definition at line 1213 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSet.getExceedance(), wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.TimeOperation.monthValue(), wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.components.ControlData.timeStep.
exceedance_tsi()
IntDouble wrimsv2.evaluator.ValueEvaluation.exceedance_tsi (String tsName, IntDouble exc_id, String selMon, String syStr, String smStr, String sdStr, String eyStr, String emStr, String edStr) static
Definition at line 1249 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSet.getExceedance_tsi(), wrimsv2.evaluator.DssDataSet.getTimeseriesDataWithOptions(), wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.TimeOperation.monthValue(), wrimsv2.evaluator.TimeOperation.numberOfDays(), wrimsv2.evaluator.DataTimeSeries.svTS, and wrimsv2.components.ControlData.timeStep.
exp()
IntDouble wrimsv2.evaluator.ValueEvaluation.exp (IntDouble id1) static
Definition at line 1115 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
expressionInput()
IntDouble wrimsv2.evaluator.ValueEvaluation.expressionInput (IntDouble id) static
Definition at line 1474 of file ValueEvaluation.java.
getDVAliasInitTimeseries()
boolean wrimsv2.evaluator.ValueEvaluation.getDVAliasInitTimeseries (String ident) static
Definition at line 721 of file ValueEvaluation.java.
References wrimsv2.evaluator.DssOperation.getDVAliasInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getDVAliasInitTimeseries(), and wrimsv2.components.ControlData.initHDF5.
Referenced by dvarAliasCycleTimeSeries(), dvarAliasTimeSeries(), dvarAliasTimeSeries(), and pastTSFV().
getSVInitTimeseries()
boolean wrimsv2.evaluator.ValueEvaluation.getSVInitTimeseries (String ident) static
Definition at line 523 of file ValueEvaluation.java.
References wrimsv2.evaluator.DssOperation.getSVInitTimeseries(), wrimsv2.hdf5.HDF5Reader.getSVInitTimeseries(), and wrimsv2.components.ControlData.initHDF5.
Referenced by svarTimeSeries().
getTimeSeries()
IntDouble wrimsv2.evaluator.ValueEvaluation.getTimeSeries (String ident, ArrayList< IntDouble > idArray) static
Definition at line 421 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currSvFutMap, wrimsv2.components.ControlData.currSvMap, dvarAliasTimeSeries(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.components.ControlData.ignoreError, and svarTimeSeries().
Referenced by argFunction().
initSumExpression()
void wrimsv2.evaluator.ValueEvaluation.initSumExpression (IntDouble id1, IntDouble id2, String s, Stack< LoopIndex > sumIndex) static
Definition at line 1381 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), convertStringToInt(), wrimsv2.evaluator.LoopIndex.end, wrimsv2.components.IntDouble.getData(), wrimsv2.components.ControlData.ignoreError, wrimsv2.components.IntDouble.isInt(), wrimsv2.evaluator.LoopIndex.setIndexStart(), wrimsv2.evaluator.LoopIndex.setValue(), wrimsv2.evaluator.LoopIndex.start, and wrimsv2.evaluator.LoopIndex.step.
intFunc()
IntDouble wrimsv2.evaluator.ValueEvaluation.intFunc (IntDouble id1) static
Definition at line 1087 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
log()
IntDouble wrimsv2.evaluator.ValueEvaluation.log (IntDouble id1) static
Definition at line 1125 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
log10()
IntDouble wrimsv2.evaluator.ValueEvaluation.log10 (IntDouble id1) static
Definition at line 1135 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
max()
IntDouble wrimsv2.evaluator.ValueEvaluation.max (IntDouble id1, IntDouble id2) static
Definition at line 1059 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
min()
IntDouble wrimsv2.evaluator.ValueEvaluation.min (IntDouble id1, IntDouble id2) static
Definition at line 1073 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
mod()
IntDouble wrimsv2.evaluator.ValueEvaluation.mod (IntDouble id1, IntDouble id2) static
Definition at line 230 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
mult()
IntDouble wrimsv2.evaluator.ValueEvaluation.mult (IntDouble id1, IntDouble id2) static
Definition at line 198 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
noArgFunction()
IntDouble wrimsv2.evaluator.ValueEvaluation.noArgFunction (String ident) static
Definition at line 282 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.allExternalFunctionMap, and wrimsv2.external.ExternalFunction.execute().
pastCycleIndexNoTimeArray()
IntDouble wrimsv2.evaluator.ValueEvaluation.pastCycleIndexNoTimeArray (String ident, int index) static
Definition at line 886 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), and wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap().
Referenced by pastCycleIndexTimeArray().
pastCycleIndexTimeArray()
IntDouble wrimsv2.evaluator.ValueEvaluation.pastCycleIndexTimeArray (String ident, int pci, IntDouble id) static
Definition at line 964 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currCycleIndex, wrimsv2.components.ControlData.currStudyDataSet, dvarAliasCycleTimeSeries(), wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.components.IntDouble.isInt(), and pastCycleIndexNoTimeArray().
pastCycleNoTimeArray()
IntDouble wrimsv2.evaluator.ValueEvaluation.pastCycleNoTimeArray (String ident, String cycle) static
Definition at line 783 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), and wrimsv2.components.IntDouble.isInt().
Referenced by pastCycleTimeArray().
pastCycleTimeArray()
IntDouble wrimsv2.evaluator.ValueEvaluation.pastCycleTimeArray (String ident, String cycle, IntDouble id) static
Definition at line 906 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.commondata.wresldata.ModelDataSet.asMap, wrimsv2.components.ControlData.currStudyDataSet, dvarAliasCycleTimeSeries(), wrimsv2.commondata.wresldata.ModelDataSet.dvMap, wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.StudyDataSet.getModelDataSetMap(), wrimsv2.commondata.wresldata.StudyDataSet.getModelList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.components.IntDouble.isInt(), and pastCycleNoTimeArray().
pastTSFV()
IntDouble wrimsv2.evaluator.ValueEvaluation.pastTSFV (String ident, IntDouble id1, ArrayList< ArrayList< IntDouble > > idArray, ParallelVars prvs) static
Definition at line 805 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDay, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.evaluator.DataTimeSeries.dvAliasInit, wrimsv2.evaluator.DataTimeSeries.dvAliasTS, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSetFixLength.getData(), getDVAliasInitTimeseries(), wrimsv2.evaluator.TimeOperation.getNumberOfTimestep(), wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), wrimsv2.components.IntDouble.isInt(), timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
pow()
IntDouble wrimsv2.evaluator.ValueEvaluation.pow (IntDouble id1, IntDouble id2) static
Definition at line 1145 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
range()
boolean wrimsv2.evaluator.ValueEvaluation.range (String m1, String m2) static
Definition at line 106 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.evaluator.TimeOperation.range().
realFunc()
IntDouble wrimsv2.evaluator.ValueEvaluation.realFunc (IntDouble id1) static
Definition at line 1096 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
relationStatement()
boolean wrimsv2.evaluator.ValueEvaluation.relationStatement (IntDouble id1, IntDouble id2, String relation) static
Definition at line 45 of file ValueEvaluation.java.
References wrimsv2.solver.CbcSolver.cbcSolutionRounding, wrimsv2.components.IntDouble.getData(), wrimsv2.components.ControlData.relationTolerance, and wrimsv2.components.ControlData.solverName.
relationStatementSeries()
boolean wrimsv2.evaluator.ValueEvaluation.relationStatementSeries (boolean r1, boolean r2, String s) static
Definition at line 110 of file ValueEvaluation.java.
round()
IntDouble wrimsv2.evaluator.ValueEvaluation.round (IntDouble id1) static
Definition at line 248 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
Referenced by wrimsv2.evaluator.Evaluation.round().
setSvarDoubleValue()
void wrimsv2.evaluator.ValueEvaluation.setSvarDoubleValue (IntDouble id, double value) static
Definition at line 1494 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currSvFutMap, and wrimsv2.components.ControlData.currSvMap.
Referenced by wrimsv2.evaluator.Evaluation.argFunction(), and argFunction().
setSvarIntValue()
void wrimsv2.evaluator.ValueEvaluation.setSvarIntValue (IntDouble id, int value) static
Definition at line 1478 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currSvFutMap, and wrimsv2.components.ControlData.currSvMap.
Referenced by wrimsv2.evaluator.Evaluation.argFunction(), and argFunction().
sin()
IntDouble wrimsv2.evaluator.ValueEvaluation.sin (IntDouble id1) static
Definition at line 1159 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
substract()
IntDouble wrimsv2.evaluator.ValueEvaluation.substract (IntDouble id1, IntDouble id2) static
Definition at line 268 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
sumExpression()
IntDouble wrimsv2.evaluator.ValueEvaluation.sumExpression (IntDouble id, String expression, Stack< LoopIndex > sumIndex) static
Definition at line 1405 of file ValueEvaluation.java.
References add(), wrimsv2.components.Error.addEvaluationError(), wrimsv2.evaluator.LoopIndex.end, wrimsv2.components.ControlData.ignoreError, wrimsv2.evaluator.LoopIndex.setIndexStart(), wrimsv2.evaluator.LoopIndex.setValue(), wrimsv2.evaluator.LoopIndex.start, and wrimsv2.evaluator.LoopIndex.step.
sumExpression_IDENT()
void wrimsv2.evaluator.ValueEvaluation.sumExpression_IDENT (String ident, Stack< LoopIndex > sumIndex) static
Definition at line 1375 of file ValueEvaluation.java.
svarTimeSeries()
double wrimsv2.evaluator.ValueEvaluation.svarTimeSeries (String ident, int idValue, ParallelVars prvs) static
Definition at line 461 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.allowSvTsInit, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.evaluator.TimeOperation.findTime(), wrimsv2.evaluator.DssDataSet.fromDssFile, wrimsv2.evaluator.DssDataSet.getData(), wrimsv2.evaluator.DssDataSet.getStudyStartIndex(), getSVInitTimeseries(), wrimsv2.evaluator.DataTimeSeries.lookInitDss, wrimsv2.evaluator.DataTimeSeries.svInit, wrimsv2.evaluator.DataTimeSeries.svTS, timeSeriesIndex(), and wrimsv2.components.ControlData.timeStep.
Referenced by getTimeSeries(), timeseries(), and timeseries().
tableSQL()
IntDouble wrimsv2.evaluator.ValueEvaluation.tableSQL (String table, String select, HashMap< String, Number > where, HashMap< String, Number > given, String use) static
Definition at line 1465 of file ValueEvaluation.java.
References wrimsv2.evaluator.TableOperation.findData().
tafcfs()
double wrimsv2.evaluator.ValueEvaluation.tafcfs (String ident, ParallelVars prvs) static
Definition at line 1314 of file ValueEvaluation.java.
References wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.TimeOperation.isMonthlyInterval(), wrimsv2.evaluator.TimeOperation.numberOfDays(), and wrimsv2.components.ControlData.timeStep.
Referenced by tafcfs_term().
tafcfs_term()
IntDouble wrimsv2.evaluator.ValueEvaluation.tafcfs_term (String ident, IntDouble id) static
Definition at line 1299 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currMonth, wrimsv2.components.ControlData.currYear, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.TimeOperation.findTime(), and tafcfs().
tan()
IntDouble wrimsv2.evaluator.ValueEvaluation.tan (IntDouble id1) static
Definition at line 1171 of file ValueEvaluation.java.
References wrimsv2.components.IntDouble.getData().
term_ARRAY_ITERATOR()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_ARRAY_ITERATOR (ParallelVars prvs) static
Definition at line 1371 of file ValueEvaluation.java.
References wrimsv2.parallel.ParallelVars.timeArrayIndex.
term_DAY()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_DAY () static
Definition at line 1352 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currDay.
term_FLOAT()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_FLOAT (String floatValue) static
Definition at line 180 of file ValueEvaluation.java.
References convertStringToDouble().
term_IDENT()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_IDENT (String ident, Stack< LoopIndex > sumIndex) static
Definition at line 122 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currAliasMap, wrimsv2.components.ControlData.currDvMap, wrimsv2.components.ControlData.currSvMap, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.LoopIndex.getIndexStart(), wrimsv2.evaluator.LoopIndex.getName(), wrimsv2.evaluator.LoopIndex.getValue(), wrimsv2.components.IntDouble.isInt(), wrimsv2.components.ControlData.isPostProcessing, and wrimsv2.components.ControlData.parameterMap.
term_INTEGER()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_INTEGER (String integer) static
Definition at line 176 of file ValueEvaluation.java.
References convertStringToInt().
term_knownTS()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_knownTS (IntDouble result) static
Definition at line 118 of file ValueEvaluation.java.
term_MONTH()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_MONTH () static
Definition at line 1348 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.evaluator.TimeOperation.waterMonthValue().
term_MONTH_CONST()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_MONTH_CONST (String month) static
Definition at line 1356 of file ValueEvaluation.java.
References wrimsv2.evaluator.TimeOperation.monthValue(), and wrimsv2.evaluator.TimeOperation.waterMonthValue().
term_PASTMONTH()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_PASTMONTH (String pastMonth) static
Definition at line 1361 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currMonth, and wrimsv2.evaluator.TimeOperation.monthValue().
term_SVAR()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_SVAR (String ident) static
Definition at line 156 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), wrimsv2.components.ControlData.currSvMap, wrimsv2.components.ControlData.currTsMap, wrimsv2.components.IntDouble.getData(), and wrimsv2.components.IntDouble.isInt().
term_YEAR()
IntDouble wrimsv2.evaluator.ValueEvaluation.term_YEAR () static
Definition at line 1344 of file ValueEvaluation.java.
References wrimsv2.evaluator.TimeOperation.waterYearValue().
timeseries() [1/2]
IntDouble wrimsv2.evaluator.ValueEvaluation.timeseries () static
Definition at line 771 of file ValueEvaluation.java.
References wrimsv2.components.ControlData.currEvalName, wrimsv2.evaluator.TimeOperation.findTime(), and svarTimeSeries().
timeseries() [2/2]
double wrimsv2.evaluator.ValueEvaluation.timeseries (String tsName) static
Definition at line 778 of file ValueEvaluation.java.
References wrimsv2.evaluator.TimeOperation.findTime(), and svarTimeSeries().
timeSeriesIndex() [1/2]
int wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex (DssDataSet dds, ParallelVars prvs) static
Definition at line 729 of file ValueEvaluation.java.
References wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.DssDataSet.getStartTime(), wrimsv2.evaluator.DssDataSet.getTimeStep(), and wrimsv2.evaluator.TimeOperation.isMonthlyInterval().
Referenced by dvarAliasCycleTimeSeries(), dvarAliasTimeSeries(), dvarAliasTimeSeries(), wrimsv2.components.DebugInterface.getTimeseriesDetail(), wrimsv2.components.DebugInterface.modifyTimeSeries(), pastTSFV(), svarTimeSeries(), and wrimsv2.components.ControllerDebug.updateVarMonitor().
timeSeriesIndex() [2/2]
int wrimsv2.evaluator.ValueEvaluation.timeSeriesIndex (DssDataSetFixLength dds, ParallelVars prvs) static
Definition at line 750 of file ValueEvaluation.java.
References wrimsv2.parallel.ParallelVars.dataDay, wrimsv2.parallel.ParallelVars.dataMonth, wrimsv2.parallel.ParallelVars.dataYear, wrimsv2.evaluator.DssDataSetFixLength.getStartTime(), wrimsv2.evaluator.DssDataSetFixLength.getTimeStep(), and wrimsv2.evaluator.TimeOperation.isMonthlyInterval().
trunk_timeArray()
ArrayList< IntDouble > wrimsv2.evaluator.ValueEvaluation.trunk_timeArray (String ident, IntDouble start, IntDouble end) static
Definition at line 1017 of file ValueEvaluation.java.
References wrimsv2.components.Error.addEvaluationError(), argFunction(), wrimsv2.components.IntDouble.getData(), wrimsv2.components.IntDouble.isInt(), and wrimsv2.components.IntDouble.setIndex().
unary()
IntDouble wrimsv2.evaluator.ValueEvaluation.unary (String s, IntDouble id) static
Definition at line 184 of file ValueEvaluation.java.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/evaluator/ValueEvaluation.java