Wrims-engine: wrimsv2.hdf5.HDF5Util Class Reference
wrimsv2.hdf5.HDF5Util Class Reference
Static Public Member Functions
static int locateFile (String fileName)
static int locateGroup (int id, String group)
static String readStringAttr (int aid, int tid, int stringLength)
static String[] readStringData (int did, int tid, int size, int stringLength)
static void writeCycleDynamicSv (ModelDataSet mds, int gid, String dName)
static void writeCycleStaticSv (int index, int size, int gid, double[][] write_data)
static void writeCycleStaticSvNames (ModelDataSet mds, int gid, int index)
static void writeCycleVariableNames (String[] write_data, int gid, String strCycleI)
static void writeStringAttr (int aid, int tid, String[] stringArray, int stringLength)
static void writeStringData (int did, int tid, String[] stringArray, int stringLength)
Detailed Description
Definition at line 21 of file HDF5Util.java.
Member Function Documentation
locateFile()
int wrimsv2.hdf5.HDF5Util.locateFile (String fileName) static
Definition at line 23 of file HDF5Util.java.
Referenced by wrimsv2.hdf5.HDF5Writer.createDataStructure(), wrimsv2.hdf5.DSSHDF5Converter.createInitHDF5DataStructure(), and wrimsv2.hdf5.DSSHDF5Converter.createSVHDF5DataStructure().
locateGroup()
int wrimsv2.hdf5.HDF5Util.locateGroup (int id, String group) static
Definition at line 42 of file HDF5Util.java.
Referenced by wrimsv2.hdf5.HDF5Writer.createDataStructure(), wrimsv2.hdf5.DSSHDF5Converter.createInitHDF5DataStructure(), wrimsv2.hdf5.DSSHDF5Converter.createSVHDF5DataStructure(), and wrimsv2.hdf5.HDF5Reader.openFileAndGroup().
readStringAttr()
String wrimsv2.hdf5.HDF5Util.readStringAttr (int aid, int tid, int stringLength) static
Definition at line 148 of file HDF5Util.java.
Referenced by wrimsv2.hdf5.HDF5Reader.openFileAndGroup().
readStringData()
String[] wrimsv2.hdf5.HDF5Util.readStringData (int did, int tid, int size, int stringLength) static
Definition at line 101 of file HDF5Util.java.
Referenced by wrimsv2.hdf5.HDF5Reader.readDailyTimestepList(), wrimsv2.hdf5.HDF5Reader.readLookupTable(), and wrimsv2.hdf5.HDF5Reader.readMonthlyTimestepList().
writeCycleDynamicSv()
void wrimsv2.hdf5.HDF5Util.writeCycleDynamicSv (ModelDataSet mds, int gid, String dName) static
Definition at line 325 of file HDF5Util.java.
References wrimsv2.commondata.wresldata.Svar.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.wresldata.ModelDataSet.svFutMap, and writeStringData().
Referenced by wrimsv2.hdf5.HDF5Writer.writeDailyCycleDynamicSv(), and wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleDynamicSv().
writeCycleStaticSv()
void wrimsv2.hdf5.HDF5Util.writeCycleStaticSv (int index, int size, int gid, double write_data[][]) static
Definition at line 199 of file HDF5Util.java.
References wrimsv2.components.ControlData.currTimeStep.
Referenced by wrimsv2.hdf5.HDF5Writer.skipDailyCycleStaticSv(), wrimsv2.hdf5.HDF5Writer.skipMonthlyCycleStaticSv(), wrimsv2.hdf5.HDF5Writer.writeDailyCycleStaticSv(), and wrimsv2.hdf5.HDF5Writer.writeMonthlyCycleStaticSv().
writeCycleStaticSvNames()
void wrimsv2.hdf5.HDF5Util.writeCycleStaticSvNames (ModelDataSet mds, int gid, int index) static
Definition at line 261 of file HDF5Util.java.
References wrimsv2.commondata.wresldata.ModelDataSet.svList, and writeStringData().
Referenced by wrimsv2.hdf5.HDF5Writer.listCycleStaticSv().
writeCycleVariableNames()
void wrimsv2.hdf5.HDF5Util.writeCycleVariableNames (String[] write_data, int gid, String strCycleI) static
Definition at line 162 of file HDF5Util.java.
References writeStringData().
Referenced by wrimsv2.hdf5.HDF5Writer.listCycleDvAliasVariables().
writeStringAttr()
void wrimsv2.hdf5.HDF5Util.writeStringAttr (int aid, int tid, String[] stringArray, int stringLength) static
Definition at line 127 of file HDF5Util.java.
Referenced by wrimsv2.hdf5.HDF5Writer.createDataStructure(), wrimsv2.hdf5.DSSHDF5Converter.createInitHDF5DataStructure(), and wrimsv2.hdf5.DSSHDF5Converter.createSVHDF5DataStructure().
writeStringData()
void wrimsv2.hdf5.HDF5Util.writeStringData (int did, int tid, String[] stringArray, int stringLength) static
Definition at line 78 of file HDF5Util.java.
Referenced by wrimsv2.hdf5.HDF5Writer.createDvarAliasLookup(), wrimsv2.hdf5.DSSHDF5Converter.createInitLookup(), wrimsv2.hdf5.DSSHDF5Converter.createSVLookup(), wrimsv2.hdf5.DSSHDF5Converter.listDailyInitHDF5File(), wrimsv2.hdf5.DSSHDF5Converter.listDailySVHDF5File(), wrimsv2.hdf5.HDF5Writer.listDailyTimestepDvarAlias(), wrimsv2.hdf5.DSSHDF5Converter.listMonthlyInitHDF5File(), wrimsv2.hdf5.DSSHDF5Converter.listMonthlySVHDF5File(), wrimsv2.hdf5.HDF5Writer.listMonthlyTimestepDvarAlias(), writeCycleDynamicSv(), writeCycleStaticSvNames(), and writeCycleVariableNames().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/hdf5/HDF5Util.java