Wrims-engine: wrimsv2.solver.Gurobi.GurobiSolver Class Reference
wrimsv2.solver.Gurobi.GurobiSolver Class Reference
Public Member Functions
GurobiSolver () throws GRBException
void setDVars () throws GRBException
Static Public Member Functions
static void addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName)
static void assignDvar ()
static void dispose ()
static void initialize ()
static void setLp (String CplexLpFilePath)
static void solve ()
Static Public Attributes
static Map< String, Double > varDoubleMap
Package Attributes
int modelStatus
Map< String, GRBVar > varMap = new HashMap <String, GRBVar> ()
Static Package Attributes
static GRBEnv env
static GRBModel model
Private Member Functions
void checkStatus () throws GRBException
void Output () throws GRBException
void setConstraints () throws GRBException
Static Private Member Functions
static void collectDvar (LpResult lpResult)
Detailed Description
Definition at line 55 of file GurobiSolver.java.
Constructor & Destructor Documentation
GurobiSolver()
wrimsv2.solver.Gurobi.GurobiSolver.GurobiSolver () throws GRBException
Definition at line 107 of file GurobiSolver.java.
References assignDvar(), model, Output(), setConstraints(), and setDVars().
Member Function Documentation
addConditionalSlackSurplusToDvarMap()
void wrimsv2.solver.Gurobi.GurobiSolver.addConditionalSlackSurplusToDvarMap (Map< String, Dvar > dvarMap, String multName) static
Definition at line 416 of file GurobiSolver.java.
References wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, and wrimsv2.commondata.wresldata.Dvar.upperBoundValue.
assignDvar()
void wrimsv2.solver.Gurobi.GurobiSolver.assignDvar () static
Definition at line 250 of file GurobiSolver.java.
References wrimsv2.components.ControlData.currCycleName, wrimsv2.components.ControlData.currModelDataSet, wrimsv2.components.ControlData.currStudyDataSet, wrimsv2.commondata.wresldata.Dvar.data, wrimsv2.commondata.wresldata.ModelDataSet.dvarTimeArrayUsedByLaterCycle, wrimsv2.commondata.wresldata.ModelDataSet.dvarUsedByLaterCycle, wrimsv2.evaluator.DssOperation.entryNameTS(), wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.components.IntDouble.getData(), wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.StudyDataSet.getDvarTimeArrayCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexList(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleIndexValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarCycleValueMap(), wrimsv2.commondata.wresldata.StudyDataSet.getVarTimeArrayCycleValueMap(), wrimsv2.components.ControlData.lpsolve_objective, model, wrimsv2.evaluator.DataTimeSeries.saveDataToTimeSeries(), wrimsv2.commondata.wresldata.Dvar.setData(), wrimsv2.components.ControlData.showRunTimeMessage, wrimsv2.commondata.wresldata.ModelDataSet.timeArrayDvList, wrimsv2.components.ControlData.timeStep, and varDoubleMap.
Referenced by GurobiSolver(), and solve().
checkStatus()
void wrimsv2.solver.Gurobi.GurobiSolver.checkStatus () throws GRBException private
Definition at line 339 of file GurobiSolver.java.
References model.
collectDvar()
void wrimsv2.solver.Gurobi.GurobiSolver.collectDvar (LpResult lpResult) static private
Definition at line 321 of file GurobiSolver.java.
References varDoubleMap, wrimsv2.solver.Gurobi.LpResult.varNames, and wrimsv2.solver.Gurobi.LpResult.varValues.
Referenced by solve().
dispose()
void wrimsv2.solver.Gurobi.GurobiSolver.dispose () static
Definition at line 93 of file GurobiSolver.java.
References env, and model.
Referenced by wrimsv2.solver.CloseCurrentSolver.CloseCurrentSolver(), wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), and wrimsv2.components.ControllerBatch.runModelGurobiTest().
initialize()
void wrimsv2.solver.Gurobi.GurobiSolver.initialize () static
Definition at line 64 of file GurobiSolver.java.
References env.
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobiTest(), wrimsv2.components.ControllerDebug.runModelSolvers(), and wrimsv2.components.DebugInterface.setSolverOptions().
Output()
void wrimsv2.solver.Gurobi.GurobiSolver.Output () throws GRBException private
Definition at line 403 of file GurobiSolver.java.
References wrimsv2.components.ControlData.currDvMap, wrimsv2.commondata.wresldata.Dvar.getData(), wrimsv2.components.IntDouble.getData(), and model.
Referenced by GurobiSolver().
setConstraints()
void wrimsv2.solver.Gurobi.GurobiSolver.setConstraints () throws GRBException private
Definition at line 216 of file GurobiSolver.java.
References wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap(), wrimsv2.components.IntDouble.getData(), wrimsv2.evaluator.EvalConstraint.getEvalExpression(), wrimsv2.evaluator.EvalExpression.getMultiplier(), wrimsv2.evaluator.EvalConstraint.getSign(), wrimsv2.evaluator.EvalExpression.getValue(), model, and varMap.
Referenced by GurobiSolver().
setDVars()
void wrimsv2.solver.Gurobi.GurobiSolver.setDVars () throws GRBException
Definition at line 184 of file GurobiSolver.java.
References wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.wresldata.Dvar.lowerBoundValue, model, wrimsv2.commondata.wresldata.Dvar.upperBoundValue, and varMap.
Referenced by GurobiSolver().
setLp()
void wrimsv2.solver.Gurobi.GurobiSolver.setLp (String CplexLpFilePath) static
Definition at line 78 of file GurobiSolver.java.
References wrimsv2.components.Error.addSolvingError(), env, and model.
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobiTest(), and wrimsv2.components.ControllerDebug.runModelSolvers().
solve()
void wrimsv2.solver.Gurobi.GurobiSolver.solve () static
Definition at line 117 of file GurobiSolver.java.
References wrimsv2.components.Error.addSolvingError(), assignDvar(), collectDvar(), env, wrimsv2.components.ControlData.gurobi_objective, wrimsv2.components.FilePaths.mainDirectory, and model.
Referenced by wrimsv2.components.Controller.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobi(), wrimsv2.components.ControllerBatch.runModelGurobiTest(), and wrimsv2.components.ControllerDebug.runModelSolvers().
Member Data Documentation
env
GRBEnv wrimsv2.solver.Gurobi.GurobiSolver.env static package
Definition at line 58 of file GurobiSolver.java.
Referenced by dispose(), initialize(), setLp(), and solve().
model
GRBModel wrimsv2.solver.Gurobi.GurobiSolver.model static package
Definition at line 59 of file GurobiSolver.java.
Referenced by GurobiSolver(), assignDvar(), checkStatus(), dispose(), Output(), setConstraints(), setDVars(), setLp(), and solve().
modelStatus
int wrimsv2.solver.Gurobi.GurobiSolver.modelStatus package
Definition at line 57 of file GurobiSolver.java.
varDoubleMap
Map<String, Double> wrimsv2.solver.Gurobi.GurobiSolver.varDoubleMap static
Definition at line 60 of file GurobiSolver.java.
Referenced by assignDvar(), collectDvar(), and wrimsv2.ilp.ILP.writeDvarValue_Gurobi().
varMap
Map<String, GRBVar> wrimsv2.solver.Gurobi.GurobiSolver.varMap = new HashMap <String, GRBVar> () package
Definition at line 62 of file GurobiSolver.java.
Referenced by setConstraints(), and setDVars().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/solver/Gurobi/GurobiSolver.java