Wrims-engine: wrimsv2.ilp.AmplWriter Class Reference
wrimsv2.ilp.AmplWriter Class Reference
Static Public Member Functions
static void writeComment (PrintWriter outFile, String msg)
static void writeObjValue ()
Static Protected Member Functions
static void writeConstraint (PrintWriter outFile)
static void writeDvar (PrintWriter outFile, Set< String > dvar_effective)
static void writeDvar (PrintWriter outFile, Set< String > dvar_weighted, Set< String > dvar_unWeighted)
static void writeDvarValue (PrintWriter dvarFile, Set< String > dvar_effective)
static void writeObj (PrintWriter outFile, Map< String, WeightElement > activeWeightMap)
static void writeSvarValue (PrintWriter svarFile)
Private Member Functions
AmplWriter ()
Detailed Description
Definition at line 20 of file AmplWriter.java.
Constructor & Destructor Documentation
AmplWriter()
wrimsv2.ilp.AmplWriter.AmplWriter () private
Definition at line 22 of file AmplWriter.java.
Member Function Documentation
writeComment()
void wrimsv2.ilp.AmplWriter.writeComment (PrintWriter outFile, String msg) static
Definition at line 90 of file AmplWriter.java.
writeConstraint()
void wrimsv2.ilp.AmplWriter.writeConstraint (PrintWriter outFile) static protected
Definition at line 144 of file AmplWriter.java.
References wrimsv2.commondata.solverdata.SolverData.getConstraintDataMap().
Referenced by wrimsv2.ilp.ILP.writeAmplFile().
writeDvar() [1/2]
void wrimsv2.ilp.AmplWriter.writeDvar (PrintWriter outFile, Set< String > dvar_effective) static protected
Definition at line 329 of file AmplWriter.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.Param.lower_unbounded, wrimsv2.commondata.wresldata.Param.upper_unbounded, wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, and wrimsv2.commondata.wresldata.Param.yes.
writeDvar() [2/2]
void wrimsv2.ilp.AmplWriter.writeDvar (PrintWriter outFile, Set< String > dvar_weighted, Set< String > dvar_unWeighted) static protected
Definition at line 217 of file AmplWriter.java.
References wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.wresldata.Param.lower_unbounded, wrimsv2.commondata.wresldata.Param.upper_unbounded, and wrimsv2.commondata.wresldata.Param.yes.
Referenced by wrimsv2.ilp.ILP.writeAmplFile().
writeDvarValue()
void wrimsv2.ilp.AmplWriter.writeDvarValue (PrintWriter dvarFile, Set< String > dvar_effective) static protected
Definition at line 45 of file AmplWriter.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getDvarMap(), wrimsv2.commondata.solverdata.SolverData.getWeightMap(), wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList, and wrimsv2.components.ControlData.xasolver.
writeObj()
void wrimsv2.ilp.AmplWriter.writeObj (PrintWriter outFile, Map< String, WeightElement > activeWeightMap) static protected
Definition at line 103 of file AmplWriter.java.
References wrimsv2.components.ControlData.currModelDataSet, wrimsv2.commondata.solverdata.SolverData.getWeightMap(), and wrimsv2.commondata.wresldata.ModelDataSet.usedWtSlackSurplusList.
Referenced by wrimsv2.ilp.ILP.writeAmplFile().
writeObjValue()
void wrimsv2.ilp.AmplWriter.writeObjValue () static
Definition at line 97 of file AmplWriter.java.
writeSvarValue()
void wrimsv2.ilp.AmplWriter.writeSvarValue (PrintWriter svarFile) static protected
Definition at line 76 of file AmplWriter.java.
References wrimsv2.components.ControlData.currSvMap.
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/ilp/AmplWriter.java