Wrims-engine: wrimsv2.tools.solutionRangeFinder.Misc Class Reference
wrimsv2.tools.solutionRangeFinder.Misc Class Reference
Static Protected Member Functions
static LinkedHashMap< String, double[]> filterVarsRange (LinkedHashMap< String, double[]> varsRange, double min_abs_diff, double min_ratio_diff)
static LinkedHashMap< String, double[]> findVarsRange (ArrayList< LinkedHashMap< String, Double > > allSearchSolutions)
static LinkedHashMap< String, double[]> updateVarsRange (LinkedHashMap< String, double[]> varsRange1, LinkedHashMap< String, double[]> varsRange2)
static LinkedHashMap< String, double[]> updateVarsRange (List< LinkedHashMap< String, double[]> > varsRangeList)
static void writeReport (LinkedHashMap< String, double[]> varRange, PrintWriter reportFile)
static void writeReport (LinkedHashMap< String, double[]> varRange, String dir, String fileName)
Static Package Functions
static PrintWriter openReportFile (String filePath)
Detailed Description
Definition at line 16 of file Misc.java.
Member Function Documentation
filterVarsRange()
LinkedHashMap< String, double[]> wrimsv2.tools.solutionRangeFinder.Misc.filterVarsRange (LinkedHashMap< String, double[]> varsRange, double min_abs_diff, double min_ratio_diff) static protected
Definition at line 101 of file Misc.java.
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions().
findVarsRange()
LinkedHashMap< String, double[]> wrimsv2.tools.solutionRangeFinder.Misc.findVarsRange (ArrayList< LinkedHashMap< String, Double > > allSearchSolutions) static protected
Definition at line 130 of file Misc.java.
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions().
openReportFile()
PrintWriter wrimsv2.tools.solutionRangeFinder.Misc.openReportFile (String filePath) static package
Definition at line 18 of file Misc.java.
References wrimsv2.wreslplus.elements.Tools.openFile().
Referenced by wrimsv2.tools.solutionRangeFinder.Detector.main(), and wrimsv2.tools.solutionRangeFinder.Main.main().
updateVarsRange() [1/2]
LinkedHashMap< String, double[]> wrimsv2.tools.solutionRangeFinder.Misc.updateVarsRange (LinkedHashMap< String, double[]> varsRange1, LinkedHashMap< String, double[]> varsRange2) static protected
Definition at line 188 of file Misc.java.
updateVarsRange() [2/2]
LinkedHashMap< String, double[]> wrimsv2.tools.solutionRangeFinder.Misc.updateVarsRange (List< LinkedHashMap< String, double[]> > varsRangeList) static protected
Definition at line 163 of file Misc.java.
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions().
writeReport() [1/2]
void wrimsv2.tools.solutionRangeFinder.Misc.writeReport (LinkedHashMap< String, double[]> varRange, PrintWriter reportFile) static protected
Definition at line 51 of file Misc.java.
Referenced by wrimsv2.tools.solutionRangeFinder.Detector.main(), and wrimsv2.tools.solutionRangeFinder.Main.main().
writeReport() [2/2]
void wrimsv2.tools.solutionRangeFinder.Misc.writeReport (LinkedHashMap< String, double[]> varRange, String dir, String fileName) static protected
Definition at line 73 of file Misc.java.
References wrimsv2.wreslplus.elements.Tools.openFile().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/solutionRangeFinder/Misc.java