Wrims-engine: wrimsv2.tools.solutionRangeFinder.AltSolutionFinder Class Reference
wrimsv2.tools.solutionRangeFinder.AltSolutionFinder Class Reference
Public Member Functions
AltSolutionFinder (String id, MPModel inModel, List< String > searchVars, int searchObjSign, ArrayList< String > reportVars)
ArrayList< LinkedHashMap< String, Double > > go ()
void setLpsLoggingPath (String dirName, String lpsFileNamePrepend)
Static Public Member Functions
static double createObjFunc (LinkedHashMap< String, Double > out_searchObjFunc, ArrayList< String > vars, int searchObjSign, LinkedHashMap< String, Double > baseSolution)
Private Attributes
MPModel asfModel = null
String id
String lpsDir = ""
String lpsFileNamePrepend = ""
boolean lpsLogging = false
ArrayList< String > reportVars
int searchObjSign
List< String > searchVars
Detailed Description
Definition at line 12 of file AltSolutionFinder.java.
Constructor & Destructor Documentation
AltSolutionFinder()
wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.AltSolutionFinder (String id, MPModel inModel, List< String > searchVars, int searchObjSign, ArrayList< String > reportVars)
Definition at line 30 of file AltSolutionFinder.java.
References id, reportVars, searchObjSign, and searchVars.
Member Function Documentation
createObjFunc()
double wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.createObjFunc (LinkedHashMap< String, Double > out_searchObjFunc, ArrayList< String > vars, int searchObjSign, LinkedHashMap< String, Double > baseSolution) static
Definition at line 121 of file AltSolutionFinder.java.
References searchObjSign.
go()
ArrayList< LinkedHashMap< String, Double > > wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.go ()
Definition at line 50 of file AltSolutionFinder.java.
References asfModel, wrimsv2.tools.solutionRangeFinder.DetectorParam.continueOnErrors, wrimsv2.solver.ortools.OrToolsSolver.delete(), lpsDir, lpsFileNamePrepend, wrimsv2.tools.solutionRangeFinder.DetectorParam.lpsLogging, wrimsv2.wreslplus.elements.Tools.mapRetainAll(), wrimsv2.solver.ortools.OrToolsSolver.model, wrimsv2.solver.ortools.OrToolsSolver.refreshObjFunc(), reportVars, searchObjSign, searchVars, wrimsv2.solver.ortools.OrToolsSolver.setModel(), wrimsv2.tools.solutionRangeFinder.DetectorParam.showSolutionInConsole, wrimsv2.solver.ortools.OrToolsSolver.solution, wrimsv2.solver.ortools.OrToolsSolver.solve(), wrimsv2.solver.ortools.OrToolsSolver.solver, and wrimsv2.solver.mpmodel.MPModelUtils.toLpSolve().
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions().
setLpsLoggingPath()
void wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.setLpsLoggingPath (String dirName, String lpsFileNamePrepend)
Definition at line 42 of file AltSolutionFinder.java.
References id, and lpsFileNamePrepend.
Referenced by wrimsv2.tools.solutionRangeFinder.DetectorWorkflow.findAltSolutions().
Member Data Documentation
asfModel
MPModel wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.asfModel = null private
Definition at line 17 of file AltSolutionFinder.java.
Referenced by go().
id
String wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.id private
Definition at line 16 of file AltSolutionFinder.java.
Referenced by AltSolutionFinder(), and setLpsLoggingPath().
lpsDir
String wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.lpsDir = "" private
Definition at line 26 of file AltSolutionFinder.java.
Referenced by go().
lpsFileNamePrepend
String wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.lpsFileNamePrepend = "" private
Definition at line 27 of file AltSolutionFinder.java.
Referenced by go(), and setLpsLoggingPath().
lpsLogging
boolean wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.lpsLogging = false private
Definition at line 25 of file AltSolutionFinder.java.
reportVars
ArrayList<String> wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.reportVars private
Definition at line 20 of file AltSolutionFinder.java.
Referenced by AltSolutionFinder(), and go().
searchObjSign
int wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.searchObjSign private
Definition at line 19 of file AltSolutionFinder.java.
Referenced by AltSolutionFinder(), createObjFunc(), and go().
searchVars
List<String> wrimsv2.tools.solutionRangeFinder.AltSolutionFinder.searchVars private
Definition at line 18 of file AltSolutionFinder.java.
Referenced by AltSolutionFinder(), and go().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/tools/solutionRangeFinder/AltSolutionFinder.java