Wrims-engine: wrimsv2.external.Functionrequiredsac Class Reference
wrimsv2.external.Functionrequiredsac Class Reference
Public Member Functions
Functionrequiredsac ()
void execute (Stack stack)
double requiredsac (double target, double[] Qsac_prv, double Qsac_est, double[] Qexp_prv, double Qexp_est, double[] Qsjr_prv, double Qsjr_fut, double[] DXC_prv, double DXC_fut, double[] DICU_prv, double DICU_fut, double[] SMSCG_prv, double SMSCG_fut, double sacLoBound, double sacHiBound, int location, int ave_type, int month, int year)
Private Attributes
final boolean DEBUG = false
SalinitySurrogateManager ssm
Static Private Attributes
static int cpuTime =0
static int nCalls =0
Additional Inherited Members
Static Public Attributes inherited from wrimsv2.external.ExternalFunction
static String externalDir =FilePaths.mainDirectory+File.separator+"external"+File.separator
Detailed Description
Definition at line 8 of file Functionrequiredsac.java.
Constructor & Destructor Documentation
Functionrequiredsac()
wrimsv2.external.Functionrequiredsac.Functionrequiredsac ()
Definition at line 15 of file Functionrequiredsac.java.
References cpuTime, wrimsv2.components.TimeUsage.cpuTimeMap, wrimsv2.external.SalinitySurrogateSetup.getManager(), nCalls, wrimsv2.components.TimeUsage.nCallsMap, and ssm.
Member Function Documentation
execute()
void wrimsv2.external.Functionrequiredsac.execute (Stack stack)
Reimplemented from wrimsv2.external.ExternalFunction.
Definition at line 25 of file Functionrequiredsac.java.
References cpuTime, wrimsv2.components.TimeUsage.cpuTimeMap, nCalls, wrimsv2.components.TimeUsage.nCallsMap, and requiredsac().
requiredsac()
double wrimsv2.external.Functionrequiredsac.requiredsac (double target, double[] Qsac_prv, double Qsac_est, double[] Qexp_prv, double Qexp_est, double[] Qsjr_prv, double Qsjr_fut, double[] DXC_prv, double DXC_fut, double[] DICU_prv, double DICU_fut, double[] SMSCG_prv, double SMSCG_fut, double sacLoBound, double sacHiBound, int location, int ave_type, int month, int year)
Definition at line 114 of file Functionrequiredsac.java.
References ssm.
Referenced by execute().
Member Data Documentation
cpuTime
int wrimsv2.external.Functionrequiredsac.cpuTime =0 static private
Definition at line 10 of file Functionrequiredsac.java.
Referenced by Functionrequiredsac(), and execute().
DEBUG
final boolean wrimsv2.external.Functionrequiredsac.DEBUG = false private
Definition at line 9 of file Functionrequiredsac.java.
nCalls
int wrimsv2.external.Functionrequiredsac.nCalls =0 static private
Definition at line 11 of file Functionrequiredsac.java.
Referenced by Functionrequiredsac(), and execute().
ssm
SalinitySurrogateManager wrimsv2.external.Functionrequiredsac.ssm private
Definition at line 12 of file Functionrequiredsac.java.
Referenced by Functionrequiredsac(), and requiredsac().
The documentation for this class was generated from the following file:
wrims-core/src/main/java/wrimsv2/external/Functionrequiredsac.java