Wrims-engine: graalpy.JavaTest Interface Reference
graalpy.JavaTest Interface Reference
Public Member Functions
int getAbsoluteDifference (int x, int y)
String getText ()
void instanceTest ()
boolean isAnInteger (Object value)
Detailed Description
Definition at line 3 of file JavaTest.java.
Member Function Documentation
getAbsoluteDifference()
int graalpy.JavaTest.getAbsoluteDifference (int x, int y)
Referenced by graalpy.PythonTest.testRunJavaTest().
getText()
String graalpy.JavaTest.getText ()
Referenced by graalpy.PythonTest.testRunJavaTest().
instanceTest()
void graalpy.JavaTest.instanceTest ()
Referenced by graalpy.PythonTest.testRunJavaTest().
isAnInteger()
boolean graalpy.JavaTest.isAnInteger (Object value)
Referenced by graalpy.PythonTest.testRunJavaTest().
The documentation for this interface was generated from the following file:
wrims-core/src/test/java/graalpy/JavaTest.java